/* soapH.h
   Generated by gSOAP 2.8.8 from nx_soap.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef SOAP_TYPE_LONG64
#define SOAP_TYPE_LONG64 (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_LONG64(struct soap*, LONG64 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_LONG64(struct soap*, const char*, int, const LONG64 *, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_in_LONG64(struct soap*, const char*, LONG64 *, const char*);

#ifndef soap_write_LONG64
#define soap_write_LONG64(soap, data) ( soap_begin_send(soap) || soap_put_LONG64(soap, data, "long", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_LONG64(struct soap*, const LONG64 *, const char*, const char*);

#ifndef soap_read_LONG64
#define soap_read_LONG64(soap, data) ( soap_begin_recv(soap) || !soap_get_LONG64(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_get_LONG64(struct soap*, LONG64 *, const char*, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#endif

#ifndef SOAP_TYPE___ns3__GetListSchool
#define SOAP_TYPE___ns3__GetListSchool (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__GetListSchool(struct soap*, struct __ns3__GetListSchool *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__GetListSchool(struct soap*, const struct __ns3__GetListSchool *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__GetListSchool(struct soap*, const char*, int, const struct __ns3__GetListSchool *, const char*);
SOAP_FMAC3 struct __ns3__GetListSchool * SOAP_FMAC4 soap_in___ns3__GetListSchool(struct soap*, const char*, struct __ns3__GetListSchool *, const char*);

#ifndef soap_write___ns3__GetListSchool
#define soap_write___ns3__GetListSchool(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns3__GetListSchool(soap, data), 0) || soap_put___ns3__GetListSchool(soap, data, "-ns3:GetListSchool", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__GetListSchool(struct soap*, const struct __ns3__GetListSchool *, const char*, const char*);

#ifndef soap_read___ns3__GetListSchool
#define soap_read___ns3__GetListSchool(soap, data) ( soap_begin_recv(soap) || !soap_get___ns3__GetListSchool(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns3__GetListSchool * SOAP_FMAC4 soap_get___ns3__GetListSchool(struct soap*, struct __ns3__GetListSchool *, const char*, const char*);

#ifndef SOAP_TYPE___ns3__CheckPasswordByMemberSN
#define SOAP_TYPE___ns3__CheckPasswordByMemberSN (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__CheckPasswordByMemberSN(struct soap*, struct __ns3__CheckPasswordByMemberSN *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__CheckPasswordByMemberSN(struct soap*, const struct __ns3__CheckPasswordByMemberSN *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__CheckPasswordByMemberSN(struct soap*, const char*, int, const struct __ns3__CheckPasswordByMemberSN *, const char*);
SOAP_FMAC3 struct __ns3__CheckPasswordByMemberSN * SOAP_FMAC4 soap_in___ns3__CheckPasswordByMemberSN(struct soap*, const char*, struct __ns3__CheckPasswordByMemberSN *, const char*);

#ifndef soap_write___ns3__CheckPasswordByMemberSN
#define soap_write___ns3__CheckPasswordByMemberSN(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns3__CheckPasswordByMemberSN(soap, data), 0) || soap_put___ns3__CheckPasswordByMemberSN(soap, data, "-ns3:CheckPasswordByMemberSN", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__CheckPasswordByMemberSN(struct soap*, const struct __ns3__CheckPasswordByMemberSN *, const char*, const char*);

#ifndef soap_read___ns3__CheckPasswordByMemberSN
#define soap_read___ns3__CheckPasswordByMemberSN(soap, data) ( soap_begin_recv(soap) || !soap_get___ns3__CheckPasswordByMemberSN(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns3__CheckPasswordByMemberSN * SOAP_FMAC4 soap_get___ns3__CheckPasswordByMemberSN(struct soap*, struct __ns3__CheckPasswordByMemberSN *, const char*, const char*);

#ifndef SOAP_TYPE___ns3__CheckSameUser
#define SOAP_TYPE___ns3__CheckSameUser (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__CheckSameUser(struct soap*, struct __ns3__CheckSameUser *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__CheckSameUser(struct soap*, const struct __ns3__CheckSameUser *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__CheckSameUser(struct soap*, const char*, int, const struct __ns3__CheckSameUser *, const char*);
SOAP_FMAC3 struct __ns3__CheckSameUser * SOAP_FMAC4 soap_in___ns3__CheckSameUser(struct soap*, const char*, struct __ns3__CheckSameUser *, const char*);

#ifndef soap_write___ns3__CheckSameUser
#define soap_write___ns3__CheckSameUser(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns3__CheckSameUser(soap, data), 0) || soap_put___ns3__CheckSameUser(soap, data, "-ns3:CheckSameUser", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__CheckSameUser(struct soap*, const struct __ns3__CheckSameUser *, const char*, const char*);

#ifndef soap_read___ns3__CheckSameUser
#define soap_read___ns3__CheckSameUser(soap, data) ( soap_begin_recv(soap) || !soap_get___ns3__CheckSameUser(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns3__CheckSameUser * SOAP_FMAC4 soap_get___ns3__CheckSameUser(struct soap*, struct __ns3__CheckSameUser *, const char*, const char*);

#ifndef SOAP_TYPE___ns2__GetListSchool
#define SOAP_TYPE___ns2__GetListSchool (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns2__GetListSchool(struct soap*, struct __ns2__GetListSchool *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns2__GetListSchool(struct soap*, const struct __ns2__GetListSchool *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns2__GetListSchool(struct soap*, const char*, int, const struct __ns2__GetListSchool *, const char*);
SOAP_FMAC3 struct __ns2__GetListSchool * SOAP_FMAC4 soap_in___ns2__GetListSchool(struct soap*, const char*, struct __ns2__GetListSchool *, const char*);

#ifndef soap_write___ns2__GetListSchool
#define soap_write___ns2__GetListSchool(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns2__GetListSchool(soap, data), 0) || soap_put___ns2__GetListSchool(soap, data, "-ns2:GetListSchool", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns2__GetListSchool(struct soap*, const struct __ns2__GetListSchool *, const char*, const char*);

#ifndef soap_read___ns2__GetListSchool
#define soap_read___ns2__GetListSchool(soap, data) ( soap_begin_recv(soap) || !soap_get___ns2__GetListSchool(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns2__GetListSchool * SOAP_FMAC4 soap_get___ns2__GetListSchool(struct soap*, struct __ns2__GetListSchool *, const char*, const char*);

#ifndef SOAP_TYPE___ns2__CheckPasswordByMemberSN
#define SOAP_TYPE___ns2__CheckPasswordByMemberSN (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns2__CheckPasswordByMemberSN(struct soap*, struct __ns2__CheckPasswordByMemberSN *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns2__CheckPasswordByMemberSN(struct soap*, const struct __ns2__CheckPasswordByMemberSN *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns2__CheckPasswordByMemberSN(struct soap*, const char*, int, const struct __ns2__CheckPasswordByMemberSN *, const char*);
SOAP_FMAC3 struct __ns2__CheckPasswordByMemberSN * SOAP_FMAC4 soap_in___ns2__CheckPasswordByMemberSN(struct soap*, const char*, struct __ns2__CheckPasswordByMemberSN *, const char*);

#ifndef soap_write___ns2__CheckPasswordByMemberSN
#define soap_write___ns2__CheckPasswordByMemberSN(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns2__CheckPasswordByMemberSN(soap, data), 0) || soap_put___ns2__CheckPasswordByMemberSN(soap, data, "-ns2:CheckPasswordByMemberSN", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns2__CheckPasswordByMemberSN(struct soap*, const struct __ns2__CheckPasswordByMemberSN *, const char*, const char*);

#ifndef soap_read___ns2__CheckPasswordByMemberSN
#define soap_read___ns2__CheckPasswordByMemberSN(soap, data) ( soap_begin_recv(soap) || !soap_get___ns2__CheckPasswordByMemberSN(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns2__CheckPasswordByMemberSN * SOAP_FMAC4 soap_get___ns2__CheckPasswordByMemberSN(struct soap*, struct __ns2__CheckPasswordByMemberSN *, const char*, const char*);

#ifndef SOAP_TYPE___ns2__CheckSameUser
#define SOAP_TYPE___ns2__CheckSameUser (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns2__CheckSameUser(struct soap*, struct __ns2__CheckSameUser *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns2__CheckSameUser(struct soap*, const struct __ns2__CheckSameUser *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns2__CheckSameUser(struct soap*, const char*, int, const struct __ns2__CheckSameUser *, const char*);
SOAP_FMAC3 struct __ns2__CheckSameUser * SOAP_FMAC4 soap_in___ns2__CheckSameUser(struct soap*, const char*, struct __ns2__CheckSameUser *, const char*);

#ifndef soap_write___ns2__CheckSameUser
#define soap_write___ns2__CheckSameUser(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns2__CheckSameUser(soap, data), 0) || soap_put___ns2__CheckSameUser(soap, data, "-ns2:CheckSameUser", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns2__CheckSameUser(struct soap*, const struct __ns2__CheckSameUser *, const char*, const char*);

#ifndef soap_read___ns2__CheckSameUser
#define soap_read___ns2__CheckSameUser(soap, data) ( soap_begin_recv(soap) || !soap_get___ns2__CheckSameUser(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns2__CheckSameUser * SOAP_FMAC4 soap_get___ns2__CheckSameUser(struct soap*, struct __ns2__CheckSameUser *, const char*, const char*);

#ifndef SOAP_TYPE__ns1__GetListSchoolResponse
#define SOAP_TYPE__ns1__GetListSchoolResponse (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__GetListSchoolResponse(struct soap*, struct _ns1__GetListSchoolResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__GetListSchoolResponse(struct soap*, const struct _ns1__GetListSchoolResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetListSchoolResponse(struct soap*, const char*, int, const struct _ns1__GetListSchoolResponse *, const char*);
SOAP_FMAC3 struct _ns1__GetListSchoolResponse * SOAP_FMAC4 soap_in__ns1__GetListSchoolResponse(struct soap*, const char*, struct _ns1__GetListSchoolResponse *, const char*);

#ifndef soap_write__ns1__GetListSchoolResponse
#define soap_write__ns1__GetListSchoolResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize__ns1__GetListSchoolResponse(soap, data), 0) || soap_put__ns1__GetListSchoolResponse(soap, data, "ns1:GetListSchoolResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__GetListSchoolResponse(struct soap*, const struct _ns1__GetListSchoolResponse *, const char*, const char*);

#ifndef soap_read__ns1__GetListSchoolResponse
#define soap_read__ns1__GetListSchoolResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__GetListSchoolResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct _ns1__GetListSchoolResponse * SOAP_FMAC4 soap_get__ns1__GetListSchoolResponse(struct soap*, struct _ns1__GetListSchoolResponse *, const char*, const char*);

#ifndef SOAP_TYPE__ns1__GetListSchool
#define SOAP_TYPE__ns1__GetListSchool (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__GetListSchool(struct soap*, struct _ns1__GetListSchool *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__GetListSchool(struct soap*, const struct _ns1__GetListSchool *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetListSchool(struct soap*, const char*, int, const struct _ns1__GetListSchool *, const char*);
SOAP_FMAC3 struct _ns1__GetListSchool * SOAP_FMAC4 soap_in__ns1__GetListSchool(struct soap*, const char*, struct _ns1__GetListSchool *, const char*);

#ifndef soap_write__ns1__GetListSchool
#define soap_write__ns1__GetListSchool(soap, data) ( soap_begin_send(soap) || (soap_serialize__ns1__GetListSchool(soap, data), 0) || soap_put__ns1__GetListSchool(soap, data, "ns1:GetListSchool", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__GetListSchool(struct soap*, const struct _ns1__GetListSchool *, const char*, const char*);

#ifndef soap_read__ns1__GetListSchool
#define soap_read__ns1__GetListSchool(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__GetListSchool(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct _ns1__GetListSchool * SOAP_FMAC4 soap_get__ns1__GetListSchool(struct soap*, struct _ns1__GetListSchool *, const char*, const char*);

#ifndef SOAP_TYPE__ns1__CheckPasswordByMemberSNResponse
#define SOAP_TYPE__ns1__CheckPasswordByMemberSNResponse (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__CheckPasswordByMemberSNResponse(struct soap*, struct _ns1__CheckPasswordByMemberSNResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__CheckPasswordByMemberSNResponse(struct soap*, const struct _ns1__CheckPasswordByMemberSNResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__CheckPasswordByMemberSNResponse(struct soap*, const char*, int, const struct _ns1__CheckPasswordByMemberSNResponse *, const char*);
SOAP_FMAC3 struct _ns1__CheckPasswordByMemberSNResponse * SOAP_FMAC4 soap_in__ns1__CheckPasswordByMemberSNResponse(struct soap*, const char*, struct _ns1__CheckPasswordByMemberSNResponse *, const char*);

#ifndef soap_write__ns1__CheckPasswordByMemberSNResponse
#define soap_write__ns1__CheckPasswordByMemberSNResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize__ns1__CheckPasswordByMemberSNResponse(soap, data), 0) || soap_put__ns1__CheckPasswordByMemberSNResponse(soap, data, "ns1:CheckPasswordByMemberSNResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__CheckPasswordByMemberSNResponse(struct soap*, const struct _ns1__CheckPasswordByMemberSNResponse *, const char*, const char*);

#ifndef soap_read__ns1__CheckPasswordByMemberSNResponse
#define soap_read__ns1__CheckPasswordByMemberSNResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__CheckPasswordByMemberSNResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct _ns1__CheckPasswordByMemberSNResponse * SOAP_FMAC4 soap_get__ns1__CheckPasswordByMemberSNResponse(struct soap*, struct _ns1__CheckPasswordByMemberSNResponse *, const char*, const char*);

#ifndef SOAP_TYPE__ns1__CheckPasswordByMemberSN
#define SOAP_TYPE__ns1__CheckPasswordByMemberSN (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__CheckPasswordByMemberSN(struct soap*, struct _ns1__CheckPasswordByMemberSN *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__CheckPasswordByMemberSN(struct soap*, const struct _ns1__CheckPasswordByMemberSN *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__CheckPasswordByMemberSN(struct soap*, const char*, int, const struct _ns1__CheckPasswordByMemberSN *, const char*);
SOAP_FMAC3 struct _ns1__CheckPasswordByMemberSN * SOAP_FMAC4 soap_in__ns1__CheckPasswordByMemberSN(struct soap*, const char*, struct _ns1__CheckPasswordByMemberSN *, const char*);

#ifndef soap_write__ns1__CheckPasswordByMemberSN
#define soap_write__ns1__CheckPasswordByMemberSN(soap, data) ( soap_begin_send(soap) || (soap_serialize__ns1__CheckPasswordByMemberSN(soap, data), 0) || soap_put__ns1__CheckPasswordByMemberSN(soap, data, "ns1:CheckPasswordByMemberSN", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__CheckPasswordByMemberSN(struct soap*, const struct _ns1__CheckPasswordByMemberSN *, const char*, const char*);

#ifndef soap_read__ns1__CheckPasswordByMemberSN
#define soap_read__ns1__CheckPasswordByMemberSN(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__CheckPasswordByMemberSN(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct _ns1__CheckPasswordByMemberSN * SOAP_FMAC4 soap_get__ns1__CheckPasswordByMemberSN(struct soap*, struct _ns1__CheckPasswordByMemberSN *, const char*, const char*);

#ifndef SOAP_TYPE__ns1__CheckSameUserResponse
#define SOAP_TYPE__ns1__CheckSameUserResponse (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__CheckSameUserResponse(struct soap*, struct _ns1__CheckSameUserResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__CheckSameUserResponse(struct soap*, const struct _ns1__CheckSameUserResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__CheckSameUserResponse(struct soap*, const char*, int, const struct _ns1__CheckSameUserResponse *, const char*);
SOAP_FMAC3 struct _ns1__CheckSameUserResponse * SOAP_FMAC4 soap_in__ns1__CheckSameUserResponse(struct soap*, const char*, struct _ns1__CheckSameUserResponse *, const char*);

#ifndef soap_write__ns1__CheckSameUserResponse
#define soap_write__ns1__CheckSameUserResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize__ns1__CheckSameUserResponse(soap, data), 0) || soap_put__ns1__CheckSameUserResponse(soap, data, "ns1:CheckSameUserResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__CheckSameUserResponse(struct soap*, const struct _ns1__CheckSameUserResponse *, const char*, const char*);

#ifndef soap_read__ns1__CheckSameUserResponse
#define soap_read__ns1__CheckSameUserResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__CheckSameUserResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct _ns1__CheckSameUserResponse * SOAP_FMAC4 soap_get__ns1__CheckSameUserResponse(struct soap*, struct _ns1__CheckSameUserResponse *, const char*, const char*);

#ifndef SOAP_TYPE__ns1__CheckSameUser
#define SOAP_TYPE__ns1__CheckSameUser (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__CheckSameUser(struct soap*, struct _ns1__CheckSameUser *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__CheckSameUser(struct soap*, const struct _ns1__CheckSameUser *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__CheckSameUser(struct soap*, const char*, int, const struct _ns1__CheckSameUser *, const char*);
SOAP_FMAC3 struct _ns1__CheckSameUser * SOAP_FMAC4 soap_in__ns1__CheckSameUser(struct soap*, const char*, struct _ns1__CheckSameUser *, const char*);

#ifndef soap_write__ns1__CheckSameUser
#define soap_write__ns1__CheckSameUser(soap, data) ( soap_begin_send(soap) || (soap_serialize__ns1__CheckSameUser(soap, data), 0) || soap_put__ns1__CheckSameUser(soap, data, "ns1:CheckSameUser", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__CheckSameUser(struct soap*, const struct _ns1__CheckSameUser *, const char*, const char*);

#ifndef soap_read__ns1__CheckSameUser
#define soap_read__ns1__CheckSameUser(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__CheckSameUser(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct _ns1__CheckSameUser * SOAP_FMAC4 soap_get__ns1__CheckSameUser(struct soap*, struct _ns1__CheckSameUser *, const char*, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#endif

#ifndef SOAP_TYPE_PointerTo_ns1__GetListSchoolResponse
#define SOAP_TYPE_PointerTo_ns1__GetListSchoolResponse (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetListSchoolResponse(struct soap*, struct _ns1__GetListSchoolResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetListSchoolResponse(struct soap*, const char *, int, struct _ns1__GetListSchoolResponse *const*, const char *);
SOAP_FMAC3 struct _ns1__GetListSchoolResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetListSchoolResponse(struct soap*, const char*, struct _ns1__GetListSchoolResponse **, const char*);

#ifndef soap_write_PointerTo_ns1__GetListSchoolResponse
#define soap_write_PointerTo_ns1__GetListSchoolResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__GetListSchoolResponse(soap, data), 0) || soap_put_PointerTo_ns1__GetListSchoolResponse(soap, data, "ns1:GetListSchoolResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetListSchoolResponse(struct soap*, struct _ns1__GetListSchoolResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__GetListSchoolResponse
#define soap_read_PointerTo_ns1__GetListSchoolResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__GetListSchoolResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct _ns1__GetListSchoolResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetListSchoolResponse(struct soap*, struct _ns1__GetListSchoolResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetListSchool
#define SOAP_TYPE_PointerTo_ns1__GetListSchool (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetListSchool(struct soap*, struct _ns1__GetListSchool *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetListSchool(struct soap*, const char *, int, struct _ns1__GetListSchool *const*, const char *);
SOAP_FMAC3 struct _ns1__GetListSchool ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetListSchool(struct soap*, const char*, struct _ns1__GetListSchool **, const char*);

#ifndef soap_write_PointerTo_ns1__GetListSchool
#define soap_write_PointerTo_ns1__GetListSchool(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__GetListSchool(soap, data), 0) || soap_put_PointerTo_ns1__GetListSchool(soap, data, "ns1:GetListSchool", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetListSchool(struct soap*, struct _ns1__GetListSchool *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__GetListSchool
#define soap_read_PointerTo_ns1__GetListSchool(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__GetListSchool(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct _ns1__GetListSchool ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetListSchool(struct soap*, struct _ns1__GetListSchool **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__CheckPasswordByMemberSNResponse
#define SOAP_TYPE_PointerTo_ns1__CheckPasswordByMemberSNResponse (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__CheckPasswordByMemberSNResponse(struct soap*, struct _ns1__CheckPasswordByMemberSNResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__CheckPasswordByMemberSNResponse(struct soap*, const char *, int, struct _ns1__CheckPasswordByMemberSNResponse *const*, const char *);
SOAP_FMAC3 struct _ns1__CheckPasswordByMemberSNResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__CheckPasswordByMemberSNResponse(struct soap*, const char*, struct _ns1__CheckPasswordByMemberSNResponse **, const char*);

#ifndef soap_write_PointerTo_ns1__CheckPasswordByMemberSNResponse
#define soap_write_PointerTo_ns1__CheckPasswordByMemberSNResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__CheckPasswordByMemberSNResponse(soap, data), 0) || soap_put_PointerTo_ns1__CheckPasswordByMemberSNResponse(soap, data, "ns1:CheckPasswordByMemberSNResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__CheckPasswordByMemberSNResponse(struct soap*, struct _ns1__CheckPasswordByMemberSNResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__CheckPasswordByMemberSNResponse
#define soap_read_PointerTo_ns1__CheckPasswordByMemberSNResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__CheckPasswordByMemberSNResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct _ns1__CheckPasswordByMemberSNResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__CheckPasswordByMemberSNResponse(struct soap*, struct _ns1__CheckPasswordByMemberSNResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__CheckPasswordByMemberSN
#define SOAP_TYPE_PointerTo_ns1__CheckPasswordByMemberSN (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__CheckPasswordByMemberSN(struct soap*, struct _ns1__CheckPasswordByMemberSN *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__CheckPasswordByMemberSN(struct soap*, const char *, int, struct _ns1__CheckPasswordByMemberSN *const*, const char *);
SOAP_FMAC3 struct _ns1__CheckPasswordByMemberSN ** SOAP_FMAC4 soap_in_PointerTo_ns1__CheckPasswordByMemberSN(struct soap*, const char*, struct _ns1__CheckPasswordByMemberSN **, const char*);

#ifndef soap_write_PointerTo_ns1__CheckPasswordByMemberSN
#define soap_write_PointerTo_ns1__CheckPasswordByMemberSN(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__CheckPasswordByMemberSN(soap, data), 0) || soap_put_PointerTo_ns1__CheckPasswordByMemberSN(soap, data, "ns1:CheckPasswordByMemberSN", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__CheckPasswordByMemberSN(struct soap*, struct _ns1__CheckPasswordByMemberSN *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__CheckPasswordByMemberSN
#define soap_read_PointerTo_ns1__CheckPasswordByMemberSN(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__CheckPasswordByMemberSN(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct _ns1__CheckPasswordByMemberSN ** SOAP_FMAC4 soap_get_PointerTo_ns1__CheckPasswordByMemberSN(struct soap*, struct _ns1__CheckPasswordByMemberSN **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__CheckSameUserResponse
#define SOAP_TYPE_PointerTo_ns1__CheckSameUserResponse (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__CheckSameUserResponse(struct soap*, struct _ns1__CheckSameUserResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__CheckSameUserResponse(struct soap*, const char *, int, struct _ns1__CheckSameUserResponse *const*, const char *);
SOAP_FMAC3 struct _ns1__CheckSameUserResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__CheckSameUserResponse(struct soap*, const char*, struct _ns1__CheckSameUserResponse **, const char*);

#ifndef soap_write_PointerTo_ns1__CheckSameUserResponse
#define soap_write_PointerTo_ns1__CheckSameUserResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__CheckSameUserResponse(soap, data), 0) || soap_put_PointerTo_ns1__CheckSameUserResponse(soap, data, "ns1:CheckSameUserResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__CheckSameUserResponse(struct soap*, struct _ns1__CheckSameUserResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__CheckSameUserResponse
#define soap_read_PointerTo_ns1__CheckSameUserResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__CheckSameUserResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct _ns1__CheckSameUserResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__CheckSameUserResponse(struct soap*, struct _ns1__CheckSameUserResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__CheckSameUser
#define SOAP_TYPE_PointerTo_ns1__CheckSameUser (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__CheckSameUser(struct soap*, struct _ns1__CheckSameUser *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__CheckSameUser(struct soap*, const char *, int, struct _ns1__CheckSameUser *const*, const char *);
SOAP_FMAC3 struct _ns1__CheckSameUser ** SOAP_FMAC4 soap_in_PointerTo_ns1__CheckSameUser(struct soap*, const char*, struct _ns1__CheckSameUser **, const char*);

#ifndef soap_write_PointerTo_ns1__CheckSameUser
#define soap_write_PointerTo_ns1__CheckSameUser(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__CheckSameUser(soap, data), 0) || soap_put_PointerTo_ns1__CheckSameUser(soap, data, "ns1:CheckSameUser", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__CheckSameUser(struct soap*, struct _ns1__CheckSameUser *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__CheckSameUser
#define soap_read_PointerTo_ns1__CheckSameUser(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__CheckSameUser(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct _ns1__CheckSameUser ** SOAP_FMAC4 soap_get_PointerTo_ns1__CheckSameUser(struct soap*, struct _ns1__CheckSameUser **, const char*, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapH.h */
