/* soapClient.c
   Generated by gSOAP 2.8.8 from nx_soap.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.8 2013-03-27 23:21:54 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__CheckSameUser(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__CheckSameUser *ns1__CheckSameUser, struct _ns1__CheckSameUserResponse *ns1__CheckSameUserResponse)
{	struct __ns2__CheckSameUser soap_tmp___ns2__CheckSameUser;
	if (!soap_endpoint)
		soap_endpoint = "http://api.user.nexon.com/soap/elswordgame.asmx";
	if (!soap_action)
		soap_action = "http://tempuri.org/CheckSameUser";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__CheckSameUser.ns1__CheckSameUser = ns1__CheckSameUser;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__CheckSameUser(soap, &soap_tmp___ns2__CheckSameUser);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__CheckSameUser(soap, &soap_tmp___ns2__CheckSameUser, "-ns2:CheckSameUser", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__CheckSameUser(soap, &soap_tmp___ns2__CheckSameUser, "-ns2:CheckSameUser", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__CheckSameUserResponse)
		return soap_closesock(soap);
	soap_default__ns1__CheckSameUserResponse(soap, ns1__CheckSameUserResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__CheckSameUserResponse(soap, ns1__CheckSameUserResponse, "ns1:CheckSameUserResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__CheckPasswordByMemberSN(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__CheckPasswordByMemberSN *ns1__CheckPasswordByMemberSN, struct _ns1__CheckPasswordByMemberSNResponse *ns1__CheckPasswordByMemberSNResponse)
{	struct __ns2__CheckPasswordByMemberSN soap_tmp___ns2__CheckPasswordByMemberSN;
	if (!soap_endpoint)
		soap_endpoint = "http://api.user.nexon.com/soap/elswordgame.asmx";
	if (!soap_action)
		soap_action = "http://tempuri.org/CheckPasswordByMemberSN";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__CheckPasswordByMemberSN.ns1__CheckPasswordByMemberSN = ns1__CheckPasswordByMemberSN;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__CheckPasswordByMemberSN(soap, &soap_tmp___ns2__CheckPasswordByMemberSN);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__CheckPasswordByMemberSN(soap, &soap_tmp___ns2__CheckPasswordByMemberSN, "-ns2:CheckPasswordByMemberSN", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__CheckPasswordByMemberSN(soap, &soap_tmp___ns2__CheckPasswordByMemberSN, "-ns2:CheckPasswordByMemberSN", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__CheckPasswordByMemberSNResponse)
		return soap_closesock(soap);
	soap_default__ns1__CheckPasswordByMemberSNResponse(soap, ns1__CheckPasswordByMemberSNResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__CheckPasswordByMemberSNResponse(soap, ns1__CheckPasswordByMemberSNResponse, "ns1:CheckPasswordByMemberSNResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__GetListSchool(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__GetListSchool *ns1__GetListSchool, struct _ns1__GetListSchoolResponse *ns1__GetListSchoolResponse)
{	struct __ns2__GetListSchool soap_tmp___ns2__GetListSchool;
	if (!soap_endpoint)
		soap_endpoint = "http://api.user.nexon.com/soap/elswordgame.asmx";
	if (!soap_action)
		soap_action = "http://tempuri.org/GetListSchool";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__GetListSchool.ns1__GetListSchool = ns1__GetListSchool;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__GetListSchool(soap, &soap_tmp___ns2__GetListSchool);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__GetListSchool(soap, &soap_tmp___ns2__GetListSchool, "-ns2:GetListSchool", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__GetListSchool(soap, &soap_tmp___ns2__GetListSchool, "-ns2:GetListSchool", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetListSchoolResponse)
		return soap_closesock(soap);
	soap_default__ns1__GetListSchoolResponse(soap, ns1__GetListSchoolResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__GetListSchoolResponse(soap, ns1__GetListSchoolResponse, "ns1:GetListSchoolResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns3__CheckSameUser(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__CheckSameUser *ns1__CheckSameUser, struct _ns1__CheckSameUserResponse *ns1__CheckSameUserResponse)
{	struct __ns3__CheckSameUser soap_tmp___ns3__CheckSameUser;
	if (!soap_endpoint)
		soap_endpoint = "http://api.user.nexon.com/soap/elswordgame.asmx";
	if (!soap_action)
		soap_action = "http://tempuri.org/CheckSameUser";
	soap->encodingStyle = NULL;
	soap_tmp___ns3__CheckSameUser.ns1__CheckSameUser = ns1__CheckSameUser;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns3__CheckSameUser(soap, &soap_tmp___ns3__CheckSameUser);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__CheckSameUser(soap, &soap_tmp___ns3__CheckSameUser, "-ns3:CheckSameUser", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__CheckSameUser(soap, &soap_tmp___ns3__CheckSameUser, "-ns3:CheckSameUser", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__CheckSameUserResponse)
		return soap_closesock(soap);
	soap_default__ns1__CheckSameUserResponse(soap, ns1__CheckSameUserResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__CheckSameUserResponse(soap, ns1__CheckSameUserResponse, "ns1:CheckSameUserResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns3__CheckPasswordByMemberSN(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__CheckPasswordByMemberSN *ns1__CheckPasswordByMemberSN, struct _ns1__CheckPasswordByMemberSNResponse *ns1__CheckPasswordByMemberSNResponse)
{	struct __ns3__CheckPasswordByMemberSN soap_tmp___ns3__CheckPasswordByMemberSN;
	if (!soap_endpoint)
		soap_endpoint = "http://api.user.nexon.com/soap/elswordgame.asmx";
	if (!soap_action)
		soap_action = "http://tempuri.org/CheckPasswordByMemberSN";
	soap->encodingStyle = NULL;
	soap_tmp___ns3__CheckPasswordByMemberSN.ns1__CheckPasswordByMemberSN = ns1__CheckPasswordByMemberSN;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns3__CheckPasswordByMemberSN(soap, &soap_tmp___ns3__CheckPasswordByMemberSN);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__CheckPasswordByMemberSN(soap, &soap_tmp___ns3__CheckPasswordByMemberSN, "-ns3:CheckPasswordByMemberSN", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__CheckPasswordByMemberSN(soap, &soap_tmp___ns3__CheckPasswordByMemberSN, "-ns3:CheckPasswordByMemberSN", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__CheckPasswordByMemberSNResponse)
		return soap_closesock(soap);
	soap_default__ns1__CheckPasswordByMemberSNResponse(soap, ns1__CheckPasswordByMemberSNResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__CheckPasswordByMemberSNResponse(soap, ns1__CheckPasswordByMemberSNResponse, "ns1:CheckPasswordByMemberSNResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns3__GetListSchool(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__GetListSchool *ns1__GetListSchool, struct _ns1__GetListSchoolResponse *ns1__GetListSchoolResponse)
{	struct __ns3__GetListSchool soap_tmp___ns3__GetListSchool;
	if (!soap_endpoint)
		soap_endpoint = "http://api.user.nexon.com/soap/elswordgame.asmx";
	if (!soap_action)
		soap_action = "http://tempuri.org/GetListSchool";
	soap->encodingStyle = NULL;
	soap_tmp___ns3__GetListSchool.ns1__GetListSchool = ns1__GetListSchool;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns3__GetListSchool(soap, &soap_tmp___ns3__GetListSchool);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__GetListSchool(soap, &soap_tmp___ns3__GetListSchool, "-ns3:GetListSchool", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__GetListSchool(soap, &soap_tmp___ns3__GetListSchool, "-ns3:GetListSchool", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetListSchoolResponse)
		return soap_closesock(soap);
	soap_default__ns1__GetListSchoolResponse(soap, ns1__GetListSchoolResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__GetListSchoolResponse(soap, ns1__GetListSchoolResponse, "ns1:GetListSchoolResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
