/* soapElswordGameSoapProxy.h
   Generated by gSOAP 2.8.15 from nx_soap.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapElswordGameSoapProxy_H
#define soapElswordGameSoapProxy_H
#include "soapH.h"

class SOAP_CMAC ElswordGameSoapProxy : public soap
{ public:
	/// Endpoint URL of service 'ElswordGameSoapProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	ElswordGameSoapProxy();
	/// Construct from another engine state
	ElswordGameSoapProxy(const struct soap&);
	/// Constructor with endpoint URL
	ElswordGameSoapProxy(const char *url);
	/// Constructor with engine input+output mode control
	ElswordGameSoapProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	ElswordGameSoapProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	ElswordGameSoapProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~ElswordGameSoapProxy();
	/// Initializer used by constructors
	virtual	void ElswordGameSoapProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'CheckSameUser' (returns error code or SOAP_OK)
	virtual	int CheckSameUser(_ns1__CheckSameUser *ns1__CheckSameUser, _ns1__CheckSameUserResponse *ns1__CheckSameUserResponse) { return this->CheckSameUser(NULL, NULL, ns1__CheckSameUser, ns1__CheckSameUserResponse); }
	virtual	int CheckSameUser(const char *endpoint, const char *soap_action, _ns1__CheckSameUser *ns1__CheckSameUser, _ns1__CheckSameUserResponse *ns1__CheckSameUserResponse);

	/// Web service operation 'CheckPasswordByMemberSN' (returns error code or SOAP_OK)
	virtual	int CheckPasswordByMemberSN(_ns1__CheckPasswordByMemberSN *ns1__CheckPasswordByMemberSN, _ns1__CheckPasswordByMemberSNResponse *ns1__CheckPasswordByMemberSNResponse) { return this->CheckPasswordByMemberSN(NULL, NULL, ns1__CheckPasswordByMemberSN, ns1__CheckPasswordByMemberSNResponse); }
	virtual	int CheckPasswordByMemberSN(const char *endpoint, const char *soap_action, _ns1__CheckPasswordByMemberSN *ns1__CheckPasswordByMemberSN, _ns1__CheckPasswordByMemberSNResponse *ns1__CheckPasswordByMemberSNResponse);

	/// Web service operation 'GetListSchool' (returns error code or SOAP_OK)
	virtual	int GetListSchool(_ns1__GetListSchool *ns1__GetListSchool, _ns1__GetListSchoolResponse *ns1__GetListSchoolResponse) { return this->GetListSchool(NULL, NULL, ns1__GetListSchool, ns1__GetListSchoolResponse); }
	virtual	int GetListSchool(const char *endpoint, const char *soap_action, _ns1__GetListSchool *ns1__GetListSchool, _ns1__GetListSchoolResponse *ns1__GetListSchoolResponse);

	/// Web service operation 'CheckSameUser' (returns error code or SOAP_OK)
	virtual	int CheckSameUser_(_ns1__CheckSameUser *ns1__CheckSameUser, _ns1__CheckSameUserResponse *ns1__CheckSameUserResponse) { return this->CheckSameUser_(NULL, NULL, ns1__CheckSameUser, ns1__CheckSameUserResponse); }
	virtual	int CheckSameUser_(const char *endpoint, const char *soap_action, _ns1__CheckSameUser *ns1__CheckSameUser, _ns1__CheckSameUserResponse *ns1__CheckSameUserResponse);

	/// Web service operation 'CheckPasswordByMemberSN' (returns error code or SOAP_OK)
	virtual	int CheckPasswordByMemberSN_(_ns1__CheckPasswordByMemberSN *ns1__CheckPasswordByMemberSN, _ns1__CheckPasswordByMemberSNResponse *ns1__CheckPasswordByMemberSNResponse) { return this->CheckPasswordByMemberSN_(NULL, NULL, ns1__CheckPasswordByMemberSN, ns1__CheckPasswordByMemberSNResponse); }
	virtual	int CheckPasswordByMemberSN_(const char *endpoint, const char *soap_action, _ns1__CheckPasswordByMemberSN *ns1__CheckPasswordByMemberSN, _ns1__CheckPasswordByMemberSNResponse *ns1__CheckPasswordByMemberSNResponse);

	/// Web service operation 'GetListSchool' (returns error code or SOAP_OK)
	virtual	int GetListSchool_(_ns1__GetListSchool *ns1__GetListSchool, _ns1__GetListSchoolResponse *ns1__GetListSchoolResponse) { return this->GetListSchool_(NULL, NULL, ns1__GetListSchool, ns1__GetListSchoolResponse); }
	virtual	int GetListSchool_(const char *endpoint, const char *soap_action, _ns1__GetListSchool *ns1__GetListSchool, _ns1__GetListSchoolResponse *ns1__GetListSchoolResponse);

	/// Web service operation 'SelectCashCouponFromCouponBoxByNexonID' (returns error code or SOAP_OK)
	virtual	int SelectCashCouponFromCouponBoxByNexonID(_ns1__SelectCashCouponFromCouponBoxByNexonID *ns1__SelectCashCouponFromCouponBoxByNexonID, _ns1__SelectCashCouponFromCouponBoxByNexonIDResponse *ns1__SelectCashCouponFromCouponBoxByNexonIDResponse) { return this->SelectCashCouponFromCouponBoxByNexonID(NULL, NULL, ns1__SelectCashCouponFromCouponBoxByNexonID, ns1__SelectCashCouponFromCouponBoxByNexonIDResponse); }
	virtual	int SelectCashCouponFromCouponBoxByNexonID(const char *endpoint, const char *soap_action, _ns1__SelectCashCouponFromCouponBoxByNexonID *ns1__SelectCashCouponFromCouponBoxByNexonID, _ns1__SelectCashCouponFromCouponBoxByNexonIDResponse *ns1__SelectCashCouponFromCouponBoxByNexonIDResponse);

	/// Web service operation 'SelectItemCouponFromCouponBoxByNexonID' (returns error code or SOAP_OK)
	virtual	int SelectItemCouponFromCouponBoxByNexonID(_ns1__SelectItemCouponFromCouponBoxByNexonID *ns1__SelectItemCouponFromCouponBoxByNexonID, _ns1__SelectItemCouponFromCouponBoxByNexonIDResponse *ns1__SelectItemCouponFromCouponBoxByNexonIDResponse) { return this->SelectItemCouponFromCouponBoxByNexonID(NULL, NULL, ns1__SelectItemCouponFromCouponBoxByNexonID, ns1__SelectItemCouponFromCouponBoxByNexonIDResponse); }
	virtual	int SelectItemCouponFromCouponBoxByNexonID(const char *endpoint, const char *soap_action, _ns1__SelectItemCouponFromCouponBoxByNexonID *ns1__SelectItemCouponFromCouponBoxByNexonID, _ns1__SelectItemCouponFromCouponBoxByNexonIDResponse *ns1__SelectItemCouponFromCouponBoxByNexonIDResponse);

	/// Web service operation 'AddCouponBoxByCouponPinByNexonId' (returns error code or SOAP_OK)
	virtual	int AddCouponBoxByCouponPinByNexonId(_ns1__AddCouponBoxByCouponPinByNexonId *ns1__AddCouponBoxByCouponPinByNexonId, _ns1__AddCouponBoxByCouponPinByNexonIdResponse *ns1__AddCouponBoxByCouponPinByNexonIdResponse) { return this->AddCouponBoxByCouponPinByNexonId(NULL, NULL, ns1__AddCouponBoxByCouponPinByNexonId, ns1__AddCouponBoxByCouponPinByNexonIdResponse); }
	virtual	int AddCouponBoxByCouponPinByNexonId(const char *endpoint, const char *soap_action, _ns1__AddCouponBoxByCouponPinByNexonId *ns1__AddCouponBoxByCouponPinByNexonId, _ns1__AddCouponBoxByCouponPinByNexonIdResponse *ns1__AddCouponBoxByCouponPinByNexonIdResponse);

	/// Web service operation 'CheckAddCouponBoxByCouponPinByNexonId' (returns error code or SOAP_OK)
	virtual	int CheckAddCouponBoxByCouponPinByNexonId(_ns1__CheckAddCouponBoxByCouponPinByNexonId *ns1__CheckAddCouponBoxByCouponPinByNexonId, _ns1__CheckAddCouponBoxByCouponPinByNexonIdResponse *ns1__CheckAddCouponBoxByCouponPinByNexonIdResponse) { return this->CheckAddCouponBoxByCouponPinByNexonId(NULL, NULL, ns1__CheckAddCouponBoxByCouponPinByNexonId, ns1__CheckAddCouponBoxByCouponPinByNexonIdResponse); }
	virtual	int CheckAddCouponBoxByCouponPinByNexonId(const char *endpoint, const char *soap_action, _ns1__CheckAddCouponBoxByCouponPinByNexonId *ns1__CheckAddCouponBoxByCouponPinByNexonId, _ns1__CheckAddCouponBoxByCouponPinByNexonIdResponse *ns1__CheckAddCouponBoxByCouponPinByNexonIdResponse);

	/// Web service operation 'SelectDiscountCouponFromCouponBoxByNexonIDByItemCode' (returns error code or SOAP_OK)
	virtual	int SelectDiscountCouponFromCouponBoxByNexonIDByItemCode(_ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemCode *ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemCode, _ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemCodeResponse *ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemCodeResponse) { return this->SelectDiscountCouponFromCouponBoxByNexonIDByItemCode(NULL, NULL, ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemCode, ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemCodeResponse); }
	virtual	int SelectDiscountCouponFromCouponBoxByNexonIDByItemCode(const char *endpoint, const char *soap_action, _ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemCode *ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemCode, _ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemCodeResponse *ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemCodeResponse);

	/// Web service operation 'SelectDiscountCouponFromCouponBoxByNexonIDByItemList' (returns error code or SOAP_OK)
	virtual	int SelectDiscountCouponFromCouponBoxByNexonIDByItemList(_ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemList *ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemList, _ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemListResponse *ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemListResponse) { return this->SelectDiscountCouponFromCouponBoxByNexonIDByItemList(NULL, NULL, ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemList, ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemListResponse); }
	virtual	int SelectDiscountCouponFromCouponBoxByNexonIDByItemList(const char *endpoint, const char *soap_action, _ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemList *ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemList, _ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemListResponse *ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemListResponse);

	/// Web service operation 'SelectDiscountCouponFromCouponBoxByCharacterIDByItemCode' (returns error code or SOAP_OK)
	virtual	int SelectDiscountCouponFromCouponBoxByCharacterIDByItemCode(_ns1__SelectDiscountCouponFromCouponBoxByCharacterIDByItemCode *ns1__SelectDiscountCouponFromCouponBoxByCharacterIDByItemCode, _ns1__SelectDiscountCouponFromCouponBoxByCharacterIDByItemCodeResponse *ns1__SelectDiscountCouponFromCouponBoxByCharacterIDByItemCodeResponse) { return this->SelectDiscountCouponFromCouponBoxByCharacterIDByItemCode(NULL, NULL, ns1__SelectDiscountCouponFromCouponBoxByCharacterIDByItemCode, ns1__SelectDiscountCouponFromCouponBoxByCharacterIDByItemCodeResponse); }
	virtual	int SelectDiscountCouponFromCouponBoxByCharacterIDByItemCode(const char *endpoint, const char *soap_action, _ns1__SelectDiscountCouponFromCouponBoxByCharacterIDByItemCode *ns1__SelectDiscountCouponFromCouponBoxByCharacterIDByItemCode, _ns1__SelectDiscountCouponFromCouponBoxByCharacterIDByItemCodeResponse *ns1__SelectDiscountCouponFromCouponBoxByCharacterIDByItemCodeResponse);

	/// Web service operation 'SelectCouponBoxByCharacterIDForUser' (returns error code or SOAP_OK)
	virtual	int SelectCouponBoxByCharacterIDForUser(_ns1__SelectCouponBoxByCharacterIDForUser *ns1__SelectCouponBoxByCharacterIDForUser, _ns1__SelectCouponBoxByCharacterIDForUserResponse *ns1__SelectCouponBoxByCharacterIDForUserResponse) { return this->SelectCouponBoxByCharacterIDForUser(NULL, NULL, ns1__SelectCouponBoxByCharacterIDForUser, ns1__SelectCouponBoxByCharacterIDForUserResponse); }
	virtual	int SelectCouponBoxByCharacterIDForUser(const char *endpoint, const char *soap_action, _ns1__SelectCouponBoxByCharacterIDForUser *ns1__SelectCouponBoxByCharacterIDForUser, _ns1__SelectCouponBoxByCharacterIDForUserResponse *ns1__SelectCouponBoxByCharacterIDForUserResponse);

	/// Web service operation 'SelectCouponBoxByAccountIDForUser' (returns error code or SOAP_OK)
	virtual	int SelectCouponBoxByAccountIDForUser(_ns1__SelectCouponBoxByAccountIDForUser *ns1__SelectCouponBoxByAccountIDForUser, _ns1__SelectCouponBoxByAccountIDForUserResponse *ns1__SelectCouponBoxByAccountIDForUserResponse) { return this->SelectCouponBoxByAccountIDForUser(NULL, NULL, ns1__SelectCouponBoxByAccountIDForUser, ns1__SelectCouponBoxByAccountIDForUserResponse); }
	virtual	int SelectCouponBoxByAccountIDForUser(const char *endpoint, const char *soap_action, _ns1__SelectCouponBoxByAccountIDForUser *ns1__SelectCouponBoxByAccountIDForUser, _ns1__SelectCouponBoxByAccountIDForUserResponse *ns1__SelectCouponBoxByAccountIDForUserResponse);

	/// Web service operation 'SelectCouponBoxListByNexonIDForUser' (returns error code or SOAP_OK)
	virtual	int SelectCouponBoxListByNexonIDForUser(_ns1__SelectCouponBoxListByNexonIDForUser *ns1__SelectCouponBoxListByNexonIDForUser, _ns1__SelectCouponBoxListByNexonIDForUserResponse *ns1__SelectCouponBoxListByNexonIDForUserResponse) { return this->SelectCouponBoxListByNexonIDForUser(NULL, NULL, ns1__SelectCouponBoxListByNexonIDForUser, ns1__SelectCouponBoxListByNexonIDForUserResponse); }
	virtual	int SelectCouponBoxListByNexonIDForUser(const char *endpoint, const char *soap_action, _ns1__SelectCouponBoxListByNexonIDForUser *ns1__SelectCouponBoxListByNexonIDForUser, _ns1__SelectCouponBoxListByNexonIDForUserResponse *ns1__SelectCouponBoxListByNexonIDForUserResponse);

	/// Web service operation 'SelectCouponBoxUsedListByNexonIDForUser' (returns error code or SOAP_OK)
	virtual	int SelectCouponBoxUsedListByNexonIDForUser(_ns1__SelectCouponBoxUsedListByNexonIDForUser *ns1__SelectCouponBoxUsedListByNexonIDForUser, _ns1__SelectCouponBoxUsedListByNexonIDForUserResponse *ns1__SelectCouponBoxUsedListByNexonIDForUserResponse) { return this->SelectCouponBoxUsedListByNexonIDForUser(NULL, NULL, ns1__SelectCouponBoxUsedListByNexonIDForUser, ns1__SelectCouponBoxUsedListByNexonIDForUserResponse); }
	virtual	int SelectCouponBoxUsedListByNexonIDForUser(const char *endpoint, const char *soap_action, _ns1__SelectCouponBoxUsedListByNexonIDForUser *ns1__SelectCouponBoxUsedListByNexonIDForUser, _ns1__SelectCouponBoxUsedListByNexonIDForUserResponse *ns1__SelectCouponBoxUsedListByNexonIDForUserResponse);

	/// Web service operation 'GetCouponBoxListCountByNexonIDForUser' (returns error code or SOAP_OK)
	virtual	int GetCouponBoxListCountByNexonIDForUser(_ns1__GetCouponBoxListCountByNexonIDForUser *ns1__GetCouponBoxListCountByNexonIDForUser, _ns1__GetCouponBoxListCountByNexonIDForUserResponse *ns1__GetCouponBoxListCountByNexonIDForUserResponse) { return this->GetCouponBoxListCountByNexonIDForUser(NULL, NULL, ns1__GetCouponBoxListCountByNexonIDForUser, ns1__GetCouponBoxListCountByNexonIDForUserResponse); }
	virtual	int GetCouponBoxListCountByNexonIDForUser(const char *endpoint, const char *soap_action, _ns1__GetCouponBoxListCountByNexonIDForUser *ns1__GetCouponBoxListCountByNexonIDForUser, _ns1__GetCouponBoxListCountByNexonIDForUserResponse *ns1__GetCouponBoxListCountByNexonIDForUserResponse);

	/// Web service operation 'GetCouponBoxUsedListCountByNexonIDForUser' (returns error code or SOAP_OK)
	virtual	int GetCouponBoxUsedListCountByNexonIDForUser(_ns1__GetCouponBoxUsedListCountByNexonIDForUser *ns1__GetCouponBoxUsedListCountByNexonIDForUser, _ns1__GetCouponBoxUsedListCountByNexonIDForUserResponse *ns1__GetCouponBoxUsedListCountByNexonIDForUserResponse) { return this->GetCouponBoxUsedListCountByNexonIDForUser(NULL, NULL, ns1__GetCouponBoxUsedListCountByNexonIDForUser, ns1__GetCouponBoxUsedListCountByNexonIDForUserResponse); }
	virtual	int GetCouponBoxUsedListCountByNexonIDForUser(const char *endpoint, const char *soap_action, _ns1__GetCouponBoxUsedListCountByNexonIDForUser *ns1__GetCouponBoxUsedListCountByNexonIDForUser, _ns1__GetCouponBoxUsedListCountByNexonIDForUserResponse *ns1__GetCouponBoxUsedListCountByNexonIDForUserResponse);

	/// Web service operation 'SelectCouponBoxTargetItemList' (returns error code or SOAP_OK)
	virtual	int SelectCouponBoxTargetItemList(_ns1__SelectCouponBoxTargetItemList *ns1__SelectCouponBoxTargetItemList, _ns1__SelectCouponBoxTargetItemListResponse *ns1__SelectCouponBoxTargetItemListResponse) { return this->SelectCouponBoxTargetItemList(NULL, NULL, ns1__SelectCouponBoxTargetItemList, ns1__SelectCouponBoxTargetItemListResponse); }
	virtual	int SelectCouponBoxTargetItemList(const char *endpoint, const char *soap_action, _ns1__SelectCouponBoxTargetItemList *ns1__SelectCouponBoxTargetItemList, _ns1__SelectCouponBoxTargetItemListResponse *ns1__SelectCouponBoxTargetItemListResponse);

	/// Web service operation 'GetCouponBoxTargetItemListCount' (returns error code or SOAP_OK)
	virtual	int GetCouponBoxTargetItemListCount(_ns1__GetCouponBoxTargetItemListCount *ns1__GetCouponBoxTargetItemListCount, _ns1__GetCouponBoxTargetItemListCountResponse *ns1__GetCouponBoxTargetItemListCountResponse) { return this->GetCouponBoxTargetItemListCount(NULL, NULL, ns1__GetCouponBoxTargetItemListCount, ns1__GetCouponBoxTargetItemListCountResponse); }
	virtual	int GetCouponBoxTargetItemListCount(const char *endpoint, const char *soap_action, _ns1__GetCouponBoxTargetItemListCount *ns1__GetCouponBoxTargetItemListCount, _ns1__GetCouponBoxTargetItemListCountResponse *ns1__GetCouponBoxTargetItemListCountResponse);

	/// Web service operation 'CheckCashCouponFromCouponBox' (returns error code or SOAP_OK)
	virtual	int CheckCashCouponFromCouponBox(_ns1__CheckCashCouponFromCouponBox *ns1__CheckCashCouponFromCouponBox, _ns1__CheckCashCouponFromCouponBoxResponse *ns1__CheckCashCouponFromCouponBoxResponse) { return this->CheckCashCouponFromCouponBox(NULL, NULL, ns1__CheckCashCouponFromCouponBox, ns1__CheckCashCouponFromCouponBoxResponse); }
	virtual	int CheckCashCouponFromCouponBox(const char *endpoint, const char *soap_action, _ns1__CheckCashCouponFromCouponBox *ns1__CheckCashCouponFromCouponBox, _ns1__CheckCashCouponFromCouponBoxResponse *ns1__CheckCashCouponFromCouponBoxResponse);

	/// Web service operation 'UseCashCouponFromCouponBox' (returns error code or SOAP_OK)
	virtual	int UseCashCouponFromCouponBox(_ns1__UseCashCouponFromCouponBox *ns1__UseCashCouponFromCouponBox, _ns1__UseCashCouponFromCouponBoxResponse *ns1__UseCashCouponFromCouponBoxResponse) { return this->UseCashCouponFromCouponBox(NULL, NULL, ns1__UseCashCouponFromCouponBox, ns1__UseCashCouponFromCouponBoxResponse); }
	virtual	int UseCashCouponFromCouponBox(const char *endpoint, const char *soap_action, _ns1__UseCashCouponFromCouponBox *ns1__UseCashCouponFromCouponBox, _ns1__UseCashCouponFromCouponBoxResponse *ns1__UseCashCouponFromCouponBoxResponse);

	/// Web service operation 'RollbackCashCouponFromCouponBox' (returns error code or SOAP_OK)
	virtual	int RollbackCashCouponFromCouponBox(_ns1__RollbackCashCouponFromCouponBox *ns1__RollbackCashCouponFromCouponBox, _ns1__RollbackCashCouponFromCouponBoxResponse *ns1__RollbackCashCouponFromCouponBoxResponse) { return this->RollbackCashCouponFromCouponBox(NULL, NULL, ns1__RollbackCashCouponFromCouponBox, ns1__RollbackCashCouponFromCouponBoxResponse); }
	virtual	int RollbackCashCouponFromCouponBox(const char *endpoint, const char *soap_action, _ns1__RollbackCashCouponFromCouponBox *ns1__RollbackCashCouponFromCouponBox, _ns1__RollbackCashCouponFromCouponBoxResponse *ns1__RollbackCashCouponFromCouponBoxResponse);

	/// Web service operation 'CheckCashCoupon' (returns error code or SOAP_OK)
	virtual	int CheckCashCoupon(_ns1__CheckCashCoupon *ns1__CheckCashCoupon, _ns1__CheckCashCouponResponse *ns1__CheckCashCouponResponse) { return this->CheckCashCoupon(NULL, NULL, ns1__CheckCashCoupon, ns1__CheckCashCouponResponse); }
	virtual	int CheckCashCoupon(const char *endpoint, const char *soap_action, _ns1__CheckCashCoupon *ns1__CheckCashCoupon, _ns1__CheckCashCouponResponse *ns1__CheckCashCouponResponse);

	/// Web service operation 'UseCashCoupon' (returns error code or SOAP_OK)
	virtual	int UseCashCoupon(_ns1__UseCashCoupon *ns1__UseCashCoupon, _ns1__UseCashCouponResponse *ns1__UseCashCouponResponse) { return this->UseCashCoupon(NULL, NULL, ns1__UseCashCoupon, ns1__UseCashCouponResponse); }
	virtual	int UseCashCoupon(const char *endpoint, const char *soap_action, _ns1__UseCashCoupon *ns1__UseCashCoupon, _ns1__UseCashCouponResponse *ns1__UseCashCouponResponse);

	/// Web service operation 'RollbackCashCoupon' (returns error code or SOAP_OK)
	virtual	int RollbackCashCoupon(_ns1__RollbackCashCoupon *ns1__RollbackCashCoupon, _ns1__RollbackCashCouponResponse *ns1__RollbackCashCouponResponse) { return this->RollbackCashCoupon(NULL, NULL, ns1__RollbackCashCoupon, ns1__RollbackCashCouponResponse); }
	virtual	int RollbackCashCoupon(const char *endpoint, const char *soap_action, _ns1__RollbackCashCoupon *ns1__RollbackCashCoupon, _ns1__RollbackCashCouponResponse *ns1__RollbackCashCouponResponse);

	/// Web service operation 'ActivationCashCoupon' (returns error code or SOAP_OK)
	virtual	int ActivationCashCoupon(_ns1__ActivationCashCoupon *ns1__ActivationCashCoupon, _ns1__ActivationCashCouponResponse *ns1__ActivationCashCouponResponse) { return this->ActivationCashCoupon(NULL, NULL, ns1__ActivationCashCoupon, ns1__ActivationCashCouponResponse); }
	virtual	int ActivationCashCoupon(const char *endpoint, const char *soap_action, _ns1__ActivationCashCoupon *ns1__ActivationCashCoupon, _ns1__ActivationCashCouponResponse *ns1__ActivationCashCouponResponse);

	/// Web service operation 'ReverseActivationCashCoupon' (returns error code or SOAP_OK)
	virtual	int ReverseActivationCashCoupon(_ns1__ReverseActivationCashCoupon *ns1__ReverseActivationCashCoupon, _ns1__ReverseActivationCashCouponResponse *ns1__ReverseActivationCashCouponResponse) { return this->ReverseActivationCashCoupon(NULL, NULL, ns1__ReverseActivationCashCoupon, ns1__ReverseActivationCashCouponResponse); }
	virtual	int ReverseActivationCashCoupon(const char *endpoint, const char *soap_action, _ns1__ReverseActivationCashCoupon *ns1__ReverseActivationCashCoupon, _ns1__ReverseActivationCashCouponResponse *ns1__ReverseActivationCashCouponResponse);

	/// Web service operation 'ReverseDeactivationCashCoupon' (returns error code or SOAP_OK)
	virtual	int ReverseDeactivationCashCoupon(_ns1__ReverseDeactivationCashCoupon *ns1__ReverseDeactivationCashCoupon, _ns1__ReverseDeactivationCashCouponResponse *ns1__ReverseDeactivationCashCouponResponse) { return this->ReverseDeactivationCashCoupon(NULL, NULL, ns1__ReverseDeactivationCashCoupon, ns1__ReverseDeactivationCashCouponResponse); }
	virtual	int ReverseDeactivationCashCoupon(const char *endpoint, const char *soap_action, _ns1__ReverseDeactivationCashCoupon *ns1__ReverseDeactivationCashCoupon, _ns1__ReverseDeactivationCashCouponResponse *ns1__ReverseDeactivationCashCouponResponse);

	/// Web service operation 'CancelActivationCashCoupon' (returns error code or SOAP_OK)
	virtual	int CancelActivationCashCoupon(_ns1__CancelActivationCashCoupon *ns1__CancelActivationCashCoupon, _ns1__CancelActivationCashCouponResponse *ns1__CancelActivationCashCouponResponse) { return this->CancelActivationCashCoupon(NULL, NULL, ns1__CancelActivationCashCoupon, ns1__CancelActivationCashCouponResponse); }
	virtual	int CancelActivationCashCoupon(const char *endpoint, const char *soap_action, _ns1__CancelActivationCashCoupon *ns1__CancelActivationCashCoupon, _ns1__CancelActivationCashCouponResponse *ns1__CancelActivationCashCouponResponse);

	/// Web service operation 'CheckActivationCouponStatus' (returns error code or SOAP_OK)
	virtual	int CheckActivationCouponStatus(_ns1__CheckActivationCouponStatus *ns1__CheckActivationCouponStatus, _ns1__CheckActivationCouponStatusResponse *ns1__CheckActivationCouponStatusResponse) { return this->CheckActivationCouponStatus(NULL, NULL, ns1__CheckActivationCouponStatus, ns1__CheckActivationCouponStatusResponse); }
	virtual	int CheckActivationCouponStatus(const char *endpoint, const char *soap_action, _ns1__CheckActivationCouponStatus *ns1__CheckActivationCouponStatus, _ns1__CheckActivationCouponStatusResponse *ns1__CheckActivationCouponStatusResponse);

	/// Web service operation 'SelectAppliableItemCodeForDiscountByAccountByGame' (returns error code or SOAP_OK)
	virtual	int SelectAppliableItemCodeForDiscountByAccountByGame(_ns1__SelectAppliableItemCodeForDiscountByAccountByGame *ns1__SelectAppliableItemCodeForDiscountByAccountByGame, _ns1__SelectAppliableItemCodeForDiscountByAccountByGameResponse *ns1__SelectAppliableItemCodeForDiscountByAccountByGameResponse) { return this->SelectAppliableItemCodeForDiscountByAccountByGame(NULL, NULL, ns1__SelectAppliableItemCodeForDiscountByAccountByGame, ns1__SelectAppliableItemCodeForDiscountByAccountByGameResponse); }
	virtual	int SelectAppliableItemCodeForDiscountByAccountByGame(const char *endpoint, const char *soap_action, _ns1__SelectAppliableItemCodeForDiscountByAccountByGame *ns1__SelectAppliableItemCodeForDiscountByAccountByGame, _ns1__SelectAppliableItemCodeForDiscountByAccountByGameResponse *ns1__SelectAppliableItemCodeForDiscountByAccountByGameResponse);

	/// Web service operation 'SelectHoldingCouponCountByAccountIdByGameServiceCode' (returns error code or SOAP_OK)
	virtual	int SelectHoldingCouponCountByAccountIdByGameServiceCode(_ns1__SelectHoldingCouponCountByAccountIdByGameServiceCode *ns1__SelectHoldingCouponCountByAccountIdByGameServiceCode, _ns1__SelectHoldingCouponCountByAccountIdByGameServiceCodeResponse *ns1__SelectHoldingCouponCountByAccountIdByGameServiceCodeResponse) { return this->SelectHoldingCouponCountByAccountIdByGameServiceCode(NULL, NULL, ns1__SelectHoldingCouponCountByAccountIdByGameServiceCode, ns1__SelectHoldingCouponCountByAccountIdByGameServiceCodeResponse); }
	virtual	int SelectHoldingCouponCountByAccountIdByGameServiceCode(const char *endpoint, const char *soap_action, _ns1__SelectHoldingCouponCountByAccountIdByGameServiceCode *ns1__SelectHoldingCouponCountByAccountIdByGameServiceCode, _ns1__SelectHoldingCouponCountByAccountIdByGameServiceCodeResponse *ns1__SelectHoldingCouponCountByAccountIdByGameServiceCodeResponse);

	/// Web service operation 'SelectHoldingCouponCountByAccountId' (returns error code or SOAP_OK)
	virtual	int SelectHoldingCouponCountByAccountId(_ns1__SelectHoldingCouponCountByAccountId *ns1__SelectHoldingCouponCountByAccountId, _ns1__SelectHoldingCouponCountByAccountIdResponse *ns1__SelectHoldingCouponCountByAccountIdResponse) { return this->SelectHoldingCouponCountByAccountId(NULL, NULL, ns1__SelectHoldingCouponCountByAccountId, ns1__SelectHoldingCouponCountByAccountIdResponse); }
	virtual	int SelectHoldingCouponCountByAccountId(const char *endpoint, const char *soap_action, _ns1__SelectHoldingCouponCountByAccountId *ns1__SelectHoldingCouponCountByAccountId, _ns1__SelectHoldingCouponCountByAccountIdResponse *ns1__SelectHoldingCouponCountByAccountIdResponse);

	/// Web service operation 'CheckDiscountCouponFromCouponBox' (returns error code or SOAP_OK)
	virtual	int CheckDiscountCouponFromCouponBox(_ns1__CheckDiscountCouponFromCouponBox *ns1__CheckDiscountCouponFromCouponBox, _ns1__CheckDiscountCouponFromCouponBoxResponse *ns1__CheckDiscountCouponFromCouponBoxResponse) { return this->CheckDiscountCouponFromCouponBox(NULL, NULL, ns1__CheckDiscountCouponFromCouponBox, ns1__CheckDiscountCouponFromCouponBoxResponse); }
	virtual	int CheckDiscountCouponFromCouponBox(const char *endpoint, const char *soap_action, _ns1__CheckDiscountCouponFromCouponBox *ns1__CheckDiscountCouponFromCouponBox, _ns1__CheckDiscountCouponFromCouponBoxResponse *ns1__CheckDiscountCouponFromCouponBoxResponse);

	/// Web service operation 'UseDiscountCouponFromCouponBox' (returns error code or SOAP_OK)
	virtual	int UseDiscountCouponFromCouponBox(_ns1__UseDiscountCouponFromCouponBox *ns1__UseDiscountCouponFromCouponBox, _ns1__UseDiscountCouponFromCouponBoxResponse *ns1__UseDiscountCouponFromCouponBoxResponse) { return this->UseDiscountCouponFromCouponBox(NULL, NULL, ns1__UseDiscountCouponFromCouponBox, ns1__UseDiscountCouponFromCouponBoxResponse); }
	virtual	int UseDiscountCouponFromCouponBox(const char *endpoint, const char *soap_action, _ns1__UseDiscountCouponFromCouponBox *ns1__UseDiscountCouponFromCouponBox, _ns1__UseDiscountCouponFromCouponBoxResponse *ns1__UseDiscountCouponFromCouponBoxResponse);

	/// Web service operation 'RollbackDiscountCouponFromCouponBox' (returns error code or SOAP_OK)
	virtual	int RollbackDiscountCouponFromCouponBox(_ns1__RollbackDiscountCouponFromCouponBox *ns1__RollbackDiscountCouponFromCouponBox, _ns1__RollbackDiscountCouponFromCouponBoxResponse *ns1__RollbackDiscountCouponFromCouponBoxResponse) { return this->RollbackDiscountCouponFromCouponBox(NULL, NULL, ns1__RollbackDiscountCouponFromCouponBox, ns1__RollbackDiscountCouponFromCouponBoxResponse); }
	virtual	int RollbackDiscountCouponFromCouponBox(const char *endpoint, const char *soap_action, _ns1__RollbackDiscountCouponFromCouponBox *ns1__RollbackDiscountCouponFromCouponBox, _ns1__RollbackDiscountCouponFromCouponBoxResponse *ns1__RollbackDiscountCouponFromCouponBoxResponse);

	/// Web service operation 'CheckDiscountItemCoupon' (returns error code or SOAP_OK)
	virtual	int CheckDiscountItemCoupon(_ns1__CheckDiscountItemCoupon *ns1__CheckDiscountItemCoupon, _ns1__CheckDiscountItemCouponResponse *ns1__CheckDiscountItemCouponResponse) { return this->CheckDiscountItemCoupon(NULL, NULL, ns1__CheckDiscountItemCoupon, ns1__CheckDiscountItemCouponResponse); }
	virtual	int CheckDiscountItemCoupon(const char *endpoint, const char *soap_action, _ns1__CheckDiscountItemCoupon *ns1__CheckDiscountItemCoupon, _ns1__CheckDiscountItemCouponResponse *ns1__CheckDiscountItemCouponResponse);

	/// Web service operation 'UseDiscountItemCoupon' (returns error code or SOAP_OK)
	virtual	int UseDiscountItemCoupon(_ns1__UseDiscountItemCoupon *ns1__UseDiscountItemCoupon, _ns1__UseDiscountItemCouponResponse *ns1__UseDiscountItemCouponResponse) { return this->UseDiscountItemCoupon(NULL, NULL, ns1__UseDiscountItemCoupon, ns1__UseDiscountItemCouponResponse); }
	virtual	int UseDiscountItemCoupon(const char *endpoint, const char *soap_action, _ns1__UseDiscountItemCoupon *ns1__UseDiscountItemCoupon, _ns1__UseDiscountItemCouponResponse *ns1__UseDiscountItemCouponResponse);

	/// Web service operation 'RollbackDiscountItemCoupon' (returns error code or SOAP_OK)
	virtual	int RollbackDiscountItemCoupon(_ns1__RollbackDiscountItemCoupon *ns1__RollbackDiscountItemCoupon, _ns1__RollbackDiscountItemCouponResponse *ns1__RollbackDiscountItemCouponResponse) { return this->RollbackDiscountItemCoupon(NULL, NULL, ns1__RollbackDiscountItemCoupon, ns1__RollbackDiscountItemCouponResponse); }
	virtual	int RollbackDiscountItemCoupon(const char *endpoint, const char *soap_action, _ns1__RollbackDiscountItemCoupon *ns1__RollbackDiscountItemCoupon, _ns1__RollbackDiscountItemCouponResponse *ns1__RollbackDiscountItemCouponResponse);

	/// Web service operation 'CheckItemCouponFromCouponBox' (returns error code or SOAP_OK)
	virtual	int CheckItemCouponFromCouponBox(_ns1__CheckItemCouponFromCouponBox *ns1__CheckItemCouponFromCouponBox, _ns1__CheckItemCouponFromCouponBoxResponse *ns1__CheckItemCouponFromCouponBoxResponse) { return this->CheckItemCouponFromCouponBox(NULL, NULL, ns1__CheckItemCouponFromCouponBox, ns1__CheckItemCouponFromCouponBoxResponse); }
	virtual	int CheckItemCouponFromCouponBox(const char *endpoint, const char *soap_action, _ns1__CheckItemCouponFromCouponBox *ns1__CheckItemCouponFromCouponBox, _ns1__CheckItemCouponFromCouponBoxResponse *ns1__CheckItemCouponFromCouponBoxResponse);

	/// Web service operation 'UseItemCouponFromCouponBox' (returns error code or SOAP_OK)
	virtual	int UseItemCouponFromCouponBox(_ns1__UseItemCouponFromCouponBox *ns1__UseItemCouponFromCouponBox, _ns1__UseItemCouponFromCouponBoxResponse *ns1__UseItemCouponFromCouponBoxResponse) { return this->UseItemCouponFromCouponBox(NULL, NULL, ns1__UseItemCouponFromCouponBox, ns1__UseItemCouponFromCouponBoxResponse); }
	virtual	int UseItemCouponFromCouponBox(const char *endpoint, const char *soap_action, _ns1__UseItemCouponFromCouponBox *ns1__UseItemCouponFromCouponBox, _ns1__UseItemCouponFromCouponBoxResponse *ns1__UseItemCouponFromCouponBoxResponse);

	/// Web service operation 'RollbackItemCouponFromCouponBox' (returns error code or SOAP_OK)
	virtual	int RollbackItemCouponFromCouponBox(_ns1__RollbackItemCouponFromCouponBox *ns1__RollbackItemCouponFromCouponBox, _ns1__RollbackItemCouponFromCouponBoxResponse *ns1__RollbackItemCouponFromCouponBoxResponse) { return this->RollbackItemCouponFromCouponBox(NULL, NULL, ns1__RollbackItemCouponFromCouponBox, ns1__RollbackItemCouponFromCouponBoxResponse); }
	virtual	int RollbackItemCouponFromCouponBox(const char *endpoint, const char *soap_action, _ns1__RollbackItemCouponFromCouponBox *ns1__RollbackItemCouponFromCouponBox, _ns1__RollbackItemCouponFromCouponBoxResponse *ns1__RollbackItemCouponFromCouponBoxResponse);

	/// Web service operation 'CheckItemCoupon' (returns error code or SOAP_OK)
	virtual	int CheckItemCoupon(_ns1__CheckItemCoupon *ns1__CheckItemCoupon, _ns1__CheckItemCouponResponse *ns1__CheckItemCouponResponse) { return this->CheckItemCoupon(NULL, NULL, ns1__CheckItemCoupon, ns1__CheckItemCouponResponse); }
	virtual	int CheckItemCoupon(const char *endpoint, const char *soap_action, _ns1__CheckItemCoupon *ns1__CheckItemCoupon, _ns1__CheckItemCouponResponse *ns1__CheckItemCouponResponse);

	/// Web service operation 'UseItemCoupon' (returns error code or SOAP_OK)
	virtual	int UseItemCoupon(_ns1__UseItemCoupon *ns1__UseItemCoupon, _ns1__UseItemCouponResponse *ns1__UseItemCouponResponse) { return this->UseItemCoupon(NULL, NULL, ns1__UseItemCoupon, ns1__UseItemCouponResponse); }
	virtual	int UseItemCoupon(const char *endpoint, const char *soap_action, _ns1__UseItemCoupon *ns1__UseItemCoupon, _ns1__UseItemCouponResponse *ns1__UseItemCouponResponse);

	/// Web service operation 'RollbackItemCoupon' (returns error code or SOAP_OK)
	virtual	int RollbackItemCoupon(_ns1__RollbackItemCoupon *ns1__RollbackItemCoupon, _ns1__RollbackItemCouponResponse *ns1__RollbackItemCouponResponse) { return this->RollbackItemCoupon(NULL, NULL, ns1__RollbackItemCoupon, ns1__RollbackItemCouponResponse); }
	virtual	int RollbackItemCoupon(const char *endpoint, const char *soap_action, _ns1__RollbackItemCoupon *ns1__RollbackItemCoupon, _ns1__RollbackItemCouponResponse *ns1__RollbackItemCouponResponse);

	/// Web service operation 'CheckItemCouponOLD' (returns error code or SOAP_OK)
	virtual	int CheckItemCouponOLD(_ns1__CheckItemCouponOLD *ns1__CheckItemCouponOLD, _ns1__CheckItemCouponOLDResponse *ns1__CheckItemCouponOLDResponse) { return this->CheckItemCouponOLD(NULL, NULL, ns1__CheckItemCouponOLD, ns1__CheckItemCouponOLDResponse); }
	virtual	int CheckItemCouponOLD(const char *endpoint, const char *soap_action, _ns1__CheckItemCouponOLD *ns1__CheckItemCouponOLD, _ns1__CheckItemCouponOLDResponse *ns1__CheckItemCouponOLDResponse);

	/// Web service operation 'UseItemCouponOLD' (returns error code or SOAP_OK)
	virtual	int UseItemCouponOLD(_ns1__UseItemCouponOLD *ns1__UseItemCouponOLD, _ns1__UseItemCouponOLDResponse *ns1__UseItemCouponOLDResponse) { return this->UseItemCouponOLD(NULL, NULL, ns1__UseItemCouponOLD, ns1__UseItemCouponOLDResponse); }
	virtual	int UseItemCouponOLD(const char *endpoint, const char *soap_action, _ns1__UseItemCouponOLD *ns1__UseItemCouponOLD, _ns1__UseItemCouponOLDResponse *ns1__UseItemCouponOLDResponse);

	/// Web service operation 'BulkCheck' (returns error code or SOAP_OK)
	virtual	int BulkCheck(_ns1__BulkCheck *ns1__BulkCheck, _ns1__BulkCheckResponse *ns1__BulkCheckResponse) { return this->BulkCheck(NULL, NULL, ns1__BulkCheck, ns1__BulkCheckResponse); }
	virtual	int BulkCheck(const char *endpoint, const char *soap_action, _ns1__BulkCheck *ns1__BulkCheck, _ns1__BulkCheckResponse *ns1__BulkCheckResponse);

	/// Web service operation 'BulkCheckExtend' (returns error code or SOAP_OK)
	virtual	int BulkCheckExtend(_ns1__BulkCheckExtend *ns1__BulkCheckExtend, _ns1__BulkCheckExtendResponse *ns1__BulkCheckExtendResponse) { return this->BulkCheckExtend(NULL, NULL, ns1__BulkCheckExtend, ns1__BulkCheckExtendResponse); }
	virtual	int BulkCheckExtend(const char *endpoint, const char *soap_action, _ns1__BulkCheckExtend *ns1__BulkCheckExtend, _ns1__BulkCheckExtendResponse *ns1__BulkCheckExtendResponse);

	/// Web service operation 'GetUseRestrictInfo' (returns error code or SOAP_OK)
	virtual	int GetUseRestrictInfo(_ns1__GetUseRestrictInfo *ns1__GetUseRestrictInfo, _ns1__GetUseRestrictInfoResponse *ns1__GetUseRestrictInfoResponse) { return this->GetUseRestrictInfo(NULL, NULL, ns1__GetUseRestrictInfo, ns1__GetUseRestrictInfoResponse); }
	virtual	int GetUseRestrictInfo(const char *endpoint, const char *soap_action, _ns1__GetUseRestrictInfo *ns1__GetUseRestrictInfo, _ns1__GetUseRestrictInfoResponse *ns1__GetUseRestrictInfoResponse);

	/// Web service operation 'WakeUp' (returns error code or SOAP_OK)
	virtual	int WakeUp(_ns1__WakeUp *ns1__WakeUp, _ns1__WakeUpResponse *ns1__WakeUpResponse) { return this->WakeUp(NULL, NULL, ns1__WakeUp, ns1__WakeUpResponse); }
	virtual	int WakeUp(const char *endpoint, const char *soap_action, _ns1__WakeUp *ns1__WakeUp, _ns1__WakeUpResponse *ns1__WakeUpResponse);

	/// Web service operation 'SelectCashCouponFromCouponBoxByNexonID' (returns error code or SOAP_OK)
	virtual	int SelectCashCouponFromCouponBoxByNexonID_(_ns1__SelectCashCouponFromCouponBoxByNexonID *ns1__SelectCashCouponFromCouponBoxByNexonID, _ns1__SelectCashCouponFromCouponBoxByNexonIDResponse *ns1__SelectCashCouponFromCouponBoxByNexonIDResponse) { return this->SelectCashCouponFromCouponBoxByNexonID_(NULL, NULL, ns1__SelectCashCouponFromCouponBoxByNexonID, ns1__SelectCashCouponFromCouponBoxByNexonIDResponse); }
	virtual	int SelectCashCouponFromCouponBoxByNexonID_(const char *endpoint, const char *soap_action, _ns1__SelectCashCouponFromCouponBoxByNexonID *ns1__SelectCashCouponFromCouponBoxByNexonID, _ns1__SelectCashCouponFromCouponBoxByNexonIDResponse *ns1__SelectCashCouponFromCouponBoxByNexonIDResponse);

	/// Web service operation 'SelectItemCouponFromCouponBoxByNexonID' (returns error code or SOAP_OK)
	virtual	int SelectItemCouponFromCouponBoxByNexonID_(_ns1__SelectItemCouponFromCouponBoxByNexonID *ns1__SelectItemCouponFromCouponBoxByNexonID, _ns1__SelectItemCouponFromCouponBoxByNexonIDResponse *ns1__SelectItemCouponFromCouponBoxByNexonIDResponse) { return this->SelectItemCouponFromCouponBoxByNexonID_(NULL, NULL, ns1__SelectItemCouponFromCouponBoxByNexonID, ns1__SelectItemCouponFromCouponBoxByNexonIDResponse); }
	virtual	int SelectItemCouponFromCouponBoxByNexonID_(const char *endpoint, const char *soap_action, _ns1__SelectItemCouponFromCouponBoxByNexonID *ns1__SelectItemCouponFromCouponBoxByNexonID, _ns1__SelectItemCouponFromCouponBoxByNexonIDResponse *ns1__SelectItemCouponFromCouponBoxByNexonIDResponse);

	/// Web service operation 'AddCouponBoxByCouponPinByNexonId' (returns error code or SOAP_OK)
	virtual	int AddCouponBoxByCouponPinByNexonId_(_ns1__AddCouponBoxByCouponPinByNexonId *ns1__AddCouponBoxByCouponPinByNexonId, _ns1__AddCouponBoxByCouponPinByNexonIdResponse *ns1__AddCouponBoxByCouponPinByNexonIdResponse) { return this->AddCouponBoxByCouponPinByNexonId_(NULL, NULL, ns1__AddCouponBoxByCouponPinByNexonId, ns1__AddCouponBoxByCouponPinByNexonIdResponse); }
	virtual	int AddCouponBoxByCouponPinByNexonId_(const char *endpoint, const char *soap_action, _ns1__AddCouponBoxByCouponPinByNexonId *ns1__AddCouponBoxByCouponPinByNexonId, _ns1__AddCouponBoxByCouponPinByNexonIdResponse *ns1__AddCouponBoxByCouponPinByNexonIdResponse);

	/// Web service operation 'CheckAddCouponBoxByCouponPinByNexonId' (returns error code or SOAP_OK)
	virtual	int CheckAddCouponBoxByCouponPinByNexonId_(_ns1__CheckAddCouponBoxByCouponPinByNexonId *ns1__CheckAddCouponBoxByCouponPinByNexonId, _ns1__CheckAddCouponBoxByCouponPinByNexonIdResponse *ns1__CheckAddCouponBoxByCouponPinByNexonIdResponse) { return this->CheckAddCouponBoxByCouponPinByNexonId_(NULL, NULL, ns1__CheckAddCouponBoxByCouponPinByNexonId, ns1__CheckAddCouponBoxByCouponPinByNexonIdResponse); }
	virtual	int CheckAddCouponBoxByCouponPinByNexonId_(const char *endpoint, const char *soap_action, _ns1__CheckAddCouponBoxByCouponPinByNexonId *ns1__CheckAddCouponBoxByCouponPinByNexonId, _ns1__CheckAddCouponBoxByCouponPinByNexonIdResponse *ns1__CheckAddCouponBoxByCouponPinByNexonIdResponse);

	/// Web service operation 'SelectDiscountCouponFromCouponBoxByNexonIDByItemCode' (returns error code or SOAP_OK)
	virtual	int SelectDiscountCouponFromCouponBoxByNexonIDByItemCode_(_ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemCode *ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemCode, _ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemCodeResponse *ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemCodeResponse) { return this->SelectDiscountCouponFromCouponBoxByNexonIDByItemCode_(NULL, NULL, ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemCode, ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemCodeResponse); }
	virtual	int SelectDiscountCouponFromCouponBoxByNexonIDByItemCode_(const char *endpoint, const char *soap_action, _ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemCode *ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemCode, _ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemCodeResponse *ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemCodeResponse);

	/// Web service operation 'SelectDiscountCouponFromCouponBoxByNexonIDByItemList' (returns error code or SOAP_OK)
	virtual	int SelectDiscountCouponFromCouponBoxByNexonIDByItemList_(_ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemList *ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemList, _ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemListResponse *ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemListResponse) { return this->SelectDiscountCouponFromCouponBoxByNexonIDByItemList_(NULL, NULL, ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemList, ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemListResponse); }
	virtual	int SelectDiscountCouponFromCouponBoxByNexonIDByItemList_(const char *endpoint, const char *soap_action, _ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemList *ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemList, _ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemListResponse *ns1__SelectDiscountCouponFromCouponBoxByNexonIDByItemListResponse);

	/// Web service operation 'SelectDiscountCouponFromCouponBoxByCharacterIDByItemCode' (returns error code or SOAP_OK)
	virtual	int SelectDiscountCouponFromCouponBoxByCharacterIDByItemCode_(_ns1__SelectDiscountCouponFromCouponBoxByCharacterIDByItemCode *ns1__SelectDiscountCouponFromCouponBoxByCharacterIDByItemCode, _ns1__SelectDiscountCouponFromCouponBoxByCharacterIDByItemCodeResponse *ns1__SelectDiscountCouponFromCouponBoxByCharacterIDByItemCodeResponse) { return this->SelectDiscountCouponFromCouponBoxByCharacterIDByItemCode_(NULL, NULL, ns1__SelectDiscountCouponFromCouponBoxByCharacterIDByItemCode, ns1__SelectDiscountCouponFromCouponBoxByCharacterIDByItemCodeResponse); }
	virtual	int SelectDiscountCouponFromCouponBoxByCharacterIDByItemCode_(const char *endpoint, const char *soap_action, _ns1__SelectDiscountCouponFromCouponBoxByCharacterIDByItemCode *ns1__SelectDiscountCouponFromCouponBoxByCharacterIDByItemCode, _ns1__SelectDiscountCouponFromCouponBoxByCharacterIDByItemCodeResponse *ns1__SelectDiscountCouponFromCouponBoxByCharacterIDByItemCodeResponse);

	/// Web service operation 'SelectCouponBoxByCharacterIDForUser' (returns error code or SOAP_OK)
	virtual	int SelectCouponBoxByCharacterIDForUser_(_ns1__SelectCouponBoxByCharacterIDForUser *ns1__SelectCouponBoxByCharacterIDForUser, _ns1__SelectCouponBoxByCharacterIDForUserResponse *ns1__SelectCouponBoxByCharacterIDForUserResponse) { return this->SelectCouponBoxByCharacterIDForUser_(NULL, NULL, ns1__SelectCouponBoxByCharacterIDForUser, ns1__SelectCouponBoxByCharacterIDForUserResponse); }
	virtual	int SelectCouponBoxByCharacterIDForUser_(const char *endpoint, const char *soap_action, _ns1__SelectCouponBoxByCharacterIDForUser *ns1__SelectCouponBoxByCharacterIDForUser, _ns1__SelectCouponBoxByCharacterIDForUserResponse *ns1__SelectCouponBoxByCharacterIDForUserResponse);

	/// Web service operation 'SelectCouponBoxByAccountIDForUser' (returns error code or SOAP_OK)
	virtual	int SelectCouponBoxByAccountIDForUser_(_ns1__SelectCouponBoxByAccountIDForUser *ns1__SelectCouponBoxByAccountIDForUser, _ns1__SelectCouponBoxByAccountIDForUserResponse *ns1__SelectCouponBoxByAccountIDForUserResponse) { return this->SelectCouponBoxByAccountIDForUser_(NULL, NULL, ns1__SelectCouponBoxByAccountIDForUser, ns1__SelectCouponBoxByAccountIDForUserResponse); }
	virtual	int SelectCouponBoxByAccountIDForUser_(const char *endpoint, const char *soap_action, _ns1__SelectCouponBoxByAccountIDForUser *ns1__SelectCouponBoxByAccountIDForUser, _ns1__SelectCouponBoxByAccountIDForUserResponse *ns1__SelectCouponBoxByAccountIDForUserResponse);

	/// Web service operation 'SelectCouponBoxListByNexonIDForUser' (returns error code or SOAP_OK)
	virtual	int SelectCouponBoxListByNexonIDForUser_(_ns1__SelectCouponBoxListByNexonIDForUser *ns1__SelectCouponBoxListByNexonIDForUser, _ns1__SelectCouponBoxListByNexonIDForUserResponse *ns1__SelectCouponBoxListByNexonIDForUserResponse) { return this->SelectCouponBoxListByNexonIDForUser_(NULL, NULL, ns1__SelectCouponBoxListByNexonIDForUser, ns1__SelectCouponBoxListByNexonIDForUserResponse); }
	virtual	int SelectCouponBoxListByNexonIDForUser_(const char *endpoint, const char *soap_action, _ns1__SelectCouponBoxListByNexonIDForUser *ns1__SelectCouponBoxListByNexonIDForUser, _ns1__SelectCouponBoxListByNexonIDForUserResponse *ns1__SelectCouponBoxListByNexonIDForUserResponse);

	/// Web service operation 'SelectCouponBoxUsedListByNexonIDForUser' (returns error code or SOAP_OK)
	virtual	int SelectCouponBoxUsedListByNexonIDForUser_(_ns1__SelectCouponBoxUsedListByNexonIDForUser *ns1__SelectCouponBoxUsedListByNexonIDForUser, _ns1__SelectCouponBoxUsedListByNexonIDForUserResponse *ns1__SelectCouponBoxUsedListByNexonIDForUserResponse) { return this->SelectCouponBoxUsedListByNexonIDForUser_(NULL, NULL, ns1__SelectCouponBoxUsedListByNexonIDForUser, ns1__SelectCouponBoxUsedListByNexonIDForUserResponse); }
	virtual	int SelectCouponBoxUsedListByNexonIDForUser_(const char *endpoint, const char *soap_action, _ns1__SelectCouponBoxUsedListByNexonIDForUser *ns1__SelectCouponBoxUsedListByNexonIDForUser, _ns1__SelectCouponBoxUsedListByNexonIDForUserResponse *ns1__SelectCouponBoxUsedListByNexonIDForUserResponse);

	/// Web service operation 'GetCouponBoxListCountByNexonIDForUser' (returns error code or SOAP_OK)
	virtual	int GetCouponBoxListCountByNexonIDForUser_(_ns1__GetCouponBoxListCountByNexonIDForUser *ns1__GetCouponBoxListCountByNexonIDForUser, _ns1__GetCouponBoxListCountByNexonIDForUserResponse *ns1__GetCouponBoxListCountByNexonIDForUserResponse) { return this->GetCouponBoxListCountByNexonIDForUser_(NULL, NULL, ns1__GetCouponBoxListCountByNexonIDForUser, ns1__GetCouponBoxListCountByNexonIDForUserResponse); }
	virtual	int GetCouponBoxListCountByNexonIDForUser_(const char *endpoint, const char *soap_action, _ns1__GetCouponBoxListCountByNexonIDForUser *ns1__GetCouponBoxListCountByNexonIDForUser, _ns1__GetCouponBoxListCountByNexonIDForUserResponse *ns1__GetCouponBoxListCountByNexonIDForUserResponse);

	/// Web service operation 'GetCouponBoxUsedListCountByNexonIDForUser' (returns error code or SOAP_OK)
	virtual	int GetCouponBoxUsedListCountByNexonIDForUser_(_ns1__GetCouponBoxUsedListCountByNexonIDForUser *ns1__GetCouponBoxUsedListCountByNexonIDForUser, _ns1__GetCouponBoxUsedListCountByNexonIDForUserResponse *ns1__GetCouponBoxUsedListCountByNexonIDForUserResponse) { return this->GetCouponBoxUsedListCountByNexonIDForUser_(NULL, NULL, ns1__GetCouponBoxUsedListCountByNexonIDForUser, ns1__GetCouponBoxUsedListCountByNexonIDForUserResponse); }
	virtual	int GetCouponBoxUsedListCountByNexonIDForUser_(const char *endpoint, const char *soap_action, _ns1__GetCouponBoxUsedListCountByNexonIDForUser *ns1__GetCouponBoxUsedListCountByNexonIDForUser, _ns1__GetCouponBoxUsedListCountByNexonIDForUserResponse *ns1__GetCouponBoxUsedListCountByNexonIDForUserResponse);

	/// Web service operation 'SelectCouponBoxTargetItemList' (returns error code or SOAP_OK)
	virtual	int SelectCouponBoxTargetItemList_(_ns1__SelectCouponBoxTargetItemList *ns1__SelectCouponBoxTargetItemList, _ns1__SelectCouponBoxTargetItemListResponse *ns1__SelectCouponBoxTargetItemListResponse) { return this->SelectCouponBoxTargetItemList_(NULL, NULL, ns1__SelectCouponBoxTargetItemList, ns1__SelectCouponBoxTargetItemListResponse); }
	virtual	int SelectCouponBoxTargetItemList_(const char *endpoint, const char *soap_action, _ns1__SelectCouponBoxTargetItemList *ns1__SelectCouponBoxTargetItemList, _ns1__SelectCouponBoxTargetItemListResponse *ns1__SelectCouponBoxTargetItemListResponse);

	/// Web service operation 'GetCouponBoxTargetItemListCount' (returns error code or SOAP_OK)
	virtual	int GetCouponBoxTargetItemListCount_(_ns1__GetCouponBoxTargetItemListCount *ns1__GetCouponBoxTargetItemListCount, _ns1__GetCouponBoxTargetItemListCountResponse *ns1__GetCouponBoxTargetItemListCountResponse) { return this->GetCouponBoxTargetItemListCount_(NULL, NULL, ns1__GetCouponBoxTargetItemListCount, ns1__GetCouponBoxTargetItemListCountResponse); }
	virtual	int GetCouponBoxTargetItemListCount_(const char *endpoint, const char *soap_action, _ns1__GetCouponBoxTargetItemListCount *ns1__GetCouponBoxTargetItemListCount, _ns1__GetCouponBoxTargetItemListCountResponse *ns1__GetCouponBoxTargetItemListCountResponse);

	/// Web service operation 'CheckCashCouponFromCouponBox' (returns error code or SOAP_OK)
	virtual	int CheckCashCouponFromCouponBox_(_ns1__CheckCashCouponFromCouponBox *ns1__CheckCashCouponFromCouponBox, _ns1__CheckCashCouponFromCouponBoxResponse *ns1__CheckCashCouponFromCouponBoxResponse) { return this->CheckCashCouponFromCouponBox_(NULL, NULL, ns1__CheckCashCouponFromCouponBox, ns1__CheckCashCouponFromCouponBoxResponse); }
	virtual	int CheckCashCouponFromCouponBox_(const char *endpoint, const char *soap_action, _ns1__CheckCashCouponFromCouponBox *ns1__CheckCashCouponFromCouponBox, _ns1__CheckCashCouponFromCouponBoxResponse *ns1__CheckCashCouponFromCouponBoxResponse);

	/// Web service operation 'UseCashCouponFromCouponBox' (returns error code or SOAP_OK)
	virtual	int UseCashCouponFromCouponBox_(_ns1__UseCashCouponFromCouponBox *ns1__UseCashCouponFromCouponBox, _ns1__UseCashCouponFromCouponBoxResponse *ns1__UseCashCouponFromCouponBoxResponse) { return this->UseCashCouponFromCouponBox_(NULL, NULL, ns1__UseCashCouponFromCouponBox, ns1__UseCashCouponFromCouponBoxResponse); }
	virtual	int UseCashCouponFromCouponBox_(const char *endpoint, const char *soap_action, _ns1__UseCashCouponFromCouponBox *ns1__UseCashCouponFromCouponBox, _ns1__UseCashCouponFromCouponBoxResponse *ns1__UseCashCouponFromCouponBoxResponse);

	/// Web service operation 'RollbackCashCouponFromCouponBox' (returns error code or SOAP_OK)
	virtual	int RollbackCashCouponFromCouponBox_(_ns1__RollbackCashCouponFromCouponBox *ns1__RollbackCashCouponFromCouponBox, _ns1__RollbackCashCouponFromCouponBoxResponse *ns1__RollbackCashCouponFromCouponBoxResponse) { return this->RollbackCashCouponFromCouponBox_(NULL, NULL, ns1__RollbackCashCouponFromCouponBox, ns1__RollbackCashCouponFromCouponBoxResponse); }
	virtual	int RollbackCashCouponFromCouponBox_(const char *endpoint, const char *soap_action, _ns1__RollbackCashCouponFromCouponBox *ns1__RollbackCashCouponFromCouponBox, _ns1__RollbackCashCouponFromCouponBoxResponse *ns1__RollbackCashCouponFromCouponBoxResponse);

	/// Web service operation 'CheckCashCoupon' (returns error code or SOAP_OK)
	virtual	int CheckCashCoupon_(_ns1__CheckCashCoupon *ns1__CheckCashCoupon, _ns1__CheckCashCouponResponse *ns1__CheckCashCouponResponse) { return this->CheckCashCoupon_(NULL, NULL, ns1__CheckCashCoupon, ns1__CheckCashCouponResponse); }
	virtual	int CheckCashCoupon_(const char *endpoint, const char *soap_action, _ns1__CheckCashCoupon *ns1__CheckCashCoupon, _ns1__CheckCashCouponResponse *ns1__CheckCashCouponResponse);

	/// Web service operation 'UseCashCoupon' (returns error code or SOAP_OK)
	virtual	int UseCashCoupon_(_ns1__UseCashCoupon *ns1__UseCashCoupon, _ns1__UseCashCouponResponse *ns1__UseCashCouponResponse) { return this->UseCashCoupon_(NULL, NULL, ns1__UseCashCoupon, ns1__UseCashCouponResponse); }
	virtual	int UseCashCoupon_(const char *endpoint, const char *soap_action, _ns1__UseCashCoupon *ns1__UseCashCoupon, _ns1__UseCashCouponResponse *ns1__UseCashCouponResponse);

	/// Web service operation 'RollbackCashCoupon' (returns error code or SOAP_OK)
	virtual	int RollbackCashCoupon_(_ns1__RollbackCashCoupon *ns1__RollbackCashCoupon, _ns1__RollbackCashCouponResponse *ns1__RollbackCashCouponResponse) { return this->RollbackCashCoupon_(NULL, NULL, ns1__RollbackCashCoupon, ns1__RollbackCashCouponResponse); }
	virtual	int RollbackCashCoupon_(const char *endpoint, const char *soap_action, _ns1__RollbackCashCoupon *ns1__RollbackCashCoupon, _ns1__RollbackCashCouponResponse *ns1__RollbackCashCouponResponse);

	/// Web service operation 'ActivationCashCoupon' (returns error code or SOAP_OK)
	virtual	int ActivationCashCoupon_(_ns1__ActivationCashCoupon *ns1__ActivationCashCoupon, _ns1__ActivationCashCouponResponse *ns1__ActivationCashCouponResponse) { return this->ActivationCashCoupon_(NULL, NULL, ns1__ActivationCashCoupon, ns1__ActivationCashCouponResponse); }
	virtual	int ActivationCashCoupon_(const char *endpoint, const char *soap_action, _ns1__ActivationCashCoupon *ns1__ActivationCashCoupon, _ns1__ActivationCashCouponResponse *ns1__ActivationCashCouponResponse);

	/// Web service operation 'ReverseActivationCashCoupon' (returns error code or SOAP_OK)
	virtual	int ReverseActivationCashCoupon_(_ns1__ReverseActivationCashCoupon *ns1__ReverseActivationCashCoupon, _ns1__ReverseActivationCashCouponResponse *ns1__ReverseActivationCashCouponResponse) { return this->ReverseActivationCashCoupon_(NULL, NULL, ns1__ReverseActivationCashCoupon, ns1__ReverseActivationCashCouponResponse); }
	virtual	int ReverseActivationCashCoupon_(const char *endpoint, const char *soap_action, _ns1__ReverseActivationCashCoupon *ns1__ReverseActivationCashCoupon, _ns1__ReverseActivationCashCouponResponse *ns1__ReverseActivationCashCouponResponse);

	/// Web service operation 'ReverseDeactivationCashCoupon' (returns error code or SOAP_OK)
	virtual	int ReverseDeactivationCashCoupon_(_ns1__ReverseDeactivationCashCoupon *ns1__ReverseDeactivationCashCoupon, _ns1__ReverseDeactivationCashCouponResponse *ns1__ReverseDeactivationCashCouponResponse) { return this->ReverseDeactivationCashCoupon_(NULL, NULL, ns1__ReverseDeactivationCashCoupon, ns1__ReverseDeactivationCashCouponResponse); }
	virtual	int ReverseDeactivationCashCoupon_(const char *endpoint, const char *soap_action, _ns1__ReverseDeactivationCashCoupon *ns1__ReverseDeactivationCashCoupon, _ns1__ReverseDeactivationCashCouponResponse *ns1__ReverseDeactivationCashCouponResponse);

	/// Web service operation 'CancelActivationCashCoupon' (returns error code or SOAP_OK)
	virtual	int CancelActivationCashCoupon_(_ns1__CancelActivationCashCoupon *ns1__CancelActivationCashCoupon, _ns1__CancelActivationCashCouponResponse *ns1__CancelActivationCashCouponResponse) { return this->CancelActivationCashCoupon_(NULL, NULL, ns1__CancelActivationCashCoupon, ns1__CancelActivationCashCouponResponse); }
	virtual	int CancelActivationCashCoupon_(const char *endpoint, const char *soap_action, _ns1__CancelActivationCashCoupon *ns1__CancelActivationCashCoupon, _ns1__CancelActivationCashCouponResponse *ns1__CancelActivationCashCouponResponse);

	/// Web service operation 'CheckActivationCouponStatus' (returns error code or SOAP_OK)
	virtual	int CheckActivationCouponStatus_(_ns1__CheckActivationCouponStatus *ns1__CheckActivationCouponStatus, _ns1__CheckActivationCouponStatusResponse *ns1__CheckActivationCouponStatusResponse) { return this->CheckActivationCouponStatus_(NULL, NULL, ns1__CheckActivationCouponStatus, ns1__CheckActivationCouponStatusResponse); }
	virtual	int CheckActivationCouponStatus_(const char *endpoint, const char *soap_action, _ns1__CheckActivationCouponStatus *ns1__CheckActivationCouponStatus, _ns1__CheckActivationCouponStatusResponse *ns1__CheckActivationCouponStatusResponse);

	/// Web service operation 'SelectAppliableItemCodeForDiscountByAccountByGame' (returns error code or SOAP_OK)
	virtual	int SelectAppliableItemCodeForDiscountByAccountByGame_(_ns1__SelectAppliableItemCodeForDiscountByAccountByGame *ns1__SelectAppliableItemCodeForDiscountByAccountByGame, _ns1__SelectAppliableItemCodeForDiscountByAccountByGameResponse *ns1__SelectAppliableItemCodeForDiscountByAccountByGameResponse) { return this->SelectAppliableItemCodeForDiscountByAccountByGame_(NULL, NULL, ns1__SelectAppliableItemCodeForDiscountByAccountByGame, ns1__SelectAppliableItemCodeForDiscountByAccountByGameResponse); }
	virtual	int SelectAppliableItemCodeForDiscountByAccountByGame_(const char *endpoint, const char *soap_action, _ns1__SelectAppliableItemCodeForDiscountByAccountByGame *ns1__SelectAppliableItemCodeForDiscountByAccountByGame, _ns1__SelectAppliableItemCodeForDiscountByAccountByGameResponse *ns1__SelectAppliableItemCodeForDiscountByAccountByGameResponse);

	/// Web service operation 'SelectHoldingCouponCountByAccountIdByGameServiceCode' (returns error code or SOAP_OK)
	virtual	int SelectHoldingCouponCountByAccountIdByGameServiceCode_(_ns1__SelectHoldingCouponCountByAccountIdByGameServiceCode *ns1__SelectHoldingCouponCountByAccountIdByGameServiceCode, _ns1__SelectHoldingCouponCountByAccountIdByGameServiceCodeResponse *ns1__SelectHoldingCouponCountByAccountIdByGameServiceCodeResponse) { return this->SelectHoldingCouponCountByAccountIdByGameServiceCode_(NULL, NULL, ns1__SelectHoldingCouponCountByAccountIdByGameServiceCode, ns1__SelectHoldingCouponCountByAccountIdByGameServiceCodeResponse); }
	virtual	int SelectHoldingCouponCountByAccountIdByGameServiceCode_(const char *endpoint, const char *soap_action, _ns1__SelectHoldingCouponCountByAccountIdByGameServiceCode *ns1__SelectHoldingCouponCountByAccountIdByGameServiceCode, _ns1__SelectHoldingCouponCountByAccountIdByGameServiceCodeResponse *ns1__SelectHoldingCouponCountByAccountIdByGameServiceCodeResponse);

	/// Web service operation 'SelectHoldingCouponCountByAccountId' (returns error code or SOAP_OK)
	virtual	int SelectHoldingCouponCountByAccountId_(_ns1__SelectHoldingCouponCountByAccountId *ns1__SelectHoldingCouponCountByAccountId, _ns1__SelectHoldingCouponCountByAccountIdResponse *ns1__SelectHoldingCouponCountByAccountIdResponse) { return this->SelectHoldingCouponCountByAccountId_(NULL, NULL, ns1__SelectHoldingCouponCountByAccountId, ns1__SelectHoldingCouponCountByAccountIdResponse); }
	virtual	int SelectHoldingCouponCountByAccountId_(const char *endpoint, const char *soap_action, _ns1__SelectHoldingCouponCountByAccountId *ns1__SelectHoldingCouponCountByAccountId, _ns1__SelectHoldingCouponCountByAccountIdResponse *ns1__SelectHoldingCouponCountByAccountIdResponse);

	/// Web service operation 'CheckDiscountCouponFromCouponBox' (returns error code or SOAP_OK)
	virtual	int CheckDiscountCouponFromCouponBox_(_ns1__CheckDiscountCouponFromCouponBox *ns1__CheckDiscountCouponFromCouponBox, _ns1__CheckDiscountCouponFromCouponBoxResponse *ns1__CheckDiscountCouponFromCouponBoxResponse) { return this->CheckDiscountCouponFromCouponBox_(NULL, NULL, ns1__CheckDiscountCouponFromCouponBox, ns1__CheckDiscountCouponFromCouponBoxResponse); }
	virtual	int CheckDiscountCouponFromCouponBox_(const char *endpoint, const char *soap_action, _ns1__CheckDiscountCouponFromCouponBox *ns1__CheckDiscountCouponFromCouponBox, _ns1__CheckDiscountCouponFromCouponBoxResponse *ns1__CheckDiscountCouponFromCouponBoxResponse);

	/// Web service operation 'UseDiscountCouponFromCouponBox' (returns error code or SOAP_OK)
	virtual	int UseDiscountCouponFromCouponBox_(_ns1__UseDiscountCouponFromCouponBox *ns1__UseDiscountCouponFromCouponBox, _ns1__UseDiscountCouponFromCouponBoxResponse *ns1__UseDiscountCouponFromCouponBoxResponse) { return this->UseDiscountCouponFromCouponBox_(NULL, NULL, ns1__UseDiscountCouponFromCouponBox, ns1__UseDiscountCouponFromCouponBoxResponse); }
	virtual	int UseDiscountCouponFromCouponBox_(const char *endpoint, const char *soap_action, _ns1__UseDiscountCouponFromCouponBox *ns1__UseDiscountCouponFromCouponBox, _ns1__UseDiscountCouponFromCouponBoxResponse *ns1__UseDiscountCouponFromCouponBoxResponse);

	/// Web service operation 'RollbackDiscountCouponFromCouponBox' (returns error code or SOAP_OK)
	virtual	int RollbackDiscountCouponFromCouponBox_(_ns1__RollbackDiscountCouponFromCouponBox *ns1__RollbackDiscountCouponFromCouponBox, _ns1__RollbackDiscountCouponFromCouponBoxResponse *ns1__RollbackDiscountCouponFromCouponBoxResponse) { return this->RollbackDiscountCouponFromCouponBox_(NULL, NULL, ns1__RollbackDiscountCouponFromCouponBox, ns1__RollbackDiscountCouponFromCouponBoxResponse); }
	virtual	int RollbackDiscountCouponFromCouponBox_(const char *endpoint, const char *soap_action, _ns1__RollbackDiscountCouponFromCouponBox *ns1__RollbackDiscountCouponFromCouponBox, _ns1__RollbackDiscountCouponFromCouponBoxResponse *ns1__RollbackDiscountCouponFromCouponBoxResponse);

	/// Web service operation 'CheckDiscountItemCoupon' (returns error code or SOAP_OK)
	virtual	int CheckDiscountItemCoupon_(_ns1__CheckDiscountItemCoupon *ns1__CheckDiscountItemCoupon, _ns1__CheckDiscountItemCouponResponse *ns1__CheckDiscountItemCouponResponse) { return this->CheckDiscountItemCoupon_(NULL, NULL, ns1__CheckDiscountItemCoupon, ns1__CheckDiscountItemCouponResponse); }
	virtual	int CheckDiscountItemCoupon_(const char *endpoint, const char *soap_action, _ns1__CheckDiscountItemCoupon *ns1__CheckDiscountItemCoupon, _ns1__CheckDiscountItemCouponResponse *ns1__CheckDiscountItemCouponResponse);

	/// Web service operation 'UseDiscountItemCoupon' (returns error code or SOAP_OK)
	virtual	int UseDiscountItemCoupon_(_ns1__UseDiscountItemCoupon *ns1__UseDiscountItemCoupon, _ns1__UseDiscountItemCouponResponse *ns1__UseDiscountItemCouponResponse) { return this->UseDiscountItemCoupon_(NULL, NULL, ns1__UseDiscountItemCoupon, ns1__UseDiscountItemCouponResponse); }
	virtual	int UseDiscountItemCoupon_(const char *endpoint, const char *soap_action, _ns1__UseDiscountItemCoupon *ns1__UseDiscountItemCoupon, _ns1__UseDiscountItemCouponResponse *ns1__UseDiscountItemCouponResponse);

	/// Web service operation 'RollbackDiscountItemCoupon' (returns error code or SOAP_OK)
	virtual	int RollbackDiscountItemCoupon_(_ns1__RollbackDiscountItemCoupon *ns1__RollbackDiscountItemCoupon, _ns1__RollbackDiscountItemCouponResponse *ns1__RollbackDiscountItemCouponResponse) { return this->RollbackDiscountItemCoupon_(NULL, NULL, ns1__RollbackDiscountItemCoupon, ns1__RollbackDiscountItemCouponResponse); }
	virtual	int RollbackDiscountItemCoupon_(const char *endpoint, const char *soap_action, _ns1__RollbackDiscountItemCoupon *ns1__RollbackDiscountItemCoupon, _ns1__RollbackDiscountItemCouponResponse *ns1__RollbackDiscountItemCouponResponse);

	/// Web service operation 'CheckItemCouponFromCouponBox' (returns error code or SOAP_OK)
	virtual	int CheckItemCouponFromCouponBox_(_ns1__CheckItemCouponFromCouponBox *ns1__CheckItemCouponFromCouponBox, _ns1__CheckItemCouponFromCouponBoxResponse *ns1__CheckItemCouponFromCouponBoxResponse) { return this->CheckItemCouponFromCouponBox_(NULL, NULL, ns1__CheckItemCouponFromCouponBox, ns1__CheckItemCouponFromCouponBoxResponse); }
	virtual	int CheckItemCouponFromCouponBox_(const char *endpoint, const char *soap_action, _ns1__CheckItemCouponFromCouponBox *ns1__CheckItemCouponFromCouponBox, _ns1__CheckItemCouponFromCouponBoxResponse *ns1__CheckItemCouponFromCouponBoxResponse);

	/// Web service operation 'UseItemCouponFromCouponBox' (returns error code or SOAP_OK)
	virtual	int UseItemCouponFromCouponBox_(_ns1__UseItemCouponFromCouponBox *ns1__UseItemCouponFromCouponBox, _ns1__UseItemCouponFromCouponBoxResponse *ns1__UseItemCouponFromCouponBoxResponse) { return this->UseItemCouponFromCouponBox_(NULL, NULL, ns1__UseItemCouponFromCouponBox, ns1__UseItemCouponFromCouponBoxResponse); }
	virtual	int UseItemCouponFromCouponBox_(const char *endpoint, const char *soap_action, _ns1__UseItemCouponFromCouponBox *ns1__UseItemCouponFromCouponBox, _ns1__UseItemCouponFromCouponBoxResponse *ns1__UseItemCouponFromCouponBoxResponse);

	/// Web service operation 'RollbackItemCouponFromCouponBox' (returns error code or SOAP_OK)
	virtual	int RollbackItemCouponFromCouponBox_(_ns1__RollbackItemCouponFromCouponBox *ns1__RollbackItemCouponFromCouponBox, _ns1__RollbackItemCouponFromCouponBoxResponse *ns1__RollbackItemCouponFromCouponBoxResponse) { return this->RollbackItemCouponFromCouponBox_(NULL, NULL, ns1__RollbackItemCouponFromCouponBox, ns1__RollbackItemCouponFromCouponBoxResponse); }
	virtual	int RollbackItemCouponFromCouponBox_(const char *endpoint, const char *soap_action, _ns1__RollbackItemCouponFromCouponBox *ns1__RollbackItemCouponFromCouponBox, _ns1__RollbackItemCouponFromCouponBoxResponse *ns1__RollbackItemCouponFromCouponBoxResponse);

	/// Web service operation 'CheckItemCoupon' (returns error code or SOAP_OK)
	virtual	int CheckItemCoupon_(_ns1__CheckItemCoupon *ns1__CheckItemCoupon, _ns1__CheckItemCouponResponse *ns1__CheckItemCouponResponse) { return this->CheckItemCoupon_(NULL, NULL, ns1__CheckItemCoupon, ns1__CheckItemCouponResponse); }
	virtual	int CheckItemCoupon_(const char *endpoint, const char *soap_action, _ns1__CheckItemCoupon *ns1__CheckItemCoupon, _ns1__CheckItemCouponResponse *ns1__CheckItemCouponResponse);

	/// Web service operation 'UseItemCoupon' (returns error code or SOAP_OK)
	virtual	int UseItemCoupon_(_ns1__UseItemCoupon *ns1__UseItemCoupon, _ns1__UseItemCouponResponse *ns1__UseItemCouponResponse) { return this->UseItemCoupon_(NULL, NULL, ns1__UseItemCoupon, ns1__UseItemCouponResponse); }
	virtual	int UseItemCoupon_(const char *endpoint, const char *soap_action, _ns1__UseItemCoupon *ns1__UseItemCoupon, _ns1__UseItemCouponResponse *ns1__UseItemCouponResponse);

	/// Web service operation 'RollbackItemCoupon' (returns error code or SOAP_OK)
	virtual	int RollbackItemCoupon_(_ns1__RollbackItemCoupon *ns1__RollbackItemCoupon, _ns1__RollbackItemCouponResponse *ns1__RollbackItemCouponResponse) { return this->RollbackItemCoupon_(NULL, NULL, ns1__RollbackItemCoupon, ns1__RollbackItemCouponResponse); }
	virtual	int RollbackItemCoupon_(const char *endpoint, const char *soap_action, _ns1__RollbackItemCoupon *ns1__RollbackItemCoupon, _ns1__RollbackItemCouponResponse *ns1__RollbackItemCouponResponse);

	/// Web service operation 'CheckItemCouponOLD' (returns error code or SOAP_OK)
	virtual	int CheckItemCouponOLD_(_ns1__CheckItemCouponOLD *ns1__CheckItemCouponOLD, _ns1__CheckItemCouponOLDResponse *ns1__CheckItemCouponOLDResponse) { return this->CheckItemCouponOLD_(NULL, NULL, ns1__CheckItemCouponOLD, ns1__CheckItemCouponOLDResponse); }
	virtual	int CheckItemCouponOLD_(const char *endpoint, const char *soap_action, _ns1__CheckItemCouponOLD *ns1__CheckItemCouponOLD, _ns1__CheckItemCouponOLDResponse *ns1__CheckItemCouponOLDResponse);

	/// Web service operation 'UseItemCouponOLD' (returns error code or SOAP_OK)
	virtual	int UseItemCouponOLD_(_ns1__UseItemCouponOLD *ns1__UseItemCouponOLD, _ns1__UseItemCouponOLDResponse *ns1__UseItemCouponOLDResponse) { return this->UseItemCouponOLD_(NULL, NULL, ns1__UseItemCouponOLD, ns1__UseItemCouponOLDResponse); }
	virtual	int UseItemCouponOLD_(const char *endpoint, const char *soap_action, _ns1__UseItemCouponOLD *ns1__UseItemCouponOLD, _ns1__UseItemCouponOLDResponse *ns1__UseItemCouponOLDResponse);

	/// Web service operation 'BulkCheck' (returns error code or SOAP_OK)
	virtual	int BulkCheck_(_ns1__BulkCheck *ns1__BulkCheck, _ns1__BulkCheckResponse *ns1__BulkCheckResponse) { return this->BulkCheck_(NULL, NULL, ns1__BulkCheck, ns1__BulkCheckResponse); }
	virtual	int BulkCheck_(const char *endpoint, const char *soap_action, _ns1__BulkCheck *ns1__BulkCheck, _ns1__BulkCheckResponse *ns1__BulkCheckResponse);

	/// Web service operation 'BulkCheckExtend' (returns error code or SOAP_OK)
	virtual	int BulkCheckExtend_(_ns1__BulkCheckExtend *ns1__BulkCheckExtend, _ns1__BulkCheckExtendResponse *ns1__BulkCheckExtendResponse) { return this->BulkCheckExtend_(NULL, NULL, ns1__BulkCheckExtend, ns1__BulkCheckExtendResponse); }
	virtual	int BulkCheckExtend_(const char *endpoint, const char *soap_action, _ns1__BulkCheckExtend *ns1__BulkCheckExtend, _ns1__BulkCheckExtendResponse *ns1__BulkCheckExtendResponse);

	/// Web service operation 'GetUseRestrictInfo' (returns error code or SOAP_OK)
	virtual	int GetUseRestrictInfo_(_ns1__GetUseRestrictInfo *ns1__GetUseRestrictInfo, _ns1__GetUseRestrictInfoResponse *ns1__GetUseRestrictInfoResponse) { return this->GetUseRestrictInfo_(NULL, NULL, ns1__GetUseRestrictInfo, ns1__GetUseRestrictInfoResponse); }
	virtual	int GetUseRestrictInfo_(const char *endpoint, const char *soap_action, _ns1__GetUseRestrictInfo *ns1__GetUseRestrictInfo, _ns1__GetUseRestrictInfoResponse *ns1__GetUseRestrictInfoResponse);

	/// Web service operation 'WakeUp' (returns error code or SOAP_OK)
	virtual	int WakeUp_(_ns1__WakeUp *ns1__WakeUp, _ns1__WakeUpResponse *ns1__WakeUpResponse) { return this->WakeUp_(NULL, NULL, ns1__WakeUp, ns1__WakeUpResponse); }
	virtual	int WakeUp_(const char *endpoint, const char *soap_action, _ns1__WakeUp *ns1__WakeUp, _ns1__WakeUpResponse *ns1__WakeUpResponse);
};
#endif
