/* k3r_soap.h
   Generated by wsdl2h 2.8.0 from http://222.127.25.30:83/GameSecurityService.svc?wsdl and typemap.dat
   2012-04-30 01:53:42 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

   gSOAP XML Web services tools.
   Copyright (C) 2001-2010 Robert van Engelen, Genivia Inc. All Rights Reserved.
   Part of this software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/** @page page_notes Usage Notes

NOTE:

 - Run soapcpp2 on k3r_soap.h to generate the SOAP/XML processing logic.
   Use soapcpp2 option -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
   Use soapcpp2 option -i to generate improved proxy and server classes.
 - Use wsdl2h options -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h options -nname and -Nname to globally rename the prefix 'ns'.
 - Use wsdl2h option -d to enable DOM support for xsd:anyType.
 - Use wsdl2h option -g to auto-generate readers and writers for root elements.
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

WARNING:

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS.
   USE THE SOURCE CODE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT BUILDS:
   THE soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

LICENSE:

@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.

This software is released under one of the following two licenses:
1) GPL or 2) Genivia's license for commercial use.
--------------------------------------------------------------------------------
1) GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org
--------------------------------------------------------------------------------
2) A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt cw

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   http://tempuri.org/                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/

// This service uses SOAP 1.2 namespaces:
//gsoap SOAP-ENV schema namespace:	http://www.w3.org/2003/05/soap-envelope
//gsoap SOAP-ENC schema namespace:	http://www.w3.org/2003/05/soap-encoding

/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "http://tempuri.org/"
ns2 = "http://Kill3rComboService/2010/Imports"
ns3 = "http://Kill3rComboService/2010"
ns4 = "http://schemas.microsoft.com/2003/10/Serialization/"
ns5 = "http://schemas.datacontract.org/2004/07/Kill3rCombo.Model"
ns6 = "http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses"

*/

#define SOAP_NAMESPACE_OF_ns2	"http://Kill3rComboService/2010/Imports"
//gsoap ns2   schema namespace:	http://Kill3rComboService/2010/Imports
//gsoap ns2   schema form:	unqualified

#define SOAP_NAMESPACE_OF_ns3	"http://Kill3rComboService/2010"
//gsoap ns3   schema namespace:	http://Kill3rComboService/2010
//gsoap ns3   schema elementForm:	qualified
//gsoap ns3   schema attributeForm:	unqualified

#define SOAP_NAMESPACE_OF_ns4	"http://schemas.microsoft.com/2003/10/Serialization/"
//gsoap ns4   schema namespace:	http://schemas.microsoft.com/2003/10/Serialization/
//gsoap ns4   schema form:	qualified

#define SOAP_NAMESPACE_OF_ns5	"http://schemas.datacontract.org/2004/07/Kill3rCombo.Model"
//gsoap ns5   schema namespace:	http://schemas.datacontract.org/2004/07/Kill3rCombo.Model
//gsoap ns5   schema elementForm:	qualified
//gsoap ns5   schema attributeForm:	unqualified

#define SOAP_NAMESPACE_OF_ns6	"http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses"
//gsoap ns6   schema namespace:	http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses
//gsoap ns6   schema elementForm:	qualified
//gsoap ns6   schema attributeForm:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/


/// Primitive built-in type "xs:ID"
typedef char* xsd__ID;

/// Primitive built-in type "xs:IDREF"
typedef char* xsd__IDREF;

/// Primitive built-in type "xs:anyURI"
typedef char* xsd__anyURI;

/// Built-in type "xs:base64Binary".
struct xsd__base64Binary
{	unsigned char *__ptr;
	int __size;
	char *id, *type, *options; // NOTE: for DIME and MTOM XOP attachments only
};

/// Built-in type "xs:boolean".
enum xsd__boolean { xsd__boolean__false_, xsd__boolean__true_ };

/// Built-in type "xs:byte".
typedef char xsd__byte;

/// Primitive built-in type "xs:decimal"
typedef char* xsd__decimal;

/// Primitive built-in type "xs:duration"
typedef char* xsd__duration;

/// Built-in type "xs:unsignedByte".
typedef unsigned char xsd__unsignedByte;


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://Kill3rComboService/2010/Imports                                   *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://Kill3rComboService/2010                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://schemas.microsoft.com/2003/10/Serialization/                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://schemas.datacontract.org/2004/07/Kill3rCombo.Model                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses  *
 *                                                                            *
\******************************************************************************/


/// "http://schemas.microsoft.com/2003/10/Serialization/":char is a simpleType restriction of xs:int.
typedef int ns4__char;

/// "http://schemas.microsoft.com/2003/10/Serialization/":duration is a simpleType restriction of xs:duration.
/// Content pattern is "\\-?P(\\d*D)?(T(\\d*H)?(\\d*M)?(\\d*(\\.\\d*)?S)?)?" (note: not automatically enforced)
/// Value range is [-P10675199DT2H48M5.4775808S..P10675199DT2H48M5.4775807S]
typedef xsd__duration ns4__duration "\\-?P(\\d*D)?(T(\\d*H)?(\\d*M)?(\\d*(\\.\\d*)?S)?)?";

/// "http://schemas.microsoft.com/2003/10/Serialization/":guid is a simpleType restriction of xs:string.
/// Content pattern is "[\\da-fA-F]{8}-[\\da-fA-F]{4}-[\\da-fA-F]{4}-[\\da-fA-F]{4}-[\\da-fA-F]{12}" (note: not automatically enforced)
typedef char* ns4__guid "[\\da-fA-F]{8}-[\\da-fA-F]{4}-[\\da-fA-F]{4}-[\\da-fA-F]{4}-[\\da-fA-F]{12}";

/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://schemas.datacontract.org/2004/07/Kill3rCombo.Model                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://Kill3rComboService/2010/Imports                                   *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://Kill3rComboService/2010                                           *
 *                                                                            *
\******************************************************************************/



/// Top-level root element "http://Kill3rComboService/2010":Login

/// "http://Kill3rComboService/2010":Login is a complexType.
struct _ns3__Login
{
/// Element username of type xs:string.
    char*                                username                       0;	///< Nullable pointer.
/// Element password of type xs:string.
    char*                                password                       0;	///< Nullable pointer.
/// Element ip_address of type xs:string.
    char*                                ip_USCOREaddress               0;	///< Nullable pointer.
};


/// Top-level root element "http://Kill3rComboService/2010":LoginResponse

/// "http://Kill3rComboService/2010":LoginResponse is a complexType.
struct _ns3__LoginResponse
{
/// Element LoginResult of type xs:string.
    char*                                LoginResult                    0;	///< Nullable pointer.
};


/// Top-level root element "http://Kill3rComboService/2010":Logout

/// "http://Kill3rComboService/2010":Logout is a complexType.
struct _ns3__Logout
{
/// Element username of type xs:string.
    char*                                username                       0;	///< Nullable pointer.
/// Element ip_address of type xs:string.
    char*                                ip_USCOREaddress               0;	///< Nullable pointer.
};


/// Top-level root element "http://Kill3rComboService/2010":LogoutResponse

/// "http://Kill3rComboService/2010":LogoutResponse is a complexType.
struct _ns3__LogoutResponse
{
};


/// Top-level root element "http://Kill3rComboService/2010":InsertBannedFromGame

/// "http://Kill3rComboService/2010":InsertBannedFromGame is a complexType.
struct _ns3__InsertBannedFromGame
{
/// Element account_id of type xs:int.
    int*                                 account_USCOREid               0;	///< Nullable pointer.
/// Element ban_reason of type xs:int.
    int*                                 ban_USCOREreason               0;	///< Nullable pointer.
/// Element charname of type xs:string.
    char*                                charname                       0;	///< Nullable pointer.
};


/// Top-level root element "http://Kill3rComboService/2010":InsertBannedFromGameResponse

/// "http://Kill3rComboService/2010":InsertBannedFromGameResponse is a complexType.
struct _ns3__InsertBannedFromGameResponse
{
/// Element InsertBannedFromGameResult of type xs:int.
    int*                                 InsertBannedFromGameResult     0;	///< Optional element.
};


/// Top-level root element "http://Kill3rComboService/2010":GetSecurityQuestionsStatus

/// "http://Kill3rComboService/2010":GetSecurityQuestionsStatus is a complexType.
struct _ns3__GetSecurityQuestionsStatus
{
/// Element account_id of type xs:int.
    int*                                 account_USCOREid               0;	///< Optional element.
};


/// Top-level root element "http://Kill3rComboService/2010":GetSecurityQuestionsStatusResponse

/// "http://Kill3rComboService/2010":GetSecurityQuestionsStatusResponse is a complexType.
struct _ns3__GetSecurityQuestionsStatusResponse
{
/// Element GetSecurityQuestionsStatusResult of type xs:string.
    char*                                GetSecurityQuestionsStatusResult 0;	///< Nullable pointer.
};


/// Top-level root element "http://Kill3rComboService/2010":setGamePinQuestions

/// "http://Kill3rComboService/2010":setGamePinQuestions is a complexType.
struct _ns3__setGamePinQuestions
{
/// Element account_id of type xs:int.
    int*                                 account_USCOREid               0;	///< Optional element.
/// Element question1_id of type xs:int.
    int*                                 question1_USCOREid             0;	///< Optional element.
/// Element question1_details of type xs:string.
    char*                                question1_USCOREdetails        0;	///< Nullable pointer.
/// Element question1_answer of type xs:string.
    char*                                question1_USCOREanswer         0;	///< Nullable pointer.
/// Element question2_id of type xs:int.
    int*                                 question2_USCOREid             0;	///< Optional element.
/// Element question2_details of type xs:string.
    char*                                question2_USCOREdetails        0;	///< Nullable pointer.
/// Element question2_answer of type xs:string.
    char*                                question2_USCOREanswer         0;	///< Nullable pointer.
/// Element question3_id of type xs:int.
    int*                                 question3_USCOREid             0;	///< Optional element.
/// Element question3_details of type xs:string.
    char*                                question3_USCOREdetails        0;	///< Nullable pointer.
/// Element question3_answer of type xs:string.
    char*                                question3_USCOREanswer         0;	///< Nullable pointer.
};


/// Top-level root element "http://Kill3rComboService/2010":setGamePinQuestionsResponse

/// "http://Kill3rComboService/2010":setGamePinQuestionsResponse is a complexType.
struct _ns3__setGamePinQuestionsResponse
{
/// Element setGamePinQuestionsResult of type xs:int.
    int*                                 setGamePinQuestionsResult      0;	///< Optional element.
};


/// Top-level root element "http://Kill3rComboService/2010":getGamePinQuestions

/// "http://Kill3rComboService/2010":getGamePinQuestions is a complexType.
struct _ns3__getGamePinQuestions
{
/// Element account_id of type xs:int.
    int*                                 account_USCOREid               0;	///< Optional element.
};


/// Top-level root element "http://Kill3rComboService/2010":getGamePinQuestionsResponse

/// "http://Kill3rComboService/2010":getGamePinQuestionsResponse is a complexType.
struct _ns3__getGamePinQuestionsResponse
{
/// Element getGamePinQuestionsResult of type "http://schemas.datacontract.org/2004/07/Kill3rCombo.Model":GamePinSecretQuestions.
    struct ns5__GamePinSecretQuestions*  getGamePinQuestionsResult      0;	///< Nullable pointer.
};


/// Top-level root element "http://Kill3rComboService/2010":testerMethod

/// "http://Kill3rComboService/2010":testerMethod is a complexType.
struct _ns3__testerMethod
{
/// Element value of type xs:int.
    int*                                 value                          0;	///< Optional element.
};


/// Top-level root element "http://Kill3rComboService/2010":testerMethodResponse

/// "http://Kill3rComboService/2010":testerMethodResponse is a complexType.
struct _ns3__testerMethodResponse
{
/// Element testerMethodResult of type xs:string.
    char*                                testerMethodResult             0;	///< Nullable pointer.
};


/// Top-level root element "http://Kill3rComboService/2010":ValidateGamePinSession

/// "http://Kill3rComboService/2010":ValidateGamePinSession is a complexType.
struct _ns3__ValidateGamePinSession
{
/// Element id of type xs:string.
    char*                                id                             0;	///< Nullable pointer.
/// Element idac of type xs:string.
    char*                                idac                           0;	///< Nullable pointer.
};


/// Top-level root element "http://Kill3rComboService/2010":ValidateGamePinSessionResponse

/// "http://Kill3rComboService/2010":ValidateGamePinSessionResponse is a complexType.
struct _ns3__ValidateGamePinSessionResponse
{
/// Element ValidateGamePinSessionResult of type xs:string.
    char*                                ValidateGamePinSessionResult   0;	///< Nullable pointer.
};


/// Top-level root element "http://Kill3rComboService/2010":RevokeGamePinSession

/// "http://Kill3rComboService/2010":RevokeGamePinSession is a complexType.
struct _ns3__RevokeGamePinSession
{
/// Element account_id of type xs:int.
    int*                                 account_USCOREid               0;	///< Optional element.
};


/// Top-level root element "http://Kill3rComboService/2010":RevokeGamePinSessionResponse

/// "http://Kill3rComboService/2010":RevokeGamePinSessionResponse is a complexType.
struct _ns3__RevokeGamePinSessionResponse
{
};


/// Top-level root element "http://Kill3rComboService/2010":AnswerGamePinQuestionsSuccess

/// "http://Kill3rComboService/2010":AnswerGamePinQuestionsSuccess is a complexType.
struct _ns3__AnswerGamePinQuestionsSuccess
{
/// Element account_id of type xs:int.
    int*                                 account_USCOREid               0;	///< Optional element.
/// Element IP of type xs:string.
    char*                                IP                             0;	///< Nullable pointer.
};


/// Top-level root element "http://Kill3rComboService/2010":AnswerGamePinQuestionsSuccessResponse

/// "http://Kill3rComboService/2010":AnswerGamePinQuestionsSuccessResponse is a complexType.
struct _ns3__AnswerGamePinQuestionsSuccessResponse
{
/// Element AnswerGamePinQuestionsSuccessResult of type xs:string.
    char*                                AnswerGamePinQuestionsSuccessResult 0;	///< Nullable pointer.
};

/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://schemas.microsoft.com/2003/10/Serialization/                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://schemas.datacontract.org/2004/07/Kill3rCombo.Model                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses  *
 *                                                                            *
\******************************************************************************/


/// "http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses":StructuralObject is a complexType.
struct ns6__StructuralObject
{
/// Attribute reference "http://schemas.microsoft.com/2003/10/Serialization/":Id.
   @xsd__ID                              ns4__Id                        0;	///< Optional attribute.
/// Attribute reference "http://schemas.microsoft.com/2003/10/Serialization/":Ref.
   @xsd__IDREF                           ns4__Ref                       0;	///< Optional attribute.
};

/// "http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses":ComplexObject is a complexType with complexContent extension of "http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses":StructuralObject.
struct ns6__ComplexObject
{
/// INHERITED FROM ns6__StructuralObject:
/// Attribute reference "http://schemas.microsoft.com/2003/10/Serialization/":Id.
   @xsd__ID                              ns4__Id                        0;	///< Optional attribute.
/// Attribute reference "http://schemas.microsoft.com/2003/10/Serialization/":Ref.
   @xsd__IDREF                           ns4__Ref                       0;	///< Optional attribute.
//  END OF INHERITED FROM ns6__StructuralObject
};

/// "http://schemas.datacontract.org/2004/07/Kill3rCombo.Model":GamePinSecretQuestions is a complexType with complexContent extension of "http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses":ComplexObject.
struct ns5__GamePinSecretQuestions
{
/// INHERITED FROM ns6__StructuralObject:
/// Attribute reference "http://schemas.microsoft.com/2003/10/Serialization/":Id.
   @xsd__ID                              ns4__Id                        0;	///< Optional attribute.
/// Attribute reference "http://schemas.microsoft.com/2003/10/Serialization/":Ref.
   @xsd__IDREF                           ns4__Ref                       0;	///< Optional attribute.
//  END OF INHERITED FROM ns6__StructuralObject
/// INHERITED FROM ns6__ComplexObject:
//  END OF INHERITED FROM ns6__ComplexObject
/// Element account_id of type xs:int.
    int*                                 account_USCOREid               0;	///< Optional element.
/// Element question1_answer of type xs:string.
    char*                                question1_USCOREanswer         0;	///< Nullable pointer.
/// Element question1_details of type xs:string.
    char*                                question1_USCOREdetails        0;	///< Nullable pointer.
/// Element question1_id of type xs:int.
    int*                                 question1_USCOREid             0;	///< Nullable pointer.
/// Element question2_answer of type xs:string.
    char*                                question2_USCOREanswer         0;	///< Nullable pointer.
/// Element question2_details of type xs:string.
    char*                                question2_USCOREdetails        0;	///< Nullable pointer.
/// Element question2_id of type xs:int.
    int*                                 question2_USCOREid             0;	///< Nullable pointer.
/// Element question3_answer of type xs:string.
    char*                                question3_USCOREanswer         0;	///< Nullable pointer.
/// Element question3_details of type xs:string.
    char*                                question3_USCOREdetails        0;	///< Nullable pointer.
/// Element question3_id of type xs:int.
    int*                                 question3_USCOREid             0;	///< Nullable pointer.
};

/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://Kill3rComboService/2010/Imports                                   *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://Kill3rComboService/2010/Imports                                   *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://Kill3rComboService/2010                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://Kill3rComboService/2010                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://schemas.microsoft.com/2003/10/Serialization/                      *
 *                                                                            *
\******************************************************************************/


/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":anyType of type xs:anyType.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":anyURI of type xs:anyURI.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":base64Binary of type xs:base64Binary.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":boolean of type xs:boolean.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":byte of type xs:byte.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":dateTime of type xs:dateTime.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":decimal of type xs:decimal.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":double of type xs:double.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":float of type xs:float.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":int of type xs:int.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":long of type xs:long.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":QName of type xs:QName.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":short of type xs:short.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":string of type xs:string.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":unsignedByte of type xs:unsignedByte.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":unsignedInt of type xs:unsignedInt.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":unsignedLong of type xs:unsignedLong.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":unsignedShort of type xs:unsignedShort.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":char of type "http://schemas.microsoft.com/2003/10/Serialization/":char.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":duration of type "http://schemas.microsoft.com/2003/10/Serialization/":duration.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.microsoft.com/2003/10/Serialization/":guid of type "http://schemas.microsoft.com/2003/10/Serialization/":guid.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://schemas.microsoft.com/2003/10/Serialization/                      *
 *                                                                            *
\******************************************************************************/


/// Top-level attribute "http://schemas.microsoft.com/2003/10/Serialization/":FactoryType of simpleType xs:QName.
/// Note: use wsdl2h option -g to auto-generate a top-level attribute declaration and processing code.

/// Top-level attribute "http://schemas.microsoft.com/2003/10/Serialization/":Id of simpleType xs:ID.
/// Note: use wsdl2h option -g to auto-generate a top-level attribute declaration and processing code.

/// Top-level attribute "http://schemas.microsoft.com/2003/10/Serialization/":Ref of simpleType xs:IDREF.
/// Note: use wsdl2h option -g to auto-generate a top-level attribute declaration and processing code.

/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://schemas.datacontract.org/2004/07/Kill3rCombo.Model                *
 *                                                                            *
\******************************************************************************/


/// Top-level root element "http://schemas.datacontract.org/2004/07/Kill3rCombo.Model":GamePinSecretQuestions of type "http://schemas.datacontract.org/2004/07/Kill3rCombo.Model":GamePinSecretQuestions.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://schemas.datacontract.org/2004/07/Kill3rCombo.Model                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses  *
 *                                                                            *
\******************************************************************************/


/// Top-level root element "http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses":ComplexObject of type "http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses":ComplexObject.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses":StructuralObject of type "http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses":StructuralObject.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns1  service name:	gameEndPoint 
//gsoap ns1  service type:	IGameSecurityContract 
//gsoap ns1  service port:	http://222.127.25.30:83/GameSecurityService.svc 
//gsoap ns1  service namespace:	http://tempuri.org/ 
//gsoap ns1  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage GameSecurityService Definitions

@section GameSecurityService_bindings Service Bindings

  - @ref gameEndPoint

@section GameSecurityService_more More Information

  - @ref page_notes "Usage Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/**

@page gameEndPoint Binding "gameEndPoint"

@section gameEndPoint_operations Operations of Binding  "gameEndPoint"

  - @ref __ns1__Login

  - @ref __ns1__Logout

  - @ref __ns1__InsertBannedFromGame

  - @ref __ns1__GetSecurityQuestionsStatus

  - @ref __ns1__setGamePinQuestions

  - @ref __ns1__getGamePinQuestions

  - @ref __ns1__testerMethod

  - @ref __ns1__ValidateGamePinSession

  - @ref __ns1__RevokeGamePinSession

  - @ref __ns1__AnswerGamePinQuestionsSuccess

@section gameEndPoint_ports Endpoints of Binding  "gameEndPoint"

  - http://222.127.25.30:83/GameSecurityService.svc

Note: use wsdl2h option -N to change the service binding prefix name

*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   gameEndPoint                                                             *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__Login                                                             *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__Login" of service binding "gameEndPoint"

/**

Operation details:


  - SOAP document/literal style messaging

  - SOAP action="http://Kill3rComboService/2010/IGameSecurityContract/Login"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__Login(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    struct _ns3__Login*                 ns3__Login,
    // response parameters:
    struct _ns3__LoginResponse*         ns3__LoginResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__Login(
    struct soap *soap,
    // request parameters:
    struct _ns3__Login*                 ns3__Login,
    // response parameters:
    struct _ns3__LoginResponse*         ns3__LoginResponse
  );
@endcode

*/

//gsoap ns1  service method-style:	Login document
//gsoap ns1  service method-encoding:	Login literal
//gsoap ns1  service method-action:	Login http://Kill3rComboService/2010/IGameSecurityContract/Login
int __ns1__Login(
    struct _ns3__Login*                 ns3__Login,	///< Request parameter
    struct _ns3__LoginResponse*         ns3__LoginResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__Logout                                                            *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__Logout" of service binding "gameEndPoint"

/**

Operation details:


  - SOAP document/literal style messaging

  - SOAP action="http://Kill3rComboService/2010/IGameSecurityContract/Logout"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__Logout(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    struct _ns3__Logout*                ns3__Logout,
    // response parameters:
    struct _ns3__LogoutResponse*        ns3__LogoutResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__Logout(
    struct soap *soap,
    // request parameters:
    struct _ns3__Logout*                ns3__Logout,
    // response parameters:
    struct _ns3__LogoutResponse*        ns3__LogoutResponse
  );
@endcode

*/

//gsoap ns1  service method-style:	Logout document
//gsoap ns1  service method-encoding:	Logout literal
//gsoap ns1  service method-action:	Logout http://Kill3rComboService/2010/IGameSecurityContract/Logout
int __ns1__Logout(
    struct _ns3__Logout*                ns3__Logout,	///< Request parameter
    struct _ns3__LogoutResponse*        ns3__LogoutResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__InsertBannedFromGame                                              *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__InsertBannedFromGame" of service binding "gameEndPoint"

/**

Operation details:


  - SOAP document/literal style messaging

  - SOAP action="http://Kill3rComboService/2010/IGameSecurityContract/InsertBannedFromGame"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__InsertBannedFromGame(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    struct _ns3__InsertBannedFromGame*  ns3__InsertBannedFromGame,
    // response parameters:
    struct _ns3__InsertBannedFromGameResponse* ns3__InsertBannedFromGameResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__InsertBannedFromGame(
    struct soap *soap,
    // request parameters:
    struct _ns3__InsertBannedFromGame*  ns3__InsertBannedFromGame,
    // response parameters:
    struct _ns3__InsertBannedFromGameResponse* ns3__InsertBannedFromGameResponse
  );
@endcode

*/

//gsoap ns1  service method-style:	InsertBannedFromGame document
//gsoap ns1  service method-encoding:	InsertBannedFromGame literal
//gsoap ns1  service method-action:	InsertBannedFromGame http://Kill3rComboService/2010/IGameSecurityContract/InsertBannedFromGame
int __ns1__InsertBannedFromGame(
    struct _ns3__InsertBannedFromGame*  ns3__InsertBannedFromGame,	///< Request parameter
    struct _ns3__InsertBannedFromGameResponse* ns3__InsertBannedFromGameResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__GetSecurityQuestionsStatus                                        *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__GetSecurityQuestionsStatus" of service binding "gameEndPoint"

/**

Operation details:


  - SOAP document/literal style messaging

  - SOAP action="http://Kill3rComboService/2010/IGameSecurityContract/GetSecurityQuestionsStatus"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__GetSecurityQuestionsStatus(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    struct _ns3__GetSecurityQuestionsStatus* ns3__GetSecurityQuestionsStatus,
    // response parameters:
    struct _ns3__GetSecurityQuestionsStatusResponse* ns3__GetSecurityQuestionsStatusResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__GetSecurityQuestionsStatus(
    struct soap *soap,
    // request parameters:
    struct _ns3__GetSecurityQuestionsStatus* ns3__GetSecurityQuestionsStatus,
    // response parameters:
    struct _ns3__GetSecurityQuestionsStatusResponse* ns3__GetSecurityQuestionsStatusResponse
  );
@endcode

*/

//gsoap ns1  service method-style:	GetSecurityQuestionsStatus document
//gsoap ns1  service method-encoding:	GetSecurityQuestionsStatus literal
//gsoap ns1  service method-action:	GetSecurityQuestionsStatus http://Kill3rComboService/2010/IGameSecurityContract/GetSecurityQuestionsStatus
int __ns1__GetSecurityQuestionsStatus(
    struct _ns3__GetSecurityQuestionsStatus* ns3__GetSecurityQuestionsStatus,	///< Request parameter
    struct _ns3__GetSecurityQuestionsStatusResponse* ns3__GetSecurityQuestionsStatusResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__setGamePinQuestions                                               *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__setGamePinQuestions" of service binding "gameEndPoint"

/**

Operation details:


  - SOAP document/literal style messaging

  - SOAP action="http://Kill3rComboService/2010/IGameSecurityContract/setGamePinQuestions"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__setGamePinQuestions(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    struct _ns3__setGamePinQuestions*   ns3__setGamePinQuestions,
    // response parameters:
    struct _ns3__setGamePinQuestionsResponse* ns3__setGamePinQuestionsResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__setGamePinQuestions(
    struct soap *soap,
    // request parameters:
    struct _ns3__setGamePinQuestions*   ns3__setGamePinQuestions,
    // response parameters:
    struct _ns3__setGamePinQuestionsResponse* ns3__setGamePinQuestionsResponse
  );
@endcode

*/

//gsoap ns1  service method-style:	setGamePinQuestions document
//gsoap ns1  service method-encoding:	setGamePinQuestions literal
//gsoap ns1  service method-action:	setGamePinQuestions http://Kill3rComboService/2010/IGameSecurityContract/setGamePinQuestions
int __ns1__setGamePinQuestions(
    struct _ns3__setGamePinQuestions*   ns3__setGamePinQuestions,	///< Request parameter
    struct _ns3__setGamePinQuestionsResponse* ns3__setGamePinQuestionsResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__getGamePinQuestions                                               *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__getGamePinQuestions" of service binding "gameEndPoint"

/**

Operation details:


  - SOAP document/literal style messaging

  - SOAP action="http://Kill3rComboService/2010/IGameSecurityContract/getGamePinQuestions"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__getGamePinQuestions(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    struct _ns3__getGamePinQuestions*   ns3__getGamePinQuestions,
    // response parameters:
    struct _ns3__getGamePinQuestionsResponse* ns3__getGamePinQuestionsResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__getGamePinQuestions(
    struct soap *soap,
    // request parameters:
    struct _ns3__getGamePinQuestions*   ns3__getGamePinQuestions,
    // response parameters:
    struct _ns3__getGamePinQuestionsResponse* ns3__getGamePinQuestionsResponse
  );
@endcode

*/

//gsoap ns1  service method-style:	getGamePinQuestions document
//gsoap ns1  service method-encoding:	getGamePinQuestions literal
//gsoap ns1  service method-action:	getGamePinQuestions http://Kill3rComboService/2010/IGameSecurityContract/getGamePinQuestions
int __ns1__getGamePinQuestions(
    struct _ns3__getGamePinQuestions*   ns3__getGamePinQuestions,	///< Request parameter
    struct _ns3__getGamePinQuestionsResponse* ns3__getGamePinQuestionsResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__testerMethod                                                      *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__testerMethod" of service binding "gameEndPoint"

/**

Operation details:


  - SOAP document/literal style messaging

  - SOAP action="http://Kill3rComboService/2010/IGameSecurityContract/testerMethod"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__testerMethod(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    struct _ns3__testerMethod*          ns3__testerMethod,
    // response parameters:
    struct _ns3__testerMethodResponse*  ns3__testerMethodResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__testerMethod(
    struct soap *soap,
    // request parameters:
    struct _ns3__testerMethod*          ns3__testerMethod,
    // response parameters:
    struct _ns3__testerMethodResponse*  ns3__testerMethodResponse
  );
@endcode

*/

//gsoap ns1  service method-style:	testerMethod document
//gsoap ns1  service method-encoding:	testerMethod literal
//gsoap ns1  service method-action:	testerMethod http://Kill3rComboService/2010/IGameSecurityContract/testerMethod
int __ns1__testerMethod(
    struct _ns3__testerMethod*          ns3__testerMethod,	///< Request parameter
    struct _ns3__testerMethodResponse*  ns3__testerMethodResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__ValidateGamePinSession                                            *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__ValidateGamePinSession" of service binding "gameEndPoint"

/**

Operation details:


  - SOAP document/literal style messaging

  - SOAP action="http://Kill3rComboService/2010/IGameSecurityContract/ValidateGamePinSession"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__ValidateGamePinSession(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    struct _ns3__ValidateGamePinSession* ns3__ValidateGamePinSession,
    // response parameters:
    struct _ns3__ValidateGamePinSessionResponse* ns3__ValidateGamePinSessionResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__ValidateGamePinSession(
    struct soap *soap,
    // request parameters:
    struct _ns3__ValidateGamePinSession* ns3__ValidateGamePinSession,
    // response parameters:
    struct _ns3__ValidateGamePinSessionResponse* ns3__ValidateGamePinSessionResponse
  );
@endcode

*/

//gsoap ns1  service method-style:	ValidateGamePinSession document
//gsoap ns1  service method-encoding:	ValidateGamePinSession literal
//gsoap ns1  service method-action:	ValidateGamePinSession http://Kill3rComboService/2010/IGameSecurityContract/ValidateGamePinSession
int __ns1__ValidateGamePinSession(
    struct _ns3__ValidateGamePinSession* ns3__ValidateGamePinSession,	///< Request parameter
    struct _ns3__ValidateGamePinSessionResponse* ns3__ValidateGamePinSessionResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__RevokeGamePinSession                                              *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__RevokeGamePinSession" of service binding "gameEndPoint"

/**

Operation details:


  - SOAP document/literal style messaging

  - SOAP action="http://Kill3rComboService/2010/IGameSecurityContract/RevokeGamePinSession"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__RevokeGamePinSession(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    struct _ns3__RevokeGamePinSession*  ns3__RevokeGamePinSession,
    // response parameters:
    struct _ns3__RevokeGamePinSessionResponse* ns3__RevokeGamePinSessionResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__RevokeGamePinSession(
    struct soap *soap,
    // request parameters:
    struct _ns3__RevokeGamePinSession*  ns3__RevokeGamePinSession,
    // response parameters:
    struct _ns3__RevokeGamePinSessionResponse* ns3__RevokeGamePinSessionResponse
  );
@endcode

*/

//gsoap ns1  service method-style:	RevokeGamePinSession document
//gsoap ns1  service method-encoding:	RevokeGamePinSession literal
//gsoap ns1  service method-action:	RevokeGamePinSession http://Kill3rComboService/2010/IGameSecurityContract/RevokeGamePinSession
int __ns1__RevokeGamePinSession(
    struct _ns3__RevokeGamePinSession*  ns3__RevokeGamePinSession,	///< Request parameter
    struct _ns3__RevokeGamePinSessionResponse* ns3__RevokeGamePinSessionResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__AnswerGamePinQuestionsSuccess                                     *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__AnswerGamePinQuestionsSuccess" of service binding "gameEndPoint"

/**

Operation details:


  - SOAP document/literal style messaging

  - SOAP action="http://Kill3rComboService/2010/IGameSecurityContract/AnswerGamePinQuestionsSuccess"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__AnswerGamePinQuestionsSuccess(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    struct _ns3__AnswerGamePinQuestionsSuccess* ns3__AnswerGamePinQuestionsSuccess,
    // response parameters:
    struct _ns3__AnswerGamePinQuestionsSuccessResponse* ns3__AnswerGamePinQuestionsSuccessResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__AnswerGamePinQuestionsSuccess(
    struct soap *soap,
    // request parameters:
    struct _ns3__AnswerGamePinQuestionsSuccess* ns3__AnswerGamePinQuestionsSuccess,
    // response parameters:
    struct _ns3__AnswerGamePinQuestionsSuccessResponse* ns3__AnswerGamePinQuestionsSuccessResponse
  );
@endcode

*/

//gsoap ns1  service method-style:	AnswerGamePinQuestionsSuccess document
//gsoap ns1  service method-encoding:	AnswerGamePinQuestionsSuccess literal
//gsoap ns1  service method-action:	AnswerGamePinQuestionsSuccess http://Kill3rComboService/2010/IGameSecurityContract/AnswerGamePinQuestionsSuccess
int __ns1__AnswerGamePinQuestionsSuccess(
    struct _ns3__AnswerGamePinQuestionsSuccess* ns3__AnswerGamePinQuestionsSuccess,	///< Request parameter
    struct _ns3__AnswerGamePinQuestionsSuccessResponse* ns3__AnswerGamePinQuestionsSuccessResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/**

@page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings contractually bound by WSDL and auto-
generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data bindings
are adopted from XML schemas as part of the WSDL types section or when running
wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

The following readers and writers are C/C++ data type (de)serializers auto-
generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

XML content can be retrieved from:
  - a file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->is = ...
  - a buffer, using the soap->frecv() callback

XML content can be stored to:
  - a file descriptor, using soap->sendfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->os = ...
  - a buffer, using the soap->fsend() callback


@section ns2 Top-level root elements of schema "http://Kill3rComboService/2010/Imports"

@section ns3 Top-level root elements of schema "http://Kill3rComboService/2010"

  - <ns3:Login> @ref _ns3__Login
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns3__Login(struct soap*, struct _ns3__Login*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns3__Login(struct soap*, struct _ns3__Login*);
    @endcode

  - <ns3:LoginResponse> @ref _ns3__LoginResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns3__LoginResponse(struct soap*, struct _ns3__LoginResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns3__LoginResponse(struct soap*, struct _ns3__LoginResponse*);
    @endcode

  - <ns3:Logout> @ref _ns3__Logout
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns3__Logout(struct soap*, struct _ns3__Logout*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns3__Logout(struct soap*, struct _ns3__Logout*);
    @endcode

  - <ns3:LogoutResponse> @ref _ns3__LogoutResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns3__LogoutResponse(struct soap*, struct _ns3__LogoutResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns3__LogoutResponse(struct soap*, struct _ns3__LogoutResponse*);
    @endcode

  - <ns3:InsertBannedFromGame> @ref _ns3__InsertBannedFromGame
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns3__InsertBannedFromGame(struct soap*, struct _ns3__InsertBannedFromGame*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns3__InsertBannedFromGame(struct soap*, struct _ns3__InsertBannedFromGame*);
    @endcode

  - <ns3:InsertBannedFromGameResponse> @ref _ns3__InsertBannedFromGameResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns3__InsertBannedFromGameResponse(struct soap*, struct _ns3__InsertBannedFromGameResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns3__InsertBannedFromGameResponse(struct soap*, struct _ns3__InsertBannedFromGameResponse*);
    @endcode

  - <ns3:GetSecurityQuestionsStatus> @ref _ns3__GetSecurityQuestionsStatus
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns3__GetSecurityQuestionsStatus(struct soap*, struct _ns3__GetSecurityQuestionsStatus*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns3__GetSecurityQuestionsStatus(struct soap*, struct _ns3__GetSecurityQuestionsStatus*);
    @endcode

  - <ns3:GetSecurityQuestionsStatusResponse> @ref _ns3__GetSecurityQuestionsStatusResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns3__GetSecurityQuestionsStatusResponse(struct soap*, struct _ns3__GetSecurityQuestionsStatusResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns3__GetSecurityQuestionsStatusResponse(struct soap*, struct _ns3__GetSecurityQuestionsStatusResponse*);
    @endcode

  - <ns3:setGamePinQuestions> @ref _ns3__setGamePinQuestions
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns3__setGamePinQuestions(struct soap*, struct _ns3__setGamePinQuestions*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns3__setGamePinQuestions(struct soap*, struct _ns3__setGamePinQuestions*);
    @endcode

  - <ns3:setGamePinQuestionsResponse> @ref _ns3__setGamePinQuestionsResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns3__setGamePinQuestionsResponse(struct soap*, struct _ns3__setGamePinQuestionsResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns3__setGamePinQuestionsResponse(struct soap*, struct _ns3__setGamePinQuestionsResponse*);
    @endcode

  - <ns3:getGamePinQuestions> @ref _ns3__getGamePinQuestions
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns3__getGamePinQuestions(struct soap*, struct _ns3__getGamePinQuestions*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns3__getGamePinQuestions(struct soap*, struct _ns3__getGamePinQuestions*);
    @endcode

  - <ns3:getGamePinQuestionsResponse> @ref _ns3__getGamePinQuestionsResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns3__getGamePinQuestionsResponse(struct soap*, struct _ns3__getGamePinQuestionsResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns3__getGamePinQuestionsResponse(struct soap*, struct _ns3__getGamePinQuestionsResponse*);
    @endcode

  - <ns3:testerMethod> @ref _ns3__testerMethod
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns3__testerMethod(struct soap*, struct _ns3__testerMethod*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns3__testerMethod(struct soap*, struct _ns3__testerMethod*);
    @endcode

  - <ns3:testerMethodResponse> @ref _ns3__testerMethodResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns3__testerMethodResponse(struct soap*, struct _ns3__testerMethodResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns3__testerMethodResponse(struct soap*, struct _ns3__testerMethodResponse*);
    @endcode

  - <ns3:ValidateGamePinSession> @ref _ns3__ValidateGamePinSession
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns3__ValidateGamePinSession(struct soap*, struct _ns3__ValidateGamePinSession*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns3__ValidateGamePinSession(struct soap*, struct _ns3__ValidateGamePinSession*);
    @endcode

  - <ns3:ValidateGamePinSessionResponse> @ref _ns3__ValidateGamePinSessionResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns3__ValidateGamePinSessionResponse(struct soap*, struct _ns3__ValidateGamePinSessionResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns3__ValidateGamePinSessionResponse(struct soap*, struct _ns3__ValidateGamePinSessionResponse*);
    @endcode

  - <ns3:RevokeGamePinSession> @ref _ns3__RevokeGamePinSession
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns3__RevokeGamePinSession(struct soap*, struct _ns3__RevokeGamePinSession*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns3__RevokeGamePinSession(struct soap*, struct _ns3__RevokeGamePinSession*);
    @endcode

  - <ns3:RevokeGamePinSessionResponse> @ref _ns3__RevokeGamePinSessionResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns3__RevokeGamePinSessionResponse(struct soap*, struct _ns3__RevokeGamePinSessionResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns3__RevokeGamePinSessionResponse(struct soap*, struct _ns3__RevokeGamePinSessionResponse*);
    @endcode

  - <ns3:AnswerGamePinQuestionsSuccess> @ref _ns3__AnswerGamePinQuestionsSuccess
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns3__AnswerGamePinQuestionsSuccess(struct soap*, struct _ns3__AnswerGamePinQuestionsSuccess*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns3__AnswerGamePinQuestionsSuccess(struct soap*, struct _ns3__AnswerGamePinQuestionsSuccess*);
    @endcode

  - <ns3:AnswerGamePinQuestionsSuccessResponse> @ref _ns3__AnswerGamePinQuestionsSuccessResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns3__AnswerGamePinQuestionsSuccessResponse(struct soap*, struct _ns3__AnswerGamePinQuestionsSuccessResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns3__AnswerGamePinQuestionsSuccessResponse(struct soap*, struct _ns3__AnswerGamePinQuestionsSuccessResponse*);
    @endcode

@section ns4 Top-level root elements of schema "http://schemas.microsoft.com/2003/10/Serialization/"

  - <ns4:anyType> (use wsdl2h option -g to auto-generate)

  - <ns4:anyURI> (use wsdl2h option -g to auto-generate)

  - <ns4:base64Binary> (use wsdl2h option -g to auto-generate)

  - <ns4:boolean> (use wsdl2h option -g to auto-generate)

  - <ns4:byte> (use wsdl2h option -g to auto-generate)

  - <ns4:dateTime> (use wsdl2h option -g to auto-generate)

  - <ns4:decimal> (use wsdl2h option -g to auto-generate)

  - <ns4:double> (use wsdl2h option -g to auto-generate)

  - <ns4:float> (use wsdl2h option -g to auto-generate)

  - <ns4:int> (use wsdl2h option -g to auto-generate)

  - <ns4:long> (use wsdl2h option -g to auto-generate)

  - <ns4:QName> (use wsdl2h option -g to auto-generate)

  - <ns4:short> (use wsdl2h option -g to auto-generate)

  - <ns4:string> (use wsdl2h option -g to auto-generate)

  - <ns4:unsignedByte> (use wsdl2h option -g to auto-generate)

  - <ns4:unsignedInt> (use wsdl2h option -g to auto-generate)

  - <ns4:unsignedLong> (use wsdl2h option -g to auto-generate)

  - <ns4:unsignedShort> (use wsdl2h option -g to auto-generate)

  - <ns4:char> (use wsdl2h option -g to auto-generate)

  - <ns4:duration> (use wsdl2h option -g to auto-generate)

  - <ns4:guid> (use wsdl2h option -g to auto-generate)

@section ns5 Top-level root elements of schema "http://schemas.datacontract.org/2004/07/Kill3rCombo.Model"

  - <ns5:GamePinSecretQuestions> (use wsdl2h option -g to auto-generate)

@section ns6 Top-level root elements of schema "http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses"

  - <ns6:ComplexObject> (use wsdl2h option -g to auto-generate)

  - <ns6:StructuralObject> (use wsdl2h option -g to auto-generate)

*/

/* End of k3r_soap.h */
