/* soapStub.h
   Generated by gSOAP 2.8.0 from k3r_soap.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapStub_H
#define soapStub_H
#define SOAP_NAMESPACE_OF_ns2	"http://Kill3rComboService/2010/Imports"
#define SOAP_NAMESPACE_OF_ns3	"http://Kill3rComboService/2010"
#define SOAP_NAMESPACE_OF_ns4	"http://schemas.microsoft.com/2003/10/Serialization/"
#define SOAP_NAMESPACE_OF_ns5	"http://schemas.datacontract.org/2004/07/Kill3rCombo.Model"
#define SOAP_NAMESPACE_OF_ns6	"http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses"
#include "stdsoap2.h"
#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (14)
/* xsd:boolean */
enum xsd__boolean {xsd__boolean__false_ = 0, xsd__boolean__true_ = 1};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_xsd__base64Binary
#define SOAP_TYPE_xsd__base64Binary (10)
/* Base64 schema type: */
struct xsd__base64Binary
{
	unsigned char *__ptr;
	int __size;
	char *id;	/* optional element of type xsd:string */
	char *type;	/* optional element of type xsd:string */
	char *options;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns3__Login
#define SOAP_TYPE__ns3__Login (22)
/* ns3:Login */
struct _ns3__Login
{
	char *username;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
	char *ip_USCOREaddress;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns3__LoginResponse
#define SOAP_TYPE__ns3__LoginResponse (23)
/* ns3:LoginResponse */
struct _ns3__LoginResponse
{
	char *LoginResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns3__Logout
#define SOAP_TYPE__ns3__Logout (24)
/* ns3:Logout */
struct _ns3__Logout
{
	char *username;	/* optional element of type xsd:string */
	char *ip_USCOREaddress;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns3__LogoutResponse
#define SOAP_TYPE__ns3__LogoutResponse (25)
/* ns3:LogoutResponse */
struct _ns3__LogoutResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns3__InsertBannedFromGame
#define SOAP_TYPE__ns3__InsertBannedFromGame (26)
/* ns3:InsertBannedFromGame */
struct _ns3__InsertBannedFromGame
{
	int *account_USCOREid;	/* optional element of type xsd:int */
	int *ban_USCOREreason;	/* optional element of type xsd:int */
	char *charname;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns3__InsertBannedFromGameResponse
#define SOAP_TYPE__ns3__InsertBannedFromGameResponse (28)
/* ns3:InsertBannedFromGameResponse */
struct _ns3__InsertBannedFromGameResponse
{
	int *InsertBannedFromGameResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE__ns3__GetSecurityQuestionsStatus
#define SOAP_TYPE__ns3__GetSecurityQuestionsStatus (29)
/* ns3:GetSecurityQuestionsStatus */
struct _ns3__GetSecurityQuestionsStatus
{
	int *account_USCOREid;	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE__ns3__GetSecurityQuestionsStatusResponse
#define SOAP_TYPE__ns3__GetSecurityQuestionsStatusResponse (30)
/* ns3:GetSecurityQuestionsStatusResponse */
struct _ns3__GetSecurityQuestionsStatusResponse
{
	char *GetSecurityQuestionsStatusResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns3__setGamePinQuestions
#define SOAP_TYPE__ns3__setGamePinQuestions (31)
/* ns3:setGamePinQuestions */
struct _ns3__setGamePinQuestions
{
	int *account_USCOREid;	/* optional element of type xsd:int */
	int *question1_USCOREid;	/* optional element of type xsd:int */
	char *question1_USCOREdetails;	/* optional element of type xsd:string */
	char *question1_USCOREanswer;	/* optional element of type xsd:string */
	int *question2_USCOREid;	/* optional element of type xsd:int */
	char *question2_USCOREdetails;	/* optional element of type xsd:string */
	char *question2_USCOREanswer;	/* optional element of type xsd:string */
	int *question3_USCOREid;	/* optional element of type xsd:int */
	char *question3_USCOREdetails;	/* optional element of type xsd:string */
	char *question3_USCOREanswer;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns3__setGamePinQuestionsResponse
#define SOAP_TYPE__ns3__setGamePinQuestionsResponse (32)
/* ns3:setGamePinQuestionsResponse */
struct _ns3__setGamePinQuestionsResponse
{
	int *setGamePinQuestionsResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE__ns3__getGamePinQuestions
#define SOAP_TYPE__ns3__getGamePinQuestions (33)
/* ns3:getGamePinQuestions */
struct _ns3__getGamePinQuestions
{
	int *account_USCOREid;	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE__ns3__getGamePinQuestionsResponse
#define SOAP_TYPE__ns3__getGamePinQuestionsResponse (34)
/* ns3:getGamePinQuestionsResponse */
struct _ns3__getGamePinQuestionsResponse
{
	struct ns5__GamePinSecretQuestions *getGamePinQuestionsResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns5:GamePinSecretQuestions */
};
#endif

#ifndef SOAP_TYPE__ns3__testerMethod
#define SOAP_TYPE__ns3__testerMethod (37)
/* ns3:testerMethod */
struct _ns3__testerMethod
{
	int *value;	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE__ns3__testerMethodResponse
#define SOAP_TYPE__ns3__testerMethodResponse (38)
/* ns3:testerMethodResponse */
struct _ns3__testerMethodResponse
{
	char *testerMethodResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns3__ValidateGamePinSession
#define SOAP_TYPE__ns3__ValidateGamePinSession (39)
/* ns3:ValidateGamePinSession */
struct _ns3__ValidateGamePinSession
{
	char *id;	/* optional element of type xsd:string */
	char *idac;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns3__ValidateGamePinSessionResponse
#define SOAP_TYPE__ns3__ValidateGamePinSessionResponse (40)
/* ns3:ValidateGamePinSessionResponse */
struct _ns3__ValidateGamePinSessionResponse
{
	char *ValidateGamePinSessionResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns3__RevokeGamePinSession
#define SOAP_TYPE__ns3__RevokeGamePinSession (41)
/* ns3:RevokeGamePinSession */
struct _ns3__RevokeGamePinSession
{
	int *account_USCOREid;	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE__ns3__RevokeGamePinSessionResponse
#define SOAP_TYPE__ns3__RevokeGamePinSessionResponse (42)
/* ns3:RevokeGamePinSessionResponse */
struct _ns3__RevokeGamePinSessionResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns3__AnswerGamePinQuestionsSuccess
#define SOAP_TYPE__ns3__AnswerGamePinQuestionsSuccess (43)
/* ns3:AnswerGamePinQuestionsSuccess */
struct _ns3__AnswerGamePinQuestionsSuccess
{
	int *account_USCOREid;	/* optional element of type xsd:int */
	char *IP;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns3__AnswerGamePinQuestionsSuccessResponse
#define SOAP_TYPE__ns3__AnswerGamePinQuestionsSuccessResponse (44)
/* ns3:AnswerGamePinQuestionsSuccessResponse */
struct _ns3__AnswerGamePinQuestionsSuccessResponse
{
	char *AnswerGamePinQuestionsSuccessResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns6__StructuralObject
#define SOAP_TYPE_ns6__StructuralObject (45)
/* ns6:StructuralObject */
struct ns6__StructuralObject
{
	char *ns4__Id;	/* optional attribute of type xsd:ID */
	char *ns4__Ref;	/* optional attribute of type xsd:IDREF */
};
#endif

#ifndef SOAP_TYPE_ns6__ComplexObject
#define SOAP_TYPE_ns6__ComplexObject (46)
/* ns6:ComplexObject */
struct ns6__ComplexObject
{
	char *ns4__Id;	/* optional attribute of type xsd:ID */
	char *ns4__Ref;	/* optional attribute of type xsd:IDREF */
};
#endif

#ifndef SOAP_TYPE_ns5__GamePinSecretQuestions
#define SOAP_TYPE_ns5__GamePinSecretQuestions (35)
/* ns5:GamePinSecretQuestions */
struct ns5__GamePinSecretQuestions
{
	char *ns4__Id;	/* optional attribute of type xsd:ID */
	char *ns4__Ref;	/* optional attribute of type xsd:IDREF */
	int *account_USCOREid;	/* optional element of type xsd:int */
	char *question1_USCOREanswer;	/* optional element of type xsd:string */
	char *question1_USCOREdetails;	/* optional element of type xsd:string */
	int *question1_USCOREid;	/* optional element of type xsd:int */
	char *question2_USCOREanswer;	/* optional element of type xsd:string */
	char *question2_USCOREdetails;	/* optional element of type xsd:string */
	int *question2_USCOREid;	/* optional element of type xsd:int */
	char *question3_USCOREanswer;	/* optional element of type xsd:string */
	char *question3_USCOREdetails;	/* optional element of type xsd:string */
	int *question3_USCOREid;	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE___ns1__Login
#define SOAP_TYPE___ns1__Login (50)
/* Operation wrapper: */
struct __ns1__Login
{
	struct _ns3__Login *ns3__Login;	/* optional element of type ns3:Login */
};
#endif

#ifndef SOAP_TYPE___ns1__Logout
#define SOAP_TYPE___ns1__Logout (54)
/* Operation wrapper: */
struct __ns1__Logout
{
	struct _ns3__Logout *ns3__Logout;	/* optional element of type ns3:Logout */
};
#endif

#ifndef SOAP_TYPE___ns1__InsertBannedFromGame
#define SOAP_TYPE___ns1__InsertBannedFromGame (58)
/* Operation wrapper: */
struct __ns1__InsertBannedFromGame
{
	struct _ns3__InsertBannedFromGame *ns3__InsertBannedFromGame;	/* optional element of type ns3:InsertBannedFromGame */
};
#endif

#ifndef SOAP_TYPE___ns1__GetSecurityQuestionsStatus
#define SOAP_TYPE___ns1__GetSecurityQuestionsStatus (62)
/* Operation wrapper: */
struct __ns1__GetSecurityQuestionsStatus
{
	struct _ns3__GetSecurityQuestionsStatus *ns3__GetSecurityQuestionsStatus;	/* optional element of type ns3:GetSecurityQuestionsStatus */
};
#endif

#ifndef SOAP_TYPE___ns1__setGamePinQuestions
#define SOAP_TYPE___ns1__setGamePinQuestions (66)
/* Operation wrapper: */
struct __ns1__setGamePinQuestions
{
	struct _ns3__setGamePinQuestions *ns3__setGamePinQuestions;	/* optional element of type ns3:setGamePinQuestions */
};
#endif

#ifndef SOAP_TYPE___ns1__getGamePinQuestions
#define SOAP_TYPE___ns1__getGamePinQuestions (70)
/* Operation wrapper: */
struct __ns1__getGamePinQuestions
{
	struct _ns3__getGamePinQuestions *ns3__getGamePinQuestions;	/* optional element of type ns3:getGamePinQuestions */
};
#endif

#ifndef SOAP_TYPE___ns1__testerMethod
#define SOAP_TYPE___ns1__testerMethod (74)
/* Operation wrapper: */
struct __ns1__testerMethod
{
	struct _ns3__testerMethod *ns3__testerMethod;	/* optional element of type ns3:testerMethod */
};
#endif

#ifndef SOAP_TYPE___ns1__ValidateGamePinSession
#define SOAP_TYPE___ns1__ValidateGamePinSession (78)
/* Operation wrapper: */
struct __ns1__ValidateGamePinSession
{
	struct _ns3__ValidateGamePinSession *ns3__ValidateGamePinSession;	/* optional element of type ns3:ValidateGamePinSession */
};
#endif

#ifndef SOAP_TYPE___ns1__RevokeGamePinSession
#define SOAP_TYPE___ns1__RevokeGamePinSession (82)
/* Operation wrapper: */
struct __ns1__RevokeGamePinSession
{
	struct _ns3__RevokeGamePinSession *ns3__RevokeGamePinSession;	/* optional element of type ns3:RevokeGamePinSession */
};
#endif

#ifndef SOAP_TYPE___ns1__AnswerGamePinQuestionsSuccess
#define SOAP_TYPE___ns1__AnswerGamePinQuestionsSuccess (86)
/* Operation wrapper: */
struct __ns1__AnswerGamePinQuestionsSuccess
{
	struct _ns3__AnswerGamePinQuestionsSuccess *ns3__AnswerGamePinQuestionsSuccess;	/* optional element of type ns3:AnswerGamePinQuestionsSuccess */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (87)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (88)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (90)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (93)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (94)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE_xsd__ID
#define SOAP_TYPE_xsd__ID (7)
typedef char *xsd__ID;
#endif

#ifndef SOAP_TYPE_xsd__IDREF
#define SOAP_TYPE_xsd__IDREF (8)
typedef char *xsd__IDREF;
#endif

#ifndef SOAP_TYPE_xsd__anyURI
#define SOAP_TYPE_xsd__anyURI (9)
typedef char *xsd__anyURI;
#endif

#ifndef SOAP_TYPE_xsd__byte
#define SOAP_TYPE_xsd__byte (15)
typedef char xsd__byte;
#endif

#ifndef SOAP_TYPE_xsd__decimal
#define SOAP_TYPE_xsd__decimal (16)
typedef char *xsd__decimal;
#endif

#ifndef SOAP_TYPE_xsd__duration
#define SOAP_TYPE_xsd__duration (17)
typedef char *xsd__duration;
#endif

#ifndef SOAP_TYPE_xsd__unsignedByte
#define SOAP_TYPE_xsd__unsignedByte (18)
typedef unsigned char xsd__unsignedByte;
#endif

#ifndef SOAP_TYPE_ns4__char
#define SOAP_TYPE_ns4__char (19)
typedef int ns4__char;
#endif

#ifndef SOAP_TYPE_ns4__duration
#define SOAP_TYPE_ns4__duration (20)
typedef char *ns4__duration;
#endif

#ifndef SOAP_TYPE_ns4__guid
#define SOAP_TYPE_ns4__guid (21)
typedef char *ns4__guid;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__Login(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns3__Login *ns3__Login, struct _ns3__LoginResponse *ns3__LoginResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__Logout(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns3__Logout *ns3__Logout, struct _ns3__LogoutResponse *ns3__LogoutResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__InsertBannedFromGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns3__InsertBannedFromGame *ns3__InsertBannedFromGame, struct _ns3__InsertBannedFromGameResponse *ns3__InsertBannedFromGameResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetSecurityQuestionsStatus(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns3__GetSecurityQuestionsStatus *ns3__GetSecurityQuestionsStatus, struct _ns3__GetSecurityQuestionsStatusResponse *ns3__GetSecurityQuestionsStatusResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__setGamePinQuestions(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns3__setGamePinQuestions *ns3__setGamePinQuestions, struct _ns3__setGamePinQuestionsResponse *ns3__setGamePinQuestionsResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getGamePinQuestions(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns3__getGamePinQuestions *ns3__getGamePinQuestions, struct _ns3__getGamePinQuestionsResponse *ns3__getGamePinQuestionsResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__testerMethod(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns3__testerMethod *ns3__testerMethod, struct _ns3__testerMethodResponse *ns3__testerMethodResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ValidateGamePinSession(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns3__ValidateGamePinSession *ns3__ValidateGamePinSession, struct _ns3__ValidateGamePinSessionResponse *ns3__ValidateGamePinSessionResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__RevokeGamePinSession(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns3__RevokeGamePinSession *ns3__RevokeGamePinSession, struct _ns3__RevokeGamePinSessionResponse *ns3__RevokeGamePinSessionResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__AnswerGamePinQuestionsSuccess(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns3__AnswerGamePinQuestionsSuccess *ns3__AnswerGamePinQuestionsSuccess, struct _ns3__AnswerGamePinQuestionsSuccessResponse *ns3__AnswerGamePinQuestionsSuccessResponse);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
