#pragma once

typedef srutil::delegate1<void, CX2GUNPC*> NPCFunc;
#define SET_NPC_FUNC(classname,funcname) NPCFunc::from_method<classname, &classname::funcname>(this)
#define SET_START_FUNC(npcID,stateName,classname,funcname) SetStartFunc( npcID, pNPC->GetStateID( stateName ), NPCFunc::from_method<classname, &classname::funcname>(this) )
#define SET_FRAME_MOVE_FUNC(npcID,stateName,classname,funcname) SetFrameMoveFunc( npcID, pNPC->GetStateID( stateName ), NPCFunc::from_method<classname, &classname::funcname>(this) )
#define SET_END_FUNC(npcID,stateName,classname,funcname) SetEndFunc( npcID, pNPC->GetStateID( stateName ), NPCFunc::from_method<classname, &classname::funcname>(this) )

#define SET_COMMON_FRAME_MOVE_FUNC(npcID,classname,funcname) SetCommonFrameMoveFunc( npcID, NPCFunc::from_method<classname, &classname::funcname>(this) )


class CX2GUUser;
class CX2GUNPC;
class CX2GUNPCFunc
{
	public:
		CX2GUNPCFunc(void);
		virtual ~CX2GUNPCFunc(void);

		void SetNPC( CX2GUNPC* pNPC );

		void StartFunc( CX2GUNPC* pNPC );
		void FrameMoveFunc( CX2GUNPC* pNPC );
		void EndFunc( CX2GUNPC* pNPC );

		void CommonFrameMoveFunc( CX2GUNPC* pNPC );

	private:
		void SetStartFunc( CX2UnitManager::NPC_UNIT_ID npcID, int stateID, NPCFunc npcFunc );
		void SetFrameMoveFunc( CX2UnitManager::NPC_UNIT_ID npcID, int stateID, NPCFunc npcFunc );
		void SetEndFunc( CX2UnitManager::NPC_UNIT_ID npcID, int stateID, NPCFunc npcFunc );

		void SetCommonFrameMoveFunc( CX2UnitManager::NPC_UNIT_ID npcID, NPCFunc npcFunc );

		// Bee.lua
		void BEE_FLY_STATE_START( CX2GUNPC* pNPCUnit );
		void BEE_FLY_FRAME_MOVE( CX2GUNPC* pNPCUnit );
		void BEE_JUMP_DOWN_STATE_END( CX2GUNPC* pNPCUnit );
		void BEE_JUMP_DOWN_DIR_STATE_END( CX2GUNPC* pNPCUnit );
		void BEE_DAMAGE_SMALL_FRAME_MOVE( CX2GUNPC* pNPCUnit );
		void BEE_DAMAGE_DOWN_FRAME_MOVE( CX2GUNPC* pNPCUnit );
		void BEE_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( CX2GUNPC* pNPCUnit );
		void BEE_DYING_LAND_STATE_START( CX2GUNPC* pNPCUnit );
        //void BEE_JUMP_DOWN_DIR_STATE_END

        // Bee_NoDrop.lua
        void BEE_NODROP_JUMP_DOWN_STATE_END( CX2GUNPC* pNPCUnit );
        void BEE_NODROP_JUMP_DOWN_DIR_STATE_END( CX2GUNPC* pNPCUnit );
        void BEE_NODROP_DAMAGE_SMALL_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BEE_NODROP_DAMAGE_DOWN_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BEE_NODROP_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BEE_NODROP_DYING_LAND_STATE_START( CX2GUNPC* pNPCUnit );

        // BeeBomb.lua
        void BEE_BOMB_ANGRY_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BEE_BOMB_JUMP_DOWN_STATE_END( CX2GUNPC* pNPCUnit );
        void BEE_BOMB_JUMP_DOWN_DIR_STATE_END( CX2GUNPC* pNPCUnit );
        void BEE_BOMB_BOMB_ATTACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BEE_BOMB_BOMB_EXPLODE_STATE_START( CX2GUNPC* pNPCUnit );
        void BEE_BOMB_DAMAGE_SMALL_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BEE_BOMB_DAMAGE_DOWN_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BEE_BOMB_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BEE_BOMB_DYING_LAND_STATE_START( CX2GUNPC* pNPCUnit );

        // BeeBomb_NoDrop.lua
        void BEE_BOMB_NODROP_ANGRY_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BEE_BOMB_NODROP_JUMP_DOWN_STATE_END( CX2GUNPC* pNPCUnit );
        void BEE_BOMB_NODROP_JUMP_DOWN_DIR_STATE_END( CX2GUNPC* pNPCUnit );
        void BEE_BOMB_NODROP_BOMB_ATTACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BEE_BOMB_NODROP_BOMB_EXPLODE_STATE_START( CX2GUNPC* pNPCUnit );
        void BEE_BOMB_NODROP_DAMAGE_SMALL_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BEE_BOMB_NODROP_DAMAGE_DOWN_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BEE_BOMB_NODROP_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BEE_BOMB_NODROP_DYING_LAND_STATE_START( CX2GUNPC* pNPCUnit );

        // BeePoison.lua (BeePoison_NoDrop)
        void BEE_POISON_JUMP_DOWN_STATE_END( CX2GUNPC* pNPCUnit );
        void BEE_POISON_JUMP_DOWN_DIR_STATE_END( CX2GUNPC* pNPCUnit );
        void BEE_POISON_DAMAGE_SMALL_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BEE_POISON_DAMAGE_DOWN_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BEE_POISON_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BEE_POISON_DYING_LAND_STATE_START( CX2GUNPC* pNPCUnit );

        // BeeAssault.lua
        void BEE_ASSAULT_JUMP_DOWN_STATE_END( CX2GUNPC* pNPCUnit );
        void BEE_ASSAULT_JUMP_DOWN_DIR_STATE_END( CX2GUNPC* pNPCUnit );
        void BEE_ASSAULT_BOMB_ATTACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BEE_ASSAULT_DAMAGE_SMALL_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BEE_ASSAULT_DAMAGE_DOWN_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BEE_ASSAULT_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BEE_ASSAULT_DYING_LAND_STATE_START( CX2GUNPC* pNPCUnit );

        // BeeHouse.lua
        void BEE_HOUSE_START_STATE_START( CX2GUNPC* pNPCUnit );
        void BEE_HOUSE_RESPAWN_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BEE_HOUSE_DYING_STATE_START( CX2GUNPC* pNPCUnit );

        // BeeBombHouse.lua
        void BEE_BOMB_HOUSE_START_STATE_START( CX2GUNPC* pNPCUnit );
        void BEE_BOMB_HOUSE_RESPAWN_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BEE_BOMB_HOUSE_DYING_STATE_START( CX2GUNPC* pNPCUnit );

        // BeePoisonHouse.lua
        void BEE_POISON_HOUSE_START_STATE_START( CX2GUNPC* pNPCUnit );
        void BEE_POISON_HOUSE_RESPAWN_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BEE_POISON_HOUSE_DYING_STATE_START( CX2GUNPC* pNPCUnit );

        // MonkeyA.lua 
        void MONKEY_A_WAIT2_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_A_WALK_STATE_END( CX2GUNPC* pNPCUnit );
        void MONKEY_A_WAIT3_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_A_JUMP_DOWN_STATE_END( CX2GUNPC* pNPCUnit );
        void MONKEY_A_JUMP_DOWN_DIR_STATE_END( CX2GUNPC* pNPCUnit );

		void MONKEY_A_FLY_READY_FRAME_MOVE( CX2GUNPC* pNPCUnit );

		void MONKEY_A_FLY_STATE_START( CX2GUNPC* pNPCUnit );
		void MONKEY_A_FLY_FRAME_MOVE( CX2GUNPC* pNPCUnit );

        void MONKEY_A_DAMAGE_SMALL_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_A_DAMAGE_BIG_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_A_DAMAGE_DOWN_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_A_DAMAGE_DOWN_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_A_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_A_STAND_UP_ATTACK_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_A_STAND_UP_ATTACK_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_A_DYING_LAND_STATE_START( CX2GUNPC* pNPCUnit );

        // MonkeyA_NoDrop.lua
        void MONKEY_A_NODROP_WAIT2_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_A_NODROP_WALK_STATE_END( CX2GUNPC* pNPCUnit );
        void MONKEY_A_NODROP_WAIT3_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_A_NODROP_JUMP_DOWN_STATE_END( CX2GUNPC* pNPCUnit );
        void MONKEY_A_NODROP_JUMP_DOWN_DIR_STATE_END( CX2GUNPC* pNPCUnit );
        void MONKEY_A_NODROP_DAMAGE_SMALL_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_A_NODROP_DAMAGE_BIG_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_A_NODROP_DAMAGE_DOWN_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_A_NODROP_DAMAGE_DOWN_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_A_NODROP_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_A_NODROP_STAND_UP_ATTACK_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_A_NODROP_STAND_UP_ATTACK_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_A_NODROP_DYING_LAND_STATE_START( CX2GUNPC* pNPCUnit );

        // MonkeyB.lua
        void MONKEY_B_WAIT2_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_B_WALK_STATE_END( CX2GUNPC* pNPCUnit );
        void MONKEY_B_WAIT3_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_B_JUMP_DOWN_STATE_END( CX2GUNPC* pNPCUnit );
        void MONKEY_B_JUMP_DOWN_DIR_STATE_END( CX2GUNPC* pNPCUnit );
        void MONKEY_B_PUNCH_PUNCH_ATTACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_B_DAMAGE_SMALL_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_B_DAMAGE_BIG_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_B_DAMAGE_DOWN_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_B_DAMAGE_DOWN_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_B_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_B_STAND_UP_ATTACK_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_B_STAND_UP_ATTACK_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_B_DYING_LAND_STATE_START( CX2GUNPC* pNPCUnit );

        // MonkeyB_NoDrop.lua
        void MONKEY_B_NODROP_WAIT2_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_B_NODROP_WALK_STATE_END( CX2GUNPC* pNPCUnit );
        void MONKEY_B_NODROP_WAIT3_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_B_NODROP_JUMP_DOWN_STATE_END( CX2GUNPC* pNPCUnit );
        void MONKEY_B_NODROP_JUMP_DOWN_DIR_STATE_END( CX2GUNPC* pNPCUnit );
        void MONKEY_B_NODROP_PUNCH_PUNCH_ATTACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_B_NODROP_DAMAGE_SMALL_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_B_NODROP_DAMAGE_BIG_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_B_NODROP_DAMAGE_DOWN_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_B_NODROP_DAMAGE_DOWN_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_B_NODROP_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_B_NODROP_STAND_UP_ATTACK_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_B_NODROP_STAND_UP_ATTACK_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_B_NODROP_DYING_LAND_STATE_START( CX2GUNPC* pNPCUnit );

        // MonkeyApple.lua 
        void MONKEY_APPLE_WAIT2_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_APPLE_WALK_STATE_END( CX2GUNPC* pNPCUnit );
        void MONKEY_APPLE_WAIT3_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_APPLE_JUMP_DOWN_STATE_END( CX2GUNPC* pNPCUnit );
        void MONKEY_APPLE_JUMP_DOWN_DIR_STATE_END( CX2GUNPC* pNPCUnit );
        void MONKEY_APPLE_APPLE_ATTACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
		
		void MONKEY_APPLE_WAIT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
		void MONKEY_APPLE_WALK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
		void MONKEY_APPLE_RIDE_HORSE_STATE_START( CX2GUNPC* pNPCUnit );
		void MONKEY_APPLE_RIDE_HORSE_FRAME_MOVE( CX2GUNPC* pNPCUnit );
		void MONKEY_APPLE_RIDE_APPLE_ATTACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
		void MONKEY_APPLE_LEAVE_HORSE_STATE_END( CX2GUNPC* pNPCUnit );

        void MONKEY_APPLE_DAMAGE_SMALL_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_APPLE_DAMAGE_BIG_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_APPLE_DAMAGE_DOWN_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_APPLE_DAMAGE_DOWN_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_APPLE_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_APPLE_STAND_UP_ATTACK_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_APPLE_STAND_UP_ATTACK_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_APPLE_DYING_LAND_STATE_START( CX2GUNPC* pNPCUnit );

        // MonkeyBomb.lua
        void MONKEY_BOMB_SIEGE_WAIT_STATE_START( CX2GUNPC* pNPCUnit );
        void MONKEY_BOMB_SIEGE_BOMB_ATTACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_BOMB_WAIT_STATE_START( CX2GUNPC* pNPCUnit );
        void MONKEY_BOMB_WAIT2_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_BOMB_WAIT3_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_BOMB_WALK_STATE_END( CX2GUNPC* pNPCUnit );
        void MONKEY_BOMB_JUMP_DOWN_STATE_END( CX2GUNPC* pNPCUnit );
        void MONKEY_BOMB_JUMP_DOWN_DIR_STATE_END( CX2GUNPC* pNPCUnit );
        void MONKEY_BOMB_BOMB_ATTACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_BOMB_DAMAGE_SMALL_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_BOMB_DAMAGE_BIG_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_BOMB_DAMAGE_DOWN_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_BOMB_DAMAGE_DOWN_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_BOMB_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_BOMB_STAND_UP_ATTACK_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_BOMB_STAND_UP_ATTACK_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_BOMB_DYING_LAND_STATE_START( CX2GUNPC* pNPCUnit );

        // MonkeyApple_NoDrop.lua 
        void MONKEY_APPLE_NODROP_WAIT2_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_APPLE_NODROP_WALK_STATE_END( CX2GUNPC* pNPCUnit );
        void MONKEY_APPLE_NODROP_WAIT3_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_APPLE_NODROP_JUMP_DOWN_STATE_END( CX2GUNPC* pNPCUnit );
        void MONKEY_APPLE_NODROP_JUMP_DOWN_DIR_STATE_END( CX2GUNPC* pNPCUnit );
        void MONKEY_APPLE_NODROP_APPLE_ATTACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );

        void MONKEY_APPLE_NODROP_DAMAGE_SMALL_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_APPLE_NODROP_DAMAGE_BIG_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_APPLE_NODROP_DAMAGE_DOWN_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_APPLE_NODROP_DAMAGE_DOWN_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_APPLE_NODROP_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_APPLE_NODROP_STAND_UP_ATTACK_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_APPLE_NODROP_STAND_UP_ATTACK_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_APPLE_NODROP_DYING_LAND_STATE_START( CX2GUNPC* pNPCUnit );

        // SmallGate_Green.lua
        void SMALL_GATE_GREEN_WAIT_START_STATE( CX2GUNPC* pNPCUnit );

        // SmallGate_Yellow.lua
        void SMALL_GATE_YELLOW_WAIT_START_STATE( CX2GUNPC* pNPCUnit );

        // SmallGate_Red.lua
        void SMALL_GATE_RED_WAIT_START_STATE( CX2GUNPC* pNPCUnit );

        // SmallGatePost.lua
        void SMALL_GATE_POST_BROKEN_START_STATE( CX2GUNPC* pNPCUnit );

        // Benders_Normal.lua        
        void BENDERS_WAIT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_WALK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_WALK_STATE_END( CX2GUNPC* pNPCUnit );
        void BENDERS_JUMP_DOWN_STATE_END( CX2GUNPC* pNPCUnit );
        void BENDERS_JUMP_DOWN_DIR_STATE_END( CX2GUNPC* pNPCUnit );
        void BENDERS_DASH_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_COMBO2_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_SUMMON_MONSTER_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_DAMAGE_SMALL_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_DAMAGE_BIG_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_DAMAGE_DOWN_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_DAMAGE_DOWN_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_STAND_UP_ATTACK_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_STAND_UP_ATTACK_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_DYING_LAND_STATE_START( CX2GUNPC* pNPCUnit );

        // Benders_Hard.lua        
        void BENDERS_HARD_WAIT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_HARD_WALK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_HARD_WALK_STATE_END( CX2GUNPC* pNPCUnit );
        void BENDERS_HARD_JUMP_DOWN_STATE_END( CX2GUNPC* pNPCUnit );
        void BENDERS_HARD_JUMP_DOWN_DIR_STATE_END( CX2GUNPC* pNPCUnit );
        void BENDERS_HARD_DASH_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_HARD_COMBO2_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_HARD_SUMMON_MONSTER_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_HARD_DAMAGE_SMALL_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_HARD_DAMAGE_BIG_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_HARD_DAMAGE_DOWN_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_HARD_DAMAGE_DOWN_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_HARD_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_HARD_STAND_UP_ATTACK_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_HARD_STAND_UP_ATTACK_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_HARD_DYING_LAND_STATE_START( CX2GUNPC* pNPCUnit );

        // Benders_Expert.lua        
        void BENDERS_EXPERT_WAIT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_EXPERT_WALK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_EXPERT_WALK_STATE_END( CX2GUNPC* pNPCUnit );
        void BENDERS_EXPERT_JUMP_DOWN_STATE_END( CX2GUNPC* pNPCUnit );
        void BENDERS_EXPERT_JUMP_DOWN_DIR_STATE_END( CX2GUNPC* pNPCUnit );
        void BENDERS_EXPERT_DASH_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_EXPERT_COMBO2_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_EXPERT_SUMMON_MONSTER_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_EXPERT_DAMAGE_SMALL_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_EXPERT_DAMAGE_BIG_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_EXPERT_DAMAGE_DOWN_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_EXPERT_DAMAGE_DOWN_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_EXPERT_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_EXPERT_STAND_UP_ATTACK_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_EXPERT_STAND_UP_ATTACK_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_EXPERT_DYING_LAND_STATE_START( CX2GUNPC* pNPCUnit );

        // Benders_B.lua        
        void BENDERS_B_WAIT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_B_WALK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_B_WALK_STATE_END( CX2GUNPC* pNPCUnit );
        void BENDERS_B_JUMP_DOWN_STATE_END( CX2GUNPC* pNPCUnit );
        void BENDERS_B_JUMP_DOWN_DIR_STATE_END( CX2GUNPC* pNPCUnit );
        void BENDERS_B_DASH_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_B_COMBO2_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_B_SUMMON_MONSTER_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_B_DAMAGE_SMALL_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_B_DAMAGE_BIG_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_B_DAMAGE_DOWN_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_B_DAMAGE_DOWN_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_B_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_B_STAND_UP_ATTACK_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_B_STAND_UP_ATTACK_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_B_DYING_LAND_STATE_START( CX2GUNPC* pNPCUnit );

        // BendersUpgrade_Normal.lua        
        void BENDERS_UPGRADE_NORMAL_WAIT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_NORMAL_WALK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_NORMAL_WALK_STATE_END( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_NORMAL_JUMP_DOWN_STATE_END( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_NORMAL_JUMP_DOWN_DIR_STATE_END( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_NORMAL_DASH_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_NORMAL_COMBO2_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_NORMAL_COMBO_A_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_NORMAL_SUMMON_MONSTER_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_NORMAL_DAMAGE_SMALL_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_NORMAL_DAMAGE_BIG_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_NORMAL_DAMAGE_DOWN_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_NORMAL_DAMAGE_DOWN_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_NORMAL_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_NORMAL_STAND_UP_ATTACK_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_NORMAL_STAND_UP_ATTACK_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_NORMAL_DYING_LAND_STATE_START( CX2GUNPC* pNPCUnit );

        // BendersUpgrade_Hard.lua        
        void BENDERS_UPGRADE_HARD_WAIT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_HARD_WALK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_HARD_WALK_STATE_END( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_HARD_JUMP_DOWN_STATE_END( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_HARD_JUMP_DOWN_DIR_STATE_END( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_HARD_DASH_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_HARD_COMBO2_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_HARD_COMBO_A_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_HARD_SUMMON_MONSTER_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_HARD_DAMAGE_SMALL_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_HARD_DAMAGE_BIG_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_HARD_DAMAGE_DOWN_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_HARD_DAMAGE_DOWN_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_HARD_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_HARD_STAND_UP_ATTACK_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_HARD_STAND_UP_ATTACK_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_HARD_DYING_LAND_STATE_START( CX2GUNPC* pNPCUnit );

        // BendersUpgrade_Expert.lua        
        void BENDERS_UPGRADE_EXPERT_WAIT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_EXPERT_WALK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_EXPERT_WALK_STATE_END( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_EXPERT_JUMP_DOWN_STATE_END( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_EXPERT_JUMP_DOWN_DIR_STATE_END( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_EXPERT_DASH_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_EXPERT_COMBO2_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_EXPERT_COMBO_A_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_EXPERT_SUMMON_MONSTER_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_EXPERT_DAMAGE_SMALL_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_EXPERT_DAMAGE_BIG_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_EXPERT_DAMAGE_DOWN_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_EXPERT_DAMAGE_DOWN_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_EXPERT_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_EXPERT_STAND_UP_ATTACK_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_EXPERT_STAND_UP_ATTACK_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void BENDERS_UPGRADE_EXPERT_DYING_LAND_STATE_START( CX2GUNPC* pNPCUnit );

        // ChainGate_Green.lua
        void CHAIN_GATE_GREEN_WAIT_START_STATE( CX2GUNPC* pNPCUnit );

        // ChainGate_Yellow.lua
        void CHAIN_GATE_YELLOW_WAIT_START_STATE( CX2GUNPC* pNPCUnit );

        // ChainGate_Red.lua
        void CHAIN_GATE_RED_WAIT_START_STATE( CX2GUNPC* pNPCUnit );

        // ChainGate_Extra.lua
        void CHAIN_GATE_EXTRA_WAIT_START_STATE( CX2GUNPC* pNPCUnit );

        // ChainGatePost.lua
        void CHAIN_GATE_POST_BROKEN_START_STATE( CX2GUNPC* pNPCUnit );

        // ChainGatePostExtra.lua
        void CHAIN_GATE_POST_EXTRA_BROKEN_START_STATE( CX2GUNPC* pNPCUnit );

        //MonkeyBoss.lua
        void MONKEY_BOSS_WAIT2_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_BOSS_WAIT3_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_BOSS_WALK_STATE_END( CX2GUNPC* pNPCUnit );
        void MONKEY_BOSS_JUMP_DOWN_STATE_END( CX2GUNPC* pNPCUnit );
        void MONKEY_BOSS_JUMP_DOWN_DIR_STATE_END( CX2GUNPC* pNPCUnit );
        void MONKEY_BOSS_PUNCH_PUNCH_ATTACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_BOSS_DAMAGE_SMALL_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_BOSS_DAMAGE_BIG_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_BOSS_DAMAGE_DOWN_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_BOSS_DAMAGE_DOWN_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_BOSS_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_BOSS_STAND_UP_ATTACK_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_BOSS_STAND_UP_ATTACK_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MONKEY_BOSS_DYING_LAND_STATE_START( CX2GUNPC* pNPCUnit );

        //Mushroom.lua
        void MUSHROOM_WALK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MUSHROOM_WALK_STATE_END( CX2GUNPC* pNPCUnit );
        void MUSHROOM_JUMP_DOWN_STATE_END( CX2GUNPC* pNPCUnit );
        void MUSHROOM_JUMP_DOWN_DIR_STATE_END( CX2GUNPC* pNPCUnit );
        void MUSHROOM_DAMAGE_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MUSHROOM_DAMAGE_DOWN_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MUSHROOM_DAMAGE_DOWN_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MUSHROOM_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MUSHROOM_DYING_LAND_STATE_START( CX2GUNPC* pNPCUnit );
        
        //WoodenMushroom.lua
        void MUSHROOM_WOODEN_WALK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MUSHROOM_WOODEN_WALK_STATE_END( CX2GUNPC* pNPCUnit );
        void MUSHROOM_WOODEN_JUMP_DOWN_STATE_END( CX2GUNPC* pNPCUnit );
        void MUSHROOM_WOODEN_JUMP_DOWN_DIR_STATE_END( CX2GUNPC* pNPCUnit );
        void MUSHROOM_WOODEN_DAMAGE_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MUSHROOM_WOODEN_DAMAGE_DOWN_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MUSHROOM_WOODEN_DAMAGE_DOWN_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MUSHROOM_WOODEN_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void MUSHROOM_WOODEN_DYING_LAND_STATE_START( CX2GUNPC* pNPCUnit );

        //WilliamPporu_Normal.lua
        void WILLIAM_PPORU_WAIT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void WILLIAM_PPORU_WALK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void WILLIAM_PPORU_WALK_STATE_END( CX2GUNPC* pNPCUnit );
        void WILLIAM_PPORU_DASH_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void WILLIAM_PPORU_DASH_END_STATE_START( CX2GUNPC* pNPCUnit );
        void WILLIAM_PPORU_JUMP_DOWN_STATE_END( CX2GUNPC* pNPCUnit );
        void WILLIAM_PPORU_JUMP_DOWN_DIR_STATE_END( CX2GUNPC* pNPCUnit );
        void WILLIAM_PPORU_COMBO_ATTACK_A_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void WILLIAM_PPORU_DAMAGE_SMALL_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void WILLIAM_PPORU_DAMAGE_BIG_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void WILLIAM_PPORU_DAMAGE_DOWN_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void WILLIAM_PPORU_DAMAGE_DOWN_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void WILLIAM_PPORU_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void WILLIAM_PPORU_STAND_UP_ATTACK_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void WILLIAM_PPORU_STAND_UP_ATTACK_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void WILLIAM_PPORU_DYING_LAND_STATE_START( CX2GUNPC* pNPCUnit );
        
        //WilliamPporu_Hard.lua
        void WILLIAM_PPORU_HARD_WAIT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void WILLIAM_PPORU_HARD_WALK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void WILLIAM_PPORU_HARD_WALK_STATE_END( CX2GUNPC* pNPCUnit );
        void WILLIAM_PPORU_HARD_DASH_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void WILLIAM_PPORU_HARD_DASH_END_STATE_START( CX2GUNPC* pNPCUnit );
        void WILLIAM_PPORU_HARD_JUMP_DOWN_STATE_END( CX2GUNPC* pNPCUnit );
        void WILLIAM_PPORU_HARD_JUMP_DOWN_DIR_STATE_END( CX2GUNPC* pNPCUnit );
        void WILLIAM_PPORU_HARD_ATTACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void WILLIAM_PPORU_HARD_COMBO_ATTACK_A_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void WILLIAM_PPORU_HARD_DAMAGE_SMALL_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void WILLIAM_PPORU_HARD_DAMAGE_BIG_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void WILLIAM_PPORU_HARD_DAMAGE_DOWN_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void WILLIAM_PPORU_HARD_DAMAGE_DOWN_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void WILLIAM_PPORU_HARD_DAMAGE_AIR_DOWN_LANDING_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void WILLIAM_PPORU_HARD_STAND_UP_ATTACK_FRONT_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void WILLIAM_PPORU_HARD_STAND_UP_ATTACK_BACK_FRAME_MOVE( CX2GUNPC* pNPCUnit );
        void WILLIAM_PPORU_HARD_DYING_LAND_STATE_START( CX2GUNPC* pNPCUnit );

		//GiantPporu_Red.lua
		void GIANT_PPORU_RED_SPECIAL_ATTACK_A_FRAME_MOVE( CX2GUNPC* pNPCUnit );

		//NUI_BARRIERMACHINE_FIRE
		void BARRIER_CREATEMACHINE_FIRE_COMMON_FRAME_MOVE( CX2GUNPC* pNPCUnit );

		//NUI_BARRIERMACHINE_ICE
		void BARRIER_CREATEMACHINE_ICE_COMMON_FRAME_MOVE( CX2GUNPC* pNPCUnit );

		//NUI_NASOD_ELEMENT_FIRE
		void NASOD_ELEMENT_FIRE_COMMON_FRAME_MOVE( CX2GUNPC* pNPCUnit );

		//NUI_NASOD_ELEMENT_ICE
		void NASOD_ELEMENT_ICE_COMMON_FRAME_MOVE( CX2GUNPC* pNPCUnit );

		//NUI_BAT_A
		void BAT_A_FLY_STATE_START( CX2GUNPC* pNPCUnit );
		void BAT_A_FLY_FRAME_MOVE( CX2GUNPC* pNPCUnit );

		void MONSTER_FLY_START( CX2GUNPC* pNPCUnit, float fTime, float fAdjustHeight = 3.0f );
		void MONSTER_FLY_START_AT_HAVE_TARGET( CX2GUNPC* pNPCUnit, float fTime, float fAdjustHeight = 3.0f );
		void MONSTER_FLY_FRAME_MOVE( CX2GUNPC* pNPCUnit );

		void MONSTER_FLY_START_CALCULATE( CX2GUNPC* pNPCUnit, float fTime, float fAdjustHeight, CX2GameUnit* pGameUnit_ );
		
		map< std::pair<CX2UnitManager::NPC_UNIT_ID, int>, NPCFunc > m_StartFuncMap;
		map< std::pair<CX2UnitManager::NPC_UNIT_ID, int>, NPCFunc > m_FrameMoveFuncMap;
		map< std::pair<CX2UnitManager::NPC_UNIT_ID, int>, NPCFunc > m_EndFuncMap;

		map< CX2UnitManager::NPC_UNIT_ID, NPCFunc > m_CommonFrameMoveFuncMap;


		//임시로 여기다가 살짝
		vector< CX2UnitManager::NPC_UNIT_ID > m_vecNpcIDForMonkeyApple;
		
};
