
#ifdef __NEVER_DEFINED_MACRO__
#define _ENUM(VAL) VAL,
enum
{
#endif

	_ENUM( EVENT_X2_BASE )

	_ENUM( EVENT_X2_SERVER_CONNECT_REQ )
	_ENUM( EVENT_X2_SERVER_CONNECT_ACK )

	_ENUM( EVENT_X2_SERVER_NEW_USER_JOIN_REQ )
	_ENUM( EVENT_X2_SERVER_NEW_USER_JOIN_ACK )

	_ENUM( EVENT_X2_SERVER_LOGIN_REQ )
	_ENUM( EVENT_X2_SERVER_LOGIN_ACK )

	_ENUM( EVENT_X2_SERVER_USER_INFO_REQ )
	_ENUM( EVENT_X2_SERVER_USER_INFO_ACK )

	_ENUM( EVENT_X2_SERVER_UNIT_INFO_REQ )
	_ENUM( EVENT_X2_SERVER_UNIT_INFO_ACK )

	_ENUM( EVENT_X2_SERVER_UNIT_INFO_LIST_REQ )
	_ENUM( EVENT_X2_SERVER_UNIT_INFO_LIST_ACK )

	_ENUM( EVENT_X2_SERVER_ITEM_INFO_REQ )
	_ENUM( EVENT_X2_SERVER_ITEM_INFO_ACK )

	_ENUM( EVENT_X2_SERVER_UNIT_INVENTORY_ITEM_LIST_REQ )
	_ENUM( EVENT_X2_SERVER_UNIT_INVENTORY_ITEM_LIST_ACK )

	_ENUM( EVENT_X2_SERVER_STATE_CHANGE_UNIT_SELECT_REQ )
	_ENUM( EVENT_X2_SERVER_STATE_CHANGE_UNIT_SELECT_ACK )

	_ENUM( EVENT_X2_SERVER_UNIT_SELECT_REQ )
	_ENUM( EVENT_X2_SERVER_UNIT_SELECT_ACK )

//	_ENUM( EVENT_X2_SERVER_STATE_CHANGE_MAIN_LOBBY_REQ )
//	_ENUM( EVENT_X2_SERVER_STATE_CHANGE_MAIN_LOBBY_ACK )

	_ENUM( EVENT_X2_SERVER_STATE_CHANGE_VILLAGE_MAP_REQ )
	_ENUM( EVENT_X2_SERVER_STATE_CHANGE_VILLAGE_MAP_ACK )

	_ENUM( EVENT_X2_SERVER_STATE_CHANGE_LOCAL_MAP_REQ )
	_ENUM( EVENT_X2_SERVER_STATE_CHANGE_LOCAL_MAP_ACK )

	_ENUM( EVENT_X2_SERVER_STATE_CHANGE_WORLD_MAP_REQ )
	_ENUM( EVENT_X2_SERVER_STATE_CHANGE_WORLD_MAP_ACK )

	_ENUM( EVENT_X2_SERVER_STATE_CHANGE_CREATE_UNIT_REQ )
	_ENUM( EVENT_X2_SERVER_STATE_CHANGE_CREATE_UNIT_ACK )

	_ENUM( EVENT_X2_SERVER_CREATE_UNIT_REQ )
	_ENUM( EVENT_X2_SERVER_CREATE_UNIT_ACK )

	_ENUM( EVENT_X2_SERVER_DELETE_UNIT_REQ )
	_ENUM( EVENT_X2_SERVER_DELETE_UNIT_ACK )

	_ENUM( EVENT_X2_SERVER_GET_PVP_CHANNEL_INFO_LIST_REQ )
	_ENUM( EVENT_X2_SERVER_GET_PVP_CHANNEL_INFO_LIST_ACK )

	_ENUM( EVENT_X2_SERVER_JOIN_PVP_CHANNEL_REQ )
	_ENUM( EVENT_X2_SERVER_JOIN_PVP_CHANNEL_ACK )

	_ENUM( EVENT_X2_SERVER_STATE_CHANGE_PVP_LOBBY_REQ )
	_ENUM( EVENT_X2_SERVER_STATE_CHANGE_PVP_LOBBY_ACK )

	_ENUM( EVENT_X2_SERVER_GET_PVP_ROOM_SIMPLE_INFO_LIST_REQ )
	_ENUM( EVENT_X2_SERVER_GET_PVP_ROOM_SIMPLE_INFO_LIST_ACK )
	_ENUM( EVENT_X2_SERVER_GET_PVP_ROOM_SIMPLE_INFO_LIST_NOT )

	_ENUM( EVENT_X2_SERVER_CREATE_PVP_ROOM_REQ )
	_ENUM( EVENT_X2_SERVER_CREATE_PVP_ROOM_ACK )

	_ENUM( EVENT_X2_SERVER_JOIN_PVP_ROOM_REQ )
	_ENUM( EVENT_X2_SERVER_JOIN_PVP_ROOM_ACK )

	_ENUM( EVENT_X2_SERVER_EXIT_PVP_ROOM_REQ )
	_ENUM( EVENT_X2_SERVER_EXIT_PVP_ROOM_ACK )

	_ENUM( EVENT_X2_SERVER_CHANGE_PVP_ROOM_INFO_REQ )
	_ENUM( EVENT_X2_SERVER_CHANGE_PVP_ROOM_INFO_ACK )

	_ENUM( EVENT_X2_SERVER_CHANGE_PVP_ROOM_SLOT_INFO_REQ )
	_ENUM( EVENT_X2_SERVER_CHANGE_PVP_ROOM_SLOT_INFO_ACK )

	_ENUM( EVENT_X2_SERVER_BROADCAST_PVP_ROOM_INFO_NOT )
	_ENUM( EVENT_X2_SERVER_BROADCAST_PVP_ROOM_SLOT_INFO_LIST_NOT )

	_ENUM( EVENT_X2_SERVER_PVP_ROOM_GAME_START_REQ )
	_ENUM( EVENT_X2_SERVER_PVP_ROOM_GAME_START_ACK )
	_ENUM( EVENT_X2_SERVER_BROADCAST_PVP_ROOM_GAME_START_NOT )

	_ENUM( EVENT_X2_SERVER_PVP_ROOM_GAME_HOST_READY_REQ )
	_ENUM( EVENT_X2_SERVER_PVP_ROOM_GAME_HOST_READY_ACK )
	_ENUM( EVENT_X2_SERVER_BROADCAST_PVP_ROOM_GAME_HOST_READY_NOT )

	_ENUM( EVENT_X2_SERVER_PVP_ROOM_GAME_LOADING_COMPLETE_REQ )
	_ENUM( EVENT_X2_SERVER_PVP_ROOM_GAME_LOADING_COMPLETE_ACK )
	_ENUM( EVENT_X2_SERVER_BROADCAST_PVP_ROOM_GAME_ALL_UNIT_LOADING_COMPLETE_NOT )
	_ENUM( EVENT_X2_SERVER_BROADCAST_PVP_ROOM_GAME_ONE_UNIT_LOADING_COMPLETE_NOT )

	_ENUM( EVENT_X2_SERVER_PVP_GAME_RESULT_REQ )
	_ENUM( EVENT_X2_SERVER_PVP_GAME_RESULT_ACK )
	_ENUM( EVENT_X2_SERVER_BROADCAST_PVP_GAME_RESULT_NOT )

	_ENUM( EVENT_X2_SERVER_STATE_CHANGE_PVP_GAME_RESULT_REQ )
	_ENUM( EVENT_X2_SERVER_STATE_CHANGE_PVP_GAME_RESULT_ACK )
	_ENUM( EVENT_X2_SERVER_BROADCAST_STATE_CHANGE_PVP_GAME_RESULT_NOT )

	_ENUM( EVENT_X2_SERVER_EXIT_PVP_GAME_REQ )
	_ENUM( EVENT_X2_SERVER_EXIT_PVP_GAME_ACK )

	_ENUM( EVENT_X2_SERVER_PVP_ROOM_CHAT_REQ )
	_ENUM( EVENT_X2_SERVER_PVP_ROOM_CHAT_ACK )
	_ENUM( EVENT_X2_SERVER_BROADCAST_PVP_ROOM_CHAT_NOT )

	_ENUM( EVENT_X2_SERVER_PVP_GAME_CHAT_REQ )
	_ENUM( EVENT_X2_SERVER_PVP_GAME_CHAT_ACK )
	_ENUM( EVENT_X2_SERVER_BROADCAST_PVP_GAME_CHAT_NOT )

	_ENUM( EVENT_X2_SERVER_BROADCAST_RELAY )

	//_ENUM( EVENT_X2_SERVER_END_PVP_GAME_REQ )
	//_ENUM( EVENT_X2_SERVER_END_PVP_GAME_ACK )
	//_ENUM( EVENT_X2_SERVER_BROADCAST_END_PVP_GAME_NOT )

	//_ENUM( EVENT_X2_SERVER_STATE_CHANGE_PVP_ROOM_REQ )
	//_ENUM( EVENT_X2_SERVER_STATE_CHANGE_PVP_ROOM_ACK )




	// DUNGEON_TEST!!
	_ENUM( EVENT_X2_SERVER_GET_DUNGEON_CHANNEL_INFO_LIST_REQ )
	_ENUM( EVENT_X2_SERVER_GET_DUNGEON_CHANNEL_INFO_LIST_ACK )

	_ENUM( EVENT_X2_SERVER_JOIN_DUNGEON_CHANNEL_REQ )
	_ENUM( EVENT_X2_SERVER_JOIN_DUNGEON_CHANNEL_ACK )

	_ENUM( EVENT_X2_SERVER_STATE_CHANGE_DUNGEON_LOBBY_REQ )
	_ENUM( EVENT_X2_SERVER_STATE_CHANGE_DUNGEON_LOBBY_ACK )

	_ENUM( EVENT_X2_SERVER_GET_DUNGEON_ROOM_SIMPLE_INFO_LIST_REQ )
	_ENUM( EVENT_X2_SERVER_GET_DUNGEON_ROOM_SIMPLE_INFO_LIST_ACK )
	_ENUM( EVENT_X2_SERVER_GET_DUNGEON_ROOM_SIMPLE_INFO_LIST_NOT )

	_ENUM( EVENT_X2_SERVER_CREATE_DUNGEON_ROOM_REQ )
	_ENUM( EVENT_X2_SERVER_CREATE_DUNGEON_ROOM_ACK )

	_ENUM( EVENT_X2_SERVER_JOIN_DUNGEON_ROOM_REQ )
	_ENUM( EVENT_X2_SERVER_JOIN_DUNGEON_ROOM_ACK )

	_ENUM( EVENT_X2_SERVER_EXIT_DUNGEON_ROOM_REQ )
	_ENUM( EVENT_X2_SERVER_EXIT_DUNGEON_ROOM_ACK )

	_ENUM( EVENT_X2_SERVER_CHANGE_DUNGEON_ROOM_INFO_REQ )
	_ENUM( EVENT_X2_SERVER_CHANGE_DUNGEON_ROOM_INFO_ACK )

	_ENUM( EVENT_X2_SERVER_CHANGE_DUNGEON_ROOM_SLOT_INFO_REQ )
	_ENUM( EVENT_X2_SERVER_CHANGE_DUNGEON_ROOM_SLOT_INFO_ACK )

	_ENUM( EVENT_X2_SERVER_BROADCAST_DUNGEON_ROOM_INFO_NOT )
	_ENUM( EVENT_X2_SERVER_BROADCAST_DUNGEON_ROOM_SLOT_INFO_LIST_NOT )

	_ENUM( EVENT_X2_SERVER_DUNGEON_ROOM_GAME_START_REQ )
	_ENUM( EVENT_X2_SERVER_DUNGEON_ROOM_GAME_START_ACK )
	_ENUM( EVENT_X2_SERVER_BROADCAST_DUNGEON_ROOM_GAME_START_NOT )

	_ENUM( EVENT_X2_SERVER_DUNGEON_ROOM_GAME_HOST_READY_REQ )
	_ENUM( EVENT_X2_SERVER_DUNGEON_ROOM_GAME_HOST_READY_ACK )
	_ENUM( EVENT_X2_SERVER_BROADCAST_DUNGEON_ROOM_GAME_HOST_READY_NOT )

	_ENUM( EVENT_X2_SERVER_DUNGEON_ROOM_GAME_LOADING_COMPLETE_REQ )
	_ENUM( EVENT_X2_SERVER_DUNGEON_ROOM_GAME_LOADING_COMPLETE_ACK )
	_ENUM( EVENT_X2_SERVER_BROADCAST_DUNGEON_ROOM_GAME_ALL_UNIT_LOADING_COMPLETE_NOT )
	_ENUM( EVENT_X2_SERVER_BROADCAST_DUNGEON_ROOM_GAME_ONE_UNIT_LOADING_COMPLETE_NOT )

	_ENUM( EVENT_X2_SERVER_DUNGEON_GAME_RESULT_REQ )
	_ENUM( EVENT_X2_SERVER_DUNGEON_GAME_RESULT_ACK )
	_ENUM( EVENT_X2_SERVER_BROADCAST_DUNGEON_GAME_RESULT_NOT )

	_ENUM( EVENT_X2_SERVER_STATE_CHANGE_DUNGEON_GAME_RESULT_REQ )
	_ENUM( EVENT_X2_SERVER_STATE_CHANGE_DUNGEON_GAME_RESULT_ACK )
	_ENUM( EVENT_X2_SERVER_BROADCAST_STATE_CHANGE_DUNGEON_GAME_RESULT_NOT )

	_ENUM( EVENT_X2_SERVER_EXIT_DUNGEON_GAME_REQ )
	_ENUM( EVENT_X2_SERVER_EXIT_DUNGEON_GAME_ACK )

	_ENUM( EVENT_X2_SERVER_DUNGEON_ROOM_CHAT_REQ )
	_ENUM( EVENT_X2_SERVER_DUNGEON_ROOM_CHAT_ACK )
	_ENUM( EVENT_X2_SERVER_BROADCAST_DUNGEON_ROOM_CHAT_NOT )

	_ENUM( EVENT_X2_SERVER_DUNGEON_GAME_CHAT_REQ )
	_ENUM( EVENT_X2_SERVER_DUNGEON_GAME_CHAT_ACK )
	_ENUM( EVENT_X2_SERVER_BROADCAST_DUNGEON_GAME_CHAT_NOT )




//////////////////////////////////////////////////////////////////////////
//DB 작업
	_ENUM( DB_EVENT_X2_SERVER_READ_USER_DATA_ACK )
	_ENUM( DB_EVENT_X2_SERVER_READ_UNIT_DATA_ACK )
	_ENUM( DB_EVENT_X2_SERVER_READ_UNIT_DATA_LIST_ACK )

	//패킷의 끝
	//_ENUM( EVENT_EVENTID_SENTINEL ) //패킷의 끝

#ifdef __NEVER_DEFINED_MACRO__
};
#undef _ENUM
#endif
