-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.


-- SMS문자 전송 번호
g_pCnHackingCheckManager:AddPhoneNum( '010-4118-3867' ) -- 김창호
g_pCnHackingCheckManager:AddPhoneNum( '010-9317-0790' ) -- 황정희
g_pCnHackingCheckManager:AddPhoneNum( '010-8421-1075' ) -- 최육사


-- 던전 결과 핵 유저 체크 여부
g_pCnHackingCheckManager:SetDungeonResultCheckEnable( False )	-- 해외팀 수정


-- 오토핵 유저의 던전 클리어 체크 조건
g_pCnHackingCheckManager:SetDungeonResultHackUserCheckData
{
	m_bClear			= True,
	m_iStartedMember	= 1,
	m_eComboRank		= RANK_TYPE["RT_F"],
	m_eTechnicalRank	= RANK_TYPE["RT_F"],
	m_eTimeRank			= RANK_TYPE["RT_S"],
	m_eDamagedRank		= RANK_TYPE["RT_S"],
	m_iTechnicalScore	= 0,
	m_iContinueCount	= 0,
	m_bHavePet			= False,
	m_iMinLevelCheck	= 20,

	CHECK_UNIT_CLASS =
	{
		UNIT_CLASS["UC_ELSWORD_SWORDMAN"],
		UNIT_CLASS["UC_ARME_VIOLET_MAGE"],
		UNIT_CLASS["UC_LIRE_ELVEN_RANGER"],
		UNIT_CLASS["UC_RAVEN_FIGHTER"],
		UNIT_CLASS["UC_EVE_NASOD"],
		UNIT_CLASS["UC_CHUNG_IRON_CANNON"],
	},

	NO_ADVENT_DUNGEON_TABLE =
	{
		DUNGEON_ID["DI_TUTORIAL_ELSWORD"],
		DUNGEON_ID["DI_TUTORIAL_ARME"],
		DUNGEON_ID["DI_TUTORIAL_LIRE"],
		DUNGEON_ID["DI_TUTORIAL_RAVEN"],
		DUNGEON_ID["DI_TUTORIAL_EVE"],
		DUNGEON_ID["DI_TUTORIAL_CHUNG"],
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		DUNGEON_ID["DI_BATTLE_SHIP_VELDER"],
		DUNGEON_ID["DI_BATTLE_SHIP_HAMEL"],
		DUNGEON_ID["DI_EVENT_TREE_DAY_ELDER"],
		DUNGEON_ID["DI_EVENT_TREE_DAY_BESMA"],
		DUNGEON_ID["DI_EVENT_TREE_DAY_ALTERA"],
		DUNGEON_ID["DI_EVENT_TREE_DAY_PEITA"],
		DUNGEON_ID["DI_EVENT_TREE_DAY_VELDER"],
		
		-- 디펜스 던전
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_EXPERT"],
	},
}



-- 던전 결과 핵 유저 체크 여부
g_pCnHackingCheckManager:SetDungeonClearTimeCheckEnable( False )	-- 해외팀 수정


-- 오토핵 유저의 던전 클리어 체크 조건
g_pCnHackingCheckManager:SetDungeonClearTimeHackUserCheckData
{
	m_bClear			= True,
	m_iStartedMember	= 1,
	m_iMinLevelCheck	= 20,
	m_iCheckPlayTime	= 40,

	CHECK_UNIT_CLASS =
	{
		UNIT_CLASS["UC_ELSWORD_SWORDMAN"],
		UNIT_CLASS["UC_ARME_VIOLET_MAGE"],
		UNIT_CLASS["UC_LIRE_ELVEN_RANGER"],
		UNIT_CLASS["UC_RAVEN_FIGHTER"],
		UNIT_CLASS["UC_EVE_NASOD"],
		UNIT_CLASS["UC_CHUNG_IRON_CANNON"],
		UNIT_CLASS["UC_ARA_MARTIAL_ARTIST"],
	},

	NO_ADVENT_DUNGEON_TABLE =
	{
		DUNGEON_ID["DI_TUTORIAL_ELSWORD"],
		DUNGEON_ID["DI_TUTORIAL_ARME"],
		DUNGEON_ID["DI_TUTORIAL_LIRE"],
		DUNGEON_ID["DI_TUTORIAL_RAVEN"],
		DUNGEON_ID["DI_TUTORIAL_EVE"],
		DUNGEON_ID["DI_TUTORIAL_CHUNG"],
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		DUNGEON_ID["DI_BATTLE_SHIP_VELDER"],
		DUNGEON_ID["DI_BATTLE_SHIP_HAMEL"],		
		DUNGEON_ID["DI_EVENT_TREE_DAY_ELDER"],
		DUNGEON_ID["DI_EVENT_TREE_DAY_BESMA"],
		DUNGEON_ID["DI_EVENT_TREE_DAY_ALTERA"],
		DUNGEON_ID["DI_EVENT_TREE_DAY_PEITA"],
		DUNGEON_ID["DI_EVENT_TREE_DAY_VELDER"],
		
		-- 디펜스 던전
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_EXPERT"],
	},
}


