----------------------------------------------------------------------
-- Des : 이파일은 GameServer 에서만 사용되어지고
-- XSLMapData => 유저의 이동체크를 위해
----------------------------------------------------------------------


MapData:AddMapData
{
	ID			= VILLAGE_MAP_ID["VMI_TUTORIAL"],
	
	BEFORE		= VILLAGE_MAP_ID["VMI_INVALID"],
	AFTER		= VILLAGE_MAP_ID["VMI_RUBEN"],

	REQUIRE_LEVEL = 
	{
		MIN = 1,
		MAX = 10,
	},
	
	REQUIRE_DUNGEON = 
	{
	},
}


MapData:AddMapData
{
	ID			= VILLAGE_MAP_ID["VMI_RUBEN"],
	
	BEFORE		= VILLAGE_MAP_ID["VMI_INVALID"],
	AFTER		= VILLAGE_MAP_ID["VMI_ELDER"],
	
	DEFAULT		= TRUE,
	
	REQUIRE_LEVEL = 
	{
		MIN = 1,
		MAX = 10,
	},
	
	REQUIRE_DUNGEON = 
	{
	},
}

MapData:AddMapData
{
	ID			= VILLAGE_MAP_ID["VMI_ELDER"],
	
	BEFORE		= VILLAGE_MAP_ID["VMI_RUBEN"],
	AFTER		= VILLAGE_MAP_ID["VMI_BESMA"],
	
	REQUIRE_LEVEL = 
	{
		MIN = 6,
		MAX = 20,
	},
	
	REQUIRE_DUNGEON = 
	{
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
	},
}

MapData:AddMapData
{
	ID			= VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ELDER_REST_00"],
	
	BEFORE		= VILLAGE_MAP_ID["VMI_INVALID"],
	AFTER		= VILLAGE_MAP_ID["VMI_INVALID"],
	
	REQUIRE_LEVEL = 
	{
		MIN = 6,
		MAX = 20,
	},
	
	REQUIRE_DUNGEON = 
	{
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
	},
}

MapData:AddMapData
{
	ID			= VILLAGE_MAP_ID["VMI_BESMA"],
	
	BEFORE		= VILLAGE_MAP_ID["VMI_ELDER"],
	AFTER		= VILLAGE_MAP_ID["VMI_ALTERA"],
	
	REQUIRE_LEVEL = 
	{
		MIN = 15,
		MAX = 30,
	},
	
	REQUIRE_DUNGEON = 
	{
		DUNGEON_ID["DI_ELDER_WALLY_CASTLE_CENTER_NORMAL"],
	},
}

MapData:AddMapData
{
	ID			= VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_REST_00"],
	
	BEFORE		= VILLAGE_MAP_ID["VMI_INVALID"],
	AFTER		= VILLAGE_MAP_ID["VMI_INVALID"],
	
	REQUIRE_LEVEL = 
	{
		MIN = 15,
		MAX = 30,
	},
	
	REQUIRE_DUNGEON = 
	{
		DUNGEON_ID["DI_ELDER_WALLY_CASTLE_CENTER_NORMAL"],
	},
}

MapData:AddMapData
{
	ID			= VILLAGE_MAP_ID["VMI_ALTERA"],
	
	BEFORE		= VILLAGE_MAP_ID["VMI_BESMA"],
	AFTER		= VILLAGE_MAP_ID["VMI_PEITA"],
	
	REQUIRE_LEVEL = 
	{
		MIN = 27,
		MAX = 40,
	},
	
	REQUIRE_DUNGEON = 
	{
		DUNGEON_ID["DI_BESMA_AIRSHIP_NORMAL"],
	},
}

MapData:AddMapData
{
	ID			= VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_REST_00"],
	
	BEFORE		= VILLAGE_MAP_ID["VMI_INVALID"],
	AFTER		= VILLAGE_MAP_ID["VMI_INVALID"],
	
	REQUIRE_LEVEL = 
	{
		MIN = 27,
		MAX = 40,
	},
	
	REQUIRE_DUNGEON = 
	{
		DUNGEON_ID["DI_BESMA_AIRSHIP_NORMAL"],
	},
}

MapData:AddMapData
{
	ID			= VILLAGE_MAP_ID["VMI_PEITA"],
	
	BEFORE		= VILLAGE_MAP_ID["VMI_ALTERA"],
	AFTER		= VILLAGE_MAP_ID["VMI_VELDER"],
	
	REQUIRE_LEVEL = 
	{
		MIN = 34,
		MAX = 50,
	},
	
	REQUIRE_DUNGEON = 
	{
		DUNGEON_ID["DI_ALTERA_CORE_NORMAL"],
	},
}

MapData:AddMapData
{
	ID			= VILLAGE_MAP_ID["VMI_BATTLE_FIELD_PEITA_REST_00"],
	
	BEFORE		= VILLAGE_MAP_ID["VMI_INVALID"],
	AFTER		= VILLAGE_MAP_ID["VMI_INVALID"],
	
	REQUIRE_LEVEL = 
	{
		MIN = 34,
		MAX = 50,
	},
	
	REQUIRE_DUNGEON = 
	{
		DUNGEON_ID["DI_ALTERA_CORE_NORMAL"],
	},
}

MapData:AddMapData
{
	ID			= VILLAGE_MAP_ID["VMI_VELDER"],
	
	BEFORE		= VILLAGE_MAP_ID["VMI_PEITA"],
	AFTER		= VILLAGE_MAP_ID["VMI_HAMEL"],
	
	REQUIRE_LEVEL = 
	{
		MIN = 41,
		MAX = 50,
	},
	
	REQUIRE_DUNGEON = 
	{
		DUNGEON_ID["DI_PEITA_OFFERINGS_ALTER_NORMAL"],
	},
}

MapData:AddMapData
{
	ID			= VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_REST_00"],
	
	BEFORE		= VILLAGE_MAP_ID["VMI_INVALID"],
	AFTER		= VILLAGE_MAP_ID["VMI_INVALID"],
	
	REQUIRE_LEVEL = 
	{
		MIN = 41,
		MAX = 50,
	},
	
	REQUIRE_DUNGEON = 
	{
		DUNGEON_ID["DI_PEITA_OFFERINGS_ALTER_NORMAL"],
	},
}

MapData:AddMapData
{
	ID			= VILLAGE_MAP_ID["VMI_HAMEL"],
	
	BEFORE		= VILLAGE_MAP_ID["VMI_VELDER"],
	AFTER		= VILLAGE_MAP_ID["VMI_NONE"],	-- NO_SANDER_VILLIAGE 사용시 VMI_SANDER 로 변경
	
	REQUIRE_LEVEL = 
	{
		MIN = 49,
		MAX = 60,
	},
	
	REQUIRE_DUNGEON = 
	{
		DUNGEON_ID["DI_VELDER_GATE_NORMAL"],
	},
}

MapData:AddMapData
{
	ID			= VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_REST_00"],
	
	BEFORE		= VILLAGE_MAP_ID["VMI_INVALID"],
	AFTER		= VILLAGE_MAP_ID["VMI_INVALID"],
	
	REQUIRE_LEVEL = 
	{
		MIN = 49,
		MAX = 60,
	},
	
	REQUIRE_DUNGEON = 
	{
		DUNGEON_ID["DI_VELDER_GATE_NORMAL"],
	},
}

MapData:AddMapData
{
	ID			= VILLAGE_MAP_ID["VMI_SANDER"],
	
	BEFORE		= VILLAGE_MAP_ID["VMI_HAMEL"],
	AFTER		= VILLAGE_MAP_ID["VMI_NONE"],
	
	REQUIRE_LEVEL = 
	{
		MIN = 55,
		MAX = 65,
	},
	
	REQUIRE_DUNGEON = 
	{
		DUNGEON_ID["DI_VELDER_GATE_NORMAL"],
	},
}

MapData:AddMapData
{
	ID			= VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_REST_00"],
	
	BEFORE		= VILLAGE_MAP_ID["VMI_INVALID"],
	AFTER		= VILLAGE_MAP_ID["VMI_INVALID"],
	
	REQUIRE_LEVEL = 
	{
		MIN = 55,
		MAX = 65,
	},
	
	REQUIRE_DUNGEON = 
	{
		DUNGEON_ID["DI_VELDER_GATE_NORMAL"],
	},
}

-- 로컬맵 정보 (루벤)
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_NORTH"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_NORTH"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_NORTH"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_RUBEN_SWAMP_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_NORTH"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_NORTH"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_NORTH"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_NORTH"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"] )


-- 로컬맵 정보 (엘더)
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_EAST"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_ELDER_DRUID_FOREST_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_EAST"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_ELDER_DRUID_FOREST_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_EAST"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_ELDER_DRUID_FOREST_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_EAST"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_ELDER_BENDERS_CAVE_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_EAST"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_ELDER_BENDERS_CAVE_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_EAST"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_ELDER_BENDERS_CAVE_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_EAST"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_ELDER_BELOW_PASSAGE_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_EAST"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_ELDER_BELOW_PASSAGE_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_EAST"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_ELDER_BELOW_PASSAGE_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_EAST"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_ELDER_WALLY_CASTLE_CENTER_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_EAST"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_ELDER_WALLY_CASTLE_CENTER_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_EAST"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_ELDER_WALLY_CASTLE_CENTER_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_EAST"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_ELDER_WALLY_CASTLE_ROOF_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_EAST"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_ELDER_WALLY_CASTLE_ROOF_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_EAST"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_ELDER_WALLY_CASTLE_ROOF_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_EAST"],	DUNGEON_MODE["DM_SECRET_NORMAL"],	DUNGEON_ID["DI_ELDER_SECRET_COMMON"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_EAST"],	DUNGEON_MODE["DM_SECRET_HELL"],		DUNGEON_ID["DI_ELDER_SECRET_HELL"] )


-- 로컬맵 정보 (베스마)
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_SOUTH"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_BESMA_DRAGON_ROAD_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_SOUTH"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_BESMA_DRAGON_ROAD_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_SOUTH"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_BESMA_DRAGON_ROAD_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_SOUTH"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_BESMA_LAKE_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_SOUTH"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_BESMA_LAKE_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_SOUTH"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_BESMA_LAKE_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_SOUTH"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_BESMA_LAKE_NIGHT_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_SOUTH"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_BESMA_LAKE_NIGHT_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_SOUTH"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_BESMA_LAKE_NIGHT_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_SOUTH"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_BESMA_DRAGON_NEST_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_SOUTH"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_BESMA_DRAGON_NEST_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_SOUTH"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_BESMA_DRAGON_NEST_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_SOUTH"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_BESMA_MINE_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_SOUTH"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_BESMA_MINE_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_SOUTH"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_BESMA_MINE_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_SOUTH"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_BESMA_MINE2_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_SOUTH"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_BESMA_MINE2_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_SOUTH"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_BESMA_MINE2_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_SOUTH"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_BESMA_AIRSHIP_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_SOUTH"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_BESMA_AIRSHIP_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_SOUTH"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_BESMA_AIRSHIP_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_SOUTH"],	DUNGEON_MODE["DM_SECRET_NORMAL"],	DUNGEON_ID["DI_BESMA_SECRET_COMMON"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_SOUTH"],	DUNGEON_MODE["DM_SECRET_HELL"],		DUNGEON_ID["DI_BESMA_SECRET_HELL"] )


-- 로컬맵 정보 (알테라)
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_ALTERA_ISLAND"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_ALTERA_BATTLE_AIR_SHIP_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_ALTERA_ISLAND"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_ALTERA_BATTLE_AIR_SHIP_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_ALTERA_ISLAND"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_ALTERA_BATTLE_AIR_SHIP_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_ALTERA_ISLAND"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_ALTERA_PLAIN_RECYCLE_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_ALTERA_ISLAND"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_ALTERA_PLAIN_RECYCLE_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_ALTERA_ISLAND"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_ALTERA_PLAIN_RECYCLE_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_ALTERA_ISLAND"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_ALTERA_BELOW_TUNNEL_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_ALTERA_ISLAND"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_ALTERA_BELOW_TUNNEL_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_ALTERA_ISLAND"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_ALTERA_BELOW_TUNNEL_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_ALTERA_ISLAND"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_ALTERA_PLAIN_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_ALTERA_ISLAND"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_ALTERA_PLAIN_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_ALTERA_ISLAND"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_ALTERA_PLAIN_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_ALTERA_ISLAND"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_ALTERA_NASOD_FACTORY_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_ALTERA_ISLAND"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_ALTERA_NASOD_FACTORY_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_ALTERA_ISLAND"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_ALTERA_NASOD_FACTORY_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_ALTERA_ISLAND"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_ALTERA_CORE_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_ALTERA_ISLAND"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_ALTERA_CORE_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_ALTERA_ISLAND"],	DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_ALTERA_CORE_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_SOUTH"],	DUNGEON_MODE["DM_SECRET_NORMAL"],	DUNGEON_ID["DI_ALTERA_SECRET_COMMON"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER_SOUTH"],	DUNGEON_MODE["DM_SECRET_HELL"],		DUNGEON_ID["DI_ALTERA_SECRET_HELL"] )


-- 로컬맵 정보 (페이타)
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_PEITA"],			DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_PEITA_OFFERINGS_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_PEITA"],			DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_PEITA_OFFERINGS_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_PEITA"],			DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_PEITA_OFFERINGS_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_PEITA"],			DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_PEITA_SPIRAL_CORRIDOR_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_PEITA"],			DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_PEITA_SPIRAL_CORRIDOR_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_PEITA"],			DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_PEITA_SPIRAL_CORRIDOR_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_PEITA"],			DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_PEITA_CHAPEL_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_PEITA"],			DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_PEITA_CHAPEL_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_PEITA"],			DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_PEITA_CHAPEL_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_PEITA"],			DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_PEITA_UNDER_GARDEN_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_PEITA"],			DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_PEITA_UNDER_GARDEN_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_PEITA"],			DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_PEITA_UNDER_GARDEN_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_PEITA"],			DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_PEITA_TOWER_HEART_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_PEITA"],			DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_PEITA_TOWER_HEART_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_PEITA"],			DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_PEITA_TOWER_HEART_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_PEITA"],			DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_PEITA_OFFERINGS_ALTER_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_PEITA"],			DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_PEITA_OFFERINGS_ALTER_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_PEITA"],			DUNGEON_MODE["DM_INVALID"],			DUNGEON_ID["DI_PEITA_OFFERINGS_ALTER_EXPERT"] )


-- 로컬맵 정보 (벨더)
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER"],		DUNGEON_MODE["DM_INVALID"], 		DUNGEON_ID["DI_VELDER_THIRD_DWELLING_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER"],		DUNGEON_MODE["DM_INVALID"], 		DUNGEON_ID["DI_VELDER_THIRD_DWELLING_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER"],		DUNGEON_MODE["DM_INVALID"], 		DUNGEON_ID["DI_VELDER_THIRD_DWELLING_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER"],		DUNGEON_MODE["DM_INVALID"], 		DUNGEON_ID["DI_VELDER_BRIDGE_HOPE_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER"],		DUNGEON_MODE["DM_INVALID"], 		DUNGEON_ID["DI_VELDER_BRIDGE_HOPE_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER"],		DUNGEON_MODE["DM_INVALID"], 		DUNGEON_ID["DI_VELDER_BRIDGE_HOPE_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER"],		DUNGEON_MODE["DM_INVALID"], 		DUNGEON_ID["DI_VELDER_PALACE_ENTRANCE_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER"],		DUNGEON_MODE["DM_INVALID"], 		DUNGEON_ID["DI_VELDER_PALACE_ENTRANCE_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER"],		DUNGEON_MODE["DM_INVALID"], 		DUNGEON_ID["DI_VELDER_PALACE_ENTRANCE_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER"],		DUNGEON_MODE["DM_INVALID"], 		DUNGEON_ID["DI_VELDER_BRIDGE_BUNNING_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER"],		DUNGEON_MODE["DM_INVALID"], 		DUNGEON_ID["DI_VELDER_BRIDGE_BUNNING_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER"],		DUNGEON_MODE["DM_INVALID"], 		DUNGEON_ID["DI_VELDER_BRIDGE_BUNNING_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER"],		DUNGEON_MODE["DM_INVALID"], 		DUNGEON_ID["DI_VELDER_MARKET_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER"],		DUNGEON_MODE["DM_INVALID"], 		DUNGEON_ID["DI_VELDER_MARKET_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER"],		DUNGEON_MODE["DM_INVALID"], 		DUNGEON_ID["DI_VELDER_MARKET_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER"],		DUNGEON_MODE["DM_INVALID"], 		DUNGEON_ID["DI_VELDER_GATE_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER"],		DUNGEON_MODE["DM_INVALID"], 		DUNGEON_ID["DI_VELDER_GATE_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER"],		DUNGEON_MODE["DM_INVALID"], 		DUNGEON_ID["DI_VELDER_GATE_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER"],		DUNGEON_MODE["DM_SECRET_NORMAL"], 	DUNGEON_ID["DI_VELDER_SECRET_COMMON"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_VELDER"],		DUNGEON_MODE["DM_SECRET_HELL"], 	DUNGEON_ID["DI_VELDER_SECRET_HELL"] )


-- 로컬맵 정보 (하멜)
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_HAMEL"],			DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_HAMEL_OUTSKIRTS_RESIAM_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_HAMEL"],			DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_HAMEL_OUTSKIRTS_RESIAM_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_HAMEL"],			DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_HAMEL_OUTSKIRTS_RESIAM_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_HAMEL"],			DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_HAMEL_BREAK_RESIAM_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_HAMEL"],			DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_HAMEL_BREAK_RESIAM_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_HAMEL"],			DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_HAMEL_BREAK_RESIAM_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_HAMEL"],			DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_HAMEL_ANCIENT_WATERWAY_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_HAMEL"],			DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_HAMEL_ANCIENT_WATERWAY_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_HAMEL"],			DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_HAMEL_ANCIENT_WATERWAY_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_HAMEL"],			DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_HAMEL_ANCIENT_WATERWAY_CORE_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_HAMEL"],			DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_HAMEL_ANCIENT_WATERWAY_CORE_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_HAMEL"],			DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_HAMEL_ANCIENT_WATERWAY_CORE_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_HAMEL"],			DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_HAMEL_CAVE_OF_MAGMANTA_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_HAMEL"],			DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_HAMEL_CAVE_OF_MAGMANTA_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_HAMEL"],			DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_HAMEL_CAVE_OF_MAGMANTA_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_HAMEL"],			DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_HAMEL_FROZEN_WATER_TEMPLE_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_HAMEL"],			DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_HAMEL_FROZEN_WATER_TEMPLE_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_HAMEL"],			DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_HAMEL_FROZEN_WATER_TEMPLE_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_HAMEL"],			DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_HAMEL_FROZEN_WATER_HALL_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_HAMEL"],			DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_HAMEL_FROZEN_WATER_HALL_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_HAMEL"],			DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_HAMEL_FROZEN_WATER_HALL_EXPERT"] )

-- 로컬맵 정보 (센더)
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_SANDER"],		DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_SANDER_DRY_SANDER_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_SANDER"],		DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_SANDER_DRY_SANDER_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_SANDER"],		DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_SANDER_DRY_SANDER_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_SANDER"],		DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_SANDER_GARPAI_ROCK_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_SANDER"],		DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_SANDER_GARPAI_ROCK_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_SANDER"],		DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_SANDER_GARPAI_ROCK_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_SANDER"],		DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_SANDER_DEN_OF_TROCK_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_SANDER"],		DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_SANDER_DEN_OF_TROCK_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_SANDER"],		DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_SANDER_DEN_OF_TROCK_EXPERT"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_SANDER"],		DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_SANDER_KARUSO_VILLAGE_NORMAL"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_SANDER"],		DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_SANDER_KARUSO_VILLAGE_HARD"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_SANDER"],		DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_SANDER_KARUSO_VILLAGE_EXPERT"] )

-- 로컬맵 정보 (천조)
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_CHINA"],			DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_CHINA_EMPEROR_CITY"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_CHINA"],			DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_CHINA_MAGIC_CITY"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_CHINA"],			DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_CHINA_ELF_CITY"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_CHINA"],			DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_CHINA_JANGAN"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_CHINA"],			DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_CHINA_FACHOK"] )
MapData:AddLocalMapInfo( LOCAL_MAP_ID["LMI_CHINA"],			DUNGEON_MODE["DM_INVALID"],		 	DUNGEON_ID["DI_CHINA_DEVIL"] )


----------------------------------------------
-- 코보 익스프레스 VIP 티켓 유효한 필드 체크
----------------------------------------------
function CheckCOBOExpressTicketMapID( iMapID )

	-- 루벤
	if (iMapID == VILLAGE_MAP_ID["VMI_RUBEN"]) then
		return 1
	elseif (iMapID == VILLAGE_MAP_ID["VMI_BATTLE_FIELD_RUBEN_FIELD_01"]) then
		return 1
	
	-- 엘더
	elseif (iMapID == VILLAGE_MAP_ID["VMI_ELDER"]) then
		return 2
	elseif (iMapID == VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ELDER_FIELD_01"]) then
		return 2
	elseif (iMapID == VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ELDER_FIELD_02"]) then
		return 2
		
	elseif (iMapID == VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ELDER_REST_00"]) then
		return 3
		
	-- 베스마
	elseif (iMapID == VILLAGE_MAP_ID["VMI_BESMA"]) then
		return 4
	elseif (iMapID == VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_01"]) then
		return 4
	elseif (iMapID == VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_02"]) then
		return 4
	elseif (iMapID == VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_03"]) then
		return 4
		
	elseif (iMapID == VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_REST_00"]) then
		return 5
		
	-- 알테라
	elseif (iMapID == VILLAGE_MAP_ID["VMI_ALTERA"]) then
		return 6
	elseif (iMapID == VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_01"]) then
		return 6
	elseif (iMapID == VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_02"]) then
		return 6
	elseif (iMapID == VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_03"]) then
		return 6
		
	elseif (iMapID == VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_REST_00"]) then
		return 7
		
	-- 페이타
	elseif (iMapID == VILLAGE_MAP_ID["VMI_PEITA"]) then
		return 8
	elseif (iMapID == VILLAGE_MAP_ID["VMI_BATTLE_FIELD_PEITA_FIELD_01"]) then
		return 8
	elseif (iMapID == VILLAGE_MAP_ID["VMI_BATTLE_FIELD_PEITA_FIELD_02"]) then
		return 8
	elseif (iMapID == VILLAGE_MAP_ID["VMI_BATTLE_FIELD_PEITA_FIELD_03"]) then
		return 8
	
	-- 벨더
	elseif (iMapID == VILLAGE_MAP_ID["VMI_VELDER"]) then
		return 9
	elseif (iMapID == VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_01"]) then
		return 9
	elseif (iMapID == VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_02"]) then
		return 9
	elseif (iMapID == VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_03"]) then
		return 9
	elseif (iMapID == VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_04"]) then
		return 9
		
	elseif (iMapID == VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_REST_00"]) then
		return 10
		
	-- 하멜
	elseif (iMapID == VILLAGE_MAP_ID["VMI_HAMEL"]) then
		return 11
	elseif (iMapID == VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_01"]) then
		return 11
	elseif (iMapID == VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_02"]) then
		return 11
	elseif (iMapID == VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_03"]) then
		return 11
	elseif (iMapID == VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_04"]) then
		return 11
	elseif (iMapID == VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_SHIP_STAGE"]) then
		return 11
	elseif (iMapID == VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_SHIP_STAGE"]) then
		return 11
		
	elseif (iMapID == VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_REST_00"]) then
		return 12
	
	-- 샌더
	elseif (iMapID == VILLAGE_MAP_ID["VMI_SANDER"]) then
		return 13
	elseif (iMapID == VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_01"]) then
		return 13
	elseif (iMapID == VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_02"]) then
		return 13
	elseif (iMapID == VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_03"]) then
		return 13
	elseif (iMapID == VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_04"]) then
		return 13
		
	elseif (iMapID == VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_REST_00"]) then
		return 14
	end

    return 0
end


----------------------------------------------
-- 코보 익스프레스 VIP 티켓 비용 계산
----------------------------------------------
function ComputeCOBOExpressTicketCost( iSrcMapID, iDesMapID, ucLevel )

	local A = 6000
	local B = 0.6
	local d = 0
	local iSrcID = CheckCOBOExpressTicketMapID( iSrcMapID )	
	local iDesID = CheckCOBOExpressTicketMapID( iDesMapID )
	
	if ( (iSrcID == 0) or (iDesID == 0) ) then
		d = math.abs( iDesMapID - iSrcMapID )
	else
		d = math.abs( iDesID - iSrcID )
	end
	
	return ( ucLevel / 60.0 ) * ( A + A * B * ( d - 1 ) )
end
