-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.


-- 기본적으로 튜토리얼, 훈련소, 헤니르시공은 출현하지 않도록 되어 있습니다.



----공존의 축제 불안정한 엘 ----
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 1,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	--m_bAllyNpc = True,				--아군 몬스터 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_DARK_CRYSTAL"],
			ADVENT_RATE = 100,
		},
	},
	
	m_iAddLevel 	= 0,      		   -- 몬스터 레벨
	m_bDrop			= True,            -- 드롭 여부 / true = 드롭 함
	--m_bAggressive	= True,  		   -- 선/비 선공 / true = 선공
	--m_fAddPosY 		= 0.0,         -- 몬스터 높이값 설치 
	
	
	---필드-------
	ADVENT_FIELD_TABLE =               -- 몬스터 출현 필드 
	{
								--설정 안하면 모든 필드에 출현
	},
	   
	NO_ADVENT_FIELD_TABLE =      -- 지정된 필드에서는 출현하지 않습니다.(설정 안하면 모든 필드에 출현)
	{
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_RUBEN_FIELD_01"],
	},
	
	---던전---------
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
		DUNGEON_ID["DI_END"],
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_EXPERT"],
	},
	
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 130807/오현택/배커전야
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 2,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	--m_bAllyNpc = True,				--아군 몬스터 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_JOKE_PPORU"],
			ADVENT_RATE = 50,
		},
	},
	
	m_iAddLevel 	= 0,      		   -- 몬스터 레벨
	m_bDrop			= True,            -- 드롭 여부 / true = 드롭 함
	--m_bAggressive	= True,  		   -- 선/비 선공 / true = 선공
	--m_fAddPosY 		= 0.0,         -- 몬스터 높이값 설치 
	
	
	---필드-------
	ADVENT_FIELD_TABLE =               -- 몬스터 출현 필드 
	{
								--설정 안하면 모든 필드에 출현
	},
	   
	NO_ADVENT_FIELD_TABLE =      -- 지정된 필드에서는 출현하지 않습니다.(설정 안하면 모든 필드에 출현)
	{
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_RUBEN_FIELD_01"],
	},
	
	---던전---------
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
		DUNGEON_ID["DI_END"],
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_EXPERT"],
	},
	
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 130807/오현택/베커
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 3,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	--m_bAllyNpc = True,				--아군 몬스터 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_GHOST_PPORU"],
			ADVENT_RATE = 50,
		},
	},
	
	m_iAddLevel 	= 0,      		   -- 몬스터 레벨
	m_bDrop			= True,            -- 드롭 여부 / true = 드롭 함
	--m_bAggressive	= True,  		   -- 선/비 선공 / true = 선공
	--m_fAddPosY 		= 0.0,         -- 몬스터 높이값 설치 
	
	
	---필드-------
	ADVENT_FIELD_TABLE =               -- 몬스터 출현 필드 
	{
								--설정 안하면 모든 필드에 출현
	},
	   
	NO_ADVENT_FIELD_TABLE =      -- 지정된 필드에서는 출현하지 않습니다.(설정 안하면 모든 필드에 출현)
	{
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_RUBEN_FIELD_01"],
	},
	
	---던전---------
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
		DUNGEON_ID["DI_END"],
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_EXPERT"],
	},
	
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 130904/오현택/도둑 뽀루
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 4,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_JOKE_PPORU"],
			ADVENT_RATE = 80,
		},
	},
	
	m_iAddLevel 	= 0,      		   -- 몬스터 레벨
	m_bDrop			= True,            -- 드롭 여부 / true = 드롭 함
	
	---필드-------
	ADVENT_FIELD_TABLE =					-- 몬스터 출현 필드 
	{
		VILLAGE_MAP_ID["VMI_INVALID"],		-- 설정 안하면 모든 필드에 출현
	},
	   
	NO_ADVENT_FIELD_TABLE =					-- 지정된 필드에서는 출현하지 않습니다.(설정 안하면 모든 필드에 출현)
	{
	
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_EXPERT"],		
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 131218/이경철/어둠의 문 시즌 3 개편 이벤트
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 5,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_GHOST_PPORU"],	-- 다크엘프 스나이퍼
			ADVENT_RATE = 10,
			IS_ACTIVE = FALSE,
		},
		
		{
			NPC_ID		= NPC_UNIT_ID["NUI_FLAME_RED_EVENT"],	-- 글리터 정예 돌격병
			ADVENT_RATE = 10,
			IS_ACTIVE = FALSE,
		},
		
		{
			NPC_ID		= NPC_UNIT_ID["NUI_FLAME_BLUE_EVENT"],	-- 정예 코카트리글
			ADVENT_RATE = 10,
			IS_ACTIVE = FALSE,
		},
		
		{
			NPC_ID		= NPC_UNIT_ID["NUI_JOKE_PPORU"],	-- 포트 쉐도우 스팅어
			ADVENT_RATE = 10,
			IS_ACTIVE = FALSE,
		},
	},
	
	---필드-------
	ADVENT_FIELD_TABLE =               -- 몬스터 출현 필드 
	{
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ELDER_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ELDER_FIELD_02"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_03"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_03"],
	},
	   
	NO_ADVENT_FIELD_TABLE =      -- 지정된 필드에서는 출현하지 않습니다.(설정 안하면 모든 필드에 출현)
	{
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_RUBEN_FIELD_01"],
	},
	
	---던전---------
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
			DUNGEON_ID["DI_END"],
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{

	},
	
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}


-- 140122/오현택/소마이벤트
-- 131212/임홍락/란 짜응
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 6,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	--m_bAllyNpc = True,				--아군 몬스터 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_FLAME_RED_EVENT"],
			ADVENT_RATE = 50,
			IS_ACTIVE = FALSE,
		},
	},
	
	m_iAddLevel 	= 0,      		   -- 몬스터 레벨
	m_bDrop			= True,            -- 드롭 여부 / true = 드롭 함
	--m_bAggressive	= True,  		   -- 선/비 선공 / true = 선공
	--m_fAddPosY 		= 0.0,         -- 몬스터 높이값 설치 
	
	
	---필드-------
	ADVENT_FIELD_TABLE =					-- 몬스터 출현 필드 
	{
		VILLAGE_MAP_ID["VMI_INVALID"],		-- 설정 안하면 모든 필드에 출현
	},
	   
	NO_ADVENT_FIELD_TABLE =					-- 지정된 필드에서는 출현하지 않습니다.(설정 안하면 모든 필드에 출현)
	{
	
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_EXPERT"],	

		DUNGEON_ID["DI_ELDER_SECRET_COMMON"],
		DUNGEON_ID["DI_ELDER_SECRET_HELL"],
		DUNGEON_ID["DI_BESMA_SECRET_COMMON"],
		DUNGEON_ID["DI_BESMA_SECRET_HELL"],
		DUNGEON_ID["DI_ALTERA_SECRET_COMMON"],
		DUNGEON_ID["DI_ALTERA_SECRET_HELL"],
		DUNGEON_ID["DI_VELDER_SECRET_COMMON"],
		DUNGEON_ID["DI_VELDER_SECRET_HELL"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 131212/임홍락/란 짜응
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 7,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_FLAME_BLUE_EVENT"],	-- 턱시도 뽀루
			ADVENT_RATE = 30,
			IS_ACTIVE = FALSE,
		},
	},
	
	---필드-------
	ADVENT_FIELD_TABLE =               -- 몬스터 출현 필드 
	{
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ELDER_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ELDER_FIELD_02"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_03"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_03"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_PEITA_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_PEITA_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_PEITA_FIELD_03"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_03"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_04"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_03"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_04"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_SHIP_STAGE"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_SHIP_STAGE"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_03"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_04"],
	},
	   
	NO_ADVENT_FIELD_TABLE =      -- 지정된 필드에서는 출현하지 않습니다.(설정 안하면 모든 필드에 출현)
	{
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_RUBEN_FIELD_01"],
	},
	
	---던전---------
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
			DUNGEON_ID["DI_END"],
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{

	},
	
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}


-- 140122/오현택/명왕이벤트
-- 131212/임홍락/란 짜응/2차 전직 World War 이벤트 테스트용
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 8,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	--m_bAllyNpc = True,				--아군 몬스터 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_JOKE_PPORU"],
			ADVENT_RATE = 100,
			IS_ACTIVE = FALSE,
		},
	},
	
	m_iAddLevel 	= 0,      		   -- 몬스터 레벨
	m_bDrop			= True,            -- 드롭 여부 / true = 드롭 함
	--m_bAggressive	= True,  		   -- 선/비 선공 / true = 선공
	--m_fAddPosY 		= 0.0,         -- 몬스터 높이값 설치 
	
	
	---필드-------
	ADVENT_FIELD_TABLE =					-- 몬스터 출현 필드 
	{
		VILLAGE_MAP_ID["VMI_INVALID"],		-- 설정 안하면 모든 필드에 출현
	},
	   
	NO_ADVENT_FIELD_TABLE =					-- 지정된 필드에서는 출현하지 않습니다.(설정 안하면 모든 필드에 출현)
	{
	
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_EXPERT"],	

		DUNGEON_ID["DI_ELDER_SECRET_COMMON"],
		DUNGEON_ID["DI_ELDER_SECRET_HELL"],
		DUNGEON_ID["DI_BESMA_SECRET_COMMON"],
		DUNGEON_ID["DI_BESMA_SECRET_HELL"],
		DUNGEON_ID["DI_ALTERA_SECRET_COMMON"],
		DUNGEON_ID["DI_ALTERA_SECRET_HELL"],
		DUNGEON_ID["DI_VELDER_SECRET_COMMON"],
		DUNGEON_ID["DI_VELDER_SECRET_HELL"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}


-- 140122/오현택/소마전야 이벤트 (던전출현)

GameEvent:AddEventMonsterInfo
{
	m_iEventID = 9,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	--m_bAllyNpc = True,				--아군 몬스터 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_GHOST_PPORU"],	-- 사파 뽀루
			ADVENT_RATE = 100,
			IS_ACTIVE = FALSE,
		},
	},
	
	m_iAddLevel 	= 0,      		   -- 몬스터 레벨
	m_bDrop			= True,            -- 드롭 여부 / true = 드롭 함
	--m_bAggressive	= True,  		   -- 선/비 선공 / true = 선공
	--m_fAddPosY 		= 0.0,         -- 몬스터 높이값 설치 
	
	
	---필드-------
	ADVENT_FIELD_TABLE =					-- 몬스터 출현 필드 
	{
		VILLAGE_MAP_ID["VMI_INVALID"],		-- 설정 안하면 모든 필드에 출현
	},
	   
	NO_ADVENT_FIELD_TABLE =					-- 지정된 필드에서는 출현하지 않습니다.(설정 안하면 모든 필드에 출현)
	{
	
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_EXPERT"],	

		DUNGEON_ID["DI_ELDER_SECRET_COMMON"],
		DUNGEON_ID["DI_ELDER_SECRET_HELL"],
		DUNGEON_ID["DI_BESMA_SECRET_COMMON"],
		DUNGEON_ID["DI_BESMA_SECRET_HELL"],
		DUNGEON_ID["DI_ALTERA_SECRET_COMMON"],
		DUNGEON_ID["DI_ALTERA_SECRET_HELL"],
		DUNGEON_ID["DI_VELDER_SECRET_COMMON"],
		DUNGEON_ID["DI_VELDER_SECRET_HELL"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}


-- 140122/오현택/소마전야 이벤트 (필드출현)

GameEvent:AddEventMonsterInfo
{
	m_iEventID = 10,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_GHOST_PPORU"],	-- 사파 뽀루
			ADVENT_RATE = 30,
			IS_ACTIVE = FALSE,
		},
	},
	
	---필드-------
	ADVENT_FIELD_TABLE =               -- 몬스터 출현 필드 
	{
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ELDER_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ELDER_FIELD_02"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_03"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_03"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_PEITA_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_PEITA_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_PEITA_FIELD_03"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_03"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_04"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_03"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_04"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_SHIP_STAGE"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_SHIP_STAGE"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_03"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_04"],
	},
	   
	NO_ADVENT_FIELD_TABLE =      -- 지정된 필드에서는 출현하지 않습니다.(설정 안하면 모든 필드에 출현)
	{
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_RUBEN_FIELD_01"],
	},
	
	---던전---------
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
			DUNGEON_ID["DI_END"],
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{

	},
	
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}