-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요


--					비던/정예 스페셜 드롭 보상		( npcid, item, 수량 )
DropTable:AddHenirSpecialNpcDropInfo(NPC_UNIT_ID["NUI_HENIR_APPLE"],					61205,	1	)
DropTable:AddHenirSpecialNpcDropInfo(NPC_UNIT_ID["NUI_HENIR_CODE_Q_PROTO_00"],			61205,	1	)
DropTable:AddHenirSpecialNpcDropInfo(NPC_UNIT_ID["NUI_GLITER_NECROMANCER_BOSS"],		61205,	1	)
DropTable:AddHenirSpecialNpcDropInfo(NPC_UNIT_ID["NUI_GLITER_HAMMER_BOSS"],				61205,	1	)
DropTable:AddHenirSpecialNpcDropInfo(NPC_UNIT_ID["NUI_GLITER_ARCHER_BOSS"],				61205,	1	)
DropTable:AddHenirSpecialNpcDropInfo(NPC_UNIT_ID["NUI_GLITER_LANCE_GREAT_BOSS"],		61205,	1	)
DropTable:AddHenirSpecialNpcDropInfo(NPC_UNIT_ID["NUI_GLITER_THIEF_GREAT_BOSS"],		61205,	1	)
DropTable:AddHenirSpecialNpcDropInfo(NPC_UNIT_ID["NUI_GLITER_FRAIL_GREAT_BOSS"],		61205,	1	)
DropTable:AddHenirSpecialNpcDropInfo(NPC_UNIT_ID["NUI_GLITER_ALCHEMYST_GREAT_BOSS"],	61205,	1	)
DropTable:AddHenirSpecialNpcDropInfo(NPC_UNIT_ID["NUI_SHADOW_STINGER"],					61205,	1	)
DropTable:AddHenirSpecialNpcDropInfo(NPC_UNIT_ID["NUI_CLOE_THE_CORRUPTION"],			61205,	1	)
DropTable:AddHenirSpecialNpcDropInfo(NPC_UNIT_ID["NUI_CONRAD_THE_ODD"],					61205,	1	)
DropTable:AddHenirSpecialNpcDropInfo(NPC_UNIT_ID["NUI_BOBOSSE_THE_REDHAMMER"],			61205,	1	)
DropTable:AddHenirSpecialNpcDropInfo(NPC_UNIT_ID["NUI_NASOD_INSPECTOR"],				61205,	4	)
DropTable:AddHenirSpecialNpcDropInfo(NPC_UNIT_ID["NUI_ANCIENT_BONE_DRAGON"],			61205,	5	)
DropTable:AddHenirSpecialNpcDropInfo(NPC_UNIT_ID["NUI_ELSWORD_PARASITE_COMMON"],		61205,	6	)
DropTable:AddHenirSpecialNpcDropInfo(NPC_UNIT_ID["NUI_GLITER_ALCHEMYST_SECRET_BOSS"],	61205,	7	)
