-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.


-- 기본적으로 튜토리얼, 훈련소, 헤니르시공은 출현하지 않도록 되어 있습니다.


-- 이벤트 몬스터 드롭 테스트
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 1,
	m_iMonsterDropCount = 1,
	m_bIsAdventInBossStage = True,
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_VELDER_MISSION"],
			ADVENT_RATE = 50,
		},
		
		{
			NPC_ID		= NPC_UNIT_ID["NUI_RUBEN_MISSION"],
			ADVENT_RATE = 50,
		},
	},
	
	ADVENT_DUNGEON_TABLE =
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
	},
	
	NO_ADVENT_STAGE_TABLE =
	{
		0,
	},
}



-- 조크 뽀루 이벤트
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 2,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_JOKE_PPORU"],
			ADVENT_RATE = 100,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 페어리 가디언 이벤트
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 3,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_FAIRY_GUARDIAN_RED"],
			ADVENT_RATE = 100,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 산타 클로에 이벤트 
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 4,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_SANTA_CHLOE"],
			ADVENT_RATE = 100,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}


-- 머맨, 워커 이벤트
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 5,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_MERMAN_EVENT"],
			ADVENT_RATE = 50,
		},
		{
			NPC_ID		= NPC_UNIT_ID["NUI_SHADOW_WALKER_EVENT"],
			ADVENT_RATE = 50,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 등교거부몽
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 6,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_REJECTION_MONKEY"],
			ADVENT_RATE = 100,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 김소드(엘소드)
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 7,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_EVENT_CHALLENGER"],
			ADVENT_RATE = 100,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 엘을 훔친 도적
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 8,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_EVENT_EL_THIEF"],
			ADVENT_RATE = 100,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}


-- 할로윈 던전 강시 뽀루
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 9,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_GHOST_PPORU"],
			ADVENT_RATE = 100,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}


GameEvent:AddEventMonsterInfo
{
	m_iEventID = 10,
	m_iMonsterDropCount = 10,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_PPORU_WILLIAM_FAKE_TEACHER"],
			ADVENT_RATE = 100,
		},		
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

--크리스마스선물상자
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 11,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = True,	--보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_PUMPKIN_BOX_1"],
						
			ADVENT_RATE = 100,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

--루돌뽀
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 12,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,	--보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_EVENT_RUDOLPH"],
						
			ADVENT_RATE = 100,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 란 뽀루 이벤트
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 13,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = True,  --보스 스테이지에서 출현 시킬껀지 
	
	--{{ 2011. 4. 10 조효진  유저가 특정 칭호 차고 있어야만 이벤트 몬스터 나오게 함
	m_bIsRequireTitle = True,		-- 이벤트 몬스터 타이틀 필요 여부
	m_iRequireTitleID = 		-- 필요 타이틀 ID
	{
		5515,
	},
	m_iMinRequireTitleUserCnt = 1,		-- 타이틀을 착용해야 하는 최소 파티원 수
	m_bIsAllUserRequireTitle= False,	-- 파티원 수 와는 별개로 파티 전원이 타이틀 착용해야는지 여부
	--}}
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_SPRIGGAN_PPORU"],
			ADVENT_RATE = 100,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_HAMEL_OUTSKIRTS_RESIAM_NORMAL"],
		DUNGEON_ID["DI_HAMEL_OUTSKIRTS_RESIAM_HARD"],
		DUNGEON_ID["DI_HAMEL_OUTSKIRTS_RESIAM_EXPERT"],
		DUNGEON_ID["DI_HAMEL_BREAK_RESIAM_NORMAL"],
		DUNGEON_ID["DI_HAMEL_BREAK_RESIAM_HARD"],
		DUNGEON_ID["DI_HAMEL_BREAK_RESIAM_EXPERT"],
		DUNGEON_ID["DI_HAMEL_ANCIENT_WATERWAY_NORMAL"],
		DUNGEON_ID["DI_HAMEL_ANCIENT_WATERWAY_HARD"],
		DUNGEON_ID["DI_HAMEL_ANCIENT_WATERWAY_EXPERT"],
		DUNGEON_ID["DI_HAMEL_ANCIENT_WATERWAY_CORE_NORMAL"],
		DUNGEON_ID["DI_HAMEL_ANCIENT_WATERWAY_CORE_HARD"],
		DUNGEON_ID["DI_HAMEL_ANCIENT_WATERWAY_CORE_EXPERT"],
		DUNGEON_ID["DI_HAMEL_CAVE_OF_MAGMANTA_NORMAL"],
		DUNGEON_ID["DI_HAMEL_CAVE_OF_MAGMANTA_HARD"],
		DUNGEON_ID["DI_HAMEL_CAVE_OF_MAGMANTA_EXPERT"],
		DUNGEON_ID["DI_HAMEL_FROZEN_WATER_TEMPLE_NORMAL"],
		DUNGEON_ID["DI_HAMEL_FROZEN_WATER_TEMPLE_HARD"],
		DUNGEON_ID["DI_HAMEL_FROZEN_WATER_TEMPLE_EXPERT"],
		DUNGEON_ID["DI_HAMEL_FROZEN_WATER_HALL_NORMAL"],
		DUNGEON_ID["DI_HAMEL_FROZEN_WATER_HALL_HARD"],
		DUNGEON_ID["DI_HAMEL_FROZEN_WATER_HALL_EXPERT"],
		
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

--운동회 박A
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 14,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,	--보스 스테이지에서 출현 시킬껀지
	m_iMinRequirePartyUserCnt = 2, 	--2명 이상 파티일 경우에만 등장
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_EVENT_BAZZI"],
						
			ADVENT_RATE = 100,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

--운동회 박B
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 15,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,	--보스 스테이지에서 출현 시킬껀지
	m_iMinRequirePartyUserCnt = 2, 	--2명 이상 파티일 경우에만 등장
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_EVENT_GOLDEN_DAO"],
						
			ADVENT_RATE = 100,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 6.13 / 오연된 알테라시아 포자
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 16,
	m_iMonsterDropCount = 2,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,	--보스 스테이지에서 출현 시킬껀지
	m_iMinRequirePartyUserCnt = 2, 	--2명 이상 파티일 경우에만 등장
	m_cUnitType = UNIT_TYPE["UT_LIRE"] ,	-- 레나 캐릭터가 있어야만 출현
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_EVENT_ALTERASIA_FOJA"],
						
			ADVENT_RATE = 100,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

GameEvent:AddEventMonsterInfo
{
	m_iEventID = 17,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,	--보스 스테이지에서 출현 시킬껀지
	m_iMinRequirePartyUserCnt = 1, 	--2명 이상 파티일 경우에만 등장
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_EVENT_LORD_KNIGHT_CORRUPTION"],
						
			ADVENT_RATE = 100,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

GameEvent:AddEventMonsterInfo
{
	m_iEventID = 18,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,	--보스 스테이지에서 출현 시킬껀지
	m_iMinRequirePartyUserCnt = 1, 	--2명 이상 파티일 경우에만 등장
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_EVENT_RUNE_SLAYER_CORRUPTION"],
						
			ADVENT_RATE = 100,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 7.11
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 19,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,	--보스 스테이지에서 출현 시킬껀지
	m_iMinRequirePartyUserCnt = 2, 	--2명 이상 파티일 경우에만 등장
	m_cUnitClass = UNIT_CLASS["UC_RAVEN_WEAPON_TAKER"], -- 웨폰테이커 있어야 나옴
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_PVP_HERO_BALAK"],
						
			ADVENT_RATE = 100,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 이브 이벤트 몬스터 8.8 종료
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 20,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = True,  --보스 스테이지에서 출현 시킬껀지 
	--m_iMinRequirePartyUserCnt = 2,
	m_cUnitType = UNIT_TYPE["UT_EVE"] ,	-- 이브 캐릭터가 있어야만 출현
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_EVENT_EL_CRYSTAL"],
			ADVENT_RATE = 100,
			ACTIVE = False,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
		DUNGEON_ID["DI_EVENT_DARK_WALLY_CASTLE_ELDER"],
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{

	},
	
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0, 1, 2,
	},
}

-- 올림픽 7.25
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 21,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_FAKE_RAVEN"],
			ADVENT_RATE = 100,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 일본 이벤 카드 캡터 뽀루 몬스터 2012.10.08
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 22,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_CARD_CAPTER_PPORU"],
			ADVENT_RATE = 100,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

GameEvent:AddEventMonsterInfo
{
	m_iEventID = 23,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_FAKE_RAVEN"],
			ADVENT_RATE = 100,
			ACTIVE		= False,			
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_ELDER_HALLOWEEN_NORMAL"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

--#ifdef SERV_EVENT_MONSTER_INFINITY_PPORU
--[[
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 24,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_EVENT_INFINITY_PPORU1"],
			ADVENT_RATE = 100,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
		DUNGEON_ID["DI_ELDER_BENDERS_CAVE_NORMAL"],
		DUNGEON_ID["DI_ELDER_BENDERS_CAVE_HARD"],
		DUNGEON_ID["DI_ELDER_BENDERS_CAVE_EXPERT"],
		DUNGEON_ID["DI_ELDER_NATURE_CAVE_NORMAL"],
		DUNGEON_ID["DI_ELDER_NATURE_CAVE_HARD"],
		DUNGEON_ID["DI_ELDER_NATURE_CAVE_EXPERT"],
		DUNGEON_ID["DI_ELDER_DRUID_FOREST_NORMAL"],
		DUNGEON_ID["DI_ELDER_DRUID_FOREST_HARD"],
		DUNGEON_ID["DI_ELDER_DRUID_FOREST_EXPERT"],
		DUNGEON_ID["DI_ELDER_WALLY_CASTLE_CENTER_NORMAL"],
		DUNGEON_ID["DI_ELDER_WALLY_CASTLE_CENTER_HARD"],
		DUNGEON_ID["DI_ELDER_WALLY_CASTLE_CENTER_EXPERT"],
		DUNGEON_ID["DI_ELDER_WALLY_CASTLE_ROOF_NORMAL"],
		DUNGEON_ID["DI_ELDER_WALLY_CASTLE_ROOF_HARD"],
		DUNGEON_ID["DI_ELDER_WALLY_CASTLE_ROOF_EXPERT"],
		DUNGEON_ID["DI_ELDER_BELOW_PASSAGE_NORMAL"],
		DUNGEON_ID["DI_ELDER_BELOW_PASSAGE_HARD"],
		DUNGEON_ID["DI_ELDER_BELOW_PASSAGE_EXPERT"],		
		DUNGEON_ID["DI_BESMA_DRAGON_ROAD_NORMAL"],
		DUNGEON_ID["DI_BESMA_DRAGON_ROAD_HARD"],
		DUNGEON_ID["DI_BESMA_DRAGON_ROAD_EXPERT"],
		DUNGEON_ID["DI_BESMA_MINE_NORMAL"],
		DUNGEON_ID["DI_BESMA_MINE_HARD"],
		DUNGEON_ID["DI_BESMA_MINE_EXPERT"],
		DUNGEON_ID["DI_BESMA_LAKE_NORMAL"],
		DUNGEON_ID["DI_BESMA_LAKE_HARD"],
		DUNGEON_ID["DI_BESMA_LAKE_EXPERT"],
		DUNGEON_ID["DI_BESMA_DRAGON_NEST_NORMAL"],
		DUNGEON_ID["DI_BESMA_DRAGON_NEST_HARD"],
		DUNGEON_ID["DI_BESMA_DRAGON_NEST_EXPERT"],
		DUNGEON_ID["DI_BESMA_AIRSHIP_NORMAL"],
		DUNGEON_ID["DI_BESMA_AIRSHIP_HARD"],
		DUNGEON_ID["DI_BESMA_AIRSHIP_EXPERT"],
		DUNGEON_ID["DI_BESMA_LAKE_NIGHT_NORMAL"],
		DUNGEON_ID["DI_BESMA_LAKE_NIGHT_HARD"],
		DUNGEON_ID["DI_BESMA_LAKE_NIGHT_EXPERT"],
		DUNGEON_ID["DI_BESMA_MINE2_NORMAL"],
		DUNGEON_ID["DI_BESMA_MINE2_HARD"],
		DUNGEON_ID["DI_BESMA_MINE2_EXPERT"],
		DUNGEON_ID["DI_BESMA_CANYON_NORMAL"],
		DUNGEON_ID["DI_BESMA_CANYON_HARD"],
		DUNGEON_ID["DI_BESMA_CANYON_EXPERT"],	
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_ELDER_HALLOWEEN_NORMAL"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

GameEvent:AddEventMonsterInfo
{
	m_iEventID = 25,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_EVENT_INFINITY_PPORU2"],
			ADVENT_RATE = 100,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
		DUNGEON_ID["DI_ALTERA_BATTLE_AIR_SHIP_NORMAL"],
		DUNGEON_ID["DI_ALTERA_BATTLE_AIR_SHIP_HARD"],
		DUNGEON_ID["DI_ALTERA_BATTLE_AIR_SHIP_EXPERT"],
		DUNGEON_ID["DI_ALTERA_PLAIN_RECYCLE_NORMAL"],
		DUNGEON_ID["DI_ALTERA_PLAIN_RECYCLE_HARD"],
		DUNGEON_ID["DI_ALTERA_PLAIN_RECYCLE_EXPERT"],
		DUNGEON_ID["DI_ALTERA_BELOW_TUNNEL_NORMAL"],
		DUNGEON_ID["DI_ALTERA_BELOW_TUNNEL_HARD"],
		DUNGEON_ID["DI_ALTERA_BELOW_TUNNEL_EXPERT"],
		DUNGEON_ID["DI_ALTERA_PLAIN_NORMAL"],
		DUNGEON_ID["DI_ALTERA_PLAIN_HARD"],
		DUNGEON_ID["DI_ALTERA_PLAIN_EXPERT"],
		DUNGEON_ID["DI_ALTERA_NASOD_FACTORY_NORMAL"],
		DUNGEON_ID["DI_ALTERA_NASOD_FACTORY_HARD"],
		DUNGEON_ID["DI_ALTERA_NASOD_FACTORY_EXPERT"],
		DUNGEON_ID["DI_ALTERA_CORE_NORMAL"],
		DUNGEON_ID["DI_ALTERA_CORE_HARD"],
		DUNGEON_ID["DI_ALTERA_CORE_EXPERT"],
		DUNGEON_ID["DI_PEITA_OFFERINGS_NORMAL"],
		DUNGEON_ID["DI_PEITA_OFFERINGS_HARD"],
		DUNGEON_ID["DI_PEITA_OFFERINGS_EXPERT"],
		DUNGEON_ID["DI_PEITA_SPIRAL_CORRIDOR_NORMAL"],
		DUNGEON_ID["DI_PEITA_SPIRAL_CORRIDOR_HARD"],
		DUNGEON_ID["DI_PEITA_SPIRAL_CORRIDOR_EXPERT"],
		DUNGEON_ID["DI_PEITA_CHAPEL_NORMAL"],
		DUNGEON_ID["DI_PEITA_CHAPEL_HARD"],
		DUNGEON_ID["DI_PEITA_CHAPEL_EXPERT"],
		DUNGEON_ID["DI_PEITA_UNDER_GARDEN_NORMAL"],
		DUNGEON_ID["DI_PEITA_UNDER_GARDEN_HARD"],
		DUNGEON_ID["DI_PEITA_UNDER_GARDEN_EXPERT"],
		DUNGEON_ID["DI_PEITA_TOWER_HEART_NORMAL"],
		DUNGEON_ID["DI_PEITA_TOWER_HEART_HARD"],
		DUNGEON_ID["DI_PEITA_TOWER_HEART_EXPERT"],
		DUNGEON_ID["DI_PEITA_OFFERINGS_ALTER_NORMAL"],
		DUNGEON_ID["DI_PEITA_OFFERINGS_ALTER_HARD"],
		DUNGEON_ID["DI_PEITA_OFFERINGS_ALTER_EXPERT"],		
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_ELDER_HALLOWEEN_NORMAL"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

GameEvent:AddEventMonsterInfo
{
	m_iEventID = 26,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_EVENT_INFINITY_PPORU3"],
			ADVENT_RATE = 100,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
		DUNGEON_ID["DI_VELDER_THIRD_DWELLING_NORMAL"],
		DUNGEON_ID["DI_VELDER_THIRD_DWELLING_HARD"],
		DUNGEON_ID["DI_VELDER_THIRD_DWELLING_EXPERT"],
		DUNGEON_ID["DI_VELDER_BRIDGE_HOPE_NORMAL"],
		DUNGEON_ID["DI_VELDER_BRIDGE_HOPE_HARD"],
		DUNGEON_ID["DI_VELDER_BRIDGE_HOPE_EXPERT"],
		DUNGEON_ID["DI_VELDER_PALACE_ENTRANCE_NORMAL"],
		DUNGEON_ID["DI_VELDER_PALACE_ENTRANCE_HARD"],
		DUNGEON_ID["DI_VELDER_PALACE_ENTRANCE_EXPERT"],
		DUNGEON_ID["DI_VELDER_BRIDGE_BUNNING_NORMAL"],
		DUNGEON_ID["DI_VELDER_BRIDGE_BUNNING_HARD"],
		DUNGEON_ID["DI_VELDER_BRIDGE_BUNNING_EXPERT"],
		DUNGEON_ID["DI_VELDER_MARKET_NORMAL"],
		DUNGEON_ID["DI_VELDER_MARKET_HARD"],
		DUNGEON_ID["DI_VELDER_MARKET_EXPERT"],
		DUNGEON_ID["DI_VELDER_GATE_NORMAL"],
		DUNGEON_ID["DI_VELDER_GATE_HARD"],
		DUNGEON_ID["DI_VELDER_GATE_EXPERT"],
		DUNGEON_ID["DI_HAMEL_OUTSKIRTS_RESIAM_NORMAL"],
		DUNGEON_ID["DI_HAMEL_OUTSKIRTS_RESIAM_HARD"],
		DUNGEON_ID["DI_HAMEL_OUTSKIRTS_RESIAM_EXPERT"],
		DUNGEON_ID["DI_HAMEL_BREAK_RESIAM_NORMAL"],
		DUNGEON_ID["DI_HAMEL_BREAK_RESIAM_HARD"],
		DUNGEON_ID["DI_HAMEL_BREAK_RESIAM_EXPERT"],
		DUNGEON_ID["DI_HAMEL_ANCIENT_WATERWAY_NORMAL"],
		DUNGEON_ID["DI_HAMEL_ANCIENT_WATERWAY_HARD"],
		DUNGEON_ID["DI_HAMEL_ANCIENT_WATERWAY_EXPERT"],
		DUNGEON_ID["DI_HAMEL_ANCIENT_WATERWAY_CORE_NORMAL"],
		DUNGEON_ID["DI_HAMEL_ANCIENT_WATERWAY_CORE_HARD"],
		DUNGEON_ID["DI_HAMEL_ANCIENT_WATERWAY_CORE_EXPERT"],
		DUNGEON_ID["DI_HAMEL_CAVE_OF_MAGMANTA_NORMAL"],
		DUNGEON_ID["DI_HAMEL_CAVE_OF_MAGMANTA_HARD"],
		DUNGEON_ID["DI_HAMEL_CAVE_OF_MAGMANTA_EXPERT"],
		DUNGEON_ID["DI_HAMEL_FROZEN_WATER_TEMPLE_NORMAL"],
		DUNGEON_ID["DI_HAMEL_FROZEN_WATER_TEMPLE_HARD"],
		DUNGEON_ID["DI_HAMEL_FROZEN_WATER_TEMPLE_EXPERT"],
		DUNGEON_ID["DI_HAMEL_FROZEN_WATER_HALL_NORMAL"],
		DUNGEON_ID["DI_HAMEL_FROZEN_WATER_HALL_HARD"],
		DUNGEON_ID["DI_HAMEL_FROZEN_WATER_HALL_EXPERT"],
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_ELDER_HALLOWEEN_NORMAL"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}
--]]
--#endif

GameEvent:AddEventMonsterInfo
{
	m_iEventID = 27,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_GHOST_PPORU"],
			ADVENT_RATE = 50,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
		DUNGEON_ID["DI_ELDER_BENDERS_CAVE_NORMAL"],
		DUNGEON_ID["DI_ELDER_BENDERS_CAVE_HARD"],
		DUNGEON_ID["DI_ELDER_BENDERS_CAVE_EXPERT"],
		DUNGEON_ID["DI_ELDER_NATURE_CAVE_NORMAL"],
		DUNGEON_ID["DI_ELDER_NATURE_CAVE_HARD"],
		DUNGEON_ID["DI_ELDER_NATURE_CAVE_EXPERT"],
		DUNGEON_ID["DI_ELDER_DRUID_FOREST_NORMAL"],
		DUNGEON_ID["DI_ELDER_DRUID_FOREST_HARD"],
		DUNGEON_ID["DI_ELDER_DRUID_FOREST_EXPERT"],
		DUNGEON_ID["DI_ELDER_WALLY_CASTLE_CENTER_NORMAL"],
		DUNGEON_ID["DI_ELDER_WALLY_CASTLE_CENTER_HARD"],
		DUNGEON_ID["DI_ELDER_WALLY_CASTLE_CENTER_EXPERT"],
		DUNGEON_ID["DI_ELDER_WALLY_CASTLE_ROOF_NORMAL"],
		DUNGEON_ID["DI_ELDER_WALLY_CASTLE_ROOF_HARD"],
		DUNGEON_ID["DI_ELDER_WALLY_CASTLE_ROOF_EXPERT"],
		DUNGEON_ID["DI_ELDER_BELOW_PASSAGE_NORMAL"],
		DUNGEON_ID["DI_ELDER_BELOW_PASSAGE_HARD"],
		DUNGEON_ID["DI_ELDER_BELOW_PASSAGE_EXPERT"],		
		DUNGEON_ID["DI_BESMA_DRAGON_ROAD_NORMAL"],
		DUNGEON_ID["DI_BESMA_DRAGON_ROAD_HARD"],
		DUNGEON_ID["DI_BESMA_DRAGON_ROAD_EXPERT"],
		DUNGEON_ID["DI_BESMA_MINE_NORMAL"],
		DUNGEON_ID["DI_BESMA_MINE_HARD"],
		DUNGEON_ID["DI_BESMA_MINE_EXPERT"],
		DUNGEON_ID["DI_BESMA_LAKE_NORMAL"],
		DUNGEON_ID["DI_BESMA_LAKE_HARD"],
		DUNGEON_ID["DI_BESMA_LAKE_EXPERT"],
		DUNGEON_ID["DI_BESMA_DRAGON_NEST_NORMAL"],
		DUNGEON_ID["DI_BESMA_DRAGON_NEST_HARD"],
		DUNGEON_ID["DI_BESMA_DRAGON_NEST_EXPERT"],
		DUNGEON_ID["DI_BESMA_AIRSHIP_NORMAL"],
		DUNGEON_ID["DI_BESMA_AIRSHIP_HARD"],
		DUNGEON_ID["DI_BESMA_AIRSHIP_EXPERT"],
		DUNGEON_ID["DI_BESMA_LAKE_NIGHT_NORMAL"],
		DUNGEON_ID["DI_BESMA_LAKE_NIGHT_HARD"],
		DUNGEON_ID["DI_BESMA_LAKE_NIGHT_EXPERT"],
		DUNGEON_ID["DI_BESMA_MINE2_NORMAL"],
		DUNGEON_ID["DI_BESMA_MINE2_HARD"],
		DUNGEON_ID["DI_BESMA_MINE2_EXPERT"],
		DUNGEON_ID["DI_BESMA_CANYON_NORMAL"],
		DUNGEON_ID["DI_BESMA_CANYON_HARD"],
		DUNGEON_ID["DI_BESMA_CANYON_EXPERT"],	
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_ELDER_HALLOWEEN_NORMAL"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

GameEvent:AddEventMonsterInfo
{
	m_iEventID = 28,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_JOKE_PPORU"],
			ADVENT_RATE = 50,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
		DUNGEON_ID["DI_ALTERA_BATTLE_AIR_SHIP_NORMAL"],
		DUNGEON_ID["DI_ALTERA_BATTLE_AIR_SHIP_HARD"],
		DUNGEON_ID["DI_ALTERA_BATTLE_AIR_SHIP_EXPERT"],
		DUNGEON_ID["DI_ALTERA_PLAIN_RECYCLE_NORMAL"],
		DUNGEON_ID["DI_ALTERA_PLAIN_RECYCLE_HARD"],
		DUNGEON_ID["DI_ALTERA_PLAIN_RECYCLE_EXPERT"],
		DUNGEON_ID["DI_ALTERA_BELOW_TUNNEL_NORMAL"],
		DUNGEON_ID["DI_ALTERA_BELOW_TUNNEL_HARD"],
		DUNGEON_ID["DI_ALTERA_BELOW_TUNNEL_EXPERT"],
		DUNGEON_ID["DI_ALTERA_PLAIN_NORMAL"],
		DUNGEON_ID["DI_ALTERA_PLAIN_HARD"],
		DUNGEON_ID["DI_ALTERA_PLAIN_EXPERT"],
		DUNGEON_ID["DI_ALTERA_NASOD_FACTORY_NORMAL"],
		DUNGEON_ID["DI_ALTERA_NASOD_FACTORY_HARD"],
		DUNGEON_ID["DI_ALTERA_NASOD_FACTORY_EXPERT"],
		DUNGEON_ID["DI_ALTERA_CORE_NORMAL"],
		DUNGEON_ID["DI_ALTERA_CORE_HARD"],
		DUNGEON_ID["DI_ALTERA_CORE_EXPERT"],
		DUNGEON_ID["DI_PEITA_OFFERINGS_NORMAL"],
		DUNGEON_ID["DI_PEITA_OFFERINGS_HARD"],
		DUNGEON_ID["DI_PEITA_OFFERINGS_EXPERT"],
		DUNGEON_ID["DI_PEITA_SPIRAL_CORRIDOR_NORMAL"],
		DUNGEON_ID["DI_PEITA_SPIRAL_CORRIDOR_HARD"],
		DUNGEON_ID["DI_PEITA_SPIRAL_CORRIDOR_EXPERT"],
		DUNGEON_ID["DI_PEITA_CHAPEL_NORMAL"],
		DUNGEON_ID["DI_PEITA_CHAPEL_HARD"],
		DUNGEON_ID["DI_PEITA_CHAPEL_EXPERT"],
		DUNGEON_ID["DI_PEITA_UNDER_GARDEN_NORMAL"],
		DUNGEON_ID["DI_PEITA_UNDER_GARDEN_HARD"],
		DUNGEON_ID["DI_PEITA_UNDER_GARDEN_EXPERT"],
		DUNGEON_ID["DI_PEITA_TOWER_HEART_NORMAL"],
		DUNGEON_ID["DI_PEITA_TOWER_HEART_HARD"],
		DUNGEON_ID["DI_PEITA_TOWER_HEART_EXPERT"],
		DUNGEON_ID["DI_PEITA_OFFERINGS_ALTER_NORMAL"],
		DUNGEON_ID["DI_PEITA_OFFERINGS_ALTER_HARD"],
		DUNGEON_ID["DI_PEITA_OFFERINGS_ALTER_EXPERT"],		
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_ELDER_HALLOWEEN_NORMAL"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

GameEvent:AddEventMonsterInfo
{
	m_iEventID = 29,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_JOKE_PPORU2"],
			ADVENT_RATE = 50,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
		DUNGEON_ID["DI_VELDER_THIRD_DWELLING_NORMAL"],
		DUNGEON_ID["DI_VELDER_THIRD_DWELLING_HARD"],
		DUNGEON_ID["DI_VELDER_THIRD_DWELLING_EXPERT"],
		DUNGEON_ID["DI_VELDER_BRIDGE_HOPE_NORMAL"],
		DUNGEON_ID["DI_VELDER_BRIDGE_HOPE_HARD"],
		DUNGEON_ID["DI_VELDER_BRIDGE_HOPE_EXPERT"],
		DUNGEON_ID["DI_VELDER_PALACE_ENTRANCE_NORMAL"],
		DUNGEON_ID["DI_VELDER_PALACE_ENTRANCE_HARD"],
		DUNGEON_ID["DI_VELDER_PALACE_ENTRANCE_EXPERT"],
		DUNGEON_ID["DI_VELDER_BRIDGE_BUNNING_NORMAL"],
		DUNGEON_ID["DI_VELDER_BRIDGE_BUNNING_HARD"],
		DUNGEON_ID["DI_VELDER_BRIDGE_BUNNING_EXPERT"],
		DUNGEON_ID["DI_VELDER_MARKET_NORMAL"],
		DUNGEON_ID["DI_VELDER_MARKET_HARD"],
		DUNGEON_ID["DI_VELDER_MARKET_EXPERT"],
		DUNGEON_ID["DI_VELDER_GATE_NORMAL"],
		DUNGEON_ID["DI_VELDER_GATE_HARD"],
		DUNGEON_ID["DI_VELDER_GATE_EXPERT"],
		DUNGEON_ID["DI_HAMEL_OUTSKIRTS_RESIAM_NORMAL"],
		DUNGEON_ID["DI_HAMEL_OUTSKIRTS_RESIAM_HARD"],
		DUNGEON_ID["DI_HAMEL_OUTSKIRTS_RESIAM_EXPERT"],
		DUNGEON_ID["DI_HAMEL_BREAK_RESIAM_NORMAL"],
		DUNGEON_ID["DI_HAMEL_BREAK_RESIAM_HARD"],
		DUNGEON_ID["DI_HAMEL_BREAK_RESIAM_EXPERT"],
		DUNGEON_ID["DI_HAMEL_ANCIENT_WATERWAY_NORMAL"],
		DUNGEON_ID["DI_HAMEL_ANCIENT_WATERWAY_HARD"],
		DUNGEON_ID["DI_HAMEL_ANCIENT_WATERWAY_EXPERT"],
		DUNGEON_ID["DI_HAMEL_ANCIENT_WATERWAY_CORE_NORMAL"],
		DUNGEON_ID["DI_HAMEL_ANCIENT_WATERWAY_CORE_HARD"],
		DUNGEON_ID["DI_HAMEL_ANCIENT_WATERWAY_CORE_EXPERT"],
		DUNGEON_ID["DI_HAMEL_CAVE_OF_MAGMANTA_NORMAL"],
		DUNGEON_ID["DI_HAMEL_CAVE_OF_MAGMANTA_HARD"],
		DUNGEON_ID["DI_HAMEL_CAVE_OF_MAGMANTA_EXPERT"],
		DUNGEON_ID["DI_HAMEL_FROZEN_WATER_TEMPLE_NORMAL"],
		DUNGEON_ID["DI_HAMEL_FROZEN_WATER_TEMPLE_HARD"],
		DUNGEON_ID["DI_HAMEL_FROZEN_WATER_TEMPLE_EXPERT"],
		DUNGEON_ID["DI_HAMEL_FROZEN_WATER_HALL_NORMAL"],
		DUNGEON_ID["DI_HAMEL_FROZEN_WATER_HALL_HARD"],
		DUNGEON_ID["DI_HAMEL_FROZEN_WATER_HALL_EXPERT"],
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_ELDER_HALLOWEEN_NORMAL"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}


GameEvent:AddEventMonsterInfo
{
	m_iEventID = 30,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	m_bAllyNpc = True,				--아군 몬스터
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_APINK_ANGEL_03_RENA"],
			ADVENT_RATE = 100,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_ELDER_HALLOWEEN_NORMAL"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 130227/오현택/배커 이벤트 (김민곤님 작품)
-- 배테랑 커맨더 이벤트 몬스터 2 ( 파괴 뽀루 )
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 31,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	m_iNeedQuestID = 62650,
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_EVENT_PET_HATCHLING_DARK_F_MONSTER"],
			ADVENT_RATE = 100,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}
-- 배테랑 커맨더 이벤트 몬스터 1 ( 용병대원 )
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 32,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	m_iNeedQuestID = 62670,
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_EVENT_PET_HATCHLING_NORM_F_MONSTER"],
			ADVENT_RATE = 100,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 13.03.27 ESJP_신학기이벤트
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 33,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	m_iNeedQuestID = 73870,
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_MONKEY_KING"],
			ADVENT_RATE = 100,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

----폭염 뽀루----
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 34,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_WILLIAM_PPORU_FIRE_EVENT"],	-- 폭염 뽀루
			ADVENT_RATE = 50,
			IS_ACTIVE = FALSE,
		},
		
		{
			NPC_ID		= NPC_UNIT_ID["NUI_WILLIAM_PPORU_FIRE_EVENT2"],	-- 진격의 폭염 뽀루
			ADVENT_RATE = 50,
			IS_ACTIVE = FALSE,
		},
	},
	
	---필드-------
	ADVENT_FIELD_TABLE =               -- 몬스터 출현 필드 
	{
	},
	   
	NO_ADVENT_FIELD_TABLE =      -- 지정된 필드에서는 출현하지 않습니다.(설정 안하면 모든 필드에 출현)
	{
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_RUBEN_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ELDER_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ELDER_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_03"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_03"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_PEITA_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_PEITA_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_PEITA_FIELD_03"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_03"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_04"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_03"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_04"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_SHIP_STAGE"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_SHIP_STAGE"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_03"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_04"],
	},
	
	---던전---------
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_EXPERT"],
	},
	
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 130911/이경철/어둠의 문 시즌 3 개편 이벤트
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 35,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_GHOST_PPORU"],	-- 다크엘프 스나이퍼
			ADVENT_RATE = 10,
			IS_ACTIVE = FALSE,
		},
		
		{
			NPC_ID		= NPC_UNIT_ID["NUI_FLAME_RED_EVENT"],	-- 글리터 정예 돌격병
			ADVENT_RATE = 10,
			IS_ACTIVE = FALSE,
		},
		
		{
			NPC_ID		= NPC_UNIT_ID["NUI_FLAME_BLUE_EVENT"],	-- 정예 코카트리글
			ADVENT_RATE = 10,
			IS_ACTIVE = FALSE,
		},
		
		{
			NPC_ID		= NPC_UNIT_ID["NUI_JOKE_PPORU"],	-- 포트 쉐도우 스팅어
			ADVENT_RATE = 10,
			IS_ACTIVE = FALSE,
		},
	},
	
	---필드-------
	ADVENT_FIELD_TABLE =               -- 몬스터 출현 필드 
	{
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ELDER_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ELDER_FIELD_02"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_03"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_03"],
	},
	   
	NO_ADVENT_FIELD_TABLE =      -- 지정된 필드에서는 출현하지 않습니다.(설정 안하면 모든 필드에 출현)
	{
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_RUBEN_FIELD_01"],
	},
	
	---던전---------
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
			DUNGEON_ID["DI_END"],
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{

	},
	
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 130926/이경철/결혼 이벤트
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 36,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_JOKE_PPORU2"],	-- 턱시도 뽀루
			ADVENT_RATE = 30,
			IS_ACTIVE = FALSE,
		},
		{
			NPC_ID		= NPC_UNIT_ID["NUI_JOKE_PPORU"],	-- 드레스 뽀루
			ADVENT_RATE = 30,
			IS_ACTIVE = FALSE,
		},
	},
	
	---필드-------
	ADVENT_FIELD_TABLE =               -- 몬스터 출현 필드 
	{
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ELDER_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ELDER_FIELD_02"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_03"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_03"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_PEITA_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_PEITA_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_PEITA_FIELD_03"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_03"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_04"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_03"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_04"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_SHIP_STAGE"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_SHIP_STAGE"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_03"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_04"],
	},
	   
	NO_ADVENT_FIELD_TABLE =      -- 지정된 필드에서는 출현하지 않습니다.(설정 안하면 모든 필드에 출현)
	{
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_RUBEN_FIELD_01"],
	},
	
	---던전---------
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
			DUNGEON_ID["DI_END"],
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{

	},
	
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 131023/이경철/마법의 스프
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 37,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	--m_bAllyNpc = True,				--아군 몬스터 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_JOKE_PPORU"],
			ADVENT_RATE = 50,
		},
	},
	
	m_iAddLevel 	= 0,      		   -- 몬스터 레벨
	m_bDrop			= True,            -- 드롭 여부 / true = 드롭 함
	--m_bAggressive	= True,  		   -- 선/비 선공 / true = 선공
	--m_fAddPosY 		= 0.0,         -- 몬스터 높이값 설치 
	
	
	---필드-------
	ADVENT_FIELD_TABLE =					-- 몬스터 출현 필드 
	{
		VILLAGE_MAP_ID["VMI_INVALID"],		-- 설정 안하면 모든 필드에 출현
	},
	   
	NO_ADVENT_FIELD_TABLE =					-- 지정된 필드에서는 출현하지 않습니다.(설정 안하면 모든 필드에 출현)
	{
	
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_EXPERT"],	

		DUNGEON_ID["DI_ELDER_SECRET_COMMON"],
		DUNGEON_ID["DI_ELDER_SECRET_HELL"],
		DUNGEON_ID["DI_BESMA_SECRET_COMMON"],
		DUNGEON_ID["DI_BESMA_SECRET_HELL"],
		DUNGEON_ID["DI_ALTERA_SECRET_COMMON"],
		DUNGEON_ID["DI_ALTERA_SECRET_HELL"],
		DUNGEON_ID["DI_VELDER_SECRET_COMMON"],
		DUNGEON_ID["DI_VELDER_SECRET_HELL"],

	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

--140115/강민정/소마전야 이벤트

-- 140122/오현택/소마전야 이벤트 (던전출현)

GameEvent:AddEventMonsterInfo
{
	m_iEventID = 38,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	--m_bAllyNpc = True,				--아군 몬스터 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_GHOST_PPORU"],	-- 사파 뽀루
			ADVENT_RATE = 100,
			IS_ACTIVE = FALSE,
		},
	},
	
	m_iAddLevel 	= 0,      		   -- 몬스터 레벨
	m_bDrop			= True,            -- 드롭 여부 / true = 드롭 함
	--m_bAggressive	= True,  		   -- 선/비 선공 / true = 선공
	--m_fAddPosY 		= 0.0,         -- 몬스터 높이값 설치 
	
	
	---필드-------
	ADVENT_FIELD_TABLE =					-- 몬스터 출현 필드 
	{
		VILLAGE_MAP_ID["VMI_INVALID"],		-- 설정 안하면 모든 필드에 출현
	},
	   
	NO_ADVENT_FIELD_TABLE =					-- 지정된 필드에서는 출현하지 않습니다.(설정 안하면 모든 필드에 출현)
	{
	
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_EXPERT"],	

		DUNGEON_ID["DI_ELDER_SECRET_COMMON"],
		DUNGEON_ID["DI_ELDER_SECRET_HELL"],
		DUNGEON_ID["DI_BESMA_SECRET_COMMON"],
		DUNGEON_ID["DI_BESMA_SECRET_HELL"],
		DUNGEON_ID["DI_ALTERA_SECRET_COMMON"],
		DUNGEON_ID["DI_ALTERA_SECRET_HELL"],
		DUNGEON_ID["DI_VELDER_SECRET_COMMON"],
		DUNGEON_ID["DI_VELDER_SECRET_HELL"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 140128 일본 소마 이벤트
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 39,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	--m_bAllyNpc = True,				--아군 몬스터 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_EVENT_FAKE_RAN_DUNGEON"],	-- 란의 허상 던전
			ADVENT_RATE = 100,
			IS_ACTIVE = FALSE,
		},
	},
	
	m_iAddLevel 	= 0,      		   -- 몬스터 레벨
	m_bDrop			= True,            -- 드롭 여부 / true = 드롭 함
	--m_bAggressive	= True,  		   -- 선/비 선공 / true = 선공
	--m_fAddPosY 		= 0.0,         -- 몬스터 높이값 설치 
	
	
	---필드-------
	ADVENT_FIELD_TABLE =					-- 몬스터 출현 필드 
	{
		VILLAGE_MAP_ID["VMI_INVALID"],		-- 설정 안하면 모든 필드에 출현
	},
	   
	NO_ADVENT_FIELD_TABLE =					-- 지정된 필드에서는 출현하지 않습니다.(설정 안하면 모든 필드에 출현)
	{
	
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_EXPERT"],	

		DUNGEON_ID["DI_ELDER_SECRET_COMMON"],
		DUNGEON_ID["DI_ELDER_SECRET_HELL"],
		DUNGEON_ID["DI_BESMA_SECRET_COMMON"],
		DUNGEON_ID["DI_BESMA_SECRET_HELL"],
		DUNGEON_ID["DI_ALTERA_SECRET_COMMON"],
		DUNGEON_ID["DI_ALTERA_SECRET_HELL"],
		DUNGEON_ID["DI_VELDER_SECRET_COMMON"],
		DUNGEON_ID["DI_VELDER_SECRET_HELL"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

GameEvent:AddEventMonsterInfo
{
	m_iEventID = 40,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_EVENT_FAKE_RAN_FIELD"],	-- 란의 허상 필드
			ADVENT_RATE = 30,
			IS_ACTIVE = FALSE,
		},
	},
	
	---필드-------
	ADVENT_FIELD_TABLE =               -- 몬스터 출현 필드 
	{
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ELDER_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ELDER_FIELD_02"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_03"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_03"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_PEITA_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_PEITA_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_PEITA_FIELD_03"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_03"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_04"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_03"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_04"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_SHIP_STAGE"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_SHIP_STAGE"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_03"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_04"],
	},
	   
	NO_ADVENT_FIELD_TABLE =      -- 지정된 필드에서는 출현하지 않습니다.(설정 안하면 모든 필드에 출현)
	{
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_RUBEN_FIELD_01"],
	},
	
	---던전---------
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
			DUNGEON_ID["DI_END"],
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{

	},
	
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 131212/임홍락/란 짜응/2차 전직 World War 이벤트 테스트용
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 41,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	--m_bAllyNpc = True,				--아군 몬스터 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_EVENT_ZOMBI_GLITER"],
			ADVENT_RATE = 100,
			IS_ACTIVE = FALSE,
		},
	},
	
	m_iAddLevel 	= 0,      		   -- 몬스터 레벨
	m_bDrop			= True,            -- 드롭 여부 / true = 드롭 함
	--m_bAggressive	= True,  		   -- 선/비 선공 / true = 선공
	--m_fAddPosY 		= 0.0,         -- 몬스터 높이값 설치 
	
	
	---필드-------
	ADVENT_FIELD_TABLE =					-- 몬스터 출현 필드 
	{
		VILLAGE_MAP_ID["VMI_INVALID"],		-- 설정 안하면 모든 필드에 출현
	},
	   
	NO_ADVENT_FIELD_TABLE =					-- 지정된 필드에서는 출현하지 않습니다.(설정 안하면 모든 필드에 출현)
	{
	
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_EXPERT"],	

		DUNGEON_ID["DI_ELDER_SECRET_COMMON"],
		DUNGEON_ID["DI_ELDER_SECRET_HELL"],
		DUNGEON_ID["DI_BESMA_SECRET_COMMON"],
		DUNGEON_ID["DI_BESMA_SECRET_HELL"],
		DUNGEON_ID["DI_ALTERA_SECRET_COMMON"],
		DUNGEON_ID["DI_ALTERA_SECRET_HELL"],
		DUNGEON_ID["DI_VELDER_SECRET_COMMON"],
		DUNGEON_ID["DI_VELDER_SECRET_HELL"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 140219/박필홍/샌더5,6  이벤트(던전 출현)
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 42,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_EVENT_SANDER_SAND"],	-- 모래 더미
			ADVENT_RATE = 100,
			IS_ACTIVE = FALSE,
		},
		
	},
	
	---필드-------
	ADVENT_FIELD_TABLE =               -- 몬스터 출현 필드 
	{
		VILLAGE_MAP_ID["VMI_INVALID"],		-- 설정 안하면 모든 필드에 출현
	},
	   
	NO_ADVENT_FIELD_TABLE =      -- 지정된 필드에서는 출현하지 않습니다.(설정 안하면 모든 필드에 출현)
	{

	},
	
	---던전---------
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
				
		DUNGEON_ID["DI_SANDER_DRY_SANDER_NORMAL"],
		DUNGEON_ID["DI_SANDER_DRY_SANDER_HARD"],
		DUNGEON_ID["DI_SANDER_DRY_SANDER_EXPERT"],
		DUNGEON_ID["DI_SANDER_GARPAI_ROCK_NORMAL"],
		DUNGEON_ID["DI_SANDER_GARPAI_ROCK_HARD"],
		DUNGEON_ID["DI_SANDER_GARPAI_ROCK_EXPERT"],
		DUNGEON_ID["DI_SANDER_DEN_OF_TROCK_NORMAL"],
		DUNGEON_ID["DI_SANDER_DEN_OF_TROCK_HARD"],
		DUNGEON_ID["DI_SANDER_DEN_OF_TROCK_EXPERT"],
		DUNGEON_ID["DI_SANDER_KARUSO_VILLAGE_NORMAL"],
		DUNGEON_ID["DI_SANDER_KARUSO_VILLAGE_HARD"],
		DUNGEON_ID["DI_SANDER_KARUSO_VILLAGE_EXPERT"],
		DUNGEON_ID["DI_SANDER_SANTILUS_SHIP_NORMAL"],
		DUNGEON_ID["DI_SANDER_SANTILUS_SHIP_HARD"],
		DUNGEON_ID["DI_SANDER_SANTILUS_SHIP_EXPERT"],
		DUNGEON_ID["DI_SANDER_BEHIMOSS_HEART_NORMAL"],
		DUNGEON_ID["DI_SANDER_BEHIMOSS_HEART_HARD"],
		DUNGEON_ID["DI_SANDER_BEHIMOSS_HEART_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_EXPERT"],
				
	},
	
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}


