-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요

--#ifdef SERV_HENIR_RENEWAL_2013

--[[
--					일반 모드 도전 보상			  ( stage, item, 수량 )
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	0,	61205,	0	)	-- 루벤/엘더
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	1,	61205,	0	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	2,	61205,	0	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	3,	61205,	0	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	4,	61205,	0	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	5,	61205,	0	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	6,	61205,	0	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	7,	61205,	0	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	8,	61205,	0	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	9,	61205,	0	)	
-- 0~9 stage 는 수량이 0 -> 서버 에러 로그 때문에 넣었지만 보상은 없다.						
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	10,	61205,	1	)	-- 베스마/알테라
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	11,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	12,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	13,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	14,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	15,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	16,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	17,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	18,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	19,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	20,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	21,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	22,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	23,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	24,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	25,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	26,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	27,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	28,	61205,	3	)	-- 페이타
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	29,	61205,	3	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	30,	61205,	3	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	31,	61205,	3	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	32,	61205,	3	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	33,	61205,	3	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	34,	61205,	3	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	35,	61205,	3	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	36,	61205,	3	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	37,	61205,	7	)	-- 벨더
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	38,	61205,	7	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	39,	61205,	7	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	40,	61205,	7	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	41,	61205,	7	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	42,	61205,	7	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	43,	61205,	7	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	44,	61205,	7	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	45,	61205,	15	)	-- 하멜
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	46,	61205,	15	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	47,	61205,	15	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	48,	61205,	15	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	49,	61205,	15	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	50,	61205,	15	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	51,	61205,	15	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	52,	61205,	15	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	53,	61205,	15	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	54,	61205,	15	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	55,	61205,	25	)	-- 샌더
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	56,	61205,	25	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	57,	61205,	25	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	58,	61205,	25	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	59,	61205,	25	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	60,	61205,	25	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	61,	61205,	25	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	62,	61205,	25	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_PRACTICE"],	63,	61205,	25	)	

--					도전 모드 도전 보상 (시공간의 조각)			  ( stage, item, 수량 )
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	0,	61205,	0	)	-- 루벤/엘더
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	1,	61205,	0	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	2,	61205,	0	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	3,	61205,	0	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	4,	61205,	0	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	5,	61205,	0	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	6,	61205,	0	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	7,	61205,	0	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	8,	61205,	0	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	9,	61205,	0	)	
-- 0~9 stage 는 수량이 0 -> 서버 에러 로그 때문에 넣었지만 보상은 없다.						
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	10,	61205,	1	)	-- 베스마/알테라
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	11,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	12,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	13,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	14,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	15,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	16,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	17,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	18,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	19,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	20,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	21,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	22,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	23,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	24,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	25,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	26,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	27,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	28,	61205,	3	)	-- 페이타
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	29,	61205,	3	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	30,	61205,	3	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	31,	61205,	3	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	32,	61205,	3	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	33,	61205,	3	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	34,	61205,	3	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	35,	61205,	3	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	36,	61205,	3	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	37,	61205,	7	)	-- 벨더
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	38,	61205,	7	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	39,	61205,	7	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	40,	61205,	7	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	41,	61205,	7	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	42,	61205,	7	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	43,	61205,	7	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	44,	61205,	7	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	45,	61205,	15	)	-- 하멜
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	46,	61205,	15	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	47,	61205,	15	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	48,	61205,	15	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	49,	61205,	15	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	50,	61205,	15	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	51,	61205,	15	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	52,	61205,	15	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	53,	61205,	15	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	54,	61205,	15	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	55,	61205,	25	)	-- 샌더
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	56,	61205,	25	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	57,	61205,	25	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	58,	61205,	25	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	59,	61205,	25	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	60,	61205,	25	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	61,	61205,	25	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	62,	61205,	25	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	63,	61205,	25	)	

--					도전 모드 도전 보상 (시공의 오로라 원석)			  ( stage, item, 수량 )
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	0,	61538,	0	)	-- 루벤/엘더
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	1,	61538,	0	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	2,	61538,	0	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	3,	61538,	0	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	4,	61538,	0	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	5,	61538,	0	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	6,	61538,	0	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	7,	61538,	0	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	8,	61538,	0	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	9,	61538,	0	)	
-- 0~9 stage 는 수량이 0 -> 서버 에러 로그 때문에 넣었지만 보상은 없다.						
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	10,	61538,	1	)	-- 베스마/알테라
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	11,	61538,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	12,	61538,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	13,	61538,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	14,	61538,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	15,	61538,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	16,	61538,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	17,	61538,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	18,	61538,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	19,	61538,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	20,	61538,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	21,	61538,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	22,	61538,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	23,	61538,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	24,	61538,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	25,	61538,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	26,	61538,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	27,	61538,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	28,	61538,	3	)	-- 페이타
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	29,	61538,	3	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	30,	61538,	3	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	31,	61538,	3	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	32,	61538,	3	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	33,	61538,	3	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	34,	61538,	3	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	35,	61538,	3	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	36,	61538,	3	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	37,	61538,	6	)	-- 벨더
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	38,	61538,	6	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	39,	61538,	6	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	40,	61538,	6	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	41,	61538,	6	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	42,	61538,	6	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	43,	61538,	6	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	44,	61538,	6	)	
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	45,	61538,	10	)-- 하멜
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	46,	61538,	10	)
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	47,	61538,	10	)
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	48,	61538,	10	)
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	49,	61538,	10	)
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	50,	61538,	10	)
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	51,	61538,	10	)
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	52,	61538,	10	)
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	53,	61538,	10	)
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	54,	61538,	10	)
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	55,	61538,	15	)-- 샌더
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	56,	61538,	15	)
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	57,	61538,	15	)
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	58,	61538,	15	)
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	59,	61538,	15	)
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	60,	61538,	15	)
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	61,	61538,	15	)
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	62,	61538,	15	)
HenirResultTable:AddHenirChallangeRewardInfo(	DUNGEON_MODE["DM_HENIR_CHALLENGE"],	63,	61538,	15	)
--]]

--#else //SERV_HENIR_RENEWAL_2013

--					도전 보상			  ( stage, item, 수량 )
HenirResultTable:AddHenirChallangeRewardInfo(	0,	61205,	0	)	-- 루벤/엘더
HenirResultTable:AddHenirChallangeRewardInfo(	1,	61205,	0	)	
HenirResultTable:AddHenirChallangeRewardInfo(	2,	61205,	0	)	
HenirResultTable:AddHenirChallangeRewardInfo(	3,	61205,	0	)	
HenirResultTable:AddHenirChallangeRewardInfo(	4,	61205,	0	)	
HenirResultTable:AddHenirChallangeRewardInfo(	5,	61205,	0	)	
HenirResultTable:AddHenirChallangeRewardInfo(	6,	61205,	0	)	
HenirResultTable:AddHenirChallangeRewardInfo(	7,	61205,	0	)	
HenirResultTable:AddHenirChallangeRewardInfo(	8,	61205,	0	)	
HenirResultTable:AddHenirChallangeRewardInfo(	9,	61205,	0	)
-- 0~9 stage 는 수량이 0 -> 서버 에러 로그 때문에 넣었지만 보상은 없다.	
HenirResultTable:AddHenirChallangeRewardInfo(	10,	61205,	1	)	-- 베스마
HenirResultTable:AddHenirChallangeRewardInfo(	11,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	12,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	13,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	14,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	15,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	16,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	17,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	18,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	19,	61205,	1	)	
HenirResultTable:AddHenirChallangeRewardInfo(	20,	61205,	3	)	-- 알테라
HenirResultTable:AddHenirChallangeRewardInfo(	21,	61205,	3	)	
HenirResultTable:AddHenirChallangeRewardInfo(	22,	61205,	3	)	
HenirResultTable:AddHenirChallangeRewardInfo(	23,	61205,	3	)	
HenirResultTable:AddHenirChallangeRewardInfo(	24,	61205,	3	)	
HenirResultTable:AddHenirChallangeRewardInfo(	25,	61205,	3	)	
HenirResultTable:AddHenirChallangeRewardInfo(	26,	61205,	3	)	
HenirResultTable:AddHenirChallangeRewardInfo(	27,	61205,	3	)	
HenirResultTable:AddHenirChallangeRewardInfo(	28,	61205,	3	)	
HenirResultTable:AddHenirChallangeRewardInfo(	29,	61205,	3	)	
HenirResultTable:AddHenirChallangeRewardInfo(	30,	61205,	7	)	-- 페이타
HenirResultTable:AddHenirChallangeRewardInfo(	31,	61205,	7	)	
HenirResultTable:AddHenirChallangeRewardInfo(	32,	61205,	7	)	
HenirResultTable:AddHenirChallangeRewardInfo(	33,	61205,	7	)	
HenirResultTable:AddHenirChallangeRewardInfo(	34,	61205,	7	)	
HenirResultTable:AddHenirChallangeRewardInfo(	35,	61205,	7	)	
HenirResultTable:AddHenirChallangeRewardInfo(	36,	61205,	7	)	
HenirResultTable:AddHenirChallangeRewardInfo(	37,	61205,	7	)	
HenirResultTable:AddHenirChallangeRewardInfo(	38,	61205,	7	)	
HenirResultTable:AddHenirChallangeRewardInfo(	39,	61205,	15	)	-- 벨더
HenirResultTable:AddHenirChallangeRewardInfo(	40,	61205,	15	)	
HenirResultTable:AddHenirChallangeRewardInfo(	41,	61205,	15	)	
HenirResultTable:AddHenirChallangeRewardInfo(	42,	61205,	15	)	
HenirResultTable:AddHenirChallangeRewardInfo(	43,	61205,	15	)	
HenirResultTable:AddHenirChallangeRewardInfo(	44,	61205,	15	)	
HenirResultTable:AddHenirChallangeRewardInfo(	45,	61205,	15	)	
HenirResultTable:AddHenirChallangeRewardInfo(	46,	61205,	15	)	
HenirResultTable:AddHenirChallangeRewardInfo(	47,	61205,	15	)	
HenirResultTable:AddHenirChallangeRewardInfo(	48,	61205,	25	)	-- 하멜
HenirResultTable:AddHenirChallangeRewardInfo(	49,	61205,	25	)	
HenirResultTable:AddHenirChallangeRewardInfo(	50,	61205,	25	)	
HenirResultTable:AddHenirChallangeRewardInfo(	51,	61205,	25	)	
HenirResultTable:AddHenirChallangeRewardInfo(	52,	61205,	25	)	
HenirResultTable:AddHenirChallangeRewardInfo(	53,	61205,	25	)	
HenirResultTable:AddHenirChallangeRewardInfo(	54,	61205,	25	)	
HenirResultTable:AddHenirChallangeRewardInfo(	55,	61205,	25	)	
HenirResultTable:AddHenirChallangeRewardInfo(	56,	61205,	25	)	

--#endif //SERV_HENIR_RENEWAL_2013

