
#include "ServerDefine.h"

//////////////////////////////////////////////////////////////////////////
// for visual assist

#ifndef EVENT_HANDLER
#define EVENT_HANDLER( eventid )
#endif

#ifndef EVENT_HANDLER_NOPARAM
#define EVENT_HANDLER_NOPARAM( eventid )
#endif

#ifndef _EVENT_HANDLER
#define _EVENT_HANDLER( eventid, structtype )
#endif


//////////////////////////////////////////////////////////////////////////
// 여기서 부터 이벤트 핸들러 정의!


EVENT_HANDLER( EGS_KNM_REQUEST_NEW_FRIEND_INFO_REQ );
_EVENT_HANDLER( ELG_KNM_REQUEST_NEW_FRIEND_INFO_ACK, KEGS_KNM_REQUEST_NEW_FRIEND_INFO_ACK );
_EVENT_HANDLER( DBE_KNM_REQUEST_NEW_FRIEND_INFO_ACK, KEGS_KNM_REQUEST_NEW_FRIEND_INFO_ACK );
EVENT_HANDLER( EGS_KNM_INVITE_REQ );
_EVENT_HANDLER( ELG_KNM_INVITE_ACK, KEGS_KNM_INVITE_ACK );
_EVENT_HANDLER( ELG_KNM_INVITE_NOT, KEGS_KNM_INVITE_NOT );
EVENT_HANDLER( EGS_KNM_INVITE_RESULT_NOT );
EVENT_HANDLER( EGS_KNM_TOGETHER_REQ );
_EVENT_HANDLER( ELG_KNM_TOGETHER_ACK, KEGS_KNM_TOGETHER_ACK );
EVENT_HANDLER( ELG_KNM_TOGETHER_BY_UNIT_INFO_REQ );

EVENT_HANDLER( EGS_GET_MY_MESSENGER_SN_REQ );
_EVENT_HANDLER( DBE_GET_MY_MESSENGER_SN_ACK, KEGS_GET_MY_MESSENGER_SN_ACK );

EVENT_HANDLER( EGS_REQUEST_FRIEND_REQ );
EVENT_HANDLER( DBE_REQUEST_FRIEND_ACK );
EVENT_HANDLER( EGS_REQUEST_FRIEND_NOT );
EVENT_HANDLER( EGS_ACCEPT_FRIEND_REQ );
EVENT_HANDLER( DBE_ACCEPT_FRIEND_ACK );
EVENT_HANDLER( EGS_ACCEPT_FRIEND_NOT );
EVENT_HANDLER( EGS_DENY_FRIEND_REQ );
EVENT_HANDLER( DBE_DENY_FRIEND_ACK );
EVENT_HANDLER( EGS_DENY_FRIEND_NOT );
EVENT_HANDLER( EGS_BLOCK_FRIEND_REQ );
EVENT_HANDLER( DBE_BLOCK_FRIEND_ACK );
EVENT_HANDLER( EGS_BLOCK_FRIEND_NOT );
EVENT_HANDLER( EGS_UNBLOCK_FRIEND_REQ );
EVENT_HANDLER( DBE_UNBLOCK_FRIEND_ACK );
EVENT_HANDLER( EGS_UNBLOCK_FRIEND_NOT );
EVENT_HANDLER( EGS_DELETE_FRIEND_REQ );
EVENT_HANDLER( DBE_DELETE_FRIEND_ACK );
EVENT_HANDLER( EGS_DELETE_FRIEND_NOT );
EVENT_HANDLER( EGS_MOVE_FRIEND_REQ );
EVENT_HANDLER( DBE_MOVE_FRIEND_ACK );
EVENT_HANDLER( EGS_MAKE_FRIEND_GROUP_REQ );
EVENT_HANDLER( DBE_MAKE_FRIEND_GROUP_ACK );
EVENT_HANDLER( EGS_RENAME_FRIEND_GROUP_REQ );
EVENT_HANDLER( DBE_RENAME_FRIEND_GROUP_ACK );
EVENT_HANDLER( EGS_DELETE_FRIEND_GROUP_REQ );
EVENT_HANDLER( DBE_DELETE_FRIEND_GROUP_ACK );
EVENT_HANDLER( EGS_FRIEND_POSITION_UPDATE_NOT );



