
#include "ServerDefine.h"

//////////////////////////////////////////////////////////////////////////
// for visual assist

#ifndef EVENT_HANDLER
#define EVENT_HANDLER( eventid )
#endif

#ifndef EVENT_HANDLER_NOPARAM
#define EVENT_HANDLER_NOPARAM( eventid )
#endif

#ifndef _EVENT_HANDLER
#define _EVENT_HANDLER( eventid, structtype )
#endif


//////////////////////////////////////////////////////////////////////////
// 여기서 부터 이벤트 핸들러 정의!

EVENT_HANDLER_NOPARAM( EGS_MY_UNIT_AND_INVENTORY_INFO_LIST_REQ );

_EVENT_HANDLER( DBE_MY_UNIT_AND_INVENTORY_INFO_LIST_ACK, KEGS_MY_UNIT_AND_INVENTORY_INFO_LIST_ACK );

EVENT_HANDLER( EGS_CREATE_UNIT_REQ );
_EVENT_HANDLER( DBE_GAME_CREATE_UNIT_ACK, KEGS_CREATE_UNIT_ACK );
_EVENT_HANDLER( DBE_ACCOUNT_CREATE_UNIT_ACK, KEGS_CREATE_UNIT_ACK );

EVENT_HANDLER( EGS_DELETE_UNIT_REQ );
_EVENT_HANDLER( DBE_GAME_DELETE_UNIT_ACK, KEGS_DELETE_UNIT_ACK );

#ifdef SERV_UNIT_WAIT_DELETE
_EVENT_HANDLER( DBE_ACCOUNT_DELETE_UNIT_ACK, KEGS_FINAL_DELETE_UNIT_ACK );
#else //SERV_UNIT_WAIT_DELETE
_EVENT_HANDLER( DBE_ACCOUNT_DELETE_UNIT_ACK, KEGS_DELETE_UNIT_ACK );
#endif //SERV_UNIT_WAIT_DELETE

EVENT_HANDLER( EGS_SELECT_UNIT_REQ );
//{{ 2012. 12. 10  캐릭터 선택 패킷 분할 - 김민성
#ifdef SERV_SELECT_UNIT_PACKET_DIVISION
_EVENT_HANDLER( DBE_GAME_SELECT_UNIT_ACK, KDBE_SELECT_UNIT_ACK );
_EVENT_HANDLER( DBE_ACCOUNT_SELECT_UNIT_ACK, KDBE_SELECT_UNIT_ACK );
#else
_EVENT_HANDLER( DBE_GAME_SELECT_UNIT_ACK, KEGS_SELECT_UNIT_ACK );
_EVENT_HANDLER( DBE_ACCOUNT_SELECT_UNIT_ACK, KEGS_SELECT_UNIT_ACK );	
#endif SERV_SELECT_UNIT_PACKET_DIVISION
//}}
//{{ 2010. 01. 04  최육사	인벤토리 개선
EVENT_HANDLER_NOPARAM( EGS_GET_MY_INVENTORY_REQ );
//}}

_EVENT_HANDLER( EGS_ENTER_EQUIP_SHOP_REQ, KEGS_ENTER_NPC_HOUSE_REQ );
EVENT_HANDLER( EGS_ENTER_NPC_HOUSE_REQ );

EVENT_HANDLER( EGS_CHAT_REQ );
EVENT_HANDLER( ERM_CHAT_ACK );
_EVENT_HANDLER( ERM_CHAT_NOT, KEGS_CHAT_NOT );
EVENT_HANDLER( ELG_CHAT_ACK );
EVENT_HANDLER( ELG_CHAT_NOT );

EVENT_HANDLER( EGS_NEW_QUEST_REQ );
EVENT_HANDLER( DBE_NEW_QUEST_ACK );
EVENT_HANDLER( EGS_TALK_WITH_NPC_REQ );
EVENT_HANDLER( EGS_GIVE_UP_QUEST_REQ );
#ifdef SERV_GATHER_GIVE_UP_QUEST 
EVENT_HANDLER( EGS_GATHER_GIVE_UP_QUEST_REQ );
#endif // SERV_GATHER_GIVE_UP_QUEST
EVENT_HANDLER( DBE_GIVE_UP_QUEST_ACK );
//{{ 2012. 04. 17	최육사	퀘스트 조건 마을 입장
#ifdef SERV_ENTER_FIELD_QUEST_CLEAR
EVENT_HANDLER( EGS_ALL_COMPLETED_QUEST_COMPLETE_REQ );
#endif SERV_ENTER_FIELD_QUEST_CLEAR
//}}
EVENT_HANDLER( EGS_QUEST_COMPLETE_REQ );
EVENT_HANDLER( DBE_QUEST_COMPLETE_ACK );

//{{ 2010. 02. 01  최육사	메가폰 및 전체공지 상태 제한
_EVENT_HANDLER( ECN_NOTIFY_MSG_NOT, KEGS_NOTIFY_MSG_NOT );
//}}

EVENT_HANDLER( EGS_CHANGE_OPTION_PLAY_GUIDE_REQ );
_EVENT_HANDLER( EGS_CHANGE_OPTION_PLAY_GUIDE_ACK, KPacketOK );

EVENT_HANDLER( EGS_SEARCH_UNIT_REQ );
//{{ 2009. 4. 17  최육사	접속중인 유저찾기
EVENT_HANDLER( EGS_GET_CONNECTION_UNIT_INFO_REQ );   
//}}
//{{ 2009. 6. 23  최육사	살펴보기
EVENT_HANDLER( EGS_WATCH_UNIT_REQ );
//}}
EVENT_HANDLER( ELG_SEARCH_UNIT_ACK );
_EVENT_HANDLER( DBE_SEARCH_UNIT_ACK, KPacketOK );

EVENT_HANDLER( ELG_GET_UNIT_INFO_REQ );
//{{ 2010. 05. 13  최육사	대전 던전 서버군 통합
#ifdef SERV_INTEGRATION
_EVENT_HANDLER( ERM_GET_UNIT_INFO_REQ, KELG_GET_UNIT_INFO_REQ );
_EVENT_HANDLER( ERM_SEARCH_UNIT_ACK, KELG_SEARCH_UNIT_ACK );
#endif SERV_INTEGRATION
//}}

EVENT_HANDLER( EGS_GET_SKILL_REQ );
EVENT_HANDLER( DBE_INSERT_SKILL_ACK );
EVENT_HANDLER( EGS_CHANGE_SKILL_SLOT_REQ );

// 블랙리스트
EVENT_HANDLER( EGS_NEW_BLACKLIST_USER_REQ );	
EVENT_HANDLER( ELG_SEARCH_BLACK_LIST_UNIT_ACK );
EVENT_HANDLER( DBE_NEW_BLACKLIST_USER_ACK );
EVENT_HANDLER( EGS_DEL_BLACKLIST_USER_REQ );
EVENT_HANDLER( DBE_DEL_BLACKLIST_USER_ACK );
EVENT_HANDLER( EGS_UPDATE_COMMUNITY_OPTION_REQ );

EVENT_HANDLER( EGS_FRAME_AVERAGE_REQ );

EVENT_HANDLER( EGS_CHANGE_NICK_NAME_REQ );
_EVENT_HANDLER( DBE_CHANGE_NICK_NAME_ACK, KEGS_CHANGE_NICK_NAME_ACK );

//{{ 2009. 9. 22  최육사	전직캐쉬	
EVENT_HANDLER( DBE_CHANGE_UNIT_CLASS_ACK );
//}}

EVENT_HANDLER( EGS_INIT_SKILL_TREE_REQ );
EVENT_HANDLER( DBE_INIT_SKILL_TREE_ACK );

// 추천
EVENT_HANDLER( EGS_RECOMMEND_USER_REQ );
EVENT_HANDLER( DBE_RECOMMEND_USER_ACK );
_EVENT_HANDLER( ELG_RECOMMEND_USER_RESULT_NOT, KEGS_RECOMMEND_USER_RESULT_NOT );

// 근성도 회복 아이템
_EVENT_HANDLER( ERM_RESTORE_SPIRIT_NOT, KEGS_RESTORE_SPIRIT_NOT );

EVENT_HANDLER( EGS_DEL_TUTORIAL_REQ );
EVENT_HANDLER( DBE_DEL_TUTORIAL_ACK );
_EVENT_HANDLER( ELG_TUTORIAL_UPDATE_UNIT_INFO_NOT, KEGS_TUTORIAL_UPDATE_UNIT_INFO_NOT );
_EVENT_HANDLER( ELG_DEL_TUTORIAL_NOT, KEGS_DEL_TUTORIAL_NOT );

EVENT_HANDLER( EGS_TUTORIAL_STUDENT_LIST_REQ );
EVENT_HANDLER( EGS_REQUEST_TUTORIAL_REQ );
EVENT_HANDLER( ELG_REQUEST_TUTORIAL_NOT );
EVENT_HANDLER( EGS_REQUEST_TUTORIAL_REPLY_NOT );
_EVENT_HANDLER( ELG_REQUEST_TUTORIAL_REPLY_NOT, KEGS_REQUEST_TUTORIAL_REPLY_NOT );
EVENT_HANDLER( DBE_INSERT_TUTORIAL_ACK );

EVENT_HANDLER( EGS_RESET_SKILL_REQ );
EVENT_HANDLER( DBE_RESET_SKILL_ACK );   

EVENT_HANDLER_NOPARAM( EGS_CURRENT_TIME_REQ );
EVENT_HANDLER( DBE_EXPAND_INVENTORY_SLOT_ACK );
EVENT_HANDLER( DBE_EXPAND_SKILL_SLOT_ACK );
//{{ 2008. 12. 14  최육사	캐릭터 슬롯 확장
EVENT_HANDLER( DBE_EXPAND_CHAR_SLOT_ACK );
//}}

// 이벤트
EVENT_HANDLER( DBE_UPDATE_EVENT_TIME_ACK );

//{{ 2009. 7. 6  최육사		랭킹 개편
EVENT_HANDLER_NOPARAM( ELG_NEW_RECORD_RANKING_SUCCESS_NOT );
EVENT_HANDLER( EGS_GET_RANKING_INFO_REQ );
//}}

//{{ 2008. 10. 6  최육사	타이틀
EVENT_HANDLER( EGS_EQUIP_TITLE_REQ );
EVENT_HANDLER( DBE_INSERT_TITLE_ACK );
_EVENT_HANDLER( ELG_INSERT_TITLE_NOT, KDBE_INSERT_TITLE_ACK );
//}}

//{{ 2009. 4. 8  최육사		닉네임 변경
EVENT_HANDLER( DBE_DELETE_NICK_NAME_ACK );
//}}

//{{ 2009. 8. 4  최육사		봉인스킬
EVENT_HANDLER( DBE_UNSEAL_SKILL_ACK );
//}}

//{{ 2009. 5. 8  최육사		실시간 레벨업
_EVENT_HANDLER( ERM_CHAR_LEVEL_UP_NOT, KEGS_CHAR_LEVEL_UP_NOT );
//}}

//{{ 2009. 6. 3  최육사		확성기
EVENT_HANDLER( EGS_USE_MEGAPHONE_REQ );
_EVENT_HANDLER( ECN_MEGAPHONE_MESSAGE_NOT, KEGS_MEGAPHONE_MESSAGE_NOT );
//}}

//{{ 2009. 12. 8  최육사	크리스마스이벤트
EVENT_HANDLER_NOPARAM( EGS_CHECK_TIME_EVENT_COMPLETE_REQ );
EVENT_HANDLER( DBE_CHECK_TIME_EVENT_COMPLETE_ACK );
//}}

//{{ 2010. 01. 07  최육사	추천인리스트
EVENT_HANDLER( EGS_GET_RECOMMEND_USER_LIST_REQ );
EVENT_HANDLER( DBE_GET_RECOMMEND_USER_LIST_ACK );
_EVENT_HANDLER( ELG_GET_RECOMMEND_USER_LIST_ACK, KDBE_GET_RECOMMEND_USER_LIST_ACK );
EVENT_HANDLER( ELG_RECOMMEND_USER_INFO_NOT );
//}}

//{{ 2010. 02. 23  최육사	웹 포인트 이벤트
#ifdef SERV_WEB_POINT_EVENT

EVENT_HANDLER_NOPARAM( EGS_ATTENDANCE_CHECK_REQ );
EVENT_HANDLER( DBE_ATTENDANCE_CHECK_ACK );

#endif SERV_WEB_POINT_EVENT
//}}

//{{ 2010. 03. 22  최육사	기술의 노트
#ifdef SERV_SKILL_NOTE
EVENT_HANDLER( DBE_EXPAND_SKILL_NOTE_PAGE_ACK );
EVENT_HANDLER( EGS_REG_SKILL_NOTE_MEMO_REQ );
_EVENT_HANDLER( DBE_REG_SKILL_NOTE_MEMO_ACK, KEGS_REG_SKILL_NOTE_MEMO_ACK );
#endif SERV_SKILL_NOTE
//}}

//{{ 2012.02.20 조효진	캐릭터 삭제 프로세스 변경 (삭제 대기 기간 도입)
#ifdef SERV_UNIT_WAIT_DELETE
EVENT_HANDLER( EGS_RESTORE_UNIT_REQ );
_EVENT_HANDLER( DBE_GAME_RESTORE_UNIT_ACK, KEGS_RESTORE_UNIT_ACK );
EVENT_HANDLER( EGS_FINAL_DELETE_UNIT_REQ );
_EVENT_HANDLER( DBE_GAME_FINAL_DELETE_UNIT_ACK, KEGS_FINAL_DELETE_UNIT_ACK );
#endif SERV_UNIT_WAIT_DELETE
//{{ 2011. 04. 13  김민성  글로벌 서버 추가
#ifdef SERV_INSERT_GLOBAL_SERVER
_EVENT_HANDLER( EGB_UPDATE_WORLD_BUFF_NOT, KEGS_UPDATE_WORLD_BUFF_NOT );
#endif SERV_INSERT_GLOBAL_SERVER
//}} 2011. 04. 13  김민성  글로벌 서버 추가

//{{ 2012. 03. 23	박세훈	어둠의 문 개편
#ifdef SERV_REFORM_THE_GATE_OF_DARKNESS
EVENT_HANDLER( EGB_THE_GATE_OF_DARKNESS_INDIVIDUAL_BUFF_NOT );
#endif SERV_REFORM_THE_GATE_OF_DARKNESS
//}}

//{{ 2012. 05. 17	박세훈	키보드 맵핑 정보를 DB에서 읽고 쓰기
#ifdef SERV_KEYBOARD_MAPPING_INFO_RW
EVENT_HANDLER( EGS_KEYBOARD_MAPPING_INFO_WRITE_REQ )
_EVENT_HANDLER( DBE_KEYBOARD_MAPPING_INFO_WRITE_ACK, KEGS_KEYBOARD_MAPPING_INFO_WRITE_ACK )
_EVENT_HANDLER( DBE_KEYBOARD_MAPPING_INFO_READ_ACK, KEGS_KEYBOARD_MAPPING_INFO_NOT )
#endif SERV_KEYBOARD_MAPPING_INFO_RW
//}}

//{{ 2012. 05. 23	최육사	배틀필드 시스템
#ifdef SERV_BATTLE_FIELD_SYSTEM
EVENT_HANDLER( EGS_UPDATE_PLAY_STATUS_NOT );
_EVENT_HANDLER( EPM_BROADCAST_PARTY_MEMBER_STATUS_NOT, KEGS_UPDATE_PARTY_MEMBER_STATUS_NOT );

EVENT_HANDLER( EGS_USE_SKILL_BUFF_IN_PLAY_NOT );
_EVENT_HANDLER( ERM_USE_SKILL_BUFF_IN_PLAY_BROAD_NOT, KEGS_USE_SKILL_BUFF_IN_PLAY_BROAD_NOT );
#endif SERV_BATTLE_FIELD_SYSTEM
//}}

//{{ 2012. 05. 29	박세훈	채팅 옵션 정보를 DB에서 읽고 쓰기
#ifdef SERV_CHAT_OPTION_INFO_RW
EVENT_HANDLER( EGS_CHAT_OPTION_INFO_WRITE_REQ )
_EVENT_HANDLER( DBE_CHAT_OPTION_INFO_WRITE_ACK, KEGS_CHAT_OPTION_INFO_WRITE_ACK )
_EVENT_HANDLER( DBE_CHAT_OPTION_INFO_READ_ACK, KEGS_CHAT_OPTION_INFO_NOT )
#endif SERV_CHAT_OPTION_INFO_RW
//}}

#ifdef SERV_EVENT_MONEY	// 김민성 // 적용날짜: 2013-07-04
_EVENT_HANDLER( DBE_UPDATE_EVENT_MONEY_ACK, int );
#endif // SERV_EVENT_MONEY

//{{ 버프 관리 시스템 - 김민성
#ifdef SERV_SERVER_BUFF_SYSTEM
EVENT_HANDLER( EGS_UPDATE_USER_UNIT_BUFF_INFO_NOT );
_EVENT_HANDLER( ERM_UPDATE_USER_UNIT_BUFF_INFO_BROAD_NOT, KEGS_UPDATE_USER_UNIT_BUFF_INFO_BROAD_NOT );
EVENT_HANDLER( EGS_UPDATE_NPC_UNIT_BUFF_INFO_NOT );
_EVENT_HANDLER( ERM_UPDATE_NPC_UNIT_BUFF_INFO_BROAD_NOT, KEGS_UPDATE_NPC_UNIT_BUFF_INFO_BROAD_NOT );
#endif SERV_SERVER_BUFF_SYSTEM
//}}

//{{ QUEST 개편 - 김민성
#ifdef SERV_REFORM_QUEST
EVENT_HANDLER( ERM_UPDATE_QUEST_INFO_NOT );
#endif SERV_REFORM_QUEST
//}}

//{{ 2012. 09. 02	박세훈	Merge ( 대전에서 클라이언트 조작등으로 UDP 패킷이 날아오지 않는 유저가 발견되면 서버에서 킥한다. // 2012.06.11 lygan_조성욱 )
#ifdef UDP_CAN_NOT_SEND_USER_KICK
EVENT_HANDLER( EGS_UDP_CHECK_KICK_USER_NOT );
_EVENT_HANDLER( ECN_UDP_KICK_GAMEEDIT_NOT, KEGS_UDP_KICK_GAMEEDIT_NOT );
#endif UDP_CAN_NOT_SEND_USER_KICK
//}}

//{{ 버프 관리 시스템 - 김민성
#ifdef SERV_SERVER_BUFF_SYSTEM
EVENT_HANDLER( ELG_UPDATE_USER_UNIT_BUFF_INFO_ACK );
#endif SERV_SERVER_BUFF_SYSTEM
//}

//{{ 2012. 12. 12	박세훈	겨울 방학 전야 이벤트( 임시, 하드 코딩 )
#ifdef SERV_2012_WINTER_VACATION_EVENT
_EVENT_HANDLER( DBE_2012_WINTER_VACATION_EVENT_NOT, int );
#endif SERV_2012_WINTER_VACATION_EVENT
//}}

//{{ 2012. 12. 18	최육사	아라 파티 플레이 보너스 경험치
#ifdef SERV_PLAY_WITH_CHAR_PARTY_BONUS_EXP
EVENT_HANDLER( ERM_DEACTIVATE_BUFF_NOT );
#endif SERV_PLAY_WITH_CHAR_PARTY_BONUS_EXP
//}}

//{{ 2012. 12. 14  계정 미션 시스템 ( 계정단위 퀘스트 ) - 김민성
#ifdef SERV_ACCOUNT_MISSION_SYSTEM
EVENT_HANDLER( DBE_NEW_ACCOUNT_QUEST_ACK );
_EVENT_HANDLER( DBE_NEW_ACCOUNT_QUEST_GAME_DB_ACK, KDBE_NEW_QUEST_ACK );
EVENT_HANDLER( DBE_ACCOUNT_QUEST_COMPLETE_ACK );
_EVENT_HANDLER( DBE_ACCOUNT_QUEST_COMPLETE_GAME_DB_ACK, KDBE_QUEST_COMPLETE_ACK );
#endif SERV_ACCOUNT_MISSION_SYSTEM
//}}

//{{ 2013. 02. 07   플루오르 스톤 강화 이벤트 실시간 적용 - 김민성
#ifdef SERV_SUPPORT_MATERIAL_ENCHANT_EVENT
EVENT_HANDLER_NOPARAM( EGS_SUPPORT_MATERIAL_EVENT_TIME_REQ );
#endif SERV_SUPPORT_MATERIAL_ENCHANT_EVENT
//}

// 2011.05.05 lygan_조성욱 // 중국용 커뮤니티탭 유저 정보 보기
#ifdef SERV_USER_WATCH_NEW
EVENT_HANDLER( EGS_USER_COMMUNITY_SURVEY_NEW_REQ  );
#endif //SERV_USER_WATCH_NEW

#ifdef SERV_CATCH_HACKUSER_INFO
_EVENT_HANDLER( EGS_CATCH_HACKUSER_INFO_NOT, KEGS_CATCH_HACKUSER_INFO_NOT );
#endif SERV_CATCH_HACKUSER_INFO

#ifdef SERV_ADVERTISEMENT_EVENT
EVENT_HANDLER_NOPARAM( EGS_GET_ADVERTISEMENT_EVENT_REQ );
#endif SERV_ADVERTISEMENT_EVENT

//{{ 2013. 3. 4	박세훈	 로컬 랭킹 시스템
#ifdef SERV_LOCAL_RANKING_SYSTEM
EVENT_HANDLER( EGS_LOCAL_RANKING_USER_INFO_READ_REQ );
EVENT_HANDLER( SOAP_LOCAL_RANKING_NEXON_ID_CHECK_FOR_READ_ACK );
EVENT_HANDLER( DBE_ACCOUNT_LOCAL_RANKING_USER_INFO_READ_ACK );
EVENT_HANDLER( DBE_ACCOUNT_LOCAL_RANKING_UNIT_INFO_READ_FOR_INQUIRY_ACK );
EVENT_HANDLER( DBE_ACCOUNT_LOCAL_RANKING_UNIT_INFO_READ_FOR_INCREASE_ACK );
EVENT_HANDLER( EGS_LOCAL_RANKING_USER_INFO_WRITE_REQ );
EVENT_HANDLER( SOAP_LOCAL_RANKING_NEXON_ID_CHECK_FOR_WRITE_ACK );
EVENT_HANDLER( DBE_LOCAL_RANKING_USER_INFO_WRITE_ACK );
EVENT_HANDLER_NOPARAM( ELG_LOCAL_RANKING_RESET_NOT );
EVENT_HANDLER( ELG_LOCAL_RANKING_RANK_UP_NOT );
EVENT_HANDLER( EGS_LOCAL_RANKING_INQUIRY_REQ );
EVENT_HANDLER( EGS_LOCAL_RANKING_INQUIRY_ACK );
#endif SERV_LOCAL_RANKING_SYSTEM
//}}

//{{ 2013. 03. 21	 추천인 시스템 개편 - 김민성
#ifdef SERV_RECOMMEND_LIST_EVENT
EVENT_HANDLER( DBE_RECOMMEND_USER_GET_NEXON_SN_ACK );
EVENT_HANDLER( SOAP_CHECK_SAME_USER_ACK );
#endif SERV_RECOMMEND_LIST_EVENT
//}

#ifdef SERV_ADD_WARP_BUTTON
EVENT_HANDLER( EGS_WARP_BY_BUTTON_REQ )
#endif // SERV_ADD_WARP_BUTTON

#ifdef	SERV_LOCAL_RANKING_SYSTEM // 적용날짜: 2013-04-05
EVENT_HANDLER( EGS_LOCAL_RANKING_WATCH_UNIT_REQ );
EVENT_HANDLER( ELG_LOCAL_RANKING_WATCH_UNIT_REQ );
EVENT_HANDLER( ELG_LOCAL_RANKING_WATCH_UNIT_ACK );
EVENT_HANDLER( ERM_LOCAL_RANKING_WATCH_UNIT_REQ );
EVENT_HANDLER( ERM_LOCAL_RANKING_WATCH_UNIT_ACK );
#endif	// SERV_LOCAL_RANKING_SYSTEM

//{{ 2013. 2. 1	박세훈	랜선렉 방지 코드2
#ifdef SERV_FIX_SYNC_PACKET_USING_RELAY
EVENT_HANDLER( EGS_FORCE_RELAY_NOT );
_EVENT_HANDLER( ERM_FORCE_RELAY_NOT, KEGS_FORCE_RELAY_NOT );
EVENT_HANDLER_NOPARAM( ERM_UDP_KICK_STATE_CHANGE_FIELD_NOT );
#endif SERV_FIX_SYNC_PACKET_USING_RELAY
//}}


#ifdef SERV_CLIENT_PORT_CHANGE_REQUEST_LOG
EVENT_HANDLER( EGS_CLIENT_POPRT_CHANGE_REQUEST_INFO_NOT );
#endif //SERV_CLIENT_PORT_CHANGE_REQUEST_LOG

#ifdef SERV_SKILL_USE_SUBQUEST
EVENT_HANDLER( EGS_SKILL_USE_REQ );
#endif SERV_SKILL_USE_SUBQUEST

#ifdef SERV_JUMPING_CHARACTER// 작업날짜: 2013-07-10	// 박세훈
EVENT_HANDLER( DBE_JUMPING_CHARACTER_INFO_NOT );
EVENT_HANDLER( EGS_JUMPING_CHARACTER_REQ );
EVENT_HANDLER( DBE_JUMPING_CHARACTER_UPDATE_ACK );
#endif // SERV_JUMPING_CHARACTER

#ifdef SERV_KOM_FILE_CHECK_ADVANCED
EVENT_HANDLER( EGS_KOM_FILE_CHECK_LOG_REQ );
#endif SERV_KOM_FILE_CHECK_ADVANCED


#ifdef SERV_HALLOWEEN_PUMPKIN_FAIRY_PET
EVENT_HANDLER( DBE_CHANGE_PET_ID_ACK );
#endif //SERV_HALLOWEEN_PUMPKIN_FAIRY_PET

#ifdef SERV_CHINA_SPIRIT_EVENT
EVENT_HANDLER( EGS_USE_SPIRIT_REWARD_REQ );
#endif SERV_CHINA_SPIRIT_EVENT

#ifdef SERV_RECRUIT_EVENT_BASE
_EVENT_HANDLER( ELG_REGISTER_RECRUITER_NOT, KEGS_REGISTER_RECRUITER_NOT );
EVENT_HANDLER_NOPARAM( EGS_GET_RECRUIT_RECRUITER_LIST_REQ );
_EVENT_HANDLER( DBE_GET_RECRUIT_RECRUITER_LIST_ACK, KEGS_GET_RECRUIT_RECRUITER_LIST_ACK );
_EVENT_HANDLER( ELG_GET_RECRUIT_RECRUITER_LIST_ACK, KEGS_GET_RECRUIT_RECRUITER_LIST_ACK );
EVENT_HANDLER( ELG_RECRUIT_RECRUITER_INFO_NOT );
#endif SERV_RECRUIT_EVENT_BASE

#ifdef SERV_NEW_YEAR_EVENT_2014
EVENT_HANDLER( EGS_2013_EVENT_MISSION_COMPLETE_REQ );
EVENT_HANDLER( DBE_2013_EVENT_MISSION_COMPLETE_ACK );
EVENT_HANDLER_NOPARAM( EGS_2014_EVENT_MISSION_COMPLETE_REQ );
_EVENT_HANDLER( DBE_2014_EVENT_MISSION_COMPLETE_ACK, KEGS_2014_EVENT_MISSION_COMPLETE_ACK );
#endif SERV_NEW_YEAR_EVENT_2014

#ifdef SERV_UNLIMITED_SECOND_CHANGE_JOB
EVENT_HANDLER( EGS_UNLIMITED_SECOND_CHANGE_JOB_NOT );
#endif //SERV_UNLIMITED_SECOND_CHANGE_JOB

