
#include "ServerDefine.h"

//////////////////////////////////////////////////////////////////////////
// for visual assist

#ifndef EVENT_HANDLER
#define EVENT_HANDLER( eventid )
#endif

#ifndef EVENT_HANDLER_NOPARAM
#define EVENT_HANDLER_NOPARAM( eventid )
#endif

#ifndef _EVENT_HANDLER
#define _EVENT_HANDLER( eventid, structtype )
#endif


//////////////////////////////////////////////////////////////////////////
// 여기서 부터 이벤트 핸들러 정의!

#ifdef SERV_GLOBAL_BILLING

EVENT_HANDLER( EGS_BILL_PRODUCT_INFO_REQ );
EVENT_HANDLER( EGS_BILL_INVENTORY_INQUIRY_REQ );
_EVENT_HANDLER( EBILL_INVENTORY_INQUIRY_ACK, KEGS_BILL_INVENTORY_INQUIRY_ACK );


//{{ 2009-11-18  최육사  구매전 캐쉬인벤체크
EVENT_HANDLER( EBILL_PREPARE_BUY_PRODUCT_ACK );
//}}
EVENT_HANDLER( EBILL_BUY_PRODUCT_ACK );
EVENT_HANDLER( EGS_BILL_GET_PURCHASED_CASH_ITEM_REQ );
EVENT_HANDLER( EBILL_PICK_UP_ACK );

EVENT_HANDLER( EBILL_GIFT_ITEM_ACK );

//{{ 허상형 : [2010/8/19/] //	선물 기능 개편
EVENT_HANDLER( DBE_GET_NICKNAME_BY_UNITUID_ACK );
//}} 허상형 : [2010/8/19/] //	선물 기능 개편


EVENT_HANDLER( EPUBLISHER_BILLING_BALANCE_ACK )

// 중국처럼 KOG 캐시 차감 구조나 사내 빌링에서 사용
_EVENT_HANDLER( EBILL_CHECK_BALANCE_ACK, KEGS_CHECK_BALANCE_ACK )


EVENT_HANDLER( EGS_EXCHANGE_CASH_REQ )
EVENT_HANDLER( EBILL_EXCHANGE_CASH_ACK )

EVENT_HANDLER( DBE_PRESENT_CASH_ITEM_CHECK_NICKNAME_ACK );
EVENT_HANDLER( EBILL_PREPARE_GIFT_ITEM_ACK );

#endif // SERV_GLOBAL_BILLING

EVENT_HANDLER_NOPARAM( EGS_CHECK_BALANCE_REQ );

EVENT_HANDLER( EGS_APPLY_COUPON_REQ );

#ifdef SERV_GLOBAL_BILLING
EVENT_HANDLER( EBILL_USE_COUPON_ACK );
EVENT_HANDLER( EBILL_USE_COUPON_RESERVE_ACK );
EVENT_HANDLER( EBILL_USE_COUPON_RESULT_ACK );
#endif //SERV_GLOBAL_BILLING

EVENT_HANDLER( EGS_PURCHASED_CASH_ITEM_LIST_REQ );
EVENT_HANDLER( EGS_GET_PURCHASED_CASH_ITEM_REQ );
EVENT_HANDLER( ENX_BT_NISMS_INVENTORY_PICK_UP_ACK );
EVENT_HANDLER( ENX_BT_NISMS_INVENTORY_PICK_UP_ONCE_ACK );
_EVENT_HANDLER( DBE_INSERT_PURCHASED_CASH_ITEM_ACK, KDBE_INSERT_ITEM_ACK );
EVENT_HANDLER( DBE_INSERT_PURCHASED_CASH_PACKAGE_ACK );

EVENT_HANDLER( EGS_CASH_PRODUCT_INFO_REQ );
EVENT_HANDLER( EGS_BUY_CASH_ITEM_REQ );	
_EVENT_HANDLER( ENX_BT_PURCHASE_ITEM_ACK, KEGS_BUY_CASH_ITEM_ACK );
EVENT_HANDLER( EGS_PRESENT_CASH_ITEM_REQ );
_EVENT_HANDLER( ENX_BT_PURCHASE_GIFT_ACK, KEGS_PRESENT_CASH_ITEM_ACK );
EVENT_HANDLER( ELG_PRESENT_CASH_ITEM_ACK );
//EVENT_HANDLER( DBE_PRESENT_CASH_ITEM_CHECK_NICKNAME_ACK ); // 해외팀 위치 변경

//{{ 2009. 10. 6  최육사	자동결재
EVENT_HANDLER( EGS_BUY_CASH_ITEM_AUTOMATIC_PAYMENT_REQ );
EVENT_HANDLER( ENX_BT_CHECK_AUTO_PAYMENT_USER_ACK );
//}}

// 넥슨빌링 패키지 픽업
EVENT_HANDLER( EGS_GET_PURCHASED_PACKAGE_CASH_ITEM_REQ );
EVENT_HANDLER( ENX_BT_NISMS_INVENTORY_PICK_UP_FOR_PACKAGE_ACK );

// 선물하기
EVENT_HANDLER( EGS_CHECK_PRESENT_CASH_INVENTORY_NOT );
_EVENT_HANDLER( ELG_PRESENT_MESSAGE_TO_RECEIVER_NOT, KEGS_PRESENT_MESSAGE_TO_RECEIVER_NOT );

EVENT_HANDLER( DBE_INSERT_CASH_SKILL_POINT_ACK );
EVENT_HANDLER( DBE_EXPIRE_CASH_SKILL_POINT_ACK );

// 장바구니
EVENT_HANDLER( DBE_GET_WISH_LIST_ACK );
EVENT_HANDLER_NOPARAM( EGS_GET_WISH_LIST_REQ );
EVENT_HANDLER( EGS_MODIFY_WISH_LIST_REQ );

//{{ 2010. 11. 17	최육사	넥슨 빌링 청약 철회
#ifdef SERV_NX_BILLING_REFUND
EVENT_HANDLER( EGS_CASH_ITEM_REFUND_REQ );
_EVENT_HANDLER( ENX_BT_REFUND_ACK, KEGS_CASH_ITEM_REFUND_ACK );
#endif SERV_NX_BILLING_REFUND
//}}
//{{ 2011. 11. 21  김민성	전직 변경 아이템
#ifdef SERV_UNIT_CLASS_CHANGE_ITEM
_EVENT_HANDLER( DBE_BUY_UNIT_CLASS_CHANGE_ACK, KDBE_BUY_UNIT_CLASS_CHANGE_REQ );
#endif SERV_UNIT_CLASS_CHANGE_ITEM
//}}
//{{ 2012. 04. 02	김민성		넥슨 auth soap
#ifdef SERV_NEXON_AUTH_SOAP
EVENT_HANDLER( SOAP_CHECK_NEXON_ID_ACK );
#endif SERV_NEXON_AUTH_SOAP
//}}
//{{ 2012. 09. 19   김민성   캐시샵 방문 상태
#ifdef SERV_VISIT_CASH_SHOP
EVENT_HANDLER( EGS_VISIT_CASH_SHOP_NOT );
#endif SERV_VISIT_CASH_SHOP
//}}
//{{ 2012. 09. 22	박세훈	빙고 이벤트
#ifdef SERV_EVENT_BINGO
EVENT_HANDLER_NOPARAM( EGS_BINGO_EVENT_INFO_REQ );
//EVENT_HANDLER( DBE_BINGO_EVENT_INFO_READ_ACK );
EVENT_HANDLER( DBE_BINGO_EVENT_INFO_WRITE_ACK );
EVENT_HANDLER_NOPARAM( EGS_BINGO_EVENT_LOTTERY_REQ );
EVENT_HANDLER( DBE_BINGO_EVENT_LOTTERY_ACK );
EVENT_HANDLER_NOPARAM( EGS_BINGO_EVENT_MIX_REQ );
EVENT_HANDLER( DBE_BINGO_EVENT_MIX_ACK );
EVENT_HANDLER_NOPARAM( EGS_BINGO_EVENT_RESET_REQ );
EVENT_HANDLER( DBE_BINGO_EVENT_RESET_ACK );
EVENT_HANDLER_NOPARAM( EGS_BINGO_EVENT_INIT_REQ );
EVENT_HANDLER( DBE_BINGO_EVENT_INIT_ACK );
_EVENT_HANDLER( ENX_BT_NISMS_INVENTORY_INQUIRY_ACK, KEGS_PURCHASED_CASH_ITEM_LIST_ACK );
#endif SERV_EVENT_BINGO
//}}

#ifdef SERV_ADD_WARP_BUTTON
EVENT_HANDLER( DBE_INSERT_WARP_VIP_ACK )
#endif // SERV_ADD_WARP_BUTTON

#ifdef SERV_EVENT_BUY_FAKE_ITEM
EVENT_HANDLER( EBILL_CHECK_BUY_FAKE_ITEM_ACK )
#endif //SERV_EVENT_BUY_FAKE_ITEM

#ifdef SERV_NEXON_COUPON_SYSTEM// 작업날짜: 2013-06-17	// 박세훈
EVENT_HANDLER( EGS_COUPON_LIST_REQ );
EVENT_HANDLER( SOAP_COUPON_LIST_ACK );
EVENT_HANDLER( EGS_REGIST_COUPON_REQ );
EVENT_HANDLER( EGS_USE_ITEM_COUPON_REQ );
EVENT_HANDLER( EGS_COUPON_TARGET_ITEM_REQ );
EVENT_HANDLER( SOAP_COUPON_TARGET_ITEM_ACK );
EVENT_HANDLER( EGS_DISCOUNT_COUPON_INQUIRY_REQ );
EVENT_HANDLER( EGS_DISCOUNT_COUPON_LIST_INQUIRY_REQ );
#endif // SERV_NEXON_COUPON_SYSTEM

#ifdef SERV_COUNTRY_PH
//EVENT_HANDLER( EJSON_GN_CHECK_ACCOUNT_REQ )
EVENT_HANDLER( EJSON_GN_CHANGE_GAME_CURRENCY_REQ )
//EVENT_HANDLER( EBILL_GN_CHANGE_GAME_CURRENCY_ACK )
EVENT_HANDLER( EGS_EXCHANGE_CASH_NOT )
#endif //SERV_COUNTRY_PH