
#include "ServerDefine.h"

//////////////////////////////////////////////////////////////////////////
// for visual assist

#ifndef EVENT_HANDLER
#define EVENT_HANDLER( eventid )
#endif

#ifndef EVENT_HANDLER_NOPARAM
#define EVENT_HANDLER_NOPARAM( eventid )
#endif

#ifndef _EVENT_HANDLER
#define _EVENT_HANDLER( eventid, structtype )
#endif


//////////////////////////////////////////////////////////////////////////
// 여기서 부터 이벤트 핸들러 정의!

EVENT_HANDLER( DBE_INSERT_REWARD_TO_POST_ACK );

// 우체국
EVENT_HANDLER( EGS_GET_POST_LETTER_LIST_REQ );
EVENT_HANDLER( DBE_GET_POST_LETTER_LIST_ACK );	
EVENT_HANDLER( EGS_SEND_LETTER_REQ );
EVENT_HANDLER( DBE_PREPARE_INSERT_LETTER_TO_POST_ACK );
EVENT_HANDLER( DBE_INSERT_LETTER_TO_POST_ACK );
EVENT_HANDLER( ELG_FIND_USER_SEND_LETTER_NOT );
EVENT_HANDLER( EGS_READ_LETTER_REQ );
EVENT_HANDLER( EGS_GET_ITEM_FROM_LETTER_REQ );
EVENT_HANDLER( DBE_GET_ITEM_FROM_LETTER_ACK );
EVENT_HANDLER( EGS_DELETE_LETTER_REQ );

//{{ 2008. 9. 26  최육사	우체국 블랙리스트
EVENT_HANDLER_NOPARAM( EGS_GET_POST_BLACK_LIST_REQ );
EVENT_HANDLER( EGS_NEW_POST_BLACK_LIST_REQ );
EVENT_HANDLER( DBE_NEW_POST_BLACK_LIST_ACK );
EVENT_HANDLER( EGS_DEL_POST_BLACK_LIST_REQ );
EVENT_HANDLER( DBE_DEL_POST_BLACK_LIST_ACK );
//}}

//{{ 2011. 04. 05  김민성	우편 및 거래 감시
#ifdef SERV_MONITORING_LETTER_AND_TRADE
EVENT_HANDLER( DBE_WRITE_LETTER_AND_TRADE_MOINTORING_ACK );
#endif SERV_MONITORING_LETTER_AND_TRADE
//}}

//{{ 우편 ED 거래시 ED 동기화 - 김민성
#ifdef SERV_SEND_LETTER_BEFOR_ED_SYNC
EVENT_HANDLER( DBE_SYNC_ED_ACK );
#endif SERV_SEND_LETTER_BEFOR_ED_SYNC
//}}

//{{ 2012. 08. 21	박세훈	우편 로직 변경
#ifdef SERV_TRADE_LOGIC_CHANGE_LETTER
EVENT_HANDLER( DBE_GET_ITEM_FROM_LETTER_ARRANGE_ACK );
#endif SERV_TRADE_LOGIC_CHANGE_LETTER
//}}

EVENT_HANDLER_NOPARAM( EGS_RENEWAL_LETTER_REQ );

#ifdef SERV_RELATIONSHIP_SYSTEM_LAUNCHING_EVENT// 작업날짜: 2013-05-12	// 박세훈
EVENT_HANDLER( EGS_SEND_LOVE_LETTER_EVENT_REQ );
EVENT_HANDLER( DBE_SEND_LOVE_LETTER_EVENT_ACK );
#endif // SERV_RELATIONSHIP_SYSTEM_LAUNCHING_EVENT
