
#include "ServerDefine.h"

//////////////////////////////////////////////////////////////////////////
// for visual assist

#ifndef EVENT_HANDLER
#define EVENT_HANDLER( eventid )
#endif

#ifndef EVENT_HANDLER_NOPARAM
#define EVENT_HANDLER_NOPARAM( eventid )
#endif

#ifndef _EVENT_HANDLER
#define _EVENT_HANDLER( eventid, structtype )
#endif


//////////////////////////////////////////////////////////////////////////
// 여기서 부터 이벤트 핸들러 정의!


//{{ 2010. 7. 21  최육사	펫 시스템
#ifdef SERV_PET_SYSTEM
EVENT_HANDLER( EGS_CREATE_PET_REQ );
EVENT_HANDLER( DBE_CREATE_PET_ACK );

EVENT_HANDLER( EGS_GET_PET_LIST_REQ );

EVENT_HANDLER( EGS_SUMMON_PET_REQ );
EVENT_HANDLER( DBE_SUMMON_PET_ACK );
EVENT_HANDLER( ERM_SUMMON_PET_NOT );

EVENT_HANDLER( EGS_COMMANDS_FOR_PETS_REQ );
EVENT_HANDLER( ERM_PET_ACTION_NOT );

EVENT_HANDLER( ERM_DECREASE_PET_SATIETY_NOT );
_EVENT_HANDLER( ERM_CHANGED_PET_SATIETY_NOT, KEGS_CHANGED_PET_SATIETY_NOT );
_EVENT_HANDLER( ERM_CHANGED_PET_INTIMACY_NOT, KEGS_CHANGED_PET_INTIMACY_NOT );
_EVENT_HANDLER( ERM_CHANGED_PET_SATIETY_INTIMACY_NOT, KEGS_CHANGED_PET_SATIETY_INTIMACY_NOT );

EVENT_HANDLER( EGS_FEED_PETS_REQ );
EVENT_HANDLER( EGS_SET_AUTO_FEED_PETS_REQ );

EVENT_HANDLER( EGS_PET_EVOLUTION_REQ );
EVENT_HANDLER( ERM_PET_EVOLUTION_NOT );

//{{ 2012. 02. 22	박세훈	펫 이름 변경권
#ifdef SERV_PET_CHANGE_NAME
EVENT_HANDLER( EGS_CHANGE_PET_NAME_REQ );
EVENT_HANDLER( DBE_CHANGE_PET_NAME_ACK );
#endif SERV_PET_CHANGE_NAME
//}}

#ifdef	SERV_RIDING_PET_SYSTM// 적용날짜: 2013-04-20
EVENT_HANDLER( EGS_GET_RIDING_PET_LIST_REQ );
EVENT_HANDLER( EGS_SUMMON_RIDING_PET_REQ );
EVENT_HANDLER( EGS_UNSUMMON_RIDING_PET_REQ );
EVENT_HANDLER( EGS_CREATE_RIDING_PET_REQ );

EVENT_HANDLER( DBE_GET_RIDING_PET_LIST_ACK );
EVENT_HANDLER( DBE_CREATE_RIDING_PET_ACK );

EVENT_HANDLER( EGS_RELEASE_RIDING_PET_REQ );
_EVENT_HANDLER( DBE_RELEASE_RIDING_PET_ACK, KEGS_RELEASE_RIDING_PET_ACK );

_EVENT_HANDLER( ERM_SUMMON_RIDING_PET_NOT, KEGS_SUMMON_RIDING_PET_NOT );
_EVENT_HANDLER( ERM_UNSUMMON_RIDING_PET_NOT, KEGS_UNSUMMON_RIDING_PET_NOT );

EVENT_HANDLER( EGS_UPDATE_RIDING_PET_NOT );
#endif	// SERV_RIDING_PET_SYSTM

#ifdef SERV_PERIOD_PET
_EVENT_HANDLER( DBE_RELEASE_PET_ACK, KEGS_RELEASE_PET_ACK );
#endif SERV_PERIOD_PET

#endif SERV_PET_SYSTEM
//}}