
#include "ServerDefine.h"

//////////////////////////////////////////////////////////////////////////
// for visual assist

#ifndef EVENT_HANDLER
#define EVENT_HANDLER( eventid )
#endif

#ifndef EVENT_HANDLER_NOPARAM
#define EVENT_HANDLER_NOPARAM( eventid )
#endif

#ifndef _EVENT_HANDLER
#define _EVENT_HANDLER( eventid, structtype )
#endif


//////////////////////////////////////////////////////////////////////////
// 여기서 부터 이벤트 핸들러 정의!


EVENT_HANDLER( EGS_REQUEST_TRADE_REQ );
EVENT_HANDLER( ERM_REQUEST_TRADE_NOT );
EVENT_HANDLER( EGS_REQUEST_TRADE_REPLY_NOT );
EVENT_HANDLER( ERM_REQUEST_TRADE_REPLY_NOT );
EVENT_HANDLER( ERM_OPEN_TRADE_ACK );
EVENT_HANDLER( ERM_ACCEPT_JOIN_TRADE_NOT );
EVENT_HANDLER( ERM_JOIN_TRADE_ACK );
_EVENT_HANDLER( ERM_JOIN_TRADE_NOT, KEGS_JOIN_TRADE_NOT );
EVENT_HANDLER( EGS_BREAK_TRADE_REQ );
_EVENT_HANDLER( ERM_BREAK_TRADE_REQ, KEGS_BREAK_TRADE_REQ );
_EVENT_HANDLER( ERM_BREAK_TRADE_ACK, KEGS_BREAK_TRADE_ACK );
_EVENT_HANDLER( ERM_BREAK_TRADE_NOT, KEGS_BREAK_TRADE_NOT );
EVENT_HANDLER( EGS_UPDATE_TRADE_ITEM_REQ );
_EVENT_HANDLER( ERM_UPDATE_TRADE_ITEM_ACK, KEGS_UPDATE_TRADE_ITEM_ACK );
_EVENT_HANDLER( ERM_UPDATE_TRADE_ITEM_NOT, KEGS_UPDATE_TRADE_ITEM_NOT );
EVENT_HANDLER( EGS_UPDATE_TRADE_ED_REQ );
_EVENT_HANDLER( ERM_UPDATE_TRADE_ED_ACK, KEGS_UPDATE_TRADE_ED_ACK );
_EVENT_HANDLER( ERM_UPDATE_TRADE_ED_NOT, KEGS_UPDATE_TRADE_ED_NOT );
EVENT_HANDLER_NOPARAM( EGS_OFFER_TRADE_REQ );
_EVENT_HANDLER( ERM_OFFER_TRADE_ACK, KEGS_OFFER_TRADE_ACK );
_EVENT_HANDLER( ERM_OFFER_TRADE_NOT, KEGS_OFFER_TRADE_NOT );
EVENT_HANDLER_NOPARAM( EGS_APPROVE_TRADE_REQ );
_EVENT_HANDLER( ERM_APPROVE_TRADE_ACK, KEGS_APPROVE_TRADE_ACK );
_EVENT_HANDLER( ERM_APPROVE_TRADE_NOT, KEGS_APPROVE_TRADE_NOT );
EVENT_HANDLER( ERM_CONFIRM_TRADE_REQ );
EVENT_HANDLER( ERM_CONFIRM_TRADE_NOT );
//{{ 2012. 05. 08	김민성       개인 거래 로직 변경
#ifdef SERV_TRADE_LOGIC_CHANGE_TRADE
_EVENT_HANDLER( ERM_DB_UPDATE_TRADE_COMPLETE_NOT, KERM_DB_UPDATE_TRADE_RESULT_NOT );
EVENT_HANDLER( DBE_TRADE_COMPLETE_ACK );
#else
//{{ 2012. 03. 28	최육사	개인거래 DDOS 방어
#ifdef SERV_TRADE_DDOS_DEFENCE
EVENT_HANDLER( ERM_DB_UPDATE_TRADE_COMPLETE_NOT );
#else
EVENT_HANDLER( DBE_INSERT_TRADE_ITEM_ACK );
#endif SERV_TRADE_DDOS_DEFENCE
//}}
#endif SERV_TRADE_LOGIC_CHANGE_TRADE
//}}

_EVENT_HANDLER( ERM_CHANGE_TRADE_NOT, KEGS_CHANGE_TRADE_NOT );


