
#include "ServerDefine.h"

//////////////////////////////////////////////////////////////////////////
// for visual assist

#ifndef EVENT_HANDLER
#define EVENT_HANDLER( eventid )
#endif

#ifndef EVENT_HANDLER_NOPARAM
#define EVENT_HANDLER_NOPARAM( eventid )
#endif

#ifndef _EVENT_HANDLER
#define _EVENT_HANDLER( eventid, structtype )
#endif


//////////////////////////////////////////////////////////////////////////
// 여기서 부터 이벤트 핸들러 정의!

//{{ 2013. 04. 01	 인연 시스템 - 김민성
#ifdef SERV_RELATIONSHIP_SYSTEM
EVENT_HANDLER( EGS_COUPLE_PROPOSE_REQ );
EVENT_HANDLER( DBE_COUPLE_PROPOSE_USER_FIND_ACK );
EVENT_HANDLER( ELG_COUPLE_PROPOSE_CHECK_CONNECT_USER_ACK );
EVENT_HANDLER( ELG_COUPLE_PROPOSE_NOT );
EVENT_HANDLER( EGS_COUPLE_PROPOSE_AGREE_NOT );
_EVENT_HANDLER( ELG_COUPLE_PROPOSE_AGREE_CHECK_NOT, KEGS_COUPLE_PROPOSE_AGREE_NOT );
EVENT_HANDLER( DBE_COUPLE_MAKING_SUCCESS_ACK );
EVENT_HANDLER( ERM_COUPLE_PROPOSE_RESULT_FAIL_NOT );
_EVENT_HANDLER( ELG_COUPLE_PROPOSE_RESULT_SUCCESS_NOT, KERM_COUPLE_PROPOSE_RESULT_SUCCESS_NOT );
_EVENT_HANDLER( ERM_COUPLE_MAKING_SUCCESS_NOT, KEGS_COUPLE_MAKING_SUCCESS_NOT );
EVENT_HANDLER( EGS_RELATIONSHIP_INFO_REQ );
_EVENT_HANDLER( ELG_RELATIONSHIP_INFO_ACK, KEGS_RELATIONSHIP_INFO_ACK );
_EVENT_HANDLER( ELG_RELATIONSHIP_INFO_GAME_SERVER_REQ, KELG_RELATIONSHIP_INFO_REQ );
EVENT_HANDLER( EGS_RELATIONSHIP_EFFECT_NOT );
_EVENT_HANDLER( ERM_RELATIONSHIP_EFFECT_NOT, KEGS_RELATIONSHIP_EFFECT_NOT );
EVENT_HANDLER( EGS_WEDDING_PROPOSE_REQ );
EVENT_HANDLER( DBE_WEDDING_PROPOSE_ACK );
EVENT_HANDLER( EGS_CHECK_NICK_NAME_REQ );
_EVENT_HANDLER( DBE_CHECK_NICK_NAME_ACK, KEGS_CHECK_NICK_NAME_ACK );
EVENT_HANDLER( EGS_WEDDING_ITEM_INFO_REQ );
_EVENT_HANDLER( DBE_WEDDING_ITEM_INFO_ACK, KEGS_WEDDING_ITEM_INFO_ACK );
_EVENT_HANDLER( ELG_WEDDING_ITEM_FIND_INFO_ACK, KELG_WEDDING_ITEM_FIND_INFO_REQ );
EVENT_HANDLER( DBE_WEDDING_ITEM_DELETE_ACK );
EVENT_HANDLER( EGS_CALL_MY_LOVER_REQ );
EVENT_HANDLER( ELG_CALL_MY_LOVER_FIND_USER_VILLAGE_ACK );
_EVENT_HANDLER( ELG_CALL_MY_LOVER_VILLAGE_NOT, KELG_CALL_MY_LOVER_FIND_USER_VILLAGE_REQ );
EVENT_HANDLER( EGS_CALL_MY_LOVER_AGREE_VILLAGE_NOT );
EVENT_HANDLER( ELG_CALL_MY_LOVER_AGREE_RESULT_VILLAGE_NOT );
EVENT_HANDLER( ELG_CALL_MY_LOVER_STATE_CHANGE_FIELD_NOT );
EVENT_HANDLER( ERM_CALL_MY_LOVER_LEAVE_FIELD_ACK );
EVENT_HANDLER( ERM_CALL_MY_LOVER_CHECK_ROOM_ACK );
EVENT_HANDLER( ELG_CALL_MY_LOVER_FIND_USER_ROOM_ACK );
_EVENT_HANDLER( ELG_CALL_MY_LOVER_ROOM_NOT, KELG_CALL_MY_LOVER_FIND_USER_ROOM_REQ );
EVENT_HANDLER( EGS_CALL_MY_LOVER_AGREE_ROOM_NOT );
EVENT_HANDLER( ELG_CALL_MY_LOVER_JOIN_BATTLE_FIELD_NOT );
EVENT_HANDLER( ELG_CALL_MY_LOVER_AGREE_RESULT_ROOM_NOT );
_EVENT_HANDLER( ERM_LEAVE_BATTLE_FIELD_FOR_CALL_MY_LOVER_ACK, KERM_CALL_MY_LOVER_JOIN_BATTLE_FIELD_REQ );
_EVENT_HANDLER( ERM_CALL_MY_LOVER_JOIN_BATTLE_FIELD_ACK, KEGS_CALL_MY_LOVER_JOIN_BATTLE_FIELD_NOT );
EVENT_HANDLER( ELG_CALL_MY_LOVER_JOIN_BATTLE_FIELD_FAILD_NOT );
EVENT_HANDLER( EGS_JOIN_WEDDING_HALL_REQ );
EVENT_HANDLER( ELG_CHECK_WEDDING_HALL_INFO_ACK );
_EVENT_HANDLER( ERM_LEAVE_BATTLE_FIELD_FOR_JOIN_WEDDING_HALL_ACK, KERM_LEAVE_BATTLE_FIELD_FOR_JOIN_WEDDING_HALL_REQ );
EVENT_HANDLER( ERM_OPEN_WEDDING_HALL_ACK );
_EVENT_HANDLER( ERM_LEAVE_WEDDING_HALL_NOT, KEGS_LEAVE_WEDDING_HALL_NOT );
EVENT_HANDLER( ERM_JOIN_WEDDING_HALL_ACK );
_EVENT_HANDLER( ERM_JOIN_WEDDING_HALL_NOT, KEGS_JOIN_WEDDING_HALL_NOT );
EVENT_HANDLER( EGS_LEAVE_WEDDING_HALL_REQ );
_EVENT_HANDLER( ERM_LEAVE_WEDDING_HALL_ACK, KEGS_LEAVE_ROOM_ACK );
EVENT_HANDLER_NOPARAM( EGS_CHECK_BREAK_UP_REQ );
EVENT_HANDLER_NOPARAM( EGS_BREAK_UP_REQ );
EVENT_HANDLER( DBE_BREAK_UP_ACK );
EVENT_HANDLER( ELG_BREAK_UP_NOT );
EVENT_HANDLER_NOPARAM( EGS_START_WEDDING_REQ );
EVENT_HANDLER( ERM_CHECK_START_WEDDING_ACK );
EVENT_HANDLER_NOPARAM( ERM_CHECK_START_WEDDING_NOT );
EVENT_HANDLER( EGS_START_WEDDING_ASK_ACK );
_EVENT_HANDLER( ERM_START_WEDDING_AGREE_NOT, KEGS_START_WEDDING_AGREE_NOT );
EVENT_HANDLER( ERM_START_WEDDING_NOT );
EVENT_HANDLER( EGS_CHANGE_LOVE_WORD_REQ );
EVENT_HANDLER( DBE_CHANGE_LOVE_WORD_ACK );
EVENT_HANDLER( ELG_CHANGE_LOVE_WORD_NOT );
EVENT_HANDLER( DBE_INSERT_WEDDING_REWARD_ACK );
EVENT_HANDLER( DBE_WRITE_RELATIONSHIP_INFO_LOG_ACK );
#endif SERV_RELATIONSHIP_SYSTEM
//}