
#include "ServerDefine.h"

//////////////////////////////////////////////////////////////////////////
// for visual assist

#ifndef EVENT_HANDLER
#define EVENT_HANDLER( eventid )
#endif

#ifndef EVENT_HANDLER_NOPARAM
#define EVENT_HANDLER_NOPARAM( eventid )
#endif

#ifndef _EVENT_HANDLER
#define _EVENT_HANDLER( eventid, structtype )
#endif


//////////////////////////////////////////////////////////////////////////
// 여기서 부터 이벤트 핸들러 정의!


EVENT_HANDLER_NOPARAM( EGS_OPEN_PVP_ROOM_LIST_REQ );	
EVENT_HANDLER( EGS_CHANGE_PVP_ROOM_LIST_REQ );

EVENT_HANDLER( EGS_INVITE_PVP_ROOM_REQ );
EVENT_HANDLER( ELG_INVITE_PVP_ROOM_ACK );
_EVENT_HANDLER( ELG_INVITE_PVP_ROOM_NOT, KEGS_INVITE_PVP_ROOM_NOT );

EVENT_HANDLER_NOPARAM( EGS_STATE_CHANGE_GAME_INTRUDE_REQ );
EVENT_HANDLER( ERM_STATE_CHANGE_GAME_INTRUDE_ACK );
_EVENT_HANDLER( ERM_STATE_CHANGE_GAME_INTRUDE_NOT, KEGS_STATE_CHANGE_GAME_INTRUDE_NOT );

EVENT_HANDLER( EGS_INTRUDE_START_REQ );
_EVENT_HANDLER( ERM_INTRUDE_START_ACK, KEGS_INTRUDE_START_ACK );
_EVENT_HANDLER( ERM_INTRUDE_START_NOT, KEGS_INTRUDE_START_NOT );

EVENT_HANDLER( EGS_CHANGE_MOTION_REQ );
_EVENT_HANDLER( ERM_CHANGE_MOTION_ACK, KEGS_CHANGE_MOTION_ACK );
_EVENT_HANDLER( ERM_CHANGE_MOTION_NOT, KEGS_CHANGE_MOTION_NOT );

EVENT_HANDLER( EGS_CHANGE_TEAM_REQ );
_EVENT_HANDLER( ERM_CHANGE_TEAM_ACK, KEGS_CHANGE_TEAM_ACK );
_EVENT_HANDLER( ERM_CHANGE_TEAM_NOT, KEGS_CHANGE_TEAM_NOT );

EVENT_HANDLER( EGS_CHANGE_READY_REQ );
EVENT_HANDLER( ERM_CHANGE_READY_ACK );
_EVENT_HANDLER( ERM_CHANGE_READY_NOT, KEGS_CHANGE_READY_NOT );

EVENT_HANDLER( EGS_CHANGE_PITIN_REQ );
_EVENT_HANDLER( ERM_CHANGE_PITIN_ACK, KEGS_CHANGE_PITIN_ACK );
_EVENT_HANDLER( ERM_CHANGE_PITIN_NOT, KEGS_CHANGE_PITIN_NOT );

EVENT_HANDLER( EGS_CHANGE_MAP_REQ );
_EVENT_HANDLER( ERM_CHANGE_MAP_ACK, KEGS_CHANGE_MAP_ACK );
_EVENT_HANDLER( ERM_CHANGE_MAP_NOT, KEGS_CHANGE_MAP_NOT );

EVENT_HANDLER( EGS_CHANGE_SLOT_OPEN_REQ );
_EVENT_HANDLER( ERM_CHANGE_SLOT_OPEN_ACK, KEGS_CHANGE_SLOT_OPEN_ACK );
_EVENT_HANDLER( ERM_CHANGE_SLOT_OPEN_NOT, KEGS_CHANGE_SLOT_OPEN_NOT );

EVENT_HANDLER( EGS_CHANGE_PLAY_TIME_LIMIT_REQ );
_EVENT_HANDLER( ERM_CHANGE_PLAY_TIME_LIMIT_ACK, KEGS_CHANGE_PLAY_TIME_LIMIT_ACK );
_EVENT_HANDLER( ERM_CHANGE_PLAY_TIME_LIMIT_NOT, KEGS_CHANGE_PLAY_TIME_LIMIT_NOT );

EVENT_HANDLER( EGS_CHANGE_WINNING_NUM_KILL_REQ );
_EVENT_HANDLER( ERM_CHANGE_WINNING_NUM_KILL_ACK, KEGS_CHANGE_WINNING_NUM_KILL_ACK );
_EVENT_HANDLER( ERM_CHANGE_WINNING_NUM_KILL_NOT, KEGS_CHANGE_WINNING_NUM_KILL_NOT );

_EVENT_HANDLER( ERM_CURRENT_KILL_SCORE_NOT, KEGS_CURRENT_KILL_SCORE_NOT );
_EVENT_HANDLER( ERM_CURRENT_TEAM_KILL_SCORE_NOT, KEGS_CURRENT_TEAM_KILL_SCORE_NOT );
EVENT_HANDLER_NOPARAM( EGS_LEAVE_GAME_REQ );
_EVENT_HANDLER( ERM_LEAVE_GAME_ACK, KEGS_LEAVE_GAME_ACK );
_EVENT_HANDLER( ERM_LEAVE_GAME_NOT, KEGS_LEAVE_GAME_NOT );

_EVENT_HANDLER( ERM_END_GAME_PVP_RESULT_DATA_NOT, KEGS_END_GAME_PVP_RESULT_DATA_NOT );

//{{ 2010. 07. 01  최육사	내구도 개편
EVENT_HANDLER_NOPARAM( ERM_DECREASE_ENDURANCE_PVP_NOT );
//}}

EVENT_HANDLER( ERM_UPDATE_PVP_UNIT_INFO_NOT );
EVENT_HANDLER( ERM_PVP_USER_STATISTICS_NOT );

#ifdef DUNGEON_ITEM
EVENT_HANDLER( EGS_CREATE_PVP_ITEM_REQ );
_EVENT_HANDLER( ERM_CREATE_PVP_ITEM_ACK, KEGS_CREATE_PVP_ITEM_ACK );
_EVENT_HANDLER( ERM_CREATE_PVP_ITEM_NOT, KEGS_CREATE_PVP_ITEM_NOT );
_EVENT_HANDLER( ERM_CHANGE_PVP_ITEM_NOT, KEGS_CHANGE_PVP_ITEM_NOT );
EVENT_HANDLER_NOPARAM( EGS_CHANGE_PVP_ITEMMODE_REQ );
_EVENT_HANDLER( ERM_CHANGE_PVP_ITEMMODE_ACK, KEGS_CHANGE_PVP_ITEMMODE_ACK );
_EVENT_HANDLER( ERM_CHANGE_PVP_ITEMMODE_NOT, KEGS_CHANGE_PVP_ITEMMODE_NOT );
#endif DUNGEON_ITEM

#ifdef SERVER_PVP_BASE_DEFENCE_TEST
_EVENT_HANDLER( EGS_CHANGE_PVP_GAME_OPTION_REQ, KEGS_CHANGE_PVP_GAME_OPTION_REQ );
_EVENT_HANDLER( ERM_CHANGE_PVP_GAME_OPTION_ACK, KEGS_CHANGE_PVP_GAME_OPTION_ACK );
_EVENT_HANDLER( ERM_CHANGE_PVP_GAME_OPTION_NOT, KEGS_CHANGE_PVP_GAME_OPTION_NOT );
#endif SERVER_PVP_BASE_DEFENCE_TEST

//{{ 2012. 02. 14    김민성   PVP 대전 Item 생성 위치 변경
#ifdef SERV_PVP_ITEM_CHANGE_POS
EVENT_HANDLER( EGS_CHANGE_PVP_ITEM_POS_REQ );
_EVENT_HANDLER( ERM_CHANGE_PVP_ITEM_POS_ACK, KEGS_CHANGE_PVP_ITEM_POS_ACK );
_EVENT_HANDLER( ERM_CHANGE_PVP_ITEM_POS_NOT, KEGS_CHANGE_PVP_ITEM_POS_NOT );
#endif SERV_PVP_ITEM_CHANGE_POS
//}}
//{{ 2012 대전 시즌2 전야 런칭 이벤트	- 김민성
#ifdef SERV_2012_PVP_SEASON2_EVENT
EVENT_HANDLER( DBE_PVP_WIN_EVENT_CHECK_ACK );
#endif SERV_2012_PVP_SEASON2_EVENT
//}}

//{{ 2012. 10. 10	박세훈	튕긴 유저 마을로 보내기
#ifdef UDP_CAN_NOT_SEND_USER_KICK
_EVENT_HANDLER( ERM_UDP_KICK_STATE_CHANGE_FIELD_NOT, UidType );
//EVENT_HANDLER_NOPARAM( ERM_UDP_KICK_STATE_CHANGE_FIELD_NOT );
#endif UDP_CAN_NOT_SEND_USER_KICK
//}}

#ifdef SERV_NEW_PVPROOM_PROCESS
_EVENT_HANDLER( EGS_CHANGE_PVP_ROOM_PUBLIC_REQ, KEGS_CHANGE_PVP_ROOM_PUBLIC_REQ );
_EVENT_HANDLER( ERM_CHANGE_PVP_ROOM_PUBLIC_ACK, KEGS_CHANGE_PVP_ROOM_PUBLIC_ACK );
_EVENT_HANDLER( ERM_CHANGE_PVP_ROOM_PUBLIC_NOT, KEGS_CHANGE_PVP_ROOM_PUBLIC_NOT );
_EVENT_HANDLER( EGS_CHANGE_PVP_ROOM_NAME_REQ, KEGS_CHANGE_PVP_ROOM_NAME_REQ );
_EVENT_HANDLER( ERM_CHANGE_PVP_ROOM_NAME_ACK, KEGS_CHANGE_PVP_ROOM_NAME_ACK );
_EVENT_HANDLER( ERM_CHANGE_PVP_ROOM_NAME_NOT, KEGS_CHANGE_PVP_ROOM_NAME_NOT );
#endif SERV_NEW_PVPROOM_PROCESS

#ifdef SERV_PVP_REMATCH
EVENT_HANDLER( EGS_PVP_REMATCH_REQ );
_EVENT_HANDLER( ERM_PVP_REMATCH_ACK, KEGS_PVP_REMATCH_ACK );
_EVENT_HANDLER( ERM_PVP_REMATCH_NOT, KEGS_PVP_REMATCH_NOT );
#endif SERV_PVP_REMATCH