
#include "ServerDefine.h"

//////////////////////////////////////////////////////////////////////////
// for visual assist

#ifndef EVENT_HANDLER
#define EVENT_HANDLER( eventid )
#endif

#ifndef EVENT_HANDLER_NOPARAM
#define EVENT_HANDLER_NOPARAM( eventid )
#endif

#ifndef _EVENT_HANDLER
#define _EVENT_HANDLER( eventid, structtype )
#endif


//////////////////////////////////////////////////////////////////////////
// 여기서 부터 이벤트 핸들러 정의!

//{{ 2011. 06. 21	최육사	대전 개편
#ifdef SERV_PVP_NEW_SYSTEM
EVENT_HANDLER( EGS_CHANGE_PARTY_TYPE_REQ );
_EVENT_HANDLER( EPM_CHANGE_PARTY_TYPE_ACK, KEGS_CHANGE_PARTY_TYPE_ACK );
_EVENT_HANDLER( EPM_CHANGE_PARTY_TYPE_NOT, KEGS_CHANGE_PARTY_TYPE_NOT );

EVENT_HANDLER( EGS_PVP_PARTY_CHANGE_MATCH_INFO_REQ );
_EVENT_HANDLER( EPM_PVP_PARTY_CHANGE_MATCH_INFO_ACK, KEGS_PVP_PARTY_CHANGE_MATCH_INFO_ACK );
_EVENT_HANDLER( EPM_PVP_PARTY_CHANGE_MATCH_INFO_NOT, KEGS_PVP_PARTY_CHANGE_MATCH_INFO_NOT );

EVENT_HANDLER( EGS_REQUEST_MATCH_MAKING_REQ );
EVENT_HANDLER( EPM_GET_PARTY_INFO_FOR_MATCH_MAKING_ACK );
_EVENT_HANDLER( EGB_REQUEST_MATCH_MAKING_ACK, KEGS_REQUEST_MATCH_MAKING_ACK );
_EVENT_HANDLER( EGB_REG_MATCH_WAIT_LIST_SUCCESS_NOT, KEGS_REG_MATCH_WAIT_LIST_SUCCESS_NOT );

EVENT_HANDLER_NOPARAM( EGS_CANCEL_MATCH_MAKING_REQ );
_EVENT_HANDLER( EGB_CANCEL_MATCH_MAKING_ACK, KEGS_CANCEL_MATCH_MAKING_ACK );

_EVENT_HANDLER( EGB_MATCH_MAKING_SUCCESS_NOT, KEGS_MATCH_MAKING_SUCCESS_NOT );
EVENT_HANDLER( EGS_MATCH_MAKING_SUCCESS_REPLY_NOT );

_EVENT_HANDLER( EGB_UNREG_MATCH_WAIT_LIST_NOT, KEGS_UNREG_MATCH_WAIT_LIST_NOT );
_EVENT_HANDLER( EGB_MATCH_CLOSE_NOT, KEGS_MATCH_CLOSE_NOT );

EVENT_HANDLER( EGB_REMATCH_MAKING_USER_NOT );

EVENT_HANDLER_NOPARAM( EGB_GET_ROOM_USER_INFO_FOR_MATCH_REQ );

EVENT_HANDLER( EGB_OPEN_PVP_ROOM_FOR_MATCH_REQ );

_EVENT_HANDLER( ERM_OPEN_PVP_ROOM_FOR_MATCH_ACK, KEGB_OPEN_PVP_ROOM_FOR_MATCH_ACK );
//{{ 2012. 06. 05	최육사	배틀필드 시스템
#ifdef SERV_BATTLE_FIELD_SYSTEM
_EVENT_HANDLER( ERM_LEAVE_BATTLE_FIELD_FOR_PVP_GAME_START_ACK, KEGS_LEAVE_ROOM_ACK );
#endif SERV_BATTLE_FIELD_SYSTEM
//}}
_EVENT_HANDLER( ERM_GAME_START_PVP_MATCH_NOT, KEGS_GAME_START_PVP_MATCH_NOT );

EVENT_HANDLER( EGS_PVP_NPC_UNIT_RE_BIRTH_POS_REQ );
_EVENT_HANDLER( ERM_PVP_NPC_UNIT_RE_BIRTH_POS_ACK, KEGS_PVP_NPC_UNIT_RE_BIRTH_POS_ACK );

EVENT_HANDLER( EGS_PVP_NPC_UNIT_INFO_TO_SERVER_REQ );
_EVENT_HANDLER( ERM_PVP_NPC_UNIT_INFO_TO_SERVER_ACK, KEGS_PVP_NPC_UNIT_INFO_TO_SERVER_ACK );

EVENT_HANDLER_NOPARAM( EGB_CHECK_INVALID_MATCH_NOT );
#endif SERV_PVP_NEW_SYSTEM
//}}



