
#include "ServerDefine.h"

//////////////////////////////////////////////////////////////////////////
// for visual assist

#ifndef EVENT_HANDLER
#define EVENT_HANDLER( eventid )
#endif

#ifndef EVENT_HANDLER_NOPARAM
#define EVENT_HANDLER_NOPARAM( eventid )
#endif

#ifndef _EVENT_HANDLER
#define _EVENT_HANDLER( eventid, structtype )
#endif


//////////////////////////////////////////////////////////////////////////
// 여기서 부터 이벤트 핸들러 정의!


//{{ 2008. 11. 4  최육사	광장 개편
EVENT_HANDLER( EGS_STATE_CHANGE_FIELD_REQ );
EVENT_HANDLER( ERM_LEAVE_FIELD_ACK );
EVENT_HANDLER( EGS_FIELD_LOADING_COMPLETE_REQ );
EVENT_HANDLER( ERM_JOIN_FIELD_ACK );
EVENT_HANDLER_NOPARAM( EGS_LEAVE_FIELD_NOT );

//{{ 2012. 11. 7	최육사	배틀필드 시스템
#ifdef SERV_BATTLE_FIELD_SYSTEM
_EVENT_HANDLER( ERM_LEAVE_ROOM_FOR_ENTER_THE_VILLAGE_ACK, KEGS_LEAVE_ROOM_ACK );
#endif SERV_BATTLE_FIELD_SYSTEM
//}}

EVENT_HANDLER( EGS_FIELD_UNIT_SYNC_DATA_NOT );
_EVENT_HANDLER( ERM_FIELD_UNIT_SYNC_DATA_BROAD_NOT, KEGS_FIELD_UNIT_SYNC_DATA_BROAD_NOT );

//{{ 2009. 1. 13  최육사	필드 유저 리스트
EVENT_HANDLER( EGS_COMMUNITY_USER_LIST_REQ );
_EVENT_HANDLER( ERM_FIELD_USER_LIST_ACK, KEGS_COMMUNITY_USER_LIST_ACK );
//}}

//{{ 2008. 12. 9  최육사
EVENT_HANDLER( EGS_OPTION_UPDATE_REQ );
//}}

//{{ 2009. 4. 7  최육사		친구정보
EVENT_HANDLER( EGS_UPDATE_FRIEND_INFO_REQ );
_EVENT_HANDLER( ELG_FIND_FRIEND_UNIT_INFO_ACK, KEGS_UPDATE_FRIEND_INFO_ACK );
//}}

//{{ 2011. 09. 20  김민성	게임내 ED 감시 모니터링
#ifdef SERV_ED_MONITORING_IN_GAME
EVENT_HANDLER( EGS_ED_MONITORING_BLOCK_REQ );
EVENT_HANDLER( EGS_COMMUNITY_USER_LIST_MONITORING_MODE_REQ );
#endif SERV_ED_MONITORING_IN_GAME
//}}

//{{ 2012. 11. 15	박세훈	Field PT 로그 추가
#ifdef SERV_FIELD_PLAY_TIME_LOG
EVENT_HANDLER( ERM_FIELD_USER_STATISTICS_NOT );
#endif SERV_FIELD_PLAY_TIME_LOG
//}}

#ifdef SERV_INVISIBLE_GM
EVENT_HANDLER_NOPARAM( EGS_TOGGLE_INVISIBLE_REQ );
#endif SERV_INVISIBLE_GM
