
#include "ServerDefine.h"

//////////////////////////////////////////////////////////////////////////
// for visual assist

#ifndef EVENT_HANDLER
#define EVENT_HANDLER( eventid )
#endif

#ifndef EVENT_HANDLER_NOPARAM
#define EVENT_HANDLER_NOPARAM( eventid )
#endif

#ifndef _EVENT_HANDLER
#define _EVENT_HANDLER( eventid, structtype )
#endif


//////////////////////////////////////////////////////////////////////////
// 여기서 부터 이벤트 핸들러 정의!


// 자동 파티 신청
EVENT_HANDLER( EGS_AUTO_PARTY_DUNGEON_GAME_REQ );
EVENT_HANDLER( EPM_CHECK_FOR_AUTO_PARTY_MAKING_REQ );
EVENT_HANDLER( EPM_GET_PARTY_INFO_FOR_AUTO_PARTY_MAKING_ACK );
_EVENT_HANDLER( EGB_REQUEST_AUTO_PARTY_MAKING_ACK, KEGS_AUTO_PARTY_DUNGEON_GAME_ACK );

// 자동 파티 통보
_EVENT_HANDLER( EGB_REG_AUTO_PARTY_WAIT_LIST_SUCCESS_NOT, KEGS_REG_AUTO_PARTY_WAIT_LIST_SUCCESS_NOT );
_EVENT_HANDLER( EGB_AUTO_PARTY_MAKING_SUCCESS_NOT, KEGS_AUTO_PARTY_MAKING_SUCCESS_NOT );
EVENT_HANDLER( EGS_AUTO_PARTY_MAKING_SUCCESS_REPLY_NOT );

// 자동 파티 취소
EVENT_HANDLER_NOPARAM( EGS_CANCEL_AUTO_PARTY_MAKING_REQ );
_EVENT_HANDLER( EGB_CANCEL_AUTO_PARTY_MAKING_ACK, KEGS_CANCEL_AUTO_PARTY_MAKING_ACK );
_EVENT_HANDLER( EGB_UNREG_AUTO_PARTY_WAIT_LIST_NOT, KEGS_UNREG_AUTO_PARTY_WAIT_LIST_NOT );

// 자동 파티 실패에 따른 재등록 처리
EVENT_HANDLER( EGB_REMAKING_AUTO_PARTY_NOT );

// 자동 파티 닫힘
_EVENT_HANDLER( EGB_AUTO_PARTY_CLOSE_NOT, KEGS_AUTO_PARTY_CLOSE_NOT );

// 자동 파티 매칭 성공에 따른 파티 재결합
EVENT_HANDLER( EGB_GET_REGROUP_PARTY_INFO_REQ );
_EVENT_HANDLER( EGB_REGROUP_PARTY_FOR_AUTO_PARTY_DUNGEON_GAME_REQ, KEPM_REGROUP_PARTY_FOR_AUTO_PARTY_DUNGEON_GAME_REQ );
_EVENT_HANDLER( EPM_REGROUP_PARTY_FOR_AUTO_PARTY_DUNGEON_GAME_ACK, KEPM_REGROUP_PARTY_FOR_AUTO_PARTY_DUNGEON_GAME_ACK );
_EVENT_HANDLER( EPM_REGROUP_PARTY_NOT, KEGS_REGROUP_PARTY_NOT );

EVENT_HANDLER( EPM_LEAVE_PARTY_BY_AUTO_PARTY_NOT );

_EVENT_HANDLER( EPM_PREPARE_FOR_REGROUP_PARTY_AND_CHECK_NEW_HOST_NOT, KEPM_REQUEST_REGROUP_PARTY_NOT );

// 자동 파티 보너스
EVENT_HANDLER( EGS_REQUEST_GET_AUTO_PARTY_BONUS_INFO_NOT );
//{{ 2012. 11. 13	최육사		자동파티 대기열 카운트 표시
#ifdef SERV_AUTO_PARTY_WAIT_USER_COUNT_VIEW
_EVENT_HANDLER( EGB_AUTO_PARTY_WAIT_USER_COUNT_NOT, KEGS_AUTO_PARTY_WAIT_USER_COUNT_NOT );
#endif SERV_AUTO_PARTY_WAIT_USER_COUNT_VIEW
//}}


