
#include "ServerDefine.h"

//////////////////////////////////////////////////////////////////////////
// for visual assist

#ifndef EVENT_HANDLER
#define EVENT_HANDLER( eventid )
#endif

#ifndef EVENT_HANDLER_NOPARAM
#define EVENT_HANDLER_NOPARAM( eventid )
#endif

#ifndef _EVENT_HANDLER
#define _EVENT_HANDLER( eventid, structtype )
#endif


//////////////////////////////////////////////////////////////////////////
// 여기서 부터 이벤트 핸들러 정의!


EVENT_HANDLER( EGS_BUY_ED_ITEM_REQ );
EVENT_HANDLER( DBE_BUY_ED_ITEM_ACK );
EVENT_HANDLER( EGS_SELL_ED_ITEM_REQ );
//{{ 2010. 11. 18	최육사	아이템 판매 차단
#ifdef SERV_AUTO_HACK_CHECK_SELL_ITEM
EVENT_HANDLER( ERM_CHECK_SELL_ED_ITEM_ACK );
#endif SERV_AUTO_HACK_CHECK_SELL_ITEM
//}}
EVENT_HANDLER( DBE_INSERT_ITEM_ACK );

EVENT_HANDLER( EGS_CHANGE_INVENTORY_SLOT_ITEM_REQ );
//{{ 2013. 07. 10	최육사	공유 은행
#ifdef SERV_SHARING_BANK_TEST
EVENT_HANDLER( DBE_CHANGE_INVENTORY_SLOT_ITEM_ACK );
#endif SERV_SHARING_BANK_TEST
//}}
EVENT_HANDLER( ERM_CHANGE_EQUIPPED_ITEM_IN_FIELD_NOT );
EVENT_HANDLER( ERM_CHANGE_EQUIPPED_ITEM_IN_SQUARE_NOT );
EVENT_HANDLER( ERM_CHANGE_EQUIPPED_ITEM_IN_ROOM_NOT );
EVENT_HANDLER( EGS_DELETE_ITEM_REQ );

EVENT_HANDLER( EGS_USE_QUICK_SLOT_REQ );   
//{{ 2013. 04. 10	최육사	어둠의 문 개편
#ifdef SERV_NEW_DEFENCE_DUNGEON
EVENT_HANDLER( EGS_USE_DEFENCE_DUNGEON_QUICK_SLOT_REQ );
#endif SERV_NEW_DEFENCE_DUNGEON
//}}
_EVENT_HANDLER( ERM_USE_QUICK_SLOT_NOT, KEGS_USE_QUICK_SLOT_NOT );

EVENT_HANDLER( EGS_REPAIR_ITEM_REQ );
_EVENT_HANDLER( ERM_REPAIR_ITEM_NOT, KEGS_REPAIR_ITEM_NOT );

EVENT_HANDLER( EGS_OPEN_RANDOM_ITEM_REQ );
//{{ 2010. 12. 20	최육사	특정 시각 큐브 보상
#ifdef SERV_TIME_OPEN_RANDOM_ITEM_EVENT
EVENT_HANDLER( ELG_CHECK_TIME_RANDOM_ITEM_EVENT_ACK );
#endif SERV_TIME_OPEN_RANDOM_ITEM_EVENT
//}}
EVENT_HANDLER( DBE_OPEN_RANDOM_ITEM_ACK );

EVENT_HANDLER( EGS_ITEM_MANUFACTURE_REQ );
EVENT_HANDLER( DBE_ITEM_MANUFACTURE_ACK );

EVENT_HANDLER( EGS_RESOLVE_ITEM_REQ );
EVENT_HANDLER( DBE_RESOLVE_ITEM_ACK );
EVENT_HANDLER( EGS_ENCHANT_ITEM_REQ );
EVENT_HANDLER( DBE_ENCHANT_ITEM_ACK );
EVENT_HANDLER( EGS_SOCKET_ITEM_REQ );
EVENT_HANDLER( DBE_SOCKET_ITEM_ACK );

//{{ 2008. 9. 3  최육사		속성강화
EVENT_HANDLER( EGS_ATTRIB_ENCHANT_ITEM_REQ );
EVENT_HANDLER( DBE_ATTRIB_ENCHANT_ITEM_ACK );
EVENT_HANDLER( EGS_IDENTIFY_ITEM_REQ );
EVENT_HANDLER( DBE_IDENTIFY_ITEM_ACK );
//}}

//{{ 2008. 10. 9  최육사	아이템사용
EVENT_HANDLER( EGS_USE_ITEM_IN_INVENTORY_REQ );
//}}
//{{ 2011. 10. 14	최육사	아이템 사용 DB 업데이트 수정
#ifdef SERV_USE_ITEM_DB_UPDATE_FIX
EVENT_HANDLER( DBE_USE_ITEM_IN_INVENTORY_ACK );
#endif SERV_USE_ITEM_DB_UPDATE_FIX
//}}

//{{ 2008. 12. 19  최육사	아이템 복구
EVENT_HANDLER( EGS_RESTORE_ITEM_REQ );
EVENT_HANDLER( DBE_RESTORE_ITEM_ACK );
//}}

//{{ 2008. 12. 25  최육사	부여
EVENT_HANDLER( EGS_ENCHANT_ATTACH_ITEM_REQ );
EVENT_HANDLER( DBE_ENCHANT_ATTACH_ITEM_ACK );
//}}

//{{ 2008. 11. 18  최육사	아이템 교환
EVENT_HANDLER( EGS_ITEM_EXCHANGE_REQ );
EVENT_HANDLER( DBE_ITEM_EXCHANGE_ACK );
//}}

//{{ 2009. 8. 7  최육사		은행
EVENT_HANDLER_NOPARAM( EGS_GET_MY_BANK_INFO_REQ );
//}}

//{{ 2009. 8. 27  최육사	밀봉
EVENT_HANDLER( EGS_SEAL_ITEM_REQ );
EVENT_HANDLER( DBE_SEAL_ITEM_ACK );
EVENT_HANDLER( EGS_UNSEAL_ITEM_REQ );
EVENT_HANDLER( DBE_UNSEAL_ITEM_ACK );
//}}

//{{ 2009. 12. 14  최육사	헤니르임시인벤
EVENT_HANDLER_NOPARAM( ERM_CLEAR_TEMP_INVENTORY_NOT );
//}}

//{{ 2010. 8. 16	최육사	기간 리셋 아이템 이벤트
#ifdef SERV_RESET_PERIOD_EVENT
EVENT_HANDLER( DBE_RESET_PERIOD_ITEM_ACK );	
#endif SERV_RESET_PERIOD_EVENT
//}}

//{{ 2011. 01. 04  김민성	속성 부적
#ifdef SERV_ATTRIBUTE_CHARM
EVENT_HANDLER( EGS_ATTRIB_ATTACH_ITEM_REQ );
EVENT_HANDLER( DBE_ATTRIB_ATTACH_ITEM_ACK );
#endif SERV_ATTRIBUTE_CHARM
//}}

//{{ 2011. 06. 22    김민성    이탈 방지 모델 - NEXON 세션 시스템 수정
#ifdef SERV_NEXON_SESSION_PROTOCOL
EVENT_HANDLER( EGS_OUT_USER_RETAINING_REQ );
EVENT_HANDLER( DBE_CHECK_RETAINING_USER_ACK );
EVENT_HANDLER( EGS_RETAINING_SELECT_REWARD_REQ );
EVENT_HANDLER( DBE_RETAINING_SELECT_REWARD_ACK );
_EVENT_HANDLER( DBE_INSERT_RETAINING_USER_ACK, KDBE_INSERT_RETAINING_USER_REQ );
#endif SERV_NEXON_SESSION_PROTOCOL
//}} 

//{{ 2012. 02. 21	김민성	인벤토리 정렬
#ifdef SERV_SORT_CATEGORY_ITEM
EVENT_HANDLER( EGS_SORT_CATEGORY_ITEM_REQ );
#endif SERV_SORT_CATEGORY_ITEM
//}}
//{{ 2012. 12. 19  교환(한정 수량) - 김민성
#ifdef SERV_ITEM_EXCHANGE_LIMIT_COUNT
EVENT_HANDLER( DBE_ITEM_EXCHANGE_LIMIT_CHECK_ACK )
#endif SERV_ITEM_EXCHANGE_LIMIT_COUNT
//}}

//{{ 2011.03.16   임규수 아바타 분해 시스템
#ifdef SERV_MULTI_RESOLVE
EVENT_HANDLER( EGS_RESOLVE_ITEM_AVATAR_REQ );
#endif SERV_MULTI_RESOLVE
//}}

//{{ 2011.05.04   임규수 아바타 합성 시스템
#ifdef SERV_SYNTHESIS_AVATAR
EVENT_HANDLER_NOPARAM( EGS_SYNTHESIS_SOCKET_GROUPID_REQ );

EVENT_HANDLER( EGS_SYNTHESIS_ITEM_REQ );
EVENT_HANDLER( DBE_OPEN_SYNTHESIS_ITEM_ACK );
#endif SERV_SYNTHESIS_AVATAR
//}

//{{ 지헌 - 은행 개편 퀘스트, 캐쉬 작업 
#ifdef SERV_SHARING_BANK_QUEST_CASH
EVENT_HANDLER( DBE_SHARING_BACK_OPEN_ACK );
#endif
//}}

#ifdef	SERV_SHARING_BANK_TEST
EVENT_HANDLER( EGS_GET_SHARE_BANK_REQ );
_EVENT_HANDLER( DBE_GET_SHARE_BANK_ACK, KEGS_GET_SHARE_BANK_ACK );

EVENT_HANDLER( DBE_UPDATE_SHARE_ITEM_ACK );
_EVENT_HANDLER( DBE_UPDATE_SHARE_ITEM_FOR_MOVE_SLOT_ACK, KDBE_UPDATE_SHARE_ITEM_ACK );
//EVENT_HANDLER_NOPARAM( EGS_CLOSE_BANK_NOT );
#endif	SERV_SHARING_BANK_TEST

#ifdef SERV_SHARING_BANK_EVENT
EVENT_HANDLER_NOPARAM( DBE_SHARING_BANK_EVENT_ACK );
#endif

#ifdef SERV_GOLD_TICKET
EVENT_HANDLER( EPUBLISHER_CHARGE_POINT_ACK );
#endif //SERV_GOLD_TICKET
#ifdef SERV_DEVELOPER_RANDOM_OPEN_ITEM_LOG
EVENT_HANDLER( EGS_OPEN_RANDOM_ITEM_DEVELOPER_REQ );
#endif//SERV_DEVELOPER_RANDOM_OPEN_ITEM_LOG

//{{ 2013. 05. 15	최육사	아이템 개편
#ifdef SERV_NEW_ITEM_SYSTEM_2013_05
EVENT_HANDLER( EGS_ITEM_EVALUATE_REQ );
EVENT_HANDLER( DBE_ITEM_EVALUATE_ACK );

EVENT_HANDLER( EGS_RESTORE_ITEM_EVALUATE_REQ );
EVENT_HANDLER( DBE_RESTORE_ITEM_EVALUATE_ACK );

EVENT_HANDLER( EGS_ITEM_CONVERT_REQ );
EVENT_HANDLER( DBE_ITEM_CONVERT_ACK );
#endif SERV_NEW_ITEM_SYSTEM_2013_05
//}}

#ifdef SERV_TIME_ENCHANT_EVENT// 작업날짜: 2013-05-28	// 박세훈
EVENT_HANDLER( EGB_TIME_ENCHANT_EVENT_CUBE_NOT );
#endif // SERV_TIME_ENCHANT_EVENT

#ifdef SERV_ITEM_EXCHANGE_LIMIT// 작업날짜: 2013-06-30	// 박세훈
EVENT_HANDLER( EGB_EXCHANGE_LIMIT_ACK );
#endif // SERV_ITEM_EXCHANGE_LIMIT

#ifdef SERV_RECRUIT_EVENT_BASE
EVENT_HANDLER( EGS_USE_RECRUIT_TICKET_REQ );
EVENT_HANDLER( DBE_USE_RECRUIT_TICKET_ACK );
EVENT_HANDLER( EGS_REGISTER_RECRUITER_REQ );
EVENT_HANDLER( DBE_REGISTER_RECRUITER_ACK );
#endif SERV_RECRUIT_EVENT_BASE

#ifdef SERV_READY_TO_SOSUN_EVENT
EVENT_HANDLER_NOPARAM( EGS_READY_TO_SOSUN_EVENT_REQ );
EVENT_HANDLER( DBE_READY_TO_SOSUN_EVENT_ACK );
#endif SERV_READY_TO_SOSUN_EVENT