
#include "ServerDefine.h"

//////////////////////////////////////////////////////////////////////////
// for visual assist

#ifndef EVENT_HANDLER
#define EVENT_HANDLER( eventid )
#endif

#ifndef EVENT_HANDLER_NOPARAM
#define EVENT_HANDLER_NOPARAM( eventid )
#endif

#ifndef _EVENT_HANDLER
#define _EVENT_HANDLER( eventid, structtype )
#endif


//////////////////////////////////////////////////////////////////////////
// 여기서 부터 이벤트 핸들러 정의!


EVENT_HANDLER( EGS_CREATE_ROOM_REQ );
//{{ 2008. 12. 4  최육사
EVENT_HANDLER( EGS_CREATE_TUTORIAL_ROOM_REQ );
//}}
_EVENT_HANDLER( ERM_OPEN_ROOM_ACK, KEGS_CREATE_ROOM_ACK );
EVENT_HANDLER( EGS_JOIN_ROOM_REQ );
_EVENT_HANDLER( ERM_JOIN_ROOM_ACK, KEGS_JOIN_ROOM_ACK );
_EVENT_HANDLER( ERM_JOIN_ROOM_NOT, KEGS_JOIN_ROOM_NOT );
EVENT_HANDLER( EGS_QUICK_JOIN_REQ );
_EVENT_HANDLER( ERM_QUICK_JOIN_ACK, KEGS_JOIN_ROOM_ACK );
EVENT_HANDLER( EGS_LEAVE_ROOM_REQ );

//{{ 2011. 02. 21  김민성	특정 던전 입장 아이템 버그 수정
#ifdef SERV_DUNGEON_REQUIRED_ITEM_BUG
_EVENT_HANDLER( ERM_LEAVE_ROOM_ACK, KEGS_LEAVE_ROOM_ACK );
#else
_EVENT_HANDLER( ERM_LEAVE_ROOM_ACK, KPacketOK );
#endif SERV_DUNGEON_REQUIRED_ITEM_BUG
//}}

_EVENT_HANDLER( ERM_LEAVE_ROOM_NOT, KEGS_LEAVE_ROOM_NOT );
EVENT_HANDLER( EGS_BAN_USER_REQ );
_EVENT_HANDLER( ERM_BAN_USER_ACK, KPacketOK );
EVENT_HANDLER_NOPARAM( ERM_BAN_USER_NOT );

EVENT_HANDLER( EGS_STATE_CHANGE_GAME_START_REQ );
EVENT_HANDLER( EGS_GAME_LOADING_REQ );
EVENT_HANDLER( ERM_GAME_START_ACK );
EVENT_HANDLER( ERM_GAME_START_NOT );
_EVENT_HANDLER( ERM_GAME_LOADING_ACK, KPacketOK );
_EVENT_HANDLER( ERM_GAME_LOADING_NOT, KEGS_GAME_LOADING_NOT );
EVENT_HANDLER_NOPARAM( ERM_GAME_LOADING_TIME_OUT_NOT );
EVENT_HANDLER_NOPARAM( ERM_GAME_LOADING_ALL_UNIT_OK_NOT );
_EVENT_HANDLER( ERM_PLAY_START_NOT, KEGS_PLAY_START_NOT );
EVENT_HANDLER( EGS_END_GAME_REQ );
_EVENT_HANDLER( ERM_END_GAME_ACK, KPacketOK );
_EVENT_HANDLER( ERM_END_GAME_NOT, KEGS_END_GAME_NOT );
EVENT_HANDLER( EGS_STATE_CHANGE_RESULT_REQ );
_EVENT_HANDLER( ERM_STATE_CHANGE_RESULT_ACK, KEGS_STATE_CHANGE_RESULT_ACK );
_EVENT_HANDLER( ERM_STATE_CHANGE_RESULT_NOT, KEGS_STATE_CHANGE_RESULT_NOT );

EVENT_HANDLER( EGS_USER_UNIT_RE_BIRTH_POS_REQ );
_EVENT_HANDLER( ERM_USER_UNIT_RE_BIRTH_POS_ACK, KPacketOK );
_EVENT_HANDLER( ERM_USER_UNIT_RE_BIRTH_NOT, KEGS_USER_UNIT_RE_BIRTH_NOT );

EVENT_HANDLER( EGS_ROOM_LIST_REQ );
EVENT_HANDLER( EGS_USER_UNIT_DIE_REQ );

//{{ 2011. 09. 19  김민성	칭호 획득 조건 추가
#ifdef SERV_ADD_TITLE_CONDITION
EVENT_HANDLER( ERM_USER_UNIT_DIE_ACK );
#else
_EVENT_HANDLER( ERM_USER_UNIT_DIE_ACK, KEGS_USER_UNIT_DIE_ACK );
#endif SERV_ADD_TITLE_CONDITION
//}}

EVENT_HANDLER( ERM_USER_UNIT_DIE_NOT );
EVENT_HANDLER_NOPARAM( EGS_USER_UNIT_DIE_COMPLETE_REQ );
_EVENT_HANDLER( ERM_USER_UNIT_DIE_COMPLETE_ACK, KEGS_USER_UNIT_DIE_COMPLETE_ACK );
_EVENT_HANDLER( ERM_USER_UNIT_DIE_COMPLETE_NOT, KEGS_USER_UNIT_DIE_COMPLETE_NOT );

_EVENT_HANDLER( ERM_REMAINING_PLAY_TIME_NOT, float );
EVENT_HANDLER_NOPARAM( ERM_PLAY_TIME_OUT_NOT );

EVENT_HANDLER( EGS_MY_USER_UNIT_INFO_TO_SERVER_REQ ); 
_EVENT_HANDLER( ERM_MY_USER_UNIT_INFO_TO_SERVER_ACK, KPacketOK );

EVENT_HANDLER( EGS_NPC_UNIT_CREATE_REQ );
_EVENT_HANDLER( ERM_NPC_UNIT_CREATE_ACK, KPacketOK );
_EVENT_HANDLER( ERM_NPC_UNIT_CREATE_NOT, KEGS_NPC_UNIT_CREATE_NOT );

EVENT_HANDLER( EGS_NPC_UNIT_DIE_REQ );
EVENT_HANDLER( ERM_NPC_UNIT_DIE_ACK );
EVENT_HANDLER( ERM_NPC_UNIT_DIE_NOT );
//{{ 2012. 11. 12	최육사	배틀필드 시스템
#ifdef SERV_BATTLE_FIELD_SYSTEM
_EVENT_HANDLER( ERM_BATTLE_FIELD_NPC_UNIT_DIE_NOT, KERM_NPC_UNIT_DIE_NOT );
#endif SERV_BATTLE_FIELD_SYSTEM
//}}

_EVENT_HANDLER( ERM_DROP_ITEM_NOT, KEGS_DROP_ITEM_NOT );
EVENT_HANDLER( EGS_GET_ITEM_REQ );
_EVENT_HANDLER( ERM_GET_ITEM_ACK, KEGS_GET_ITEM_ACK );
_EVENT_HANDLER( ERM_GET_ITEM_NOT, KEGS_GET_ITEM_NOT );

//{{ 2009. 5. 11  최육사		실시간아이템
_EVENT_HANDLER( ERM_GET_ITEM_INSERT_TO_INVENTORY_NOT, KEGS_GET_ITEM_NOT );
EVENT_HANDLER( DBE_GET_ITEM_INSERT_TO_INVENTORY_ACK );
EVENT_HANDLER( EGS_GET_TEMP_ITEM_REQ );
EVENT_HANDLER( DBE_GET_TEMP_ITEM_ACK );
EVENT_HANDLER( EGS_DELETE_TEMP_ITEM_REQ );
//}}

EVENT_HANDLER_NOPARAM( EGS_REFRESH_ROOM_REQ );
_EVENT_HANDLER( ERM_REFRESH_ROOM_ACK, KEGS_REFRESH_ROOM_ACK );

EVENT_HANDLER( ERM_CHECK_INVALID_ZOMBIE_USER_NOT );
_EVENT_HANDLER( ERM_CHECK_INVALID_ROOM_NOT, UidType );

//{{ 2012. 10. 17	최육사		P2P & Relay 정보 수집
#ifdef SERV_COLLECTION_OF_RELAY_AND_P2P_INFO
EVENT_HANDLER( EGS_RESULT_SUCCESS_REQ );
#else
EVENT_HANDLER_NOPARAM( EGS_RESULT_SUCCESS_REQ );
#endif SERV_COLLECTION_OF_RELAY_AND_P2P_INFO
//}}
_EVENT_HANDLER( ERM_RESULT_SUCCESS_ACK, KEGS_RESULT_SUCCESS_ACK );
_EVENT_HANDLER( ERM_RESULT_ALL_UNIT_SUCCESS_NOT, KEGS_RESULT_ALL_UNIT_SUCCESS_NOT );

EVENT_HANDLER( EGS_SQUARE_LIST_REQ );

EVENT_HANDLER( EGS_JOIN_SQUARE_REQ );
_EVENT_HANDLER( ERM_JOIN_SQUARE_ACK, KEGS_JOIN_SQUARE_ACK );
_EVENT_HANDLER( ERM_JOIN_SQUARE_NOT, KEGS_JOIN_SQUARE_NOT );

EVENT_HANDLER( EGS_LEAVE_SQUARE_REQ );
_EVENT_HANDLER( ERM_LEAVE_SQUARE_ACK, KEGS_LEAVE_SQUARE_ACK );
_EVENT_HANDLER( ERM_LEAVE_SQUARE_NOT, KEGS_LEAVE_SQUARE_NOT );

EVENT_HANDLER( EGS_SQUARE_UNIT_SYNC_DATA_REQ );
_EVENT_HANDLER( ERM_SQUARE_UNIT_SYNC_DATA_NOT, KEGS_SQUARE_UNIT_SYNC_DATA_NOT );

EVENT_HANDLER( EGS_CREATE_TC_ROOM_REQ );
_EVENT_HANDLER( ERM_OPEN_TC_ROOM_ACK, KEGS_CREATE_TC_ROOM_ACK );

EVENT_HANDLER( EGS_END_TC_GAME_REQ );
EVENT_HANDLER( ERM_END_TC_GAME_ACK );

EVENT_HANDLER( EGS_SET_TC_REMAINING_TIME_REQ );
_EVENT_HANDLER( ERM_SET_TC_REMAINING_TIME_ACK, KEGS_SET_TC_REMAINING_TIME_ACK );

_EVENT_HANDLER( ERM_LEAVE_TC_ROOM_ACK, KEGS_LEAVE_TC_ROOM_ACK );

EVENT_HANDLER( EGS_ADD_ON_STAT_REQ );
_EVENT_HANDLER( ERM_ADD_ON_STAT_ACK, KEGS_ADD_ON_STAT_ACK );
_EVENT_HANDLER( ERM_ADD_ON_STAT_NOT, KEGS_ADD_ON_STAT_NOT );

//{{ 2009. 5. 21  최육사		내구도 소모 개편
EVENT_HANDLER( ERM_ZERO_ENDURANCE_ITEM_IN_ROOM_NOT );
//}}

//{{ 2009. 9. 23  최육사	1차전직캐쉬템
_EVENT_HANDLER( ERM_CHANGE_ROOM_USER_INFO_NOT, KRoomUserInfo );
_EVENT_HANDLER( ERM_CHANGE_SQUARE_USER_INFO_NOT, KSquareUserInfo );
//}}

//{{ 2011. 03. 26  김민성	청 1차 추가 스킬 추가 - 버프
#ifdef SERV_ADD_BUFF_SKILL_INFO
EVENT_HANDLER( EGS_BUFF_SKILL_INFO_CONVEY_REQ );
_EVENT_HANDLER( ERM_BUFF_SKILL_INFO_CONVEY_ACK, KEGS_BUFF_SKILL_INFO_CONVEY_ACK );
_EVENT_HANDLER( ERM_BUFF_SKILL_INFO_CONVEY_NOT, KEGS_BUFF_SKILL_INFO_CONVEY_NOT );
#endif SERV_ADD_BUFF_SKILL_INFO
//}}

//{{ 2011. 04. 13  김민성  글로벌 서버 추가
#ifdef SERV_INSERT_GLOBAL_SERVER
_EVENT_HANDLER( ERM_CREATE_ATTRIB_NPC_NOT, KEGS_CREATE_ATTRIB_NPC_NOT );
#endif SERV_INSERT_GLOBAL_SERVER
//}} 2011. 04. 13  김민성  글로벌 서버 추가

//{{ 버프 관리 시스템 - 김민성
#ifdef SERV_SERVER_BUFF_SYSTEM
EVENT_HANDLER( ERM_ACTIVATE_BUFF_NOT );
EVENT_HANDLER( ECN_PARTY_BUFF_UPDATE_NOT );
#endif SERV_SERVER_BUFF_SYSTEM
//}}

//{{ 2012. 04. 17	박세훈	어둠의 문 개편
#ifdef SERV_REFORM_THE_GATE_OF_DARKNESS
_EVENT_HANDLER( ERM_UPDATE_BUFF_INFO_IN_ROOM_NOT, KEGS_UPDATE_BUFF_INFO_IN_ROOM_NOT );
#endif SERV_REFORM_THE_GATE_OF_DARKNESS
//}}

//{{ 2013. 03. 12	최육사	몬스터 유효 검사
#ifdef SERV_CHECK_EXIST_MONSTER_UID
EVENT_HANDLER( EGS_CHECK_EXIST_MONSTER_UID_REQ );
_EVENT_HANDLER( ERM_CHECK_EXIST_MONSTER_UID_ACK, KEGS_CHECK_EXIST_MONSTER_UID_ACK );
#endif SERV_CHECK_EXIST_MONSTER_UID
//}}

//{{ 핑 상태체크 호스트 변경 - 김민성
#ifdef SERV_CHOOSE_FASTEST_HOST
EVENT_HANDLER( EGS_UDP_PING_SCORE_NOT );
_EVENT_HANDLER( ERM_CHECK_PING_SCORE_CHANGE_HOST_NOT, KEGS_CHECK_PING_SCORE_CHANGE_HOST_NOT );
#endif SERV_CHOOSE_FASTEST_HOST
//}

#ifdef SERV_TIME_ENCHANT_EVENT// 작업날짜: 2013-05-30	// 박세훈
EVENT_HANDLER( EGB_TIME_ENCHANT_EVENT_DROP_NOT );
#endif // SERV_TIME_ENCHANT_EVENT

#ifdef SERV_CHANGE_UPDATE_BUFF_INFO_PROCESS// 작업날짜: 2013-06-08	// 박세훈
EVENT_HANDLER_NOPARAM( ERM_UPDATE_BUFF_INFO_NOT );
#endif // SERV_CHANGE_UPDATE_BUFF_INFO_PROCESS
