
#include "ServerDefine.h"

//////////////////////////////////////////////////////////////////////////
// for visual assist

#ifndef EVENT_HANDLER
#define EVENT_HANDLER( eventid )
#endif

#ifndef EVENT_HANDLER_NOPARAM
#define EVENT_HANDLER_NOPARAM( eventid )
#endif

#ifndef _EVENT_HANDLER
#define _EVENT_HANDLER( eventid, structtype )
#endif


//////////////////////////////////////////////////////////////////////////
//{{ 2011. 12. 05	최육사	배틀필드
#ifdef SERV_BATTLE_FIELD_SYSTEM
#else
//////////////////////////////////////////////////////////////////////////


//////////////////////////////////////////////////////////////////////////
// 여기서 부터 이벤트 핸들러 정의!


// Party
//EVENT_HANDLER( EGS_PARTY_LIST_REQ );
//
//EVENT_HANDLER( EGS_CREATE_PARTY_REQ );
//
//EVENT_HANDLER( EGS_JOIN_PARTY_REQ );
//EVENT_HANDLER( EGS_JOIN_PARTY_INVITE_REPLY_NOT );
//
//EVENT_HANDLER( EGS_LEAVE_PARTY_REQ );
//
//EVENT_HANDLER( EGS_INVITE_PARTY_REQ );
//EVENT_HANDLER( EGS_INVITE_PARTY_REPLY_NOT );
//
//EVENT_HANDLER( EGS_PARTY_CHANGE_READY_REQ );
//
//EVENT_HANDLER( EGS_PARTY_CHANGE_DUNGEON_REQ );
//
//EVENT_HANDLER( EGS_PARTY_GAME_START_REQ );
//EVENT_HANDLER( ERM_PARTY_OPEN_DUNGEON_ROOM_ACK );   
//_EVENT_HANDLER( ERM_PARTY_OPEN_DUNGEON_ROOM_NOT, KEGS_PARTY_GAME_START_NOT );
//
////{{ 2009. 2. 4  최육사	던전 리플레이
//_EVENT_HANDLER( ERM_PARTY_GAME_REPLAY_START_ACK, KERM_PARTY_OPEN_DUNGEON_ROOM_ACK );
//_EVENT_HANDLER( ERM_PARTY_GAME_REPLAY_START_NOT, KEGS_PARTY_GAME_START_NOT );
////}}
//
////{{ 2010. 12. 28	최육사	하멜 마을 추가
//#ifdef SERV_SHIP_DUNGEON
//EVENT_HANDLER( EGS_PARTY_TO_FIELD_MAP_REQ );
//#else
//EVENT_HANDLER_NOPARAM( EGS_PARTY_TO_FIELD_MAP_REQ );
//#endif SERV_SHIP_DUNGEON
////}}
//_EVENT_HANDLER( ERM_PARTY_TO_FIELD_MAP_ACK, KEGS_PARTY_TO_FIELD_MAP_ACK );
////{{ 2010. 12. 29	최육사	하멜 마을 추가
//#ifdef SERV_SHIP_DUNGEON
//_EVENT_HANDLER( ERM_PARTY_TO_FIELD_MAP_NOT, KEGS_PARTY_TO_FIELD_MAP_NOT );
//#else
//EVENT_HANDLER_NOPARAM( ERM_PARTY_TO_FIELD_MAP_NOT );
//#endif SERV_SHIP_DUNGEON
////}}
//
//EVENT_HANDLER( EGS_PARTY_CHANGE_NAME_REQ );		// 파티 이름변경	
//EVENT_HANDLER( EGS_PARTY_CHANGE_PUBLIC_REQ );	// 파티 공개설정 변경	
//EVENT_HANDLER( EGS_PARTY_CHANGE_HOST_REQ );		// 파티장 변경
//EVENT_HANDLER( EGS_PARTY_BAN_USER_REQ );			// 파티유저밴	
//EVENT_HANDLER( ERM_PARTY_BAN_USER_ACK );
//
//EVENT_HANDLER( EGS_PARTY_CHANGE_GET_ITEM_TYPE_REQ );
//EVENT_HANDLER( EGS_PARTY_CHANGE_NUM_OF_PER_REQ );
//
////{{ 2009. 4. 1  최육사		파티렙제
//EVENT_HANDLER( EGS_PARTY_LIMIT_LEVEL_REQ );
////}}
//
////{{ 2009. 5. 1  최육사		파티 퀵조인
//EVENT_HANDLER( EGS_PARTY_QUICK_JOIN_REQ );
////}}
//
////////////////////////////////////////////////////////////////////////////
////{{ 2010. 02. 17  최육사	채널 파티 통합
//#ifdef SERV_CHANNEL_PARTY
//
//EVENT_HANDLER( EPM_CREATE_PARTY_ACK );
//EVENT_HANDLER( EPM_JOIN_PARTY_ACK );
//_EVENT_HANDLER( EPM_JOIN_PARTY_NOT, KEGS_JOIN_PARTY_NOT );
//
//_EVENT_HANDLER( EPM_JOIN_PARTY_INVITE_NOT, KEGS_JOIN_PARTY_INVITE_NOT );
//_EVENT_HANDLER( EPM_JOIN_PARTY_INVITE_DENY_NOT, KEGS_JOIN_PARTY_INVITE_DENY_NOT );
//_EVENT_HANDLER( EPM_INVITE_PARTY_DENY_NOT, KEGS_INVITE_PARTY_DENY_NOT );
//
////{{ 2010. 03. 12  최육사	채널 통합 파티 버그 수정
//EVENT_HANDLER( EPM_CHECK_JOIN_PARTY_USER_REQ );
////}}
//
//EVENT_HANDLER( EPM_LEAVE_PARTY_ACK );
//_EVENT_HANDLER( EPM_LEAVE_PARTY_NOT, KEGS_LEAVE_PARTY_NOT );
//
//_EVENT_HANDLER( EPM_INVITE_PARTY_ACK, KEGS_INVITE_PARTY_ACK );
//_EVENT_HANDLER( EPM_INVITE_PARTY_NOT, KEGS_INVITE_PARTY_NOT );
//
//_EVENT_HANDLER( EPM_UPDATE_PARTY_USER_INFO_BROAD_NOT, KEGS_UPDATE_PARTY_USER_INFO_NOT );
//
//_EVENT_HANDLER( EPM_PARTY_CHANGE_READY_ACK, KEGS_PARTY_CHANGE_READY_ACK );
//_EVENT_HANDLER( EPM_PARTY_CHANGE_READY_NOT, KEGS_PARTY_CHANGE_READY_NOT );
//
//_EVENT_HANDLER( EPM_PARTY_CHANGE_DUNGEON_ACK, KEGS_PARTY_CHANGE_DUNGEON_ACK );
//_EVENT_HANDLER( EPM_PARTY_CHANGE_DUNGEON_NOT, KEGS_PARTY_CHANGE_DUNGEON_NOT );
//
//_EVENT_HANDLER( EPM_PARTY_GAME_START_ACK, KEGS_PARTY_GAME_START_ACK );
//EVENT_HANDLER( EPM_CHECK_FOR_PARTY_GAME_START_REQ );
//_EVENT_HANDLER( EPM_PARTY_OPEN_DUNGEON_ROOM_NOT, KERM_PARTY_OPEN_DUNGEON_ROOM_REQ );
//_EVENT_HANDLER( EPM_PARTY_GAME_REPLAY_START_NOT, KERM_PARTY_OPEN_DUNGEON_ROOM_REQ );
//
//_EVENT_HANDLER( EPM_PARTY_TO_FIELD_MAP_ACK, KEGS_PARTY_TO_FIELD_MAP_ACK );
//
//_EVENT_HANDLER( EPM_PARTY_CHANGE_NAME_ACK, KEGS_PARTY_CHANGE_NAME_ACK );
//_EVENT_HANDLER( EPM_PARTY_CHANGE_NAME_NOT, KEGS_PARTY_CHANGE_NAME_NOT );
//
//_EVENT_HANDLER( EPM_PARTY_CHANGE_PUBLIC_ACK, KEGS_PARTY_CHANGE_PUBLIC_ACK );
//_EVENT_HANDLER( EPM_PARTY_CHANGE_PUBLIC_NOT, KEGS_PARTY_CHANGE_PUBLIC_NOT );
//
//EVENT_HANDLER( EPM_CHECK_PARTY_CHANGE_HOST_REQ );
//_EVENT_HANDLER( EPM_PARTY_CHANGE_HOST_ACK, KEGS_PARTY_CHANGE_HOST_ACK );
//_EVENT_HANDLER( EPM_PARTY_CHANGE_HOST_NOT, KEGS_PARTY_CHANGE_HOST_NOT );
//
//_EVENT_HANDLER( EPM_PARTY_CHANGE_NUM_OF_PER_ACK, KEGS_PARTY_CHANGE_NUM_OF_PER_ACK );
//_EVENT_HANDLER( EPM_PARTY_CHANGE_NUM_OF_PER_NOT, KEGS_PARTY_CHANGE_NUM_OF_PER_NOT );
//
//_EVENT_HANDLER( EPM_PARTY_CHANGE_GET_ITEM_TYPE_ACK, KEGS_PARTY_CHANGE_GET_ITEM_TYPE_ACK );
//_EVENT_HANDLER( EPM_PARTY_CHANGE_GET_ITEM_TYPE_NOT, KEGS_PARTY_CHANGE_GET_ITEM_TYPE_NOT );
//
//_EVENT_HANDLER( EPM_PARTY_BAN_USER_ACK, KEGS_PARTY_BAN_USER_ACK );
//EVENT_HANDLER( EPM_PARTY_BAN_USER_NOT );
//
//_EVENT_HANDLER( EPM_PARTY_QUICK_JOIN_ACK, KEGS_PARTY_QUICK_JOIN_ACK );
//_EVENT_HANDLER( EPM_DUNGEON_SECRET_STAGE_ENTER_CHECK_ACK, KEGS_DUNGEON_SECRET_STAGE_ENTER_CHECK_ACK );
//
//_EVENT_HANDLER( EPM_CHAT_ACK, KEGS_CHAT_ACK );
//_EVENT_HANDLER( EPM_CHAT_NOT, KEGS_CHAT_NOT );
//
//_EVENT_HANDLER( EPM_CHANGE_PARTY_FEVER_STATE_NOT, KEGS_CHANGE_PARTY_FEVER_STATE_NOT );
//_EVENT_HANDLER( EPM_PARTY_FEVER_POINT_NOT, KEGS_PARTY_FEVER_POINT_NOT );
//
//EVENT_HANDLER( EPM_SEND_UPDATE_PARTY_MEMBER_LIST_NOT );   
//EVENT_HANDLER( EPM_PARTY_TALKBOX_INFO_UPDATE_NOT );
//
//EVENT_HANDLER_NOPARAM( EPM_QUICK_SLOT_COOL_TIME_RESET_NOT );
//
////{{ 2011. 03. 21  김민성	던전 난이도 보정
//#ifdef SERV_DUNGEON_DIFFICULTY_REVISION
//EVENT_HANDLER( EGS_PARTY_CHANGE_CHECK_MIN_LEVEL_REQ );
//EVENT_HANDLER( EPM_PARTY_CHANGE_CHECK_MIN_LEVEL_ACK );
//EVENT_HANDLER( EPM_PARTY_CHANGE_CHECK_MIN_LEVEL_NOT );
//#endif SERV_DUNGEON_DIFFICULTY_REVISION
////}}
//
////{{ 2011. 05. 27    김민성    휴면 복귀 유저 보상
//#ifdef SERV_COME_BACK_USER_REWARD
//EVENT_HANDLER( EPM_CHANGE_COME_BACK_BUFF_NOT );
//#endif SERV_COME_BACK_USER_REWARD
////}} 
//
//#endif SERV_CHANNEL_PARTY
////}}
////////////////////////////////////////////////////////////////////////////


//////////////////////////////////////////////////////////////////////////
#endif SERV_BATTLE_FIELD_SYSTEM
//////////////////////////////////////////////////////////////////////////
//}}