
#include "ServerDefine.h"

//////////////////////////////////////////////////////////////////////////
// for visual assist

#ifndef EVENT_HANDLER
#define EVENT_HANDLER( eventid )
#endif

#ifndef EVENT_HANDLER_NOPARAM
#define EVENT_HANDLER_NOPARAM( eventid )
#endif

#ifndef _EVENT_HANDLER
#define _EVENT_HANDLER( eventid, structtype )
#endif


//////////////////////////////////////////////////////////////////////////
// 여기서 부터 이벤트 핸들러 정의!


EVENT_HANDLER_NOPARAM( EGS_CREATE_PERSONAL_SHOP_REQ );
EVENT_HANDLER( ERM_CHECK_OPEN_PERSONAL_SHOP_ACK );
EVENT_HANDLER( ERM_OPEN_PERSONAL_SHOP_ACK );
EVENT_HANDLER( EGS_REG_PERSONAL_SHOP_ITEM_REQ );
EVENT_HANDLER( ERM_REG_PERSONAL_SHOP_ITEM_ACK );
EVENT_HANDLER( EGS_JOIN_PERSONAL_SHOP_REQ );
EVENT_HANDLER( ERM_CHECK_JOIN_PERSONAL_SHOP_ACK );
EVENT_HANDLER( ERM_JOIN_PERSONAL_SHOP_ACK );
EVENT_HANDLER( EGS_BREAK_PERSONAL_SHOP_REQ );
_EVENT_HANDLER( ERM_BREAK_PERSONAL_SHOP_ACK, KEGS_BREAK_PERSONAL_SHOP_ACK );
EVENT_HANDLER( ERM_BREAK_PERSONAL_SHOP_NOT );

EVENT_HANDLER_NOPARAM( EGS_LEAVE_PERSONAL_SHOP_REQ );
_EVENT_HANDLER( ERM_LEAVE_PERSONAL_SHOP_ACK, KEGS_LEAVE_PERSONAL_SHOP_ACK );

EVENT_HANDLER( EGS_BUY_PERSONAL_SHOP_ITEM_REQ );
_EVENT_HANDLER( ERM_BUY_PERSONAL_SHOP_ITEM_ACK, KEGS_BUY_PERSONAL_SHOP_ITEM_ACK );

_EVENT_HANDLER( ERM_UPDATE_SQUARE_PERSONAL_SHOP_INFO_NOT, KEGS_UPDATE_SQUARE_PERSONAL_SHOP_INFO_NOT );
EVENT_HANDLER( ERM_CONFIRM_BUY_PERSONAL_SHOP_ITEM_REQ );
_EVENT_HANDLER( ERM_UPDATE_PERSONAL_SHOP_ITEM_INFO_NOT, KEGS_UPDATE_PERSONAL_SHOP_ITEM_INFO_NOT );
//{{ 2012. 05. 29	김민성       개인 상점 거래 로직 변경
#ifdef SERV_TRADE_LOGIC_CHANGE_PERSONAL_SHOP
_EVENT_HANDLER( ERM_BUY_PERSONAL_SHOP_ITEM_COMPLETE_NOT, KDBE_BUY_PERSONAL_SHOP_ITEM_COMPLETE_REQ );
#else
EVENT_HANDLER( ERM_BUY_PERSONAL_SHOP_ITEM_COMPLETE_NOT );
#endif SERV_TRADE_LOGIC_CHANGE_PERSONAL_SHOP
//}}
EVENT_HANDLER( DBE_INSERT_BUY_PERSONAL_SHOP_ITEM_ACK );

#ifdef DEF_TRADE_BOARD
EVENT_HANDLER( EGS_SEARCH_TRADE_BOARD_REQ );
#endif DEF_TRADE_BOARD

//////////////////////////////////////////////////////////////////////////
//{{ 2011. 04. 11	최육사	대리 상인
#ifdef SERV_PSHOP_AGENCY

EVENT_HANDLER( DBE_INSERT_PERIOD_PSHOP_AGENCY_ACK );										// 대리상인 캐쉬템 구매결과
EVENT_HANDLER( ERM_CHECK_MY_PSHOP_AGENCY_INFO_ACK );										// 대리상점 PShopAgencyUID얻기 결과

EVENT_HANDLER_NOPARAM( EGS_CREATE_PSHOP_AGENCY_REQ );										// 대리상인 개설
_EVENT_HANDLER( ERM_OPEN_PSHOP_AGENCY_ACK, KERM_OPEN_PERSONAL_SHOP_ACK );					// 대리상인 개설 응답

EVENT_HANDLER( ERM_CHECK_OPEN_PSHOP_AGENCY_ACK );											// 대리상인 정보 체크

EVENT_HANDLER( EGS_REG_PSHOP_AGENCY_ITEM_REQ );												// 대리상인 물품 등록
//{{ 2012. 05. 31	김민성       대리 상점 거래 로직 변경
#ifdef SERV_TRADE_LOGIC_CHANGE_AGENCY_SHOP
_EVENT_HANDLER( ERM_CHECK_FOR_REG_PSHOP_AGENCY_ITEM_ACK, KEGS_REG_PSHOP_AGENCY_ITEM_ACK );
#endif SERV_TRADE_LOGIC_CHANGE_AGENCY_SHOP
//}}
EVENT_HANDLER( DBE_PREPARE_REG_PSHOP_AGENCY_ITEM_ACK );										// 대리상인 물품 등록 DB처리
_EVENT_HANDLER( ERM_REG_PSHOP_AGENCY_ITEM_ACK, KERM_REG_PERSONAL_SHOP_ITEM_ACK );			// 대리상인 물품 등록 결과

EVENT_HANDLER( EGS_JOIN_MY_PSHOP_AGENCY_REQ );												// 대리상인 개설자 입장
_EVENT_HANDLER( ERM_JOIN_MY_PSHOP_AGENCY_ACK, KEGS_JOIN_MY_PSHOP_AGENCY_ACK );				// 대리상인 개설자 입장 결과

EVENT_HANDLER_NOPARAM( EGS_LEAVE_PSHOP_AGENCY_REQ );										// 대리상인 이탈 요청
_EVENT_HANDLER( ERM_LEAVE_PSHOP_AGENCY_ACK, KEGS_LEAVE_PSHOP_AGENCY_ACK );					// 대리상인 이탈 결과
EVENT_HANDLER( ERM_BREAK_PSHOP_AGENCY_NOT );												// 대리상인 종료 통보

_EVENT_HANDLER( ELG_PSHOP_AGENCY_MESSAGE_NOT, KEGS_PSHOP_AGENCY_MESSAGE_NOT );				// 대리상인 메시지

_EVENT_HANDLER( ERM_BUY_PSHOP_AGENCY_ITEM_COMPLETE_NOT, KERM_BUY_PERSONAL_SHOP_ITEM_COMPLETE_NOT ); // 대리상점에서 구매한 결과

EVENT_HANDLER_NOPARAM( EGS_STOP_SALE_PSHOP_AGENCY_REQ );									// 대리상인 판매 중지
_EVENT_HANDLER( ERM_STOP_SALE_PSHOP_AGENCY_ACK, KEGS_STOP_SALE_PSHOP_AGENCY_ACK );			// 대리상인 판매 중지 결과

EVENT_HANDLER( EGS_PICK_UP_FROM_PSHOP_AGENCY_REQ );											// 대리상인 물품 가져오기
EVENT_HANDLER( ERM_PREPARE_PICK_UP_FROM_PSHOP_AGENCY_REQ );									// 대리상인 물품 가져오기 준비
EVENT_HANDLER( ERM_PICK_UP_FROM_PSHOP_AGENCY_ACK );											// 대리상인 물품 가져오기 결과
EVENT_HANDLER( DBE_INSERT_TO_INVENTORY_PICK_UP_FROM_PSHOP_AGENCY_ACK );						// 대리상인 물품 가져오기 종료

#endif SERV_PSHOP_AGENCY
//}}
//////////////////////////////////////////////////////////////////////////

//{{ 2011. 05. 13	최육사	대리 상인 좀비 유저 버그 해결
#ifdef SERV_PSHOP_AGENCY_ZOMBIE_USER_BUG_FIX
EVENT_HANDLER( ERM_CHECK_ZOMBIE_USER_REQ );
#endif SERV_PSHOP_AGENCY_ZOMBIE_USER_BUG_FIX
//}}


