
#include "ServerDefine.h"

//////////////////////////////////////////////////////////////////////////
// for visual assist

#ifndef EVENT_HANDLER
#define EVENT_HANDLER( eventid )
#endif

#ifndef EVENT_HANDLER_NOPARAM
#define EVENT_HANDLER_NOPARAM( eventid )
#endif

#ifndef _EVENT_HANDLER
#define _EVENT_HANDLER( eventid, structtype )
#endif


//////////////////////////////////////////////////////////////////////////
// 여기서 부터 이벤트 핸들러 정의!


EVENT_HANDLER( EGS_DUNGEON_PLAY_INFO_TO_SERVER_NOT );

EVENT_HANDLER( EGS_DUNGEON_STAGE_LOAD_REQ );
_EVENT_HANDLER( ERM_DUNGEON_STAGE_LOAD_ACK, KEGS_DUNGEON_STAGE_LOAD_ACK );
_EVENT_HANDLER( ERM_DUNGEON_STAGE_LOAD_NOT, KEGS_DUNGEON_STAGE_LOAD_NOT );

EVENT_HANDLER( EGS_DUNGEON_STAGE_LOAD_COMPLETE_REQ );
_EVENT_HANDLER( ERM_DUNGEON_STAGE_LOAD_COMPLETE_ACK, KPacketOK );
_EVENT_HANDLER( ERM_DUNGEON_STAGE_LOAD_COMPLETE_NOT, KEGS_DUNGEON_STAGE_LOAD_COMPLETE_NOT );

_EVENT_HANDLER( ERM_DUNGEON_STAGE_START_NOT, KEGS_DUNGEON_STAGE_START_NOT );

EVENT_HANDLER( EGS_DUNGEON_SUB_STAGE_OPEN_REQ );
_EVENT_HANDLER( ERM_DUNGEON_SUB_STAGE_OPEN_ACK, KEGS_DUNGEON_SUB_STAGE_OPEN_ACK );
_EVENT_HANDLER( ERM_DUNGEON_SUB_STAGE_OPEN_NOT, KEGS_DUNGEON_SUB_STAGE_OPEN_NOT );

EVENT_HANDLER( EGS_DUNGEON_SUB_STAGE_GO_NEXT_REQ );
_EVENT_HANDLER( ERM_DUNGEON_SUB_STAGE_GO_NEXT_ACK, KEGS_DUNGEON_SUB_STAGE_GO_NEXT_ACK );
_EVENT_HANDLER( ERM_DUNGEON_SUB_STAGE_GO_NEXT_ALL_NOT, KEGS_DUNGEON_SUB_STAGE_GO_NEXT_ALL_NOT );

EVENT_HANDLER( EGS_DUNGEON_SUB_STAGE_LOAD_COMPLETE_REQ );
_EVENT_HANDLER( ERM_DUNGEON_SUB_STAGE_LOAD_COMPLETE_ACK, KEGS_DUNGEON_SUB_STAGE_LOAD_COMPLETE_ACK );

_EVENT_HANDLER( ERM_DUNGEON_SUB_STAGE_START_NOT, KEGS_DUNGEON_SUB_STAGE_START_NOT );

//{{ 2009. 7. 20  최육사	비밀스테이지
EVENT_HANDLER_NOPARAM( EGS_DUNGEON_SECRET_STAGE_ENTER_CHECK_REQ );
_EVENT_HANDLER( ERM_DUNGEON_SECRET_STAGE_ENTER_CHECK_ACK, KEGS_DUNGEON_SECRET_STAGE_ENTER_CHECK_ACK );

#ifdef SERV_STAGE_CLEAR_IN_SERVER
_EVENT_HANDLER( ERM_DUNGEON_SECRET_STAGE_ENTER_CHECK_NOT, KEGS_DUNGEON_SECRET_STAGE_ENTER_CHECK_NOT );
#else SERV_STAGE_CLEAR_IN_SERVER
EVENT_HANDLER_NOPARAM( ERM_DUNGEON_SECRET_STAGE_ENTER_CHECK_NOT );
#endif SERV_STAGE_CLEAR_IN_SERVER

EVENT_HANDLER( EGS_DUNGEON_SECRET_STAGE_ENTER_SELECT_NOT );
_EVENT_HANDLER( ERM_DUNGEON_SECRET_STAGE_ENTER_RESULT_NOT, KEGS_DUNGEON_SECRET_STAGE_ENTER_RESULT_NOT );
//}}

_EVENT_HANDLER( ERM_END_GAME_DUNGEON_RESULT_DATA_NOT, KEGS_END_GAME_DUNGEON_RESULT_DATA_NOT );

EVENT_HANDLER( ERM_UPDATE_DUNGEON_UNIT_INFO_NOT );	

EVENT_HANDLER( EGS_RESURRECT_TO_CONTINUE_DUNGEON_REQ );
EVENT_HANDLER( EGS_RESURRECT_TO_CONTINUE_DUNGEON_ACK );
EVENT_HANDLER( EGS_RESURRECT_TO_CONTINUE_DUNGEON_NOT );

// 실시간 부활석
EVENT_HANDLER( EGS_STOP_DUNGEON_CONTINUE_TIME_REQ );
_EVENT_HANDLER( ERM_STOP_DUNGEON_CONTINUE_TIME_ACK, KEGS_STOP_DUNGEON_CONTINUE_TIME_ACK );
EVENT_HANDLER_NOPARAM( EGS_SKIP_CONTINUE_DUNGEON_NOT );

//{{ 2010. 07. 01  최육사	내구도 개편
EVENT_HANDLER( ERM_DECREASE_ENDURANCE_DUNGEON_NOT );
//}}

//{{ 2010. 05. 06  최육사	비밀던전 헬모드
#ifdef SERV_SECRET_HELL
_EVENT_HANDLER( ERM_DUNGEON_EFFECT_REMAINING_TIME_NOT, KEGS_DUNGEON_EFFECT_REMAINING_TIME_NOT );
_EVENT_HANDLER( ERM_DUNGEON_EFFECT_TIME_OUT_NOT, KEGS_DUNGEON_EFFECT_TIME_OUT_NOT );
#endif SERV_SECRET_HELL
//}}

EVENT_HANDLER( ERM_DUNGEON_USER_STATISTICS_NOT );
EVENT_HANDLER( ERM_TC_USER_STATISTICS_NOT );

//{{ 2011. 01. 25  김민성  월드 트리거 전달(던전만 적용중 - 이후 PVP 확장)
#ifdef SERV_WORLD_TRIGGER_RELOCATION
EVENT_HANDLER( EGS_WORLD_TRIGGER_RELOCATION_REQ );
_EVENT_HANDLER( ECN_WORLD_TRIGGER_RELOCATION_ACK, KEGS_WORLD_TRIGGER_RELOCATION_ACK );
_EVENT_HANDLER( ECN_WORLD_TRIGGER_RELOCATION_NOT, KEGS_WORLD_TRIGGER_RELOCATION_NOT );
#endif SERV_WORLD_TRIGGER_RELOCATION
//}}
//{{ 2013. 01. 09 던전 강퇴 시스템 - 김민성
#ifdef SERV_DUNGEON_FORCED_EXIT_SYSTEM
EVENT_HANDLER( EGS_BAD_ATTITUDE_USER_CHECK_INFO_NOT );
_EVENT_HANDLER( ERM_BAD_ATTITUDE_USER_MSG_NOT, KEGS_BAD_ATTITUDE_USER_MSG_NOT );
_EVENT_HANDLER( ERM_BAD_ATTITUDE_USER_NOT, KEGS_BAD_ATTITUDE_USER_NOT );
EVENT_HANDLER( EGS_FORCED_EXIT_VOTE_REQ );
EVENT_HANDLER( EGS_DEFENCE_DUNGEON_WAVE_ID_NOT );
_EVENT_HANDLER( ERM_FORCED_EXIT_VOTE_ACK, KEGS_FORCED_EXIT_VOTE_ACK );
EVENT_HANDLER( ERM_BAD_ATTITUDE_USER_LOG_NOT );
#endif SERV_DUNGEON_FORCED_EXIT_SYSTEM
//}
//{{ 2013. 04. 09	최육사	어둠의 문 개편
#ifdef SERV_NEW_DEFENCE_DUNGEON
EVENT_HANDLER( ERM_PREPARE_FOR_DEFENCE_DUNGEON_REQ );
_EVENT_HANDLER( ERM_DECISION_ENTER_DEFENCE_DUNGEON_NOT, KEGS_DECISION_ENTER_DEFENCE_DUNGEON_NOT );
_EVENT_HANDLER( ERM_DEFENCE_DUNGEON_GAME_START_NOT, KEGS_DEFENCE_DUNGEON_GAME_START_NOT );
_EVENT_HANDLER( ERM_CHANGE_GAME_STAT_INFO_IN_ROOM_NOT, KEGS_CHANGE_GAME_STAT_INFO_IN_ROOM_NOT );
EVENT_HANDLER( ERM_CHANGE_DEFENCE_DUNGEON_PHASE_NOT );
#endif SERV_NEW_DEFENCE_DUNGEON
//}}
//{{ 2013. 04. 22	최육사	어둠의 문 입장 로직 변경
#ifdef SERV_NEW_DEFENCE_DUNGEON_ENTER_LOGIC
EVENT_HANDLER( EGS_ENTER_DEFENCE_DUNGEON_POPUP_REPLY_NOT );
EVENT_HANDLER_NOPARAM( ERM_LEAVE_ROOM_BEFORE_DEFENCE_DUNGEON_START_NOT );
#endif SERV_NEW_DEFENCE_DUNGEON_ENTER_LOGIC
//}}
//{{ 2013. 02. 01  이벤트 발렌타인 던전 - 김민성
#ifdef SERV_EVENT_VALENTINE_DUNGEON
EVENT_HANDLER_NOPARAM( EGS_SYNC_DUNGEON_TIMER_NOT );
_EVENT_HANDLER( ERM_SYNC_DUNGEON_TIMER_NOT, KEGS_SYNC_DUNGEON_TIMER_NOT );
#endif SERV_EVENT_VALENTINE_DUNGEON
//}

#ifdef SERV_STAGE_CLEAR_IN_SERVER
EVENT_HANDLER( EGS_DUNGEON_SUB_STAGE_CLEAR_REQ )
_EVENT_HANDLER( ERM_DUNGEON_SUB_STAGE_CLEAR_ACK, KEGS_DUNGEON_SUB_STAGE_CLEAR_ACK )
EVENT_HANDLER( EGS_SECRET_STAGE_LOAD_REQ )
_EVENT_HANDLER( ERM_SECRET_STAGE_LOAD_ACK, KEGS_DUNGEON_STAGE_LOAD_REQ )
#endif SERV_STAGE_CLEAR_IN_SERVER