
#include "ServerDefine.h"

//////////////////////////////////////////////////////////////////////////
// for visual assist

#ifndef EVENT_HANDLER
#define EVENT_HANDLER( eventid )
#endif

#ifndef EVENT_HANDLER_NOPARAM
#define EVENT_HANDLER_NOPARAM( eventid )
#endif

#ifndef _EVENT_HANDLER
#define _EVENT_HANDLER( eventid, structtype )
#endif


//////////////////////////////////////////////////////////////////////////
// 여기서 부터 이벤트 핸들러 정의!

// Party
EVENT_HANDLER( EGS_INVITE_PARTY_REQ );
_EVENT_HANDLER( EPM_INVITE_PARTY_ACK, KEGS_INVITE_PARTY_ACK );
_EVENT_HANDLER( EPM_INVITE_PARTY_NOT, KEGS_INVITE_PARTY_NOT );

_EVENT_HANDLER( ELG_INVITE_PARTY_GET_RECEIVER_USER_INFO_REQ, KELG_INVITE_PARTY_FIND_RECEIVER_REQ );
_EVENT_HANDLER( EGB_INVITE_PARTY_GET_RECEIVER_USER_INFO_REQ, KELG_INVITE_PARTY_FIND_RECEIVER_REQ );

EVENT_HANDLER( ELG_INVITE_PARTY_FIND_RECEIVER_ACK );
_EVENT_HANDLER( EGB_INVITE_PARTY_FIND_RECEIVER_ACK, KELG_INVITE_PARTY_FIND_RECEIVER_ACK );

EVENT_HANDLER( EGS_INVITE_PARTY_REPLY_NOT );
_EVENT_HANDLER( EPM_INVITE_PARTY_DENY_NOT, KEGS_INVITE_PARTY_DENY_NOT );
//{{ 2012. 10. 25	최육사	배틀필드 시스템
#ifdef SERV_BATTLE_FIELD_SYSTEM
EVENT_HANDLER_NOPARAM( EPM_LEAVE_CANDIDATE_PARTY_NOT );
#endif SERV_BATTLE_FIELD_SYSTEM
//}}

EVENT_HANDLER( EPM_CREATE_PARTY_BY_INVITE_ACK );
_EVENT_HANDLER( EPM_JOIN_PARTY_NOT, KEGS_JOIN_PARTY_NOT );
_EVENT_HANDLER( EPM_CLOSE_PARTY_NOT, KEGS_CLOSE_PARTY_NOT );

EVENT_HANDLER( EGS_LEAVE_PARTY_REQ );
EVENT_HANDLER( EPM_LEAVE_PARTY_ACK );
_EVENT_HANDLER( EPM_LEAVE_PARTY_NOT, KEGS_LEAVE_PARTY_NOT );

EVENT_HANDLER( EGS_PARTY_CHANGE_READY_REQ );

EVENT_HANDLER( EGS_PARTY_CHANGE_DUNGEON_REQ );


//////////////////////////////////////////////////////////////////////////
// 빠르게 던전 시작
EVENT_HANDLER( EGS_QUICK_START_DUNGEON_GAME_REQ );
EVENT_HANDLER( EPM_CHECK_DUNGEON_GAME_PLAY_CONDITION_REQ );
//{{ 2012. 12. 17	박세훈	수동 파티 시 던전 팝업 창 문구 오류 수정
#ifdef SERV_FIX_MANUAL_PARTY_DUNGEON_POPUP_BUG
_EVENT_HANDLER( EPM_PARTY_GAME_START_OPINION_CHECK_NOT, KEGS_PARTY_GAME_START_OPINION_CHECK_NOT );
#else
EVENT_HANDLER_NOPARAM( EPM_PARTY_GAME_START_OPINION_CHECK_NOT );
#endif SERV_FIX_MANUAL_PARTY_DUNGEON_POPUP_BUG
//}}
EVENT_HANDLER( EGS_PARTY_GAME_START_OPINION_CHECK_REPLY_NOT );
EVENT_HANDLER( ERM_SINGLE_OPEN_DUNGEON_ROOM_ACK );
_EVENT_HANDLER( ERM_LEAVE_BATTLE_FIELD_FOR_DUNGEON_GAME_START_ACK, KEGS_LEAVE_ROOM_ACK );
_EVENT_HANDLER( EPM_PARTY_GAME_START_FAILED_NOT, KEGS_PARTY_GAME_START_FAILED_NOT );

EVENT_HANDLER( ERM_PARTY_OPEN_DUNGEON_ROOM_ACK );   
EVENT_HANDLER( ERM_PARTY_OPEN_DUNGEON_ROOM_NOT );

//{{ 2009. 2. 4  최육사	던전 리플레이
//_EVENT_HANDLER( ERM_PARTY_GAME_REPLAY_START_ACK, KERM_PARTY_OPEN_DUNGEON_ROOM_ACK );
//_EVENT_HANDLER( ERM_PARTY_GAME_REPLAY_START_NOT, KEGS_PARTY_GAME_START_NOT );
//}}

EVENT_HANDLER( EGS_PARTY_CHANGE_HOST_REQ );		// 파티장 변경
EVENT_HANDLER( EGS_PARTY_BAN_USER_REQ );		// 파티유저밴	
EVENT_HANDLER( ERM_PARTY_BAN_USER_ACK );

EVENT_HANDLER( EGS_PARTY_CHANGE_GET_ITEM_TYPE_REQ );
EVENT_HANDLER( EGS_PARTY_CHANGE_NUM_OF_PER_REQ );

//{{ 2009. 4. 1  최육사		파티렙제
EVENT_HANDLER( EGS_PARTY_LIMIT_LEVEL_REQ );
//}}

_EVENT_HANDLER( EPM_UPDATE_PARTY_USER_INFO_BROAD_NOT, KEGS_UPDATE_PARTY_USER_INFO_NOT );

_EVENT_HANDLER( EPM_PARTY_CHANGE_READY_ACK, KEGS_PARTY_CHANGE_READY_ACK );
_EVENT_HANDLER( EPM_PARTY_CHANGE_READY_NOT, KEGS_PARTY_CHANGE_READY_NOT );

_EVENT_HANDLER( EPM_PARTY_CHANGE_DUNGEON_ACK, KEGS_PARTY_CHANGE_DUNGEON_ACK );
_EVENT_HANDLER( EPM_PARTY_CHANGE_DUNGEON_NOT, KEGS_PARTY_CHANGE_DUNGEON_NOT );

EVENT_HANDLER( EPM_PARTY_GAME_START_ACK );
EVENT_HANDLER( EPM_CHECK_FOR_PARTY_GAME_START_REQ );
_EVENT_HANDLER( EPM_PARTY_OPEN_DUNGEON_ROOM_NOT, KERM_PARTY_OPEN_DUNGEON_ROOM_REQ );
//_EVENT_HANDLER( EPM_PARTY_GAME_REPLAY_START_NOT, KERM_PARTY_OPEN_DUNGEON_ROOM_REQ );

EVENT_HANDLER( EPM_CHECK_PARTY_CHANGE_HOST_REQ );
_EVENT_HANDLER( EPM_PARTY_CHANGE_HOST_ACK, KEGS_PARTY_CHANGE_HOST_ACK );
_EVENT_HANDLER( EPM_PARTY_CHANGE_HOST_NOT, KEGS_PARTY_CHANGE_HOST_NOT );

_EVENT_HANDLER( EPM_PARTY_CHANGE_NUM_OF_PER_ACK, KEGS_PARTY_CHANGE_NUM_OF_PER_ACK );
_EVENT_HANDLER( EPM_PARTY_CHANGE_NUM_OF_PER_NOT, KEGS_PARTY_CHANGE_NUM_OF_PER_NOT );

_EVENT_HANDLER( EPM_PARTY_CHANGE_GET_ITEM_TYPE_ACK, KEGS_PARTY_CHANGE_GET_ITEM_TYPE_ACK );
_EVENT_HANDLER( EPM_PARTY_CHANGE_GET_ITEM_TYPE_NOT, KEGS_PARTY_CHANGE_GET_ITEM_TYPE_NOT );

_EVENT_HANDLER( EPM_PARTY_BAN_USER_ACK, KEGS_PARTY_BAN_USER_ACK );
EVENT_HANDLER( EPM_PARTY_BAN_USER_NOT );

_EVENT_HANDLER( EPM_DUNGEON_SECRET_STAGE_ENTER_CHECK_ACK, KEGS_DUNGEON_SECRET_STAGE_ENTER_CHECK_ACK );

_EVENT_HANDLER( EPM_CHAT_ACK, KEGS_CHAT_ACK );
_EVENT_HANDLER( EPM_CHAT_NOT, KEGS_CHAT_NOT );

_EVENT_HANDLER( EPM_CHANGE_PARTY_FEVER_STATE_NOT, KEGS_CHANGE_PARTY_FEVER_STATE_NOT );
_EVENT_HANDLER( EPM_PARTY_FEVER_POINT_NOT, KEGS_PARTY_FEVER_POINT_NOT );

EVENT_HANDLER( EPM_SEND_UPDATE_PARTY_MEMBER_LIST_NOT );

EVENT_HANDLER_NOPARAM( EPM_QUICK_SLOT_COOL_TIME_RESET_NOT );

//{{ 2011. 03. 21  김민성	던전 난이도 보정
#ifdef SERV_DUNGEON_DIFFICULTY_REVISION
EVENT_HANDLER( EGS_PARTY_CHANGE_CHECK_MIN_LEVEL_REQ );
EVENT_HANDLER( EPM_PARTY_CHANGE_CHECK_MIN_LEVEL_ACK );
EVENT_HANDLER( EPM_PARTY_CHANGE_CHECK_MIN_LEVEL_NOT );
#endif SERV_DUNGEON_DIFFICULTY_REVISION
//}}

//{{ 2011. 05. 27    김민성    휴면 복귀 유저 보상
#ifdef SERV_COME_BACK_USER_REWARD
EVENT_HANDLER( EPM_CHANGE_COME_BACK_BUFF_NOT );
#endif SERV_COME_BACK_USER_REWARD
//}} 

//{{ 2012. 05. 23	최육사	배틀필드 시스템
#ifdef SERV_BATTLE_FIELD_SYSTEM
_EVENT_HANDLER( ERM_GAME_START_TIME_COUNT_NOT, KEGS_GAME_START_TIME_COUNT_NOT );
#endif SERV_BATTLE_FIELD_SYSTEM
//}}


