
#include "ServerDefine.h"

//////////////////////////////////////////////////////////////////////////
// for visual assist

#ifndef EVENT_HANDLER
#define EVENT_HANDLER( eventid )
#endif

#ifndef EVENT_HANDLER_NOPARAM
#define EVENT_HANDLER_NOPARAM( eventid )
#endif

#ifndef _EVENT_HANDLER
#define _EVENT_HANDLER( eventid, structtype )
#endif


//////////////////////////////////////////////////////////////////////////
// 여기서 부터 이벤트 핸들러 정의!

//{{ 2009. 9. 18  최육사	길드
#ifdef GUILD_TEST

//{{ 2009. 11. 20  최육사	길드구조개선	
EVENT_HANDLER( EGS_CREATE_GUILD_REQ );
//{{ 2012. 02. 22	박세훈	길드 이름 변경권
#ifdef SERV_GUILD_CHANGE_NAME
EVENT_HANDLER( ELG_CREATE_GUILD_ACK );
#else
EVENT_HANDLER( DBE_CREATE_GUILD_ACK );
#endif SERV_GUILD_CHANGE_NAME
//}}
_EVENT_HANDLER( ELG_CREATE_GUILD_RESULT_ACK, KEGS_GUILD_INFO_NOT );
//}}

_EVENT_HANDLER( ELG_GET_GUILD_INFO_ACK, KEGS_GUILD_INFO_NOT );

EVENT_HANDLER( EGS_GET_GUILD_USER_LIST_REQ );
_EVENT_HANDLER( ELG_GET_GUILD_USER_LIST_ACK, KEGS_GET_GUILD_USER_LIST_ACK );

_EVENT_HANDLER( ELG_GUILD_INFO_NOT, KEGS_GUILD_INFO_NOT );
_EVENT_HANDLER( ELG_GUILD_MESSAGE_NOT, KEGS_GUILD_MESSAGE_NOT );

EVENT_HANDLER( EGS_INVITE_GUILD_REQ );
EVENT_HANDLER( ELG_INVITE_GUILD_FIND_USER_REQ );
EVENT_HANDLER( ELG_INVITE_GUILD_ACK );
_EVENT_HANDLER( DBE_INVITE_GUILD_NICKNAME_CHECK_ACK, KELG_INVITE_GUILD_ACK );

EVENT_HANDLER( EGS_INVITE_GUILD_REPLY_REQ );
EVENT_HANDLER( ELG_INVITE_GUILD_REPLY_ACK );
_EVENT_HANDLER( ELG_INVITE_GUILD_REPLY_DENY_NOT, KEGS_INVITE_GUILD_REPLY_DENY_NOT );	
EVENT_HANDLER( ELG_JOIN_GUILD_ACK );

EVENT_HANDLER( EGS_CHANGE_GUILD_MEMBER_GRADE_REQ );
EVENT_HANDLER( ELG_CHECK_CHANGE_GUILD_MEMBER_GRADE_ACK );
EVENT_HANDLER( DBE_CHANGE_GUILD_MEMBER_GRADE_ACK );

EVENT_HANDLER( EGS_CHANGE_GUILD_MESSAGE_REQ );
EVENT_HANDLER( DBE_CHANGE_GUILD_MESSAGE_ACK );

EVENT_HANDLER( EGS_KICK_GUILD_MEMBER_REQ );
EVENT_HANDLER( DBE_KICK_GUILD_MEMBER_ACK );

EVENT_HANDLER( EGS_CHANGE_GUILD_MEMBER_MESSAGE_REQ );
EVENT_HANDLER( DBE_CHANGE_GUILD_MEMBER_MESSAGE_ACK );

EVENT_HANDLER_NOPARAM( EGS_DISBAND_GUILD_REQ );
EVENT_HANDLER( DBE_DISBAND_GUILD_ACK );

EVENT_HANDLER( ELG_CHECK_EXPAND_GUILD_MAX_MEMBER_ACK );

//{{ 2012. 02. 22	박세훈	길드 이름 변경권
#ifdef SERV_GUILD_CHANGE_NAME
EVENT_HANDLER( EGS_CHANGE_GUILD_NAME_CHECK_REQ );
EVENT_HANDLER( ELG_CHANGE_GUILD_NAME_CHECK_ACK );
EVENT_HANDLER( EGS_CHANGE_GUILD_NAME_REQ );
EVENT_HANDLER( ELG_CHANGE_GUILD_NAME_ACK );
EVENT_HANDLER( ELG_CHANGE_GUILD_NAME_TIME_CHECK_ACK );
#endif SERV_GUILD_CHANGE_NAME
//}}

#endif GUILD_TEST
//}}

//{{ 2009. 11. 23  최육사	길드스킬
#ifdef GUILD_SKILL_TEST

EVENT_HANDLER( EGS_GET_GUILD_SKILL_REQ );
_EVENT_HANDLER( ELG_GET_GUILD_SKILL_ACK, KEGS_GET_GUILD_SKILL_ACK );
_EVENT_HANDLER( ELG_GET_GUILD_SKILL_NOT, KEGS_GET_GUILD_SKILL_NOT );

EVENT_HANDLER( EGS_RESET_GUILD_SKILL_REQ );
_EVENT_HANDLER( ELG_RESET_GUILD_SKILL_ACK, KEGS_RESET_GUILD_SKILL_ACK );
_EVENT_HANDLER( ELG_RESET_GUILD_SKILL_DEL_ITEM_REQ, KDBE_RESET_GUILD_SKILL_REQ );
EVENT_HANDLER( DBE_RESET_GUILD_SKILL_ACK );
_EVENT_HANDLER( ELG_RESET_GUILD_SKILL_NOT, KEGS_RESET_GUILD_SKILL_NOT );

EVENT_HANDLER( EGS_INIT_GUILD_SKILL_REQ );
_EVENT_HANDLER( ELG_INIT_GUILD_SKILL_ACK, KEGS_INIT_GUILD_SKILL_ACK );
_EVENT_HANDLER( ELG_INIT_GUILD_SKILL_DEL_ITEM_REQ, KDBE_INIT_GUILD_SKILL_REQ );
EVENT_HANDLER( DBE_INIT_GUILD_SKILL_ACK );
_EVENT_HANDLER( ELG_INIT_GUILD_SKILL_NOT, KEGS_INIT_GUILD_SKILL_NOT );

_EVENT_HANDLER( ELG_EXPIRE_GUILD_CASH_SKILL_POINT_NOT, KEGS_EXPIRE_GUILD_CASH_SKILL_POINT_NOT );

EVENT_HANDLER( ERM_CHANGE_SKILL_INFO_IN_ROOM_NOT );

#endif GUILD_SKILL_TEST
//}}

//{{ 2009. 12. 31  최육사	길드 광고
#ifdef SERV_GUILD_AD

EVENT_HANDLER( EGS_GET_GUILD_AD_LIST_REQ );
_EVENT_HANDLER( ELG_GET_GUILD_AD_LIST_ACK, KEGS_GET_GUILD_AD_LIST_ACK );

EVENT_HANDLER( EGS_GET_GUILD_SKILL_IN_BOARD_REQ );
_EVENT_HANDLER( ELG_GET_GUILD_SKILL_IN_BOARD_ACK, KEGS_GET_GUILD_SKILL_IN_BOARD_ACK );

EVENT_HANDLER( EGS_REGISTRATION_GUILD_AD_REQ );
EVENT_HANDLER( ELG_REGISTRATION_GUILD_AD_ACK );

EVENT_HANDLER( EGS_MODIFY_REG_GUILD_AD_REQ );
EVENT_HANDLER( ELG_MODIFY_REG_GUILD_AD_ACK );

EVENT_HANDLER( EGS_APPLY_JOIN_GUILD_REQ );
_EVENT_HANDLER( ELG_APPLY_JOIN_GUILD_ACK, KEGS_APPLY_JOIN_GUILD_ACK );

EVENT_HANDLER( EGS_GET_APPLY_JOIN_GUILD_LIST_REQ );
_EVENT_HANDLER( ELG_GET_APPLY_JOIN_GUILD_LIST_ACK, KEGS_GET_APPLY_JOIN_GUILD_LIST_ACK );

EVENT_HANDLER( EGS_ACCEPT_JOIN_GUILD_REQ );
_EVENT_HANDLER( ELG_ACCEPT_JOIN_GUILD_ACK, KEGS_ACCEPT_JOIN_GUILD_ACK );

EVENT_HANDLER( EGS_DELETE_APPLY_JOIN_GUILD_REQ );
_EVENT_HANDLER( ELG_DELETE_APPLY_JOIN_GUILD_ACK, KEGS_DELETE_APPLY_JOIN_GUILD_ACK );

#endif SERV_GUILD_AD
//}}


