#pragma once

#include "Event.h"
#include "CommonPacket.h"
#include "SystemPacket.h"
#include "ClientPacket.h"
#include "ServerPacket.h"

#include "SubThread.h"

class KNexonBillingTCP : public KSubThread
{
	enum NEXON_BILLING_ENUM
	{
		ROW_PER_PAGE = 90,
	};

public:
	KNexonBillingTCP( void );
	virtual ~KNexonBillingTCP( void );

protected:
	// derived from KSubThread
	virtual void ProcessEvent( const KEventPtr& spEvent );

    DECL_ON_FUNC( ENX_BT_INITIALIZE_ACK );
    DECL_ON_FUNC( ENX_BT_HEART_BEAT_ACK );
    DECL_ON_FUNC( ENX_BT_CATEGORY_INQUIRY_ACK );
    DECL_ON_FUNC( ENX_BT_PRODUCT_INQUIRY_ACK );
    DECL_ON_FUNC( ENX_BT_CHECK_BALANCE_REQ );
    DECL_ON_FUNC( ENX_BT_CHECK_BALANCE_ACK );
    DECL_ON_FUNC( ENX_BT_PURCHASE_ITEM_REQ );
    DECL_ON_FUNC( ENX_BT_PURCHASE_ITEM_ACK );
    DECL_ON_FUNC( ENX_BT_PURCHASE_GIFT_REQ );
    DECL_ON_FUNC( ENX_BT_PURCHASE_GIFT_ACK );
	//{{ 2009. 10. 14  ÃÖÀ°»ç	ÀÚµ¿°áÁ¦
	DECL_ON_FUNC( ENX_BT_CHECK_AUTO_PAYMENT_USER_REQ );
	DECL_ON_FUNC( ENX_BT_CHECK_AUTO_PAYMENT_USER_ACK );
	//}}
    DECL_ON_FUNC( ENX_BT_COUPON_INQUIRY_REQ );
    DECL_ON_FUNC( ENX_BT_COUPON_INQUIRY_ACK );
	//{{ 2009. 3. 24  ÃÖÀ°»ç	ÄíÆù»ç¿ë¿©ºÎ Á¶È¸
	DECL_ON_FUNC( ENX_BT_COUPON_INQUIRY_NEW_REQ );
	DECL_ON_FUNC( ENX_BT_COUPON_INQUIRY_NEW_ACK );
	//}}
    DECL_ON_FUNC( ENX_BT_COUPON_USING_REQ );
    DECL_ON_FUNC( ENX_BT_COUPON_USING_ACK );	
    DECL_ON_FUNC( ENX_BT_NISMS_INVENTORY_INQUIRY_REQ );
    DECL_ON_FUNC( ENX_BT_NISMS_INVENTORY_INQUIRY_ACK );
	//{{ 2008. 6. 20  ÃÖÀ°»ç  ¼±¹°ÇÏ±â
	DECL_ON_FUNC( ENX_BT_NISMS_INVENTORY_CHECK_REQ ); 
	DECL_ON_FUNC( ENX_BT_NISMS_INVENTORY_CHECK_ACK );
	DECL_ON_FUNC( ENX_BT_NISMS_INVENTORY_READABLE_REQ );
	DECL_ON_FUNC( ENX_BT_NISMS_INVENTORY_READABLE_ACK );
	//}}
    DECL_ON_FUNC( ENX_BT_NISMS_INVENTORY_READ_REQ );
    DECL_ON_FUNC( ENX_BT_NISMS_INVENTORY_READ_ACK );
    DECL_ON_FUNC( ENX_BT_NISMS_INVENTORY_PICK_UP_REQ );
    DECL_ON_FUNC( ENX_BT_NISMS_INVENTORY_PICK_UP_ACK );
    DECL_ON_FUNC( ENX_BT_NISMS_INVENTORY_PICK_UP_ROLLBACK_REQ );
    DECL_ON_FUNC( ENX_BT_NISMS_INVENTORY_PICK_UP_ROLLBACK_ACK );
    DECL_ON_FUNC( ENX_BT_NISMS_INVENTORY_PICK_UP_ONCE_REQ );
    DECL_ON_FUNC( ENX_BT_NISMS_INVENTORY_PICK_UP_ONCE_ACK );
	//{{ 2008. 6. 16  ÃÖÀ°»ç  ³Ø½¼ºô¸µ ÆÐÅ°Áö ÇÈ¾÷
	DECL_ON_FUNC( ENX_BT_NISMS_INVENTORY_PICK_UP_FOR_PACKAGE_REQ );
	DECL_ON_FUNC( ENX_BT_NISMS_INVENTORY_PICK_UP_FOR_PACKAGE_ACK );
	//}}
	//{{ 2010. 11. 17	ÃÖÀ°»ç	³Ø½¼ ºô¸µ Ã»¾à Ã¶È¸
#ifdef SERV_NX_BILLING_REFUND
	DECL_ON_FUNC( ENX_BT_REFUND_REQ );
	DECL_ON_FUNC( ENX_BT_REFUND_ACK );
#endif SERV_NX_BILLING_REFUND
	//}}

#ifdef SERV_NEXON_COUPON_SYSTEM// ÀÛ¾÷³¯Â¥: 2013-06-21	// ¹Ú¼¼ÈÆ
	DECL_ON_FUNC( ENX_BT_NISMS_ITEM_COUPON_USING_REQ );
	DECL_ON_FUNC( ENX_BT_NISMS_ITEM_COUPON_USING_ACK );

	DECL_ON_FUNC( ENX_BT_NISMS_DISCOUNT_COUPON_INQUIRY_REQ );
	DECL_ON_FUNC( ENX_BT_NISMS_DISCOUNT_COUPON_INQUIRY_ACK );

	DECL_ON_FUNC( ENX_BT_NISMS_DISCOUNT_COUPON_INQUIRY_LIST_REQ );
	DECL_ON_FUNC( ENX_BT_NISMS_DISCOUNT_COUPON_INQUIRY_LIST_ACK );
#endif // SERV_NEXON_COUPON_SYSTEM
};
