_ENUM( INITIALIZE, 0x01 )
_ENUM( HEART_BEAT, 0x02 )
//{{ 2011. 07. 27    김민성    투니랜드 채널링
//#ifdef SERV_TOONILAND_CHANNELING
_ENUM( CHECK_BALANCE, 0x13 ) // 채널링 버전 잔액조회
//#else
//_ENUM( CHECK_BALANCE, 0x11 )
//#endif SERV_TOONILAND_CHANNELING
//}}

_ENUM( PURCHASE_ITEM, 0x21 )
_ENUM( PURCHASE_GIFT, 0x22 )
//{{ 2009. 10. 14  최육사	자동결제
_ENUM( CHECK_AUTO_PAYMENT_USER, 0x29 )
//}}
_ENUM( COUPON_INQUIRY, 0x31 )
//{{ 2009. 3. 24  최육사	쿠폰사용여부 조회
_ENUM( COUPON_INQUIRY_NEW, 0x33 )
//}}
_ENUM( COUPON_USING, 0x032 )
_ENUM( NISMS_INVENTORY_CHECK, 0x40 )
_ENUM( NISMS_INVENTORY_INQUIRY, 0x41 )
//_ENUM( NISMS_INVENTORY_INQUIRY_ORDER, 0x42 )
//_ENUM( NISMS_INVENTORY_INQUIRY_PACKAGE, 0x43 )
//_ENUM( NISMS_INVENTORY_INQUIRY_LOTTERY, 0x44 )
//{{ 2008. 6. 26  최육사  선물하기
_ENUM( NISMS_INVENTORY_READABLE, 0x45 )
//}}
_ENUM( NISMS_INVENTORY_READ, 0x49 )
_ENUM( NISMS_INVENTORY_PICK_UP, 0x4A )
_ENUM( NISMS_INVENTORY_PICK_UP_ROLLBACK, 0x4B )
_ENUM( NISMS_INVENTORY_PICK_UP_ONCE, 0x4C )
_ENUM( NISMS_INVENTORY_PICK_UP_FOR_PACKAGE, 0x4D )
_ENUM( PRODUCT_INQUIRY_XML, 0x51 )
_ENUM( PRODUCT_INQUIRY, 0x52 )
_ENUM( CATEGORY_INQUIRY, 0x61 )
//{{ 2010. 11. 17	최육사	넥슨 빌링 청약 철회
_ENUM( REFUND, 0x80 )
//}}

//#ifdef SERV_NEXON_COUPON_SYSTEM// 작업날짜: 2013-06-20	// 박세훈
//_ENUM( NISMS_ITEM_COUPON_USING, 0x70 )
//_ENUM( NISMS_DISCOUNT_COUPON_INQUIRY, 0x71 )
//_ENUM( NISMS_DISCOUNT_COUPON_INQUIRY_LIST, 0x72 )
//_ENUM_PROCESS( NISMS_PURCHASE_ITEM_WITH_DISCOUNT_COUPON, 0x73, PURCHASE_ITEM )	// 구매 패킷 프로세스를 하나로 하기 위한 작업
//_ENUM_PROCESS( NISMS_PURCHASE_GIFT_WITH_DISCOUNT_COUPON, 0x74, PURCHASE_GIFT )	// 선물 패킷 프로세스를 하나로 하기 위한 작업
//#endif // SERV_NEXON_COUPON_SYSTEM