#ifdef __NEVER_DEFINED_MACRO__
#define _ENUM(VAL) VAL,
enum
{
#endif

	//_ENUM( ENUM_MY_EVENT_ID )

	//#ifdef SERV_LOGIN_RESULT_INFO
	_ENUM( DBE_INSERT_LOGIN_RESULT_INFO_REQ )
	//#endif SERV_LOGIN_RESULT_INFO

	//#ifdef SERV_CHECK_PCBANG_BY_PUBLISHER
	_ENUM( ELG_PCBANG_LOGOUT_NOT )
	//#endif SERV_CHECK_PCBANG_BY_PUBLISHER

	//#ifdef SERV_NEW_PVPROOM_PROCESS
	_ENUM( ERM_CHANGE_PVP_ROOM_PUBLIC_REQ )
	_ENUM( ERM_CHANGE_PVP_ROOM_PUBLIC_ACK )
	_ENUM( ERM_CHANGE_PVP_ROOM_PUBLIC_NOT )
	_ENUM( ERM_CHANGE_PVP_ROOM_NAME_REQ )
	_ENUM( ERM_CHANGE_PVP_ROOM_NAME_ACK )
	_ENUM( ERM_CHANGE_PVP_ROOM_NAME_NOT )
	//#endif SERV_NEW_PVPROOM_PROCESS

	//ifdef SERV_DELETE_GUILD_ADD_CHEAT
	_ENUM( ELG_ADMIN_DELETE_GUILD_ADD_NOT )
	//endif

	//#ifdef SERV_DELETE_HENIR_RANKING
	_ENUM( ELG_ADMIN_DELETE_HENIR_RANKING_RANK_NOT )
	_ENUM( ELG_ADMIN_DELETE_HENIR_RANKING_NICKNAME_NOT )
	_ENUM( ELG_ADMIN_DELETE_HENIR_RANKING_UNITUID_NOT )
	//#endif

	//#ifdef SERV_NEW_PUNISHMENT
	_ENUM( DBE_GET_PUNISHMENT_REQ )
	_ENUM( DBE_GET_PUNISHMENT_ACK )
	//#endif SERV_NEW_PUNISHMENT

	//#ifdef SERV_PVP_REMATCH
	_ENUM( ERM_PVP_REMATCH_REQ )
	_ENUM( ERM_PVP_REMATCH_ACK )
	_ENUM( ERM_PVP_REMATCH_NOT )
	//#endif SERV_PVP_REMATCH

	//#ifdef SERV_GLOBAL_AUTH && SERV_GLOBAL_BILLING


	_ENUM( ELG_VERIFY_ACCOUNT_REQ )		// ChannelServer 에서 LoginServer 로 인증 넘어감
	_ENUM( ELG_SECURITY_AUTH_REQ )		// ChannelServer 에서 LoginServer 로 인증 넘어감

	_ENUM( EPUBLISHER_SECURITY_INFO_NOT )

	_ENUM( EPUBLISHER_AUTHENTICATION_REQ )
	_ENUM( EPUBLISHER_AUTHENTICATION_ACK )


	_ENUM( DBE_CH_USER_GENERAL_LOGIN_REQ )	
	_ENUM( DBE_CH_USER_GENERAL_LOGIN_ACK )

	_ENUM( DBE_CH_USER_KOGOTP_LOGIN_REQ )
	_ENUM( DBE_CH_USER_KOGOTP_LOGIN_ACK )

	_ENUM( ELG_GAME_USER_AUTHENTICATE_REQ )          // gs -> cn : 유저 인증 요청
	_ENUM( ELG_GAME_USER_AUTHENTICATE_ACK )

	// 조금 특이한 패킷이긴 한데 퍼블에 핵유저 Report
	_ENUM( EPUBLISHER_REPORT_HACK_USER_NOT )

	//#ifdef SERV_COUNTRY_TH
	//{{ 허상형 : [2012/6/19] //	AsiaSoft 인증
	_ENUM( EAS_AUTH_LOGIN_REQ )
	_ENUM( EAS_AUTH_LOGIN_ACK )

	_ENUM( EAS_GET_IPBONUS_REQ )
	_ENUM( EAS_GET_IPBONUS_ACK )

	_ENUM( EAS_AUTH_AKEY_REQ )
	_ENUM( EAS_AUTH_AKEY_ACK )

	_ENUM( DBE_AS_USER_LOGIN_REQ )
	_ENUM( DBE_AS_USER_LOGIN_ACK )

	_ENUM( ELG_AS_USER_AUTHENTICATE_REQ )
	_ENUM( ELG_AS_USER_AUTHENTICATE_ACK )
	//}} 허상형 : [2012/6/19] //	AsiaSoft 인증
	//endif // SERV_COUNTRY_TH

	//#ifdef SERV_COUNTRY_CN
	// 2010.07.07 박교현 / 자이언트 플랫폼 인증
	_ENUM( EGIANT_COMMON_INITIALIZE_REQ )						// LoginHLCmd
	_ENUM( EGIANT_COMMON_INITIALIZE_ACK )						// LoginHLOKCmd
	_ENUM( EGIANT_COMMON_NULL_SERVER )							// ServerNullCmd
	_ENUM( EGIANT_COMMON_NULL_CLIENT )							// ClientNullCmd
	// 2010.07.07 박교현 / 자이언트 HLServer 인증
	_ENUM( EGIANT_AUTH_LOGIN_SUCCESS )
	_ENUM( EGIANT_AUTH_LOGIN_FAIL )
	//#endif SERV_COUNTRY_CN

	_ENUM( DBE_GIANT_USER_LOGIN_REQ )
	_ENUM( DBE_GIANT_USER_LOGIN_ACK )

	
	//{{ 박교현 : [2010/03/09] //	중국 중독방지 방침미 시스템
	_ENUM( DBE_GET_ANTI_ADDICTION_INFO_REQ )
	_ENUM( DBE_GET_ANTI_ADDICTION_INFO_ACK )
	_ENUM( DBE_UPDATE_ANTI_ADDICTION_INFO )
	//}}

	//////////////////////////////////////////////////////////////////////////
	_ENUM( EPUBLISHER_BILLING_BALANCE_REQ )							
	_ENUM( EPUBLISHER_BILLING_BALANCE_ACK )

	//{{ 2011. 02. 28	최육사	중국 자이언트 빌링
	_ENUM( ELG_VERIFY_GIANT_MATRIX_CARD_REQ )
	_ENUM( ELG_VERIFY_GIANT_MATRIX_CARD_ACK )
	_ENUM( ELG_VERIFY_GIANT_MATRIX_CARD_NOT )

	_ENUM( EGIANT_BILLING_RETURN )								// RetCmd
	_ENUM( EGIANT_BILLING_USE_CARD_CMD )
	_ENUM( EGIANT_BILLING_USE_CARD_RET_CMD )
	_ENUM( EGIANT_BILLING_CONSUME_REQ )							// CONSUME_CMD
	_ENUM( EGIANT_BILLING_CONSUME_ACK )
	_ENUM( EGIANT_BILLING_PCARD_CMD )
	_ENUM( EGIANT_BILLING_SCARD_CMD )
	//}}

	//////////////////////////////////////////////////////////////////////////
	// 2010.07.07 박교현 / 자이언트 RoleRegServer 인증
	_ENUM( EGIANT_ROLEREG )						
	_ENUM( EGIANT_ROLEREG_CREATE_UNIT_REQ )						// CharNameRoleReg
	_ENUM( EGIANT_ROLEREG_CREATE_UNIT_ACK )						// CharNameRoleReg
	_ENUM( EGIANT_ROLEREG_DELETE_UNIT_REQ )						// CharNameRoleReg
	_ENUM( EGIANT_ROLEREG_DELETE_UNIT_ACK )						// CharNameRoleReg
	//_ENUM( DBE_INSERT_GIANT_DELETE_UNIT_REQ ) // 현재 사용하는 곳 없음. 주석 처리
	//_ENUM( DBE_UPDATE_GIANT_DELETE_UNIT_NOT )	// 현재 사용하는 곳 없음. 주석 처리
	_ENUM( EGIANT_ROLEREG_CREATE_GUILD_REQ )					// ClubNameRoleReg
	_ENUM( EGIANT_ROLEREG_CREATE_GUILD_ACK )					// ClubNameRoleReg
	_ENUM( EGIANT_ROLEREG_DELETE_GUILD_REQ )					// ClubNameRoleReg
	_ENUM( EGIANT_ROLEREG_DELETE_GUILD_ACK )					// ClubNameRoleReg

	//_ENUM( DBE_GET_GIANT_DELETED_UNIT_LIST_REQ )	// 현재 사용하는 곳 없음. 주석 처리
	//_ENUM( DBE_GET_GIANT_DELETED_UNIT_LIST_ACK )	// 현재 사용하는 곳 없음. 주석 처리


	//////////////////////////////////////////////////////////////////////////
	// 2010.07.07 박교현 / 자이언트 InfoServer 인증
	_ENUM( EGIANT_INFO_GET_CCU_REQ )
	_ENUM( EGIANT_INFO_GET_TOTAL_CCU_ACK )
	_ENUM( EGIANT_INFO_GET_CHANNEL_CCU_ACK )
	_ENUM( EGIANT_INFO_CHAT_NOT )
	_ENUM( EGIANT_INFO_PUNISH_REQ )

	//#ifdef SERV_INFOSERVER_ADD_WORK
	_ENUM( EGIANT_INFO_USERONLINE_REQ )
	_ENUM( EGIANT_INFO_USERONLINE_ACK )
	_ENUM( EGIANT_INFO_REQUESTID_REQ )
	_ENUM( EGIANT_INFO_REQUESTID_ACK )
	//#endif //SERV_INFOSERVER_ADD_WORK
	_ENUM( ELG_CHAT_OBSERVATION_NOT )

	_ENUM( EPUBLISHER_SECURITY_AUTH_REQ )
	_ENUM( EPUBLISHER_SECURITY_AUTH_ACK )

	_ENUM( EPUBLISHER_REG_USER_REQ )
	_ENUM( EPUBLISHER_REG_USER_ACK )

	_ENUM( EPUBLISHER_UNREG_USER_REQ )
	_ENUM( EPUBLISHER_UNREG_USER_ACK )

	_ENUM( ELG_REGISTER_USER_GLOBAL_PUBLISHER_ACK )	// 해외용 퍼블리셔 인증 ACK 처리 함수 
	

	//{{ 2011. 03. 03	최육사	중국 서버 빌링
	_ENUM( EBILL_INVENTORY_INQUIRY_REQ )
	_ENUM( EBILL_INVENTORY_INQUIRY_ACK )


	_ENUM( EBILL_CHECK_PRODUCT_INFO_REQ )
	_ENUM( EBILL_CHECK_PRODUCT_INFO_ACK )

	// 2009-11-18  구매전 캐쉬인벤체크	KOG_BILLING
	_ENUM( EBILL_PREPARE_BUY_PRODUCT_REQ )
	_ENUM( EBILL_PREPARE_BUY_PRODUCT_ACK )

	_ENUM( EBILL_BUY_PRODUCT_REQ )	
	_ENUM( EBILL_BUY_PRODUCT_ACK )

	_ENUM( EBILL_PREPARE_GIFT_ITEM_REQ )
	_ENUM( EBILL_PREPARE_GIFT_ITEM_ACK )

	_ENUM( EBILL_GIFT_ITEM_REQ )
	_ENUM( EBILL_GIFT_ITEM_ACK )

	_ENUM( DBE_INSERT_CASH_DECREASE_ERROR_LOG_NOT )

	_ENUM( EBILL_USE_COUPON_REQ )
	_ENUM( EBILL_USE_COUPON_ACK )

	_ENUM( EBILL_USE_COUPON_RESULT_REQ )
	_ENUM( EBILL_USE_COUPON_RESULT_ACK )

	_ENUM( EBILL_PICK_UP_REQ )
	_ENUM( EBILL_PICK_UP_ACK )

	_ENUM( ELG_EXCHANGE_CASH_REQ )
	_ENUM( ELG_EXCHANGE_CASH_ACK )
	_ENUM( EBILL_CHECK_BALANCE_REQ )
	_ENUM( EBILL_CHECK_BALANCE_ACK )
	_ENUM( EBILL_EXCHANGE_CASH_RESERVE_REQ )
	_ENUM( EBILL_EXCHANGE_CASH_RESERVE_ACK )
	_ENUM( EBILL_EXCHANGE_CASH_REQ )
	_ENUM( EBILL_EXCHANGE_CASH_ACK )
	_ENUM( EBILL_GET_TRANS_FOR_CHECK_BALANCE_REQ )
	_ENUM( EBILL_GET_TRANS_FOR_CHECK_BALANCE_ACK )
	_ENUM( EBILL_GET_TRANS_FOR_EXCHANGE_REQ )
	_ENUM( EBILL_GET_TRANS_FOR_EXCHANGE_ACK )

	_ENUM( ELG_USE_COUPON_REQ )
	_ENUM( EBILL_USE_COUPON_RESERVE_REQ )
	_ENUM( EBILL_USE_COUPON_RESERVE_ACK )

	_ENUM( DBE_GET_NICKNAME_BY_UNITUID_REQ )	//	선물 기능 개편
	_ENUM( DBE_GET_NICKNAME_BY_UNITUID_ACK )

	//#ifdef GIANT_RESURRECTION_CASHSTONE
	_ENUM( DBE_REALTIME_RESURRECTION_CASHSTONE_NOT )
	_ENUM( DBE_RESURRECTION_CASHSTONE_NOT )
	//#endif //GIANT_RESURRECTION_CASHSTONE

	_ENUM( EGASH_GET_GASHPOINT_REQ )
	_ENUM( EGASH_GET_GASHPOINT_ACK )

	_ENUM( EGASH_DECREASE_GASHPOINT_REQ )
	_ENUM( EGASH_DECREASE_GASHPOINT_ACK )

	// Gash 사용했다고 대만DB에 로그 남기는데 사용하는 패킷
	_ENUM( EGASH_USE_GASH_LOG_NOT )

	//#ifdef SERV_GOLD_TICKET // 대만 사용
	_ENUM( EPUBLISHER_CHARGE_POINT_REQ )
	_ENUM( EPUBLISHER_CHARGE_POINT_ACK )
	_ENUM( ELOG_CHARGE_POINT_NOT )
	//#endif SERV_GOLD_TICKET

	//#ifdef SERV_COUNTRY_US
	_ENUM( EPL_BT_HEALTH_CHECK_REQ )
	_ENUM( EPL_BT_HEALTH_CHECK_ACK )

	_ENUM( EPL_BT_BALANCE_CHECK_REQ )
	_ENUM( EPL_BT_BALANCE_CHECK_ACK )

	_ENUM( EPL_BT_PURCHASEITEM_ACK )

	_ENUM( EPL_BT_REGCOUPON_ACK )

	_ENUM( EPL_BT_GIFTITEM_ACK )
	//#endif SERV_COUNTRY_US

	//#ifdef SERV_COUNTRY_BR
	_ENUM( EPL_BR_HEALTH_CHECK_REQ )
	_ENUM( EPL_BR_HEALTH_CHECK_ACK )

	_ENUM( EPL_BR_BALANCE_CHECK_REQ )
	_ENUM( EPL_BR_BALANCE_CHECK_ACK )

	_ENUM( EPL_BR_PURCHASEITEM_ACK )

	_ENUM( EPL_BR_REGCOUPON_ACK )

	_ENUM( EPL_BR_GIFTITEM_ACK )
	//#endif SERV_COUNTRY_BR


	//#endif SERV_GLOBAL_AUTH && SERV_GLOBAL_BILLING

	//{{ 2012.02.20 조효진	캐릭터 삭제 프로세스 변경 (삭제 대기 기간 도입)
	//#ifdef SERV_UNIT_WAIT_DELETE
	_ENUM( DBE_GAME_FINAL_DELETE_UNIT_REQ )	//유닉 최종 삭제용으로 사용
	_ENUM( DBE_GAME_FINAL_DELETE_UNIT_ACK )
	_ENUM( DBE_GAME_RESTORE_UNIT_REQ )
	_ENUM( DBE_GAME_RESTORE_UNIT_ACK )
	//#endif SERV_UNIT_WAIT_DELETE
	//}}

	//{{ 허상형 : [2010/8/31/] //	부활석 통계 분리 작업
	//#ifdef SERV_SELECT_UNIT_NEW	
	_ENUM( ELOG_UPDATE_STONE_NOT )
	//#endif SERV_SELECT_UNIT_NEW

	//{{ 2010. 11. 22 조효진. 채팅 로그 작업
	//#ifdef SERV_RECORD_CHAT
	_ENUM( DCHATLOG_RECORD_CHAT_NOT )
	//#endif SERV_RECORD_CHAT
	//}}

	//{{ 2011.05.04   임규수 아바타 합성 시스템
	//#ifdef SERV_SYNTHESIS_AVATAR
	_ENUM( DBE_OPEN_SYNTHESIS_ITEM_REQ )
	_ENUM( DBE_OPEN_SYNTHESIS_ITEM_ACK )
	_ENUM( DBE_SYNTHESIS_LOG_NOT )
	//#endif SERV_SYNTHESIS_AVATAR

	//{{ 2011. 12. 09	박교현		서버군 리스트
	//#ifdef SERVER_GROUP_UI_ADVANCED
	_ENUM( DBE_SERVERGROUP_LIST_REQ )
	_ENUM( DBE_SERVERGROUP_LIST_ACK )
	//#endif SERVER_GROUP_UI_ADVANCED
	//}}

	//#ifdef SERV_INVISIBLE_GM
	_ENUM( ERM_TOGGLE_INVISIBLE_NOT )
	_ENUM( ETR_TOGGLE_INVISIBLE_NOT )
	//#endif SERV_INVISIBLE_GM

	//#ifdef SERV_CATCH_HACKUSER_INFO
	_ENUM( DBE_CATCH_HACKUSER_INTO_NOT )
	//#endif SERV_CATCH_HACKUSER_INFO

	//#ifdef SERV_SHARING_BANK_TEST
	_ENUM( DBE_GET_SHARE_BANK_REQ )
	_ENUM( DBE_GET_SHARE_BANK_ACK )

	_ENUM( DBE_UPDATE_SHARE_ITEM_REQ )
	_ENUM( DBE_UPDATE_SHARE_ITEM_ACK )

	_ENUM( DBE_CHANGE_INVENTORY_SLOT_ITEM_REQ )
	_ENUM( DBE_CHANGE_INVENTORY_SLOT_ITEM_ACK )

	_ENUM( DBE_UPDATE_SHARE_ITEM_FOR_MOVE_SLOT_REQ )
	_ENUM( DBE_UPDATE_SHARE_ITEM_FOR_MOVE_SLOT_ACK )

	_ENUM( DBE_UPDATE_SEAL_DATA_NOT )

	_ENUM( ELOG_UPDATE_SHARE_ITEM_NOT )
	_ENUM( ELOG_ITEM_TRADE_ERROR_NOT )
	//#endif SERV_SHARING_BANK_TEST
	//#ifdef SERV_SHARING_BANK_QUEST_CASH
	_ENUM( DBE_SHARING_BACK_OPEN_REQ )
	_ENUM( DBE_SHARING_BACK_OPEN_ACK )
	//#endif SERV_SHARING_BANK_QUEST_CASH

	//#ifdef SERV_ADVERTISEMENT_EVENT
	_ENUM( DBE_INSERT_ADVERTISEMENT_EVENT_INFO_NOT )
	//#endif SERV_ADVERTISEMENT_EVENT
	
//#ifdef SERV_REFRESH_EVENT_USING_RELEASE_TICK
	_ENUM( DBE_CHECK_EVENT_UPDATE_REQ )
	_ENUM( DBE_CHECK_EVENT_UPDATE_ACK )
//#endif SERV_REFRESH_EVENT_USING_RELEASE_TICK	

//#ifdef SERV_ADD_WARP_BUTTON
	_ENUM( DBE_INSERT_WARP_VIP_REQ )
	_ENUM( DBE_INSERT_WARP_VIP_ACK )
//#endif // SERV_ADD_WARP_BUTTON

//{{ 2013. 05. 14	최육사	통합 제재 시스템
//#ifdef SERV_BLOCK_LIST
	_ENUM( DBE_CHECK_BLOCK_LIST_REQ )
	_ENUM( DBE_CHECK_BLOCK_LIST_ACK )

	_ENUM( EGB_CHECK_BLOCK_USER_NOT )
	_ENUM( EGB_UPDATE_BLOCK_RESULT_NOT )

	_ENUM( EGB_MODULE_INFO_UPDATE_NOT )
//#endif SERV_BLOCK_LIST
//}}

//#ifdef SERV_EVENT_BUY_FAKE_ITEM
	_ENUM( EBILL_CHECK_BUY_FAKE_ITEM_REQ )
	_ENUM( EBILL_CHECK_BUY_FAKE_ITEM_ACK )
//#endif SERV_EVENT_BUY_FAKE_ITEM
//#ifdef SERV_KOM_FILE_CHECK_ADVANCED
	_ENUM( ELOG_KOM_FILE_CHECK_LOG_NOT )
//#endif SERV_KOM_FILE_CHECK_ADVANCED


//#ifdef SERV_CLIENT_PORT_CHANGE_REQUEST_LOG
	_ENUM( DBE_CLIENT_POPRT_CHANGE_REQUEST_INFO_NOT )
//#endif //SERV_CLIENT_PORT_CHANGE_REQUEST_LOG

//#ifdef SERV_SKILL_POINT_CORRECTION
	_ENUM( DBE_SKILL_POINT_CORRECTION_INFO_NOT )
//#endif //SERV_SKILL_POINT_CORRECTION

//#ifdef SERV_ID_NETMARBLE_PCBANG
	_ENUM( DBE_PCBANG_IP_AND_MAC_INFO_NOT )
	_ENUM( DBE_ID_PCBANG_CEHCK_AUTH_REQ )
	_ENUM( DBE_ID_PCBANG_CEHCK_AUTH_ACK )
//#endif //SERV_ID_NETMARBLE_PCBANG

//#ifdef SERV_COUNTRY_PH
	_ENUM( EJSON_GN_CHECK_ACCOUNT_REQ )
	_ENUM( EJSON_GN_CHECK_ACCOUNT_ACK )
	_ENUM( EJSON_GN_CHANGE_GAME_CURRENCY_REQ )
	_ENUM( EJSON_GN_CHANGE_GAME_CURRENCY_ACK )
	_ENUM( EJSON_GN_TRANSACTION_REQ )
	_ENUM( EJSON_GN_TRANSACTION_ACK )

	_ENUM( EBILL_GN_CHANGE_GAME_CURRENCY_REQ )
	_ENUM( ELG_GN_CHANGE_GAME_CURRENCY_NOT )
	_ENUM( EBILL_GN_CHANGE_GAME_CURRENCY_ACK )

	_ENUM( EBILL_LOGIN_CHECK_BALANCE_REQ )
	_ENUM( EBILL_LOGIN_CHECK_BALANCE_ACK )

	_ENUM( EGS_EXCHANGE_CASH_NOT )


	_ENUM( EBILL_LOGIN_ACCOUNT_USER_OFFLINE_GN_ACCOUNT_CHECK_REQ )
	_ENUM( EBILL_LOGIN_ACCOUNT_USER_OFFLINE_GN_ACCOUNT_CHECK_ACK )


	_ENUM( EBILL_LOGIN_ACCOUNT_USER_OFFLINE_GN_EXCHANGE_REQ )
	_ENUM( EBILL_LOGIN_ACCOUNT_USER_OFFLINE_GN_EXCHANGE_ACK )

	_ENUM( EBILL_GN_CHANGE_GAME_CURRENCY_FAIL_NOT )
	_ENUM( EBILL_GN_TRANSACTION_CHECK_REQ )
	_ENUM( EBILL_GN_TRANSACTION_CHECK_ACK )

//#endif //SERV_COUNTRY_PH

//{{ 2013. 09. 23	최육사	일본 이벤트 중계DB작업
//#ifdef SERV_RELAY_DB_CONNECTION
	_ENUM( DBE_UPDATE_USER_INFO_TO_RELAY_DB_JP_EVENT_NOT )
	_ENUM( DBE_CHECK_REWARD_FROM_RELAY_DB_JP_EVENT_REQ )
	_ENUM( DBE_CHECK_REWARD_FROM_RELAY_DB_JP_EVENT_ACK )
	_ENUM( DBE_UPDATE_REWARD_COMPLETE_JP_EVENT_NOT )
	_ENUM( EBILL_REWARD_COUPON_JP_EVENT_REQ )
	_ENUM( EBILL_REWARD_COUPON_JP_EVENT_ACK )
//#endif SERV_RELAY_DB_CONNECTION

	//#ifdef SERV_WATCH_LOG
	_ENUM( E_LOCAL_LOG_WATCH_NOT )
	//#endif //SERV_WATCH_LOG
//}}

//#ifdef SERV_HALLOWEEN_PUMPKIN_FAIRY_PET
	_ENUM( DBE_CHANGE_PET_ID_REQ )
	_ENUM( DBE_CHANGE_PET_ID_ACK )
	_ENUM( DBE_CHANGE_PET_ID_LOG_NOT )
//#endif //SERV_HALLOWEEN_PUMPKIN_FAIRY_PET

//#ifdef SERV_STAGE_CLEAR_IN_SERVER
	_ENUM( ERM_DUNGEON_SUB_STAGE_CLEAR_REQ )
	_ENUM( ERM_DUNGEON_SUB_STAGE_CLEAR_ACK )
	_ENUM( ERM_SECRET_STAGE_LOAD_REQ )
	_ENUM( ERM_SECRET_STAGE_LOAD_ACK )
//#endif SERV_STAGE_CLEAR_IN_SERVER

//#ifdef SERV_PERIOD_PET
	_ENUM( DBE_RELEASE_PET_REQ )
	_ENUM( DBE_RELEASE_PET_ACK )
//#endif SERV_PERIOD_PET

	//#ifdef SERV_PAYLETTER_BILLING_ERROR_PACKET_LOG
	_ENUM( DBE_PAYLETTER_BILLING_ERROR_BUY_PACKET_NOT )
	_ENUM( DBE_PAYLETTER_BILLING_ERROR_GIFT_PACKET_NOT )
	_ENUM( DBE_PAYLETTER_BILLING_ERROR_COUPON_PACKET_NOT )
	//#endif //SERV_PAYLETTER_BILLING_ERROR_PACKET_LOG

	//#ifdef SERV_RECRUIT_EVENT_BASE
	_ENUM( DBE_USE_RECRUIT_TICKET_REQ )
	_ENUM( DBE_USE_RECRUIT_TICKET_ACK )
	_ENUM( DBE_REGISTER_RECRUITER_REQ )
	_ENUM( DBE_REGISTER_RECRUITER_ACK )
	_ENUM( ELG_REGISTER_RECRUITER_NOT )
	_ENUM( ELG_RECRUIT_RECRUITER_INFO_NOT )		// 추천인/피추천인의 상태변화를 등록된 피추천인/추천인에게 보내주는 패킷

	_ENUM( DBE_GET_RECRUIT_RECRUITER_LIST_REQ )	// 추천인/피추천인 리스트를 요청하는 패킷
	_ENUM( DBE_GET_RECRUIT_RECRUITER_LIST_ACK )	// 추천인/피추천인 리스트
	_ENUM( ELG_GET_RECRUIT_RECRUITER_LIST_REQ )	// ?
	_ENUM( ELG_GET_RECRUIT_RECRUITER_LIST_ACK )	// ?
	//#endif SERV_RECRUIT_EVENT_BASE

//#ifdef SERV_NEW_YEAR_EVENT_2014
	_ENUM( DBE_2013_EVENT_MISSION_COMPLETE_REQ )
	_ENUM( DBE_2013_EVENT_MISSION_COMPLETE_ACK )
	_ENUM( DBE_2014_EVENT_MISSION_COMPLETE_REQ )
	_ENUM( DBE_2014_EVENT_MISSION_COMPLETE_ACK )
//#endif SERV_NEW_YEAR_EVENT_2014

//#ifdef SERV_READY_TO_SOSUN_EVENT
	_ENUM( DBE_READY_TO_SOSUN_EVENT_REQ )
	_ENUM( DBE_READY_TO_SOSUN_EVENT_ACK )
//#endif SERV_READY_TO_SOSUN_EVENT

//#ifdef SERV_GLOBAL_MISSION_MANAGER
	_ENUM( EGB_UPDATE_GLOBAL_MISSION_INFO_NOT )
	_ENUM( EGB_GET_GLOBAL_MISSION_INFO_REQ )
	_ENUM( EGB_GET_GLOBAL_MISSION_INFO_ACK )
	_ENUM( EGB_UPDATE_GLOBAL_MISSION_START_TIME_NOT )
	_ENUM( DBE_UPDATE_GLOBAL_MISSION_INFO_REQ )
	_ENUM( DBE_GET_GLOBAL_MISSION_INFO_REQ )
	_ENUM( DBE_GET_GLOBAL_MISSION_INFO_ACK )
	_ENUM( EGB_GLOBAL_MISSION_UPDATE_NOT )
	_ENUM( DBE_INSERT_CONNECT_EVENT_REQ )
	_ENUM( DBE_REGIST_GLOBAL_MISSION_CLEAR_NOT )
//#endif SERV_GLOBAL_MISSION_MANAGER


//#ifdef SERV_UNLIMITED_SECOND_CHANGE_JOB	
	_ENUM( DBE_UNLIMITED_SECOND_CHANGE_JOB_NOT )
//#endif SERV_UNLIMITED_SECOND_CHANGE_JOB

//#ifdef SERV_CUBE_IN_ITEM_MAPPING_BY_DBTIME_SETTING
_ENUM( DBE_GET_CUBE_IN_ITEM_MAPPING_ONOFF_REQ )
_ENUM( DBE_GET_CUBE_IN_ITEM_MAPPING_ONOFF_ACK )
//#ifdef SERV_CUBE_IN_ITEM_MAPPING_BY_DBTIME_SETTING

#ifdef __NEVER_DEFINED_MACRO__
};
#undef _ENUM
#endif

