#ifdef __NEVER_DEFINED_MACRO__
#define _ENUM(VAL) VAL,
enum
{
#endif

	//_ENUM( ENUM_MY_EVENT_ID )

	//--------------------------------
	//#ifdef SERV_GLOBAL_AUTH
	_ENUM( ECH_SECURITY_AUTH_REQ )
	_ENUM( ECH_SECURITY_AUTH_ACK )

	_ENUM( ECH_SECURITY_INFO_NOT )	// 서버에서 보안관련 정보 변경 알려주기 위해 필요
	//#endif SERV_GLOBAL_AUTH
	//--------------------------------

	//--------------------------------
	//#ifdef SERV_GLOBAL_BILLING
	//{{ 2011. 02. 28	최육사	중국 자이언트 빌링
	_ENUM( EGS_USE_GIANT_CARD_REQ )
	_ENUM( EGS_USE_GIANT_CARD_ACK )

	_ENUM( EGS_EXCHANGE_CASH_REQ )
	_ENUM( EGS_EXCHANGE_CASH_ACK )

	//#ifdef SERV_SUPPORT_SEVERAL_CASH_TYPES
	_ENUM( EGS_BONUS_CASH_EVENT_NOT ) // 2011.10.04 lygan_조성욱 //보너스 캐쉬 증정 이벤트를 알리는 패킷
	//#endif //SERV_SUPPORT_SEVERAL_CASH_TYPES
	//}}

	_ENUM( EGS_BILL_PRODUCT_INFO_REQ )
	_ENUM( EGS_BILL_PRODUCT_INFO_ACK )

	_ENUM( EGS_BILL_INVENTORY_INQUIRY_REQ )
	_ENUM( EGS_BILL_INVENTORY_INQUIRY_ACK )

	_ENUM( EGS_BILL_GET_PURCHASED_CASH_ITEM_REQ )
	_ENUM( EGS_BILL_GET_PURCHASED_CASH_ITEM_ACK )

	//#ifdef SERV_GOLD_TICKET
	_ENUM( EGS_CHARGE_POINT_NOT )
	_ENUM( EGS_CHECK_GOLD_TICKET_KEY_NOT )	// 구조체 없이 int 값 하나만 씀
	//#endif SERV_GOLD_TICKET
	//#endif // SERV_GLOBAL_BILLING
	//--------------------------------

	//#ifdef SERV_NEW_PVPROOM_PROCESS
	_ENUM( EGS_CHANGE_PVP_ROOM_PUBLIC_REQ )
	_ENUM( EGS_CHANGE_PVP_ROOM_PUBLIC_ACK )
	_ENUM( EGS_CHANGE_PVP_ROOM_PUBLIC_NOT )
	_ENUM( EGS_CHANGE_PVP_ROOM_NAME_REQ )
	_ENUM( EGS_CHANGE_PVP_ROOM_NAME_ACK )
	_ENUM( EGS_CHANGE_PVP_ROOM_NAME_NOT )
	//#endif SERV_NEW_PVPROOM_PROCESS

	//ifdef SERV_DELETE_GUILD_ADD_CHEAT
	_ENUM( EGS_ADMIN_DELETE_GUILD_ADD_NOT )
	//endif

	//#ifdef SERV_DELETE_HENIR_RANKING
	_ENUM( EGS_ADMIN_DELETE_HENIR_RANKING_RANK_NOT )
	_ENUM( EGS_ADMIN_DELETE_HENIR_RANKING_NICKNAME_NOT )
	_ENUM( EGS_ADMIN_DELETE_HENIR_RANKING_UNITUID_NOT )
	//#endif

	//#ifdef SERV_NEW_UNIT_TRADE_LIMIT
	_ENUM( EGS_NEW_CHARACTER_TRADE_BLOCK_MSG_NOT )
	//#endif SERV_NEW_UNIT_TRADE_LIMIT

	//{{ 2011.05.05 lygan_조성욱 // 중국 전용 커뮤니티 탭 유저 정보보기 
	//#ifdef SERV_USER_WATCH_NEW
	_ENUM( EGS_USER_COMMUNITY_SURVEY_NEW_REQ )
	_ENUM( EGS_USER_COMMUNITY_SURVEY_NEW_ACK )
	//endif SERV_USER_WATCH_NEW
	//}}

	//#ifdef SERV_NPROTECT_CS_AUTH_30
	_ENUM( EGS_NPROTECT_CSAUTH3_CHECK_NOT )
	_ENUM( EGS_NPROTECT_CSAUTH3_RESPONE_NOT )
	_ENUM( EGS_NPROTECT_CSAUTH3_GAMEHACK_REPORT_NOT )
	//#endif SERV_NPROTECT_CS_AUTH_30

	//#ifdef SERV_PVP_REMATCH
	_ENUM( EGS_PVP_REMATCH_REQ )
	_ENUM( EGS_PVP_REMATCH_ACK )
	_ENUM( EGS_PVP_REMATCH_NOT )
	//#endif SERV_PVP_REMATCH

	//{{ 2012.02.20 조효진	캐릭터 삭제 프로세스 변경 (삭제 대기 기간 도입)
	//#ifdef SERV_UNIT_WAIT_DELETE
	_ENUM( EGS_RESTORE_UNIT_REQ )
	_ENUM( EGS_RESTORE_UNIT_ACK )
	_ENUM( EGS_FINAL_DELETE_UNIT_REQ )
	_ENUM( EGS_FINAL_DELETE_UNIT_ACK )
	//#endif SERV_UNIT_WAIT_DELETE
	//}}

	//{{ 2011.03.16   임규수 아바타 분해 시스템
	//#ifdef SERV_MULTI_RESOLVE
	_ENUM( EGS_RESOLVE_ITEM_AVATAR_REQ )
	_ENUM( EGS_RESOLVE_ITEM_AVATAR_ACK )
	//#endif SERV_MULTI_RESOLVE
	//}}

	//{{ 2011.05.04   임규수 아바타 합성 시스템
	//#ifdef SERV_SYNTHESIS_AVATAR
	_ENUM( EGS_SYNTHESIS_SOCKET_GROUPID_REQ )	// 구조체 없음
	_ENUM( EGS_SYNTHESIS_SOCKET_GROUPID_ACK )	

	_ENUM( EGS_SYNTHESIS_ITEM_REQ )
	_ENUM( EGS_SYNTHESIS_ITEM_ACK )
	//#endif SERV_SYNTHESIS_AVATAR

	//{{ 2011. 12. 09	박교현		서버군 리스트
	//#ifdef SERVER_GROUP_UI_ADVANCED
	_ENUM( ECH_GET_SERVERGROUP_LIST_REQ )
	_ENUM( ECH_GET_SERVERGROUP_LIST_ACK )
	_ENUM( ECH_GET_SERVERGROUP_LIST_NOT )
	//#endif SERVER_GROUP_UI_ADVANCED
	//}}

	//{{ 박교현 : [2010/03/09] //	중국 중독방지 방침미 시스템
	//#ifdef SERV_ANTI_ADDICTION_SYSTEM
	_ENUM( EGS_ANTI_ADDICTION_NOT )
	//#endif SERV_ANTI_ADDICTION_SYSTEM
	//}}
	//#ifdef SERV_EPAY_SYSTEM
	_ENUM( EGS_EPAY_INFO_NOT )
	//#endif //SERV_EPAY_SYSTEM

	//#ifdef SERV_IDENTITY_CONFIRM_POPUP_MESSAGE
	_ENUM( EGS_IDENTITY_CONFIRM_POPUP_MESSAGE_NOT)
	//#endif //SERV_IDENTITY_CONFIRM_POPUP_MESSAGE

	//#ifdef SERV_USE_XTRAP
	_ENUM ( EGS_XTRAP_REQ )
	_ENUM ( EGS_XTRAP_ACK )
	//#endif SERV_USE_XTRAP

	//#ifdef SERV_INVISIBLE_GM
	_ENUM( EGS_TOGGLE_INVISIBLE_REQ )
	_ENUM( EGS_TOGGLE_INVISIBLE_NOT )
	//#endif SERV_INVISIBLE_GM

	//#ifdef SERV_CATCH_HACKUSER_INFO
	_ENUM( EGS_CATCH_HACKUSER_INFO_NOT )
	//#endif SERV_CATCH_HACKUSER_INFO

	//#ifdef SERV_SHARING_BANK_TEST
	_ENUM( EGS_GET_SHARE_BANK_REQ )
	_ENUM( EGS_GET_SHARE_BANK_ACK )
	//_ENUM( EGS_CLOSE_BANK_NOT )		// -- 필요 없는 기능이다.
	_ENUM( EGS_UPDATE_ITEM_POSITION_NOT )
	//#endif SERV_SHARING_BANK_TEST
	//#ifdef SERV_SHARE_BANK_WAIT_SERVER_RECIEVE
	_ENUM( EGS_SHARE_BANK_UPDATE_OK_NOT )
	//#endif SERV_SHARE_BANK_WAIT_SERVER_RECIEVE
	//#ifdef SERV_SHARING_BANK_QUEST_CASH
	_ENUM( EGS_SHARING_BACK_OPEN_NOT )
	//#endif SERV_SHARING_BANK_QUEST_CASH

	//#ifdef SERV_ADVERTISEMENT_EVENT
	_ENUM( EGS_ADVERTISEMENT_EVENT_INFO_NOT )
	_ENUM( EGS_GET_ADVERTISEMENT_EVENT_REQ )
	_ENUM( EGS_GET_ADVERTISEMENT_EVENT_ACK )
	//#endif SERV_ADVERTISEMENT_EVENT

	//#ifdef SERV_ADD_WARP_BUTTON
	_ENUM( EGS_WARP_BY_BUTTON_REQ )
	_ENUM( EGS_WARP_BY_BUTTON_ACK )
	//#endif // SERV_ADD_WARP_BUTTON

	//#ifdef SERV_NEW_EVENT_TYPES
	_ENUM( EGS_UPDATE_MAX_LEVEL_NOT )
	_ENUM( EGS_UPDATE_DUNGEON_STATUS_NOT )
	//#endif SERV_NEW_EVENT_TYPES

	//#ifdef SERV_CODE_EVENT
	_ENUM( EGS_UPDATE_CODE_EVENT_NOT )
	//#endif SERV_CODE_EVENT

	//#ifdef SERV_ADD_WARP_BUTTON
	_ENUM( EGS_UPDATE_WARP_VIP_NOT )
	//#endif // SERV_ADD_WARP_BUTTON

	//#ifdef SERV_CLIENT_DIRECT_CONNECT_AUTH_PCBANG
	_ENUM( EGS_CLIENT_DIRECT_CONNECT_AUTH_PCBAG_REQ )
	_ENUM( EGS_CLIENT_DIRECT_CONNECT_AUTH_PCBAG_ACK )
	//#endif //SERV_CLIENT_DIRECT_CONNECT_AUTH_PCBANG

	//#ifdef SERV_DEVELOPER_RANDOM_OPEN_ITEM_LOG
	_ENUM( EGS_OPEN_RANDOM_ITEM_DEVELOPER_REQ )
	_ENUM( EGS_OPEN_RANDOM_ITEM_DEVELOPER_ACK )
	//#endif//SERV_DEVELOPER_RANDOM_OPEN_ITEM_LOG

	//#ifdef SERV_CLIENT_PORT_CHANGE_REQUEST_LOG
	_ENUM( EGS_CLIENT_POPRT_CHANGE_REQUEST_INFO_NOT )
	//#endif //SERV_CLIENT_PORT_CHANGE_REQUEST_LOG
	
	//#ifdef SERV_KOM_FILE_CHECK_ADVANCED
	_ENUM( EGS_KOM_FILE_CHECK_LOG_REQ )
	_ENUM( EGS_KOM_FILE_CHECK_LOG_ACK )
	//#endif SERV_KOM_FILE_CHECK_ADVANCED

	//#ifdef SERV_CHECK_TIME_QUEST
	_ENUM( EGS_EVENT_QUEST_CHECK_FOR_ADMIN_NOT )
	//#endif // SERV_CHECK_TIME_QUEST

	//{{ 2012. 01. 20  박진웅 스킬사용 퀘스트
	//#ifdef SERV_SKILL_USE_SUBQUEST
	_ENUM( EGS_SKILL_USE_REQ )
	//#endif SERV_SKILL_USE_SUBQUEST
	//}}
	//김준환 서버시간 받아오기
	//#ifdef SERV_SERVER_TIME_GET
	_ENUM( ECH_GET_SERVER_TIME_REQ )
	_ENUM( ECH_GET_SERVER_TIME_ACK )
	//#endif SERV_SERVER_TIME_GET

	//#ifdef SERV_POINT_COUNT_SYSTEM
	_ENUM( EGS_QUEST_POINT_COUNT_SYSTEM_NOT )	// 2013.04.09 lygan_조성욱 // 포인트가 갱신되면 subquest에서 포인트를 사용하는 퀘스트 전부를 갱신해줘야 하는 용도
	//#endif //SERV_POINT_COUNT_SYSTEM	

//#ifdef SERV_STAGE_CLEAR_IN_SERVER
	_ENUM( EGS_DUNGEON_SUB_STAGE_CLEAR_REQ )
	_ENUM( EGS_DUNGEON_SUB_STAGE_CLEAR_ACK )
	_ENUM( EGS_SECRET_STAGE_LOAD_REQ )
//#endif SERV_STAGE_CLEAR_IN_SERVER
	
	//#ifdef SERV_COUNTRY_PH
	_ENUM( EGS_EXCHANGE_CASH_CLIENT_NOT )
	//#endif //SERV_COUNTRY_PH

	//#ifdef SERV_GATE_OF_DARKNESS_SUPPORT_EVENT
	_ENUM( EGS_GOD_SUPPORT_EVENT_TIME_NOT )
	//#endif SERV_GATE_OF_DARKNESS_SUPPORT_EVENT

//#ifdef SERV_HALLOWEEN_PUMPKIN_FAIRY_PET
	_ENUM( EGS_CHANGE_PET_ID_NOT )
//#endif //SERV_HALLOWEEN_PUMPKIN_FAIRY_PET

//#ifdef SERV_CHINA_SPIRIT_EVENT
	_ENUM( EGS_USE_SPIRIT_REWARD_REQ )
	_ENUM( EGS_USE_SPIRIT_REWARD_ACK )
//#endif //SERV_CHINA_SPIRIT_EVENT

//#ifdef SERV_PERIOD_PET
	_ENUM( EGS_RELEASE_PET_ACK )
	_ENUM( EGS_RELEASE_PET_NOT )
//#endif SERV_PERIOD_PET

//#ifdef SERV_BLOCK_LIST_SHOW_DISCONNECT_REASON
	_ENUM( EGS_SHOW_DISCONNECT_REASON_NOT )
//#endif SERV_BLOCK_LIST_SHOW_DISCONNECT_REASON

//#ifdef SERV_CUBE_IN_ITEM_MAPPING
	_ENUM( EGS_CUBE_IN_ITEM_MAPPING_NOT )
//#endif //SERV_CUBE_IN_ITEM_MAPPING

	//#ifdef SERV_RECRUIT_EVENT_BASE
	_ENUM( EGS_USE_RECRUIT_TICKET_REQ )
	_ENUM( EGS_USE_RECRUIT_TICKET_ACK )
	_ENUM( EGS_REGISTER_RECRUITER_REQ )
	_ENUM( EGS_REGISTER_RECRUITER_ACK )
	_ENUM( EGS_REGISTER_RECRUITER_NOT )
	_ENUM( EGS_RECRUIT_RECRUITER_INFO_NOT )		// 추천인/피추천인의 상태변화를 등록된 피추천인/추천인에게 보내주는 패킷

	_ENUM( EGS_GET_RECRUIT_RECRUITER_LIST_REQ )	// 추천인/피추천인 리스트를 요청하는 패킷
	_ENUM( EGS_GET_RECRUIT_RECRUITER_LIST_ACK )	// 추천인/피추천인 리스트
	//#endif SERV_RECRUIT_EVENT_BASE


//#ifdef SERV_GLOBAL_MISSION_MANAGER
	_ENUM( EGS_GLOBAL_MISSION_UPDATE_NOT )
//#endif SERV_GLOBAL_MISSION_MANAGER

//#ifdef SERV_NEW_YEAR_EVENT_2014
	_ENUM( EGS_2013_EVENT_MISSION_COMPLETE_REQ )
	_ENUM( EGS_2013_EVENT_MISSION_COMPLETE_ACK )
	_ENUM( EGS_2014_EVENT_MISSION_COMPLETE_REQ )
	_ENUM( EGS_2014_EVENT_MISSION_COMPLETE_ACK )
//#endif SERV_NEW_YEAR_EVENT_2014

//#ifdef SERV_UNLIMITED_SECOND_CHANGE_JOB
	_ENUM( EGS_UNLIMITED_SECOND_CHANGE_JOB_NOT )
//#endif SERV_UNLIMITED_SECOND_CHANGE_JOB


//#ifdef SERV_READY_TO_SOSUN_EVENT
	_ENUM( EGS_READY_TO_SOSUN_EVENT_REQ )
	_ENUM( EGS_READY_TO_SOSUN_EVENT_ACK )
//#endif SERV_READY_TO_SOSUN_EVENT

#ifdef __NEVER_DEFINED_MACRO__
};
#undef _ENUM
#endif
