_ENUM( A_CONNECT_CHANNEL_SERVER )
_ENUM( A_GET_CHANNEL_LIST )

_ENUM( A_CONNECT_GAME_SERVER )
_ENUM( A_MAKE_ACCOUNT )
_ENUM( A_VERIFY )
_ENUM( A_SELECT_SERVER )
_ENUM( A_SELECT_UNIT )
_ENUM( A_CREATE_UNIT )
_ENUM( A_DELETE_UNIT )

_ENUM( A_STATE_CHANGE_SERVER_SELECT )
_ENUM( A_STATE_CHANGE_FIELD )
_ENUM( A_FIELD_MOVE )
_ENUM( A_FIELD_STAND )
_ENUM( A_FIELD_CHAT )
_ENUM( A_CREATE_PARTY )
_ENUM( A_JOIN_PARTY )

_ENUM( A_LEAVE_PARTY )
_ENUM( A_PARTY_CHAT )

_ENUM( A_ENTER_NPC_HOUSE )
_ENUM( A_ENTER_EQUIP_SHOP )

_ENUM( A_OPEN_PVP_ROOM_LIST )
_ENUM( A_ROOM_LIST )

_ENUM( A_JOIN_SQUARE )
_ENUM( A_CREATE_ROOM )
_ENUM( A_CREATE_TC_ROOM )
_ENUM( A_JOIN_ROOM )
_ENUM( A_QUICK_JOIN_ROOM )

_ENUM( A_SQUARE_UNIT_SYNC )
_ENUM( A_LEAVE_ROOM )
_ENUM( A_CHAT )
_ENUM( A_CHANGE_TEAM )
_ENUM( A_CHANGE_DIFFICULTY )
_ENUM( A_SEARCH_UNIT )

_ENUM( A_CLIENT_QUIT )

_ENUM( A_EXIT )

_ENUM( A_SENTINEL )