/* soapClient.c
   Generated by gSOAP 2.8.0 from gf_soap.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.0 2011-05-06 08:01:22 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getLoginsByUsernameFromGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *userName, char *days, char *startDate, char *endDate, struct ns1__getLoginsByUsernameFromGameResponse *_param_1)
{	struct ns1__getLoginsByUsernameFromGame soap_tmp_ns1__getLoginsByUsernameFromGame;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__getLoginsByUsernameFromGame.userName = userName;
	soap_tmp_ns1__getLoginsByUsernameFromGame.days = days;
	soap_tmp_ns1__getLoginsByUsernameFromGame.startDate = startDate;
	soap_tmp_ns1__getLoginsByUsernameFromGame.endDate = endDate;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__getLoginsByUsernameFromGame(soap, &soap_tmp_ns1__getLoginsByUsernameFromGame);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getLoginsByUsernameFromGame(soap, &soap_tmp_ns1__getLoginsByUsernameFromGame, "ns1:getLoginsByUsernameFromGame", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getLoginsByUsernameFromGame(soap, &soap_tmp_ns1__getLoginsByUsernameFromGame, "ns1:getLoginsByUsernameFromGame", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_1)
		return soap_closesock(soap);
	soap_default_ns1__getLoginsByUsernameFromGameResponse(soap, _param_1);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__getLoginsByUsernameFromGameResponse(soap, _param_1, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getLoginsByIpFromGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *ipaddress, char *days, char *startDate, char *endDate, struct ns1__getLoginsByIpFromGameResponse *_param_2)
{	struct ns1__getLoginsByIpFromGame soap_tmp_ns1__getLoginsByIpFromGame;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__getLoginsByIpFromGame.ipaddress = ipaddress;
	soap_tmp_ns1__getLoginsByIpFromGame.days = days;
	soap_tmp_ns1__getLoginsByIpFromGame.startDate = startDate;
	soap_tmp_ns1__getLoginsByIpFromGame.endDate = endDate;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__getLoginsByIpFromGame(soap, &soap_tmp_ns1__getLoginsByIpFromGame);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getLoginsByIpFromGame(soap, &soap_tmp_ns1__getLoginsByIpFromGame, "ns1:getLoginsByIpFromGame", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getLoginsByIpFromGame(soap, &soap_tmp_ns1__getLoginsByIpFromGame, "ns1:getLoginsByIpFromGame", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_2)
		return soap_closesock(soap);
	soap_default_ns1__getLoginsByIpFromGameResponse(soap, _param_2);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__getLoginsByIpFromGameResponse(soap, _param_2, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getCcuDataFromGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int worldId, struct ns1__getCcuDataFromGameResponse *_param_3)
{	struct ns1__getCcuDataFromGame soap_tmp_ns1__getCcuDataFromGame;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__getCcuDataFromGame.worldId = worldId;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__getCcuDataFromGame(soap, &soap_tmp_ns1__getCcuDataFromGame);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getCcuDataFromGame(soap, &soap_tmp_ns1__getCcuDataFromGame, "ns1:getCcuDataFromGame", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getCcuDataFromGame(soap, &soap_tmp_ns1__getCcuDataFromGame, "ns1:getCcuDataFromGame", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_3)
		return soap_closesock(soap);
	soap_default_ns1__getCcuDataFromGameResponse(soap, _param_3);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__getCcuDataFromGameResponse(soap, _param_3, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getHighscoreFromGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int worldId, char *charType, char *rankType, int startValue, int limit, struct ns1__getHighscoreFromGameResponse *_param_4)
{	struct ns1__getHighscoreFromGame soap_tmp_ns1__getHighscoreFromGame;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__getHighscoreFromGame.ServerId = ServerId;
	soap_tmp_ns1__getHighscoreFromGame.worldId = worldId;
	soap_tmp_ns1__getHighscoreFromGame.charType = charType;
	soap_tmp_ns1__getHighscoreFromGame.rankType = rankType;
	soap_tmp_ns1__getHighscoreFromGame.startValue = startValue;
	soap_tmp_ns1__getHighscoreFromGame.limit = limit;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__getHighscoreFromGame(soap, &soap_tmp_ns1__getHighscoreFromGame);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getHighscoreFromGame(soap, &soap_tmp_ns1__getHighscoreFromGame, "ns1:getHighscoreFromGame", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getHighscoreFromGame(soap, &soap_tmp_ns1__getHighscoreFromGame, "ns1:getHighscoreFromGame", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_4)
		return soap_closesock(soap);
	soap_default_ns1__getHighscoreFromGameResponse(soap, _param_4);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__getHighscoreFromGameResponse(soap, _param_4, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getCharacterDetailsOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int pagesize, int lastsize, char *value, int flag, struct ns1__getCharacterDetailsOnGameResponse *_param_5)
{	struct ns1__getCharacterDetailsOnGame soap_tmp_ns1__getCharacterDetailsOnGame;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__getCharacterDetailsOnGame.ServerId = ServerId;
	soap_tmp_ns1__getCharacterDetailsOnGame.pagesize = pagesize;
	soap_tmp_ns1__getCharacterDetailsOnGame.lastsize = lastsize;
	soap_tmp_ns1__getCharacterDetailsOnGame.value = value;
	soap_tmp_ns1__getCharacterDetailsOnGame.flag = flag;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__getCharacterDetailsOnGame(soap, &soap_tmp_ns1__getCharacterDetailsOnGame);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getCharacterDetailsOnGame(soap, &soap_tmp_ns1__getCharacterDetailsOnGame, "ns1:getCharacterDetailsOnGame", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getCharacterDetailsOnGame(soap, &soap_tmp_ns1__getCharacterDetailsOnGame, "ns1:getCharacterDetailsOnGame", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_5)
		return soap_closesock(soap);
	soap_default_ns1__getCharacterDetailsOnGameResponse(soap, _param_5);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__getCharacterDetailsOnGameResponse(soap, _param_5, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getCharacterQuestsCurrentOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int pagesize, int lastsize, char *nickName, struct ns1__getCharacterQuestsCurrentOnGameResponse *_param_6)
{	struct ns1__getCharacterQuestsCurrentOnGame soap_tmp_ns1__getCharacterQuestsCurrentOnGame;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__getCharacterQuestsCurrentOnGame.ServerId = ServerId;
	soap_tmp_ns1__getCharacterQuestsCurrentOnGame.pagesize = pagesize;
	soap_tmp_ns1__getCharacterQuestsCurrentOnGame.lastsize = lastsize;
	soap_tmp_ns1__getCharacterQuestsCurrentOnGame.nickName = nickName;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__getCharacterQuestsCurrentOnGame(soap, &soap_tmp_ns1__getCharacterQuestsCurrentOnGame);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getCharacterQuestsCurrentOnGame(soap, &soap_tmp_ns1__getCharacterQuestsCurrentOnGame, "ns1:getCharacterQuestsCurrentOnGame", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getCharacterQuestsCurrentOnGame(soap, &soap_tmp_ns1__getCharacterQuestsCurrentOnGame, "ns1:getCharacterQuestsCurrentOnGame", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_6)
		return soap_closesock(soap);
	soap_default_ns1__getCharacterQuestsCurrentOnGameResponse(soap, _param_6);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__getCharacterQuestsCurrentOnGameResponse(soap, _param_6, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getCharacterQuestsCompleteOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int pagesize, int lastsize, char *nickName, struct ns1__getCharacterQuestsCompleteOnGameResponse *_param_7)
{	struct ns1__getCharacterQuestsCompleteOnGame soap_tmp_ns1__getCharacterQuestsCompleteOnGame;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__getCharacterQuestsCompleteOnGame.ServerId = ServerId;
	soap_tmp_ns1__getCharacterQuestsCompleteOnGame.pagesize = pagesize;
	soap_tmp_ns1__getCharacterQuestsCompleteOnGame.lastsize = lastsize;
	soap_tmp_ns1__getCharacterQuestsCompleteOnGame.nickName = nickName;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__getCharacterQuestsCompleteOnGame(soap, &soap_tmp_ns1__getCharacterQuestsCompleteOnGame);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getCharacterQuestsCompleteOnGame(soap, &soap_tmp_ns1__getCharacterQuestsCompleteOnGame, "ns1:getCharacterQuestsCompleteOnGame", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getCharacterQuestsCompleteOnGame(soap, &soap_tmp_ns1__getCharacterQuestsCompleteOnGame, "ns1:getCharacterQuestsCompleteOnGame", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_7)
		return soap_closesock(soap);
	soap_default_ns1__getCharacterQuestsCompleteOnGameResponse(soap, _param_7);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__getCharacterQuestsCompleteOnGameResponse(soap, _param_7, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getCharacterPostsOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int pagesize, int lastsize, char *userUID, struct ns1__getCharacterPostsOnGameResponse *_param_8)
{	struct ns1__getCharacterPostsOnGame soap_tmp_ns1__getCharacterPostsOnGame;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__getCharacterPostsOnGame.ServerId = ServerId;
	soap_tmp_ns1__getCharacterPostsOnGame.pagesize = pagesize;
	soap_tmp_ns1__getCharacterPostsOnGame.lastsize = lastsize;
	soap_tmp_ns1__getCharacterPostsOnGame.userUID = userUID;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__getCharacterPostsOnGame(soap, &soap_tmp_ns1__getCharacterPostsOnGame);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getCharacterPostsOnGame(soap, &soap_tmp_ns1__getCharacterPostsOnGame, "ns1:getCharacterPostsOnGame", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getCharacterPostsOnGame(soap, &soap_tmp_ns1__getCharacterPostsOnGame, "ns1:getCharacterPostsOnGame", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_8)
		return soap_closesock(soap);
	soap_default_ns1__getCharacterPostsOnGameResponse(soap, _param_8);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__getCharacterPostsOnGameResponse(soap, _param_8, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getAllianceDetailsOnGameById(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int pagesize, int lastsize, int GuildNo, struct ns1__getAllianceDetailsOnGameByIdResponse *_param_9)
{	struct ns1__getAllianceDetailsOnGameById soap_tmp_ns1__getAllianceDetailsOnGameById;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__getAllianceDetailsOnGameById.ServerId = ServerId;
	soap_tmp_ns1__getAllianceDetailsOnGameById.pagesize = pagesize;
	soap_tmp_ns1__getAllianceDetailsOnGameById.lastsize = lastsize;
	soap_tmp_ns1__getAllianceDetailsOnGameById.GuildNo = GuildNo;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__getAllianceDetailsOnGameById(soap, &soap_tmp_ns1__getAllianceDetailsOnGameById);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getAllianceDetailsOnGameById(soap, &soap_tmp_ns1__getAllianceDetailsOnGameById, "ns1:getAllianceDetailsOnGameById", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getAllianceDetailsOnGameById(soap, &soap_tmp_ns1__getAllianceDetailsOnGameById, "ns1:getAllianceDetailsOnGameById", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_9)
		return soap_closesock(soap);
	soap_default_ns1__getAllianceDetailsOnGameByIdResponse(soap, _param_9);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__getAllianceDetailsOnGameByIdResponse(soap, _param_9, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getAllianceDetailsOnGameByName(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int pagesize, int lastsize, char *guildName, struct ns1__getAllianceDetailsOnGameByNameResponse *_param_10)
{	struct ns1__getAllianceDetailsOnGameByName soap_tmp_ns1__getAllianceDetailsOnGameByName;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__getAllianceDetailsOnGameByName.ServerId = ServerId;
	soap_tmp_ns1__getAllianceDetailsOnGameByName.pagesize = pagesize;
	soap_tmp_ns1__getAllianceDetailsOnGameByName.lastsize = lastsize;
	soap_tmp_ns1__getAllianceDetailsOnGameByName.guildName = guildName;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__getAllianceDetailsOnGameByName(soap, &soap_tmp_ns1__getAllianceDetailsOnGameByName);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getAllianceDetailsOnGameByName(soap, &soap_tmp_ns1__getAllianceDetailsOnGameByName, "ns1:getAllianceDetailsOnGameByName", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getAllianceDetailsOnGameByName(soap, &soap_tmp_ns1__getAllianceDetailsOnGameByName, "ns1:getAllianceDetailsOnGameByName", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_10)
		return soap_closesock(soap);
	soap_default_ns1__getAllianceDetailsOnGameByNameResponse(soap, _param_10);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__getAllianceDetailsOnGameByNameResponse(soap, _param_10, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getAllianceMembersOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int pagesize, int lastsize, int GuildNo, struct ns1__getAllianceMembersOnGameResponse *_param_11)
{	struct ns1__getAllianceMembersOnGame soap_tmp_ns1__getAllianceMembersOnGame;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__getAllianceMembersOnGame.ServerId = ServerId;
	soap_tmp_ns1__getAllianceMembersOnGame.pagesize = pagesize;
	soap_tmp_ns1__getAllianceMembersOnGame.lastsize = lastsize;
	soap_tmp_ns1__getAllianceMembersOnGame.GuildNo = GuildNo;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__getAllianceMembersOnGame(soap, &soap_tmp_ns1__getAllianceMembersOnGame);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getAllianceMembersOnGame(soap, &soap_tmp_ns1__getAllianceMembersOnGame, "ns1:getAllianceMembersOnGame", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getAllianceMembersOnGame(soap, &soap_tmp_ns1__getAllianceMembersOnGame, "ns1:getAllianceMembersOnGame", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_11)
		return soap_closesock(soap);
	soap_default_ns1__getAllianceMembersOnGameResponse(soap, _param_11);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__getAllianceMembersOnGameResponse(soap, _param_11, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getCharacterListByAccountFromGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int pagesize, int lastsize, char *userName, struct ns1__getCharacterListByAccountFromGameResponse *_param_12)
{	struct ns1__getCharacterListByAccountFromGame soap_tmp_ns1__getCharacterListByAccountFromGame;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__getCharacterListByAccountFromGame.pagesize = pagesize;
	soap_tmp_ns1__getCharacterListByAccountFromGame.lastsize = lastsize;
	soap_tmp_ns1__getCharacterListByAccountFromGame.userName = userName;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__getCharacterListByAccountFromGame(soap, &soap_tmp_ns1__getCharacterListByAccountFromGame);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getCharacterListByAccountFromGame(soap, &soap_tmp_ns1__getCharacterListByAccountFromGame, "ns1:getCharacterListByAccountFromGame", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getCharacterListByAccountFromGame(soap, &soap_tmp_ns1__getCharacterListByAccountFromGame, "ns1:getCharacterListByAccountFromGame", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_12)
		return soap_closesock(soap);
	soap_default_ns1__getCharacterListByAccountFromGameResponse(soap, _param_12);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__getCharacterListByAccountFromGameResponse(soap, _param_12, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getDeletedCharacterListFromGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int pagesize, int lastsize, struct ns1__getDeletedCharacterListFromGameResponse *_param_13)
{	struct ns1__getDeletedCharacterListFromGame soap_tmp_ns1__getDeletedCharacterListFromGame;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__getDeletedCharacterListFromGame.ServerId = ServerId;
	soap_tmp_ns1__getDeletedCharacterListFromGame.pagesize = pagesize;
	soap_tmp_ns1__getDeletedCharacterListFromGame.lastsize = lastsize;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__getDeletedCharacterListFromGame(soap, &soap_tmp_ns1__getDeletedCharacterListFromGame);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getDeletedCharacterListFromGame(soap, &soap_tmp_ns1__getDeletedCharacterListFromGame, "ns1:getDeletedCharacterListFromGame", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getDeletedCharacterListFromGame(soap, &soap_tmp_ns1__getDeletedCharacterListFromGame, "ns1:getDeletedCharacterListFromGame", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_13)
		return soap_closesock(soap);
	soap_default_ns1__getDeletedCharacterListFromGameResponse(soap, _param_13);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__getDeletedCharacterListFromGameResponse(soap, _param_13, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getCharacterListByLevelFromGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int pagesize, int lastsize, int levelMin, int levelMax, struct ns1__getCharacterListByLevelFromGameResponse *_param_14)
{	struct ns1__getCharacterListByLevelFromGame soap_tmp_ns1__getCharacterListByLevelFromGame;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__getCharacterListByLevelFromGame.ServerId = ServerId;
	soap_tmp_ns1__getCharacterListByLevelFromGame.pagesize = pagesize;
	soap_tmp_ns1__getCharacterListByLevelFromGame.lastsize = lastsize;
	soap_tmp_ns1__getCharacterListByLevelFromGame.levelMin = levelMin;
	soap_tmp_ns1__getCharacterListByLevelFromGame.levelMax = levelMax;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__getCharacterListByLevelFromGame(soap, &soap_tmp_ns1__getCharacterListByLevelFromGame);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getCharacterListByLevelFromGame(soap, &soap_tmp_ns1__getCharacterListByLevelFromGame, "ns1:getCharacterListByLevelFromGame", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getCharacterListByLevelFromGame(soap, &soap_tmp_ns1__getCharacterListByLevelFromGame, "ns1:getCharacterListByLevelFromGame", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_14)
		return soap_closesock(soap);
	soap_default_ns1__getCharacterListByLevelFromGameResponse(soap, _param_14);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__getCharacterListByLevelFromGameResponse(soap, _param_14, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getUserAuthorityOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int UserID, int *getUserAuthorityOnGameReturn)
{	struct ns1__getUserAuthorityOnGame soap_tmp_ns1__getUserAuthorityOnGame;
	struct ns1__getUserAuthorityOnGameResponse *soap_tmp_ns1__getUserAuthorityOnGameResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__getUserAuthorityOnGame.UserID = UserID;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__getUserAuthorityOnGame(soap, &soap_tmp_ns1__getUserAuthorityOnGame);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getUserAuthorityOnGame(soap, &soap_tmp_ns1__getUserAuthorityOnGame, "ns1:getUserAuthorityOnGame", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getUserAuthorityOnGame(soap, &soap_tmp_ns1__getUserAuthorityOnGame, "ns1:getUserAuthorityOnGame", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!getUserAuthorityOnGameReturn)
		return soap_closesock(soap);
	soap_default_int(soap, getUserAuthorityOnGameReturn);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__getUserAuthorityOnGameResponse = soap_get_ns1__getUserAuthorityOnGameResponse(soap, NULL, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (getUserAuthorityOnGameReturn && soap_tmp_ns1__getUserAuthorityOnGameResponse->getUserAuthorityOnGameReturn)
		*getUserAuthorityOnGameReturn = *soap_tmp_ns1__getUserAuthorityOnGameResponse->getUserAuthorityOnGameReturn;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getItemsByCharacterOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerID, int CharacterID, struct ns1__getItemsByCharacterOnGameResponse *_param_15)
{	struct ns1__getItemsByCharacterOnGame soap_tmp_ns1__getItemsByCharacterOnGame;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__getItemsByCharacterOnGame.ServerID = ServerID;
	soap_tmp_ns1__getItemsByCharacterOnGame.CharacterID = CharacterID;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__getItemsByCharacterOnGame(soap, &soap_tmp_ns1__getItemsByCharacterOnGame);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getItemsByCharacterOnGame(soap, &soap_tmp_ns1__getItemsByCharacterOnGame, "ns1:getItemsByCharacterOnGame", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getItemsByCharacterOnGame(soap, &soap_tmp_ns1__getItemsByCharacterOnGame, "ns1:getItemsByCharacterOnGame", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_15)
		return soap_closesock(soap);
	soap_default_ns1__getItemsByCharacterOnGameResponse(soap, _param_15);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__getItemsByCharacterOnGameResponse(soap, _param_15, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getItemDetailsOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerID, int ItemID, struct ns1__getItemDetailsOnGameResponse *_param_16)
{	struct ns1__getItemDetailsOnGame soap_tmp_ns1__getItemDetailsOnGame;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__getItemDetailsOnGame.ServerID = ServerID;
	soap_tmp_ns1__getItemDetailsOnGame.ItemID = ItemID;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__getItemDetailsOnGame(soap, &soap_tmp_ns1__getItemDetailsOnGame);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getItemDetailsOnGame(soap, &soap_tmp_ns1__getItemDetailsOnGame, "ns1:getItemDetailsOnGame", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getItemDetailsOnGame(soap, &soap_tmp_ns1__getItemDetailsOnGame, "ns1:getItemDetailsOnGame", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_16)
		return soap_closesock(soap);
	soap_default_ns1__getItemDetailsOnGameResponse(soap, _param_16);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__getItemDetailsOnGameResponse(soap, _param_16, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getQuestListOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, struct ns1__getQuestListOnGameResponse *_param_17)
{	struct ns1__getQuestListOnGame soap_tmp_ns1__getQuestListOnGame;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__getQuestListOnGame.ServerId = ServerId;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__getQuestListOnGame(soap, &soap_tmp_ns1__getQuestListOnGame);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getQuestListOnGame(soap, &soap_tmp_ns1__getQuestListOnGame, "ns1:getQuestListOnGame", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getQuestListOnGame(soap, &soap_tmp_ns1__getQuestListOnGame, "ns1:getQuestListOnGame", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_17)
		return soap_closesock(soap);
	soap_default_ns1__getQuestListOnGameResponse(soap, _param_17);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__getQuestListOnGameResponse(soap, _param_17, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getItemListOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, struct ns1__getItemListOnGameResponse *_param_18)
{	struct ns1__getItemListOnGame soap_tmp_ns1__getItemListOnGame;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__getItemListOnGame.ServerId = ServerId;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__getItemListOnGame(soap, &soap_tmp_ns1__getItemListOnGame);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getItemListOnGame(soap, &soap_tmp_ns1__getItemListOnGame, "ns1:getItemListOnGame", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getItemListOnGame(soap, &soap_tmp_ns1__getItemListOnGame, "ns1:getItemListOnGame", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_18)
		return soap_closesock(soap);
	soap_default_ns1__getItemListOnGameResponse(soap, _param_18);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__getItemListOnGameResponse(soap, _param_18, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__setCharacterDetailsOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerID, int iUnitUID, int iEXP, int iGamePoint, int iSPoint, int iStoneCnt, int iSpirit, int iVsPoint, int iVsPointMax, int *setCharacterDetailsOnGameReturn)
{	struct ns1__setCharacterDetailsOnGame soap_tmp_ns1__setCharacterDetailsOnGame;
	struct ns1__setCharacterDetailsOnGameResponse *soap_tmp_ns1__setCharacterDetailsOnGameResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__setCharacterDetailsOnGame.ServerID = ServerID;
	soap_tmp_ns1__setCharacterDetailsOnGame.iUnitUID = iUnitUID;
	soap_tmp_ns1__setCharacterDetailsOnGame.iEXP = iEXP;
	soap_tmp_ns1__setCharacterDetailsOnGame.iGamePoint = iGamePoint;
	soap_tmp_ns1__setCharacterDetailsOnGame.iSPoint = iSPoint;
	soap_tmp_ns1__setCharacterDetailsOnGame.iStoneCnt = iStoneCnt;
	soap_tmp_ns1__setCharacterDetailsOnGame.iSpirit = iSpirit;
	soap_tmp_ns1__setCharacterDetailsOnGame.iVsPoint = iVsPoint;
	soap_tmp_ns1__setCharacterDetailsOnGame.iVsPointMax = iVsPointMax;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__setCharacterDetailsOnGame(soap, &soap_tmp_ns1__setCharacterDetailsOnGame);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__setCharacterDetailsOnGame(soap, &soap_tmp_ns1__setCharacterDetailsOnGame, "ns1:setCharacterDetailsOnGame", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__setCharacterDetailsOnGame(soap, &soap_tmp_ns1__setCharacterDetailsOnGame, "ns1:setCharacterDetailsOnGame", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!setCharacterDetailsOnGameReturn)
		return soap_closesock(soap);
	soap_default_int(soap, setCharacterDetailsOnGameReturn);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__setCharacterDetailsOnGameResponse = soap_get_ns1__setCharacterDetailsOnGameResponse(soap, NULL, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (setCharacterDetailsOnGameReturn && soap_tmp_ns1__setCharacterDetailsOnGameResponse->setCharacterDetailsOnGameReturn)
		*setCharacterDetailsOnGameReturn = *soap_tmp_ns1__setCharacterDetailsOnGameResponse->setCharacterDetailsOnGameReturn;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__setUserAuthorityOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *Username, char *Authority, int *setUserAuthorityOnGameReturn)
{	struct ns1__setUserAuthorityOnGame soap_tmp_ns1__setUserAuthorityOnGame;
	struct ns1__setUserAuthorityOnGameResponse *soap_tmp_ns1__setUserAuthorityOnGameResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__setUserAuthorityOnGame.Username = Username;
	soap_tmp_ns1__setUserAuthorityOnGame.Authority = Authority;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__setUserAuthorityOnGame(soap, &soap_tmp_ns1__setUserAuthorityOnGame);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__setUserAuthorityOnGame(soap, &soap_tmp_ns1__setUserAuthorityOnGame, "ns1:setUserAuthorityOnGame", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__setUserAuthorityOnGame(soap, &soap_tmp_ns1__setUserAuthorityOnGame, "ns1:setUserAuthorityOnGame", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!setUserAuthorityOnGameReturn)
		return soap_closesock(soap);
	soap_default_int(soap, setUserAuthorityOnGameReturn);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__setUserAuthorityOnGameResponse = soap_get_ns1__setUserAuthorityOnGameResponse(soap, NULL, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (setUserAuthorityOnGameReturn && soap_tmp_ns1__setUserAuthorityOnGameResponse->setUserAuthorityOnGameReturn)
		*setUserAuthorityOnGameReturn = *soap_tmp_ns1__setUserAuthorityOnGameResponse->setUserAuthorityOnGameReturn;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__setCharacterNicknameOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerID, int iUnitUID, char *sNickname, int *setCharacterNicknameOnGameReturn)
{	struct ns1__setCharacterNicknameOnGame soap_tmp_ns1__setCharacterNicknameOnGame;
	struct ns1__setCharacterNicknameOnGameResponse *soap_tmp_ns1__setCharacterNicknameOnGameResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__setCharacterNicknameOnGame.ServerID = ServerID;
	soap_tmp_ns1__setCharacterNicknameOnGame.iUnitUID = iUnitUID;
	soap_tmp_ns1__setCharacterNicknameOnGame.sNickname = sNickname;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__setCharacterNicknameOnGame(soap, &soap_tmp_ns1__setCharacterNicknameOnGame);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__setCharacterNicknameOnGame(soap, &soap_tmp_ns1__setCharacterNicknameOnGame, "ns1:setCharacterNicknameOnGame", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__setCharacterNicknameOnGame(soap, &soap_tmp_ns1__setCharacterNicknameOnGame, "ns1:setCharacterNicknameOnGame", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!setCharacterNicknameOnGameReturn)
		return soap_closesock(soap);
	soap_default_int(soap, setCharacterNicknameOnGameReturn);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__setCharacterNicknameOnGameResponse = soap_get_ns1__setCharacterNicknameOnGameResponse(soap, NULL, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (setCharacterNicknameOnGameReturn && soap_tmp_ns1__setCharacterNicknameOnGameResponse->setCharacterNicknameOnGameReturn)
		*setCharacterNicknameOnGameReturn = *soap_tmp_ns1__setCharacterNicknameOnGameResponse->setCharacterNicknameOnGameReturn;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__deleteAllianceMemberOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int iUnitUID, int iGuildNo, int *deleteAllianceMemberOnGameReturn)
{	struct ns1__deleteAllianceMemberOnGame soap_tmp_ns1__deleteAllianceMemberOnGame;
	struct ns1__deleteAllianceMemberOnGameResponse *soap_tmp_ns1__deleteAllianceMemberOnGameResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__deleteAllianceMemberOnGame.ServerId = ServerId;
	soap_tmp_ns1__deleteAllianceMemberOnGame.iUnitUID = iUnitUID;
	soap_tmp_ns1__deleteAllianceMemberOnGame.iGuildNo = iGuildNo;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__deleteAllianceMemberOnGame(soap, &soap_tmp_ns1__deleteAllianceMemberOnGame);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__deleteAllianceMemberOnGame(soap, &soap_tmp_ns1__deleteAllianceMemberOnGame, "ns1:deleteAllianceMemberOnGame", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__deleteAllianceMemberOnGame(soap, &soap_tmp_ns1__deleteAllianceMemberOnGame, "ns1:deleteAllianceMemberOnGame", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!deleteAllianceMemberOnGameReturn)
		return soap_closesock(soap);
	soap_default_int(soap, deleteAllianceMemberOnGameReturn);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__deleteAllianceMemberOnGameResponse = soap_get_ns1__deleteAllianceMemberOnGameResponse(soap, NULL, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (deleteAllianceMemberOnGameReturn && soap_tmp_ns1__deleteAllianceMemberOnGameResponse->deleteAllianceMemberOnGameReturn)
		*deleteAllianceMemberOnGameReturn = *soap_tmp_ns1__deleteAllianceMemberOnGameResponse->deleteAllianceMemberOnGameReturn;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__deleteCharacterItemOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int unitUID, int itemID, int reason, int *deleteCharacterItemOnGameReturn)
{	struct ns1__deleteCharacterItemOnGame soap_tmp_ns1__deleteCharacterItemOnGame;
	struct ns1__deleteCharacterItemOnGameResponse *soap_tmp_ns1__deleteCharacterItemOnGameResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__deleteCharacterItemOnGame.ServerId = ServerId;
	soap_tmp_ns1__deleteCharacterItemOnGame.unitUID = unitUID;
	soap_tmp_ns1__deleteCharacterItemOnGame.itemID = itemID;
	soap_tmp_ns1__deleteCharacterItemOnGame.reason = reason;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__deleteCharacterItemOnGame(soap, &soap_tmp_ns1__deleteCharacterItemOnGame);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__deleteCharacterItemOnGame(soap, &soap_tmp_ns1__deleteCharacterItemOnGame, "ns1:deleteCharacterItemOnGame", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__deleteCharacterItemOnGame(soap, &soap_tmp_ns1__deleteCharacterItemOnGame, "ns1:deleteCharacterItemOnGame", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!deleteCharacterItemOnGameReturn)
		return soap_closesock(soap);
	soap_default_int(soap, deleteCharacterItemOnGameReturn);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__deleteCharacterItemOnGameResponse = soap_get_ns1__deleteCharacterItemOnGameResponse(soap, NULL, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (deleteCharacterItemOnGameReturn && soap_tmp_ns1__deleteCharacterItemOnGameResponse->deleteCharacterItemOnGameReturn)
		*deleteCharacterItemOnGameReturn = *soap_tmp_ns1__deleteCharacterItemOnGameResponse->deleteCharacterItemOnGameReturn;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__deleteAllianceOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int iGuildNo, int *deleteAllianceOnGameReturn)
{	struct ns1__deleteAllianceOnGame soap_tmp_ns1__deleteAllianceOnGame;
	struct ns1__deleteAllianceOnGameResponse *soap_tmp_ns1__deleteAllianceOnGameResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__deleteAllianceOnGame.ServerId = ServerId;
	soap_tmp_ns1__deleteAllianceOnGame.iGuildNo = iGuildNo;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__deleteAllianceOnGame(soap, &soap_tmp_ns1__deleteAllianceOnGame);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__deleteAllianceOnGame(soap, &soap_tmp_ns1__deleteAllianceOnGame, "ns1:deleteAllianceOnGame", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__deleteAllianceOnGame(soap, &soap_tmp_ns1__deleteAllianceOnGame, "ns1:deleteAllianceOnGame", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!deleteAllianceOnGameReturn)
		return soap_closesock(soap);
	soap_default_int(soap, deleteAllianceOnGameReturn);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__deleteAllianceOnGameResponse = soap_get_ns1__deleteAllianceOnGameResponse(soap, NULL, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (deleteAllianceOnGameReturn && soap_tmp_ns1__deleteAllianceOnGameResponse->deleteAllianceOnGameReturn)
		*deleteAllianceOnGameReturn = *soap_tmp_ns1__deleteAllianceOnGameResponse->deleteAllianceOnGameReturn;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__deleteQuestOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int iQuestID, int iUnitUID, int *deleteQuestOnGameReturn)
{	struct ns1__deleteQuestOnGame soap_tmp_ns1__deleteQuestOnGame;
	struct ns1__deleteQuestOnGameResponse *soap_tmp_ns1__deleteQuestOnGameResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__deleteQuestOnGame.ServerId = ServerId;
	soap_tmp_ns1__deleteQuestOnGame.iQuestID = iQuestID;
	soap_tmp_ns1__deleteQuestOnGame.iUnitUID = iUnitUID;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__deleteQuestOnGame(soap, &soap_tmp_ns1__deleteQuestOnGame);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__deleteQuestOnGame(soap, &soap_tmp_ns1__deleteQuestOnGame, "ns1:deleteQuestOnGame", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__deleteQuestOnGame(soap, &soap_tmp_ns1__deleteQuestOnGame, "ns1:deleteQuestOnGame", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!deleteQuestOnGameReturn)
		return soap_closesock(soap);
	soap_default_int(soap, deleteQuestOnGameReturn);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__deleteQuestOnGameResponse = soap_get_ns1__deleteQuestOnGameResponse(soap, NULL, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (deleteQuestOnGameReturn && soap_tmp_ns1__deleteQuestOnGameResponse->deleteQuestOnGameReturn)
		*deleteQuestOnGameReturn = *soap_tmp_ns1__deleteQuestOnGameResponse->deleteQuestOnGameReturn;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__deleteQuestCompleteOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int iQuestID, int iUnitUID, int *deleteQuestCompleteOnGameReturn)
{	struct ns1__deleteQuestCompleteOnGame soap_tmp_ns1__deleteQuestCompleteOnGame;
	struct ns1__deleteQuestCompleteOnGameResponse *soap_tmp_ns1__deleteQuestCompleteOnGameResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__deleteQuestCompleteOnGame.ServerId = ServerId;
	soap_tmp_ns1__deleteQuestCompleteOnGame.iQuestID = iQuestID;
	soap_tmp_ns1__deleteQuestCompleteOnGame.iUnitUID = iUnitUID;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__deleteQuestCompleteOnGame(soap, &soap_tmp_ns1__deleteQuestCompleteOnGame);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__deleteQuestCompleteOnGame(soap, &soap_tmp_ns1__deleteQuestCompleteOnGame, "ns1:deleteQuestCompleteOnGame", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__deleteQuestCompleteOnGame(soap, &soap_tmp_ns1__deleteQuestCompleteOnGame, "ns1:deleteQuestCompleteOnGame", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!deleteQuestCompleteOnGameReturn)
		return soap_closesock(soap);
	soap_default_int(soap, deleteQuestCompleteOnGameReturn);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__deleteQuestCompleteOnGameResponse = soap_get_ns1__deleteQuestCompleteOnGameResponse(soap, NULL, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (deleteQuestCompleteOnGameReturn && soap_tmp_ns1__deleteQuestCompleteOnGameResponse->deleteQuestCompleteOnGameReturn)
		*deleteQuestCompleteOnGameReturn = *soap_tmp_ns1__deleteQuestCompleteOnGameResponse->deleteQuestCompleteOnGameReturn;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__deleteCharsOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int iUnitUID, int *deleteCharsOnGameReturn)
{	struct ns1__deleteCharsOnGame soap_tmp_ns1__deleteCharsOnGame;
	struct ns1__deleteCharsOnGameResponse *soap_tmp_ns1__deleteCharsOnGameResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__deleteCharsOnGame.ServerId = ServerId;
	soap_tmp_ns1__deleteCharsOnGame.iUnitUID = iUnitUID;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__deleteCharsOnGame(soap, &soap_tmp_ns1__deleteCharsOnGame);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__deleteCharsOnGame(soap, &soap_tmp_ns1__deleteCharsOnGame, "ns1:deleteCharsOnGame", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__deleteCharsOnGame(soap, &soap_tmp_ns1__deleteCharsOnGame, "ns1:deleteCharsOnGame", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!deleteCharsOnGameReturn)
		return soap_closesock(soap);
	soap_default_int(soap, deleteCharsOnGameReturn);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__deleteCharsOnGameResponse = soap_get_ns1__deleteCharsOnGameResponse(soap, NULL, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (deleteCharsOnGameReturn && soap_tmp_ns1__deleteCharsOnGameResponse->deleteCharsOnGameReturn)
		*deleteCharsOnGameReturn = *soap_tmp_ns1__deleteCharsOnGameResponse->deleteCharsOnGameReturn;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__startQuestOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int iQuestID, int iUnitUID, int *startQuestOnGameReturn)
{	struct ns1__startQuestOnGame soap_tmp_ns1__startQuestOnGame;
	struct ns1__startQuestOnGameResponse *soap_tmp_ns1__startQuestOnGameResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__startQuestOnGame.ServerId = ServerId;
	soap_tmp_ns1__startQuestOnGame.iQuestID = iQuestID;
	soap_tmp_ns1__startQuestOnGame.iUnitUID = iUnitUID;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__startQuestOnGame(soap, &soap_tmp_ns1__startQuestOnGame);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__startQuestOnGame(soap, &soap_tmp_ns1__startQuestOnGame, "ns1:startQuestOnGame", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__startQuestOnGame(soap, &soap_tmp_ns1__startQuestOnGame, "ns1:startQuestOnGame", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!startQuestOnGameReturn)
		return soap_closesock(soap);
	soap_default_int(soap, startQuestOnGameReturn);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__startQuestOnGameResponse = soap_get_ns1__startQuestOnGameResponse(soap, NULL, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (startQuestOnGameReturn && soap_tmp_ns1__startQuestOnGameResponse->startQuestOnGameReturn)
		*startQuestOnGameReturn = *soap_tmp_ns1__startQuestOnGameResponse->startQuestOnGameReturn;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__completeQuestOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int iQuestID, int iUnitUID, int *completeQuestOnGameReturn)
{	struct ns1__completeQuestOnGame soap_tmp_ns1__completeQuestOnGame;
	struct ns1__completeQuestOnGameResponse *soap_tmp_ns1__completeQuestOnGameResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__completeQuestOnGame.ServerId = ServerId;
	soap_tmp_ns1__completeQuestOnGame.iQuestID = iQuestID;
	soap_tmp_ns1__completeQuestOnGame.iUnitUID = iUnitUID;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__completeQuestOnGame(soap, &soap_tmp_ns1__completeQuestOnGame);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__completeQuestOnGame(soap, &soap_tmp_ns1__completeQuestOnGame, "ns1:completeQuestOnGame", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__completeQuestOnGame(soap, &soap_tmp_ns1__completeQuestOnGame, "ns1:completeQuestOnGame", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!completeQuestOnGameReturn)
		return soap_closesock(soap);
	soap_default_int(soap, completeQuestOnGameReturn);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__completeQuestOnGameResponse = soap_get_ns1__completeQuestOnGameResponse(soap, NULL, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (completeQuestOnGameReturn && soap_tmp_ns1__completeQuestOnGameResponse->completeQuestOnGameReturn)
		*completeQuestOnGameReturn = *soap_tmp_ns1__completeQuestOnGameResponse->completeQuestOnGameReturn;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__postItemInsertOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerID, int iUnitUID, int iQuantity, int iScType, int iScIndex, char *sTitle, char *sMessage, int *postItemInsertOnGameReturn)
{	struct ns1__postItemInsertOnGame soap_tmp_ns1__postItemInsertOnGame;
	struct ns1__postItemInsertOnGameResponse *soap_tmp_ns1__postItemInsertOnGameResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__postItemInsertOnGame.ServerID = ServerID;
	soap_tmp_ns1__postItemInsertOnGame.iUnitUID = iUnitUID;
	soap_tmp_ns1__postItemInsertOnGame.iQuantity = iQuantity;
	soap_tmp_ns1__postItemInsertOnGame.iScType = iScType;
	soap_tmp_ns1__postItemInsertOnGame.iScIndex = iScIndex;
	soap_tmp_ns1__postItemInsertOnGame.sTitle = sTitle;
	soap_tmp_ns1__postItemInsertOnGame.sMessage = sMessage;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__postItemInsertOnGame(soap, &soap_tmp_ns1__postItemInsertOnGame);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__postItemInsertOnGame(soap, &soap_tmp_ns1__postItemInsertOnGame, "ns1:postItemInsertOnGame", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__postItemInsertOnGame(soap, &soap_tmp_ns1__postItemInsertOnGame, "ns1:postItemInsertOnGame", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!postItemInsertOnGameReturn)
		return soap_closesock(soap);
	soap_default_int(soap, postItemInsertOnGameReturn);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__postItemInsertOnGameResponse = soap_get_ns1__postItemInsertOnGameResponse(soap, NULL, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (postItemInsertOnGameReturn && soap_tmp_ns1__postItemInsertOnGameResponse->postItemInsertOnGameReturn)
		*postItemInsertOnGameReturn = *soap_tmp_ns1__postItemInsertOnGameResponse->postItemInsertOnGameReturn;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__reduceCashOnWebDB(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *orderID, char *userName, int serverGroupID, LONG64 characterID, int countProducts, char *products, int *reduceCashOnWebDBReturn)
{	struct ns1__reduceCashOnWebDB soap_tmp_ns1__reduceCashOnWebDB;
	struct ns1__reduceCashOnWebDBResponse *soap_tmp_ns1__reduceCashOnWebDBResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__reduceCashOnWebDB.orderID = orderID;
	soap_tmp_ns1__reduceCashOnWebDB.userName = userName;
	soap_tmp_ns1__reduceCashOnWebDB.serverGroupID = serverGroupID;
	soap_tmp_ns1__reduceCashOnWebDB.characterID = characterID;
	soap_tmp_ns1__reduceCashOnWebDB.countProducts = countProducts;
	soap_tmp_ns1__reduceCashOnWebDB.products = products;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__reduceCashOnWebDB(soap, &soap_tmp_ns1__reduceCashOnWebDB);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__reduceCashOnWebDB(soap, &soap_tmp_ns1__reduceCashOnWebDB, "ns1:reduceCashOnWebDB", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__reduceCashOnWebDB(soap, &soap_tmp_ns1__reduceCashOnWebDB, "ns1:reduceCashOnWebDB", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!reduceCashOnWebDBReturn)
		return soap_closesock(soap);
	soap_default_int(soap, reduceCashOnWebDBReturn);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__reduceCashOnWebDBResponse = soap_get_ns1__reduceCashOnWebDBResponse(soap, NULL, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (reduceCashOnWebDBReturn && soap_tmp_ns1__reduceCashOnWebDBResponse->reduceCashOnWebDBReturn)
		*reduceCashOnWebDBReturn = *soap_tmp_ns1__reduceCashOnWebDBResponse->reduceCashOnWebDBReturn;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__confirmLoginOnWebDB(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *userName, char *password, struct ns1__confirmLoginOnWebDBResponse *_param_19)
{	struct ns1__confirmLoginOnWebDB soap_tmp_ns1__confirmLoginOnWebDB;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__confirmLoginOnWebDB.userName = userName;
	soap_tmp_ns1__confirmLoginOnWebDB.password = password;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__confirmLoginOnWebDB(soap, &soap_tmp_ns1__confirmLoginOnWebDB);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__confirmLoginOnWebDB(soap, &soap_tmp_ns1__confirmLoginOnWebDB, "ns1:confirmLoginOnWebDB", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__confirmLoginOnWebDB(soap, &soap_tmp_ns1__confirmLoginOnWebDB, "ns1:confirmLoginOnWebDB", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_19)
		return soap_closesock(soap);
	soap_default_ns1__confirmLoginOnWebDBResponse(soap, _param_19);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__confirmLoginOnWebDBResponse(soap, _param_19, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getCashFromWebDB(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *userName, int *getCashFromWebDBReturn)
{	struct ns1__getCashFromWebDB soap_tmp_ns1__getCashFromWebDB;
	struct ns1__getCashFromWebDBResponse *soap_tmp_ns1__getCashFromWebDBResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__getCashFromWebDB.userName = userName;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__getCashFromWebDB(soap, &soap_tmp_ns1__getCashFromWebDB);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getCashFromWebDB(soap, &soap_tmp_ns1__getCashFromWebDB, "ns1:getCashFromWebDB", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getCashFromWebDB(soap, &soap_tmp_ns1__getCashFromWebDB, "ns1:getCashFromWebDB", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!getCashFromWebDBReturn)
		return soap_closesock(soap);
	soap_default_int(soap, getCashFromWebDBReturn);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__getCashFromWebDBResponse = soap_get_ns1__getCashFromWebDBResponse(soap, NULL, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (getCashFromWebDBReturn && soap_tmp_ns1__getCashFromWebDBResponse->getCashFromWebDBReturn)
		*getCashFromWebDBReturn = *soap_tmp_ns1__getCashFromWebDBResponse->getCashFromWebDBReturn;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__insertServerMessageOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *message, char *date, char *time, int *insertServerMessageOnGameReturn)
{	struct ns1__insertServerMessageOnGame soap_tmp_ns1__insertServerMessageOnGame;
	struct ns1__insertServerMessageOnGameResponse *soap_tmp_ns1__insertServerMessageOnGameResponse;
	if (!soap_endpoint)
		soap_endpoint = "http://dev.phpsoap.elsword.de/elsword";
	if (!soap_action)
		soap_action = "urn:ElswordAction";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__insertServerMessageOnGame.message = message;
	soap_tmp_ns1__insertServerMessageOnGame.date = date;
	soap_tmp_ns1__insertServerMessageOnGame.time = time;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__insertServerMessageOnGame(soap, &soap_tmp_ns1__insertServerMessageOnGame);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__insertServerMessageOnGame(soap, &soap_tmp_ns1__insertServerMessageOnGame, "ns1:insertServerMessageOnGame", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__insertServerMessageOnGame(soap, &soap_tmp_ns1__insertServerMessageOnGame, "ns1:insertServerMessageOnGame", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!insertServerMessageOnGameReturn)
		return soap_closesock(soap);
	soap_default_int(soap, insertServerMessageOnGameReturn);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__insertServerMessageOnGameResponse = soap_get_ns1__insertServerMessageOnGameResponse(soap, NULL, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (insertServerMessageOnGameReturn && soap_tmp_ns1__insertServerMessageOnGameResponse->insertServerMessageOnGameReturn)
		*insertServerMessageOnGameReturn = *soap_tmp_ns1__insertServerMessageOnGameResponse->insertServerMessageOnGameReturn;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
