/* soapStub.h
   Generated by gSOAP 2.8.0 from gf_soap.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapStub_H
#define soapStub_H
#define SOAP_NAMESPACE_OF_ns1	"urn:elsword"
#include "stdsoap2.h"
#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_ArrayOfstring
#define SOAP_TYPE_ArrayOfstring (8)
/* SOAP encoded array of xsd:string schema type: */
struct ArrayOfstring
{
	char **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ns1__getLoginsByUsernameFromGameResponse
#define SOAP_TYPE_ns1__getLoginsByUsernameFromGameResponse (10)
/* ns1:getLoginsByUsernameFromGameResponse */
struct ns1__getLoginsByUsernameFromGameResponse
{
	struct ArrayOfstring *getLoginsByUsernameFromGameReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__getLoginsByUsernameFromGame
#define SOAP_TYPE_ns1__getLoginsByUsernameFromGame (14)
/* ns1:getLoginsByUsernameFromGame */
struct ns1__getLoginsByUsernameFromGame
{
	char *userName;	/* optional element of type xsd:string */
	char *days;	/* optional element of type xsd:string */
	char *startDate;	/* optional element of type xsd:string */
	char *endDate;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__getLoginsByIpFromGameResponse
#define SOAP_TYPE_ns1__getLoginsByIpFromGameResponse (15)
/* ns1:getLoginsByIpFromGameResponse */
struct ns1__getLoginsByIpFromGameResponse
{
	struct ArrayOfstring *getLoginsByIpFromGameReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__getLoginsByIpFromGame
#define SOAP_TYPE_ns1__getLoginsByIpFromGame (18)
/* ns1:getLoginsByIpFromGame */
struct ns1__getLoginsByIpFromGame
{
	char *ipaddress;	/* optional element of type xsd:string */
	char *days;	/* optional element of type xsd:string */
	char *startDate;	/* optional element of type xsd:string */
	char *endDate;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__getCcuDataFromGameResponse
#define SOAP_TYPE_ns1__getCcuDataFromGameResponse (19)
/* ns1:getCcuDataFromGameResponse */
struct ns1__getCcuDataFromGameResponse
{
	struct ArrayOfstring *getCcuDataFromGameReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__getCcuDataFromGame
#define SOAP_TYPE_ns1__getCcuDataFromGame (22)
/* ns1:getCcuDataFromGame */
struct ns1__getCcuDataFromGame
{
	int worldId;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__getHighscoreFromGameResponse
#define SOAP_TYPE_ns1__getHighscoreFromGameResponse (23)
/* ns1:getHighscoreFromGameResponse */
struct ns1__getHighscoreFromGameResponse
{
	struct ArrayOfstring *getHighscoreFromGameReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__getHighscoreFromGame
#define SOAP_TYPE_ns1__getHighscoreFromGame (26)
/* ns1:getHighscoreFromGame */
struct ns1__getHighscoreFromGame
{
	int ServerId;	/* required element of type xsd:int */
	int worldId;	/* required element of type xsd:int */
	char *charType;	/* optional element of type xsd:string */
	char *rankType;	/* optional element of type xsd:string */
	int startValue;	/* required element of type xsd:int */
	int limit;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__getCharacterDetailsOnGameResponse
#define SOAP_TYPE_ns1__getCharacterDetailsOnGameResponse (27)
/* ns1:getCharacterDetailsOnGameResponse */
struct ns1__getCharacterDetailsOnGameResponse
{
	struct ArrayOfstring *getCharacterDetailsOnGameReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__getCharacterDetailsOnGame
#define SOAP_TYPE_ns1__getCharacterDetailsOnGame (30)
/* ns1:getCharacterDetailsOnGame */
struct ns1__getCharacterDetailsOnGame
{
	int ServerId;	/* required element of type xsd:int */
	int pagesize;	/* required element of type xsd:int */
	int lastsize;	/* required element of type xsd:int */
	char *value;	/* optional element of type xsd:string */
	int flag;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__getCharacterQuestsCurrentOnGameResponse
#define SOAP_TYPE_ns1__getCharacterQuestsCurrentOnGameResponse (31)
/* ns1:getCharacterQuestsCurrentOnGameResponse */
struct ns1__getCharacterQuestsCurrentOnGameResponse
{
	struct ArrayOfstring *getCharacterQuestsCurrentOnGameReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__getCharacterQuestsCurrentOnGame
#define SOAP_TYPE_ns1__getCharacterQuestsCurrentOnGame (34)
/* ns1:getCharacterQuestsCurrentOnGame */
struct ns1__getCharacterQuestsCurrentOnGame
{
	int ServerId;	/* required element of type xsd:int */
	int pagesize;	/* required element of type xsd:int */
	int lastsize;	/* required element of type xsd:int */
	char *nickName;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__getCharacterQuestsCompleteOnGameResponse
#define SOAP_TYPE_ns1__getCharacterQuestsCompleteOnGameResponse (35)
/* ns1:getCharacterQuestsCompleteOnGameResponse */
struct ns1__getCharacterQuestsCompleteOnGameResponse
{
	struct ArrayOfstring *getCharacterQuestsCompleteOnGameReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__getCharacterQuestsCompleteOnGame
#define SOAP_TYPE_ns1__getCharacterQuestsCompleteOnGame (38)
/* ns1:getCharacterQuestsCompleteOnGame */
struct ns1__getCharacterQuestsCompleteOnGame
{
	int ServerId;	/* required element of type xsd:int */
	int pagesize;	/* required element of type xsd:int */
	int lastsize;	/* required element of type xsd:int */
	char *nickName;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__getCharacterPostsOnGameResponse
#define SOAP_TYPE_ns1__getCharacterPostsOnGameResponse (39)
/* ns1:getCharacterPostsOnGameResponse */
struct ns1__getCharacterPostsOnGameResponse
{
	struct ArrayOfstring *getCharacterPostsOnGameReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__getCharacterPostsOnGame
#define SOAP_TYPE_ns1__getCharacterPostsOnGame (42)
/* ns1:getCharacterPostsOnGame */
struct ns1__getCharacterPostsOnGame
{
	int ServerId;	/* required element of type xsd:int */
	int pagesize;	/* required element of type xsd:int */
	int lastsize;	/* required element of type xsd:int */
	char *userUID;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__getAllianceDetailsOnGameByIdResponse
#define SOAP_TYPE_ns1__getAllianceDetailsOnGameByIdResponse (43)
/* ns1:getAllianceDetailsOnGameByIdResponse */
struct ns1__getAllianceDetailsOnGameByIdResponse
{
	struct ArrayOfstring *getAllianceDetailsOnGameByIdReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__getAllianceDetailsOnGameById
#define SOAP_TYPE_ns1__getAllianceDetailsOnGameById (46)
/* ns1:getAllianceDetailsOnGameById */
struct ns1__getAllianceDetailsOnGameById
{
	int ServerId;	/* required element of type xsd:int */
	int pagesize;	/* required element of type xsd:int */
	int lastsize;	/* required element of type xsd:int */
	int GuildNo;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__getAllianceDetailsOnGameByNameResponse
#define SOAP_TYPE_ns1__getAllianceDetailsOnGameByNameResponse (47)
/* ns1:getAllianceDetailsOnGameByNameResponse */
struct ns1__getAllianceDetailsOnGameByNameResponse
{
	struct ArrayOfstring *getAllianceDetailsOnGameByNameReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__getAllianceDetailsOnGameByName
#define SOAP_TYPE_ns1__getAllianceDetailsOnGameByName (50)
/* ns1:getAllianceDetailsOnGameByName */
struct ns1__getAllianceDetailsOnGameByName
{
	int ServerId;	/* required element of type xsd:int */
	int pagesize;	/* required element of type xsd:int */
	int lastsize;	/* required element of type xsd:int */
	char *guildName;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__getAllianceMembersOnGameResponse
#define SOAP_TYPE_ns1__getAllianceMembersOnGameResponse (51)
/* ns1:getAllianceMembersOnGameResponse */
struct ns1__getAllianceMembersOnGameResponse
{
	struct ArrayOfstring *getAllianceMembersOnGameReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__getAllianceMembersOnGame
#define SOAP_TYPE_ns1__getAllianceMembersOnGame (54)
/* ns1:getAllianceMembersOnGame */
struct ns1__getAllianceMembersOnGame
{
	int ServerId;	/* required element of type xsd:int */
	int pagesize;	/* required element of type xsd:int */
	int lastsize;	/* required element of type xsd:int */
	int GuildNo;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__getCharacterListByAccountFromGameResponse
#define SOAP_TYPE_ns1__getCharacterListByAccountFromGameResponse (55)
/* ns1:getCharacterListByAccountFromGameResponse */
struct ns1__getCharacterListByAccountFromGameResponse
{
	struct ArrayOfstring *getCharacterListByAccountFromGameReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__getCharacterListByAccountFromGame
#define SOAP_TYPE_ns1__getCharacterListByAccountFromGame (58)
/* ns1:getCharacterListByAccountFromGame */
struct ns1__getCharacterListByAccountFromGame
{
	int pagesize;	/* required element of type xsd:int */
	int lastsize;	/* required element of type xsd:int */
	char *userName;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__getDeletedCharacterListFromGameResponse
#define SOAP_TYPE_ns1__getDeletedCharacterListFromGameResponse (59)
/* ns1:getDeletedCharacterListFromGameResponse */
struct ns1__getDeletedCharacterListFromGameResponse
{
	struct ArrayOfstring *getDeletedCharacterListFromGameReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__getDeletedCharacterListFromGame
#define SOAP_TYPE_ns1__getDeletedCharacterListFromGame (62)
/* ns1:getDeletedCharacterListFromGame */
struct ns1__getDeletedCharacterListFromGame
{
	int ServerId;	/* required element of type xsd:int */
	int pagesize;	/* required element of type xsd:int */
	int lastsize;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__getCharacterListByLevelFromGameResponse
#define SOAP_TYPE_ns1__getCharacterListByLevelFromGameResponse (63)
/* ns1:getCharacterListByLevelFromGameResponse */
struct ns1__getCharacterListByLevelFromGameResponse
{
	struct ArrayOfstring *getCharacterListByLevelFromGameReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__getCharacterListByLevelFromGame
#define SOAP_TYPE_ns1__getCharacterListByLevelFromGame (66)
/* ns1:getCharacterListByLevelFromGame */
struct ns1__getCharacterListByLevelFromGame
{
	int ServerId;	/* required element of type xsd:int */
	int pagesize;	/* required element of type xsd:int */
	int lastsize;	/* required element of type xsd:int */
	int levelMin;	/* required element of type xsd:int */
	int levelMax;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__getUserAuthorityOnGameResponse
#define SOAP_TYPE_ns1__getUserAuthorityOnGameResponse (69)
/* ns1:getUserAuthorityOnGameResponse */
struct ns1__getUserAuthorityOnGameResponse
{
	int *getUserAuthorityOnGameReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__getUserAuthorityOnGame
#define SOAP_TYPE_ns1__getUserAuthorityOnGame (70)
/* ns1:getUserAuthorityOnGame */
struct ns1__getUserAuthorityOnGame
{
	int UserID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__getItemsByCharacterOnGameResponse
#define SOAP_TYPE_ns1__getItemsByCharacterOnGameResponse (71)
/* ns1:getItemsByCharacterOnGameResponse */
struct ns1__getItemsByCharacterOnGameResponse
{
	struct ArrayOfstring *getItemsByCharacterOnGameReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__getItemsByCharacterOnGame
#define SOAP_TYPE_ns1__getItemsByCharacterOnGame (74)
/* ns1:getItemsByCharacterOnGame */
struct ns1__getItemsByCharacterOnGame
{
	int ServerID;	/* required element of type xsd:int */
	int CharacterID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__getItemDetailsOnGameResponse
#define SOAP_TYPE_ns1__getItemDetailsOnGameResponse (75)
/* ns1:getItemDetailsOnGameResponse */
struct ns1__getItemDetailsOnGameResponse
{
	struct ArrayOfstring *getItemDetailsOnGameReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__getItemDetailsOnGame
#define SOAP_TYPE_ns1__getItemDetailsOnGame (78)
/* ns1:getItemDetailsOnGame */
struct ns1__getItemDetailsOnGame
{
	int ServerID;	/* required element of type xsd:int */
	int ItemID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__getQuestListOnGameResponse
#define SOAP_TYPE_ns1__getQuestListOnGameResponse (79)
/* ns1:getQuestListOnGameResponse */
struct ns1__getQuestListOnGameResponse
{
	struct ArrayOfstring *getQuestListOnGameReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__getQuestListOnGame
#define SOAP_TYPE_ns1__getQuestListOnGame (82)
/* ns1:getQuestListOnGame */
struct ns1__getQuestListOnGame
{
	int ServerId;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__getItemListOnGameResponse
#define SOAP_TYPE_ns1__getItemListOnGameResponse (83)
/* ns1:getItemListOnGameResponse */
struct ns1__getItemListOnGameResponse
{
	struct ArrayOfstring *getItemListOnGameReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__getItemListOnGame
#define SOAP_TYPE_ns1__getItemListOnGame (86)
/* ns1:getItemListOnGame */
struct ns1__getItemListOnGame
{
	int ServerId;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__setCharacterDetailsOnGameResponse
#define SOAP_TYPE_ns1__setCharacterDetailsOnGameResponse (88)
/* ns1:setCharacterDetailsOnGameResponse */
struct ns1__setCharacterDetailsOnGameResponse
{
	int *setCharacterDetailsOnGameReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__setCharacterDetailsOnGame
#define SOAP_TYPE_ns1__setCharacterDetailsOnGame (89)
/* ns1:setCharacterDetailsOnGame */
struct ns1__setCharacterDetailsOnGame
{
	int ServerID;	/* required element of type xsd:int */
	int iUnitUID;	/* required element of type xsd:int */
	int iEXP;	/* required element of type xsd:int */
	int iGamePoint;	/* required element of type xsd:int */
	int iSPoint;	/* required element of type xsd:int */
	int iStoneCnt;	/* required element of type xsd:int */
	int iSpirit;	/* required element of type xsd:int */
	int iVsPoint;	/* required element of type xsd:int */
	int iVsPointMax;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__setUserAuthorityOnGameResponse
#define SOAP_TYPE_ns1__setUserAuthorityOnGameResponse (91)
/* ns1:setUserAuthorityOnGameResponse */
struct ns1__setUserAuthorityOnGameResponse
{
	int *setUserAuthorityOnGameReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__setUserAuthorityOnGame
#define SOAP_TYPE_ns1__setUserAuthorityOnGame (92)
/* ns1:setUserAuthorityOnGame */
struct ns1__setUserAuthorityOnGame
{
	char *Username;	/* optional element of type xsd:string */
	char *Authority;	/* optional element of type xsd:bool */
};
#endif

#ifndef SOAP_TYPE_ns1__setCharacterNicknameOnGameResponse
#define SOAP_TYPE_ns1__setCharacterNicknameOnGameResponse (94)
/* ns1:setCharacterNicknameOnGameResponse */
struct ns1__setCharacterNicknameOnGameResponse
{
	int *setCharacterNicknameOnGameReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__setCharacterNicknameOnGame
#define SOAP_TYPE_ns1__setCharacterNicknameOnGame (95)
/* ns1:setCharacterNicknameOnGame */
struct ns1__setCharacterNicknameOnGame
{
	int ServerID;	/* required element of type xsd:int */
	int iUnitUID;	/* required element of type xsd:int */
	char *sNickname;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__deleteAllianceMemberOnGameResponse
#define SOAP_TYPE_ns1__deleteAllianceMemberOnGameResponse (97)
/* ns1:deleteAllianceMemberOnGameResponse */
struct ns1__deleteAllianceMemberOnGameResponse
{
	int *deleteAllianceMemberOnGameReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__deleteAllianceMemberOnGame
#define SOAP_TYPE_ns1__deleteAllianceMemberOnGame (98)
/* ns1:deleteAllianceMemberOnGame */
struct ns1__deleteAllianceMemberOnGame
{
	int ServerId;	/* required element of type xsd:int */
	int iUnitUID;	/* required element of type xsd:int */
	int iGuildNo;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__deleteCharacterItemOnGameResponse
#define SOAP_TYPE_ns1__deleteCharacterItemOnGameResponse (100)
/* ns1:deleteCharacterItemOnGameResponse */
struct ns1__deleteCharacterItemOnGameResponse
{
	int *deleteCharacterItemOnGameReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__deleteCharacterItemOnGame
#define SOAP_TYPE_ns1__deleteCharacterItemOnGame (101)
/* ns1:deleteCharacterItemOnGame */
struct ns1__deleteCharacterItemOnGame
{
	int ServerId;	/* required element of type xsd:int */
	int unitUID;	/* required element of type xsd:int */
	int itemID;	/* required element of type xsd:int */
	int reason;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__deleteAllianceOnGameResponse
#define SOAP_TYPE_ns1__deleteAllianceOnGameResponse (103)
/* ns1:deleteAllianceOnGameResponse */
struct ns1__deleteAllianceOnGameResponse
{
	int *deleteAllianceOnGameReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__deleteAllianceOnGame
#define SOAP_TYPE_ns1__deleteAllianceOnGame (104)
/* ns1:deleteAllianceOnGame */
struct ns1__deleteAllianceOnGame
{
	int ServerId;	/* required element of type xsd:int */
	int iGuildNo;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__deleteQuestOnGameResponse
#define SOAP_TYPE_ns1__deleteQuestOnGameResponse (106)
/* ns1:deleteQuestOnGameResponse */
struct ns1__deleteQuestOnGameResponse
{
	int *deleteQuestOnGameReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__deleteQuestOnGame
#define SOAP_TYPE_ns1__deleteQuestOnGame (107)
/* ns1:deleteQuestOnGame */
struct ns1__deleteQuestOnGame
{
	int ServerId;	/* required element of type xsd:int */
	int iQuestID;	/* required element of type xsd:int */
	int iUnitUID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__deleteQuestCompleteOnGameResponse
#define SOAP_TYPE_ns1__deleteQuestCompleteOnGameResponse (109)
/* ns1:deleteQuestCompleteOnGameResponse */
struct ns1__deleteQuestCompleteOnGameResponse
{
	int *deleteQuestCompleteOnGameReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__deleteQuestCompleteOnGame
#define SOAP_TYPE_ns1__deleteQuestCompleteOnGame (110)
/* ns1:deleteQuestCompleteOnGame */
struct ns1__deleteQuestCompleteOnGame
{
	int ServerId;	/* required element of type xsd:int */
	int iQuestID;	/* required element of type xsd:int */
	int iUnitUID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__deleteCharsOnGameResponse
#define SOAP_TYPE_ns1__deleteCharsOnGameResponse (112)
/* ns1:deleteCharsOnGameResponse */
struct ns1__deleteCharsOnGameResponse
{
	int *deleteCharsOnGameReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__deleteCharsOnGame
#define SOAP_TYPE_ns1__deleteCharsOnGame (113)
/* ns1:deleteCharsOnGame */
struct ns1__deleteCharsOnGame
{
	int ServerId;	/* required element of type xsd:int */
	int iUnitUID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__startQuestOnGameResponse
#define SOAP_TYPE_ns1__startQuestOnGameResponse (115)
/* ns1:startQuestOnGameResponse */
struct ns1__startQuestOnGameResponse
{
	int *startQuestOnGameReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__startQuestOnGame
#define SOAP_TYPE_ns1__startQuestOnGame (116)
/* ns1:startQuestOnGame */
struct ns1__startQuestOnGame
{
	int ServerId;	/* required element of type xsd:int */
	int iQuestID;	/* required element of type xsd:int */
	int iUnitUID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__completeQuestOnGameResponse
#define SOAP_TYPE_ns1__completeQuestOnGameResponse (118)
/* ns1:completeQuestOnGameResponse */
struct ns1__completeQuestOnGameResponse
{
	int *completeQuestOnGameReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__completeQuestOnGame
#define SOAP_TYPE_ns1__completeQuestOnGame (119)
/* ns1:completeQuestOnGame */
struct ns1__completeQuestOnGame
{
	int ServerId;	/* required element of type xsd:int */
	int iQuestID;	/* required element of type xsd:int */
	int iUnitUID;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__postItemInsertOnGameResponse
#define SOAP_TYPE_ns1__postItemInsertOnGameResponse (121)
/* ns1:postItemInsertOnGameResponse */
struct ns1__postItemInsertOnGameResponse
{
	int *postItemInsertOnGameReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__postItemInsertOnGame
#define SOAP_TYPE_ns1__postItemInsertOnGame (122)
/* ns1:postItemInsertOnGame */
struct ns1__postItemInsertOnGame
{
	int ServerID;	/* required element of type xsd:int */
	int iUnitUID;	/* required element of type xsd:int */
	int iQuantity;	/* required element of type xsd:int */
	int iScType;	/* required element of type xsd:int */
	int iScIndex;	/* required element of type xsd:int */
	char *sTitle;	/* optional element of type xsd:string */
	char *sMessage;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__reduceCashOnWebDBResponse
#define SOAP_TYPE_ns1__reduceCashOnWebDBResponse (125)
/* ns1:reduceCashOnWebDBResponse */
struct ns1__reduceCashOnWebDBResponse
{
	int *reduceCashOnWebDBReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__reduceCashOnWebDB
#define SOAP_TYPE_ns1__reduceCashOnWebDB (126)
/* ns1:reduceCashOnWebDB */
struct ns1__reduceCashOnWebDB
{
	char *orderID;	/* optional element of type xsd:string */
	char *userName;	/* optional element of type xsd:string */
	int serverGroupID;	/* required element of type xsd:int */
	LONG64 characterID;	/* required element of type xsd:long */
	int countProducts;	/* required element of type xsd:int */
	char *products;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__confirmLoginOnWebDBResponse
#define SOAP_TYPE_ns1__confirmLoginOnWebDBResponse (127)
/* ns1:confirmLoginOnWebDBResponse */
struct ns1__confirmLoginOnWebDBResponse
{
	struct ArrayOfstring *confirmLoginOnWebDBReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns1__confirmLoginOnWebDB
#define SOAP_TYPE_ns1__confirmLoginOnWebDB (130)
/* ns1:confirmLoginOnWebDB */
struct ns1__confirmLoginOnWebDB
{
	char *userName;	/* optional element of type xsd:string */
	char *password;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__getCashFromWebDBResponse
#define SOAP_TYPE_ns1__getCashFromWebDBResponse (132)
/* ns1:getCashFromWebDBResponse */
struct ns1__getCashFromWebDBResponse
{
	int *getCashFromWebDBReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__getCashFromWebDB
#define SOAP_TYPE_ns1__getCashFromWebDB (133)
/* ns1:getCashFromWebDB */
struct ns1__getCashFromWebDB
{
	char *userName;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__insertServerMessageOnGameResponse
#define SOAP_TYPE_ns1__insertServerMessageOnGameResponse (135)
/* ns1:insertServerMessageOnGameResponse */
struct ns1__insertServerMessageOnGameResponse
{
	int *insertServerMessageOnGameReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__insertServerMessageOnGame
#define SOAP_TYPE_ns1__insertServerMessageOnGame (136)
/* ns1:insertServerMessageOnGame */
struct ns1__insertServerMessageOnGame
{
	char *message;	/* optional element of type xsd:string */
	char *date;	/* optional element of type xsd:string */
	char *time;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (137)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (138)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (140)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (143)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (144)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE_xsd__bool
#define SOAP_TYPE_xsd__bool (7)
typedef char *xsd__bool;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getLoginsByUsernameFromGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *userName, char *days, char *startDate, char *endDate, struct ns1__getLoginsByUsernameFromGameResponse *_param_1);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getLoginsByIpFromGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *ipaddress, char *days, char *startDate, char *endDate, struct ns1__getLoginsByIpFromGameResponse *_param_2);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getCcuDataFromGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int worldId, struct ns1__getCcuDataFromGameResponse *_param_3);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getHighscoreFromGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int worldId, char *charType, char *rankType, int startValue, int limit, struct ns1__getHighscoreFromGameResponse *_param_4);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getCharacterDetailsOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int pagesize, int lastsize, char *value, int flag, struct ns1__getCharacterDetailsOnGameResponse *_param_5);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getCharacterQuestsCurrentOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int pagesize, int lastsize, char *nickName, struct ns1__getCharacterQuestsCurrentOnGameResponse *_param_6);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getCharacterQuestsCompleteOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int pagesize, int lastsize, char *nickName, struct ns1__getCharacterQuestsCompleteOnGameResponse *_param_7);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getCharacterPostsOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int pagesize, int lastsize, char *userUID, struct ns1__getCharacterPostsOnGameResponse *_param_8);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getAllianceDetailsOnGameById(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int pagesize, int lastsize, int GuildNo, struct ns1__getAllianceDetailsOnGameByIdResponse *_param_9);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getAllianceDetailsOnGameByName(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int pagesize, int lastsize, char *guildName, struct ns1__getAllianceDetailsOnGameByNameResponse *_param_10);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getAllianceMembersOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int pagesize, int lastsize, int GuildNo, struct ns1__getAllianceMembersOnGameResponse *_param_11);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getCharacterListByAccountFromGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int pagesize, int lastsize, char *userName, struct ns1__getCharacterListByAccountFromGameResponse *_param_12);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getDeletedCharacterListFromGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int pagesize, int lastsize, struct ns1__getDeletedCharacterListFromGameResponse *_param_13);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getCharacterListByLevelFromGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int pagesize, int lastsize, int levelMin, int levelMax, struct ns1__getCharacterListByLevelFromGameResponse *_param_14);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getUserAuthorityOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int UserID, int *getUserAuthorityOnGameReturn);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getItemsByCharacterOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerID, int CharacterID, struct ns1__getItemsByCharacterOnGameResponse *_param_15);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getItemDetailsOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerID, int ItemID, struct ns1__getItemDetailsOnGameResponse *_param_16);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getQuestListOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, struct ns1__getQuestListOnGameResponse *_param_17);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getItemListOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, struct ns1__getItemListOnGameResponse *_param_18);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__setCharacterDetailsOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerID, int iUnitUID, int iEXP, int iGamePoint, int iSPoint, int iStoneCnt, int iSpirit, int iVsPoint, int iVsPointMax, int *setCharacterDetailsOnGameReturn);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__setUserAuthorityOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *Username, char *Authority, int *setUserAuthorityOnGameReturn);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__setCharacterNicknameOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerID, int iUnitUID, char *sNickname, int *setCharacterNicknameOnGameReturn);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__deleteAllianceMemberOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int iUnitUID, int iGuildNo, int *deleteAllianceMemberOnGameReturn);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__deleteCharacterItemOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int unitUID, int itemID, int reason, int *deleteCharacterItemOnGameReturn);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__deleteAllianceOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int iGuildNo, int *deleteAllianceOnGameReturn);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__deleteQuestOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int iQuestID, int iUnitUID, int *deleteQuestOnGameReturn);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__deleteQuestCompleteOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int iQuestID, int iUnitUID, int *deleteQuestCompleteOnGameReturn);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__deleteCharsOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int iUnitUID, int *deleteCharsOnGameReturn);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__startQuestOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int iQuestID, int iUnitUID, int *startQuestOnGameReturn);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__completeQuestOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerId, int iQuestID, int iUnitUID, int *completeQuestOnGameReturn);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__postItemInsertOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ServerID, int iUnitUID, int iQuantity, int iScType, int iScIndex, char *sTitle, char *sMessage, int *postItemInsertOnGameReturn);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__reduceCashOnWebDB(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *orderID, char *userName, int serverGroupID, LONG64 characterID, int countProducts, char *products, int *reduceCashOnWebDBReturn);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__confirmLoginOnWebDB(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *userName, char *password, struct ns1__confirmLoginOnWebDBResponse *_param_19);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getCashFromWebDB(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *userName, int *getCashFromWebDBReturn);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__insertServerMessageOnGame(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *message, char *date, char *time, int *insertServerMessageOnGameReturn);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
