#ifdef __NEVER_DEFINED_MACRO__
#define _ENUM(VAL) VAL,
enum
{
#endif

_ENUM( I_TO_INIT )
_ENUM( I_TO_CLOSE )
_ENUM( I_TO_MAKING_PARTY )
_ENUM( I_TO_WAIT )
_ENUM( I_TO_CHECK_PLAY_CONDITION )
_ENUM( I_TO_CHECK_AUTO_PARTY )
_ENUM( I_TO_ACCEPT_FOR_PLAY )
_ENUM( I_TO_PREPARE_FOR_PLAY )

#ifdef __NEVER_DEFINED_MACRO__
};
#undef _ENUM
#endif