_ENUM( DC_ACCOUNT )
_ENUM( DC_GAME )
_ENUM( DC_LOG )
_ENUM( DC_NX_WEB )
_ENUM( DC_SMS )
_ENUM( DC_GAME_2ND )
_ENUM( DC_LOG_2ND )
_ENUM( DC_KOG_BILLING )			// SERV_GLOBAL_BILLING
_ENUM( DC_PUBLISHER_BILLING )	// SERV_GLOBAL_BILLING
_ENUM( DC_CHAT_LOG ) // SERV_RECORD_CHAT
_ENUM( DC_ID_PCBANG_AUTH ) // SERV_ID_NETMARBLE_PCBANG
_ENUM( DC_JP_RELAY_DB ) // SERV_RELAY_DB_CONNECTION
_ENUM( DC_EVENT ) // SERV_ADD_EVENT_DB
_ENUM( DC_PUBLISHER_AUTH )	// SERV_GLOBAL_AUTH
_ENUM( DC_SCRIPT ) // SERV_ADD_SCRIPT_DB