_ENUM( DC_ACCOUNT )
_ENUM( DC_GAME )
_ENUM( DC_LOG )
_ENUM( DC_NX_WEB )
_ENUM( DC_SMS )
_ENUM( DC_KOG_BILLING )			// SERV_GLOBAL_BILLING
_ENUM( DC_PUBLISHER_BILLING )	// SERV_GLOBAL_BILLING
_ENUM( DC_CHAT_LOG ) // SERV_RECORD_CHAT
_ENUM( DC_ID_PCBANG_AUTH ) // SERV_ID_NETMARBLE_PCBANG
_ENUM( DC_JP_RELAY_DB ) // SERV_RELAY_DB_CONNECTION
