// 게임 서버와 센터 서버간의 이벤트 정의.



#ifdef __NEVER_DEFINED_MACRO__
#define _ENUM(VAL) VAL,
enum
{
#endif

    _ENUM( DBE_SERVER_ON_REQ )
    _ENUM( DBE_SERVER_ON_ACK )
    _ENUM( DBE_SERVER_OFF_NOT )

	_ENUM( DBE_NEW_USER_JOIN_REQ )
	_ENUM( DBE_NEW_USER_JOIN_ACK )

    _ENUM( DBE_UPDATE_SERVER_INFO_REQ )
    _ENUM( DBE_UPDATE_SERVER_INFO_ACK )
    
    _ENUM( ECN_UPDATE_SERVER_INFO_REQ )
    _ENUM( ECN_UPDATE_SERVER_INFO_ACK )

	_ENUM( ECN_SEND_STATISTICS_LOCLOG_REQ )
	_ENUM( ECN_SEND_STATISTICS_DBLOG_REQ )

	_ENUM( DBE_MY_UNIT_AND_INVENTORY_INFO_LIST_REQ )
	_ENUM( DBE_MY_UNIT_AND_INVENTORY_INFO_LIST_ACK )

	_ENUM( E_KICK_USER_NOT )

    _ENUM( DBE_UPDATE_UNIT_INFO_REQ )
    _ENUM( DBE_UPDATE_UNIT_INFO_ACK )

	//{{ 2011. 07. 19	최육사	서버간 접속 코드 리팩토링
	//#ifdef SERV_SERVER_CONNECT_CODE_REFACTORING	
    _ENUM( ECN_VERIFY_SERVER_CONNECT_REQ )
    _ENUM( ECN_VERIFY_SERVER_CONNECT_ACK )

	_ENUM( ELG_VERIFY_SERVER_CONNECT_REQ )
	_ENUM( ELG_VERIFY_SERVER_CONNECT_ACK )

	_ENUM( EGB_VERIFY_SERVER_CONNECT_REQ )
	_ENUM( EGB_VERIFY_SERVER_CONNECT_ACK )

	_ENUM( DBE_VERIFY_SERVER_CONNECT_REQ )
	_ENUM( DBE_VERIFY_SERVER_CONNECT_ACK )
	//#endif SERV_SERVER_CONNECT_CODE_REFACTORING
	//}}

    _ENUM( ECN_CHECK_UUID_REQ )                 // gs -> cn : 유저의 UID 문의. 없으면 새로 발행됨.
    _ENUM( ECN_CHECK_UUID_ACK )

    _ENUM( ELG_NEXON_USER_AUTHENTICATE_REQ )          // gs -> cn : 유저 인증 요청
    _ENUM( ELG_NEXON_USER_AUTHENTICATE_ACK )

	//{{ 2010. 06. 29  최육사	게임 PC방 인증 서버 개편
	_ENUM( ELG_NEXON_USER_LOGIN_TIME_OUT_NOT )
	//}}

	_ENUM( DBE_ADMIN_SERVER_STATUS_REQ )
	_ENUM( DBE_ADMIN_SERVER_STATUS_ACK )

	_ENUM( DBE_ADMIN_MODIFY_UNIT_LEVEL_REQ )
	_ENUM( DBE_ADMIN_MODIFY_UNIT_LEVEL_ACK )

	_ENUM( DBE_ADMIN_CHANGE_AUTH_LEVEL_REQ )
	_ENUM( DBE_ADMIN_CHANGE_AUTH_LEVEL_ACK )

	_ENUM( DBE_ADMIN_GET_AUTH_LEVEL_LIST_REQ )
	_ENUM( DBE_ADMIN_GET_AUTH_LEVEL_LIST_ACK )

	_ENUM( DBE_ADMIN_CHANGE_ED_REQ )
	_ENUM( DBE_ADMIN_CHANGE_ED_ACK )

//{{ 2012. 12. 10  캐릭터 선택 패킷 분할 - 김민성
//#ifdef SERV_SELECT_UNIT_PACKET_DIVISION
	_ENUM( DBE_SELECT_UNIT_ACK )	
//#endif SERV_SELECT_UNIT_PACKET_DIVISION
//}

	//{{ 2009. 5. 26  최육사	채널이동
	_ENUM( ECN_CHECK_CHANNEL_CHANGE_REQ )
	_ENUM( ECN_CHECK_CHANNEL_CHANGE_ACK )

	_ENUM( ELG_CHANNEL_CHANGE_NEXON_USER_AUTHENTICATE_REQ )
	_ENUM( ELG_CHANNEL_CHANGE_NEXON_USER_AUTHENTICATE_ACK )
	_ENUM( ELG_CHANNEL_CHANGE_REGISTER_USER_REQ )
	_ENUM( ELG_CHANNEL_CHANGE_REGISTER_USER_ACK )
	_ENUM( DBE_CHANNEL_CHANGE_GAME_SELECT_UNIT_REQ )
	_ENUM( DBE_CHANNEL_CHANGE_GAME_SELECT_UNIT_ACK )
	_ENUM( DBE_CHANNEL_CHANGE_ACCOUNT_SELECT_UNIT_REQ )
	_ENUM( DBE_CHANNEL_CHANGE_ACCOUNT_SELECT_UNIT_ACK )	

	_ENUM( ERM_JOIN_FIELD_CHANNEL_CHANGE_REQ )
	_ENUM( ERM_JOIN_FIELD_CHANNEL_CHANGE_ACK )
	//}}

	_ENUM( ECN_NOTIFY_MSG_NOT )					// NOTIFY MESSAGE

    _ENUM( ERM_OPEN_PVP_ROOM_REQ )              // gs -> room : PvP 방 생성 요청.
    _ENUM( ERM_OPEN_DUNGEON_ROOM_REQ )
    _ENUM( ERM_OPEN_ROOM_ACK )                  // room -> gs : 방 생성 응답.

	_ENUM( ERM_OPEN_TC_ROOM_REQ )				// 훈련소 방생성
	_ENUM( ERM_OPEN_TC_ROOM_ACK )

    _ENUM( ERM_JOIN_ROOM_REQ )
    _ENUM( ERM_JOIN_ROOM_ACK )
    _ENUM( ERM_JOIN_ROOM_NOT )

	_ENUM( ERM_JOIN_SQUARE_REQ )
	_ENUM( ERM_JOIN_SQUARE_ACK )
	_ENUM( ERM_JOIN_SQUARE_NOT )

    _ENUM( ERM_QUICK_JOIN_ACK )

    _ENUM( ERM_LEAVE_ROOM_REQ )                 // gs -> room : 방 퇴장 요청.
    _ENUM( ERM_LEAVE_ROOM_ACK )                 // room -> gs : 방 퇴장 응답.
    _ENUM( ERM_LEAVE_ROOM_NOT )

	_ENUM( ERM_LEAVE_SQUARE_REQ )
	_ENUM( ERM_LEAVE_SQUARE_ACK )
	_ENUM( ERM_LEAVE_SQUARE_NOT )

    _ENUM( ERM_INTRUDE_GAME_REQ )
    _ENUM( ERM_INTRUDE_GAME_ACK )
    _ENUM( ERM_INTRUDE_GAME_NOT )

    _ENUM( ERM_LEAVE_GAME_REQ )
    _ENUM( ERM_LEAVE_GAME_ACK )
    _ENUM( ERM_LEAVE_GAME_NOT )

    _ENUM( ERM_BAN_USER_REQ )                   // gs -> room : 강퇴 요청.
    _ENUM( ERM_BAN_USER_ACK )                   // room -> gs : 강퇴 응답.
    _ENUM( ERM_BAN_USER_NOT )                   // room -> gs : 강퇴 대상에게.

    _ENUM( ERM_CHANGE_EQUIP_INFO_REQ )           // gs -> room : 유저 장착 정보 변경 요청.
    _ENUM( ERM_CHANGE_EQUIP_INFO_ACK )           // room -> gs : 유저 장착 정보 변경 응답.

    _ENUM( ERM_ROOM_LIST_INFO_NOT )             // room -> gs : 룸 리스트 정보 변경.
    _ENUM( ERM_ROOM_OPTION_INFO_NOT )           // room -> gs : 룸 옵션 정보 변경. 모든 방원에게.
    _ENUM( ERM_ROOM_SLOT_INFO_NOT )             // room -> gs : 룸 멤버 정보 변경. 모든 방원에게.

    _ENUM( ERM_CHANGE_ROOM_OPTION_INFO_REQ )
    _ENUM( ERM_CHANGE_ROOM_OPTION_INFO_ACK )

	_ENUM( ERM_CHANGE_TEAM_REQ )
	_ENUM( ERM_CHANGE_TEAM_ACK )
	_ENUM( ERM_CHANGE_TEAM_NOT )

	_ENUM( ERM_CHANGE_READY_REQ )
	_ENUM( ERM_CHANGE_READY_ACK )
	_ENUM( ERM_CHANGE_READY_NOT )

	_ENUM( ERM_CHANGE_PITIN_REQ )	//방안에서 내정보창에 들어갔을때..
	_ENUM( ERM_CHANGE_PITIN_ACK )
	_ENUM( ERM_CHANGE_PITIN_NOT )

	_ENUM( ERM_CHANGE_MAP_REQ )
	_ENUM( ERM_CHANGE_MAP_ACK )
	_ENUM( ERM_CHANGE_MAP_NOT )

    _ENUM( ERM_CHANGE_SLOT_OPEN_REQ )
    _ENUM( ERM_CHANGE_SLOT_OPEN_ACK )
    _ENUM( ERM_CHANGE_SLOT_OPEN_NOT )

    _ENUM( ERM_CHANGE_PLAY_TIME_LIMIT_REQ )
    _ENUM( ERM_CHANGE_PLAY_TIME_LIMIT_ACK )
    _ENUM( ERM_CHANGE_PLAY_TIME_LIMIT_NOT )

    _ENUM( ERM_CHANGE_WINNING_NUM_KILL_REQ )
    _ENUM( ERM_CHANGE_WINNING_NUM_KILL_ACK )
    _ENUM( ERM_CHANGE_WINNING_NUM_KILL_NOT )

    _ENUM( ERM_CHANGE_ROOM_SLOT_INFO_REQ )
    _ENUM( ERM_CHANGE_ROOM_SLOT_INFO_ACK )

    _ENUM( ERM_GAME_START_REQ )
    _ENUM( ERM_GAME_START_ACK )
    _ENUM( ERM_GAME_START_NOT )

    _ENUM( ERM_GAME_LOADING_REQ )
    _ENUM( ERM_GAME_LOADING_ACK )
    _ENUM( ERM_GAME_LOADING_NOT )
    _ENUM( ERM_GAME_LOADING_ALL_UNIT_OK_NOT )

    _ENUM( ERM_P2P_CONNECT_SUCCESS_REQ )
    _ENUM( ERM_P2P_CONNECT_SUCCESS_ACK )
    _ENUM( ERM_P2P_CONNECT_SUCCESS_ALL_UNIT_OK_NOT )

    _ENUM( ERM_CHAT_REQ )
    _ENUM( ERM_CHAT_ACK )
    _ENUM( ERM_CHAT_NOT )

	_ENUM( ETR_CHAT_NOT )

	_ENUM( ELG_CHAT_REQ )
	_ENUM( ELG_CHAT_ACK )
	_ENUM( ELG_CHAT_NOT )

	_ENUM( ERM_CHANGE_MOTION_REQ )
	_ENUM( ERM_CHANGE_MOTION_ACK )
	_ENUM( ERM_CHANGE_MOTION_NOT )

    _ENUM( ERM_PLAY_START_NOT )
    _ENUM( ERM_REMAINING_PLAY_TIME_NOT )
    _ENUM( ERM_PLAY_TIME_OUT_NOT )

    _ENUM( ERM_STATE_CHANGE_GAME_INTRUDE_REQ ) //난입자가 난입 버튼을 누름
    _ENUM( ERM_STATE_CHANGE_GAME_INTRUDE_ACK )
    _ENUM( ERM_STATE_CHANGE_GAME_INTRUDE_NOT )

    _ENUM( ERM_INTRUDE_REQ ) //난입자가 로딩, 커넥트 끝나면
    _ENUM( ERM_INTRUDE_ACK ) //난입자가 로딩, 커넥트 끝나면
    _ENUM( ERM_INTRUDE_NOT ) //난입자가 로딩, 커넥트 끝나면

    _ENUM( ERM_INTRUDER_LOADING_COMPLETE_REQ ) //게임중인 유저가 난입자 유닛 로딩
    _ENUM( ERM_INTRUDER_LOADING_COMPLETE_ACK )

    _ENUM( ERM_INTRUDE_START_REQ )
    _ENUM( ERM_INTRUDE_START_ACK )
    _ENUM( ERM_INTRUDE_START_NOT ) //난입 성공

    _ENUM( ERM_END_GAME_REQ )
    _ENUM( ERM_END_GAME_ACK )
    _ENUM( ERM_END_GAME_NOT )

    _ENUM( ERM_STATE_CHANGE_RESULT_REQ )
    _ENUM( ERM_STATE_CHANGE_RESULT_ACK )
    _ENUM( ERM_STATE_CHANGE_RESULT_NOT )

	_ENUM( ERM_USER_UNIT_DIE_REQ )
	_ENUM( ERM_USER_UNIT_DIE_ACK )
	_ENUM( ERM_USER_UNIT_DIE_NOT )

	_ENUM( ERM_USER_UNIT_DIE_COMPLETE_REQ )
	_ENUM( ERM_USER_UNIT_DIE_COMPLETE_ACK )
	_ENUM( ERM_USER_UNIT_DIE_COMPLETE_NOT )

	_ENUM( ERM_DUNGEON_STAGE_LOAD_REQ )
	_ENUM( ERM_DUNGEON_STAGE_LOAD_ACK )
	_ENUM( ERM_DUNGEON_STAGE_LOAD_NOT )

	_ENUM( ERM_DUNGEON_STAGE_LOAD_COMPLETE_REQ )
	_ENUM( ERM_DUNGEON_STAGE_LOAD_COMPLETE_ACK )
	_ENUM( ERM_DUNGEON_STAGE_LOAD_COMPLETE_NOT )

	_ENUM( ERM_DUNGEON_STAGE_START_NOT )

	_ENUM( ERM_DUNGEON_SUB_STAGE_OPEN_REQ ) //호스트가 날림, 서브 스테이지 번호 
	_ENUM( ERM_DUNGEON_SUB_STAGE_OPEN_ACK )
	_ENUM( ERM_DUNGEON_SUB_STAGE_OPEN_NOT )// 다음 스테이지의 스타트 라인을 연다

	_ENUM( ERM_DUNGEON_SUB_STAGE_GO_NEXT_REQ ) //내가 다음 스테이지 라인으로 넘어갔다 장막 생성
	_ENUM( ERM_DUNGEON_SUB_STAGE_GO_NEXT_ACK )
	_ENUM( ERM_DUNGEON_SUB_STAGE_GO_NEXT_ALL_NOT ) //모두 넘어왔다 이전 스테이지 라인을 끈다

	_ENUM( ERM_DUNGEON_SUB_STAGE_LOAD_COMPLETE_REQ ) //몬스터 생성이 끝나면 각자 날림
	_ENUM( ERM_DUNGEON_SUB_STAGE_LOAD_COMPLETE_ACK )

	_ENUM( ERM_DUNGEON_SUB_STAGE_START_NOT ) //장막 열림

	_ENUM( ERM_NPC_UNIT_CREATE_REQ )
	_ENUM( ERM_NPC_UNIT_CREATE_ACK )
	_ENUM( ERM_NPC_UNIT_CREATE_NOT )

	_ENUM( ERM_NPC_UNIT_DIE_REQ )
	_ENUM( ERM_NPC_UNIT_DIE_ACK )
	_ENUM( ERM_NPC_UNIT_DIE_NOT )
	//{{ 2012. 11. 12	최육사	배틀필드 시스템
//#ifdef SERV_BATTLE_FIELD_SYSTEM
	_ENUM( ERM_BATTLE_FIELD_NPC_UNIT_DIE_NOT )
//#endif SERV_BATTLE_FIELD_SYSTEM
	//}}

	_ENUM( ERM_MY_USER_UNIT_INFO_TO_SERVER_REQ )
	_ENUM( ERM_MY_USER_UNIT_INFO_TO_SERVER_ACK )

	//{{ 2008. 9. 19  최육사	통계
	_ENUM( ERM_DUNGEON_PLAY_INFO_TO_SERVER_NOT )
	//}}

	_ENUM( ERM_END_GAME_DUNGEON_RESULT_DATA_NOT )
	_ENUM( ERM_END_GAME_PVP_RESULT_DATA_NOT )

    _ENUM( ERM_USER_UNIT_RE_BIRTH_POS_REQ )
    _ENUM( ERM_USER_UNIT_RE_BIRTH_POS_ACK )

    _ENUM( ERM_USER_UNIT_RE_BIRTH_NOT )

    _ENUM( ERM_CURRENT_KILL_SCORE_NOT )
    _ENUM( ERM_CURRENT_TEAM_KILL_SCORE_NOT )

    _ENUM( ERM_CHANGE_DUNGEON_DIFFICULTY_REQ )
    _ENUM( ERM_CHANGE_DUNGEON_DIFFICULTY_ACK )
    _ENUM( ERM_CHANGE_DUNGEON_DIFFICULTY_NOT )

	_ENUM( ERM_DROP_ITEM_NOT )
	_ENUM( ERM_GET_ITEM_REQ )
	_ENUM( ERM_GET_ITEM_ACK )
	_ENUM( ERM_GET_ITEM_NOT )

	//{{ 2009. 5. 11  최육사	실시간아이템
	_ENUM( ERM_GET_ITEM_INSERT_TO_INVENTORY_NOT )
	_ENUM( DBE_GET_ITEM_INSERT_TO_INVENTORY_REQ )
	_ENUM( DBE_GET_ITEM_INSERT_TO_INVENTORY_ACK )
	_ENUM( ERM_GET_ITEM_COMPLETE_NOT )
	_ENUM( DBE_GET_TEMP_ITEM_REQ )
	_ENUM( DBE_GET_TEMP_ITEM_ACK )
	//}}

	_ENUM( ERM_CHANGE_DUNGEON_GET_ITEM_TYPE_REQ )
	_ENUM( ERM_CHANGE_DUNGEON_GET_ITEM_TYPE_ACK )
	_ENUM( ERM_CHANGE_DUNGEON_GET_ITEM_TYPE_NOT )

    // -----------------------------------------------------------------------------------------------------------------------
    // 여기 아래에 선언하시오
    // -----------------------------------------------------------------------------------------------------------------------
	//_ENUM( ERM_UPDATE_UNIT_INFO_NOT )	// cs => gs : unit 정보 업데이트를 위해
	_ENUM( ERM_UPDATE_PVP_UNIT_INFO_NOT )
	_ENUM( ERM_UPDATE_DUNGEON_UNIT_INFO_NOT )

	_ENUM( ERM_SET_UNIT_INFO_NOT )		// gs => cs : unit정보 셋팅후 아직방에 있다면 바뀐 unit정보를 seting하기 위해

    _ENUM( ERM_REFRESH_ROOM_REQ )
    _ENUM( ERM_REFRESH_ROOM_ACK )

    _ENUM( ERM_CHANGE_EQUIPPED_ITEM_IN_SQUARE_NOT )
    _ENUM( ERM_CHANGE_EQUIPPED_ITEM_IN_ROOM_NOT )
	//{{ 2008. 11. 7  최육사
	_ENUM( ERM_CHANGE_EQUIPPED_ITEM_IN_FIELD_NOT )
	_ENUM( ETR_CHANGE_EQUIPPED_ITEM_IN_FIELD_NOT )
	//}}
	//{{ 2010. 12. 30	최육사	코드 정리
	_ENUM( ERM_GAME_LOADING_TIME_OUT_NOT )
	//}}	

    _ENUM( DBE_BUY_ED_ITEM_REQ )
    _ENUM( DBE_BUY_ED_ITEM_ACK )

    _ENUM( DBE_INSERT_ITEM_REQ )
    _ENUM( DBE_INSERT_ITEM_ACK )
	
	// 통계
    _ENUM( ELOG_STAT_PLAY_TIME )    
	_ENUM( ELOG_STAT_PVP_MAP )
	_ENUM( ELOG_STAT_FPS )
	_ENUM( ELOG_CHEAT_LOG_NOT )

	_ENUM( DBE_NEW_QUEST_REQ )
	_ENUM( DBE_NEW_QUEST_ACK )

	_ENUM( DBE_GIVE_UP_QUEST_REQ )
	_ENUM( DBE_GIVE_UP_QUEST_ACK )

	_ENUM( DBE_QUEST_COMPLETE_REQ )
	_ENUM( DBE_QUEST_COMPLETE_ACK )	

    _ENUM( ELOG_CHAT_LOG_NOT )  // 게임 채팅 메세지를 남긴다.
    _ENUM( DBE_UPDATE_LOGIN_TIME_NOT ) // 유저의 최근 로그인 시각을 DB에 기록한다.
    _ENUM( DBE_CHARACTER_LEVELUP_NOT ) // 캐릭터 로그인 시점을 DB에 기록한다.

	_ENUM( ERM_CHECK_INVALID_ROOM_NOT )	// 없어저야할 방에서 게임중인 경우를 체크한다.(센터서버 비정상 종료인 경우)
    _ENUM( ERM_CHECK_INVALID_USER_NOT ) // 접속이 끊어진 방에 연결되어있는 RoomUser를 체크한다 (게임서버 비정상 종료시)
	_ENUM( ERM_CHECK_INVALID_ZOMBIE_USER_NOT )	//방에서 삭제된 좀비유저를 게임서버에서 체크해본다.

	_ENUM( ERM_RESULT_SUCCESS_REQ )
	_ENUM( ERM_RESULT_SUCCESS_ACK )
	_ENUM( ERM_RESULT_ALL_UNIT_SUCCESS_NOT )

	_ENUM( ERM_USE_QUICK_SLOT_NOT )
	
	_ENUM( ERM_SQUARE_LIST_INFO_NOT )			// room -> gs : 광장 리스트 정보 추가/변경/삭제등.

	_ENUM( ERM_SQUARE_UNIT_SYNC_DATA_REQ )
	_ENUM( ERM_SQUARE_UNIT_SYNC_DATA_NOT )

	_ENUM( DBE_INSERT_SKILL_REQ )
	_ENUM( DBE_INSERT_SKILL_ACK )

	_ENUM( DBE_ADMIN_INIT_SKILL_TREE_REQ )
	_ENUM( DBE_ADMIN_INIT_SKILL_TREE_ACK )

	_ENUM( DBE_INIT_SKILL_TREE_REQ )
	_ENUM( DBE_INIT_SKILL_TREE_ACK )

	//{{ 2008. 4. 14  최육사  스킬 초기화
	_ENUM( DBE_RESET_SKILL_REQ )
	_ENUM( DBE_RESET_SKILL_ACK )
	_ENUM( ERM_RESET_SKILL_NOT )				// obsolete!! 현재 사용안하고 있는듯
	//}}

	//{{ 2008. 4. 21  최육사  스킬슬롯B
	_ENUM( DBE_EXPAND_SKILL_SLOT_REQ )
	_ENUM( DBE_EXPAND_SKILL_SLOT_ACK )
	//}}

	_ENUM( DBE_INSERT_CASH_SKILL_POINT_REQ )
	_ENUM( DBE_INSERT_CASH_SKILL_POINT_ACK )

	_ENUM( DBE_EXPIRE_CASH_SKILL_POINT_REQ )
	_ENUM( DBE_EXPIRE_CASH_SKILL_POINT_ACK )

	//{{ 2009. 8. 4  최육사		봉인 스킬
	_ENUM( DBE_UNSEAL_SKILL_REQ )
	_ENUM( DBE_UNSEAL_SKILL_ACK )
	//}}

	_ENUM( ELOG_INIT_SKILL_TREE_NOT )
	_ENUM( ELOG_INSERT_CASH_SKILL_POINT_NOT )	// 캐시 스킬 포인트 사용시작 로그

    _ENUM( DBE_SEARCH_UNIT_REQ )
    _ENUM( DBE_SEARCH_UNIT_ACK )

	_ENUM( DBE_KNM_REQUEST_NEW_FRIEND_INFO_REQ )
	_ENUM( DBE_KNM_REQUEST_NEW_FRIEND_INFO_ACK )

	//////////////////////////////////////////////////////////////////////////
	// Party

	_ENUM( ERM_PARTY_OPEN_DUNGEON_ROOM_REQ )
	_ENUM( ERM_PARTY_OPEN_DUNGEON_ROOM_ACK )
	_ENUM( ERM_PARTY_OPEN_DUNGEON_ROOM_NOT )

	//던전게임 종료
	_ENUM( ERM_PARTY_TO_FIELD_MAP_REQ )
	_ENUM( ERM_PARTY_TO_FIELD_MAP_ACK )
	_ENUM( ERM_PARTY_TO_FIELD_MAP_NOT )

	//파티유저 밴
	_ENUM( ERM_PARTY_BAN_USER_REQ )
	_ENUM( ERM_PARTY_BAN_USER_ACK )

	// Party
	//////////////////////////////////////////////////////////////////////////

	_ENUM( ERM_RESURRECT_TO_CONTINUE_DUNGEON_REQ )
	_ENUM( ERM_RESURRECT_TO_CONTINUE_DUNGEON_ACK )
	_ENUM( ERM_RESURRECT_TO_CONTINUE_DUNGEON_NOT )

	// 블랙리스트
	_ENUM( DBE_NEW_BLACKLIST_USER_REQ )
	_ENUM( DBE_NEW_BLACKLIST_USER_ACK )
	_ENUM( DBE_DEL_BLACKLIST_USER_REQ )
	_ENUM( DBE_DEL_BLACKLIST_USER_ACK )

	_ENUM( ERM_SKIP_CONTINUE_DUNGEON_NOT )
	
	_ENUM( ERM_DECREASE_ENDURANCE_PVP_NOT )
	_ENUM( ERM_DECREASE_ENDURANCE_DUNGEON_NOT )
	_ENUM( ERM_OPEN_SQUARE_NOT )

	// 개인 거래
	_ENUM( ERM_REQUEST_TRADE_NOT )
	_ENUM( ERM_REQUEST_TRADE_REPLY_NOT )

	_ENUM( ERM_OPEN_TRADE_REQ )
	_ENUM( ERM_OPEN_TRADE_ACK )

	_ENUM( ERM_BREAK_TRADE_REQ )
	_ENUM( ERM_BREAK_TRADE_ACK )
	_ENUM( ERM_BREAK_TRADE_NOT )

	_ENUM( ERM_ACCEPT_JOIN_TRADE_NOT )
	_ENUM( ERM_JOIN_TRADE_REQ )
	_ENUM( ERM_JOIN_TRADE_ACK )
	_ENUM( ERM_JOIN_TRADE_NOT )

	_ENUM( ERM_UPDATE_TRADE_ITEM_REQ )
	_ENUM( ERM_UPDATE_TRADE_ITEM_ACK )
	_ENUM( ERM_UPDATE_TRADE_ITEM_NOT )

	_ENUM( ERM_UPDATE_TRADE_ED_REQ )
	_ENUM( ERM_UPDATE_TRADE_ED_ACK )
	_ENUM( ERM_UPDATE_TRADE_ED_NOT )

	_ENUM( ERM_OFFER_TRADE_REQ )
	_ENUM( ERM_OFFER_TRADE_ACK )
	_ENUM( ERM_OFFER_TRADE_NOT )

	_ENUM( ERM_APPROVE_TRADE_REQ )
	_ENUM( ERM_APPROVE_TRADE_ACK )
	_ENUM( ERM_APPROVE_TRADE_NOT )

	_ENUM( ERM_CONFIRM_TRADE_REQ )
	_ENUM( ERM_CONFIRM_TRADE_ACK )
	_ENUM( ERM_CONFIRM_TRADE_NOT )

	//{{ 2012. 03. 28	최육사	개인거래 DDOS 방어
//#ifdef SERV_TRADE_DDOS_DEFENCE
	_ENUM( ERM_DB_UPDATE_TRADE_RESULT_NOT )
	_ENUM( DBE_DB_UPDATE_TRADE_RESULT_REQ )
	_ENUM( DBE_DB_UPDATE_TRADE_RESULT_ACK )
	_ENUM( ERM_DB_UPDATE_TRADE_COMPLETE_NOT )
//#endif SERV_TRADE_DDOS_DEFENCE
	//}}

	_ENUM( DBE_INSERT_TRADE_ITEM_REQ )
	_ENUM( DBE_INSERT_TRADE_ITEM_ACK )
	//{{ 2009. 2. 10  최육사	개인거래 버그 예방
	_ENUM( DBE_INSERT_TRADE_ITEM_BY_SERVER_NOT )
	//}}

	_ENUM( ELOG_INSERT_TRADE_LOG_NOT )

	_ENUM( ERM_END_TC_GAME_REQ ) //훈련소 게임 끝났을때
	_ENUM( ERM_END_TC_GAME_ACK )

	_ENUM( ERM_SET_TC_REMAINING_TIME_REQ )
	_ENUM( ERM_SET_TC_REMAINING_TIME_ACK )
	
	_ENUM( ERM_LEAVE_TC_ROOM_REQ )
	_ENUM( ERM_LEAVE_TC_ROOM_ACK )

	// 넥슨 유저 인증 ( 구버전 )
	_ENUM( ENX_INITIALIZE_BILLING_AUTH_NOT )
	_ENUM( ENX_USER_LOGIN_REQ )
	_ENUM( ENX_USER_LOGIN_ACK )
	_ENUM( ENX_USER_LOGOUT_REQ )
	_ENUM( ENX_USER_TERMINATE_NOT )
	_ENUM( ENX_ALIVE_NOT )
	_ENUM( ENX_MESSAGE_NOT )
    _ENUM( ENX_COMMON_ACK_NOT )

	// 넥슨 인증 서버 개편 ( 신버전 )
	_ENUM( ENX_AUTH_INITIALIZE_REQ )
	_ENUM( ENX_AUTH_INITIALIZE_ACK )
	_ENUM( ENX_AUTH_LOGIN_REQ )
	_ENUM( ENX_AUTH_LOGIN_ACK )
	_ENUM( ENX_AUTH_LOGOUT_NOT )
	_ENUM( ENX_AUTH_TERMINATE_NOT )
	_ENUM( ENX_AUTH_MESSAGE_NOT )
	_ENUM( ENX_AUTH_SYNCHRONIZE_REQ )
	_ENUM( ENX_AUTH_SYNCHRONIZE_ACK )
	_ENUM( ENX_AUTH_ALIVE_NOT )

	// 로긴 서버
	_ENUM( ELG_REGISTER_USER_REQ )
	_ENUM( ELG_REGISTER_USER_ACK )
    _ENUM( ELG_REGISTER_NEXON_USER_ACK )					// 해외에서는 사용하지 않음. 대신 ELG_REGISTER_USER_GLOBAL_PUBLISHER_ACK 사용
	_ENUM( ELG_REGISTER_NEXON_CHANNEL_CHANGE_USER_ACK )		// 해외에서는 사용하지 않음. 대신 ELG_REGISTER_USER_GLOBAL_PUBLISHER_ACK 사용
	_ENUM( ELG_USER_DISCONNECT_REQ )            // gs -> lg : 유저 접속 종료 알림.
	_ENUM( ELG_USER_DISCONNECT_ACK )            // gs -> lg : 유저 접속 종료 알림.

	_ENUM( ELG_REGISTER_UNIT_NOT )				// 같이하기 등의 기능을 위해 gs -> cn 으로 UNIT NICKNAME 등록.
	_ENUM( ELG_UNIT_DISCONNECT_NOT )

	//{{ 2012. 03. 20	최육사	배틀필드 시스템
//#ifdef SERV_BATTLE_FIELD_SYSTEM
	_ENUM( EGB_REGISTER_UNIT_NOT )
	_ENUM( EGB_UNIT_DISCONNECT_NOT )
//#endif SERV_BATTLE_FIELD_SYSTEM
	//}}

	_ENUM( ELG_SEARCH_UNIT_REQ )
	_ENUM( ELG_SEARCH_UNIT_ACK )

	_ENUM( ELG_GET_UNIT_INFO_REQ )
	_ENUM( ELG_GET_UNIT_INFO_ACK )

	//{{ 2010. 05. 13  최육사	대전 던전 서버군 통합
	_ENUM( ERM_SEARCH_UNIT_REQ )
	_ENUM( ERM_SEARCH_UNIT_ACK )

	_ENUM( ERM_GET_UNIT_INFO_REQ )
	_ENUM( ERM_GET_UNIT_INFO_ACK )
	//}}

	//korea nexon msg
	_ENUM( ELG_KNM_REQUEST_NEW_FRIEND_INFO_REQ )
	_ENUM( ELG_KNM_REQUEST_NEW_FRIEND_INFO_ACK )
	_ENUM( ELG_KNM_INVITE_REQ )
	_ENUM( ELG_KNM_INVITE_ACK )
	_ENUM( ELG_KNM_INVITE_NOT )
	_ENUM( ELG_KNM_TOGETHER_REQ )
	_ENUM( ELG_KNM_TOGETHER_ACK )
	_ENUM( ELG_KNM_TOGETHER_BY_UNIT_INFO_REQ )
	_ENUM( ELG_KNM_TOGETHER_BY_UNIT_INFO_ACK )

	_ENUM( DBE_OPEN_RANDOM_ITEM_REQ )
	_ENUM( DBE_OPEN_RANDOM_ITEM_ACK )

	_ENUM( DBE_ITEM_MANUFACTURE_REQ )
	_ENUM( DBE_ITEM_MANUFACTURE_ACK )

	_ENUM( ELOG_USER_STATISTICS )

    // 넥슨 빌링 웹 통지
    _ENUM( ENX_INITIALIZE_BILLING_WEB_NOT )
    _ENUM( ENX_ADM_SEARCH_REQ )
    _ENUM( ENX_ADM_SEARCH_ACK )
    _ENUM( ENX_CHAR_SEARCH_REQ )
    _ENUM( ENX_CHAR_SEARCH_ACK )
    _ENUM( ENX_NEW_SHOP_ITEM_NOT )
    _ENUM( ENX_NEW_SHOP_GIFT_NOT )

	//게임중 추가 능력치 적용
	_ENUM( ERM_ADD_ON_STAT_REQ )
	_ENUM( ERM_ADD_ON_STAT_ACK )
	_ENUM( ERM_ADD_ON_STAT_NOT )

    _ENUM( DBE_GET_PURCHASED_CASH_ITEM_REQ )
    _ENUM( DBE_GET_PURCHASED_CASH_ITEM_ACK )
    _ENUM( DBE_ROLLBACK_PURCHASED_CASH_ITEM_NOT )

    _ENUM( DBE_GET_PURCHASED_CASH_PACKAGE_REQ )
    _ENUM( DBE_GET_PURCHASED_CASH_PACKAGE_ACK )
    _ENUM( DBE_ROLLBACK_PURCHASED_CASH_PACKAGE_NOT )

	_ENUM( DBE_GAME_CREATE_UNIT_REQ )
	_ENUM( DBE_GAME_CREATE_UNIT_ACK )

	_ENUM( DBE_ACCOUNT_CREATE_UNIT_REQ )
	_ENUM( DBE_ACCOUNT_CREATE_UNIT_ACK )

	_ENUM( DBE_GAME_SELECT_UNIT_REQ )
	_ENUM( DBE_GAME_SELECT_UNIT_ACK )

	_ENUM( DBE_ACCOUNT_SELECT_UNIT_REQ )
	_ENUM( DBE_ACCOUNT_SELECT_UNIT_ACK )

    _ENUM( DBE_INSERT_PURCHASED_CASH_ITEM_REQ )
    _ENUM( DBE_INSERT_PURCHASED_CASH_ITEM_ACK )

	_ENUM( DBE_INSERT_PURCHASED_CASH_PACKAGE_REQ )
	_ENUM( DBE_INSERT_PURCHASED_CASH_PACKAGE_ACK )

	// 센터 서버 유저 통계
	_ENUM( ERM_PVP_USER_STATISTICS_NOT )
	_ENUM( ERM_DUNGEON_USER_STATISTICS_NOT )
	_ENUM( ERM_TC_USER_STATISTICS_NOT )	
	
	_ENUM( ELOG_STAT_RES_STONE )
	_ENUM( ELOG_STAT_ED )
	_ENUM( ELOG_STAT_QUEST )
	_ENUM( ELOG_STAT_DISCONNECT_REASON )
	_ENUM( ELOG_STAT_DISCONNECT_USERFSM )
	//{{ 2011. 02. 28	최육사	사내 통합 통계
	_ENUM( ELOG_STAT_CHARACTER )
	//}}
	//{{ 2011. 04. 13	최육사	아이템 통계 DB기록
	_ENUM( ELOG_STAT_ITEM_DB )
	//}}
//#ifdef SERV_ACTIVE_KOG_GAME_PERFORMANCE_CHECK
	_ENUM( ELOG_STAT_SYSTEM_INFO )
	_ENUM( ELOG_STAT_KOG_GAME_PERFORMANCE_VILLAGE )
	_ENUM( ELOG_STAT_KOG_GAME_PERFORMANCE_FIELD )
	_ENUM( ELOG_STAT_KOG_GAME_PERFORMANCE_DUNGEON )
	_ENUM( ELOG_STAT_KOG_GAME_PERFORMANCE_PVP )
//#endif//SERV_ACTIVE_KOG_GAME_PERFORMANCE_CHECK

//#ifdef SERV_ACTIVE_KOG_GAME_PERFORMANCE_CHECK_VER2
	_ENUM( ECN_SET_ACTIVE_LAGCHECK_NOT )
//#endif//SERV_ACTIVE_KOG_GAME_PERFORMANCE_CHECK_VER2


	_ENUM( DBE_DELETE_UNIT_STAT_NOT )

	_ENUM( ERM_REPAIR_ITEM_NOT )	//방대기중 장착중인 아이템을 고칠경우사용.

    _ENUM( ENX_BT_INITIALIZE_REQ )
    _ENUM( ENX_BT_INITIALIZE_ACK )

    _ENUM( ENX_BT_HEART_BEAT_REQ )
    _ENUM( ENX_BT_HEART_BEAT_ACK )

    _ENUM( ENX_BT_CATEGORY_INQUIRY_REQ )
    _ENUM( ENX_BT_CATEGORY_INQUIRY_ACK )

    _ENUM( ENX_BT_PRODUCT_INQUIRY_XML_REQ )
    _ENUM( ENX_BT_PRODUCT_INQUIRY_XML_ACK )

    _ENUM( ENX_BT_PRODUCT_INQUIRY_REQ )
    _ENUM( ENX_BT_PRODUCT_INQUIRY_ACK )

    _ENUM( ENX_BT_CHECK_BALANCE_REQ )
    _ENUM( ENX_BT_CHECK_BALANCE_ACK )

    _ENUM( ENX_BT_PURCHASE_ITEM_REQ )
    _ENUM( ENX_BT_PURCHASE_ITEM_ACK )

    _ENUM( ENX_BT_PURCHASE_GIFT_REQ )
    _ENUM( ENX_BT_PURCHASE_GIFT_ACK )

	//{{ 2009. 10. 14  최육사	자동결제 부활석
	_ENUM( ENX_BT_CHECK_AUTO_PAYMENT_USER_REQ )
	_ENUM( ENX_BT_CHECK_AUTO_PAYMENT_USER_ACK )
	//}}

    _ENUM( ENX_BT_COUPON_INQUIRY_REQ )
    _ENUM( ENX_BT_COUPON_INQUIRY_ACK )

	//{{ 2009. 3. 24  최육사	쿠폰사용여부 조회
	_ENUM( ENX_BT_COUPON_INQUIRY_NEW_REQ )
	_ENUM( ENX_BT_COUPON_INQUIRY_NEW_ACK )
	//}}

    _ENUM( ENX_BT_COUPON_USING_REQ )
    _ENUM( ENX_BT_COUPON_USING_ACK )
	
    _ENUM( ENX_BT_NISMS_INVENTORY_INQUIRY_REQ )
    _ENUM( ENX_BT_NISMS_INVENTORY_INQUIRY_ACK )
	
	_ENUM( ENX_BT_NISMS_INVENTORY_CHECK_REQ )
	_ENUM( ENX_BT_NISMS_INVENTORY_CHECK_ACK )

	_ENUM( ENX_BT_NISMS_INVENTORY_READABLE_REQ )
	_ENUM( ENX_BT_NISMS_INVENTORY_READABLE_ACK )

    _ENUM( ENX_BT_NISMS_INVENTORY_READ_REQ )
    _ENUM( ENX_BT_NISMS_INVENTORY_READ_ACK )

    _ENUM( ENX_BT_NISMS_INVENTORY_PICK_UP_REQ )
    _ENUM( ENX_BT_NISMS_INVENTORY_PICK_UP_ACK )

    _ENUM( ENX_BT_NISMS_INVENTORY_PICK_UP_ROLLBACK_REQ )
    _ENUM( ENX_BT_NISMS_INVENTORY_PICK_UP_ROLLBACK_ACK )

    _ENUM( ENX_BT_NISMS_INVENTORY_PICK_UP_ONCE_REQ )
    _ENUM( ENX_BT_NISMS_INVENTORY_PICK_UP_ONCE_ACK )
	
	_ENUM( ENX_BT_NISMS_INVENTORY_PICK_UP_FOR_PACKAGE_REQ )
	_ENUM( ENX_BT_NISMS_INVENTORY_PICK_UP_FOR_PACKAGE_ACK )

	//{{ 2010. 11. 17	최육사	넥슨 빌링 청약 철회
	_ENUM( ENX_BT_REFUND_REQ )
	_ENUM( ENX_BT_REFUND_ACK )
	//}}

	_ENUM( DBE_GAME_DELETE_UNIT_REQ )	//유닉 삭제용으로 사용
	_ENUM( DBE_GAME_DELETE_UNIT_ACK )
	_ENUM( DBE_ACCOUNT_DELETE_UNIT_REQ )	//유닉 메신져 씨리얼 받아오는 용도로 사용
	_ENUM( DBE_ACCOUNT_DELETE_UNIT_ACK )
	
	_ENUM( ELG_SEARCH_BLACK_LIST_UNIT_REQ )
	_ENUM( ELG_SEARCH_BLACK_LIST_UNIT_ACK )

	//////////////////////////////////////////////////////////////////////////
	//[개인상점] Personal Shop packet
	_ENUM( ERM_CHECK_OPEN_PERSONAL_SHOP_REQ )
	_ENUM( ERM_CHECK_OPEN_PERSONAL_SHOP_ACK )

	_ENUM( ERM_OPEN_PERSONAL_SHOP_REQ )
	_ENUM( ERM_OPEN_PERSONAL_SHOP_ACK )

	_ENUM( ERM_UPDATE_SQUARE_PERSONAL_SHOP_INFO_NOT )

	_ENUM( ERM_REG_PERSONAL_SHOP_ITEM_REQ )
	_ENUM( ERM_REG_PERSONAL_SHOP_ITEM_ACK )

	_ENUM( ERM_BREAK_PERSONAL_SHOP_REQ )
	_ENUM( ERM_BREAK_PERSONAL_SHOP_ACK )
	_ENUM( ERM_BREAK_PERSONAL_SHOP_NOT )

	_ENUM( ERM_CHECK_JOIN_PERSONAL_SHOP_REQ )
	_ENUM( ERM_CHECK_JOIN_PERSONAL_SHOP_ACK )

	_ENUM( ERM_JOIN_PERSONAL_SHOP_REQ )
	_ENUM( ERM_JOIN_PERSONAL_SHOP_ACK )

	_ENUM( ERM_LEAVE_PERSONAL_SHOP_REQ )
	_ENUM( ERM_LEAVE_PERSONAL_SHOP_ACK )

	_ENUM( ERM_BUY_PERSONAL_SHOP_ITEM_REQ )
	_ENUM( ERM_BUY_PERSONAL_SHOP_ITEM_ACK )
	_ENUM( ERM_BUY_PERSONAL_SHOP_ITEM_COMPLETE_NOT )

	_ENUM( ERM_UPDATE_PERSONAL_SHOP_ITEM_INFO_NOT )

	_ENUM( ERM_CONFIRM_BUY_PERSONAL_SHOP_ITEM_REQ )
	_ENUM( ERM_CONFIRM_BUY_PERSONAL_SHOP_ITEM_ACK )
	_ENUM( DBE_INSERT_BUY_PERSONAL_SHOP_ITEM_REQ )
	_ENUM( DBE_INSERT_BUY_PERSONAL_SHOP_ITEM_ACK )
	//Personal Shop packet
	//////////////////////////////////////////////////////////////////////////
	
	//{{ 2009. 9. 22  최육사	전직캐쉬	
	_ENUM( DBE_CHANGE_UNIT_CLASS_REQ )
	_ENUM( DBE_CHANGE_UNIT_CLASS_ACK )
	//}}

    _ENUM( ERM_CHANGE_TRADE_NOT )
    _ENUM( ERM_TRADE_START_NOT )
    _ENUM( ERM_TRADE_FINISH_NOT )
	
	_ENUM( DBE_RESOLVE_ITEM_REQ )
	_ENUM( DBE_RESOLVE_ITEM_ACK )
    _ENUM( DBE_ENCHANT_ITEM_REQ )
    _ENUM( DBE_ENCHANT_ITEM_ACK )
	//{{ 2008. 12. 18  최육사	보조제 로그
	_ENUM( ELOG_ENCHANT_SUPPORT_MATERIAL_LOG_NOT )
	//}}

	_ENUM( DBE_EVENT_UPDATE_REQ )
	_ENUM( DBE_EVENT_UPDATE_ACK )

	//{{ 2012. 02. 03	박세훈	이벤트 관련정보 처리방법 변경 ( Script -> DB )
//#ifdef SERV_CHANGE_EVENT_INFO_SCRIPT_TO_DB
	_ENUM( DBE_RELEASE_TICK_UPDATE_REQ )
	_ENUM( DBE_RELEASE_TICK_UPDATE_ACK )

	_ENUM( DBE_EVENT_DATA_UPDATE_REQ )
	_ENUM( DBE_EVENT_DATA_UPDATE_ACK )

	_ENUM( DBE_EVENT_MONSTER_UPDATE_REQ )
	_ENUM( DBE_EVENT_MONSTER_UPDATE_ACK )

	_ENUM( DBE_EVENT_NOTIFY_MSG_SERVER_INFO_UPDATE_REQ )
	_ENUM( DBE_EVENT_NOTIFY_MSG_SERVER_INFO_UPDATE_ACK )

	_ENUM( DBE_EVENT_REWARD_DATA_UPDATE_REQ )
	_ENUM( DBE_EVENT_REWARD_DATA_UPDATE_ACK )

	_ENUM( DBE_EVENT_REWARD_LEVEL_UP_UPDATE_REQ )
	_ENUM( DBE_EVENT_REWARD_LEVEL_UP_UPDATE_ACK )

	_ENUM( DBE_EVENT_REWARD_RETAIN_USER_ITEM_UPDATE_REQ )
	_ENUM( DBE_EVENT_REWARD_RETAIN_USER_ITEM_UPDATE_ACK )
//#endif SERV_CHANGE_EVENT_INFO_SCRIPT_TO_DB
	//}}

	_ENUM( ELOG_INSERT_PERSONAL_SHOP_LOG_NOT )
	_ENUM( ELOG_INSERT_ABUSER_LOG_NOT )	
	
	_ENUM( DBE_SOCKET_ITEM_REQ )
	_ENUM( DBE_SOCKET_ITEM_ACK )

    _ENUM( DBE_UPDATE_UNIT_CLASS_NOT )
	_ENUM( DBE_SEND_PHONE_MSG_NOT )
	_ENUM( DBE_SEND_PHONE_MSG_FOR_MORNITORING_REQ )
	_ENUM( DBE_SEND_PHONE_MSG_FOR_MORNITORING_ACK )
	
	_ENUM( ELOG_RESURRECTION_STONE_LOG_NOT )
	_ENUM( ELOG_RESOLVE_JACKPOT_LOG_NOT )


	// 추천인
	_ENUM( DBE_RECOMMEND_USER_REQ )
	_ENUM( DBE_RECOMMEND_USER_ACK )
	_ENUM( DBE_RECOMMEND_USER_NOT )
	_ENUM( ELG_RECOMMEND_USER_RESULT_NOT )
	_ENUM( DBE_INSERT_REWARD_TO_POST_REQ )
	_ENUM( DBE_INSERT_REWARD_TO_POST_ACK )

	// 우체국
	_ENUM( DBE_GET_POST_LETTER_LIST_REQ )
	_ENUM( DBE_GET_POST_LETTER_LIST_ACK )
	_ENUM( DBE_PREPARE_INSERT_LETTER_TO_POST_REQ )
	_ENUM( DBE_PREPARE_INSERT_LETTER_TO_POST_ACK )
	_ENUM( DBE_INSERT_LETTER_TO_POST_REQ )
	_ENUM( DBE_INSERT_LETTER_TO_POST_ACK )
	_ENUM( ELG_FIND_USER_SEND_LETTER_NOT )
	_ENUM( DBE_READ_LETTER_NOT )
	_ENUM( DBE_GET_ITEM_FROM_LETTER_REQ )
	_ENUM( DBE_GET_ITEM_FROM_LETTER_ACK )
	_ENUM( DBE_DELETE_LETTER_NOT )
	_ENUM( DBE_INSERT_POST_ITEM_TO_INVENTORY_REQ )
	_ENUM( DBE_INSERT_POST_ITEM_TO_INVENTORY_ACK )

	_ENUM( ERM_SET_QUEST_ITEM_INFO_NOT )	//퀘스트 아이템 관련 인벤토리 정보가 변경될시 방에 정보를 업데이트 하기위한 패킷.

	//{{ 2008. 4. 2  최육사  근성도 회복 아이템
	_ENUM( ERM_RESTORE_SPIRIT_NOT )
	//}}

	_ENUM( DBE_DEL_TUTORIAL_REQ )
	_ENUM( DBE_DEL_TUTORIAL_ACK )

	_ENUM( ELG_DEL_TUTORIAL_NOT )	//리스트 삭제시 로그인 서버로 보내는 패킷.

	_ENUM( ELG_TUTORIAL_UPDATE_UNIT_INFO_NOT )

	_ENUM( ELG_REQUEST_TUTORIAL_NOT )
	_ENUM( ELG_REQUEST_TUTORIAL_REPLY_NOT )
	_ENUM( DBE_INSERT_TUTORIAL_REQ )
	_ENUM( DBE_INSERT_TUTORIAL_ACK )
	_ENUM( ERM_TUTORIAL_DUNGEON_ROOM_UPDATE_NOT )	//방안에서 사제관계를 맺을시 바로 해택이 주어지기 위해서.

	//{{ 2008. 4. 10  최육사  스크립트 리프레쉬
	_ENUM( ESR_SCRIPT_REFRESH_ORDER_NOT )
	_ENUM( ESR_ORDER_TO_CENTER_SERVER_NOT )
	_ENUM( ESR_ORDER_TO_GAME_SERVER_NOT )
	_ENUM( ESR_ORDER_TO_LOGIN_SERVER_NOT )
	_ENUM( ESR_ORDER_TO_REFRESH_MANAGER_REQ )
	_ENUM( ESR_ORDER_TO_REFRESH_MANAGER_ACK )
	//}}

	//{{ 2011. 04. 13  김민성  글로벌 서버 추가
//#ifdef SERV_INSERT_GLOBAL_SERVER
	_ENUM( ESR_ORDER_TO_GLOBAL_SERVER_NOT )
//#endif SERV_INSERT_GLOBAL_SERVER
	//}} 2011. 04. 13  김민성  글로벌 서버 추가

    _ENUM( ELOG_GET_PURCHASED_CASH_ITEM_NOT )

    _ENUM( DBE_EXPAND_INVENTORY_SLOT_REQ )
    _ENUM( DBE_EXPAND_INVENTORY_SLOT_ACK )


	//{{ 2008. 12. 14  최육사	캐릭터 슬롯 확장
	_ENUM( DBE_EXPAND_CHAR_SLOT_REQ )
	_ENUM( DBE_EXPAND_CHAR_SLOT_ACK )
	//}}

	//{{ 2008. 5. 5  최육사  장바구니 얻어오기
	_ENUM( DBE_GET_WISH_LIST_REQ )
	_ENUM( DBE_GET_WISH_LIST_ACK )
	//}}

	_ENUM( DBE_UPDATE_IS_LOGIN_NOT )

	//{{ 2008. 5. 19  최육사  
	_ENUM( ENX_UPDATE_PRODUCT_LIST_NOT )
	//}}

	//{{ 2008. 5. 19  최육사  체험ID 이벤트
	_ENUM( DBE_UPDATE_EVENT_TIME_REQ )	
	_ENUM( DBE_UPDATE_EVENT_TIME_ACK )	
	//}}
	
	_ENUM( ELOG_ITEM_ABUSER_LOG_NOT )
	_ENUM( ELOG_ENCHANT_ABUSER_LOG_NOT )
	_ENUM( ELOG_ED_ABUSER_LOG_NOT )

	//{{ 2008. 5. 28  최육사  아이템 슬롯 정보 업데이트
	_ENUM( DBE_UPDATE_INVENTORY_ITEM_POS_NOT )
	//}}

	_ENUM( DBE_AGREE_HACK_USER_REQ )
	_ENUM( DBE_AGREE_HACK_USER_ACK )
	_ENUM( DBE_REPORT_HACK_USER_NOT )

	//{{ 2008. 6. 16  최육사  던전 컨티뉴 시간 멈추기
	_ENUM( ERM_STOP_DUNGEON_CONTINUE_TIME_REQ )
	_ENUM( ERM_STOP_DUNGEON_CONTINUE_TIME_ACK )
	//}}

	//{{ 2008. 6. 20  최육사  선물하기
	_ENUM( ELG_PRESENT_CASH_ITEM_REQ )
	_ENUM( ELG_PRESENT_CASH_ITEM_ACK )	
	_ENUM( DBE_PRESENT_CASH_ITEM_CHECK_NICKNAME_REQ )
	_ENUM( DBE_PRESENT_CASH_ITEM_CHECK_NICKNAME_ACK )
	_ENUM( ELG_PRESENT_MESSAGE_TO_RECEIVER_NOT )
	//}}

	//{{ 2009. 7. 6  최육사		랭킹 개편	
	_ENUM( DBE_GET_HENIR_RANKING_INFO_REQ )				// DB로부터 헤니르 시공 랭킹 리스트 받기 요청
	_ENUM( DBE_GET_HENIR_RANKING_INFO_ACK )				// DB로부터 헤니르 시공 랭킹 리스트 받기 응답
	_ENUM( DBE_GET_WEB_RANKING_INFO_REQ )				// DB로부터 홈페이지 랭킹 리스트 받기 요청
	_ENUM( DBE_GET_WEB_RANKING_INFO_ACK )				// DB로부터 홈페이지 랭킹 리스트 받기 응답
	_ENUM( ELG_GET_WEB_RANKING_REFRESH_NOT )			// 로그인서버의 대전&던전 랭킹 리스트 갱신 요청
	_ENUM( ELG_WEB_RANKING_REFRESH_NOT )				// 로그인서버의 대전&던전 랭킹 리스트 갱신
	_ENUM( DBE_BACKUP_RANKING_INFO_NOT )				// DB에 랭킹정보 백업
	_ENUM( DBE_DELETE_RANKING_INFO_NOT )				// DB에 저장된 해당 타입의 랭킹 삭제
	_ENUM( ELG_GET_RANKING_FOR_GS_RANKING_MANAGER_REQ )	// 게임서버에 있는 GSRankingManager가 로그인서버의 랭킹정보 요청
	_ENUM( ELG_GET_RANKING_FOR_GS_RANKING_MANAGER_ACK )	// 게임서버에 있는 GSRankingManager가 로그인서버의 랭킹정보 요청
	_ENUM( ELG_HENIR_RANKING_REFRESH_NOT )				// 로그인서버의 RankingManager가 게임서버들에게 헤니르 시공 랭킹정보 업데이트
	_ENUM( ELG_NEW_RECORD_HENIR_RANKING_NOT )			// 유저가 새로운 랭킹 레코드 기록 요청함
	_ENUM( ELG_NEW_RECORD_RANKING_SUCCESS_NOT )			// 유저가 새로운 랭킹에 등록되었음!
	_ENUM( ELG_CLEAR_RANKING_NOT )						// 수동으로 랭킹 초기화 하는 이벤트
	//}}

	//{{ 2009. 7. 31  최육사	랭킹 추가 기능
	_ENUM( ELG_ADMIN_NEW_RECORD_TEST_NOT )
	_ENUM( ELG_ADMIN_NEW_RECORD_NOT )
	_ENUM( ELG_ADMIN_DELETE_RECORD_NOT )
	//}}

	//{{ 2008. 9. 3  최육사		속성강화
	_ENUM( DBE_ATTRIB_ENCHANT_ITEM_REQ )
	_ENUM( DBE_ATTRIB_ENCHANT_ITEM_ACK )
	_ENUM( DBE_IDENTIFY_ITEM_REQ )
	_ENUM( DBE_IDENTIFY_ITEM_ACK )
	//}}

	//{{ 2008. 9. 26  최육사	우체국 블랙리스트
	_ENUM( DBE_NEW_POST_BLACK_LIST_REQ )
	_ENUM( DBE_NEW_POST_BLACK_LIST_ACK )
	_ENUM( DBE_DEL_POST_BLACK_LIST_REQ )
	_ENUM( DBE_DEL_POST_BLACK_LIST_ACK )
	//}}

	//{{ 2008. 10. 7  최육사	타이틀
	_ENUM( DBE_INSERT_TITLE_REQ )
	_ENUM( DBE_INSERT_TITLE_ACK )
	_ENUM( ELG_INSERT_TITLE_NOT )
	_ENUM( ELG_RANKING_TITLE_REWARD_NOT )
	//}}

	//{{ 2008. 10. 22  최육사	캐쉬 분해 로그
	_ENUM( ELOG_CASH_ITEM_RESOLVE_LOG_NOT )
	//}}

	//{{ 2008. 11. 10  최육사	아이템 강화시 파괴로그
	_ENUM( ELOG_ENCHANT_ITEM_BREAK_LOG_NOT )
	//}}

	//{{ 2008. 10. 30  최육사	어뷰저 리스트
	_ENUM( DBE_ABUSER_LIST_REQ )
	_ENUM( DBE_ABUSER_LIST_ACK )
	//}}

	//{{ 2008. 12. 21  최육사	아이템 복구
	_ENUM( DBE_RESTORE_ITEM_REQ )
	_ENUM( DBE_RESTORE_ITEM_ACK )
	_ENUM( ELOG_RESTORE_ITEM_LOG_NOT )
	//}}

	//{{ 2008. 12. 25  최육사	부여
	_ENUM( DBE_ENCHANT_ATTACH_ITEM_REQ )
	_ENUM( DBE_ENCHANT_ATTACH_ITEM_ACK )
	_ENUM( ELOG_ATTACH_ITEM_ENCHANT_LOG_NOT )
	//}}

	//{{ 2008. 11. 18  최육사	아이템 교환
	_ENUM( DBE_ITEM_EXCHANGE_REQ )
	_ENUM( DBE_ITEM_EXCHANGE_ACK )	
	//}}

	//{{ 2008. 11. 19  최육사	어뷰저 자동 등록
	_ENUM( DBE_REG_ABUSER_AUTOMATIC_NOT )
	//}}

	//{{ 2008. 12. 30  최육사	매력아이템 로그
	_ENUM( ELOG_CHARM_ITEM_LOG_NOT )	
	//}}

	//{{ 2008. 11. 4  최육사	광장 개편
	_ENUM( ERM_OPEN_FIELD_NOT )
	_ENUM( ERM_UPDATE_FIELD_INFO_NOT )

	_ENUM( ERM_JOIN_FIELD_REQ )
	_ENUM( ERM_JOIN_FIELD_ACK )
	_ENUM( ERM_LEAVE_FIELD_REQ )
	_ENUM( ERM_LEAVE_FIELD_ACK )

	_ENUM( ETR_CHANGE_USER_LIST_IN_SECTOR_NOT )

	_ENUM( ERM_FIELD_UNIT_SYNC_DATA_NOT )
	_ENUM( ERM_FIELD_UNIT_SYNC_DATA_BROAD_NOT )
	_ENUM( ETR_FIELD_UNIT_SYNC_DATA_BROAD_NOT )
	//}}

	//{{ 2009. 1. 13  최육사	필드 유저 리스트
	_ENUM( ERM_FIELD_USER_LIST_REQ )
	_ENUM( ERM_FIELD_USER_LIST_ACK )
	//}}

	//{{ 2008. 12. 9  최육사	필드 옵션
	_ENUM( ERM_OPTION_UPDATE_NOT )
	_ENUM( ERM_UPDATE_PARTY_NOT )
	_ENUM( ETR_UPDATE_PARTY_NOT )
	//}}

	//{{ 2009. 1. 16  최육사	채널리스트
	_ENUM( DBE_CHANNEL_LIST_REQ )
	_ENUM( DBE_CHANNEL_LIST_ACK )
	//}}

	//{{ 2009. 2. 4  최육사		던전 리플레이
	//_ENUM( ERM_PARTY_GAME_REPLAY_START_REQ )
	//_ENUM( ERM_PARTY_GAME_REPLAY_START_ACK )
	//_ENUM( ERM_PARTY_GAME_REPLAY_START_NOT )
	//}}

	//{{ 2008. 12. 31  최육사	덤프
	_ENUM( DMP_DUMP_EVENT_NOT )
	_ENUM( DMP_DUMP_RANKING_MANAGER_NOT )
	//}}

	//{{ 2009. 4. 1  최육사		친구차단옵션
	_ENUM( ELG_UPDATE_DENY_FRIEND_SHIP_NOT )
	//}}

	//{{ 2009. 4. 7  최육사		닉네임 변경
	_ENUM( DBE_DELETE_NICK_NAME_REQ )
	_ENUM( DBE_DELETE_NICK_NAME_ACK )
	_ENUM( DBE_CHANGE_NICK_NAME_REQ )
	_ENUM( DBE_CHANGE_NICK_NAME_ACK )
	_ENUM( ELOG_DELETE_NICK_NAME_NOT )
	_ENUM( ELOG_CHANGE_NICK_NAME_NOT )
	//}}

	//{{ 2009. 4. 7  최육사		친구정보
	_ENUM( ELG_FIND_FRIEND_UNIT_INFO_REQ )
	_ENUM( ELG_FIND_FRIEND_UNIT_INFO_ACK )
	_ENUM( ERM_UPDATE_FRIEND_NOT )
	//}}

	//{{ 2009. 4. 20  최육사	초대하기
	_ENUM( ELG_INVITE_PVP_ROOM_REQ )
	_ENUM( ELG_INVITE_PVP_ROOM_ACK )
	_ENUM( ELG_INVITE_PVP_ROOM_NOT )
	//}}

	//{{ 2009. 4. 22  최육사	대전유저리스트
	_ENUM( ECN_NEW_PVP_USER_INFO_NOT )
	_ENUM( ECN_UPDATE_PVP_USER_INFO_NOT )
	_ENUM( ECN_CHECK_INVALID_PVP_USER_NOT )
	//}}


	//{{ 2009.05.06.hoons.캐릭터 메신져 아이디 요청.
	_ENUM( DBE_GET_MY_MESSENGER_SN_REQ )
	_ENUM( DBE_GET_MY_MESSENGER_SN_ACK )
	//}} hoons

	//{{ 2009. 5. 8  최육사		실시간 레벨업
	_ENUM( ERM_CHAR_LEVEL_UP_NOT )
	//}}

	//{{ 2009. 5. 21  최육사	내구도 소모 개편
	_ENUM( ERM_ZERO_ENDURANCE_ITEM_IN_ROOM_NOT )
	//}}

	//{{ 2009. 5. 23  최육사	시간드롭
	_ENUM( DBE_GET_TIME_DROP_INFO_REQ )
	_ENUM( DBE_GET_TIME_DROP_INFO_ACK )
	_ENUM( DBE_CHECK_TIME_DROP_RESULT_REQ )
	_ENUM( DBE_CHECK_TIME_DROP_RESULT_ACK )
	//}}

	//{{ 2009. 6. 3  최육사		확성기	
	_ENUM( ECN_MEGAPHONE_MESSAGE_NOT )
	_ENUM( ELOG_MEGAPHONE_LOG_NOT )
	//}}

	//{{ 2009. 7. 10  최육사	사기 시스템
	_ENUM( ERM_INCREASE_PARTY_FEVER_NOT )
	//}}
	//{{ 2012. 05. 10	최육사	배틀필드 시스템
//#ifdef SERV_BATTLE_FIELD_SYSTEM
	_ENUM( ERM_MAX_PARTY_FEVER_NOT )
	_ENUM( EPM_MAX_PARTY_FEVER_NOT )
//#endif SERV_BATTLE_FIELD_SYSTEM
	//}}

	//{{ 2009. 7. 20  최육사	비밀 스테이지
	_ENUM( ERM_DUNGEON_SECRET_STAGE_ENTER_CHECK_REQ )	// 비밀 스테이지로 입장가능한지 서버에 물어보는 패킷, 방장 -> 서버
	_ENUM( ERM_DUNGEON_SECRET_STAGE_ENTER_CHECK_ACK )	// 서버 -> 방장
	_ENUM( ERM_DUNGEON_SECRET_STAGE_ENTER_CHECK_NOT )	// 비밀 스테이지로 입장가능한 경우에 서버 -> 모든 유저

	_ENUM( ERM_DUNGEON_SECRET_STAGE_ENTER_SELECT_NOT )	// 모든 유저가 각각 비밀 스테이지로 입장 할지 말지 선택을 서버로 알리는 패킷

	_ENUM( ERM_DUNGEON_SECRET_STAGE_ENTER_RESULT_NOT )	// 서버가 실제로 비밀 스테이지로 진행하라는 것을 모든 유저에게 알리는 패킷 (단, 방장만 이 패킷을 받아서 처리한다)
	//}}

	//{{ 2009. 7. 27  최육사	헤니르 클리어 로그
	_ENUM( ELOG_HENIR_DUNGEON_CLEAR_NOT )
	//}}

    _ENUM( DBE_REQUEST_FRIEND_REQ )
    _ENUM( DBE_REQUEST_FRIEND_ACK )
    _ENUM( ELG_REQUEST_FRIEND_NOT )

    _ENUM( DBE_ACCEPT_FRIEND_REQ )
    _ENUM( DBE_ACCEPT_FRIEND_ACK )
    _ENUM( ELG_ACCEPT_FRIEND_NOT )

    _ENUM( DBE_DENY_FRIEND_REQ )
    _ENUM( DBE_DENY_FRIEND_ACK )
    _ENUM( ELG_DENY_FRIEND_NOT )

    _ENUM( DBE_BLOCK_FRIEND_REQ )
    _ENUM( DBE_BLOCK_FRIEND_ACK )
    _ENUM( ELG_BLOCK_FRIEND_NOT )

    _ENUM( DBE_UNBLOCK_FRIEND_REQ )
    _ENUM( DBE_UNBLOCK_FRIEND_ACK )
    _ENUM( ELG_UNBLOCK_FRIEND_NOT )

    _ENUM( DBE_DELETE_FRIEND_REQ )
    _ENUM( DBE_DELETE_FRIEND_ACK )
    _ENUM( ELG_DELETE_FRIEND_NOT )

    _ENUM( DBE_MOVE_FRIEND_REQ )
    _ENUM( DBE_MOVE_FRIEND_ACK )

    _ENUM( DBE_MAKE_FRIEND_GROUP_REQ )
    _ENUM( DBE_MAKE_FRIEND_GROUP_ACK )

    _ENUM( DBE_RENAME_FRIEND_GROUP_REQ )
    _ENUM( DBE_RENAME_FRIEND_GROUP_ACK )

    _ENUM( DBE_DELETE_FRIEND_GROUP_REQ )
    _ENUM( DBE_DELETE_FRIEND_GROUP_ACK )

    _ENUM( DBE_FRIEND_MESSAGE_NOT )
    _ENUM( ELG_FRIEND_POSITION_UPDATE_NOT )

	//{{ 2009. 7. 29  최육사	item set cheat
	_ENUM( DBE_ADMIN_GET_ITEM_SET_NOT )
	//}}

	//{{ 2009. 8. 27  최육사	밀봉
	_ENUM( DBE_SEAL_ITEM_REQ )
	_ENUM( DBE_SEAL_ITEM_ACK )
	_ENUM( DBE_UNSEAL_ITEM_REQ )
	_ENUM( DBE_UNSEAL_ITEM_ACK )
	//}}

	//09. 08. 08 김정협 Gash 인증관련 DB 패킷 / 이벤트 생성
	_ENUM( DBE_GASH_USER_LOGIN_REQ )
	_ENUM( DBE_GASH_USER_LOGIN_ACK )

	//09. 08. 06 김정협 Gash 인증관련 패킷 / 이벤트 생성
	_ENUM( EGASH_AUTHENTICATION_REQ )
	_ENUM( EGASH_AUTHENTICATION_ACK )

	//09. 08. 06 김정협 Gash 인증관련 패킷 / 이벤트 생성
	_ENUM( EGASH_AUTHORIZATION_REQ )
	_ENUM( EGASH_AUTHORIZATION_ACK )

	//09. 08. 06 김정협 Gash 인증관련 패킷 / 이벤트 생성
	_ENUM( EGASH_ACCOUNTING_REQ )
	_ENUM( EGASH_ACCOUNTING_ACK )
	
	//{{ 2009. 9. 1  최육사		비정상종료통계
	_ENUM( ELOG_ABNORMAL_DISCONNECT )
	//}}
	//{{ 2009. 9. 9  최육사		밀봉
	_ENUM( ELOG_USE_SEAL_ITEM_NOT )
	//}}

	//////////////////////////////////////////////////////////////////////////
	//{{ 2009. 9. 17  최육사	길드	
	_ENUM( DBE_CREATE_GUILD_REQ )
	_ENUM( DBE_CREATE_GUILD_ACK )

	_ENUM( ELG_GET_GUILD_INFO_REQ )
	_ENUM( ELG_GET_GUILD_INFO_ACK )
	_ENUM( DBE_GET_GUILD_INFO_REQ )
	_ENUM( DBE_GET_GUILD_INFO_ACK )

	_ENUM( ELG_CREATE_GUILD_RESULT_REQ )
	_ENUM( ELG_CREATE_GUILD_RESULT_ACK )

	_ENUM( ELG_GET_GUILD_USER_LIST_REQ )
	_ENUM( ELG_GET_GUILD_USER_LIST_ACK )
	
	_ENUM( ELG_UPDATE_GUILD_MEMBER_INFO_NOT )

	_ENUM( ELG_GUILD_INFO_NOT )
	_ENUM( ELG_GUILD_MESSAGE_NOT )

	_ENUM( ELG_INVITE_GUILD_REQ )
	_ENUM( ELG_INVITE_GUILD_ACK )
	_ENUM( ELG_INVITE_GUILD_FIND_USER_REQ )
	_ENUM( ELG_INVITE_GUILD_FIND_USER_ACK )
	_ENUM( DBE_INVITE_GUILD_NICKNAME_CHECK_REQ )
	_ENUM( DBE_INVITE_GUILD_NICKNAME_CHECK_ACK )

	_ENUM( ELG_INVITE_GUILD_REPLY_REQ )
	_ENUM( ELG_INVITE_GUILD_REPLY_ACK )
	_ENUM( ELG_INVITE_GUILD_REPLY_DENY_NOT )
	_ENUM( DBE_JOIN_GUILD_REQ )
	_ENUM( DBE_JOIN_GUILD_ACK )
	_ENUM( ELG_JOIN_GUILD_REQ )
	_ENUM( ELG_JOIN_GUILD_ACK )

	_ENUM( ELG_CHECK_CHANGE_GUILD_MEMBER_GRADE_REQ )
	_ENUM( ELG_CHECK_CHANGE_GUILD_MEMBER_GRADE_ACK )
	_ENUM( DBE_CHANGE_GUILD_MEMBER_GRADE_REQ )
	_ENUM( DBE_CHANGE_GUILD_MEMBER_GRADE_ACK )
	_ENUM( ELG_UPDATE_CHANGE_GUILD_MEMBER_GRADE_NOT )

	_ENUM( DBE_CHANGE_GUILD_MESSAGE_REQ )
	_ENUM( DBE_CHANGE_GUILD_MESSAGE_ACK )
	_ENUM( ELG_UPDATE_CHANGE_GUILD_MESSAGE_NOT )

	_ENUM( DBE_KICK_GUILD_MEMBER_REQ )
	_ENUM( DBE_KICK_GUILD_MEMBER_ACK )
	_ENUM( ELG_UPDATE_KICK_GUILD_MEMBER_NOT )
	_ENUM( ELG_KICK_RESULT_LETTER_NOT )

	_ENUM( DBE_CHANGE_GUILD_MEMBER_MESSAGE_REQ )
	_ENUM( DBE_CHANGE_GUILD_MEMBER_MESSAGE_ACK )
	_ENUM( ELG_UPDATE_CHANGE_GUILD_MEMBER_MESSAGE_NOT )

	_ENUM( DBE_DISBAND_GUILD_REQ )
	_ENUM( DBE_DISBAND_GUILD_ACK )
	_ENUM( ELG_UPDATE_DISBAND_GUILD_NOT )

	_ENUM( ELG_CHECK_EXPAND_GUILD_MAX_MEMBER_REQ )
	_ENUM( ELG_CHECK_EXPAND_GUILD_MAX_MEMBER_ACK )
	_ENUM( DBE_EXPAND_GUILD_MAX_MEMBER_REQ )
	_ENUM( DBE_EXPAND_GUILD_MAX_MEMBER_ACK )
	_ENUM( DLG_UPDATE_EXPAND_GUILD_MAX_MEMBER_NOT )

	//{{ 2009. 10. 27  최육사	길드레벨
	_ENUM( DBE_UPDATE_GUILD_EXP_REQ )
	_ENUM( DBE_UPDATE_GUILD_EXP_ACK )
	_ENUM( ELG_UPDATE_GUILD_EXP_NOT )
	
	_ENUM( DBE_GUILD_LEVEL_UP_REQ )
	_ENUM( DBE_GUILD_LEVEL_UP_ACK )
	_ENUM( ELG_GUILD_LEVEL_UP_NOTIFY_NOT )
	//}}

	//{{ 2012. 02. 22	박세훈	길드 이름 변경권
//#ifdef SERV_GUILD_CHANGE_NAME
	_ENUM( ELG_CREATE_GUILD_REQ )
	_ENUM( ELG_CREATE_GUILD_ACK )

	// To Guild Name Check
	_ENUM( ELG_CHANGE_GUILD_NAME_CHECK_REQ )
	_ENUM( ELG_CHANGE_GUILD_NAME_CHECK_ACK )
    _ENUM( DBE_CHANGE_GUILD_NAME_CHECK_REQ )
	_ENUM( DBE_CHANGE_GUILD_NAME_CHECK_ACK )

	// To Change Guild Name
	_ENUM( ELG_CHANGE_GUILD_NAME_REQ )
	_ENUM( ELG_CHANGE_GUILD_NAME_ACK )
	_ENUM( DBE_CHANGE_GUILD_NAME_REQ )
	_ENUM( DBE_CHANGE_GUILD_NAME_ACK )
	_ENUM( ELG_CHANGE_GUILD_NAME_TIME_CHECK_REQ )
	_ENUM( ELG_CHANGE_GUILD_NAME_TIME_CHECK_ACK )

	_ENUM( ELG_CHANGE_GUILD_NAME_RESULT_REQ )
//#endif SERV_GUILD_CHANGE_NAME
	//}}

	//}}
	//////////////////////////////////////////////////////////////////////////

	//{{ 2009. 9. 23  최육사	1차전직캐쉬템	
	_ENUM( ERM_CHANGE_FIELD_USER_INFO_NOT )
	_ENUM( ETR_CHANGE_FIELD_USER_INFO_NOT )
	_ENUM( ERM_CHANGE_ROOM_USER_INFO_NOT )
	_ENUM( ERM_CHANGE_SQUARE_USER_INFO_NOT )
	//}}

	//{{ 2009. 10. 26  최육사	트래픽어택
	_ENUM( ELOG_TRAFFIC_ATTACKER_LOG_NOT )
	//}}

	//{{ 2009. 10. 27  최육사	랭킹
	_ENUM( ELG_FIND_DELETE_CHAR_IN_RANKING_NOT )
	//}}

	//////////////////////////////////////////////////////////////////////////
	//{{ 2009. 11. 23  최육사	길드스킬

	_ENUM( ELG_GET_GUILD_SKILL_REQ )
	_ENUM( ELG_GET_GUILD_SKILL_ACK )	
	_ENUM( ELG_GET_GUILD_SKILL_NOT )
	_ENUM( DBE_GET_GUILD_SKILL_REQ )
	_ENUM( DBE_GET_GUILD_SKILL_ACK )

	_ENUM( ELG_RESET_GUILD_SKILL_REQ )
	_ENUM( ELG_RESET_GUILD_SKILL_ACK )
	_ENUM( ELG_RESET_GUILD_SKILL_NOT )
	_ENUM( ELG_RESET_GUILD_SKILL_DEL_ITEM_REQ )
	_ENUM( ELG_RESET_GUILD_SKILL_DEL_ITEM_ACK )
	_ENUM( DBE_RESET_GUILD_SKILL_REQ )
	_ENUM( DBE_RESET_GUILD_SKILL_ACK )

	_ENUM( ELG_INIT_GUILD_SKILL_REQ )
	_ENUM( ELG_INIT_GUILD_SKILL_ACK )
	_ENUM( ELG_INIT_GUILD_SKILL_NOT )
	_ENUM( ELG_INIT_GUILD_SKILL_DEL_ITEM_REQ )
	_ENUM( ELG_INIT_GUILD_SKILL_DEL_ITEM_ACK )
	_ENUM( DBE_INIT_GUILD_SKILL_REQ )
	_ENUM( DBE_INIT_GUILD_SKILL_ACK )

	_ENUM( ELG_INSERT_GUILD_CASH_SKILL_POINT_NOT )
	_ENUM( DBE_INSERT_GUILD_CASH_SKILL_POINT_REQ )
	_ENUM( DBE_INSERT_GUILD_CASH_SKILL_POINT_ACK )

	_ENUM( DBE_EXPIRE_GUILD_CASH_SKILL_POINT_REQ )
	_ENUM( DBE_EXPIRE_GUILD_CASH_SKILL_POINT_ACK )
	_ENUM( ELG_EXPIRE_GUILD_CASH_SKILL_POINT_NOT )

	_ENUM( ERM_CHANGE_SKILL_INFO_IN_ROOM_NOT )
	
	_ENUM( ELG_ADMIN_GET_GUILD_SKILL_POINT_REQ )
	_ENUM( ELG_ADMIN_GET_GUILD_SKILL_POINT_ACK )
	_ENUM( DBE_ADMIN_GET_GUILD_SKILL_POINT_REQ )
	_ENUM( DBE_ADMIN_GET_GUILD_SKILL_POINT_ACK )

	//}}
	//////////////////////////////////////////////////////////////////////////

	//////////////////////////////////////////////////////////////////////////
	// 던전,대전 아이템 기능.
	_ENUM( ERM_CREATE_PVP_ITEM_REQ )
	_ENUM( ERM_CREATE_PVP_ITEM_ACK )
	_ENUM( ERM_CREATE_PVP_ITEM_NOT )

	_ENUM( ERM_CHANGE_PVP_ITEM_NOT )

	_ENUM( ERM_CHANGE_PVP_ITEMMODE_REQ )
	_ENUM( ERM_CHANGE_PVP_ITEMMODE_ACK )
	_ENUM( ERM_CHANGE_PVP_ITEMMODE_NOT )

	// 던전,대전 아이템 기능.
	//////////////////////////////////////////////////////////////////////////

	//{{ 2009. 12. 8  최육사	크리스마스이벤트
	_ENUM( DBE_CHECK_TIME_EVENT_COMPLETE_REQ )
	_ENUM( DBE_CHECK_TIME_EVENT_COMPLETE_ACK )
	//}}

	//{{ 2009. 12. 14  최육사	헤니르임시인벤
	_ENUM( ERM_CLEAR_TEMP_INVENTORY_NOT )
	//}}

	//{{ dmlee 2009/12/15 PVP 게임 테스트 
	_ENUM( ERM_CHANGE_PVP_GAME_OPTION_REQ )
	_ENUM( ERM_CHANGE_PVP_GAME_OPTION_ACK )
	_ENUM( ERM_CHANGE_PVP_GAME_OPTION_NOT )
	//}} dmlee 2009/12/15 PVP 게임 테스트 

	//{{ 2009. 12. 16  최육사	동접툴
	_ENUM( DBE_GET_CONCURRENT_USER_INFO_REQ )
	_ENUM( DBE_GET_CONCURRENT_USER_INFO_ACK )
	//}}

	//{{ 2009. 12. 29  최육사	NPCKILLALL해킹방지
	_ENUM( ERM_DUNGEON_KILLALLNPC_CHECK_REQ )
	_ENUM( ERM_DUNGEON_KILLALLNPC_CHECK_ACK )
	//}}

	//////////////////////////////////////////////////////////////////////////
	//{{ 2010. 01. 04  최육사	길드 광고
	_ENUM( DBE_GET_GUILD_BOARD_INFO_REQ )
	_ENUM( DBE_GET_GUILD_BOARD_INFO_ACK )

	_ENUM( ELG_GET_GUILD_AD_LIST_REQ )
	_ENUM( ELG_GET_GUILD_AD_LIST_ACK )

	_ENUM( ELG_GET_GUILD_SKILL_IN_BOARD_REQ )
	_ENUM( ELG_GET_GUILD_SKILL_IN_BOARD_ACK )
	_ENUM( DBE_GET_GUILD_SKILL_IN_BOARD_REQ )
	_ENUM( DBE_GET_GUILD_SKILL_IN_BOARD_ACK )

	_ENUM( ELG_REGISTRATION_GUILD_AD_REQ )
	_ENUM( ELG_REGISTRATION_GUILD_AD_ACK )
	_ENUM( DBE_REGISTRATION_GUILD_AD_REQ )
	_ENUM( DBE_REGISTRATION_GUILD_AD_ACK )

	_ENUM( ELG_MODIFY_REG_GUILD_AD_REQ )
	_ENUM( ELG_MODIFY_REG_GUILD_AD_ACK )
	_ENUM( DBE_MODIFY_REG_GUILD_AD_REQ )
	_ENUM( DBE_MODIFY_REG_GUILD_AD_ACK )

	_ENUM( ELG_APPLY_JOIN_GUILD_REQ )
	_ENUM( ELG_APPLY_JOIN_GUILD_ACK )
	_ENUM( DBE_APPLY_JOIN_GUILD_REQ )
	_ENUM( DBE_APPLY_JOIN_GUILD_ACK )

	_ENUM( ELG_GET_APPLY_JOIN_GUILD_LIST_REQ )
	_ENUM( ELG_GET_APPLY_JOIN_GUILD_LIST_ACK )

	_ENUM( ELG_ACCEPT_JOIN_GUILD_REQ )
	_ENUM( ELG_ACCEPT_JOIN_GUILD_ACK )
	_ENUM( DBE_ACCEPT_JOIN_GUILD_REQ )
	_ENUM( DBE_ACCEPT_JOIN_GUILD_ACK )
	_ENUM( DBE_DELETE_APLLY_FOR_ACCEPT_JOIN_GUILD_REQ )
	_ENUM( DBE_DELETE_APLLY_FOR_ACCEPT_JOIN_GUILD_ACK )
	_ENUM( ELG_SEND_LETTER_JOIN_GUILD_NOT )

	_ENUM( ELG_DELETE_APPLY_JOIN_GUILD_REQ )
	_ENUM( ELG_DELETE_APPLY_JOIN_GUILD_ACK )
	_ENUM( DBE_DELETE_APPLY_JOIN_GUILD_REQ )
	_ENUM( DBE_DELETE_APPLY_JOIN_GUILD_ACK )

	_ENUM( DBE_DELETE_GUILD_AD_LIST_NOT )
	//}}
	//////////////////////////////////////////////////////////////////////////

	//{{ 2010. 01. 11  최육사	추천인리스트
	_ENUM( DBE_GET_RECOMMEND_USER_LIST_REQ )
	_ENUM( DBE_GET_RECOMMEND_USER_LIST_ACK )
	_ENUM( ELG_GET_RECOMMEND_USER_LIST_REQ )
	_ENUM( ELG_GET_RECOMMEND_USER_LIST_ACK )

	_ENUM( ELG_RECOMMEND_USER_INFO_NOT )
	//}}

	//{{ 2010. 01. 27  최육사	방 정보
	_ENUM( ERM_ROOM_COUNT_INFO_NOT )
	//}}

	//{{ 2010. 02. 16  최육사	해킹툴 리스트
	_ENUM( DBE_CHECK_HACKING_TOOL_LIST_REQ )
	_ENUM( DBE_CHECK_HACKING_TOOL_LIST_ACK )
	//}}

	//////////////////////////////////////////////////////////////////////////
	//{{ 2010. 02. 16  최육사	채널파티통합
	//{{ 2011. 12. 23	최육사	배틀필드 시스템
//#ifdef SERV_BATTLE_FIELD_SYSTEM
	_ENUM( ELG_INVITE_PARTY_FIND_RECEIVER_REQ )
	_ENUM( ELG_INVITE_PARTY_FIND_RECEIVER_ACK )
	_ENUM( EGB_INVITE_PARTY_FIND_RECEIVER_REQ )
	_ENUM( EGB_INVITE_PARTY_FIND_RECEIVER_ACK )

	_ENUM( DBE_CHECK_NICKNAME_FOR_INVITE_PARTY_REQ )
	_ENUM( DBE_CHECK_NICKNAME_FOR_INVITE_PARTY_ACK )

	_ENUM( ELG_INVITE_PARTY_GET_RECEIVER_USER_INFO_REQ )
	_ENUM( ELG_INVITE_PARTY_GET_RECEIVER_USER_INFO_ACK )
	_ENUM( EGB_INVITE_PARTY_GET_RECEIVER_USER_INFO_REQ )
	_ENUM( EGB_INVITE_PARTY_GET_RECEIVER_USER_INFO_ACK )

	_ENUM( EPM_INVITE_PARTY_REQ )
	_ENUM( EPM_INVITE_PARTY_ACK )
	_ENUM( EPM_INVITE_PARTY_NOT )
	
	_ENUM( EPM_INVITE_PARTY_REPLY_NOT )
	_ENUM( EPM_INVITE_PARTY_DENY_NOT )

	_ENUM( EPM_CREATE_PARTY_BY_INVITE_REQ )
	_ENUM( EPM_CREATE_PARTY_BY_INVITE_ACK )
	
	_ENUM( EPM_JOIN_PARTY_NOT )
	_ENUM( EPM_CLOSE_PARTY_NOT )

	_ENUM( EPM_LEAVE_PARTY_REQ )
	_ENUM( EPM_LEAVE_PARTY_ACK )
	_ENUM( EPM_LEAVE_PARTY_NOT )
	
	_ENUM( EPM_UPDATE_PARTY_USER_INFO_NOT )
	_ENUM( EPM_UPDATE_PARTY_USER_INFO_BROAD_NOT )

	_ENUM( EPM_PARTY_CHANGE_READY_REQ )
	_ENUM( EPM_PARTY_CHANGE_READY_ACK )
	_ENUM( EPM_PARTY_CHANGE_READY_NOT )

	_ENUM( EPM_PARTY_CHANGE_DUNGEON_REQ )
	_ENUM( EPM_PARTY_CHANGE_DUNGEON_ACK )
	_ENUM( EPM_PARTY_CHANGE_DUNGEON_NOT )

	_ENUM( EPM_PARTY_GAME_START_REQ )
	_ENUM( EPM_PARTY_GAME_START_ACK )

	//{{ 2012. 01. 12	최육사	배틀필드 시스템
//#ifdef SERV_BATTLE_FIELD_SYSTEM
	_ENUM( EPM_CHECK_DUNGEON_GAME_PLAY_CONDITION_REQ )
	_ENUM( EPM_CHECK_DUNGEON_GAME_PLAY_CONDITION_ACK )

	_ENUM( EPM_PARTY_GAME_START_OPINION_CHECK_NOT )
	_ENUM( EPM_PARTY_GAME_START_OPINION_CHECK_REPLY_NOT )

	_ENUM( EPM_PARTY_GAME_START_FAILED_NOT )

	_ENUM( EPM_LEAVE_CANDIDATE_PARTY_NOT )
//#endif SERV_BATTLE_FIELD_SYSTEM
	//}}

	_ENUM( EPM_CHECK_FOR_PARTY_GAME_START_REQ )
	_ENUM( EPM_CHECK_FOR_PARTY_GAME_START_ACK )
	_ENUM( EPM_PARTY_OPEN_DUNGEON_ROOM_NOT )
	//_ENUM( EPM_PARTY_GAME_REPLAY_START_NOT )

	_ENUM( EPM_END_GAME_NOT )

	_ENUM( EPM_PARTY_CHANGE_HOST_REQ )
	_ENUM( EPM_PARTY_CHANGE_HOST_ACK )
	_ENUM( EPM_CHECK_PARTY_CHANGE_HOST_REQ )
	_ENUM( EPM_CHECK_PARTY_CHANGE_HOST_ACK )
	_ENUM( EPM_PARTY_CHANGE_HOST_NOT )

	_ENUM( EPM_PARTY_CHANGE_NUM_OF_PER_REQ )
	_ENUM( EPM_PARTY_CHANGE_NUM_OF_PER_ACK )
	_ENUM( EPM_PARTY_CHANGE_NUM_OF_PER_NOT )

	_ENUM( EPM_PARTY_CHANGE_GET_ITEM_TYPE_REQ )
	_ENUM( EPM_PARTY_CHANGE_GET_ITEM_TYPE_ACK )
	_ENUM( EPM_PARTY_CHANGE_GET_ITEM_TYPE_NOT )

	_ENUM( EPM_CHAT_REQ )
	_ENUM( EPM_CHAT_ACK )
	_ENUM( EPM_CHAT_NOT )

	_ENUM( EPM_PARTY_BAN_USER_REQ )
	_ENUM( EPM_PARTY_BAN_USER_ACK )
	_ENUM( EPM_PARTY_BAN_USER_NOT )

	_ENUM( EPM_DUNGEON_SECRET_STAGE_ENTER_CHECK_REQ )
	_ENUM( EPM_DUNGEON_SECRET_STAGE_ENTER_CHECK_ACK )

	_ENUM( EPM_CHANGE_PARTY_FEVER_STATE_NOT )
	_ENUM( EPM_PARTY_FEVER_POINT_NOT )
	
	_ENUM( EPM_REQUEST_UPDATE_PARTY_MEMBER_LIST_NOT )
	_ENUM( EPM_SEND_UPDATE_PARTY_MEMBER_LIST_NOT )
	_ENUM( EPM_QUICK_SLOT_COOL_TIME_RESET_NOT )
	_ENUM( EPM_INCREASE_PARTY_FEVER_NOT )

	_ENUM( EPM_UPDATE_PARTY_IN_PARTY_LIST_NOT )
	//{{ 2012. 02. 28	최육사	배틀필드 시스템
//#ifdef SERV_BATTLE_FIELD_SYSTEM
	_ENUM( EPM_UPDATE_PARTY_FEVER_IN_PARTY_LIST_NOT )
//#endif SERV_BATTLE_FIELD_SYSTEM
	//}}
	_ENUM( EPM_OPEN_PARTY_LIST_NOT )
	_ENUM( EPM_CLOSE_PARTY_LIST_NOT )
	_ENUM( EPM_ADD_PARTY_LIST_NOT )
	_ENUM( EPM_DEL_PARTY_LIST_NOT )

	_ENUM( EPM_UPDATE_PARTY_MEMBER_IN_PARTY_LIST_NOT )
	_ENUM( EPM_ADD_PARTY_MEMBER_IN_PARTY_LIST_NOT )
	_ENUM( EPM_DEL_PARTY_MEMBER_IN_PARTY_LIST_NOT )

	_ENUM( EPM_CHECK_INVALID_USER_NOT )
//#else
	//_ENUM( EPM_CREATE_PARTY_REQ )
	//_ENUM( EPM_CREATE_PARTY_ACK )

	//_ENUM( EPM_JOIN_PARTY_REQ )
	//_ENUM( EPM_JOIN_PARTY_ACK )
	//_ENUM( EPM_JOIN_PARTY_INVITE_REPLY_NOT )
	//_ENUM( EPM_JOIN_PARTY_NOT )

	//_ENUM( EPM_JOIN_PARTY_INVITE_NOT )
	//_ENUM( EPM_JOIN_PARTY_INVITE_DENY_NOT )
	//_ENUM( EPM_INVITE_PARTY_DENY_NOT )

	//_ENUM( EPM_CHECK_JOIN_PARTY_USER_REQ )
	//_ENUM( EPM_CHECK_JOIN_PARTY_USER_ACK )

	//_ENUM( EPM_LEAVE_PARTY_REQ )
	//_ENUM( EPM_LEAVE_PARTY_ACK )
	//_ENUM( EPM_LEAVE_PARTY_NOT )

	//_ENUM( EPM_INVITE_PARTY_REQ )
	//_ENUM( EPM_INVITE_PARTY_ACK )
	//_ENUM( EPM_INVITE_PARTY_NOT )
	//_ENUM( EPM_INVITE_PARTY_REPLY_NOT )

	//_ENUM( EPM_UPDATE_PARTY_USER_INFO_NOT )
	//_ENUM( EPM_UPDATE_PARTY_USER_INFO_BROAD_NOT )

	//_ENUM( EPM_PARTY_CHANGE_READY_REQ )
	//_ENUM( EPM_PARTY_CHANGE_READY_ACK )
	//_ENUM( EPM_PARTY_CHANGE_READY_NOT )

	//_ENUM( EPM_PARTY_CHANGE_DUNGEON_REQ )
	//_ENUM( EPM_PARTY_CHANGE_DUNGEON_ACK )
	//_ENUM( EPM_PARTY_CHANGE_DUNGEON_NOT )

	//_ENUM( EPM_PARTY_GAME_START_REQ )
	//_ENUM( EPM_PARTY_GAME_START_ACK )
	//_ENUM( EPM_CHECK_FOR_PARTY_GAME_START_REQ )
	//_ENUM( EPM_CHECK_FOR_PARTY_GAME_START_ACK )
	//_ENUM( EPM_PARTY_OPEN_DUNGEON_ROOM_NOT )
	//_ENUM( EPM_PARTY_GAME_REPLAY_START_NOT )

	//_ENUM( EPM_END_GAME_NOT )

	//_ENUM( EPM_PARTY_TO_FIELD_MAP_REQ )
	//_ENUM( EPM_PARTY_TO_FIELD_MAP_ACK )

	//_ENUM( EPM_PARTY_CHANGE_NAME_REQ )
	//_ENUM( EPM_PARTY_CHANGE_NAME_ACK )
	//_ENUM( EPM_PARTY_CHANGE_NAME_NOT )

	//_ENUM( EPM_PARTY_CHANGE_PUBLIC_REQ )
	//_ENUM( EPM_PARTY_CHANGE_PUBLIC_ACK )
	//_ENUM( EPM_PARTY_CHANGE_PUBLIC_NOT )

	//_ENUM( EPM_PARTY_CHANGE_HOST_REQ )
	//_ENUM( EPM_PARTY_CHANGE_HOST_ACK )
	//_ENUM( EPM_CHECK_PARTY_CHANGE_HOST_REQ )
	//_ENUM( EPM_CHECK_PARTY_CHANGE_HOST_ACK )
	//_ENUM( EPM_PARTY_CHANGE_HOST_NOT )

	//_ENUM( EPM_PARTY_CHANGE_NUM_OF_PER_REQ )
	//_ENUM( EPM_PARTY_CHANGE_NUM_OF_PER_ACK )
	//_ENUM( EPM_PARTY_CHANGE_NUM_OF_PER_NOT )

	//_ENUM( EPM_PARTY_CHANGE_GET_ITEM_TYPE_REQ )
	//_ENUM( EPM_PARTY_CHANGE_GET_ITEM_TYPE_ACK )
	//_ENUM( EPM_PARTY_CHANGE_GET_ITEM_TYPE_NOT )

	//_ENUM( EPM_CHAT_REQ )
	//_ENUM( EPM_CHAT_ACK )
	//_ENUM( EPM_CHAT_NOT )

	//_ENUM( EPM_PARTY_BAN_USER_REQ )
	//_ENUM( EPM_PARTY_BAN_USER_ACK )
	//_ENUM( EPM_PARTY_BAN_USER_NOT )

	//_ENUM( EPM_PARTY_QUICK_JOIN_REQ )
	//_ENUM( EPM_PARTY_QUICK_JOIN_ACK )

	//_ENUM( EPM_DUNGEON_SECRET_STAGE_ENTER_CHECK_REQ )
	//_ENUM( EPM_DUNGEON_SECRET_STAGE_ENTER_CHECK_ACK )

	//_ENUM( EPM_CHANGE_PARTY_FEVER_STATE_NOT )
	//_ENUM( EPM_PARTY_FEVER_POINT_NOT )
	
	//_ENUM( EPM_REQUEST_UPDATE_PARTY_MEMBER_LIST_NOT )
	//_ENUM( EPM_SEND_UPDATE_PARTY_MEMBER_LIST_NOT )
	//_ENUM( EPM_QUICK_SLOT_COOL_TIME_RESET_NOT )
	//_ENUM( EPM_INCREASE_PARTY_FEVER_NOT )

	//_ENUM( EPM_UPDATE_PARTY_IN_PARTY_LIST_NOT )
	//_ENUM( EPM_OPEN_PARTY_LIST_NOT )
	//_ENUM( EPM_CLOSE_PARTY_LIST_NOT )
	//_ENUM( EPM_ADD_PARTY_LIST_NOT )
	//_ENUM( EPM_DEL_PARTY_LIST_NOT )

	//_ENUM( EPM_UPDATE_PARTY_MEMBER_IN_PARTY_LIST_NOT )
	//_ENUM( EPM_ADD_PARTY_MEMBER_IN_PARTY_LIST_NOT )
	//_ENUM( EPM_DEL_PARTY_MEMBER_IN_PARTY_LIST_NOT )

	//_ENUM( EPM_CHECK_INVALID_USER_NOT )
//#endif SERV_BATTLE_FIELD_SYSTEM
	//}}	
	//}}
	//////////////////////////////////////////////////////////////////////////

	//{{ 2010. 02. 23  최육사	웹 포인트 이벤트
	_ENUM( DBE_ATTENDANCE_CHECK_REQ )
	_ENUM( DBE_ATTENDANCE_CHECK_ACK )

	_ENUM( DBE_INCREASE_WEB_POINT_REQ )
	_ENUM( DBE_INCREASE_WEB_POINT_ACK )
	_ENUM( DBE_INCREASE_WEB_POINT_LOG_NOT )

	_ENUM( DBE_GET_WEB_POINT_REWARD_REQ )
	_ENUM( DBE_GET_WEB_POINT_REWARD_ACK )	

	_ENUM( DBE_GET_WEB_POINT_REWARD_CHECK_NICKNAME_REQ )
	_ENUM( DBE_GET_WEB_POINT_REWARD_CHECK_NICKNAME_ACK )

	_ENUM( ELG_WEB_POINT_REWARD_INSERT_TO_POST_NOT )
	_ENUM( DBE_RESULT_WEB_POINT_REWARD_NOT )
	//}}

	//{{ 2010.03.16.hoons.
	_ENUM( ERM_PERSONAL_SHOP_INFO_NOT ) // 상점 개설시 게임서버에 알려주는 패킷
	//}}

	//{{ 2010. 03. 22  최육사	기술의 노트
	_ENUM( DBE_EXPAND_SKILL_NOTE_PAGE_REQ )
	_ENUM( DBE_EXPAND_SKILL_NOTE_PAGE_ACK )
	_ENUM( DBE_REG_SKILL_NOTE_MEMO_REQ )
	_ENUM( DBE_REG_SKILL_NOTE_MEMO_ACK )
	//}}

	//{{ 2010. 05. 06  최육사	비밀던전 헬모드
	_ENUM( ERM_DUNGEON_EFFECT_REMAINING_TIME_NOT )
	_ENUM( ERM_DUNGEON_EFFECT_TIME_OUT_NOT )
	//}}

	//{{ 2010. 05. 31  최육사	동접 정보 개편
	_ENUM( ELG_UPDATE_CCU_INFO_NOT )
	_ENUM( DBE_UPDATE_CCU_INFO_NOT )
	//}}

	//{{ 2010. 06. 17  최육사	오토핵 방지
	_ENUM( ERM_SERVER_CHECK_HACK_USER_NOT )
	//}}

	//{{ 2010. 06. 20  최육사	통계 스레드
	_ENUM( E_STATISTICS_INFO_NOT )
	_ENUM( E_HENIR_RANKING_LOG_NOT )
	_ENUM( E_LOCAL_LOG_PVP_NOT )
	_ENUM( E_LOCAL_LOG_PVP_ROOM_NOT )
	_ENUM( E_LOCAL_LOG_DUNGEON_ROOM_NOT )
	_ENUM( E_LOCAL_LOG_TITLE_NOT )
	_ENUM( E_LOCAL_LOG_DUNGEON_NOT )
	_ENUM( E_LOCAL_LOG_HENIR_RANKING_NOT )
	_ENUM( E_LOCAL_LOG_PET_SUMMON_NOT )
	//}}

	//{{ 2010. 06. 22  최육사	계정블럭기능
	_ENUM( DBE_CHECK_ACCOUNT_BLOCK_LIST_REQ )
	_ENUM( DBE_CHECK_ACCOUNT_BLOCK_LIST_ACK )
	//}}

	//{{ 2010. 06. 30  최육사	근성도 통계
	_ENUM( DBE_SPIRIT_STATISTICS_NOT )
	//}}

	//{{ 2010. 7. 21  최육사	펫 시스템
	_ENUM( DBE_CREATE_PET_REQ )
	_ENUM( DBE_CREATE_PET_ACK )

	_ENUM( DBE_SUMMON_PET_REQ )
	_ENUM( DBE_SUMMON_PET_ACK )
	_ENUM( ERM_SUMMON_PET_NOT )
	_ENUM( ETR_SUMMON_PET_NOT )

	_ENUM( ERM_PET_ACTION_NOT )
	_ENUM( ETR_PET_ACTION_NOT )

	_ENUM( ERM_CHANGED_PET_SATIETY_NOT )
	_ENUM( ERM_CHANGED_PET_INTIMACY_NOT )
	_ENUM( ERM_CHANGED_PET_SATIETY_INTIMACY_NOT )

	_ENUM( ERM_DECREASE_PET_SATIETY_NOT )

	_ENUM( ERM_PET_EVOLUTION_NOT )
	_ENUM( ETR_PET_EVOLUTION_NOT )

	//{{ 2012. 02. 22	박세훈	펫 이름 변경권
//#ifdef SERV_PET_CHANGE_NAME
	_ENUM( DBE_CHANGE_PET_NAME_REQ )
	_ENUM( DBE_CHANGE_PET_NAME_ACK )
//#endif SERV_PET_CHANGE_NAME
	//}}

	//}}

	//{{ 2010. 8. 16	최육사	기간 리셋 아이템 이벤트
	_ENUM( DBE_RESET_PERIOD_ITEM_REQ )
	_ENUM( DBE_RESET_PERIOD_ITEM_ACK )
	//}}

	_ENUM( DBE_CCU_AGENT_REQ )
	_ENUM( DBE_CCU_AGENT_ACK )

	//{{ 2010. 9. 8	최육사	네트워크 트래픽 유발 유저 모니터링
	_ENUM( ELOG_INSERT_TRAFFIC_ABUSER_LOG_NOT )
	//}}

	//{{ 2010. 9. 29	최육사	ED 모니터링 치트
	_ENUM( ELG_ADMIN_SHOW_ED_CHEAT_REQ )
	_ENUM( ELG_ADMIN_SHOW_ED_CHEAT_ACK )
	//}}

	//{{ 2010. 10. 05	최육사	센터서버 해킹체크
	_ENUM( ELG_REG_REJECTED_USER_NOT )
	_ENUM( DBE_REG_REJECTED_USER_NOT )
	//}}

	//{{ 2010. 10. 11	최육사	서버간 접속 끊김 로그
	_ENUM( E_LOCAL_LOG_SERVER_DISCONNECT_NOT )
	//}}
	//{{ 2010. 10. 11	최육사	넥슨 빌링 패킷 로그
	_ENUM( E_LOCAL_LOG_BILLING_PACKET_NOT )
	//}}
	//{{ 2010. 11. 17	최육사	오토핵 검증 기능
	_ENUM( E_LOCAL_LOG_ABUSER_MORNITORING_NOT )
	//}}
	//{{ 2010. 10. 12	최육사	서버 모니터링
	_ENUM( E_DISCONNECT_SERVER_REPORT_NOT )
	_ENUM( ELG_DISCONNECT_SERVER_REPORT_NOT )
	//}}

	//{{ 2010. 10. 13	최육사	DLL Manager
	_ENUM( DBE_GET_MODULE_INFO_LIST_REQ )
	_ENUM( DBE_GET_MODULE_INFO_LIST_ACK )
	_ENUM( DBE_UPDATE_MODULE_INFO_LIST_REQ )
	_ENUM( DBE_UPDATE_MODULE_INFO_LIST_ACK )
	_ENUM( ELG_MODULE_INFO_UPDATE_NOT )
	//}}

	//{{ 2010. 11. 2	최육사	IP주소 계정 가입 로그
	_ENUM( DBE_JOIN_ACCOUNT_CHECK_IP_LOG_NOT )
	//}}

	//{{ 2010. 11. 8	최육사	던전 로그 DB
	_ENUM( DBE_DB_LOG_DUNGEON_NOT )
	//}}

	//{{ 2010. 11. 18	최육사	아이템 판매 차단
	_ENUM( ERM_CHECK_SELL_ED_ITEM_REQ )
	_ENUM( ERM_CHECK_SELL_ED_ITEM_ACK )
	//}}

	//{{ 2010. 11. 20	최육사	특정 시각 몬스터 출현
	_ENUM( DBE_GET_DUNGEON_EVENT_INFO_REQ )
	_ENUM( DBE_GET_DUNGEON_EVENT_INFO_ACK )
	_ENUM( DBE_UPDATE_EVENT_MONSTER_KILL_INFO_NOT )
	//}}

	//{{ 2010. 12. 7	최육사	메일 전송 시스템
	_ENUM( EMAIL_SEND_EMAIL_NOT )
	//}}

	//{{ 2010. 12. 8	최육사	적정 레벨 장비 통계
	_ENUM( ELOG_APPROPRIATE_LEVEL_STATISTICS_NOT )
	//}}

	//{{ 2010. 12. 20	최육사	특정 시각 큐브 보상
	_ENUM( DBE_GET_TIME_RANDOM_ITEM_EVENT_INFO_REQ )
	_ENUM( DBE_GET_TIME_RANDOM_ITEM_EVENT_INFO_ACK )

	_ENUM( ELG_CHECK_TIME_RANDOM_ITEM_EVENT_REQ )
	_ENUM( ELG_CHECK_TIME_RANDOM_ITEM_EVENT_ACK )

	_ENUM( DBE_UPDATE_TIME_RANDOM_ITEM_EVENT_RESULT_NOT )
	//}}

	//{{ 2011. 01. 04  김민성	속성 부적	
	_ENUM( DBE_ATTRIB_ATTACH_ITEM_REQ )
	_ENUM( DBE_ATTRIB_ATTACH_ITEM_ACK )
	_ENUM( ELOG_ATTRIB_ATTACH_ITEM_LOG_NOT )
	//}}

	//{{ 2011. 01. 13 김민성	동접 모니터링 툴
	_ENUM( DBE_GET_CONCURRENT_USER_LOGIN_REQ )
	_ENUM( DBE_GET_CONCURRENT_USER_LOGIN_ACK )

	_ENUM( DBE_GET_GAME_SERVER_LIST_REQ )
	_ENUM( DBE_GET_GAME_SERVER_LIST_ACK )
	//}}


	//{{ 2011. 01. 13	최육사	캐릭터 로그
	_ENUM( ELOG_USER_CHARACTER_LOG_NOT )
	//}}

	//{{ 2011. 01. 25  김민성  월드 트리거 전달(던전만 적용중 - 이후 PVP 확장)
	_ENUM( ECN_WORLD_TRIGGER_RELOCATION_REQ )
	_ENUM( ECN_WORLD_TRIGGER_RELOCATION_ACK )
	_ENUM( ECN_WORLD_TRIGGER_RELOCATION_NOT )
	//}}

	//{{ 2011. 01. 26	최육사	던전 클리어 타임 핵유저 체크
	_ENUM( DBE_REG_DUNGEON_CLEAR_TIME_HACK_USER_NOT )
	//}}

	//{{ 2011. 02. 08	최육사	캐쉬템 구매 로그
	_ENUM( ELOG_BUY_CASH_ITEM_LOG_NOT )
	//}}
	
	//{{ 2011. 02. 23	최육사	캐쉬 상품 리스트
	_ENUM( ELOG_CASH_PRODUCT_LIST_UPDATE_NOT )
	//}}

	//{{ 2011. 03. 02	최육사	개인 거래 차단
	_ENUM( ELG_REG_TRADE_BLOCK_USER_NOT )
	_ENUM( DBE_REG_TRADE_BLOCK_USER_NOT )
	_ENUM( ELG_TRADE_BLOCK_NOT )
	//}}

	//{{ 2011. 03. 17	김민성	던전 플레이 로그 요청사항 
	_ENUM( DBE_DB_TEMP_LOG_DUNGEON_NOT )
	//}}

	//{{ 2011. 03. 26  김민성	청 1차 추가 스킬 추가 - 버프 스킬 정보 전달
	_ENUM( ERM_BUFF_SKILL_INFO_CONVEY_REQ )
	_ENUM( ERM_BUFF_SKILL_INFO_CONVEY_ACK )
	_ENUM( ERM_BUFF_SKILL_INFO_CONVEY_NOT )
	//}}

	//{{ 2011. 04. 05  김민성	우편 및 거래 감시
	_ENUM( DBE_WRITE_LETTER_AND_TRADE_MOINTORING_REQ )
	_ENUM( DBE_WRITE_LETTER_AND_TRADE_MOINTORING_ACK )
	//}}

	//{{ 2011. 04. 07	최육사	대리 상인
	_ENUM( DBE_LOAD_PSHOP_AGENCY_REQ )
	_ENUM( DBE_LOAD_PSHOP_AGENCY_ACK )

	_ENUM( ERM_LOAD_PSHOP_BOARD_INFO_NOT )

	_ENUM( DBE_INSERT_PERIOD_PSHOP_AGENCY_REQ )
	_ENUM( DBE_INSERT_PERIOD_PSHOP_AGENCY_ACK )
	_ENUM( ERM_UPDATE_PERIOD_PSHOP_AGENCY_NOT )
	
	_ENUM( ERM_CHECK_MY_PSHOP_AGENCY_INFO_REQ )
	_ENUM( ERM_CHECK_MY_PSHOP_AGENCY_INFO_ACK )

	_ENUM( ERM_OPEN_PSHOP_AGENCY_REQ )
	_ENUM( ERM_OPEN_PSHOP_AGENCY_ACK )
	_ENUM( DBE_OPEN_PSHOP_AGENCY_REQ )
	_ENUM( DBE_OPEN_PSHOP_AGENCY_ACK )

	_ENUM( ERM_CHECK_OPEN_PSHOP_AGENCY_REQ )
	_ENUM( ERM_CHECK_OPEN_PSHOP_AGENCY_ACK )

	_ENUM( ERM_OPEN_PSHOP_AGENCY_BY_SERVER_NOT )

	_ENUM( DBE_BREAK_PSHOP_AGENCY_REQ )
	_ENUM( DBE_BREAK_PSHOP_AGENCY_ACK )

	//{{ 2011. 11. 23	최육사	대리상점 버그 수정
//#ifdef SERV_PSHOP_AGENCY_BUG_FIX
	_ENUM( ERM_CHECK_FOR_REG_PSHOP_AGENCY_ITEM_REQ )
	_ENUM( ERM_CHECK_FOR_REG_PSHOP_AGENCY_ITEM_ACK )
//#endif SERV_PSHOP_AGENCY_BUG_FIX
	//}}
	_ENUM( DBE_PREPARE_REG_PSHOP_AGENCY_ITEM_REQ )
	_ENUM( DBE_PREPARE_REG_PSHOP_AGENCY_ITEM_ACK )
	_ENUM( ERM_REG_PSHOP_AGENCY_ITEM_REQ )
	_ENUM( ERM_REG_PSHOP_AGENCY_ITEM_ACK )
	_ENUM( DBE_REG_PSHOP_AGENCY_ITEM_REQ )
	_ENUM( DBE_REG_PSHOP_AGENCY_ITEM_ACK )

	_ENUM( ERM_JOIN_MY_PSHOP_AGENCY_REQ )
	_ENUM( ERM_JOIN_MY_PSHOP_AGENCY_ACK )

	_ENUM( ERM_LEAVE_PSHOP_AGENCY_REQ )
	_ENUM( ERM_LEAVE_PSHOP_AGENCY_ACK )
	_ENUM( ERM_BREAK_PSHOP_AGENCY_NOT )

	_ENUM( ERM_STOP_SALE_PSHOP_AGENCY_REQ )
	_ENUM( ERM_STOP_SALE_PSHOP_AGENCY_ACK )
	_ENUM( DBE_STOP_SALE_PSHOP_AGENCY_REQ )
	_ENUM( DBE_STOP_SALE_PSHOP_AGENCY_ACK )

	_ENUM( DBE_BUY_PSHOP_AGENCY_ITEM_REQ )
	_ENUM( DBE_BUY_PSHOP_AGENCY_ITEM_ACK )
	_ENUM( ERM_BUY_PSHOP_AGENCY_ITEM_COMPLETE_NOT )

	_ENUM( ERM_PSHOP_AGENCY_MESSAGE_NOT )
	_ENUM( ELG_PSHOP_AGENCY_MESSAGE_NOT )

	_ENUM( ERM_PICK_UP_FROM_PSHOP_AGENCY_REQ )
	_ENUM( ERM_PICK_UP_FROM_PSHOP_AGENCY_ACK )
	_ENUM( ERM_PREPARE_PICK_UP_FROM_PSHOP_AGENCY_REQ )
	_ENUM( ERM_PREPARE_PICK_UP_FROM_PSHOP_AGENCY_ACK )
	_ENUM( DBE_PICK_UP_FROM_PSHOP_AGENCY_REQ )
	_ENUM( DBE_PICK_UP_FROM_PSHOP_AGENCY_ACK )
	_ENUM( DBE_INSERT_TO_INVENTORY_PICK_UP_FROM_PSHOP_AGENCY_REQ )
	_ENUM( DBE_INSERT_TO_INVENTORY_PICK_UP_FROM_PSHOP_AGENCY_ACK )

	//}}

	//{{ 2011. 04. 13  김민성  글로벌 서버 추가
	//#ifdef SERV_INSERT_GLOBAL_SERVER
	_ENUM( EGB_UPDATE_MISSION_INFO_NOT )

	_ENUM( EGB_GET_MISSION_INFO_REQ )
	_ENUM( EGB_GET_MISSION_INFO_ACK )

	_ENUM( EGB_CLEAR_MISSION_DUNGEON_NOT )
	
	_ENUM( EGB_UPDATE_CCU_INFO_NOT )

	_ENUM( EGB_UPDATE_WORLD_BUFF_NOT )
	_ENUM( ERM_CREATE_ATTRIB_NPC_NOT )
	
	_ENUM( DBE_INCREASE_DEFENCE_CRYSTAL_REQ )
	
	_ENUM( DBE_GET_DEFENCE_CRYSTAL_REQ )
	_ENUM( DBE_GET_DEFENCE_CRYSTAL_ACK )

	_ENUM( EGB_UPDATE_MISSION_START_TIME_NOT )
	//#endif SERV_INSERT_GLOBAL_SERVER
	//}} 2011. 04. 13  김민성  글로벌 서버 추가

	//{{ 2011. 05. 13	최육사	대리 상인 좀비 유저 버그 해결
//#ifdef SERV_PSHOP_AGENCY_ZOMBIE_USER_BUG_FIX
	_ENUM( ERM_CHECK_ZOMBIE_USER_REQ )
	_ENUM( ERM_CHECK_ZOMBIE_USER_ACK )
//#endif SERV_PSHOP_AGENCY_ZOMBIE_USER_BUG_FIX
	//}}

	//{{ 2011. 05. 02  김민성	2차 보안 시스템
//#ifdef SERV_SECOND_SECURITY
	_ENUM( DBE_GET_SECOND_SECURITY_INFO_REQ )
	_ENUM( DBE_GET_SECOND_SECURITY_INFO_ACK )
	_ENUM( DBE_SEUCCESS_SECOND_SECURITY_REQ )
	_ENUM( DBE_SEUCCESS_SECOND_SECURITY_ACK )
	_ENUM( DBE_FAILED_SECOND_SECURITY_REQ )
	_ENUM( DBE_FAILED_SECOND_SECURITY_ACK )

	_ENUM( DBE_CREATE_SECOND_SECURITY_REQ )
	_ENUM( DBE_CREATE_SECOND_SECURITY_ACK )
	_ENUM( DBE_DELETE_SECOND_SECURITY_REQ )
	_ENUM( DBE_DELETE_SECOND_SECURITY_ACK )
	_ENUM( DBE_CHANGE_SECOND_SECURITY_PW_REQ )
	_ENUM( DBE_CHANGE_SECOND_SECURITY_PW_ACK )	
	_ENUM( DBE_UPDATE_SECURITY_TYPE_NOT )
	_ENUM( DBE_FIRST_WRITE_SECURITY_TYPE_NOT )	
    
    // DBE_GET_SECOND_SECURITY_INFO_REQ에서 2차보안 정보만 가져오는 역할( DBE_GET_SECOND_SECURITY_INFO_REQ 역할이 너무 많다. 복귀유저도 있고 ), woosh, 2014-01-13
    _ENUM( DBE_GET_PURE_SECOND_SECURITY_INFO_REQ ) 
    _ENUM( DBE_GET_PURE_SECOND_SECURITY_INFO_ACK )
//#endif SERV_SECOND_SECURITY
	//}}

	//{{ 2011. 03. 21  김민성	던전 난이도 보정
//#ifdef SERV_DUNGEON_DIFFICULTY_REVISION
	_ENUM( EPM_PARTY_CHANGE_CHECK_MIN_LEVEL_REQ )
	_ENUM( EPM_PARTY_CHANGE_CHECK_MIN_LEVEL_ACK )
	_ENUM( EPM_PARTY_CHANGE_CHECK_MIN_LEVEL_NOT )
//#endif SERV_DUNGEON_DIFFICULTY_REVISION
	//}}

	//{{ 2011. 05. 27    김민성    휴면 복귀 유저 보상
//#ifdef SERV_COME_BACK_USER_REWARD
	_ENUM( DBE_WRITE_COME_BACK_REWARD_NOT )
	_ENUM( EPM_CHANGE_COME_BACK_BUFF_NOT )
	_ENUM( DBE_WRITE_COME_BACK_END_NOT )
	_ENUM( DBE_FIRST_WRITE_COME_BACK_INFO_NOT )
	_ENUM( DBE_WRITE_COME_BACK_LOGOUT_NOT )
//#endif SERV_COME_BACK_USER_REWARD
	//}} 

	//{{ 2011. 06. 13	최육사	스테이지 로그
//#ifdef SERV_DUNGEON_STAGE_LOG
	_ENUM( ELOG_DUNGEON_STAGE_LOG_NOT )
//#endif SERV_DUNGEON_STAGE_LOG
	//}}

	//{{ 2011. 06. 14	최육사	대전 개편
	//#ifdef SERV_PVP_NEW_SYSTEM
	_ENUM( EPM_CHANGE_PARTY_TYPE_REQ )
	_ENUM( EPM_CHANGE_PARTY_TYPE_ACK )
	_ENUM( EPM_CHANGE_PARTY_TYPE_NOT )

	_ENUM( EPM_PVP_PARTY_CHANGE_MATCH_INFO_REQ )
	_ENUM( EPM_PVP_PARTY_CHANGE_MATCH_INFO_ACK )
	_ENUM( EPM_PVP_PARTY_CHANGE_MATCH_INFO_NOT )

	_ENUM( EPM_GET_PARTY_INFO_FOR_MATCH_MAKING_REQ )
	_ENUM( EPM_GET_PARTY_INFO_FOR_MATCH_MAKING_ACK )

	_ENUM( EGB_REQUEST_MATCH_MAKING_REQ )
	_ENUM( EGB_REQUEST_MATCH_MAKING_ACK )
	_ENUM( EGB_REG_MATCH_WAIT_LIST_SUCCESS_NOT )

	_ENUM( EGB_CANCEL_MATCH_MAKING_REQ )
	_ENUM( EGB_CANCEL_MATCH_MAKING_ACK )
	_ENUM( EGB_UNREG_MATCH_WAIT_LIST_NOT )
	
	_ENUM( EGB_MATCH_MAKING_SUCCESS_NOT )
	_ENUM( EGB_MATCH_MAKING_SUCCESS_REPLY_NOT )

	_ENUM( EGB_MATCH_CLOSE_NOT )

	_ENUM( EGB_REMATCH_MAKING_USER_NOT )

	_ENUM( EGB_GET_ROOM_USER_INFO_FOR_MATCH_REQ )
	_ENUM( EGB_GET_ROOM_USER_INFO_FOR_MATCH_ACK )

	_ENUM( EGB_OPEN_PVP_ROOM_FOR_MATCH_REQ )
	_ENUM( EGB_OPEN_PVP_ROOM_FOR_MATCH_ACK )
	_ENUM( ERM_OPEN_PVP_ROOM_FOR_MATCH_REQ )
	_ENUM( ERM_OPEN_PVP_ROOM_FOR_MATCH_ACK )

	_ENUM( ERM_GAME_START_PVP_MATCH_NOT )
	_ENUM( ERM_UPDATE_PVP_PLAY_UNIT_INFO_NOT )

	_ENUM( ERM_PVP_NPC_UNIT_RE_BIRTH_POS_REQ )
	_ENUM( ERM_PVP_NPC_UNIT_RE_BIRTH_POS_ACK )	

	_ENUM( ERM_PVP_NPC_UNIT_INFO_TO_SERVER_REQ )
	_ENUM( ERM_PVP_NPC_UNIT_INFO_TO_SERVER_ACK )

	_ENUM( DBE_PVP_MATCH_RESULT_LOG_NOT )
	_ENUM( EGB_CHECK_INVALID_MATCH_NOT )

	_ENUM( EGB_MATCH_MAKING_ADMIN_COMMAND_NOT )
	//#endif SERV_PVP_NEW_SYSTEM
	//}}

	//{{ 2011. 08. 03	최육사	대전 강제 종료에 대한 예외처리
//#ifdef SERV_CLIENT_QUIT_PVP_BUG_PLAY_FIX
	_ENUM( DBE_QUIT_USER_PVP_RESULT_UPDATE_NOT )
//#endif SERV_CLIENT_QUIT_PVP_BUG_PLAY_FIX
	//}}

	//{{ 2011. 06. 22    김민성    이탈 방지 모델 - NEXON 세션 시스템 수정
//#ifdef SERV_NEXON_SESSION_PROTOCOL
	_ENUM( DBE_RETAINING_SELECT_REWARD_REQ )
	_ENUM( DBE_RETAINING_SELECT_REWARD_ACK )
	_ENUM( DBE_INSERT_RETAINING_USER_REQ )
	_ENUM( DBE_INSERT_RETAINING_USER_ACK )
	_ENUM( DBE_CHECK_RETAINING_USER_REQ )
	_ENUM( DBE_CHECK_RETAINING_USER_ACK )
	_ENUM( DBE_INSERT_LOG_RETAINING_USER_NOT )
//#endif SERV_NEXON_SESSION_PROTOCOL
	//}} 

	//{{ 2011. 08. 08	최육사	머신ID 블럭기능
	//#ifdef SERV_MACHINE_ID_BLOCK
	_ENUM( ELG_CHECK_MACHINE_ID_REQ )
	_ENUM( ELG_CHECK_MACHINE_ID_ACK )
	//#endif SERV_MACHINE_ID_BLOCK
	//}}

	//{{ 2011. 08. 10    김민성    채널링 SOAP
//#ifdef SERV_CHANNELING_SOAP
	_ENUM( SOAP_GET_TOONILAND_ID_REQ )
	_ENUM( SOAP_GET_TOONILAND_ID_ACK )
//#endif SERV_CHANNELING_SOAP
	//}}
	//{{ 2011. 08. 11	최육사	투니 랜드 채널링 
//#ifdef SERV_TOONILAND_CHANNELING
	_ENUM( ELG_DUMP_LOGIN_USER_NOT )
//#endif SERV_TOONILAND_CHANNELING
	//}}

	//{{ 2011. 08. 29	김민성       일일 랜덤 퀘스트
//#ifdef SERV_RANDOM_DAY_QUEST
	_ENUM( EGB_TODAY_RANDOM_QUEST_REQ )
	_ENUM( EGB_TODAY_RANDOM_QUEST_ACK )
//#endif SERV_RANDOM_DAY_QUEST
	//}}

	//{{ 2011. 09. 14  김민성	해킹 프로세스 목록 전달 - 게임 로딩 이전 단계
//#ifdef SERV_DLL_LIST_CHECK_BEFOR_LOADING
	_ENUM( DBE_UPDATE_CHANNEL_RANDOMKEY_REQ )
	_ENUM( DBE_UPDATE_CHANNEL_RANDOMKEY_ACK )
	_ENUM( DBE_UPDATE_CHANNEL_RANDOMKEY_NOT )
//#endif SERV_DLL_LIST_CHECK_BEFOR_LOADING
	//}}

	//{{ 2011. 09. 20  김민성	게임내 ED 감시 모니터링
//#ifdef SERV_ED_MONITORING_IN_GAME
	_ENUM( ERM_FIELD_USER_LIST_MONITORING_MODE_REQ )
	_ENUM( ERM_SQUARE_UNIT_REFRESH_ED_NOT )
//#endif SERV_ED_MONITORING_IN_GAME
	//}}
	//{{ 2011. 10. 13	최육사	아이템 사용 DB 업데이트 수정
//#ifdef SERV_USE_ITEM_DB_UPDATE_FIX
	_ENUM( DBE_USE_ITEM_IN_INVENTORY_REQ )
	_ENUM( DBE_USE_ITEM_IN_INVENTORY_ACK )
//#endif SERV_USE_ITEM_DB_UPDATE_FIX
	//}}

	//{{ 2011. 09. 29  김민성	셧다운제 도입
//#ifdef SERV_SHUTDOWN_SYSTEM
	_ENUM( EGB_SHUT_DOWN_NOTIFY_NOT )
//#endif SERV_SHUTDOWN_SYSTEM
	//}}	
	//{{ 2011.11.02     김민성    서버에서 SN 발급 및 유효성 검사
//#ifdef SERV_SERIAL_NUMBER_AVAILABILITY_CHECK
	_ENUM( DBE_CHECK_SERVER_SN_REQ )
	_ENUM( DBE_CHECK_SERVER_SN_ACK )
	_ENUM( DBE_CREATE_SERVER_SN_REQ )
	_ENUM( DBE_CREATE_SERVER_SN_ACK )
//#endif SERV_SERIAL_NUMBER_AVAILABILITY_CHECK
	//}}

	//{{  2011.11.08     김민성    강화 로그
//#ifdef SERV_ENCHANT_ITEM_LOG
	_ENUM( ELOG_HIGH_ENCHANT_ITEM_LOG_NOT )
//#endif SERV_ENCHANT_ITEM_LOG
	//}}
//{{  2011.11.24     김민성    캐릭터 접속 로그
//#ifdef SERV_CHAR_CONNECT_LOG
	_ENUM( DBE_UNIT_CONNECT_LOG_NOT )
//#endif SERV_CHAR_CONNECT_LOG
	//}}
	//{{ 2011. 11. 21  김민성	전직 변경 아이템
//#ifdef SERV_UNIT_CLASS_CHANGE_ITEM
	_ENUM( DBE_BUY_UNIT_CLASS_CHANGE_REQ )
	_ENUM( DBE_BUY_UNIT_CLASS_CHANGE_ACK )
//#endif SERV_UNIT_CLASS_CHANGE_ITEM
	//}}

	//{{ 2011. 12. 02  김민성	AP 구매 로그 수치
//#ifdef SERV_BUY_AP_ITEM_LOG
	_ENUM( DBE_BUY_AP_ITEM_LOG_NOT )
//#endif SERV_BUY_AP_ITEM_LOG
	//}}
	//{{ 2011. 12. 14	최육사	패킷 처리 지연 시간 체크
//#ifdef SERV_PACKET_PROCESSING_LATENCY_CHECK
	_ENUM( DBE_UPDATE_PAKCET_MORNITORING_LOG_NOT )
//#endif SERV_PACKET_PROCESSING_LATENCY_CHECK
	//}}

	//{{ 2011.10.13 박진웅 : GM계정용 엘리트 소환기능
	//#ifdef SERV_CREATE_ELITE_FOR_ADMIN
	_ENUM( ERM_ADMIN_NPC_UNIT_CREATE_REQ )
	_ENUM( ERM_ADMIN_NPC_UNIT_CREATE_ACK )
	_ENUM( ERM_ADMIN_NPC_UNIT_CREATE_NOT )
	//#ifdef SERV_CREATE_ELITE_FOR_ADMIN
	//}}

	//{{  2012. 1. 16	김민성		게임서버에서 Server SN 검사
	//#ifdef SERV_SERIAL_NUMBER_AVAILABILITY_CHECK_IN_GAMESERVER
	_ENUM( DBE_CHECK_SERVER_SN_IN_GAMESERVER_REQ )
	_ENUM( DBE_CHECK_SERVER_SN_IN_GAMESERVER_ACK )
	//#endif SERV_SERIAL_NUMBER_AVAILABILITY_CHECK_IN_GAMESERVER
	//}}
	
	//{{ 2012. 01. 27  김민성	해킹 프로세스 검사 기능
	//#ifdef SERV_HACKING_DLL_CHECK
	_ENUM( ELG_CHECK_MODULE_INFO_UPDATE_NOT )
	_ENUM( DBE_CHECK_MODULE_INFO_LOG_NOT )
	_ENUM( DBE_GET_HACKING_MODULE_LIST_REQ )
	_ENUM( DBE_GET_HACKING_MODULE_LIST_ACK )
	//#endif SERV_HACKING_DLL_CHECK
	//}}
	
	//{{ 2012. 02. 14    김민성   PVP 대전 Item 생성 위치 변경
//#ifdef SERV_PVP_ITEM_CHANGE_POS
	_ENUM( ERM_CHANGE_PVP_ITEM_POS_REQ )
	_ENUM( ERM_CHANGE_PVP_ITEM_POS_ACK )
	_ENUM( ERM_CHANGE_PVP_ITEM_POS_NOT )
//#endif SERV_PVP_ITEM_CHANGE_POS
	//}}

	//{{ 2011. 10. 27	최육사	배틀필드 시스템
//#ifdef SERV_BATTLE_FIELD_SYSTEM
	//_ENUM( EPM_CREATE_PARTY_FOR_JOIN_BATTLE_FIELD_REQ )
	//_ENUM( EPM_CREATE_PARTY_FOR_JOIN_BATTLE_FIELD_ACK )

	_ENUM( EPM_GET_PARTY_INFO_FOR_JOIN_BATTLE_FIELD_REQ )
	_ENUM( EPM_GET_PARTY_INFO_FOR_JOIN_BATTLE_FIELD_ACK )

	_ENUM( ERM_LEAVE_ROOM_FOR_JOIN_BATTLE_FIELD_REQ )
	_ENUM( ERM_LEAVE_ROOM_FOR_JOIN_BATTLE_FIELD_ACK )

	_ENUM( ERM_LEAVE_ROOM_FOR_ENTER_THE_VILLAGE_REQ )
	_ENUM( ERM_LEAVE_ROOM_FOR_ENTER_THE_VILLAGE_ACK )

	_ENUM( ERM_LEAVE_BATTLE_FIELD_FOR_JOIN_BATTLE_FIELD_REQ )
	_ENUM( ERM_LEAVE_BATTLE_FIELD_FOR_JOIN_BATTLE_FIELD_ACK )

	_ENUM( ERM_LEAVE_BATTLE_FIELD_FOR_DUNGEON_GAME_START_REQ )
	_ENUM( ERM_LEAVE_BATTLE_FIELD_FOR_DUNGEON_GAME_START_ACK )

	_ENUM( ERM_LEAVE_BATTLE_FIELD_FOR_PVP_GAME_START_REQ )
	_ENUM( ERM_LEAVE_BATTLE_FIELD_FOR_PVP_GAME_START_ACK )

	_ENUM( ERM_OPEN_BATTLE_FIELD_REQ )
	_ENUM( ERM_OPEN_BATTLE_FIELD_ACK )

	_ENUM( ERM_JOIN_BATTLE_FIELD_REQ )
	_ENUM( ERM_JOIN_BATTLE_FIELD_ACK )
	_ENUM( ERM_JOIN_BATTLE_FIELD_NOT )

	_ENUM( ERM_LEAVE_BATTLE_FIELD_NOT )

	_ENUM( ERM_BATTLE_FIELD_GAME_LOADING_REQ )
	_ENUM( ERM_BATTLE_FIELD_GAME_LOADING_ACK )

	_ENUM( ERM_BATTLE_FIELD_JOIN_USER_LOAD_COMPLETE_NOT )

	_ENUM( ERM_BATTLE_FIELD_ROOM_INFO_NOT )

	_ENUM( ERM_BATTLE_FIELD_NPC_LOAD_NOT )

	_ENUM( ERM_BATTLE_FIELD_NPC_LOAD_COMPLETE_REQ )
	_ENUM( ERM_BATTLE_FIELD_NPC_LOAD_COMPLETE_ACK )

	_ENUM( ERM_BATTLE_FIELD_NPC_P2P_SYNC_NOT )
//#ifndef SERV_OPTIMIZE_ROBUST_USER_NPC_PACKET_SEND
	//_ENUM( ERM_BATTLE_FIELD_NPC_P2P_SYNC_COMPLETE_NOT )
//#endif  SERV_OPTIMIZE_ROBUST_USER_NPC_PACKET_SEND

	_ENUM( ERM_BATTLE_FIELD_EVENT_MESSAGE_NOT )

	_ENUM( ERM_BATTLE_FIELD_ZU_ECHO_REQ )
	_ENUM( ERM_BATTLE_FIELD_ZU_ECHO_ACK )
//#ifdef  SERV_OPTIMIZE_DETECT_ZOMBIE_HOST
    _ENUM( ERM_BATTLE_FIELD_ZOMBIE_ALERT_NOT )
//#endif  SERV_OPTIMIZE_DETECT_ZOMBIE_HOST

	_ENUM( ERM_SINGLE_OPEN_DUNGEON_ROOM_REQ )
	_ENUM( ERM_SINGLE_OPEN_DUNGEON_ROOM_ACK )

	_ENUM( ERM_DUMP_ROOM_MONSTER_NOT )
	_ENUM( ERM_DUMP_BATTLE_FIELD_NOT )
	//{{ 2012. 11. 20	최육사		좀비 배틀필드 체크 및 삭제
//#ifdef SERV_ZOMBIE_BATTLE_FIELD_ROOM_CHECK_AND_DELETE
	_ENUM( ERM_KILL_ZOMBIE_USER_IN_BATTLE_FIELD_NOT )
//#endif SERV_ZOMBIE_BATTLE_FIELD_ROOM_CHECK_AND_DELETE
	//}}

	// 파티 관련 기능
	_ENUM( ERM_UPDATE_PARTY_INFO_TO_BATTLE_FIELD_NOT )
	_ENUM( ERM_END_DUNGEON_GAME_PARTY_FEVER_MODIFY_NOT )

	_ENUM( EPM_UPDATE_PARTY_USER_JOIN_ROOM_INFO_NOT )
	_ENUM( EPM_UPDATE_MOVE_TO_PARTY_MEMBER_INFO_NOT )

	// 자동 파티 매칭
	_ENUM( EGB_GET_AUTO_PARTY_BONUS_INFO_REQ )
	_ENUM( EGB_GET_AUTO_PARTY_BONUS_INFO_ACK )
	_ENUM( EGB_UPDATE_AUTO_PARTY_BONUS_INFO_NOT )

	_ENUM( EPM_GET_PARTY_INFO_FOR_AUTO_PARTY_MAKING_REQ )
	_ENUM( EPM_GET_PARTY_INFO_FOR_AUTO_PARTY_MAKING_ACK )

	_ENUM( EPM_CHECK_FOR_AUTO_PARTY_MAKING_REQ )
	_ENUM( EPM_CHECK_FOR_AUTO_PARTY_MAKING_ACK )

	_ENUM( EGB_REQUEST_AUTO_PARTY_MAKING_REQ )
	_ENUM( EGB_REQUEST_AUTO_PARTY_MAKING_ACK )
	_ENUM( EGB_REG_AUTO_PARTY_WAIT_LIST_SUCCESS_NOT )	// 다른 파티원들에게 전달 메시지

	_ENUM( EGB_CANCEL_AUTO_PARTY_MAKING_REQ )
	_ENUM( EGB_CANCEL_AUTO_PARTY_MAKING_ACK )
	_ENUM( EGB_UNREG_AUTO_PARTY_WAIT_LIST_NOT )

	_ENUM( EGB_AUTO_PARTY_MAKING_SUCCESS_NOT )
	_ENUM( EGB_AUTO_PARTY_MAKING_SUCCESS_REPLY_NOT )
	_ENUM( EGB_REMAKING_AUTO_PARTY_NOT )

	_ENUM( EGB_AUTO_PARTY_CLOSE_NOT )

	_ENUM( EGB_GET_REGROUP_PARTY_INFO_REQ )
	_ENUM( EGB_GET_REGROUP_PARTY_INFO_ACK )

	_ENUM( EGB_REGROUP_PARTY_FOR_AUTO_PARTY_DUNGEON_GAME_REQ )
	_ENUM( EGB_REGROUP_PARTY_FOR_AUTO_PARTY_DUNGEON_GAME_ACK )

	_ENUM( EPM_REGROUP_PARTY_FOR_AUTO_PARTY_DUNGEON_GAME_REQ )
	_ENUM( EPM_REGROUP_PARTY_FOR_AUTO_PARTY_DUNGEON_GAME_ACK )

	_ENUM( EPM_REGROUP_PARTY_NOT )

	_ENUM( ERM_END_GAME_REGROUP_PARTY_NOT )
	_ENUM( EPM_END_GAME_REGROUP_PARTY_NOT )
	_ENUM( EPM_LEAVE_PARTY_BY_AUTO_PARTY_NOT )

	_ENUM( EPM_PREPARE_FOR_REGROUP_PARTY_AND_CHECK_NEW_HOST_NOT )
	_ENUM( EPM_REQUEST_REGROUP_PARTY_NOT )

	_ENUM( EGB_CHECK_INVALID_AUTO_PARTY_NOT )
	_ENUM( EGB_AUTO_PARTY_MAKING_ADMIN_COMMAND_NOT )

	_ENUM( ERM_GAME_START_TIME_COUNT_NOT )

	_ENUM( EPM_UPDATE_GAME_PLAY_STATUS_NOT )
	_ENUM( EPM_BROADCAST_PARTY_MEMBER_STATUS_NOT )

	_ENUM( ERM_USE_SKILL_BUFF_IN_PLAY_NOT )
	_ENUM( ERM_USE_SKILL_BUFF_IN_PLAY_BROAD_NOT )

	_ENUM( ERM_COMPLETE_RETURN_TO_FIELD_NOT )
	_ENUM( ERM_NEXT_RETURN_TO_FIELD_NOT )

	_ENUM( ELOG_BATTLE_FIELD_LEAVE_LOG_NOT )
//#endif SERV_BATTLE_FIELD_SYSTEM
	//}}

	//{{ 2012. 04. 24	최육사	UDP릴레이 퍼포먼스 체크
//#ifdef SERV_UDP_RELAY_CHECKER
	_ENUM( DBE_GET_CENTER_SERVER_LIST_REQ )
	_ENUM( DBE_GET_CENTER_SERVER_LIST_ACK )
	_ENUM( DBE_UPDATE_UDP_RELAY_CHECK_STATISTICS_NOT )
//#endif SERV_UDP_RELAY_CHECKER
	//}}
	//{{ 2012. 03. 03	박세훈	어둠의 문 개편
//#ifdef SERV_REFORM_THE_GATE_OF_DARKNESS
	_ENUM( EGB_THE_GATE_OF_DARKNESS_INDIVIDUAL_BUFF_NOT )
	_ENUM( EGB_INCREASE_THE_PROTECTED_CRYSTAL_COUNT_NOT )
	_ENUM( EGB_RESET_INCREASE_THE_PROTECTED_CRYSTAL_COUNT_NOT )
//#endif SERV_REFORM_THE_GATE_OF_DARKNESS
	//}}

	//{{ 2012. 03. 29	김민성		중복 sn 접속 감시
//#ifdef SERV_SERIAL_NUMBER_AVAILABILITY_CHECK_FILTER
	_ENUM( EGB_REGISTER_SERVERSN_REQ )
	_ENUM( EGB_REGISTER_SERVERSN_ACK )
	_ENUM( EGB_UNREGISTER_SERVERSN_NOT )
	_ENUM( EGB_REGISTER_SERVERSN_NOT )
//#endif SERV_SERIAL_NUMBER_AVAILABILITY_CHECK_FILTER
	//}}

	//{{ 2012. 03. 29	김민성		x2.exe 모듈 유무 검사
//#ifdef SERV_CHECK_X2_EXE_MODULE
	_ENUM( DBE_MODULE_EXIST_LOG_NOT )
//#endif SERV_CHECK_X2_EXE_MODULE
	//}}

	//{{ 2012. 04. 02	김민성		넥슨 auth soap
//#ifdef SERV_NEXON_AUTH_SOAP
	_ENUM( SOAP_CHECK_NEXON_ID_REQ )
	_ENUM( SOAP_CHECK_NEXON_ID_ACK )
//#endif SERV_NEXON_AUTH_SOAP
	//}}

	//{{ 2012. 04. 30	박세훈	현자의 주문서 접속 이벤트 ( 우편함 중복 체크 )
//#ifdef SERV_SCROLL_OF_SAGE_CHECK_THE_LETTER_BOX
	_ENUM( DBE_UPDATE_EVENT_TIME_NOT )
//#endif SERV_SCROLL_OF_SAGE_CHECK_THE_LETTER_BOX
	//}}

	//{{ 2012. 05. 08	김민성       개인 거래 로직 변경
//#ifdef SERV_TRADE_LOGIC_CHANGE_TRADE
	_ENUM( DBE_TRADE_COMPLETE_REQ )
	_ENUM( DBE_TRADE_COMPLETE_ACK )
//#endif SERV_TRADE_LOGIC_CHANGE_TRADE
	//}}

	//{{ 2012. 05. 22	박세훈	[이벤트] 에이핑크가 응원합니다!
//#ifdef SERV_EVENT_APINK
	_ENUM( DBE_EVENT_APINK_USER_TYPE_WRITE_NOT )
//#endif SERV_EVENT_APINK
	//}}

	//{{ 2012. 05. 29	김민성       개인 상점 거래 로직 변경
//#ifdef SERV_TRADE_LOGIC_CHANGE_PERSONAL_SHOP
	_ENUM( DBE_BUY_PERSONAL_SHOP_ITEM_COMPLETE_REQ )
	_ENUM( DBE_BUY_PERSONAL_SHOP_ITEM_COMPLETE_ACK )
//#endif SERV_TRADE_LOGIC_CHANGE_PERSONAL_SHOP
	//}}
	//{{ 2012. 05. 30	최육사		공식 대전 버그 수정
//#ifdef SERV_OFFCIAL_PVP_BUG_FIX
	_ENUM( EPM_UPDATE_PVP_INFO_NOT )
//#endif SERV_OFFCIAL_PVP_BUG_FIX
	//}}

	//{{ 2012. 05. 17	박세훈	키보드 맵핑 정보를 DB에서 읽고 쓰기
//#ifdef SERV_KEYBOARD_MAPPING_INFO_RW
	_ENUM( DBE_KEYBOARD_MAPPING_INFO_WRITE_REQ )
	_ENUM( DBE_KEYBOARD_MAPPING_INFO_WRITE_ACK )
	_ENUM( DBE_KEYBOARD_MAPPING_INFO_READ_REQ )
	_ENUM( DBE_KEYBOARD_MAPPING_INFO_READ_ACK )
//#endif SERV_KEYBOARD_MAPPING_INFO_RW
	//}}

	//{{ 2012. 05. 29	박세훈	채팅 옵션 정보를 DB에서 읽고 쓰기
//#ifdef SERV_CHAT_OPTION_INFO_RW
	_ENUM( DBE_CHAT_OPTION_INFO_WRITE_REQ )
	_ENUM( DBE_CHAT_OPTION_INFO_WRITE_ACK )
	_ENUM( DBE_CHAT_OPTION_INFO_READ_REQ )
	_ENUM( DBE_CHAT_OPTION_INFO_READ_ACK )
//#endif SERV_CHAT_OPTION_INFO_RW
	//}}

	//{{ 2012. 05. 30	최육사	그노시스 기간 치트
//#ifdef SERV_CASH_SKILL_POINT_DATE_CHANGE
	_ENUM( DBE_ADMIN_CASH_SKILL_POINT_DATE_CHANGE_REQ )
	_ENUM( DBE_ADMIN_CASH_SKILL_POINT_DATE_CHANGE_ACK )
//#endif SERV_CASH_SKILL_POINT_DATE_CHANGE
	//}}
	//{{ 2012. 06. 07	박세훈	매일매일 선물 상자
//#ifdef SERV_EVENT_DAILY_GIFT_BOX
	_ENUM( DBE_PURCHASED_DAILY_GIFT_BOX_ITEM_WRITE_NOT )
//#endif SERV_EVENT_DAILY_GIFT_BOX
	//}}

//#ifdef SERV_EVENT_MONEY	// 김민성 // 적용날짜: 2013-07-04
	_ENUM( DBE_UPDATE_EVENT_MONEY_REQ )
	_ENUM( DBE_UPDATE_EVENT_MONEY_ACK )
//#endif // SERV_EVENT_MONEY

	//{{ 2012. 07. 02	최육사		대기열 시스템
//#ifdef SERV_WAIT_QUEUE_SYSTEM
	_ENUM( DBE_GET_TOTAL_CCU_FOR_WAIT_QUEUE_REQ )
	_ENUM( DBE_GET_TOTAL_CCU_FOR_WAIT_QUEUE_ACK )
//#endif SERV_WAIT_QUEUE_SYSTEM
	//}}

	//{{ 버프 관리 시스템 - 김민성
//#ifdef SERV_SERVER_BUFF_SYSTEM
	_ENUM( ECN_PARTY_BUFF_UPDATE_NOT )					// 서버에서 발동 시키는 버프
	_ENUM( ERM_ACTIVATE_BUFF_NOT )
	//{{ 2012. 12. 18	최육사	아라 파티 플레이 보너스 경험치
//#ifdef SERV_PLAY_WITH_CHAR_PARTY_BONUS_EXP
	_ENUM( ERM_DEACTIVATE_BUFF_NOT )
//#endif SERV_PLAY_WITH_CHAR_PARTY_BONUS_EXP
	//}}
	_ENUM( ERM_UPDATE_BUFF_INFO_IN_ROOM_NOT )

	_ENUM( ELG_UPDATE_USER_UNIT_BUFF_INFO_REQ )			// 로그인 버프 매니저에 유닛 버프 등록 요청(add/delete)
	_ENUM( ELG_UPDATE_USER_UNIT_BUFF_INFO_ACK )			// 유닛 버프 등록 결과
	
	_ENUM( ERM_UPDATE_USER_UNIT_BUFF_INFO_NOT )
	_ENUM( ERM_UPDATE_USER_UNIT_BUFF_INFO_BROAD_NOT )

	_ENUM( ERM_UPDATE_NPC_UNIT_BUFF_INFO_NOT )
	_ENUM( ERM_UPDATE_NPC_UNIT_BUFF_INFO_BROAD_NOT )
//#endif SERV_SERVER_BUFF_SYSTEM
	//}}
	//{{ 2012. 07. 24	박세훈	해당 캐릭터의 모든 스킬을 다 찍는 치트
//#ifdef SERV_ADMIN_CHEAT_GET_ALL_SKILL
	_ENUM( DBE_ADMIN_CHEAT_GET_ALL_SKILL_REQ )
	_ENUM( DBE_ADMIN_CHEAT_GET_ALL_SKILL_ACK )
//#endif SERV_ADMIN_CHEAT_GET_ALL_SKILL
	//}}

	//{{ 2012. 07. 27	최육사		사제시스템 EXP 보너스 버그 수정
//#ifdef SERV_TUTO_EXP_BONUS_BUG_FIX
	_ENUM( ERM_UPDATE_TUTORIAL_INFO_NOT )
//#endif SERV_TUTO_EXP_BONUS_BUG_FIX
	//}}

	//{{ 우편 ED 거래시 ED 동기화 - 김민성
//#ifdef SERV_SEND_LETTER_BEFOR_ED_SYNC
	_ENUM( DBE_SYNC_ED_REQ )
	_ENUM( DBE_SYNC_ED_ACK )
//#endif SERV_SEND_LETTER_BEFOR_ED_SYNC
	//}}

	//{{ 2012. 08. 14	박세훈	대천사의 주화 이벤트 가이드 문구 출력
//#ifdef SERV_ARCHUANGEL_S_COIN_EVENT_GUIDE
	_ENUM( DBE_CHECK_THE_ARCHUANGEL_S_COIN_EVENT_LETTER_REQ )
	_ENUM( DBE_CHECK_THE_ARCHUANGEL_S_COIN_EVENT_LETTER_ACK )
//#endif SERV_ARCHUANGEL_S_COIN_EVENT_GUIDE
	//}}

	//{{ 2012. 08. 21	박세훈	우편 로직 변경
//#ifdef SERV_TRADE_LOGIC_CHANGE_LETTER
	_ENUM( DBE_GET_ITEM_FROM_LETTER_ARRANGE_REQ )
	_ENUM( DBE_GET_ITEM_FROM_LETTER_ARRANGE_ACK )
//#endif SERV_TRADE_LOGIC_CHANGE_LETTER
	//}}

	//{{ 2012. 09. 02	박세훈	Merge ( 대전에서 클라이언트 조작등으로 UDP 패킷이 날아오지 않는 유저가 발견되면 서버에서 킥한다. // 2012.06.11 lygan_조성욱 )
//#ifdef UDP_CAN_NOT_SEND_USER_KICK
	_ENUM( ERM_UDP_CHECK_KICK_USER_NOT )
	_ENUM( ECN_UDP_KICK_GAMEEDIT_NOT )
//#endif UDP_CAN_NOT_SEND_USER_KICK
	//}}

	//{{ 2012. 09. 05	박세훈	랜선렉 로그 추가
//#ifdef UDP_CAN_NOT_SEND_USER_KICK
	_ENUM( DBE_UDP_CHECK_KICK_USER_NOT )
//#endif UDP_CAN_NOT_SEND_USER_KICK
	//}}

	//{{ 2012 대전 시즌2 전야 런칭 이벤트	- 김민성
//#ifdef SERV_2012_PVP_SEASON2_EVENT
	_ENUM( DBE_PVP_WIN_EVENT_CHECK_REQ )
	_ENUM( DBE_PVP_WIN_EVENT_CHECK_ACK )
//#endif SERV_2012_PVP_SEASON2_EVENT
	//}}

	//{{ 2012. 09. 22	박세훈	빙고 이벤트
//#ifdef SERV_EVENT_BINGO
	_ENUM( DBE_BINGO_EVENT_INFO_READ_REQ )		// 빙고 관련 이벤트 정보
	_ENUM( DBE_BINGO_EVENT_INFO_READ_ACK )
	_ENUM( DBE_BINGO_EVENT_INFO_WRITE_REQ )
	_ENUM( DBE_BINGO_EVENT_INFO_WRITE_ACK )
	_ENUM( DBE_BINGO_EVENT_LOTTERY_ACK )
	_ENUM( DBE_BINGO_EVENT_MIX_ACK )
	_ENUM( DBE_BINGO_EVENT_RESET_ACK )
	_ENUM( DBE_BINGO_EVENT_INIT_ACK )
//#endif SERV_EVENT_BINGO
	//}}

	//{{ 공존의 축제 - 지진 효과 - 김민성
//#ifdef SERV_EARTH_QUAKE_EFFECT
	_ENUM( EGB_EARTH_QUAKE_NOT )
//#endif SERV_EARTH_QUAKE_EFFECT
	//}}
	
	//{{ QUEST 개편 - 김민성
//#ifdef SERV_REFORM_QUEST
	_ENUM( ERM_UPDATE_QUEST_INFO_NOT )
//#endif SERV_REFORM_QUEST
//}}

//{{ 2012. 09. 19   김민성   캐시샵 방문 상태
//#ifdef SERV_VISIT_CASH_SHOP
	_ENUM( ERM_VISIT_CASH_SHOP_NOT )
	_ENUM( ERM_UPDATE_VISIT_CASH_SHOP_NOT )
//#endif SERV_VISIT_CASH_SHOP
//}}

//{{ 배틀필드 위험도 확인 치트 - 김민성
//#ifdef SERV_BATTLE_FIELD_DANGEROUS_CHEAT
	_ENUM( ERM_BATTLE_FIELD_DANGEROUS_VALUE_REQ )
	_ENUM( ERM_BATTLE_FIELD_DANGEROUS_VALUE_ACK )
//#endif SERV_BATTLE_FIELD_DANGEROUS_CHEAT
//}}
	//{{ 2012. 10. 16	최육사		ED&아이템 모니터링 시스템
//#ifdef SERV_ED_AND_ITEM_MORNITORING_SYSTEM
	_ENUM( DBE_GET_ED_AND_ITEM_MORNITOING_INFO_REQ )
	_ENUM( DBE_GET_ED_AND_ITEM_MORNITOING_INFO_ACK )
//#endif SERV_ED_AND_ITEM_MORNITORING_SYSTEM
	//}}
	//{{ 2012. 10. 16	최육사		P2P & Relay 정보 수집
//#ifdef SERV_COLLECTION_OF_RELAY_AND_P2P_INFO
	_ENUM( ELOG_COLLECTION_OF_RELAY_AND_P2P_INFO_NOT )
//#endif SERV_COLLECTION_OF_RELAY_AND_P2P_INFO
	//}}
//{{ 배틀필드 커뮤니티 리스트 확인 - 김민성
//#ifdef SERV_COMMUNITY_IN_BATTLE_FIELD
	_ENUM( ERM_COMMUNITY_IN_BATTLE_FIELD_REQ )
	_ENUM( ERM_COMMUNITY_IN_BATTLE_FIELD_ACK )
//#endif SERV_COMMUNITY_IN_BATTLE_FIELD
//}}

	//{{ 2012. 10. 10	박세훈	튕긴 유저 마을로 보내기
//#ifdef UDP_CAN_NOT_SEND_USER_KICK
	_ENUM( ERM_UDP_KICK_STATE_CHANGE_FIELD_NOT )
//#endif UDP_CAN_NOT_SEND_USER_KICK
	//}}

	//{{ 핑 상태체크 호스트 변경 - 김민성
	//#ifdef SERV_CHOOSE_FASTEST_HOST
	_ENUM( ERM_UDP_PING_SCORE_NOT )
	_ENUM( ERM_CHECK_PING_SCORE_CHANGE_HOST_NOT )
	//#endif SERV_CHOOSE_FASTEST_HOST
	//}
	//{{ 2012. 11. 9	최육사	배틀필드 시스템
//#ifdef SERV_BATTLE_FIELD_SYSTEM
	_ENUM( ERM_UPDATE_HENIR_REWARD_USER_NOT )
//#endif SERV_BATTLE_FIELD_SYSTEM
	//}}
	//{{ 2012. 11. 13	최육사		자동파티 대기열 카운트 표시
//#ifdef SERV_AUTO_PARTY_WAIT_USER_COUNT_VIEW
	_ENUM( EGB_REQUEST_AUTO_PARTY_WAIT_USER_COUNT_NOT )
	_ENUM( EGB_AUTO_PARTY_WAIT_USER_COUNT_NOT )
//#endif SERV_AUTO_PARTY_WAIT_USER_COUNT_VIEW
	//}}

	//{{ 2012. 10. 30	박세훈	Merge 랜선랙 방지 작업-릴레이를 기본적으로 사용한다.
//#ifdef SERV_FIX_SYNC_PACKET_USING_RELAY
	_ENUM( ERM_FORCE_RELAY_REQ )
	_ENUM( ERM_FORCE_RELAY_NOT )
//#endif SERV_FIX_SYNC_PACKET_USING_RELAY
	//}}

	//{{ 2012. 11. 15	박세훈	Field PT 로그 추가
//#ifdef SERV_FIELD_PLAY_TIME_LOG
	_ENUM( ERM_FIELD_USER_STATISTICS_NOT )
//#endif SERV_FIELD_PLAY_TIME_LOG
	//}}

	//{{ 2012. 11. 20	박세훈	Field Frame 로그 추가
//#ifdef SERV_FIELD_FRAME_LOG
	_ENUM( ERM_FIELD_USER_FRAME_INFO_NOT )
//#endif SERV_FIELD_FRAME_LOG
	//}}

	//{{ 2012. 11. 20	박세훈	영웅 대전 참가자 관리용 리스트
//#ifdef SERV_HERO_PVP_MANAGE_LIST
	_ENUM( EGB_ADMIN_HERO_PVP_USER_LIST_REQ )
	_ENUM( EGB_ADMIN_HERO_PVP_USER_LIST_ACK )

	_ENUM( EGB_ADMIN_NOTIFY_HERO_PVP_USER_REQ )
	_ENUM( EGB_ADMIN_NOTIFY_HERO_PVP_USER_ACK )
	_ENUM( EGB_ADMIN_NOTIFY_HERO_PVP_USER_NOT )
//#endif SERV_HERO_PVP_MANAGE_LIST
	//}}

	//{{ 2012. 12. 12	최육사	결과창 이탈 유저 로그
//#ifdef SERV_CHECK_USER_NEVER_RETURN_TO_FIELD
	_ENUM( DBE_DUNGEON_RESULT_LEAVE_LOG_NOT )
//#endif SERV_CHECK_USER_NEVER_RETURN_TO_FIELD
	//}}

	//{{ 2012. 12. 6	박세훈	랜선랙 방지 작업 오류 수정본
//#ifdef SERV_FIX_SYNC_PACKET_USING_RELAY
	_ENUM( ERM_ADD_UDP_CHECK_KICK_USER_NOT )
//#endif SERV_FIX_SYNC_PACKET_USING_RELAY
	//}}

	//{{ 2012. 12. 12	박세훈	겨울 방학 전야 이벤트( 임시, 하드 코딩 )
//#ifdef SERV_2012_WINTER_VACATION_EVENT
	_ENUM( DBE_2012_WINTER_VACATION_EVENT_NOT )
//#endif SERV_2012_WINTER_VACATION_EVENT
	//}}

	//{{ 2012. 12. 17	박세훈	잭팟 이벤트
//#ifdef SERV_EVENT_JACKPOT
	_ENUM( DBE_JACKPOT_EVENT_INIT_REQ )
	_ENUM( DBE_JACKPOT_EVENT_INIT_ACK )
	_ENUM( DBE_JACKPOT_EVENT_UPDATE_REQ )
	_ENUM( DBE_JACKPOT_EVENT_UPDATE_ACK )
	_ENUM( EGB_JACKPOT_EVENT_NOTIFY_NOT )
	_ENUM( EGB_JACKPOT_EVENT_POST_NOT )
//#endif SERV_EVENT_JACKPOT
	//}}

	//{{ 2012. 12. 14  계정 미션 시스템 ( 계정단위 퀘스트 ) - 김민성
//#ifdef SERV_ACCOUNT_MISSION_SYSTEM
	_ENUM( DBE_NEW_ACCOUNT_QUEST_REQ )	// account DB
	_ENUM( DBE_NEW_ACCOUNT_QUEST_ACK )
	_ENUM( DBE_NEW_ACCOUNT_QUEST_GAME_DB_REQ )	// game DB
	_ENUM( DBE_NEW_ACCOUNT_QUEST_GAME_DB_ACK )

	_ENUM( DBE_ACCOUNT_QUEST_COMPLETE_REQ )	// account DB
	_ENUM( DBE_ACCOUNT_QUEST_COMPLETE_ACK )
	_ENUM( DBE_ACCOUNT_QUEST_COMPLETE_GAME_DB_REQ )	// game DB
	_ENUM( DBE_ACCOUNT_QUEST_COMPLETE_GAME_DB_ACK )

	_ENUM( DBE_ACCOUNT_QUEST_UPDATE_NOT )// account DB
//#endif SERV_ACCOUNT_MISSION_SYSTEM
	//}}

	//{{ 2012. 12. 19  교환(한정 수량) - 김민성
//#ifdef SERV_ITEM_EXCHANGE_LIMIT_COUNT
	_ENUM( DBE_ITEM_EXCHANGE_LIMIT_CHECK_REQ )
	_ENUM( DBE_ITEM_EXCHANGE_LIMIT_CHECK_ACK )
//#endif SERV_ITEM_EXCHANGE_LIMIT_COUNT
	//}}

	//{{ 2012. 12. 24	박세훈	펫 오토 루팅 기능 추가
//#ifdef SERV_PET_AUTO_LOOTING
	_ENUM( DBE_PET_AUTO_LOOTING_NOT )
//#endif SERV_PET_AUTO_LOOTING
	//}}
	
	//{{ 2013. 01. 09 던전 강퇴 시스템 - 김민성
//#ifdef SERV_DUNGEON_FORCED_EXIT_SYSTEM
	_ENUM( ERM_BAD_ATTITUDE_USER_CHECK_INFO_NOT )
	_ENUM( ERM_BAD_ATTITUDE_USER_MSG_NOT )
	_ENUM( ERM_BAD_ATTITUDE_USER_NOT )
	_ENUM( ERM_FORCED_EXIT_VOTE_REQ )
	_ENUM( ERM_FORCED_EXIT_VOTE_ACK )
	_ENUM( ERM_DEFENCE_DUNGEON_WAVE_ID_NOT )
	_ENUM( ERM_BAD_ATTITUDE_USER_LOG_NOT )
	_ENUM( DBE_BAD_ATTITUDE_USER_LOG_NOT )
//#endif SERV_DUNGEON_FORCED_EXIT_SYSTEM
	//}
	//{{ 2013. 01. 21  대규모 이벤트 보상 시 최초 선택 캐릭터에게 지급하는 시스템 - 김민성
//#ifdef SERV_FIRST_SELECT_UNIT_REWARD_SYSTEM
	_ENUM( DBE_UPDATE_FIRST_SELECT_UNIT_REWARD_NOT )
//#endif SERV_FIRST_SELECT_UNIT_REWARD_SYSTEM
	//}
	//{{ 2013. 02. 	최육사	Tick퍼포먼스 DB로그 기록
//#ifdef SERV_SIMLAYER_TICK_PERFORMANCE_DB_LOG
	_ENUM( DBE_TICK_PERFORMANCE_LOG_NOT )
//#endif SERV_SIMLAYER_TICK_PERFORMANCE_DB_LOG
	//}}
	//{{ 2013. 02. 01  이벤트 발렌타인 던전 - 김민성
//#ifdef SERV_EVENT_VALENTINE_DUNGEON
	_ENUM( ERM_SYNC_DUNGEON_TIMER_NOT )
//#endif SERV_EVENT_VALENTINE_DUNGEON
	//}

	//{{ 2013. 2. 18	박세훈	랜선렉 방지 코드2
//#ifdef SERV_FIX_SYNC_PACKET_USING_RELAY
	_ENUM( ERM_REMOVE_LANBUG_CHECK_USER_NOT )
	_ENUM( ERM_REMOVE_LANBUG_VERIFY_USER_NOT )
//#endif SERV_FIX_SYNC_PACKET_USING_RELAY
	//}}

	//{{ 2013. 02. 19   교환 로그 추가 - 김민성
//#ifdef SERV_EXCHANGE_LOG
	_ENUM( DBE_ITEM_EXCHANGE_LOG_NOT )
//#endif SERV_EXCHANGE_LOG
	//}

	//{{ 2013. 02. 15   필드 중간 보스 - 김민성
//#ifdef SERV_BATTLEFIELD_MIDDLE_BOSS
	_ENUM( ERM_NPC_UNIT_CREATE_MIDDLE_BOSS_NOT )
	_ENUM( ERM_ADMIN_BATTLE_FIELD_INCREASE_DANGER_REQ )
	_ENUM( ERM_ADMIN_BATTLE_FIELD_INCREASE_DANGER_ACK )
	_ENUM( ERM_BATTLE_FIELD_NPC_DAMAGED_MAP_REQ )
	_ENUM( ERM_BATTLE_FIELD_NPC_DAMAGED_MAP_ACK )
	_ENUM( ERM_SYNC_BATTLE_FIELD_DAMAGED_MAP_NOT )
//#endif SERV_BATTLEFIELD_MIDDLE_BOSS
	//}

	//{{ 2013. 03. 12	최육사	몬스터 유효 검사
//#ifdef SERV_CHECK_EXIST_MONSTER_UID
	_ENUM( ERM_CHECK_EXIST_MONSTER_UID_REQ )
	_ENUM( ERM_CHECK_EXIST_MONSTER_UID_ACK )
//#endif SERV_CHECK_EXIST_MONSTER_UID
	//}}

	//{{ 2013. 02. 21	최육사	로그 시스템 개선
//#ifdef SERV_LOG_SYSTEM_NEW
	_ENUM( DBE_LOG_STATISTICS_INFO_NOT )
//#endif SERV_LOG_SYSTEM_NEW
	//}}

	//{{ 2013. 3. 4	박세훈	 로컬 랭킹 시스템
//#ifdef SERV_LOCAL_RANKING_SYSTEM
	_ENUM( DBE_GAME_LOCAL_RANKING_USER_INFO_READ_REQ )
	_ENUM( DBE_ACCOUNT_LOCAL_RANKING_USER_INFO_READ_REQ )
	_ENUM( DBE_ACCOUNT_LOCAL_RANKING_USER_INFO_READ_ACK )

	_ENUM( DBE_GAME_LOCAL_RANKING_UNIT_INFO_READ_FOR_INQUIRY_REQ )
	_ENUM( DBE_ACCOUNT_LOCAL_RANKING_UNIT_INFO_READ_FOR_INQUIRY_REQ )
	_ENUM( DBE_ACCOUNT_LOCAL_RANKING_UNIT_INFO_READ_FOR_INQUIRY_ACK )

	_ENUM( DBE_GAME_LOCAL_RANKING_UNIT_INFO_READ_FOR_INCREASE_REQ )
	_ENUM( DBE_ACCOUNT_LOCAL_RANKING_UNIT_INFO_READ_FOR_INCREASE_REQ )
	_ENUM( DBE_ACCOUNT_LOCAL_RANKING_UNIT_INFO_READ_FOR_INCREASE_ACK )

	_ENUM( DBE_LOCAL_RANKING_USER_INFO_WRITE_REQ )
	_ENUM( DBE_LOCAL_RANKING_USER_INFO_WRITE_ACK )

	_ENUM( ELG_LOCAL_RANKING_CHANGED_RANKER_INFO_CHECK_NOT )
	_ENUM( ELG_LOCAL_RANKING_CHANGED_RANKER_INFO_NOT )

	_ENUM( DBE_GAME_LOCAL_RANKING_INIT_INFO_REQ )
	_ENUM( DBE_GAME_LOCAL_RANKING_INIT_INFO_ACK )
	_ENUM( DBE_ACCOUNT_LOCAL_RANKING_INIT_INFO_REQ )
	_ENUM( DBE_ACCOUNT_LOCAL_RANKING_INIT_INFO_ACK )

	_ENUM( DBE_LOCAL_RANKING_RESET_REQ )
	_ENUM( DBE_LOCAL_RANKING_RESET_ACK )
	_ENUM( ELG_LOCAL_RANKING_RESET_NOT )

	_ENUM( ELG_LOCAL_RANKING_SYSTEM_INFO_CHECK_NOT )

	_ENUM( DBE_LOCAL_RANKING_RANKER_CHANGE_INFO_NOT )

	_ENUM( ELG_LOCAL_RANKING_RANK_UP_NOT )

	_ENUM( DBE_ACCOUNT_GET_GUILD_INFO_REQ )
	_ENUM( ELG_LOCAL_RANKING_GUILD_CHANGE_INFO_NOT )

	_ENUM( SOAP_LOCAL_RANKING_NEXON_ID_CHECK_FOR_READ_REQ )
	_ENUM( SOAP_LOCAL_RANKING_NEXON_ID_CHECK_FOR_READ_ACK )
	_ENUM( SOAP_LOCAL_RANKING_NEXON_ID_CHECK_FOR_WRITE_REQ )
	_ENUM( SOAP_LOCAL_RANKING_NEXON_ID_CHECK_FOR_WRITE_ACK )
//#endif SERV_LOCAL_RANKING_SYSTEM
	//}}

	//{{ 2013. 03. 21	 추천인 시스템 개편 - 김민성
//#ifdef SERV_RECOMMEND_LIST_EVENT
	_ENUM( DBE_RECOMMEND_USER_GET_NEXON_SN_REQ )
	_ENUM( DBE_RECOMMEND_USER_GET_NEXON_SN_ACK )
	_ENUM( SOAP_CHECK_SAME_USER_REQ )
	_ENUM( SOAP_CHECK_SAME_USER_ACK )
//#endif SERV_RECOMMEND_LIST_EVENT
	//}

	//{{ 2012. 11. 20	박세훈	영웅 대전 참가자 관리용 리스트
//#ifdef SERV_HERO_PVP_MANAGE_LIST
	_ENUM( EGB_ADMIN_HERO_PVP_USER_ADD_REQ )
	_ENUM( EGB_ADMIN_HERO_PVP_USER_ADD_ACK )
	
	_ENUM( EGB_ADMIN_HERO_PVP_USER_REMOVE_REQ )
	_ENUM( EGB_ADMIN_HERO_PVP_USER_REMOVE_ACK )

	_ENUM( EGB_ADMIN_HERO_PVP_USER_CONNECTION_NOT )
	_ENUM( EGB_ADMIN_HERO_PVP_USER_TOURNAMENT_CONNECTION_CHECK_NOT )
	_ENUM( EGB_ADMIN_HERO_PVP_USER_TOURNAMENT_CONNECTION_NOT )
//#endif SERV_HERO_PVP_MANAGE_LIST
	//}}

//#ifdef	SERV_LOCAL_RANKING_SYSTEM // 적용날짜: 2013-04-04
	_ENUM( DBE_LOCAL_RANKING_RESET_CHECK_REQ )
	_ENUM( DBE_LOCAL_RANKING_RESET_CHECK_ACK )
//#endif	// SERV_LOCAL_RANKING_SYSTEM

//#ifdef	SERV_LOCAL_RANKING_SYSTEM // 적용날짜: 2013-04-05
	_ENUM( ELG_LOCAL_RANKING_WATCH_UNIT_REQ )
	_ENUM( ELG_LOCAL_RANKING_WATCH_UNIT_ACK )
	_ENUM( DBE_GAME_LOCAL_RANKING_WATCH_UNIT_REQ )
	_ENUM( DBE_ACCOUNT_LOCAL_RANKING_WATCH_UNIT_REQ )
	_ENUM( DBE_ACCOUNT_LOCAL_RANKING_WATCH_UNIT_ACK )

	_ENUM( ELG_LOCAL_RANKING_SYSTEM_CHECK_NOT )
//#endif	// SERV_LOCAL_RANKING_SYSTEM

//{{ 2013. 04. 05	최육사	어둠의 문 개편
//#ifdef SERV_NEW_DEFENCE_DUNGEON
	_ENUM( ERM_PREPARE_FOR_DEFENCE_DUNGEON_REQ )
	_ENUM( ERM_PREPARE_FOR_DEFENCE_DUNGEON_ACK )

	_ENUM( ERM_DECISION_ENTER_DEFENCE_DUNGEON_NOT )
	_ENUM( ERM_DEFENCE_DUNGEON_GAME_START_NOT )
	_ENUM( ERM_CHANGE_GAME_STAT_INFO_IN_ROOM_NOT )
	_ENUM( ERM_CHANGE_DEFENCE_DUNGEON_PHASE_NOT )
//#endif SERV_NEW_DEFENCE_DUNGEON
//}}

	//{{ 2013. 04. 01	 인연 시스템 - 김민성
//#ifdef SERV_RELATIONSHIP_SYSTEM
	_ENUM( DBE_LOAD_WEDDING_HALL_INFO_REQ )
	_ENUM( DBE_LOAD_WEDDING_HALL_INFO_ACK )
	_ENUM( DBE_WEDDING_HALL_INFO_UPDATE_NOT )

	_ENUM( ELG_WEDDING_HALL_INFO_UPDATE_NOT )

	_ENUM( DBE_COUPLE_PROPOSE_USER_FIND_REQ )
	_ENUM( DBE_COUPLE_PROPOSE_USER_FIND_ACK )

	_ENUM( ELG_COUPLE_PROPOSE_CHECK_CONNECT_USER_REQ )
	_ENUM( ELG_COUPLE_PROPOSE_CHECK_CONNECT_USER_ACK )
	_ENUM( ELG_COUPLE_PROPOSE_NOT )

	_ENUM( ERM_COUPLE_PROPOSE_AGREE_CHECK_NOT )

	_ENUM( ERM_COUPLE_PROPOSE_RESULT_FAIL_NOT )
	_ENUM( ERM_COUPLE_PROPOSE_RESULT_SUCCESS_NOT )

	_ENUM( DBE_COUPLE_MAKING_SUCCESS_REQ )
	_ENUM( DBE_COUPLE_MAKING_SUCCESS_ACK )

	_ENUM( ELG_COUPLE_PROPOSE_RESULT_FAIL_NOT )
	_ENUM( ELG_COUPLE_PROPOSE_RESULT_SUCCESS_NOT )
	_ENUM( ELG_COUPLE_PROPOSE_AGREE_CHECK_NOT )

	_ENUM( ERM_COUPLE_MAKING_SUCCESS_NOT )
	_ENUM( ETR_COUPLE_MAKING_SUCCESS_NOT )

	_ENUM( ELG_RELATIONSHIP_INFO_REQ )
	_ENUM( ELG_RELATIONSHIP_INFO_ACK )

	_ENUM( DBE_RELATIONSHIP_INFO_GAME_DB_REQ )
	_ENUM( DBE_RELATIONSHIP_INFO_GAME_DB_ACK )

	_ENUM( ELG_RELATIONSHIP_INFO_GAME_SERVER_REQ )
	_ENUM( ELG_RELATIONSHIP_INFO_GAME_SERVER_ACK )
	
	_ENUM( ERM_RELATIONSHIP_EFFECT_NOT )
	_ENUM( ETR_RELATIONSHIP_EFFECT_NOT )

	_ENUM( DBE_WEDDING_PROPOSE_REQ )
	_ENUM( DBE_WEDDING_PROPOSE_ACK )

	_ENUM( DBE_CHECK_NICK_NAME_REQ )
	_ENUM( DBE_CHECK_NICK_NAME_ACK )

	_ENUM( ELG_ADD_WEDDING_HALL_INFO_NOT )

	_ENUM( DBE_WEDDING_ITEM_INFO_REQ )
	_ENUM( DBE_WEDDING_ITEM_INFO_ACK )

	_ENUM( ELG_WEDDING_ITEM_FIND_INFO_REQ )
	_ENUM( ELG_WEDDING_ITEM_FIND_INFO_ACK )

	_ENUM( DBE_WEDDING_ITEM_DELETE_REQ )
	_ENUM( DBE_WEDDING_ITEM_DELETE_ACK )

	_ENUM( DBE_WEDDING_ITEM_FIND_INFO_REQ )
	_ENUM( DBE_WEDDING_ITEM_FIND_INFO_ACK )

	_ENUM( ELG_CALL_MY_LOVER_FIND_USER_VILLAGE_REQ )
	_ENUM( ELG_CALL_MY_LOVER_FIND_USER_VILLAGE_ACK )
	_ENUM( ELG_CALL_MY_LOVER_VILLAGE_NOT )
	_ENUM( ELG_CALL_MY_LOVER_AGREE_RESULT_VILLAGE_NOT )
	_ENUM( ELG_CALL_MY_LOVER_STATE_CHANGE_FIELD_NOT )
	
	_ENUM( ERM_CALL_MY_LOVER_LEAVE_FIELD_REQ )
	_ENUM( ERM_CALL_MY_LOVER_LEAVE_FIELD_ACK )

	_ENUM( ERM_CALL_MY_LOVER_CHECK_ROOM_REQ )
	_ENUM( ERM_CALL_MY_LOVER_CHECK_ROOM_ACK )

	_ENUM( ELG_CALL_MY_LOVER_FIND_USER_ROOM_REQ )
	_ENUM( ELG_CALL_MY_LOVER_FIND_USER_ROOM_ACK )
	_ENUM( ELG_CALL_MY_LOVER_ROOM_NOT )
	_ENUM( ELG_CALL_MY_LOVER_AGREE_RESULT_ROOM_NOT )
	_ENUM( ELG_CALL_MY_LOVER_JOIN_BATTLE_FIELD_NOT )
	_ENUM( ERM_CALL_MY_LOVER_JOIN_BATTLE_FIELD_REQ )
	_ENUM( ERM_CALL_MY_LOVER_JOIN_BATTLE_FIELD_ACK )

	_ENUM( ELG_CALL_MY_LOVER_JOIN_BATTLE_FIELD_FAILD_NOT )

	_ENUM( ERM_LEAVE_BATTLE_FIELD_FOR_CALL_MY_LOVER_REQ )
	_ENUM( ERM_LEAVE_BATTLE_FIELD_FOR_CALL_MY_LOVER_ACK )

	_ENUM( ERM_WEDDING_HALL_INFO_NOT )
	
	_ENUM( ELG_CHECK_WEDDING_HALL_INFO_REQ )
	_ENUM( ELG_CHECK_WEDDING_HALL_INFO_ACK )

	_ENUM( ERM_LEAVE_BATTLE_FIELD_FOR_JOIN_WEDDING_HALL_REQ )
	_ENUM( ERM_LEAVE_BATTLE_FIELD_FOR_JOIN_WEDDING_HALL_ACK )


	_ENUM( ERM_OPEN_WEDDING_HALL_REQ )
	_ENUM( ERM_OPEN_WEDDING_HALL_ACK )

	_ENUM( ERM_JOIN_WEDDING_HALL_REQ )
	_ENUM( ERM_JOIN_WEDDING_HALL_ACK )
	_ENUM( ERM_JOIN_WEDDING_HALL_NOT )

	_ENUM( ERM_LEAVE_WEDDING_HALL_REQ )
	_ENUM( ERM_LEAVE_WEDDING_HALL_ACK )
	_ENUM( ERM_LEAVE_WEDDING_HALL_NOT )

	_ENUM( DBE_BREAK_UP_REQ )
	_ENUM( DBE_BREAK_UP_ACK )

	_ENUM( ELG_BREAK_UP_NOT )

	_ENUM( ERM_BREAK_UP_SUCCESS_NOT )

	_ENUM( ERM_CHECK_START_WEDDING_REQ )
	_ENUM( ERM_CHECK_START_WEDDING_ACK )
	_ENUM( ERM_CHECK_START_WEDDING_NOT )

	_ENUM( ERM_START_WEDDING_ASK_NOT )
	_ENUM( ERM_START_WEDDING_AGREE_NOT )

	_ENUM( DBE_WEDDING_COMPLETE_REQ )
	_ENUM( DBE_WEDDING_COMPLETE_ACK )

	_ENUM( ERM_START_WEDDING_NOT )

	_ENUM( DBE_CHANGE_LOVE_WORD_REQ )
	_ENUM( DBE_CHANGE_LOVE_WORD_ACK )

	_ENUM( ELG_CHANGE_LOVE_WORD_NOT )

	_ENUM( DBE_INSERT_WEDDING_REWARD_REQ )
	_ENUM( DBE_INSERT_WEDDING_REWARD_ACK )

	_ENUM( DBE_ADMIN_CHANGE_COUPLE_DATE_REQ )
	_ENUM( DBE_ADMIN_CHANGE_COUPLE_DATE_ACK )

	_ENUM( DBE_WRITE_RELATIONSHIP_INFO_LOG_REQ )
	_ENUM( DBE_WRITE_RELATIONSHIP_INFO_LOG_ACK )
//#endif SERV_RELATIONSHIP_SYSTEM
	//}

//#ifdef	SERV_LOCAL_RANKING_SYSTEM // 적용날짜: 2013-04-08
	_ENUM( ERM_LOCAL_RANKING_WATCH_UNIT_REQ )
	_ENUM( ERM_LOCAL_RANKING_WATCH_UNIT_ACK )
//#endif	// SERV_LOCAL_RANKING_SYSTEM

//#ifdef	SERV_RIDING_PET_SYSTM// 적용날짜: 2013-04-20
	_ENUM( DBE_GET_RIDING_PET_LIST_REQ )
	_ENUM( DBE_GET_RIDING_PET_LIST_ACK )

	_ENUM( ERM_SUMMON_RIDING_PET_NOT )
	_ENUM( ETR_SUMMON_RIDING_PET_NOT )
	
	_ENUM( ERM_UNSUMMON_RIDING_PET_NOT )
	_ENUM( ETR_UNSUMMON_RIDING_PET_NOT )

	_ENUM( DBE_CREATE_RIDING_PET_REQ )
	_ENUM( DBE_CREATE_RIDING_PET_ACK )

	_ENUM( DBE_RELEASE_RIDING_PET_REQ )
	_ENUM( DBE_RELEASE_RIDING_PET_ACK )
//#endif	// SERV_RIDING_PET_SYSTM

//{{ 2013. 04. 22	최육사	어둠의 문 입장 로직 변경
//#ifdef SERV_NEW_DEFENCE_DUNGEON_ENTER_LOGIC
	_ENUM( ERM_ENTER_DEFENCE_DUNGEON_POPUP_REPLY_NOT )
	_ENUM( ERM_LEAVE_ROOM_BEFORE_DEFENCE_DUNGEON_START_NOT )
//#endif SERV_NEW_DEFENCE_DUNGEON_ENTER_LOGIC
//}}

//{{ 2013. 05. 10	최육사	아이템 개편
//#ifdef SERV_NEW_ITEM_SYSTEM_2013_05
	_ENUM( DBE_ITEM_EVALUATE_REQ )
	_ENUM( DBE_ITEM_EVALUATE_ACK )

	_ENUM( DBE_RESTORE_ITEM_EVALUATE_REQ )
	_ENUM( DBE_RESTORE_ITEM_EVALUATE_ACK )

	_ENUM( DBE_ITEM_CONVERT_REQ )
	_ENUM( DBE_ITEM_CONVERT_ACK )
//#endif SERV_NEW_ITEM_SYSTEM_2013_05
//}}

//#ifdef SERV_SYNC_PACKET_USING_RELAY_WORKINGS_CHECK// 작업날짜: 2013-05-09	// 박세훈
	_ENUM( ERM_LEAVE_ROOM_FOR_WORKINGS_BLOCK_REQ )
	_ENUM( ERM_LEAVE_ROOM_FOR_WORKINGS_BLOCK_ACK )
//#endif // SERV_SYNC_PACKET_USING_RELAY_WORKINGS_CHECK

//#ifdef SERV_RELATIONSHIP_SYSTEM_LAUNCHING_EVENT// 작업날짜: 2013-05-10	// 박세훈
	_ENUM( DBE_SEND_LOVE_LETTER_EVENT_REQ )
	_ENUM( DBE_SEND_LOVE_LETTER_EVENT_ACK )
//#endif // SERV_RELATIONSHIP_SYSTEM_LAUNCHING_EVENT

//#ifdef SERV_LOCAL_RANKING_SYSTEM_STATISTICS_LOG// 작업날짜: 2013-05-15	// 박세훈
	_ENUM( DBE_LOCAL_RANKING_SYSTEM_STATISTICS_LOG_NOT )
//#endif // SERV_LOCAL_RANKING_SYSTEM_STATISTICS_LOG

//#ifdef SERV_DUNGEON_STAGE_LOAD_LOG// 작업날짜: 2013-05-15	// 박세훈
	_ENUM( DBE_DUNGEON_STAGE_LOAD_LOG_NOT )
//#endif // SERV_DUNGEON_STAGE_LOAD_LOG

//#ifdef SERV_FIELD_WORKINGS_BLOCK_LOG// 작업날짜: 2013-05-15	// 박세훈
	_ENUM( DBE_FIELD_WORKINGS_BLOCK_LOG_NOT )
//#endif // SERV_FIELD_WORKINGS_BLOCK_LOG

//#ifdef SERV_FIX_NONE_NPC_DUNGEON_LINES// 작업날짜: 2013-05-22	// 박세훈
	_ENUM( ERM_DUNGEON_KILLALLNPC_CHECK_NOT )
//#endif // SERV_FIX_NONE_NPC_DUNGEON_LINES

//#ifdef SERV_SYNC_PACKET_USING_RELAY_WORKINGS_CHECK// 작업날짜: 2013-05-22	// 박세훈
	_ENUM( DBE_BLOCK_COUNT_CHECK_INFO_UPDATE_NOT )

	_ENUM( DBE_BLOCK_COUNT_CHECK_INFO_READ_REQ )
	_ENUM( DBE_BLOCK_COUNT_CHECK_INFO_READ_ACK )
//#endif // SERV_SYNC_PACKET_USING_RELAY_WORKINGS_CHECK

//#ifdef SERV_TIME_ENCHANT_EVENT// 작업날짜: 2013-05-28	// 박세훈
	_ENUM( DBE_TIME_ENCHANT_EVENT_INFO_REQ )
	_ENUM( DBE_TIME_ENCHANT_EVENT_INFO_ACK )
	_ENUM( DBE_TIME_ENCHANT_EVENT_INFO_NOT )
	
	_ENUM( EGB_TIME_ENCHANT_EVENT_INFO_NOT )

	_ENUM( EGB_TIME_ENCHANT_EVENT_INFO_REQ )
	_ENUM( EGB_TIME_ENCHANT_EVENT_INFO_ACK )

	_ENUM( EGB_TIME_ENCHANT_EVENT_NOT )
	_ENUM( EGB_TIME_ENCHANT_EVENT_CUBE_NOT )
	_ENUM( EGB_TIME_ENCHANT_EVENT_DROP_NOT )

	_ENUM( DBE_TIME_ENCHANT_EVENT_INFO_UPDATE_REQ )
	_ENUM( DBE_TIME_ENCHANT_EVENT_INFO_UPDATE_ACK )
//#endif // SERV_TIME_ENCHANT_EVENT

//#ifdef SERV_HACKING_USER_CHECK_COUNT// 작업날짜: 2013-06-02	// 박세훈
	_ENUM( DBE_HACKING_USER_CHECK_COUNT_INFO_REQ )
	_ENUM( DBE_HACKING_USER_CHECK_COUNT_INFO_ACK )

	_ENUM( DBE_HACKING_USER_CHECK_COUNT_UPDATE_NOT )

	_ENUM( DBE_ACCOUNT_BLOCK_NOT )
//#endif // SERV_HACKING_USER_CHECK_COUNT

//#ifdef SERV_CHANGE_UPDATE_BUFF_INFO_PROCESS// 작업날짜: 2013-06-08	// 박세훈
	_ENUM( ERM_UPDATE_BUFF_INFO_NOT )
//#endif // SERV_CHANGE_UPDATE_BUFF_INFO_PROCESS

//#ifdef SERV_UPGRADE_SKILL_SYSTEM_2013 // 적용날짜: 2013-06-27
	_ENUM( DBE_ADMIN_CHANGE_UNIT_CLASS_REQ )
	_ENUM( DBE_ADMIN_CHANGE_UNIT_CLASS_ACK )
	_ENUM( DBE_ADMIN_AUTO_GET_ALL_SKILL_REQ )
	_ENUM( DBE_ADMIN_AUTO_GET_ALL_SKILL_ACK )
	_ENUM( DBE_ADMIN_GET_SKILL_REQ )
	_ENUM( DBE_ADMIN_GET_SKILL_ACK )
//#endif	// SERV_UPGRADE_SKILL_SYSTEM_2013

//#ifdef SERV_NEXON_COUPON_SYSTEM// 작업날짜: 2013-06-17	// 박세훈
	_ENUM( SOAP_COUPON_LIST_REQ )
	_ENUM( SOAP_COUPON_LIST_ACK )

	_ENUM( SOAP_REGIST_COUPON_REQ )
	//_ENUM( SOAP_REGIST_COUPON_ACK )	EGS_REGIST_COUPON_ACK를 바로 쏘고 있음.

	_ENUM( ENX_BT_NISMS_ITEM_COUPON_USING_REQ )
	_ENUM( ENX_BT_NISMS_ITEM_COUPON_USING_ACK )

	_ENUM( SOAP_COUPON_TARGET_ITEM_REQ )
	_ENUM( SOAP_COUPON_TARGET_ITEM_ACK )

	_ENUM( ENX_BT_NISMS_DISCOUNT_COUPON_INQUIRY_REQ )
	_ENUM( ENX_BT_NISMS_DISCOUNT_COUPON_INQUIRY_ACK )

	_ENUM( ENX_BT_NISMS_DISCOUNT_COUPON_INQUIRY_LIST_REQ )
	_ENUM( ENX_BT_NISMS_DISCOUNT_COUPON_INQUIRY_LIST_ACK )

	_ENUM( ENX_BT_NISMS_PURCHASE_GIFT_WITH_DISCOUNT_COUPON_REQ )
	_ENUM( ENX_BT_NISMS_PURCHASE_GIFT_WITH_DISCOUNT_COUPON_ACK )
//#endif // SERV_NEXON_COUPON_SYSTEM

//#ifdef SERV_ITEM_EXCHANGE_LIMIT// 작업날짜: 2013-06-29	// 박세훈
	_ENUM( DBE_EXCHANGE_LIMIT_INFO_REQ )
	_ENUM( DBE_EXCHANGE_LIMIT_INFO_ACK )
	_ENUM( DBE_EXCHANGE_LIMIT_INFO_NOT )

	_ENUM( EGB_EXCHANGE_LIMIT_INFO_NOT )

	_ENUM( EGB_EXCHANGE_LIMIT_INFO_REQ )
	_ENUM( EGB_EXCHANGE_LIMIT_INFO_ACK )

	_ENUM( EGB_EXCHANGE_LIMIT_REQ )
	_ENUM( EGB_EXCHANGE_LIMIT_ACK )

	_ENUM( DBE_EXCHANGE_LIMIT_INFO_UPDATE_REQ )
	_ENUM( DBE_EXCHANGE_LIMIT_INFO_UPDATE_ACK )

	_ENUM( EGB_EXCHANGE_LIMIT_INFO_ROLLBACK_NOT )
	_ENUM( DBE_EXCHANGE_LIMIT_INFO_ROLLBACK_NOT )
//#endif // SERV_ITEM_EXCHANGE_LIMIT

//#ifdef SERV_JUMPING_CHARACTER// 작업날짜: 2013-07-10	// 박세훈
	_ENUM( DBE_JUMPING_CHARACTER_INFO_NOT )

	_ENUM( DBE_JUMPING_CHARACTER_UPDATE_REQ )
	_ENUM( DBE_JUMPING_CHARACTER_UPDATE_ACK )
//#endif // SERV_JUMPING_CHARACTER

//#ifdef SERV_FINALITY_SKILL_SYSTEM	// 적용날짜: 2013-08-01
	_ENUM( DBE_ITEM_EXTRACT_REQ )
	_ENUM( DBE_ITEM_EXTRACT_ACK )

	_ENUM( DBE_USE_FINALITY_SKILL_REQ )
	_ENUM( DBE_USE_FINALITY_SKILL_ACK )
//#endif // SERV_FINALITY_SKILL_SYSTEM

    _ENUM( ELOG_HENIR_HACKING_LOG_NOT )

//#ifdef SERV_BATTLE_FIELD_BOSS// 작업날짜: 2013-10-28	// 박세훈
	_ENUM( ERM_UPDATE_TOTAL_DANGEROUS_VALUE_NOT )
	_ENUM( EGB_UPDATE_TOTAL_DANGEROUS_VALUE_NOT )

	_ENUM( EGB_BATTLE_FIELD_BOSS_INFO_NOT )

	_ENUM( EGB_VERIFY_SERVER_CONNECT_NOT )
	_ENUM( EGB_VERIFY_SERVER_DISCONNECT_NOT )

	_ENUM( ERM_BOSS_FIELD_INTRUDE_RESTRICTION_REQ )
	_ENUM( ERM_BOSS_FIELD_INTRUDE_RESTRICTION_ACK )
	_ENUM( ERM_BOSS_FIELD_CLOSE_PROCESS_NOT )
	_ENUM( ERM_BOSS_FIELD_RETURN_PROCESS_NOT )

	_ENUM( EGB_ADMIN_BOSS_FIELD_GATE_OPEN_REQ )
	_ENUM( EGB_ADMIN_BOSS_FIELD_GATE_OPEN_ACK)
	_ENUM( EGB_ADMIN_BOSS_FIELD_GATE_CLOSE_NOT )
	_ENUM( EGB_ADMIN_GET_TOTAL_DANGEROUS_VALUE_REQ )
	_ENUM( EGB_ADMIN_GET_TOTAL_DANGEROUS_VALUE_ACK )
	_ENUM( EGB_ADMIN_SET_TOTAL_DANGEROUS_VALUE_REQ )
	_ENUM( EGB_ADMIN_SET_TOTAL_DANGEROUS_VALUE_ACK )

	_ENUM( DBE_SOCKET_EXPAND_ITEM_REQ )
	_ENUM( DBE_SOCKET_EXPAND_ITEM_ACK )

	_ENUM( ERM_BOSS_FIELD_LOG_NOT )
	_ENUM( DBE_BOSS_FIELD_LOG_NOT )
//#endif // SERV_BATTLE_FIELD_BOSS

//#ifdef SERV_STAGE_CLEAR_IN_SERVER// 작업날짜: 2013-10-30	// 박세훈
	_ENUM( ERM_DUNGEON_SUB_STAGE_CLEAR_REQ )
	_ENUM( ERM_DUNGEON_SUB_STAGE_CLEAR_ACK )
	_ENUM( ERM_SECRET_STAGE_LOAD_REQ )
	_ENUM( ERM_SECRET_STAGE_LOAD_ACK )
//#endif // SERV_STAGE_CLEAR_IN_SERVER

//#ifdef SERV_GOOD_ELSWORD
    _ENUM( DBE_EXPAND_BANK_INVENTORY_REQ )
    _ENUM( DBE_EXPAND_BANK_INVENTORY_ACK )
    _ENUM( ELOG_EXPAND_BANK_INVENTORY_NOT )
//#endif // SERV_GOOD_ELSWORD

    _ENUM( ELOG_GEN_FIELD_MIDDLE_BOSS_STAT_NOT )
    _ENUM( ELOG_KILL_FIELD_MIDDLE_BOSS_STAT_NOT )

	//#ifdef SERV_KOM_FILE_CHECK_ADVANCED
	_ENUM( ELOG_KOM_FILE_CHECK_LOG_NOT )
	//#endif SERV_KOM_FILE_CHECK_ADVANCED

//#ifdef SERV_SKILL_PAGE_SYSTEM
	_ENUM( DBE_EXPAND_SKILL_PAGE_REQ )
	_ENUM( DBE_EXPAND_SKILL_PAGE_ACK )

	_ENUM( DBE_DECIDE_TO_USE_THIS_SKILL_PAGE_REQ )
	_ENUM( DBE_DECIDE_TO_USE_THIS_SKILL_PAGE_ACK )

	_ENUM( ELOG_EXPAND_SKILL_PAGE_NOT )
//#endif // SERV_SKILL_PAGE_SYSTEM

    //_ENUM( DBE_CHANNEL_UNIT_AND_INVENTORY_INFO_LIST_REQ )
    //_ENUM( DBE_CHANNEL_UNIT_AND_INVENTORY_INFO_LIST_ACK )
    _ENUM( DBE_CHANNEL_CHECK_NICK_NAME_REQ )

    _ENUM( DBE_CHARACTER_LIST_REQ )
    _ENUM( DBE_CHARACTER_LIST_2ND_REQ )

    _ENUM( DBE_ENTRY_POINT_CHECK_NICK_NAME_REQ )

    _ENUM( DBE_GET_CREATE_UNIT_TODAY_COUNT_REQ )
    //_ENUM( DBE_GET_CREATE_UNIT_TODAY_COUNT_2ND_DB_REQ )
    _ENUM( DBE_CHANNEL_LIST_2ND_ACK )

//#ifdef SERV_NAVER_CHANNELING
    _ENUM( NAVER_SOAP_GET_TOKEN_REQ )
    _ENUM( NAVER_SOAP_GET_TOKEN_ACK )
//#endif SERV_NAVER_CHANNELING

//#ifdef SERV_SERVER_DISCONNECT_LOG
	_ENUM( E_LOCAL_LOG_UNDEFINED_QUEST_TEMPLET_NOT )
//#endif // SERV_SERVER_DISCONNECT_LOG

//#ifdef SERV_MODFIY_FLAG_REALTIME_PATCH
	// 브로드캐스팅을 위해 센터를 거침
	// ( 게임서버SimLayer -> 센터 서버 -> 게임서버 )
	_ENUM( ECN_DEL_COMMON_FLAG_NOT )	
	_ENUM( ECN_ADD_COMMON_FLAG_NOT )
	_ENUM( EGS_DEL_COMMON_FLAG_NOT )
	_ENUM( EGS_ADD_COMMON_FLAG_NOT )
//#endif // SERV_MODFIY_FLAG_REALTIME_PATCH

	//=============================================================//
	//{{ 2013.02.27 조효진	해외 기본 구조 작업 (SERV_GLOBAL_BASE)
#   include "OnlyGlobal/EventID_Server_global.h"
	//}}
	//=============================================================//	
	
	//////////////////////////////////////////////////////////////////////////
    // 여기 밑으로 패킷 타입 정의하지 마세요!!!
    _ENUM( EVENT_EVENTID_SENTINEL ) // 패킷의 끝!


#ifdef __NEVER_DEFINED_MACRO__
};
#undef _ENUM
#endif
