// SERV_CODE_EVENT 에서 이용하는 서버, 클라, script 공통 enum

enum CODE_EVENT_ID
{
	CEI_NONE = 0,
	CEI_PVP_REWARD_ELSWORD_COIN						= 1,
	CEI_PVP_REWARD_AISHA_COIN						= 2,
	CEI_PVP_REWARD_RENA_COIN						= 3,
//#ifdef SERV_OFFCIAL_PVP_HERO_NPC_REWARD_TIME
	CEI_OFFCIAL_PVP_HERO_NPC_REWARD					= 4,
//#endif //SERV_OFFCIAL_PVP_HERO_NPC_REWARD_TIME
//#ifdef SERV_EVENT_PVP_NPC_MATCH_TIME
	CEI_OFFCIAL_PVP_EVENT_NPC_MATCH					= 5,
//#endif //SERV_EVENT_PVP_NPC_MATCH_TIME
//#ifdef SERV_VELDER_AUTO_OPEN_HARD_CODE
	CEI_VELDER_AUTO_OPEN_HARD_CODE					= 6,
//#endif //SERV_VELDER_AUTO_OPEN_HARD_CODE
//#ifdef SERV_EVENT_FOOLS_DAY_2013
	CEI_EVENT_FOOLS_DAY_2013						= 7,
//#endif SERV_EVENT_FOOLS_DAY_2013
//#ifdef SERV_EVENT_ELSWORD_PARTY_PLAY_ITEM_GIVE
	CEI_EVENT_ELSWORD_PARTY_PLAY_ITEM_GIVE			= 8,
//#endif //SERV_EVENT_ELSWORD_PARTY_PLAY_ITEM_GIVE
//#ifdef SERV_COUPON_EVENT
	CEI_EVENT_COUPON_WEEKDAY						= 9,
	CEI_EVENT_COUPON_WEEKEND						= 10,
//#endif SERV_COUPON_EVENT
//#ifdef SERV_ENCHANT_EVENT_USING_DB
	CEI_11_ENCHANT_EVENT							= 11,
//#endif SERV_ENCHANT_EVENT_USING_DB
//#ifdef SERV_ENCHANT_ITEM_EVENT
	CEI_ENCHANT_ITEM_EVENT							= 12,
//#endif SERV_ENCHANT_ITEM_EVENT
//#ifdef SERV_IN_VILLAGE_EVENT_NPC_BY_CODE_EVENT
	CEI_EVENT_IN_VILLAGE_EVENT_NPC					= 13,
//#endif //SERV_IN_VILLAGE_EVENT_NPC_BY_CODE_EVENT
//#ifdef SERV_READY_TO_SOSUN_EVENT
	CEI_READY_TO_SOSUN_EVENT						= 14,
//#endif //SERV_READY_TO_SOSUN_EVENT
//#ifdef SERV_MOMOTI_EVENT
	CEI_MOMOTI_URL_EVENT							= 15,
	CEI_MOMOTI_QUIZ_EVENT							= 16,
//#endif //SERV_MOMOTI_EVENT

//#ifdef SERV_NEW_DEFENCE_DUNGEON_ENTER_100_PERCENT_EVENT
	CEI_NEW_DEFENCE_DUNGEON_ENTER_100_PERCENT_EVENT = 17,
//#endif //SERV_NEW_DEFENCE_DUNGEON_ENTER_100_PERCENT_EVENT

//#ifdef SERV_2013_JUNGCHU_TITLE
	CEI_2013_JUNGCHU_TITLE							= 18,
//#endif SERV_2013_JUNGCHU_TITLE
//#ifdef SERV_RELATIONSHIP_EVENT_INT
	CEI_RELATIONSHIP_CODE_EVENT						= 19,
//#endif SERV_RELATIONSHIP_EVENT_INT
//#ifdef SERV_ACCUMULATION_SPIRIT_SYSTEM
	CEI_ACCUMULATION_SPIRIT_EVENT					= 20,
//#endif SERV_ACCUMULATION_SPIRIT_SYSTEM
//#ifdef SERV_ELISIS_PREVIOUS_SIS_EVENT
	CEI_ELISIS_PREVIOUS_SIS_EVENT					= 21,
//#endif SERV_ELISIS_PREVIOUS_SIS_EVENT

	CEI_SANDER_AUTO_OPEN_HARD_CODE					= 22,

//#ifdef CHRISTMAS_EVENT_2013
	CEI_CHRISTMAS_EVENT_2013						= 23,
//#endif //CHRISTMAS_EVENT_2013

//#ifdef SERV_NEW_YEAR_EVENT_2014
	CEI_OLD_YEAR_EVENT_2013							= 24,
	CEI_NEW_YEAR_EVENT_2014							= 25,
//#endif //SERV_NEW_YEAR_EVENT_2014

//#ifdef SERV_EVENT_LEVEL_UP_ARA
	CEI_EVENT_LEVEL_UP_ARA							= 26,
//#endif //SERV_EVENT_LEVEL_UP_ARA

//#ifdef SERV_ARA_FIRST_CLASS_CHANGE_EVENT
	CEI_ARA_FIRST_CLASS_CHANGE_EVENT				= 27,
//#endif //SERV_ARA_FIRST_CLASS_CHANGE_EVENT

//#ifdef SERV_GATE_OF_DARKNESS_SUPPORT_EVENT
	CEI_GATE_OF_DARKNESS_SUPPORT_EVENT				= 28,
//#endif //SERV_GATE_OF_DARKNESS_SUPPORT_EVENT

//#ifdef SERV_NEW_YEAR_EVENT_2014
	CEI_ALLOW_EVE_FIRST_CLASS_OLD_YEAR_EVENT				= 29,
	CEI_ALLOW_ARA_FIRST_CLASS_OLD_YEAR_EVENT				= 30,
	CEI_ALLOW_ELESIS_FIRST_CLASS_OLD_AND_NEW_YEAR_EVENT		= 31,
//#endif //SERV_NEW_YEAR_EVENT_2014

//#ifdef SERV_EVENT_CHECK_POWER
	CEI_CHECK_POWER											= 32,
//#endif SERV_EVENT_CHECK_POWER

//#ifdef SERV_CHANNELING_AERIA_EVENT
	CEI_CHANNELING_AERIA_EVENT						= 33,
//#endif //SERV_CHANNELING_AERIA_EVENT



//#ifdef SERV_ARA_NEW_FIRST_CLASS_EVENT
	CEI_ARA_NEW_FIRST_CLASS_EVENT				= 34,
//#endif SERV_ARA_NEW_FIRST_CLASS_EVENT

//#ifdef SERV_ARA_NEW_SECOND_CLASS_EVENT
	CEI_ARA_NEW_SECOND_CLASS_EVENT					= 35,
//#endif SERV_ARA_NEW_SECOND_CLASS_EVENT

//#ifdef SERV_BALANCE_FINALITY_SKILL_EVENT
	CEI_BALANCE_FINALITY_SKILL_EVENT				= 36,
//#endif SERV_BALANCE_FINALITY_SKILL_EVENT
//#ifdef SERV_EVENT_COBO_DUNGEON_AND_FIELD
	CEI_EVENT_COBO_DUNGEON_AND_FIELD				= 37,
//#endif SERV_EVENT_COBO_DUNGEON_AND_FIELD

//#ifdef ALWAYS_EVENT_ADAMS_UI_SHOP
	CEI_EVENT_ADAMS_SHOP							= 38,
//#endif ALWAYS_EVENT_ADAMS_UI_SHOP

//#ifdef SERV_BATTLEFIELD_EVENT_BOSS_INT
	CEI_EVENT_BATTLEFIELD_EVENT_BOSS				= 39,
//#endif SERV_BATTLEFIELD_EVENT_BOSS_INT

	CEI_CHRISTMAS_DISCOUNT_EVENT_2013				= 40,
//#ifdef SERV_ELESIS_NEW_FIRST_CLASS_EVENT
	CEI_ELESIS_NEW_FIRST_CLASS_EVENT					= 41,
//#endif SERV_ELESIS_NEW_FIRST_CLASS_EVENT
//#ifdef ADD_CASH_SHOP_CATEGORY_EVENT_2
	CEI_CASH_SHOP_CATEGORY_EVENT_2_SHOW				= 42,
//#endif ADD_CASH_SHOP_CATEGORY_EVENT_2

//#ifdef SERV_EVENT_CHANGE_CLASS
	CEI_EVENT_CHANGE_CLASS		= 43,
//#endif //#ifdef SERV_EVENT_CHANGE_CLASS

//#ifdef SERV_BUFF_BONUSRATE_HAMEL_EVENT
	CEI_HAMEL_EVENT_BUFF							= 44,
//#endif SERV_BUFF_BONUSRATE_HAMEL_EVENT

//#ifdef SERV_GUILD_BONUSRATE_POINT
	CEI_GUILD_BONUSRATE_POINT						= 45,
//#endif SERV_GUILD_BONUSRATE_POINT

//#ifdef SERV_EVENT_TEAR_OF_ELWOMAN
	CEI_TEAR_OF_ELWOMAN								= 46,
//#endif SERV_EVENT_TEAR_OF_ELWOMAN

//#ifdef EVENT_CARNIVAL_DECORATION	
	CEI_CARNIVAL_DECORATION							= 47,
//#endif EVENT_CARNIVAL_DECORATION

//#ifdef SERV_CREATE_CHUNG_REWARD_TITLE
	CEI_CREATE_CHUNG_REWARD_TITLE					= 48,
//#endif SERV_CREATE_CHUNG_REWARD_TITLE
//#ifdef SERV_4TH_ANNIVERSARY_EVENT
	CEI_4TH_ANNIVERSARY_EVENT						= 49,
//#endif //SERV_4TH_ANNIVERSARY_EVENT

//#ifdef SERV_INT_ENTRY_POINT_LEVEL_UP_EVENT
	CEI_INT_ENTRY_POINT_LEVEL_UP_EVENT					= 50,
//#endif SERV_INT_ENTRY_POINT_LEVEL_UP_EVENT

	CEI_END,
};
