_ENUM( SI_PVP_MAP )
_ENUM( SI_FPS )
_ENUM( SI_RES_STONE )
_ENUM( SI_ED )
_ENUM( SI_QUEST )
_ENUM( SI_DISCONNECT_REASON )
_ENUM( SI_DISCONNECT_USERFSM )
_ENUM( SI_LOC_ITEM )
_ENUM( SI_LOC_PVP )
_ENUM( SI_LOC_DUNGEON )
_ENUM( SI_LOC_SPIRIT )
_ENUM( SI_LOC_ENCHANT )
_ENUM( SI_LOC_PVP_VICTORY_PER )
_ENUM( SI_LOC_PVP_ROOM )
_ENUM( SI_LOC_DUNGEON_ROOM )
_ENUM( SI_LOC_HENIR_RANKING )
//{{ 2008. 10. 16  √÷¿∞ªÁ	≈∏¿Ã∆≤
_ENUM( SI_LOC_TITLE )
//}}
//{{ 2010. 9. 14	√÷¿∞ªÁ	∆Í Ω√Ω∫≈€
//#ifdef SERV_PET_SYSTEM
_ENUM( SI_LOC_PET_SUMMON )
//#endif SERV_PET_SYSTEM
//}}
//{{ 2010. 10. 11	√÷¿∞ªÁ	º≠πˆ∞£ ¡¢º” ≤˜±Ë ∑Œ±◊
//#ifdef SERV_SERVER_DISCONNECT_LOG
_ENUM( SI_LOC_SERV_DISCONNECT )
//#endif SERV_SERVER_DISCONNECT_LOG
//}}
//{{ 2010. 10. 11	√÷¿∞ªÁ	≥ÿΩº ∫Ù∏µ ∆–≈∂ ∑Œ±◊
//#ifdef SERV_BILLING_PACKET_LOG
_ENUM( SI_LOC_BILLING_PACKET )
//#endif SERV_BILLING_PACKET_LOG
//}}
//{{ 2010. 11. 17	√÷¿∞ªÁ	ø¿≈‰«Ÿ ∞À¡ı ±‚¥…
//#ifdef SERV_AUTO_HACK_CHECK_GET_ITEM
_ENUM( SI_LOC_ABUSER_MORNITORING )
//#endif SERV_AUTO_HACK_CHECK_GET_ITEM
//}}
//#ifdef SERV_WATCH_ITEM
_ENUM( SI_LOC_WATCH )
//#endif SERV_WATCH_ITEM
//{{ 2011. 02. 28	√÷¿∞ªÁ	¡ﬂ±π ∫Ù∏µ ¿€æ˜
//#ifdef SERV_CHAR_CREATE_DEL_STAT
_ENUM( SI_CHARACTER )
//#endif SERV_CHAR_CREATE_DEL_STAT
//}}
//{{ 2011. 04. 13	√÷¿∞ªÁ	æ∆¿Ã≈€ ≈Î∞Ë DB±‚∑œ
//#ifdef SERV_ITEM_STATISTICS_TO_DB
_ENUM( SI_ITEM_DB )
//#endif SERV_ITEM_STATISTICS_TO_DB
//}}
_ENUM( SI_SENTINEL )
