#pragma once

//DE버전 출력
static wchar_t* szErrorStrDE[] = {
	L"Erfolg",
	L"Unbekannter Fehler",
	L"Es ist ein Fehler beim Status des Spielers aufgetreten.",
	L"Die Version ist fehlerhaft. Logge dich erneut ein.",
	L"Server ist voll. Maximale Anzahl der Spieler ist erreicht.",
	L"Der Spiele-Server wird überprüft. Logge dich nach der Systemprüfung ein.",
	L"Du hast versucht, dich zweimal auf den selben Server einzuloggen.",
	L"Es wurde versucht, sich in verschiedene Channels gleichzeitig einzuloggen.",
	L"Prüfung der Server-IP ist fehlgeschlagen.",
	L"UID-Server ist abgestürzt.",
	L"User existiert nicht",
	L"Dieser Spieler existiert nicht mehr.",
	L"Die Login-Daten sind falsch.",
	L"Die Server-Einstellungen sind nicht korrekt.",
	L"Deine Zugangsdaten konnten nicht verifiziert werden.",
	L"Dein Account wurde gesperrt.\nBitte wende dich an den Elsword-Support: http://support.elsword.de",
	L"Anfrage ist nur von einem System Operator möglich.",
	L"Keine Proxy ID vorhanden.",
	L"Die IP-Adresse ist nicht erlaubt.",
	L"Die ID-Daten für den Channel existieren auf dem Game-Server nicht.",
	L"Die ID-Länge ist fehlerhaft.",
	L"Transaktionsfehler.",
	L"Die ID-Länge ist nicht zulässig.",
	L"Die Länge des Passwortes ist ungültig.",
	L"Die Länge des Benutzernamens ist ungültig.",
	L"Der gelöschte Spieler hat versucht einen Charakter zu erstellen.",
	L"Charaktername ist bereits vorhanden.",
	L"Transaktionsfehler.",
	L"Fehler beim Laden der Charakter-Daten.",
	L"Die Länge des Charakternamen ist fehlerhaft.",
	L"Es können keine weiteren Charaktere erstellt werden.",
	L"Nickname derzeit nicht benutzbar!",
	L"Die Datenbank konnte den CharakterSN für den Messenger nicht erstellen.",
	L"Dieser Nickname kann nicht verwendet werden.",
	L"Es können pro Tag maximal vier Charakter erstellt werden.",
	L"Der gewählte Charakter befindet sich nicht im Spiele-Server.",
	L"Die gewählte Klasse des Charakters ist fehlerhaft.",
	L"Information zum Wiederbelebungsstein konnte nicht abgerufen werden.",
	L"Die Datenbank konnte den CharakterSN des Messengers nicht aufrufen.",
	L"Bei der Auswahl des Charakters ist ein Fehler in der Datenbank aufgetreten.",
	L"Der Nickname muss geändert werden.",
	L"Kein PvP-Channel gefunden, der zu deinem Level passt.",
	L"Der zu löschende Spieler ist nicht auf dem Channel.",
	L"Channel-Wechsel fehlgeschlagen.",
	L"Nicht genügend VP um beizutreten.",
	L"Betreten des Dorfplatz-Channels fehlgeschlagen.",
	L"Channel Betreten fehlgeschlagen.",
	L"Es wird kein Wettkampf ausgeführt.",
	L"Die Gruppenliste kann nicht aufgerufen werden.",
	L"Im Dungeon Gate kannst du die Gruppenliste nicht einsehen.",
	L"In diesem Dungeon Gate kann die Gruppenliste nicht geöffnet werden.",
	L"PvP ist erst ab Level 3 möglich.",
	L"Auf dem Server können keine weiteren Räume erstellt werden.",
	L"In diesem Slot ist kein User zu finden.",
	L"Der Slot, in dem sich der gewählte Charakter befindet, wurde nicht gefunden.",
	L"Der Raum ist voll.",
	L"Die Login-Daten sind falsch.",
	L"Vorheriger Dungeon wurde nicht abgeschlossen.",
	L"Sofortiger Start fehlgeschlagen. Keine Räume vorhanden.",
	L"Nur der Meister dieses Raumes darf das beantragen.",
	L"Der Raum-Status erlaubt momentan keine Pakete.",
	L"Dieser Spieler ist noch nicht bereit.",
	L"Anzahl der Team-Mitglieder stimmt nicht überein.",
	L"Mehr als ein Charakter muss \"Bereit\" sein, um das Spiel starten zu können.",
	L"Ladevorgang konnte nicht geändert werden.",
	L"Der Raum wurde erstellt.",
	L"Die Informationen zum Raum wurden geändert.",
	L"Der Raum wurde gelöscht.",
	L"Im Raum konnte kein Spieler gefunden werden.",
	L"Eintritt fehlgeschlagen.",
	L"Du konntest den Raum nicht verlassen.",
	L"Der UID des gestorbenden NPCs ist fehlerhaft.",
	L"Der NPC ist bereits tot.",
	L"Monsterdaten fehlerhaft. Ladevorgang fehlgeschlagen.",
	L"Der Spieler kann nicht gefunden werden.",
	L"Der Chattyp ist fehlerhaft.",
	L"Du kannst dich nicht selbst aus dem Raum verweisen.",
	L"Nicht genügend Willenspunkte.",
	L"Dieser Spieletyp unterstützt nicht die Ergänzungsstatistiken.",
	L"Das Spiel wird beendet. Du kannst den Raum nicht betreten.",
	L"Du kannst den Raum nicht betreten.",
	L"Der Raum, den du betreten willst, enthält keine Informationen.",
	L"Während des Handelns kannst du dich nicht auf ein Spiel vorbereiten.",
	L"Du kannst den Raum nicht mehr betreten, da das Spiel gerade startet. Versuche es später erneut.",
	L"Es befindet sich kein Spielstarter-Item im Inventar.",
	L"Ein Spieler ohne Berechtigung hat versucht, einen Observationsraum zu erstellen.",
	L"Die Map-Daten des PvP sind falsch.",
	L"Nur wer eine Offline-Teilnahmeberechtigung für das Turnier hat, kann den Turnier-Channel benutzen.",
	L"Dir fehlt das Item um den gewählten Dungeon zu spielen. Nach dem Start des Spiels wirst du aus dem Dungeon verwiesen.",
	L"Nur im PvP-Raum kann die Funktion des Einladens verwendet werden.",
	L"Der Spieler, der eingeladen werden soll, kann im Moment nicht den PvP-Raum betreten.",
	L"Du kannst nur Spieler einladen, die sich in der Lobby des PvP-Channels befinden.",
	L"Das Spiel kann nur gestartet werden, wenn du in der Gruppe angemeldet bist.",
	L"Fehlerhafte Einstellung für die Anzahl der Kills.",
	L"Das Item gibt es nicht mehr.",
	L"Jemand anderes hat es bereits erhalten.",
	L"Zufällige Verteilung der Items fehlgeschlagen.",
	L"Keine Informationen zum Item vorhanden.",
	L"Die Item-ID ist fehlerhaft.",
	L"Das Item konnte nicht vergeben werden.",
	L"Das Item konnte nicht repariert werden",
	L"Item im Quickslot konnte nicht benutzt werden",
	L"Im Event-Dungeon kann der Quickslot nicht verwendet werden",
	L"Item konnte nicht erworben werden",
	L"Item aus der Ablage konnte nicht aufgenommen werden",
	L"Nicht genug Platz für das Item aus der Ablage.",
	L"Die Nachricht ist zu lang.",
	L"Team konnte nicht gewechselt werden",
	L"Die Änderungen im Slot konnten nicht gespeichert werden.",
	L"Die Beteiligung ist fehlgeschlagen.",
	L"Der Slot konnte nicht geschlossen werden.",
	L"Der User konnte nicht gekickt werden.",
	L"Die Daten des Gegners konnten nicht gespeichert werden.",
	L"Der Status konnte nicht geändert werden.",
	L"Verlassen wurde durch Spieler verursacht.",
	L"Die Verbindung wurde beendet.",
	L"Du wurdest gekickt.",
	L"Dein Level ist nun zu hoch für diesen Channel.",
	L"Der Verkaufsstand wurde geschlossen.",
	L"Der Besuch des Verkaufsstandes ist fehlgeschlagen.",
	L"Die Zeit ist abgelaufen. Der Verkaufsstand wurde geschlossen.",
	L"Der Verkaufsstand wurde abgebrochen.",
	L"Die Anzahl der Privatverkäufer ist fehlerhaft.",
	L"Beim Handel ist ein Fehler aufgetreten.",
	L"Du hast zu wenig Platz im Inventar oder die Itemdaten sind fehlerhaft.",
	L"Du hast nicht mehr genügend Willenspunkte.",
	L"Der Handel wurde abgebrochen. Es gibt keine Gegenstände zum Handeln.",
	L"Der Handel wurde abgebrochen.",
	L"Der Verkaufsstand wurde geschlossen, da keine Items eingestellt wurden.",
	L"Der Handel wurde abgebrochen.",
	L"Alle Items verkauft. Der Verkaufsstand wird geschlossen.",
	L"Der Handel wurde abgebrochen, da du den Raum verlassen hast.",
	L"Der Verkaufsstand wurde geschlossen.",
	L"Der Client ist abgestürzt.",
	L"Du kannst nicht länger im Kampf-Channel bleiben.",
	L"Du verlässt die Gruppe, wenn du am PvP teilnimmst.",
	L"Die Gruppe wird aufgelöst, da der Dungeon beendet wurde.",
	L"Du hast die Gruppe verlassen, da du am Markt teilnimmst.",
	L"Du hast den Ausbildungsplatz betreten. Du hast die Gruppe verlassen.",
	L"Beendet.",
	L"Wegen Verdacht auf Hacking wurde das Spiel beendet.",
	L"Der Client ist abgestürzt. Das Spiel wird beendet.",
	L"Die EXP des Charakters konnten nicht geändert werden.",
	L"Die Datenbank konnte den Charakter nicht zuordnen.",
	L"Der Autoritäts-Level ist fehlerhaft.",
	L"Dieser Spieler existiert nicht.",
	L"Transaktionsfehler.",
	L"Es ist kein Spieler mit diesem Autoritäts-Level vorhanden.",
	L"Der Operator hat die Verbindung beendet.",
	L"Dieser Befehl kann nur im Gelände ausgeführt werden.",
	L"Dieser Befehl kann in diesem Raum nicht ausgeführt werden.",
	L"Das Item kann nicht gekauft werden.",
	L"Das Item kann nicht verkauft werden.",
	L"Die Quest wird bereits ausgeführt.",
	L"Es wurde versucht, eine Quest zu löschen, die nicht ausgeführt wird.",
	L"Diese Quest existiert nicht.",
	L"Quest wurde bereits erfüllt.",
	L"Dieser Charakter kann die Quest nicht ausführen.",
	L"Die vorherige Quest wurde noch nicht beendet.",
	L"Du hast eine falsche Quest vom NPC erhalten.",
	L"Dieses Quest-Template existiert nicht.",
	L"Quest kann nicht beendet werden, da diese noch nicht alle Voraussetzungen erfüllt.",
	L"Die Datenbank konnte die Daten der Quest nicht bearbeiten.",
	L"Du kannst höchstens 10 Quests gleichzeitig annehmen.",
	L"Dein Level ist zu niedrig, um die Quest anzunehmen.",
	L"Zu wenig Platz im Inventar, um die Quest abzuschließen.",
	L"Es ist ein Fehler bei der Verteilung der Questbelohnung aufgetreten.",
	L"Die gesuchte Belohnung konnte nicht gefunden werden.",
	L"Klassenwechsel-Quest wird bereits ausgeführt.",
	L"Es ist ein Fehler bei der Verarbeitung der Klassenwechsel-Questbelohnung aufgetreten.",
	L"Der Questtyp ist fehlerhaft.",
	L"Die Chatnachricht wurde in einer kürzeren Zeit eingegeben als vorgegeben.",
	L"Du kannst keine Flüsternachricht an dich verschicken.",
	L"Der Chat ist fehlerhaft.",
	L"Dieser User ist momentan nicht eingeloggt.",
	L"--/;/Anführungsstriche/Komma/Leerzeichen können nicht verwendet werden.",
	L"Der Eingabe ist kürzer als die Ladezeit der aktuellen Spielerliste.",
	L"Die Suche nach Userdaten läuft noch.",
	L"Dieser User ist momentan nicht eingeloggt.",
	L"Nickname ist nicht vorhanden.",
	L"Betreten des Dorfplatzes fehlgeschlagen.",
	L"Verlassen des Dorfplatzes fehlgeschlagen.",
	L"Dieser Skill ist bereits auf dem höchsten Level.",
	L"Diese Skill existiert nicht.",
	L"Dein Level ist zu niedrig um diesen Skill zu erlernen.",
	L"Du hast zu wenig Skillpunkte.",
	L"Dir fehlt das benötigte Item.",
	L"Für diesen Erwerb benötigst du die abgeschlossene Quest.",
	L"Vorheriger Skill wurde noch nicht erlernt.",
	L"Diesen Skill hast du bereits erlernt.",
	L"Die zu ändernde Skillslot-ID ist falsch.",
	L"Du kannst nur die Skills eintragen, die du auch erlernt hast.",
	L"Zurücksetzung des Skills ist fehlgeschlagen.",
	L"Die Skill-Leiste B kann nicht verwendet werden.",
	L"Während der Erweiterung der Skill-Leiste B ist ein Fehler aufgetreten.",
	L"Du kannst diesen Skill erst erlernen, wenn die Versiegelung entfernt wurde.",
	L"Dieser Skill liegt in einer Stufe, die du noch nicht erreicht hast.",
	L"Du hast zu wenig Skillpunkte, um diesen Skill zu erlernen.",
	L"Du hast zu wenig Skillpunkte, um diesen Skill zu erlernen.",
	L"Du hast versucht, Informationen von einem Skills zu ändern, der nicht existiert.",
	L"Die Level-Informationen zum Skill sind fehlerhaft.",
	L"Das eingestellte Skill-Level entspricht nicht dem korrekten Level.",
	L"Die Änderungen bezüglich der Gültigkeit bei Shop-Skillpunkte konnten nicht übernommen werden.",
	L"Die Registrierung der Shop-Skillpunkte ist fehlgeschlagen.",
	L"Die Informationen zu den Shop-Skillpunkten wurden nicht aktualisiert.",
	L"Das Zurücksetzen der Informationen zu den Shop-Skillpunkten ist fehlgeschlagen.",
	L"Die Standard-Skills können nicht zurückgesetzt werden.",
	L"Die Gruppe konnte nicht erstellt werden.",
	L"Konnte nicht aus der Gruppe austreten.",
	L"Die Information der Gruppe ist nicht korrekt.",
	L"Dieser User kann nicht eingeladen werden.",
	L"Keine zugehörige Gruppe vorhanden.",
	L"Du bist bereits in der Gruppe angemeldet.",
	L"Im PvP Modus kann keine Gruppe erstellt werden.",
	L"Im PvP-Modus ist es nicht möglich, einer Gruppe beizutreten.",
	L"Die Gruppe kann keine Mitglieder mehr aufnehmen.",
	L"Es ist nicht möglich, der Gruppe beizutreten.",
	L"Die Gruppe wurde gelöscht.",
	L"Der Eintritt in die Gruppe wurde abgelehnt.",
	L"Die Einladung in die Gruppe wurde abgelehnt.",
	L"Dungeon kann hier nicht gestartet werden.",
	L"Ändern des Bereitschaftsstatus fehlgeschlagen.",
	L"Falschen Dungeon gewählt.",
	L"Starten des Spiels ist fehlgeschlagen.",
	L"Spieltyp ist ungültig.",
	L"Du bist nicht der Gruppenleiter.",
	L"Der Gruppenleiter konnte nicht gewechselt werden.",
	L"Die Gruppenmitglieder konnten nicht geändert werden.",
	L"Du kannst den Dungeon nicht in diesem Gebiet starten.",
	L"Die Einstellungen deiner Privatsphäre konnten nicht geändert werden.",
	L"Der Spieler, der zum Gruppenleiter ernannt wird, kann den jetzigen Dungeon nicht ausführen.",
	L"Der Gruppenleiter kann den Bereit-Status nicht ändern.",
	L"Es ist kein Chat-Partner vorhanden.",
	L"Die angeforderte Gruppenliste ist fehlerhaft.",
	L"Die Einstellung bezüglich der Level-Grenze konnte nicht geändert werden.",
	L"Das ist eine private Gruppe.",
	L"Es ist kein Wiederbelebungsstein vorhanden.",
	L"Du wurdest bereits wiedergeboren.",
	L"Wiedergeburt fehlgeschlagen.",
	L"In diesem Dungeon kann der Wiederbelebungsstein nicht verwendet werden.",
	L"Aktualisierung eines nicht vorhandenen Status ist nicht möglich.",
	L"Die Community-Optionen konnten nicht aufgerufen werden.",
	L"Es sind keine weiteren Eintragungen in die Sperrliste möglich.",
	L"Dieser Spieler ist bereits auf der Sperrliste.",
	L"Der Spieler ist bereits aus der Sperrliste gelöscht.",
	L"Spieler existiert nicht.",
	L"Konnte nicht aus der Sperrliste gelöscht werden.",
	L"Du kannst dich nicht selbst in die Sperrliste eintragen.",
	L"Du kannst dich nicht aus der Sperrliste löschen.",
	L"Du kannst nur eingeloggte Spieler in die Sperrliste eintragen.",
	L"Hinzufügen des eigenen Charakters ist nicht möglich.",
	L"Das Zeitlimit zum Hinzufügen von Freunden ist abgelaufen.",
	L"Charakter kann nicht gefunden werden.",
	L"Dein Charakter kann in diesem Status niemanden einladen.",
	L"Der andere Spieler kann im Moment nicht eingeladen werden.",
	L"Der andere Spieler kann im Moment nicht teilnehmen.",
	L"Kann nicht als Freund hinzugefügt werden.",
	L"Verkaufsstand konnte nicht erstellt werden.",
	L"Du kannst den privaten Handel nicht verlassen.",
	L"Suchen nach Spielern mit privatem Handel fehlgeschlagen.",
	L"Das gewählte Item ist fehlerhaft.",
	L"ED-Eintrag ist fehlerhaft.",
	L"Der zu verhandelnde Gegenstand existiert nicht.",
	L"Zu wenig ED!",
	L"Es können nur Items aus dem Inventar gewählt werden.",
	L"Zu wenig Platz im Inventar.",
	L"Items, die an den Charakter gebunden sind, können nicht verkauft werden.",
	L"Handels-Chat kann hier nicht geöffnet werden.",
	L"Du kannst nicht mit dir selbst Handeln.",
	L"Wenn die Haltbarkeit eines Items aufgebraucht ist, kann das Item nicht verkauft werden. Repariere das Item und versuche es noch einmal.",
	L"Item ist bereits eingetragen.",
	L"Es können nur eingetragene Items gelöscht werden.",
	L"Du kannst maximal 10 verschiedene Items wählen.",
	L"Bei diesem Handel überschreitet der andere Spieler sein Budget an ED. Bitte verringer die ED für diesen Handel.",
	L"Anfrage zum privaten Handel angenommen.",
	L"Es ist bereits ein Handel mit einem anderem Spieler geöffnet.",
	L"Die Anfrage zum privaten Handel wurde abgelehnt.",
	L"Es ist kein Handel möglich.",
	L"Handel wegen Server-Fehler nicht möglich.",
	L"Dir fehlt das benötigte Item, um an diesem Dungeon teilzunehmen.",
	L"Du hast noch keine Berechtigung, den Ausbildungsplatz zu betreten.",
	L"Dem Dungeon, der für das Trainingslager bestimmt ist,  fehlt die ID.",
	L"Bei der Speicherung der Belohnung ist ein Fehler aufgetreten.",
	L"Das gewählte Item ist nicht im Inventar vorhanden.",
	L"Es handelt sich beim ausgewählten Item nicht um den Würfel.",
	L"Dieser Charakter kann das Item nicht benutzen.",
	L"Du hast nicht genügend Schlüssel, um den Würfel zu öffnen.",
	L"Der Würfel kann nicht geöffnet werden.",
	L"Das Item konnte nicht erstellt werden.",
	L"Zu wenig Platz im Inventar, um den Würfel zu öffnen.",
	L"Es wurde mehr als eine Anmeldung festgestellt.",
	L"Die UID des Spielers ist fehlerhaft.",
	L"Die Spieler-ID ist fehlerhaft.",
	L"Der UID des Charakters ist fehlerhaft.",
	L"Der Nickname des Charakters ist fehlerhaft.",
	L"Der UID des Spiele-Servers ist fehlerhaft.",
	L"Die Spieler-Information ist fehlerhaft.",
	L"Die Informationen des Spiele-Servers sind fehlerhaft.",
	L"UID-Suche ist fehlgeschlagen.",
	L"Die Messenger Nummer ist fehlerhaft.",
	L"Das Item kann nicht produziert werden.",
	L"Das ist kein Schriftrollen-Item.",
	L"Zu wenig ED zum craften!",
	L"Du besitzt zu wenig Materialien.",
	L"Für das Crafting muss mindestens ein Platz in deinem Inventar frei sein.",
	L"Item konnte nicht erstellt werden.",
	L"HackShield-Zertifikation fehlgeschlagen.",
	L"Aufgrund eines Updates für HackShield muss das Spiel neu gestartet werden.",
	L"HackShield-Verifizierung fehlgeschlagen.",
	L"Der Coupon wurde bereits eingelöst oder die Coupon-Nummer ist nicht korrekt. Es kann nur ein Coupon pro Account benutzt werden.",
	L"Gebe den 30stelligen Code des Coupons ein.",
	L"Dieser Coupon wurde bereits eingelöst.",
	L"Der Coupon ist nicht mehr gültig.",
	L"Die Coupon-Nummer ist ungültig.",
	L"Dieser Coupon kann pro Account nur einmal eingelöst werden.",
	L"Der Coupon konnte nicht eingelöst werden.",
	L"Du hast nicht genügend Tage gewartet, um es wieder zu kaufen.",
	L"Die Itemliste kann nicht aufgerufen werden.",
	L"Die Item-Informationen sind fehlerhaft.",
	L"Du hast zu wenig Platz im Inventar.",
	L"Das erworbene Shop-Item konnte nicht ausgewählt werden.",
	L"Der Restbetrag konnte nicht abgefragt werden.",
	L"Mitglieder-Informationen konnten nicht gefunden werden.",
	L"Dieses Konto wurde geblockt.",
	L"Es ist nicht möglich, Items von anderen Charakteren ins Inventar zu holen.",
	L"Du bist bereits im Besitz dieses Items.",
	L"Das Item wird aufgerufen. Einen Moment bitte.",
	L"Die Durchschnittsgröße des Bildfeldes (Frame) ist fehlerhaft.",
	L"Dieser Spieler existiert nicht.",
	L"Dies ist nicht das Objekt, welches den Nickname wechseln soll.",
	L"Dieser Nickname ist schon vergeben.",
	L"Nickname derzeit nicht benutzbar!",
	L"Der Nickname konnte nicht aktualisiert werden.",
	L"Dieser Nickname ist nicht zulässig.",
	L"Die Länge des Nicknamens ist nicht zulässig.",
	L"Der Nickname konnte nicht geändert werden.",
	L"Der Verkaufsstand konnte nicht erstellt werden.",
	L"Der Verkaufsstand kann nur auf dem Dorfplatz erstellt werden.",
	L"Der Stand kann nicht aufgerufen werden. Keine Informationen zum Besitzer gefunden.",
	L"Der Stand ist momentan ausgelastet. Versuche es später nochmal.",
	L"Öffnen des Verkaufsstandes fehlgeschlagen.",
	L"Die gewählte Menge an Items, die du verkaufen möchtest, stimmt nicht mit den Daten überein.",
	L"Das Item wurde bereits als verkauft eingetragen.",
	L"Du kannst keine Waren auf fremden Verkaufsständen registrieren!",
	L"Es sind mehr Items eingetragen als tatsächlich verkauft werden können.",
	L"Du hast nicht genügend Geld, um einen Verkaufsstand zu eröffnen.",
	L"Erstellen des Verkaufsstandes noch nicht abgeschlossen.",
	L"Du hast den Shop noch nicht verlassen.",
	L"Du hast mehr Items zum Kauf ausgewählt als zum Verkauf angeboten werden.",
	L"Das Item, welches du kaufen willstl, existiert nicht.",
	L"Du hast zu wenig ED, um das Item zu kaufen.",
	L"Du hast zu wenig Platz im Inventar, um etwas zu kaufen.",
	L"Handel nicht möglich, da der Hersteller nicht gefunden werden konnte.",
	L"Während eines Handels kannst du keinen Verkaufsstand eröffnen.",
	L"Der Verkaufsstand ist bereits geöffnet.",
	L"Du hast den Höchstbetrag an ED erreicht.",
	L"Du hast die maximale Menge ED, die du kaufen kannst, erreicht.",
	L"Die Informationen des zu kaufenden Items sind fehlerhaft.",
	L"Das gewählte Item ist nicht im Inventar vorhanden.",
	L"Item kann nicht zerlegt werden.",
	L"Auflösung des Items ist fehlgeschlagen. Versuche es noch einmal.",
	L"Du kannst nur deine Ausrüstung und dein Zubehör zerlegen.",
	L"Kann nicht zerteilt werden.",
	L"Item konnte nicht erstellt werden.",
	L"Zu wenig Platz im Inventar,\num das Item zu zerlegen.",
	L"Items mit einer Nutzungsfrist können nicht geteilt werden.",
	L"Das Item, dass du verbessern willst ist nicht im Inventar vorhanden.",
	L"Item-Daten existieren nicht.",
	L"Es können nur Waffen oder Rüstungsteile für Abwehr verbessert werden.",
	L"Item kann nicht verbessert werden.",
	L"Kann nicht mehr verbessert werden.",
	L"Kein Upgradestein vorhanden!",
	L"Upgrade kann nicht ausgeführt werden.",
	L"Du hast zu wenig ED für ein Upgrade.",
	L"Für ein Upgrade musst du das Item zuerst ablegen oder ausziehen.",
	L"Fluorstein existiert nicht im Inventar.",
	L"Fluorstein kann nicht benutzt werden.",
	L"Ab Upgrade-Level 10 kann der Fluorstein nicht mehr benutzt werden.",
	L"Für Items, die du nicht benutzen kannst, ist es nicht möglich, ein Upgrade durchzuführen.",
	L"Upgrade ist fehlgeschlagen.",
	L"Das zu reparierende Item befindet sich nicht in deinem Inventar.",
	L"Item-Daten existieren nicht.",
	L"Item kann nicht repariert werden.",
	L"Reparatur nur für Items möglich, die du nicht benutzen kannst.",
	L"Nicht genügend Erneuerungssteine vorhanden.",
	L"Angelegte Items können nicht repariert werden.",
	L"Items, deren Besonderheit deaktiviert ist, können nicht verwendet werden.",
	L"Upgrade erfolgreich abgeschlossen.",
	L"Keine Veränderung.",
	L"Um eine Stufe verringert.",
	L"Zurücksetzen der Upgradestufe.",
	L"Item kann nicht verwendet werden.",
	L"Item ist nicht im Inventar vorhanden.",
	L"Item-Daten existieren nicht.",
	L"Gebühr ist zu hoch.",
	L"Sockel existieren nur bei Waffen oder Rüstungsteilen.",
	L"In deiner Ausrüstung existiert keine Information über den Zauberstein.",
	L"Kein Zauberstein im Inventar vorhanden.",
	L"Sockel kann nicht verwendet werden.",
	L"Der Zauberstein ist bereits im Sockel befestigt.",
	L"Der Zauberstein ist bereits aus dem Sockel entfernt worden.",
	L"Sockel-Option existiert nicht.",
	L"Nickname existiert nicht.",
	L"Du kannst dich nicht selbst vorschlagen.",
	L"Es existiert niemand, der die Belohnung entgegen nehmen kann.",
	L"Die private Datei, die gelöscht werden soll, ist nicht in der Datenbank vorhanden.",
	L"Schülerliste konnte nicht aufgerufen werden.",
	L"Informationen können nicht angezeigt werden. Level ist zu niedrig.",
	L"Dein Level ist nicht hoch genug, um Schüler aufzunehmen.",
	L"Es können maximal 3 Schüler eingetragen werden.",
	L"Er hat schon einen Lehrmeister.",
	L"Ist bereits als Schüler eingetragen.",
	L"Die zu kaufende Ware ist fehlerhaft.",
	L"Die Ware kann nicht erworben werden.",
	L"Zahlung ist bereits erfolgt.",
	L"Maximale Anzahl von Waren überschritten.",
	L"Du hast die maximale Warenmenge, die gekauft werden soll, überschritten.",
	L"Diese Ware kann noch nicht wieder gekauft werden.",
	L"Kein Warenkorb vorhanden.",
	L"Verwendung des Spiels ist begrenzt.",
	L"Warenmenge ist begrenzt. Ware kann nicht erworben werden.",
	L"Anzahl der Bestellungen ist begrenzt.",
	L"Die Ware kann im Moment nicht nochmals erworben werden.",
	L"Die Ware kann nicht verschenkt werden.",
	L"Anzahl der Bestellung ist begrenzt.",
	L"Der andere Spieler kann die Ware im Moment nicht entgegennehmen.",
	L"Das ist ein geblockter Spieler.",
	L"Keine Spieler-Informationen gefunden.",
	L"Nicht genügend Guthaben.",
	L"System wird geprüft.",
	L"Maximale Anzahl Wiederbelebungssteine erreicht.",
	L"Es können keine weiteren Inventar-Slots erstellt werden.",
	L"Du kannst dir nicht selbst etwas schenken.",
	L"Die Login-Daten sind falsch.",
	L"Nickname existiert nicht.",
	L"Probe-ID-Spielern kann man nichts schenken.",
	L"Anzahl der verschenkten Waren wurde überschritten.",
	L"Gebe das Passwort ein.",
	L"Konto-Verifizierung ist fehlgeschlagen.",
	L"Ware kann nicht verschenkt werden.",
	L"Spieler unter 14 Jahren können diese Funktion nicht benutzen.",
	L"Item kann nicht erworben werden.\nMaximal 9 Charakter-Slots erlaubt.",
	L"Charakter-Slot konnte nicht erweitert werden.",
	L"Die Funktion ist bereits in Gebrauch.",
	L"Skill existiert nicht.",
	L"Das Item für das Zurücksetzen eines Skills existiert nicht.",
	L"Das Item für Zurücksetzung eines Skills konnte nicht aus der Datenbank gelöscht werden.",
	L"Beim Zurücksetzen des Skills ist ein Datenbankfehler aufgetreten.",
	L"Skill kann nicht zurückgesetzt werden.",
	L"Ein Skill kann nicht zurückgesetzt werden, solange sich dieser im Quickslot befindet.",
	L"Dieses Item kann nicht vorgemerkt werden.",
	L"Du kannst keine weiteren Produkte in den Warenkorb legen.",
	L"Diese Funktion kannst du als Tester nicht benutzen.",
	L"Spieler mit Probe-IDs können das Spiel nicht weiterempfehlen.",
	L"Du hast das Maximallevel für Probe-ID-Spieler erreicht. Wenn du das Spiel fortsetzen möchtest, logge dich mit einer vollwertigen ID ein.",
	L"Probe-ID-Spieler können nicht der Freundesliste hinzugefügt werden.",
	L"Dieser User ist nicht in der Hacking-Liste eingetragen.",
	L"Die Datenbank hat die Zustimmungsdaten zum Hacking noch nicht aktualisiert.",
	L"Du hast die Meldung von Hacking-Spielern noch nicht bestätigt.",
	L"Item existiert nicht im Inventar.",
	L"Diese Eigenschaften können nicht verbessert werden.",
	L"Die Eigenschaften des Slots sind bereits verbessert worden.",
	L"Dieser Slot wurde bereits geleert.",
	L"Zu wenig ED für Attributverzauberung!",
	L"Nicht genügend Eldritstücke für eine Verzauberung.",
	L"Item-Informationen fehlerhaft.",
	L"Attributverzauberung ist nur bei Waffen und Rüstungen möglich.",
	L"Das gewählte Item kann nicht zerlegt werden.",
	L"Zu wenig Analyse-Geräte vorhanden!",
	L"Nicht genug Platz im Inventar,\num das Item zu zerlegen.",
	L"Gewähltes Item kann nicht zerlegt werden.",
	L"Herstellung des Items ist fehlgeschlagen.",
	L"Posteingang kann nicht aufgerufen werden.",
	L"Das gewählte Item kann nicht an die Mail angehängt werden.",
	L"Die eingegebene Menge an ED kann nicht per Mail verschickt werden.",
	L"Die Mail konnte nicht gesendet werden.",
	L"Die Mail existiert nicht.",
	L"Zu wenig Platz im Inventar, um den beigefügten Gegenstand zu verschieben. Schaffe Platz im Inventar und versuche es erneut.",
	L"Der beigefügte Gegenstand konnte nicht geholt werden.",
	L"Du hast versucht ein Item hinzuzufügen, das nicht existiert.",
	L"Nur vollständig reparierte Items können hinzugefügt werden.",
	L"Nickname existiert nicht.",
	L"Du kannst keine Nachrichten an dich selbst schicken!",
	L"Nicht genügend ED, um die Nachricht zu verschicken.",
	L"Der andere Spieler hat nicht genügend Speicherplatz in seinem Posteingang und kann keine Nachrichten mehr empfangen.",
	L"Du hast eine gelöschte Nachricht gewählt.",
	L"Der Spieler hat deine Nachricht abgelehnt.",
	L"Items, die an deinen Charakter gebunden sind, kannst du nicht in Nachrichten versenden.",
	L"An Probe-ID-Spieler kann keine Nachricht verschickt werden.",
	L"Nickname existiert nicht.",
	L"Dieser Nickname ist bereits in der Sperrliste eingetragen.",
	L"Eintragung in die Sperrliste ist fehlgeschlagen.",
	L"Nickname wurde bereits gelöscht.",
	L"Spieler konnte nicht aus der Sperrliste gelöscht werden.",
	L"Du besitzt diesen Titel nicht.",
	L"Du trägst diesen Titel bereits.",
	L"Die Gültigkeit dieses Titels ist abgelaufen.",
	L"Dieser Titel existiert nicht.",
	L"Der Titel wurde nicht erlangt.",
	L"Du bist bereits im Besitz dieses Titels.",
	L"Das Item kann nicht verwendet werden.",
	L"Das Item existiert nicht.",
	L"Dein Level ist zu niedrig für dieses Item.",
	L"Das Item kann im Inventar nicht verwendet werden.",
	L"Das Item existiert nicht im Inventar.",
	L"Item ist nicht erlaubt.",
	L"Das Item ist nicht zugelassen.",
	L"Das Upgrade ist fehlgeschlagen.",
	L"Item kann nicht getauscht werden.",
	L"Das Item existiert nicht im Inventar.",
	L"Dieses Item kannst du nicht handeln.",
	L"Die Items zum Tausch sind nicht erstellt worden.",
	L"Du verlässt den Ort, um in einen anderen Bereich zu gelangen.",
	L"Du verlässt die Ebene, um in den Raum zu gelangen.",
	L"Das System hat deinen Rücktritt bearbeitet.",
	L"Du kannst nicht in das Dorf gehen.",
	L"Du konntest das Dorf nicht verlassen.",
	L"Die Spielerliste kann nicht aufgerufen werden.",
	L"Dein Level ist zu niedrig, um in das Dorf zu gehen.",
	L"Du hast den Dungeon, der dir Eintritt ins Dorf gewährt, noch nicht abgeschlossen.",
	L"Dieser Channel existiert nicht.",
	L"Channel-Wechsel war erfolgreich. Die Verbindung wird beendet.",
	L"Die Registrierung zum Wechsel des Channels ist fehlgeschlagen.",
	L"Du bist nicht für einen Channel-Wechsel registriert.",
	L"Du befindest dich schon in dem Channel, zu dem du wechseln willst.",
	L"Maximale Anzahl der Mitglieder erreicht. Kein Wechsel möglich.",
	L"Channel-Wechsel funktioniert nur im Dorf oder in der Umgebung eines Dorfes.",
	L"Versuche den Channel-Wechsel später noch einmal.",
	L"Bei diesem Spieler kannst du diese Funktion nicht benutzen.",
	L"Es wurde kein Charakter gewählt.",
	L"Dieser Freund ist nicht eingeloggt.",
	L"Falscher Status.",
	L"Die Datenbank hat das Drop-Item des Events nicht geupdatet.",
	L"Du hast die Event-Belohnung bereits erhalten.",
	L"Dieser Spieler ist bereits dein Freund.",
	L"Charakterstatus des Freundes ist ungültig.",
	L"Dieser Spieler hat dich nicht als Freund hinzugefügt.",
	L"Dieser Spieler ist nicht mit dir befreundet.",
	L"Diese Gruppe existiert nicht.",
	L"Die Nachricht ist zu lang.",
	L"Das ist die gleiche Gruppe, zu der du wechseln willst.",
	L"Es können keine weiteren Gruppen erstellt werden.",
	L"Diese Gruppe gibt es bereits.",
	L"Dieser Gruppenname ist schon vergeben.",
	L"Dein Schüler hat sich 7 Tage nicht eingeloggt. Die Ausbildung wird abgebrochen.",
	L"Der Schüler ist ein Level aufgestiegen. Die Ausbildung ist damit beendet.",
	L"Der Charakter wurde gelöscht. Die Ausbildung wird beendet.",
	L"Die Ausbildung wurde abgebrochen.",
	L"Du konntest die Ausbildung nicht beenden.",
	L"Fehler in der Datenbank bezüglich der Freunde-Funktionen.",
	L"Der Gruppenname ist zu lang.",
	L"Deine Freundesliste ist voll. Die Einladung konnte nicht verschickt werden.",
	L"Freundschaftsanfragen zwischen Charakteren innerhalb eines Accounts sind nicht möglich.",
	L"Die Freundesliste des anderen Spielers ist voll. Freundschaftsanfrage kann nicht verschickt werden.",
	L"Deine Freundschaftsanfrage wurde abgelehnt.",
	L"Suchanfrage fehlgeschlagen.",
	L"Der PvP-Channel kann nicht betreten werden.",
	L"Beim PvP startet ein Spiel nur, wenn alle Plätze voll belegt sind.",
	L"Der Betreff ist zu lang.",
	L"Die Nachricht ist zu lang.",
	L"Der eingeladene Spieler kann den Dungeon nicht betreten.",
	L"Die Versiegelung ist bereits entfernt worden.",
	L"Die Versiegelung des Skills konnte nicht entfernt werden.",
	L"Du hast die falsche Klasse für diesen Gegenstand!",
	L"Diesen Skill hast du schon freigeschaltet!",
	L"Im Inventar befindet sich bereits ein Item mit den selben Funktionen. Die Ware konnte nicht gekauft werden.",
	L"Spieler mit Probe-ID können nicht in Henirs Raumzeit eingeladen werden.",
	L"Die Art der Zertifizierung ist nicht gültig.",
	L"Items in der Bank können nicht zerlegt werden.",
	L"Items, die bei der Bank aufbewahrt werden, kannst du keinen Sockel hinzufügen.",
	L"Diese Funktion kann nicht bei der Bank verwendet werden.",
	L"Die Anzahl der Bank-Slots kann nicht mehr erweitert werden.",
	L"Es ist nicht möglich, mehr als eine Mitgliedskarte für die Bank zu kaufen.",
	L"Die Mitgliedskarte der Bank kann nicht gekauft werden.",
	L"Wenn du im Inventar einen Zusicherungsschein von Luriel besitzt, kannst du eine Platinum Mitgliedskarte kaufen. Benutze nun den Zusicherungsschein von Luriel.",
	L"Das Passwort existiert nicht.",
	L"Das Passwort kann nicht erneuert werden.",
	L"Der Benutzername oder das Passwort ist nicht korrekt.",
	L"Während der Authentifizierungsphase ist ein Systemfehler aufgetreten.",
	L"Das Item existiert nicht.",
	L"Item Information ist nicht erhältlich.",
	L"Diese Art von Items kann nicht versiegelt werden.",
	L"Angelegte Items können nicht versiegelt werden.",
	L"Das Item ist bereits versiegelt.",
	L"Ein nicht repariertes Item kann nicht versiegelt werden.",
	L"Items mit einer Benutzungsfrist können nicht versiegelt werden.",
	L"Zerstörte Items können nicht versiegelt werden.",
	L"Items, mit denen du handeln kannst, können nicht versiegelt werden.",
	L"Keine weiteren Versiegelungen mehr möglich.",
	L"Die Information der gewählten Versiegelungsschriftrolle ist fehlerhaft.",
	L"Versiegelung fehlgeschlagen.",
	L"Nicht genügend Versiegelungsschriftrollen!",
	L"Bei angelegten Items kann die Versiegelung nicht entfernt werden.",
	L"Bei diesem Item wurde die Versiegelung bereits entfernt.",
	L"Entfernen der Versiegelung fehlgeschlagen.",
	L"Datenbank-Update der Informationen zur Versiegelung fehlgeschlagen.",
	L"Versiegelte Items können nicht verbessert werden.",
	L"Systemfehler bei Abfrage der El-Coins.",
	L"Dieser Account hat einen begrenzten Aktivitätsradius.",
	L"Dieser Account existiert nicht.",
	L"Der Account ist falsch.",
	L"Die Coupon-Nummer ist ungültig.",
	L"Dieser Coupon wurde bereits eingelöst.",
	L"Diese Art von Coupon kann nur einmal verwendet werden.",
	L"Der Coupon ist abgelaufen.",
	L"Während der Coupon eingelöst wurde, ist ein Systemfehler aufgetreten.",
	L"Nicht genügend El-Coins.",
	L"Während dem Einkauf ist ein Systemfehler aufgetreten.",
	L"Der Kauf ist erst ab Level 15 möglich.",
	L"Es existiert schon eine Gilde, in der du angemeldet bist.",
	L"Dieser Gildenname ist bereits vergeben.",
	L"Das Item zur Gildengründung befindet sich nicht im Inventar.",
	L"Das Item für die Gildengründung ist fehlerhaft.",
	L"Gildengründung fehlgeschlagen.",
	L"Registrierung als Gildenmeister ist fehlgschlagen.",
	L"Information der Gilde konnte nicht gefunden werden.",
	L"Einladung zur Gilde nicht möglich.",
	L"Dieser Spieler ist offline.",
	L"Probe-ID Spieler können nicht in eine Gilde eingeladen werden.",
	L"Dieser Spieler wurde bereits in die Gilde eingeladen.",
	L"Eine andere Gilde hat diesen Spieler bereits eingeladen.",
	L"Du hast nicht die Rechte, jemanden in die Gilde einzuladen.",
	L"Du kannst die Anzahl der Gildenmitglieder nicht erhöhen. Dafür benötigst du ein Item, welches dir mehr Plätze für Mitglieder schafft.",
	L"Der eingeladene Spieler ist bereits ein Gildenmitglied.",
	L"Dieser Spieler ist bereits in einer Gilde.",
	L"Du kannst die Gildenliste nicht einsehen.",
	L"Das Item, welches mit dem Coupon gekauft werden soll, ist fehlerhaft.",
	L"Der Spieler hat die Gildeneinladung abgelehnt.",
	L"Anmeldung in die Gilde fehlgeschlagen.",
	L"Gehört keiner Gilde an.",
	L"Du hast keine Berechtigung, den Rang des Gildenmitglieds zu ändern.",
	L"Der Rang des Gildenmitglieds konnte nicht geändert werden.",
	L"Änderungen der Gildennachricht können nur vom Gildenmeister und Gildenverwalter geändert werden.",
	L"Änderung der Gildennachricht fehlgeschlagen.",
	L"Du bist nicht befugt ein Gildenmitglied zu kicken.",
	L"Der Gildenmeister kann die Gilde nicht verlassen.",
	L"Verlassen der Gilde fehlgeschlagen.",
	L"Bei der Gildenbegrüßung ist die Länge begrenzt.",
	L"Du bist nicht befugt, die Gildenbegrüßung zu ändern.",
	L"Änderung der Gildenbegrüßung ist fehlgeschlagen.",
	L"Nur der Gildenmeister ist dazu befugt, die Gilde aufzulösen.",
	L"Die Gilde kann nicht aufgelöst werden. Es sind noch Gildenmitglieder angemeldet.",
	L"Auflösung der Gilde fehlgeschlagen.",
	L"Der Klassenrang wurde bereits geändert.",
	L"Es existieren bereits Gildenverwalter.\nÄndere den Rang des Gildenverwalters,\num einen neuen Verwalter zu ernennen.",
	L"Der Gildenmeister kann seinen Charakter nicht löschen. Gib den Titel des Gildenmeisters an ein anderes Gildenmitglied weiter!",
	L"Du kannst deinen eigenen Klassenrang nicht ändern.",
	L"Du kannst keine Gildengründungserlaubnis kaufen, da du bereits einer Gilde angehörst.",
	L"Du besitzt bereits eine Gildengründungserlaubnis.",
	L"Erhöhung der Mitgliederanzahl fehlgeschlagen.",
	L"Die Erweiterungskarte kann nur vom Gildenmeister oder Gildenverwalter verwendet werden.",
	L"Es können keine weiteren Mitglieder in die Gilde aufgenommen werden.",
	L"Während des Handels kann diese Funktion nicht genutzt werden.",
	L"Du kannst nicht in dieses Gebiet wechseln.",
	L"Dieser Gildenname ist 7 Tage lang nicht verfügbar.",
	L"Das ist die maximale Anzahl an Erfahrungspunkten.",
	L"Um das Item kaufen zu können, muss die dazugehörige Quest erledigt werden.",
	L"Gildenname ist zu lang.",
	L"Du besitzt nicht genug ED, um das Attribut zu entfernen.",
	L"Dieses Item kannst du erst ab Level 35 kaufen.",
	L"Upgrade dich mit dem Beanfun-Account und beende das Spiel. Die Beanfun-Seite ist: tw.beanfun.gamania.com xxx",
	L"Dieser Account wurde bereits zu einem Beanfun-Account upgegradet. Logge dich mit dem Beanfun-Programm ein. xxx",
	L"Es können keine weiteren Items gekauft werden. Dein temporäres Inventar ist voll.",
	L"GSP können nur vom Gildenmeister verwendet werden.",
	L"Dieser Gilden-Skill wurde bereits bis zum höchsten Level trainiert.",
	L"Informationen zum Gilden-Skill existieren nicht.",
	L"Vorheriger Gilden-Skill wurde noch nicht bis zum höchsten Level trainiert.",
	L"Nicht genügend Skillpoints eingesetzt.",
	L"Nicht genügend GSP.",
	L"Erlernen des Gilden-Skills ist fehlgeschlagen.",
	L"Nur der Gildenmeister kann die Gilden-Skills zurücksetzen.",
	L"Du benötigst das Item \"Hornflöte des Vergessens\"!",
	L"Gilden-Skill kann nicht zurückgesetzt werden.",
	L"Rückgabe des Gilden-Skills ist fehlgeschlagen.",
	L"Nur der Gildenmeister kann die Gilden-Skills zurücksetzen.",
	L"Die \"Hornflöte des Vergessens\" ist nicht im Inventar vorhanden.",
	L"Zurücksetzen des Gilden-Skills ist nicht möglich.",
	L"Zurücksetzen des Gilden-Skills ist fehlgeschlagen.",
	L"Verwendung nur durch den Gildenmeister möglich.",
	L"Keine befristeten Gilden-Skillpoints erhalten.",
	L"Das gesegnete Item der Erkenntnis wird bereits verwendet.",
	L"Es ist noch nicht möglich, die Event-Belohnung zu erhalten.",
	L"Zu wenig Platz im Inventar, um die Event-Belohnung entgegenzunehmen.",
	L"Fehler beim Erhalten der Event-Belohnung.",
	L"Das ist nicht der Item-Modus.",
	L"Es ist noch ein Drop-Item übrig.",
	L"Drop-Item des PvP konnte nicht geholt werden.",
	L"Nach Verwendung der Charakterkarte, kannst du die Klasse erstellen.",
	L"Dieser Account kann nicht am Event teilnehmen.",
	L"Diese Funktion kann nur der Gildenmeister oder der Gildenverwalter benutzen.",
	L"Items für Internetcafés können diese Funktion nicht benutzen.",
	L"Die Gildenwerbung existiert nicht.",
	L"Der Text ist zu lang.",
	L"Registrierungszeitraum der Werbung ist ungültig.",
	L"Nicht genug ED, um die Werbung zu registrieren.",
	L"Es wurde schon eine Werbung registriert.",
	L"Die Registrierung der Gildenwerbung hat nicht funktioniert.",
	L"Aufgrund zu vieler Anträge kann derzeit keine Anmeldung erfolgen.",
	L"Anmeldung der Gilde ist fehlgeschlagen.",
	L"Du hast schon eine Registrierung beantragt.",
	L"Die Information zum Registrierungsantrag existiert nicht.",
	L"Das Annehmen der Gildenregistrierung hat nicht funktioniert.",
	L"Das Löschen des Antrags der Gildenregistrierung hat nicht funktioniert.",
	L"Bei einer Werbung mit befristetem Zeitraum kann man keine Registrierung beantragen.",
	L"Du hast keine Rechte, die Liste der Anträge zur Gildenregistrierung anzusehen.",
	L"Du hast das Schloss nicht geöffnet.",
	L"Dieser Game-Account wurde gestoppt.",
	L"Quests für den PC-Room können nur im Internetcafé angenommen werden.",
	L"Quests für den PC-Room können nur im Internetcafé beendet werden.",
	L"Wegen Verdacht auf Hacking wurdest du aus dem Raum befördert.",
	L"Da die Option \"Gildeneinladung verweigern\" aktiviert ist, kannst du keine Registrierung beantragen.",
	L"Da es zu viele Anträge zur Gildenregistrierung gibt, kannst du keine Registrierung mehr beantragen.",
	L"Das ist nicht die aktuell ausgeführte Quest.",
	L"Das Einkaufslimit des betreffenden Items wurde erreicht.",
	L"El-Coins sind deaktiviert. Ändere deine Einstellungen auf der Website unter \"Meine Informationen\", im Menü \"Cash-Sicherheit\".",
	L"Aktueller Statuscheck wurde bereits durchgeführt.",
	L"Die DB-Abfrage der WebPoint-Erhöhung hat nicht funktioniert.",
	L"Statuscheck hat nicht funktioniert.",
	L"Aufgrund doppelter Gruppenanmeldung hast du die Gruppe verlassen.",
	L"Gruppenstatus lädt.",
	L"Item Liste löschen",
	L"Item Liste hinzufügen",
	L"Item Liste bearbeiten",
	L"Die Auswahl der Kategorie ist falsch.",
	L"Die Suche ergab keinen Treffer.",
	L"Die Willenskraft des Eingeladenen ist nicht ausreichend.",
	L"Bitte starte die Suche nach kurzer Zeit erneut.",
	L"In diesem Laden wurde der Verkauf beendet.",
	L"Der Spieler ist nicht im Kaufstatus.",
	L"Das Erstellen eines Raums hat nicht funktioniert.",
	L"Das Item existiert nicht.",
	L"Diese Seite existiert nicht.",
	L"Diese Notiz wurde bereits registriert.",
	L"Die Notiz konnte nicht registriert werden.",
	L"Du besitzt kein Notizbuch der Technik.",
	L"Einfügen der Notiz der Technik ist fehlgeschlagen.",
	L"Du besitzt diese Notiz der Technik bereits.",
	L"Du musst Level 20 erreichen, bevor du dieses Item kaufen kannst.",
	L"Mit Spielern auf anderen Servern kann man nicht handeln.",
	L"Verkaufsstände von anderen Servern kann man nicht nutzen.",
	L"Spieler von anderen Servern kannst du nicht in die Gilde einladen.",
	L"Spieler von anderen Servern können nicht als Lehrling registriert werden.",
	L"Spieler von andern Servern kannst du nicht als Freund hinzufügen.",
	L"Der Challenge-Modus von Henirs Raumzeit kann nicht mit Charakteren von anderen Servern zusammen gespielt werden.",
	L"Zugangssperre für Nutzer wegen des Verdachts auf Hacking.",
	L"[Hongkong] Mit dieser Klasse kannst du keinen Klassenwechsel durchführen.",
	L"Die Anzahl der Items, die du wegwerfen möchtest, ist fehlerhaft.",
	L"Erstellung des Pets war nicht erfolgreich.",
	L"Dieser Name wird bereits verwendet.",
	L"Der Name ist auf 12 Zeichen begrenzt.",
	L"Das Pet wird erstellt.",
	L"Pet konnte nicht herbeigerufen werden.",
	L"Das Pet kann hier nicht erstellt werden.",
	L"Du hast bereits ein Pet herbeigerufen.",
	L"Dieses Pet wurde schon herbeigerufen.",
	L"Das Pet konnte nicht fortgeschickt werden.",
	L"Befehl konnte nicht ausgeführt werden.",
	L"Dein Pet ist satt. Es kann nichts mehr fressen.",
	L"Pet konnte nicht gefüttert werden.",
	L"Das Pet ist im Wachstum. Es frisst nur noch Früchte und Samen von Els Baum.",
	L"Das wurde schon gespeichert.",
	L"Die nächste Entwicklungsstufe ist noch nicht verfügbar.",
	L"Weiterentwicklung ist nur möglich, wenn die Vertrautheit 100% beträgt.",
	L"Das Pet kann diesen Gegenstand nicht verwenden.",
	L"Das Level des Futters ist zu niedrig.",
	L"Die Login-Daten sind falsch.",
	L"Die Login-Daten sind falsch.",
	L"Der Account ist noch nicht validiert.",
	L"Das Pet kann dieses Futter nicht essen.",
	L"Der User ist beschäftigt.",
	L"매트릭스 카드가 바인딩되어 있습니다.",
	L"토큰 패스워드 에러",
	L"키 에러",
	L"계정 정보가 수정 과정에 있습니다. 의문 사항이 있으시면 서비스 센터로 연락 바랍니다.",
	L"자이언트 패스워드 보안이 바인딩 해제 상태에 있습니다. 의문사항이 있으시면 서비스 센터로 연락 바랍니다.",
	L"GM키에란",
	L"GM리엘",
	L"[Unbekannter Absender]",
	L"지금은 청약철회 기능을 이용 하실 수 없습니다.",
	L"환불 가능 개수보다 요청 갯수가 커서 청약철회를 실패하였습니다.",
	L"구매한지 7일이 초과된 상품으로 청약철회가 불가능 합니다.",
	L"패키지 중 일부 상품을 수령하여 환불이 불가능 합니다.",
	L"상품 가격이 0원으로 환불이 불가능한 상품 입니다.",
	L"중복된 RequestID입니다.",
	L"Keine Kaufinformation zu dieser Ware vorhanden.",
	L"Keine Information zu dieser Ware vorhanden.",
	L"환불이 불가능한 상품 입니다.",
	L"선물 받은 상품이어서 환불이 불가능 합니다.",
	L"Zeitbeschränkte Items können nicht weggeworfen werden.",
	L"Waren, die nicht verkauft werden können, können auch nicht weggeworfen werden.",
	L"Du hast das Kauf-Limit überschritten!",
	L"Dein Level ist zu niedrig für dieses Item.",
	L"Ab Upgrade-Level 11 können keine Fluorsteine mehr benutzen werden.",
	L"Du kannst diese Quest nicht annehmen, da du die Belohnung bereits erhalten hast.",
	L"Du kannst die Quest nicht annehmen, da in deinem Inventar nicht genügend Platz für die Belohnung ist.",
	L"Das Benutzen des Zaubersteins ist fehlgeschlagen.",
	L"Diese Funktion ist momentan nicht verfügbar.\nWir bitten um Entschuldigung.",
	L"Der Zugang für diese IP ist beschränkt.",
	L"Die Chatfunktion wurde eingeschränkt.",
	L"Die Handelsfunktion wurde beschränkt.",
	L"Das Spiel kann nicht gestartet werden, da das Item nicht existiert.",
	L"Das Spiel wird von einem anderen Programm gestört.",
	L"충전이 정상적으로 이루어지지 않았습니다. 다시 시도하여 주시기 바랍니다.",
	L"충전이 불가능한 금액입니다. 충전 금액을 재입력해 주시기 바랍니다.",
	L"존재하지 않는 아이템 카드입니다.",
	L"해당 카드는 해당 구역에서 사용이 불가능합니다.",
	L"이미 사용한 아이템 카드입니다.",
	L"잘못된 전용 카드 ID입니다.",
	L"잘못된 전용 카드 패스워드입니다.",
	L"DB 에러",
	L"Du kannst keine Nachricht verschicken, da deine Aktionen eingeschränkt wurden.",
	L"Du kannst keinen Verkaufsstand eröffnen, da der Handel eingeschränkt wurde.",
	L"Du kannst deinen Verkaufsstand nicht aufrufen, da der Handel eingeschränkt wurde.",
	L"Du kannst nicht nach Waren suchen, da der Handel eingeschränkt wurde.",
	L"Du kannst den Markt nicht betreten, da der Handel eingeschränkt wurde.",
	L"캐시 인벤토리에 아이템이 존재합니다.(HK 이벤트에 사용)",
	L"Mehr als zwei Gruppenmitglieder erforderlich.",
	L"Der Dungeon ist gesperrt und kann deshalb nicht betreten werden.",
	L"Du kannst den Weltmissions-Dungeon nicht mit anderen Spielern dieses Servers betreten.",
	L"Der Log für die Postüberwachung kostet genauso viel.",
	L"Der Log für die Verkaufsüberwachung kostet genauso viel.",
	L"Log zur Postüberwachung fehlgeschlagen.",
	L"Log zur Verkaufsüberwachung fehlgeschlagen.",
	L"Du kannst die Agentin nicht deaktivieren, da noch Waren verkauft werden.",
	L"Agentin ist nicht aktiviert.",
	L"Du kannst den Kaufvorgang nicht abbrechen.",
	L"Dies ist ein privater Verkauf: Der Kauf von Items ist nicht möglich.",
	L"Du kannst keinen Verkaufsstand eröffnen, da die Agentin noch aktiv ist.",
	L"Da du gegen die Regeln verstoßen hast, wird dein Verkaufsstand geschlossen.",
	L"Du kannst die Agentin nicht deaktivieren.",
	L"Unregisted User.",
	L"It is already canceled.",
	L"Invalid coupon number.",
	L"This coupon can not be canceled.",
	L"The used user information and cancel the requested user information does not match.",
	L"The issued cash by coupons  already had used . so can not be canceled.",
	L"requested price should be equal to billing items price.",
	L"The balance short.",
	L"Billing account that is unavailable.",
	L"You can not register any more today.",
	L"This coupon can not verify the information.",
	L"Coupon is already used.",
	L"Coupon use is stopped.",
	L"Coupon is expired.",
	L"Coupon is not available in the game.",
	L"Issued to certain customers who can use coupons, you do not have permission.",
	L"Buying is a restricted user.",
	L"Your use is limited to the payment service.",
	L"Your use is limited to the purchase service.",
	L"User cannot be verified.",
	L"Registration has exceeded the number of coupons available.",
	L"Unable to login due to IP restriction.",
	L"The coupon code has already been redeemed.",
	L"You cannot purchase the item at the moment. Your account have reached the daily limit for purchasing the item.",
	L"Du hast dein Passwort 2mal falsch eingegeben und kannst dich daher nicht mehr einloggen.",
	L"Wenn du Waren über die Agentin verkaufen willst, musst du einen Vertrag abschließen.",
	L"Die eingegebenen PINs sind nicht identisch.",
	L"Du hast 10mal eine falsche PIN eingegeben.\nWenn du den Button \"Bestätigen\" klickst, wird die Verbindung abgebrochen.\nDu musst dich auf der Website anmelden, um die Eingabe zurückzusetzen.",
	L"Das Anlegen einer PIN ist fehlgeschlagen.",
	L"PIN ist nicht korrekt.",
	L"Der Name des Items ist zu lang.",
	L"Der Verkaufsstand der Agentin wurde beendet.\nNach Erhalt deiner Waren kannst du einen neuen Verkaufsstand eröffnen.",
	L"Die Agentin verkauft diese Waren zur Zeit.\nWenn du das Geld der verkauften Waren erhalten möchtest,\nmusst du den Verkaufsstand der Agentin beenden.",
	L"DB-Query für Vertrag der Agentin fehlgeschlagen.",
	L"Agentin konnte nicht aktiviert werden.",
	L"Die Waren konnten nicht im Verkaufsstand der Agentin eingestellt werden.",
	L"Nur der Auftraggeber der Agentin kann dies nutzen.",
	L"Items konnten nicht an die Agentin übergeben werden.",
	L"Du kannst kein Item aufnehmen, das gerade verkauft wird.",
	L"Du hast diesen Gegenstand bereits erhalten.",
	L"Du hast das Maximum an ED erreicht und kannst keine weiteren mehr aufnehmen.",
	L"Du hast keinen Platz mehr in deinem Inventar.",
	L"Du hast keine Items.",
	L"Du kannst dieselben Waren nicht gleichzeitig kaufen.",
	L"Dein Level ist zu niedrig.\nDu kannst keine Gruppenanfragen erstellen.",
	L"Du kannst keine Waren kaufen, da die Agentin noch aktiv ist.",
	L"Es gibt noch Items, die du annehmen musst, bevor du weitere Items verkaufen kannst.",
	L"Alle Waren wurden verkauft, daher schließt die Agentin den Verkaufsstand.",
	L"Du hast diese Quest bereits akzeptiert und die Belohnung erhalten. Du kannst sie nicht erneut akzeptieren.",
	L"Da du keinen Platz mehr in deinem Inventar hast, kannst du die Quest nicht akzeptieren.",
	L"Der Minimumlevel der Gruppe konnte nicht geändert werden.",
	L"Du kannst keinen Verkaufsstand eröffnen, da der Agent alle Waren verkauft hat.",
	L"(TW/HK)강화 보조 아이템 사용 불가",
	L"(TW/HK)강화 보조 아이템이 없습니다.",
	L"(TW/HK)파괴 방지 아이템 사용 불가",
	L"(TW/HK)파괴 방지 아이템이 없습니다.",
	L"Dein Level ist zu niedrig.\nWähle einen anderen Dungeon oder entferne die Level-Beschränkung.",
	L"Dein Level ist zu niedrig.\nDu kannst keine Level-Einschränkung erstellen.",
	L"Das Level des eingeladenen Spielers ist zu niedrig.",
	L"Dein Level ist zu niedrig.\nWähle einen Dungeon, der deinem Level entspricht.",
	L"Keine Ziffer in der PIN darf sich direkt wiederholen.\n(0000, 1111, 999999, etc.)",
	L"Bitte verwende keine fortlaufenden Ziffern in der PIN.\n(1234, 9876, 123456, etc.)",
	L"Das Löschen des zweiten PIN-Pads ist fehlgeschlagen.",
	L"Das 2. PIN-Pad wird nicht verwendet.",
	L"Die neue PIN muss sich von der alten PIN unterscheiden.",
	L"Das Item wird nicht im Shop verkauft.",
	L"Das Match wurde durch den Start des PvP beendet.",
	L"Ein Spieler kann am PvP-Matching nicht teilnehmen.",
	L"Das Matching wurde abgebrochen.",
	L"Da das Gruppenmitglied nicht am PvP teilgenommen hat, wurde das Matching abgebrochen.",
	L"Das Match wurde erfolgreich beendet. Du wirst von der Warteliste entfernt.",
	L"Ein User hat die Match-Anmeldung abgebrochen und wurde daher von der Warteliste entfernt.",
	L"Ein Gruppenmitglied ist aus der Gruppe ausgetreten, daher wurde die Anmeldung zum Match abgebrochen.",
	L"Matching wird bereits ausgeführt.",
	L"Die Angaben zum Gruppenmitglied sind fehlerhaft.",
	L"Die Angaben zum PvP-Modus sind fehlerhaft.",
	L"PvP ist erst ab Level 10 möglich.",
	L"Du kannst erst ab dem 10. Level einer PvP-Gruppe beitreten.",
	L"Du hast den PvP-Modus bereits geändert.",
	L"Du kannst mit vier Dungeonmitgliedern nicht in eine PvP-Gruppe wechseln.",
	L"Der PvP-Modus kann nicht geändert werden.",
	L"Da ein Gruppenmitglied noch nicht Level 10 erreicht hat, kann der PvP-Raum nicht gewechselt werden.",
	L"Ein Gruppenmitglied hat Level 10 noch nicht erreicht und kann daher nicht den PvP-Raum betreten.",
	L"Nur Charaktere ab Level 10 können zu einer PvP-Gruppe eingeladen werden.",
	L"Nur ein Charakter ab Level 10 kann Gruppengründer einer PvP-Gruppe werden.",
	L"[CN]전환이 정상적으로 이루어지지 않았습니다. 다시 시도하여 주시기 바랍니다.",
	L"Items konnten nicht sortiert werden. Versuche es später noch einmal.",
	L"Du hast dich nicht für das Matching angemeldet.",
	L"Du bist bereits in einem PvP-Raum.",
	L"Das ist nicht der PvP-Raum.",
	L"Die Anfrage ist fehlgeschlagen.",
	L"Du kannst einen User, der sich zum Matching angemeldet hat, nicht einladen.",
	L"Du kannst einen User, der sich im Matching befindet, nicht einladen.",
	L"Dein Rang ist zu niedrig, um dieses Item zu kaufen.",
	L"Während des Matching kann man sich nicht bei einer anderen Gruppe anmelden.",
	L"Während des Matchings kannst du nicht die Seite wechseln.",
	L"Während des Matchings kann der Channel nicht gewechselt werden.",
	L"ID konnte nicht erkannt werden.",
	L"ID ist in mehrere Channels gleichzeitig eingeloggt.",
	L"Du kannst heute keine Random-Quests mehr annehmen.",
	L"Ich stimme dem Vertrag nicht zu.",
	L"Fehler bei der Anzeige der SP.",
	L"Fehler bei der SP-Eingabe.",
	L"Der gewünschte DB-Name ist fehlerhaft.",
	L"Daten-Überprüfung fehlgeschlagen.",
	L"죄송합니다. 캐쉬샵 점검으로 인해 이용하실 수 없습니다.",
	L"00시부터 06시까지 게임 접속이 제한됩니다.",
	L"Keine Informationen gefunden.",
	L"Du kannst nicht handeln, bis du als Abenteurer registriert wurdest.",
	L"Du kannst keine Nachrichten versenden, bist du als Abenteurer registriert wurdest.",
	L"[CN]사용실패!",
	L"Du hast das Schlachtfeld verlassen.",
	L"Kann erst ab Level 15 erworben werden.",
	L"ServerSN과 MachineID가 매칭되지 않는다.",
	L"MachineID와 ServerSN이 매칭되지 않는다.",
	L"DB에 존재 하지 않는 ServerSN이 있다.",
	L"DB에 존재 하지 않는 MachineID가 있다.",
	L"클라가 준 SN은 없는데 DB에는 MachineID에 해당하는 SN 존재.",
	L"제재된 SN입니다.",
	L"접속 제한된 ServerSN 입니다.",
	L"Mit diesem Account kannst du dich nicht auf dem Testserver einloggen.",
	L"Du hast die Gruppe wegen Zusammenlegung automatisch verlassen.",
	L"Du kannst dieses Item nicht kaufen, da bereits eine unbefristete Skillslot-Erweiterung aktiv ist.",
	L"Dieses Item kann nicht gekauft werden, da bereits die unbefristete Skillslot-Erweiterung aktiv ist.",
	L"[CN] 귀하의 계정이 정지되었습니다. 고객 센터에 문의하여 주십시요.",
	L"[CN] 비밀번호를 잘못 입력 하셨습니다. 다시 입력해 주십시요.",
	L"[CN] 해당 계정은 존재하지 않습니다.",
	L"[CN] 불명확인 시스템 에러",
	L"Du hast bereits eine Segensmedaille im Inventar, daher kann der Würfel nicht geöffnet werden.",
	L"Dein Level ist zu niedrig, um das Item zu erwerben.",
	L"Dein Level ist zu niedrig, um die Ware zu erhalten.",
	L"Gruppen-Erstellung fehlgeschlagen!",
	L"Nicht genügend Gruppenmitglieder.",
	L"Antwortverzögerung der eingeladenen Gruppenmitglieder.",
	L"Diese Ware wird nicht verkauft.",
	L"[JP] 한게임 빌링 오류로 구매할수 없습니다.",
	L"Items aus dem Bank-Sharing-System können nicht per Mail verschickt werden.",
	L"Items aus dem Bank-Sharing-System können nicht gehandelt werden.",
	L"Dieses Item kann erst ab Level 20 erworben werden.",
	L"Nur Charaktere, die einer Gilde angehören, können es umtauschen.",
	L"Kann erst ab Level 30 erworben werden.",
	L"Teilnahme-Anfragen für PvP-Gruppen sind nur mit Komplett-Patch möglich.",
	L"블랙리스트에 등록된 DLL 이 존재합니다.",
	L"Logge dich neu ein oder versuche es später noch einmal!",
	L"Du kannst heute nicht noch einmal am Quiz teilnehmen.",
	L"Unbekannter Fehler",
	L"Während der Handelsbeschränkung kannst du keine Items erwerben.",
	L"Kann während der Handelsbeschränkung nicht verwendet werden.",
	L"Du kannst die Quickslot-Leiste nicht mehr erweitern.",
	L"Der Charakter wurde bereits gelöscht oder die Löschung steht kurz bevor.",
	L"Löschen des Charakters momentan nicht möglich.",
	L"Endgültiges Löschen des Charakters momentan nicht möglich.",
	L"Dieser Charakter kann nicht endgültig gelöscht werden.",
	L"Dieser Charakter kann nach dem Löschen nicht wiederhergestellt werden.",
	L"Wiederherstellung von Charakteren momentan nicht möglich.",
	L"Bitte versuche es später noch einmal.",
	L"Dieser Charakter existiert nicht.",
	L"Charakter konnte nicht gelöscht werden.",
	L"Namensänderung des Pets fehlgeschlagen.",
	L"Namensänderung des Pets bereits im Gange.",
	L"Das Spiel wurde unterbrochen.",
	L"Du bist kein Gildenmeister.",
	L"Die Angaben zum Item sind fehlerhaft.",
	L"Änderung des Gildennamens fehlgeschlagen!",
	L"Bereits in Arbeit ...",
	L"Du hast versucht, ein nicht existierendes Item zu löschen.",
	L"[TW] 낚시대를 장착하지 않았거나, 미끼가 없습니다.",
	L"[TW] 이미 사용중인 낚시터 입니다.",
	L"[TW] 낚시터에 문제가 있습니다. 다른 곳을 이용해 주세요.",
	L"[TW] 낚시 보상에 문제가 발생했습니다.",
	L"Das Löschen des Items ist fehlgeschlagen.",
	L"Nur der Gildenmeister hat die Berechtigung zur Namensänderung seiner Gilde.",
	L"펫이 있을 때만 사용이 가능합니다. 펫이 없을 경우 일주일 이내에 청약 철회를 하셔야 합니다.",
	L"Die Bearbeitungszeit ist abgelaufen, der Vorgang wurde abgebrochen. Bitte versuche es noch einmal.",
	L"Ändern des Gildennamens wurde vom User abgebrochen.",
	L"Du hast nicht den Zustand, um zu diesem Ort zu gelangen.",
	L"Du befindet dich bereits an diesem Ort.",
	L"Dieser Ort ist bereits voll, du kannst ihn nicht betreten.",
	L"Du kannst den Ort nicht betreten, da sich bereits mehrere Gruppen darin befinden.",
	L"Der Eintritt in diesen Ort ist fehlgeschlagen.",
	L"Die Angaben zu dem Ort, in den du eintreten willst, sind fehlerhaft.",
	L"Während des Eintritts in diesen Ort ist ein Fehler aufgetreten.",
	L"In dem betreffenden Ort konnten die Informationen zum User nicht gefunden werden.",
	L"Der Spielstart in einem Dungeon durch automatische Gruppenzusammenlegung ist gescheitert.",
	L"Der Spielstart im Dungeon ist gescheitert.",
	L"Momentan kannst du keine automatische Gruppenzusammenlegung beantragen.",
	L"Du kannst momentan keine automatische Gruppenzusammenlegung durchführen. Bitte warte einen Moment.",
	L"Ein Antrag auf automatische Gruppenzusammenlegung wurde bereits gestellt.",
	L"Wegen fehlerhafter Angaben ist die automatische Gruppenzusammenlegung gescheitert.",
	L"Die Eintragung als Anwärter für eine automatische Gruppenzusammenlegung ist gescheitert.",
	L"Du hast nicht den Zustand, um eine automatische Gruppenzusammenlegung zu beantragen.",
	L"Da nur 1 Gruppenmitglied vorhanden ist, kann das Spiel nicht starten.",
	L"Unter den Gruppenmitgliedern gibt es einen Nutzer, der abgebrochen hat.",
	L"Da die Antwortzeit auf den Beginn des Gruppenspiels abgelaufen ist, findet das Spiel nicht statt.",
	L"Du bist bereits Mitglied der Gruppe.",
	L"Die eingeladene Person wartet bereits auf die Aufnahme in eine andere Gruppe.",
	L"Du bist momentan nicht Mitglied der Gruppe.",
	L"Wundermittel und Geheimtrank überschneiden sich und können daher nicht genutzt werden.",
	L"ServerSN이 중복 접속 중이다.",
	L"ServerSN 존재하지 않는데 삭제하려한다.",
	L"Diese Funktion kann gegenwärtig nicht genutzt werden.",
	L"넥슨 통합 맵버쉽 계정 인증 상향 조정 필요.",
	L"Dein Körper hat bereits seine Leistungsgrenze erreicht. Du kannst den Geheimtrank nicht nutzen.",
	L"Du erfüllst die Level-Mindestanforderungen nicht. Das Spiel in diesem Dungeon kann nicht beginnen.",
	L"[US] 추천받을 대상이 아닙니다.",
	L"[US] 추천인이 이미 3인을 추천하였습니다.",
	L"[US] 추천 가능한 유저가 아닙니다.",
	L"[US] 맞지 않는 아이템을 사용하였습니다.",
	L"Charakter-Slot konnte nicht erweitert werden. Maximal 8 Charakter-Slots erlaubt.",
	L"Ende der automatischen Gruppenzusammenlegung wegen Start eines Dungeon-Spiels.",
	L"Ein Betroffener der automatischen Gruppenzusammenlegung hat dem Spielstart nicht zugestimmt.",
	L"Automatische Gruppenzusammenlegung erfolgreich abgebrochen.",
	L"Ein Gruppenmitglied hat dem Spielstart in der automatischen Gruppenzusammenlegung nicht zugestimmt. Die automatische Gruppenzusammenlegung wurde abgebrochen.",
	L"Die automatische Gruppenzusammenlegung war erfolgreich. Dein Name wurde von der Warteliste entfernt.",
	L"Der Antrag auf automatische Gruppenzusammenlegung wurde zurückgezogen. Der Name wurde von der Warteliste gestrichen.",
	L"Durch den Austritt eines Gruppenmitglieds wurde der Antrag auf automatische Gruppenzusammenlegung zurückgezogen.",
	L"Das erforderliche Item-Level ist nicht erfüllt. Du kannst den Dungeon nicht starten.",
	L"Die Tastaturbelegung konnte nicht gespeichert werden.",
	L"Es konnten keine Tastaturbelegungsdaten gespeichert werden.",
	L"Die Tastaturbelegung konnte nicht gelesen werden.",
	L"Es konnten keine Tastaturbelegungsdaten gelesen werden.",
	L"Die Antwort auf den Spielbeginn der Gruppe im Dungeon verzögert sich.",
	L"[US] 추천인 테이블에서 캐릭터 삭제를 실패하였습니다.",
	L"[US] 보안패드 리셋용 질문 및 답변을 입력하지 않았습니다.",
	L"Der Spieler gehört nicht zur gleichen Gruppe.",
	L"Die Daten zur Chat-Auswahl konnten nicht gespeichert werden.",
	L"Die Daten der Chat-Auswahl konnten nicht gelesen werden.",
	L"Einige Daten der Chat-Auswahl konnten nicht gelesen werden.",
	L"Test",
	L"[US] 한달에 $1,000 까지만 선물이 가능합니다.",
	L"나이정보를 확인 중 오류가 발생하였습니다. 잠시 후 다시 로그인하여 주십시오.",
	L"실명인증을 받지 않은 회원이거나 넥슨닷컴 회원이 아닙니다.",
	L"셧다운제에 의하여 게임이용이 차단 됩니다.",
	L"선택적 셧다운제의 의해 게임이용이 차단됩니다.",
	L"통합 맴버십 ATL 2.0 유저가 아니므로 게임이용이 차단 됩니다.",
	L"Eine Öffnung ist noch nicht möglich.",
	L"Die Öffnungszeit ist vorbei.",
	L"ServiceID가 잘못 되었습니다.",
	L"캐시 잔액 정보를 찾을 수 없습니다.",
	L"[TW]ServiceCode 가 올바르지 않습니다.",
	L"[TW]정의되지 않은 애러 발생했습니다.",
	L"[TW]시간형식이 잘못되었습니다.",
	L"[TW]Type정보가 잘못되었습니다.",
	L"[TW]이전 상품 구매가 진행 중입니다.",
	L"Dein Level ist zu hoch für diese Quest.",
	L"파라매터 갯수 입력이 잘못되었습니다.",
	L"[JP] 합성제가 없습니다.",
	L"[JP] 없는 아바타를 합성하려고 했습니다.",
	L"[US]월 선물 가능 횟수를 초과하였습니다.",
	L"Dieser Dungeon kann nur alleine gespielt werden.",
	L"Der Dungeon ist noch nicht geöffnet.",
	L"Der Charakter wurde nicht korrekt ausgewählt.",
	L"Der Charakter kann keine Privatnachricht an sich selbst schicken.",
	L"Es ist ein Fehler in der Pet-Information aufgetreten.",
	L"Du kannst es nur verwenden, wenn das Pet herbeigerufen wurde.",
	L"Kann nur von Teen-Pets verwendet werden.",
	L"Kann nur von Kid-Pets verwendet werden.",
	L"Die Einstellung der Tag-Anzahl ist fehlerhaft.",
	L"Das Spiel startet erst mit mindestens zwei Team-Mitgliedern.",
	L"대전 아이템은 이용할 수 없는 기능입니다.",
	L"대전 아이템 사용 횟수가 남지 않았습니다.",
	L"대전 아이템 사용 횟수가 남지 않았습니다.",
	L"대전 아이템 사용 횟수가 남지 않았습니다.",
	L"Du hast den Dungeon verlassen.",
	L"Du hast den Wettkampf verlassen.",
	L"Es erfolgt ein Austritt aufgrund eines Channel-Wechsels.",
	L"Es erfolgt ein Austritt aufgrund des Aufsuchens von gleichen Gruppenmitgliedern.",
	L"Es erfolgt ein Austritt aufgrund der Benutzung eines Fortbewegungsitems.",
	L"Austritt aufgrund von unrechtmäßiger Beendigung.",
	L"Während du einen Dungeon spielst, kannst du keine neuen Gruppenmitglieder einladen.",
	L"Eine Einladung ist nicht möglich, da der Spieler bereits einer anderen Gruppe angehört.",
	L"Die Person befindet sich im Wettkampf und kann daher nicht eingeladen werden.",
	L"Die Person befindet sich gerade in einem Dungeon und kann nicht eingeladen werden.",
	L"Der Spieler konnte nicht auf diesem Server gefunden werden.",
	L"Es können keine weiteren Gruppenmitglieder eingeladen werden.",
	L"Während eines Wettkampfs können keine Gruppenmitglieder eingeladen werden.",
	L"Dein Level ist zu niedrig, um dieses Feld zu betreten.",
	L"Du hast die Dungeons noch nicht durchgespielt, die Voraussetzung für das Betreten dieses Felds sind.",
	L"Es können maximal 30 Quests ausgeführt werden.",
	L"Du hast nicht genug ED.",
	L"Ein Spieler, der die automatische Gruppenzusammenstellung nutzt, kann nicht eingeladen werden.",
	L"Wenn die automatische Gruppenzusammenstellung aktiv ist, kannst du niemanden in deine Gruppe einladen.",
	L"Im PvP-Raum kannst du keine Gruppenmitglieder einladen.",
	L"Während des Trainings kannst du kein Gruppenmitglied einladen.",
	L"Während des PvP-Matchings kannst du kein Gruppenmitglied einladen.",
	L"Solange du für die automatische Gruppenzusammenstellung eingetragen bist, funktionieren manuelle Gruppeneinladungen nicht.",
	L"Wenn du für das PvP-Matching eingetragen bist, kannst du kein Gruppenmitglied einladen.",
	L"Deine Gruppe befindet sich auf demselben Feld wie du.",
	L"Da es sich um einen Anwärter für eine andere Gruppe handelt, kann diese Person nicht eingeladen werden.",
	L"이 이벤트 쿠폰은 계정당 한 번만 받을 수 있습니다.",
	L"[ID] ID 또는 비밀번호가 잘못되었습니다.",
	L"Dieser Nickname ist nicht vorhanden.",
	L"Die Server-Group-ID ist falsch.",
	L"[TW] 공유 은행 처리중인 아이템 입니다. 은행을 닫고 다시 시도해 주세요.",
	L"Wer über keine Teilnahmeberechtigung zum Online-Wettkampf verfügt, kann den PvP-Channel nicht verwenden.",
	L"Um den Würfel zu öffnen, benötigst du Items und ED.",
	L"Du hast zu wenig ED, um den Würfel zu öffnen.",
	L"Es wird mit der gegenwärtigen Teilnehmerzahl gestartet.",
	L"길드 생성은 하루에 한 번 가능합니다.",
	L"[ID] ID 는 최소 4자에서 최대 20자 까지 입력 가능 합니다.",
	L"[ID] PW 는 최소 6자에서 최대 15자 까지 입력 가능합니다.",
	L"Das Event ist zu Ende.",
	L"Dieses Item kannst du mit Ara nicht herholen.",
	L"금일 선물하기 제한을 초과하였습니다.",
	L"Leider ist die max. Zahl an Umtäuschen aufgebraucht.\nNach der Wartung am 17.01. werden zusätzliche Umtäusche freigegeben.",
	L"[ID] 인증실패 : 서버와의 연결을 확인해 주십시오.",
	L"Dieses Pet existiert nicht.",
	L"Diese Funktion wird bereits genutzt.",
	L"Kann erst ab der Stufe 'Kid' verwendet werden.",
	L"Während du auf ein Spiel wartest, kannst du deine Skill-Slots nicht ändern.",
	L"Weil du dich momentan nicht im Raum aufhältst, konnten die Informationen zu den Feld-Monstern nicht geladen werden.",
	L"Weil du dich momentan nicht im Raum aufhältst, konnten die Informationen zu den Feld-Monstern nicht geladen werden.",
	L"Das Item zur Erweiterung der Slots konnte nicht erworben werden. Eine Slot-Erweiterung ist nur bis max. 30 Stück möglich.",
	L"Der Ausschluss aus dem Dungeon erfolgte aufgrund der Ausschlussabstimmung.",
	L"Der Abstimmende ist kein echter Spieler.",
	L"Der, über den abgestimmt werden soll, ist kein echter Spieler.",
	L"빌링 서버가 초기화 되지 않았습니다.",
	L"상품 구매중 문제가 발생하였습니다.",
	L"구매 처리 중입니다. 잠시 후에 다시 시도해 주세요.",
	L"아직 처리 중인 작업이 있습니다. 잠시 후에 다시 시도 해주세요.",
	L"아직 빙고판이 완성되지 않았습니다.",
	L"일시적인 오류입니다. 잠시 후에 다시 시도 해주세요.",
	L"Du hast nicht genügend ED, um eine Einladung zu registrieren.",
	L"Du kannst dich nicht in dieser Gilde anmelden, da die maximale Mitgliederzahl erreicht ist.",
	L"Einladungsanfrage konnte nicht gesendet werden.",
	L"Gildensuche konnte nicht registriert werden.",
	L"Es existiert bereits eine Gilden-Einladungsnachricht.",
	L"Es ist bereits eine Gildensuche registriert.",
	L"Gilden-Einladungsnachricht konnte nicht registriert werden.",
	L"Du hast nicht genügend ED, um die Gildensuche zu registrieren.",
	L"Keine Gildeneinladung vorhanden.",
	L"Keine Gildensuche vorhanden.",
	L"Diese Gilde existiert nicht.",
	L"Du bist nicht berechtigt, die Liste eingeladener User einzusehen.",
	L"Maximale Anzahl Dungeon-Eintritte ist erreicht.",
	L"로컬 랭킹 유저 정보 초기화 오류",
	L"로컬 랭킹 유저 정보가 초기화 되어있지 않습니다.",
	L"프로필 정보는 20자까지만 입력 가능합니다.",
	L"로컬 랭킹 게시판 조회 오류",
	L"로컬 랭킹 유저 정보 쓰기 오류",
	L"다음 정보 수정은 익일 06시 이후에 가능합니다.",
	L"[TW]2인 플레이 던전입니다.",
	L"더 이상 추천 할 수 없는 유저입니다.",
	L"비밀번호가 잘 못 되었습니다",
	L"투니랜드 계정이거나, 계정 인증 이후 추천 가능 합니다.",
	L"동일 명의의 계정이므로 추천 할 수 없습니다.",
	L"추천을 실패 하였습니다.",
	L"PASSWORD 길이가 잘못되었습니다.",
	L"프로필 정보에 사용할 수 없는 단어가 들어있습니다.",
	L"영웅 대전 후보 리스트에 이미 존재하는 유닛입니다.",
	L"닉네임 길이가 잘못되었습니다.",
	L"영웅 대전 후보 리스트에 존재하지 않는 유닛입니다.",
	L"--/;/따옴표/쉼표/공백 등은 사용할 수 없습니다.",
	L"Du besitzt keine \"Anleitung zu den Feldern\".",
	L"Das Kapitel konnte nicht eingetragen werden.",
	L"Das Kapitel ist bereits eingetragen.",
	L"해당 유닛은 존재하지 않습니다.",
	L"UNKNOWN",
	L"벌써 임자가 있습니다.",
	L"양다리는 안됩니다!",
	L"마을, 필드에서만 커플 신청을 할 수 있습니다.",
	L"접속중인 유저가 아닙니다.",
	L"인벤토리에 커플링이 존재하지 않습니다.",
	L"동성 캐릭터간의 커플은 한국에서는 안됩니다.",
	L"해당 서버군에 존재하지 않는 캐릭터 명입니다.",
	L"커플 신청 받는 유저의 정보가 이상합니다.",
	L"정상적인 캐릭터 명이 아닙니다.",
	L"알 수 없는 에러입니다.",
	L"존재하지 않는 유저입니다.",
	L"상대방이 실수로 커플링을 떨어트렸어요! 얼른 찾아오라고 말해주세요!",
	L"상대방이 수락했지만, 내 인벤토리에 커플링이 없어요! 인벤토리를 확인해 주세요!",
	L"인연 시스템 사용 아이템 삭제 실패",
	L"요청한 연인 정보의 캐릭터 정보가 이상합니다.",
	L"당신은 솔로입니다. 연인이 없어 드릴 정보가 없습니다.",
	L"선택한 옵션값이 이상합니다.",
	L"인벤토리에 결혼반지가 존재하지 않습니다.",
	L"선택한 옵션에 필요한 캐시 아이템이 인벤토리에 존재하지 않습니다.",
	L"결혼을 하기 위해서는 커플이 되고 72시간이 지나야 합니다.",
	L"결혼을 하려면 커플 상태여야 합니다.",
	L"무료 1차 전직 이벤트를 진행할 수 있는 상태가 아닙니다.",
	L"인벤토리에 결혼에 필요한 아이템이 존재하지 않습니다.",
	L"결혼하기 아이템 사용 실패 하였습니다.",
	L"결혼식에 초대하려는 인원 수보다 인벤토리에 있는 초대권 수가 부족합니다.",
	L"이벤트 기간이 종료되어 전직이 불가능합니다.",
	L"탈 것을 더 이상 등록 할 수 없습니다. \n사용하지 않는 탈 것을 놓아주세요!",
	L"탈 것 생성 아이템을 사용할 수 없습니다.",
	L"탈 것 정보를 가져오지 못했습니다.",
	L"탈 것을 생성할 수 있는 아이템이 아닙니다.",
	L"탈 것 생성에 실패 하였습니다.",
	L"이미 다른 탈 것이 소환되어 있습니다.",
	L"존재하지 않는 탈 것입니다.",
	L"해당 탈 것은 소환되어 있지 않습니다.",
	L"소환되어 있는 탈 것이 없습니다.",
	L"탈 것 놓아주기에 실패하였습니다.",
	L"소환되어 있는 탈 것은 놓아줄 수 없습니다.",
	L"탈 것을 소환할 수 없는 지역입니다.",
	L"보유 중인 탈 것이 없습니다.",
	L"존재하지 않는 아이템에 대한 정보를 요청하였습니다.",
	L"웨딩 관련 아이템이 아닙니다.",
	L"웨딩 관련 아이템의 정보가 없습니다.",
	L"예약된 결혼식장의 정보가 없습니다.",
	L"결혼식을 예약한 유저의 닉네임을 찾을 수 없습니다.",
	L"사용가능한 커플, 결혼 상태가 아닙니다.",
	L"던전에서는 소환하기를 사용 할 수 없습니다.",
	L"[INT] 지원하지 않는 캐시 타입 입니다.",
	L"소환하기를 사용 할 준비가 되지 않았습니다.",
	L"동일 채널에서만 소환하기가 가능합니다.",
	L"연인 소환을 위한 필드 이탈",
	L"아이템 정보가 존재하지 않습니다.",
	L"결혼식장에 입장 가능한 위치가 아닙니다.",
	L"결혼식장에 입장 가능한 아이템이 아닙니다.",
	L"결혼식장 입장을 위한 필드 이탈",
	L"결혼식이 완료 되었거나 존재하지 않는 결혼식입니다.",
	L"커플 상태가 아닙니다.",
	L"결혼식장에 입장이 실패하였습니다.",
	L"현재 필드에 소환이 불가능 합니다.",
	L"이별이 가능한 위치가 아닙니다.",
	L"위자료를 지불 할 수 없습니다.",
	L"신랑이나 신부가 아닙니다.",
	L"신랑 신부가 모두 방에 존재해야 합니다.",
	L"사랑의 리퀘스트를 가지고 오세요~뽀~",
	L"러브 뽀루가 우편으로 지급되었습니다.",
	L"러브 뽀루가 우편으로 지급되었습니다.",
	L"사랑의 리퀘스트를 가지고 오세요~뽀~",
	L"뽀루의 러브 레터를 발송하려면 1만 ED가 필요합니다.",
	L"뽀루의 러브 레터를 발송하지 못했습니다.",
	L"인연 상태가 아닙니다.",
	L"애칭 변경권의 정보가 이상합니다.",
	L"인연 상태에서는 삭제 할 수 없습니다.",
	L"Fehler bei der Berechnung der VIP-Zeit.",
	L"[JP] 선택 할 수 없는 옵션입니다.",
	L"[JP] 합성 부위가 다릅니다.",
	L"결혼 상태가 아닙니다.",
	L"연인이 필드 입장에 실패 하였습니다.",
	L"Das Item-Level passt nicht zu dieser Gesegneten Raumzeit-Schriftrolle.",
	L"Dieses Item wurde bereits identifiziert.",
	L"Es befindet sich kein Item im Inventar.",
	L"Du hast nicht genügend ED, um das Item identifizieren zu lassen.",
	L"Das Identifizieren ist fehlgeschlagen.",
	L"Nicht genügend Gesegnete Raumzeit-Schriftrollen.",
	L"Dieses Item kann nicht identifiziert werden.",
	L"",
	L"",
	L"Dieses Item kann nicht umgetauscht werden.",
	L"Du besitzt nicht genügend ED für die Umtausch-Gebühr.",
	L"",
	L"",
	L"",
	L"",
	L"Du hast keine Items mehr, die du umtauschen könntest.",
	L"Der Itemtausch ist fehlgeschlagen.",
	L"",
	L"",
	L"Zeitbegrenzte Items oder Materialien können nicht umgetauscht werden.",
	L"Zeitbegrenzte Items oder Materialien können nicht umgetauscht werden.",
	L"Die Voraussetzungen sind nicht erfüllt.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Mit einem gesperrten Account ist das Kaufen nicht möglich.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Aufgrund eines Fehlers in der Datei CheckKom.xml wird das Programm geschlossen.",
	L"",
	L"Fehlerhafte Stage-Information.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Mindestens eine Voraussetzung ist nicht erfüllt. Überprüfe, ob du das Pet herbeigerufen hast!",
	L"Mindestens eine Voraussetzung ist nicht erfüllt. Überprüfe, ob du das Pet verwenden kannst!",
	L"Du hast den Verwandlungstrank der Halloweenkürbis-Fee erfolgreich angewendet!",
	L"Mindestens eine Voraussetzung ist nicht erfüllt. Überprüfe, ob die Vertrautheit des Pets 100% beträgt!",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Maximale Anzahl Dungeon-Spiele ist erreicht.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Aufgrund einer Dateiveränderung wird das Programm geschlossen.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"더 이상 구입 할 수 없습니다.",
	L"버프 효과가 지속되고 있는 동안 동일한 버프 효과의 아이템을 다시 사용할 수 없습니다.",

	L""
};
