#pragma once

//IT버전 출력
static wchar_t* szErrorStrIT[] = {
	L"Successo",
	L"Errore sconosciuto",
	L"È subentrato un errore nello status del giocatore.",
	L"Versione incorretta. Effettua nuovamente il login.",
	L"Il server è pieno. Il numero massimo di giocatori è stato raggiunto.",
	L"Verifica del server di gioco in corso. Effettua nuovamente il login al termine della verifica del sistema.",
	L"Hai cercato di accedere due volte allo stesso server.",
	L"Hai cercato di accedere contemporaneamente a più canali.",
	L"Verifica dell'IP del server non riuscita.",
	L"Si è verificato un problema nel server UID.",
	L"L'utente non esiste",
	L"Questo giocatore non esiste più.",
	L"I dati d'accesso sono incorretti.",
	L"Le impostazioni del server non sono corrette.",
	L"Non è stato possibile verificare i tuoi dati d'accesso.",
	L"Il tuo account è stato bloccato.\nRivolgiti al supporto di Elsword: http://support.elsword.it",
	L"La richiesta può essere fatta solo da un system operator.",
	L"Nessun Proxy ID disponibile.",
	L"Questo indirizzo IP non è autorizzato.",
	L"I dati ID per il canale non si trovano sul server di gioco.",
	L"La lunghezza dell'ID non è valida.",
	L"Errore durante la transazione.",
	L"La lunghezza dell'ID non è ammessa.",
	L"La lunghezza della password non è valida.",
	L"La lunghezza del nome utente non è valida.",
	L"Il giocatore eliminato ha cercato di creare un personaggio.",
	L"Questo nome esiste già.",
	L"Errore durante la transazione.",
	L"Errore durante il caricamento dei dati del personaggio.",
	L"La lunghezza del nome del personaggio non è valida.",
	L"Non si possono creare ulteriori personaggi.",
	L"Nickname attualmente non utilizzabile!",
	L"La banca dati non ha potuto creare un SN del personaggio per il messenger.",
	L"Questo nickname non può essere utilizzato.",
	L"È possibile creare un massimo di quattro personaggi al giorno.",
	L"Il personaggio selezionato non si trova nel server di gioco.",
	L"La classe scelta per il personaggio non è valida.",
	L"Non è stato possibile accedere alle informazioni sulla Pietra rianimante.",
	L"La banca dati non ha potuto accedere all'SN del personaggio del messenger.",
	L"È stato riscontrato un errore nella banca dati durante la scelta del personaggio.",
	L"Il nickname deve essere cambiato.",
	L"Non è stato trovato alcun canale PvP adatto al tuo livello.",
	L"Il personaggio da eliminare non si trova nel canale.",
	L"Cambio di canale non riuscito.",
	L"Non hai abbastanza VP per entrare.",
	L"Accesso al canale della Piazza del Villaggio fallito.",
	L"Accesso al canale fallito.",
	L"Nessun combattimento in corso.",
	L"Non è possibile accedere alla lista dei gruppi.",
	L"Nel Portale dei Dungeon non è possibile vedere la Lista dei gruppi.",
	L"In questo Portale dei Dungeon non è possibile aprire la Lista dei gruppi.",
	L"Il PvP è possibile solo dal livello 3.",
	L"Non è possibile creare altre stanze sul server.",
	L"In questo slot non sono presenti altri utenti.",
	L"Lo slot dove si trova il personaggio scelto non è stato trovato.",
	L"La stanza è piena.",
	L"I dati d'accesso sono sbagliati.",
	L"Il Dungeon precedente non è stato completato.",
	L"L'avvio immediato è fallito. Nessuna stanza disponibile.",
	L"Solo il capo di questa stanza può effettuare la richiesta.",
	L"Lo stato della stanza non consente alcun pacchetto.",
	L"Questo giocatore non è ancora pronto.",
	L"Il numero dei membri del team non corrisponde.",
	L"Per cominciare il gioco più di un personaggio deve essere \"pronto\".",
	L"Non è stato possibile modificare il processo di caricamento.",
	L"La stanza viene creata.",
	L"Le informazioni sulla stanza sono state modificate.",
	L"La stanza è stata eliminata.",
	L"Non è stato trovato alcun giocatore nella stanza.",
	L"Accesso non riuscito.",
	L"Non hai potuto abbandonare la stanza.",
	L"L'UID dell'NPC morto non è valido.",
	L"L'NPC è già morto.",
	L"Dati dei mostri non corretti. Caricamento interrotto.",
	L"Impossibile trovare il giocatore.",
	L"Il tipo di chat non è valido.",
	L"Non puoi espellere te stesso dalla stanza.",
	L"Will Point insufficienti.",
	L"Questa tipologia di gioco non supporta le statistiche di completamento.",
	L"Il gioco sta per essere chiuso. Non puoi accedere alla stanza.",
	L"Non puoi accedere alla stanza.",
	L"La stanza a cui vuoi accedere non contiene alcuna informazione.",
	L"Durante il commercio non puoi prepararti a giocare.",
	L"Non puoi accedere alla stanza poiché il gioco è appena cominciato. Riprova più tardi.",
	L"Nell'inventario non si trova alcun item di inizio partita.",
	L"Un giocatore non autorizzato ha cercato di creare una stanza d'osservazione.",
	L"I dati della mappa del PvP sono errati.",
	L"Solo chi ha il permesso di partecipare al torneo in modalità offline può accedere al canale del torneo.",
	L"Ti manca l'item necessario per poter giocare nel Dungeon selezionato. Non appena il gioco avrà inizio, sarai pertanto espulso.",
	L"La funzione invito può essere utilizzata solo nella stanza PvP.",
	L"Attualmente il giocatore che desideri invitare non può entrare nella stanza PvP.",
	L"Puoi invitare solo giocatori che si trovano nella lobby del canale PvP.",
	L"Il gioco può iniziare solo quando ti sei iscritto a un gruppo.",
	L"Impostazione per il numero di kill non valida.",
	L"L'item non esiste più.",
	L"È già stato ricevuto da qualcun altro.",
	L"La distribuzione casuale dell'item non è riuscita.",
	L"Non sono disponibili informazioni sull'item.",
	L"L'ID dell'item è errato.",
	L"L'item non può essere ceduto.",
	L"L'item non può essere riparato",
	L"L'item nello slot di scelta rapida non può essere utilizzato",
	L"Lo slot di scelta rapida non può essere utilizzato nel Dungeon Evento",
	L"L'item non può essere acquistato",
	L"Non si è potuto prelevare l'item dal deposito.",
	L"Nel deposito non c'è abbastanza spazio per questo item.",
	L"Il messaggio è troppo lungo.",
	L"Non è stato possibile cambiare il team",
	L"Non è stato possibile salvare le modifiche nello slot.",
	L"Impossibile partecipare.",
	L"Non è stato possibile chiudere lo slot.",
	L"Il giocatore non può essere espulso.",
	L"Non è stato possibile salvare i dati dell'avversario.",
	L"Non è stato possibile modificare lo status.",
	L"Il giocatore ha deciso di uscire.",
	L"La connessione è stata interrotta.",
	L"Sei stato espulso.",
	L"Il tuo livello attuale è troppo alto per questo canale.",
	L"Lo Stand è stato chiuso.",
	L"Non è stato possibile visitare lo Stand.",
	L"Il tempo è scaduto. Lo Stand è chiuso.",
	L"Lo Stand è stato annullato.",
	L"Il numero dei venditori privati è sbagliato.",
	L"È subentrato un errore durante il commercio.",
	L"Non hai abbastanza spazio nell'inventario o i dati dell'item non sono corretti.",
	L"Non hai più abbastanza Will Point a disposizione.",
	L"Il commercio è stato interrotto. Non ci sono più oggetti da scambiare.",
	L"Il commercio è stato interrotto.",
	L"Lo Stand è stato chiuso perché non è stato messo in vendita nessun oggetto.",
	L"Il commercio è stato interrotto.",
	L"Tutti gli item sono stati venduti. Lo Stand verrà chiuso.",
	L"Il commercio è stato interrotto perché tu hai abbandonato la stanza.",
	L"Lo Stand è stato chiuso.",
	L"Si è verificato un problema nel client.",
	L"Non puoi rimanere oltre nel canale di combattimento.",
	L"Se scegli di partecipare al PvP dovrai abbandonare il gruppo.",
	L"Il gruppo si è sciolto perché il Dungeon è stato completato.",
	L"Hai lasciato il gruppo perché partecipi al Mercato.",
	L"Sei entrato nel Campo di Addestramento. Hai abbandonato il gruppo.",
	L"Finito.",
	L"Il gioco è stato chiuso per sospetto di hacking.",
	L"Il client si è impiantato. Il gioco verrà chiuso.",
	L"Gli EXP del personaggio non possono essere modificati.",
	L"La banca dati non ha potuto assegnare il personaggio.",
	L"Il livello di autorità non è valido.",
	L"Il giocatore non esiste.",
	L"Errore durante la transazione.",
	L"Non è disponibile alcun giocatore con questo livello di autorità.",
	L"L'operatore ha chiuso la comunicazione.",
	L"Questo comando può essere eseguito solamente all'interno.",
	L"Questo comando non può essere eseguito in questa stanza.",
	L"L'item non può essere acquistato.",
	L"L'item non può essere venduto.",
	L"Questa quest è già in corso.",
	L"Si è tentato di eliminare una quest che non è stata cominciata.",
	L"Questa quest non esiste.",
	L"Quest già completata.",
	L"Questo personaggio non può affrontare la quest.",
	L"La quest precedente non è stata terminata.",
	L"Hai ricevuto una quest errata dall'NPC.",
	L"Il template della quest non esiste.",
	L"Non puoi terminare la quest perché non tutti i requisiti sono stati soddisfatti.",
	L"La banca dati non ha potuto elaborare i dati della quest.",
	L"Puoi accettare al massimo 10 quest alla volta.",
	L"Il tuo livello è troppo basso per poter accettare la quest.",
	L"Non puoi completare la quest perché non hai abbastanza spazio nell'inventario.",
	L"C'è stato un errore nella consegna della ricompensa della quest.",
	L"La ricompensa che cercavi non è stata trovata.",
	L"La quest per il cambio di classe è già in esecuzione.",
	L"È sorto un problema durante l'elaborazione della ricompensa della quest per il cambio di classe.",
	L"Il tipo della quest è invalido.",
	L"Il messaggio di chat è stato digitato più velocemente di quanto stabilito.",
	L"Non puoi bisbigliare a te stesso.",
	L"La chat è difettosa.",
	L"Questo utente non è connesso al momento.",
	L"--/;/virgolette/virgole/spazio non possono essere utilizzati.",
	L"Il tempo di immissione è più breve del tempo di carica dell'attuale lista dei giocatori.",
	L"La ricerca dei dati dell'utente è ancora in corso.",
	L"Questo utente non è attualmente connesso.",
	L"Il nickname non è disponibile.",
	L"Accesso fallito alla Piazza del Villaggio.",
	L"Non sei potuto uscire dalla Piazza del Villaggio.",
	L"Questa skill si trova già al livello più alto.",
	L"Questa skill non esiste.",
	L"Il tuo livello è troppo basso per imparare questa skill.",
	L"Non hai Skill Point sufficienti.",
	L"Non possiedi l'item necessario.",
	L"Devi concludere la quest per poter effettuare l'acquisto.",
	L"La skill precedente non è stata ancora appresa.",
	L"Hai già appreso questa skill.",
	L"L'ID dello slot per le skill è errato.",
	L"Puoi inserire solamente le skill che hai già imparato.",
	L"Il reset della skill è fallito.",
	L"La barra skill B non può essere utilizzata.",
	L"È subentrato un errore durante l'espansione della barra skill B.",
	L"Puoi imparare questa skill solo una volta che il sigillo è stato tolto.",
	L"Questa skill si trova ad un livello che non hai ancora raggiunto.",
	L"Non hai abbastanza Skill Point per imparare questa skill.",
	L"Non hai abbastanza Skill Point per imparare questa skill.",
	L"Hai tentato di modificare le impostazioni di una skill che non esiste.",
	L"Le informazioni di livello della skill non sono valide.",
	L"Il livello della skill impostato non corrisponde al livello corretto.",
	L"Le modifiche alla validità degli Skill Point dello Shop non sono state applicate.",
	L"La registrazione degli Skill Point dello Shop non ha funzionato.",
	L"Le informazioni sugli Skill Point dello Shop non sono state aggiornate.",
	L"Il reset delle informazioni sugli Skill Point dello Shop negozio è fallito.",
	L"Le skill standard non possono essere resettate.",
	L"Il gruppo non è stato creato.",
	L"Non hai potuto abbandonare il gruppo.",
	L"L'informazione del gruppo non è corretta.",
	L"Questo utente non può essere invitato.",
	L"Nessun gruppo disponibile.",
	L"Fai già parte di un gruppo.",
	L"Non si possono creare gruppi in modalità PvP.",
	L"Non è possibile entrare in un gruppo nella modalità PvP.",
	L"Il gruppo è completo.",
	L"Non è possibile entrare in questo gruppo.",
	L"Il gruppo si è sciolto.",
	L"L'ingresso nel gruppo è stato rifiutato.",
	L"L'invito al gruppo è stato rifiutato.",
	L"Non è possibile accedere al Dungeon da qui.",
	L"La modifica dello stato di disponibilità è fallita.",
	L"Hai scelto il Dungeon sbagliato.",
	L"L'avvio del gioco è fallito.",
	L"Tipo di gioco non valido.",
	L"Non sei il capogruppo.",
	L"Il capogruppo non è stato cambiato.",
	L"I membri del gruppo non sono stati cambiati.",
	L"Non puoi cominciare il Dungeon in questa area.",
	L"Le impostazioni della privacy non sono state modificate.",
	L"Il giocatore che è stato nominato capogruppo non può eseguire questo Dungeon.",
	L"Il capogruppo non può modificare lo stato di disponibilità.",
	L"Nessun partner per la chat disponibile.",
	L"La lista dei gruppi richiesta non è valida.",
	L"L'impostazione della limitazione di livello non è stata modificata.",
	L"Questo è un gruppo privato.",
	L"Nessuna Pietra rianimante disponibile.",
	L"Sei già resuscitato.",
	L"Rinascita fallita.",
	L"In questo Dungeon non è possibile usare la Pietra rianimante.",
	L"Impossibile attualizzare uno stato che non esiste.",
	L"Non è possibile accedere alle opzioni della Community.",
	L"Non è possibile inserire altri nomi nella Lista di blocco.",
	L"Questo giocatore è già presente nella Lista di blocco.",
	L"Questo giocatore è già stato cancellato dalla Lista di blocco.",
	L"Questo giocatore non esiste.",
	L"Non è stato eliminato dalla Lista di blocco.",
	L"Non puoi inserire te stesso nella Lista di blocco.",
	L"Non puoi cancellarti dalla Lista di blocco.",
	L"Puoi inserire nella Lista di blocco solo i giocatori che hanno effettuato l'accesso.",
	L"Impossibile inserire il proprio personaggio.",
	L"Il tempo per l'inserimento degli amici è scaduto.",
	L"Il personaggio non è stato trovato.",
	L"Con questo status il tuo personaggio non può invitare nessuno.",
	L"Al momento non è possibile invitare l'altro giocatore.",
	L"Al momento questo giocatore non può partecipare.",
	L"Non può essere aggiunto come amico.",
	L"Non si è potuto creare lo Stand.",
	L"Non puoi abbandonare il commercio privato.",
	L"La ricerca di giocatori nel commercio privato è fallita.",
	L"L'item scelto è difettoso.",
	L"Gli ED inseriti non sono corretti.",
	L"L'oggetto non esiste.",
	L"ED insufficienti!",
	L"Puoi selezionare solamente gli oggetti dell'inventario.",
	L"Non c'è abbastanza spazio nell'inventario.",
	L"Gli item utilizzati dal personaggio non possono essere venduti.",
	L"La chat di commercio non può essere aperta qui.",
	L"Non puoi commerciare con te stesso.",
	L"Non è possibile rivendere un item la cui validità è consumata. Ripara l'item e prova ancora.",
	L"L'item è già stato registrato.",
	L"Solo gli item registrati possono essere cancellati.",
	L"Puoi scegliere al massimo 10 item diversi.",
	L"Durante il commercio l'altro giocatore ha sorpassato le proprie risorse di ED. Riduci gli ED per questo scambio.",
	L"La richiesta di commercio privato è stata accettata.",
	L"È già in corso il commercio con un altro giocatore.",
	L"La richiesta di commercio privato è stata rifiutata.",
	L"Non è possibile commerciare.",
	L"Un errore del server ha impedito il commercio.",
	L"Non sei in possesso dell'item necessario per entrare in questo Dungeon.",
	L"Non sei ancora autorizzato ad entrare nel Campo di Addestramento.",
	L"Il Dungeon che dovrebbe servire da Campo di Addestramento non ha alcun ID.",
	L"È sorto un errore durante il salvataggio della ricompensa.",
	L"L'item selezionato non compare nell'inventario.",
	L"L'item selezionato non è un Bauletto.",
	L"Questo personaggio non può utilizzare questo item.",
	L"Non hai abbastanza chiavi per aprire il Bauletto.",
	L"Il Bauletto non può essere aperto.",
	L"L'item non può essere prodotto.",
	L"Non c'è abbastanza spazio nell'inventario per aprire il Bauletto.",
	L"Sono stati riscontrati più accessi simultanei.",
	L"L'UID del giocatore è errato.",
	L"L'ID del giocatore è errato.",
	L"L'UID del personaggio è errato.",
	L"Il nickname del personaggio è errato.",
	L"L'UID del server di gioco è errato.",
	L"Le informazioni sul giocatore sono errate.",
	L"Le informazioni del server di gioco sono errate.",
	L"La ricerca di UID è fallita.",
	L"Il numero del messenger è errato.",
	L"L'item non può essere prodotto.",
	L"Questa non è una pergamena.",
	L"Non hai abbastanza ED per il crafting!",
	L"Non hai abbastanza materiale.",
	L"Deve esserci almeno uno spazio libero nell'inventario per eseguire il crafting.",
	L"L'item non può essere prodotto.",
	L"La certificazione HackShield è fallita.",
	L"A causa di un aggiornamento di HackShield è necessario riavviare il gioco.",
	L"La verifica di HackShield è fallita.",
	L"Il coupon è già stato utilizzato oppure il numero di coupon non è corretto. È possibile utilizzare solamente un coupon per account.",
	L"Inserisci il codice di 30 caratteri riportato nel coupon.",
	L"Questo coupon è già stato riscosso.",
	L"Questo coupon non è più valido.",
	L"Il numero di coupon non è valido.",
	L"Questo coupon può essere riscosso solamente una volta per account.",
	L"Non è stato possibile riscuotere il coupon.",
	L"Non hai aspettato abbastanza giorni per poterlo ricomprare.",
	L"La lista degli item non può essere visualizzata.",
	L"Le informazioni dell'item sono errate.",
	L"Non hai abbastanza spazio nell'inventario.",
	L"Non si è potuto selezionare l'item acquistato nello Shop.",
	L"Non è stato possibile consultare il resto.",
	L"Non è stata trovata alcuna informazione sul membro del gruppo.",
	L"Questo account è stato bloccato.",
	L"Non puoi inserire nell'inventario gli item di altri personaggi.",
	L"Sei già in possesso di questo item.",
	L"Attendi un momento. L'item sta per essere caricato.",
	L"La dimensiona media del campo d'immagine (frame) non è corretta.",
	L"Questo giocatore non esiste.",
	L"Questo non è l'oggetto in grado di cambiare il nickname.",
	L"Questo nickname è già in uso.",
	L"Nickname attualmente non utilizzabile!",
	L"Impossibile attualizzare il nickname.",
	L"Questo nickname non è sicuro.",
	L"La lunghezza di questo nickname non è sicura.",
	L"Non è stato possibile modificare il nickname.",
	L"Lo Stand non è stato creato.",
	L"Lo Stand può essere creato solamente nella Piazza del Villaggio.",
	L"Lo Stand non può essere visualizzato. Non sono state trovate informazioni sul proprietario.",
	L"Lo Stand è sovraccarico. Riprova più tardi.",
	L"Apertura dello Stand non riuscita.",
	L"La quantità di item selezionata per la vendita non corrisponde con i dati.",
	L"L'item è già stato registrato come venduto.",
	L"Non puoi registrare la merce a Stand altrui.",
	L"Sono stati inseriti più item di quanti possano essere venduti.",
	L"Non possiedi abbastanza denaro per aprire uno Stand.",
	L"La creazione dello Stand non è stata ancora completata.",
	L"Non hai ancora lasciato lo Shop.",
	L"Hai scelto di acquistare più item di quanti siano disponibili alla vendita.",
	L"L'item che vuoi acquistare non esiste.",
	L"Non hai abbastanza ED per comprare questo item.",
	L"Non hai abbastanza spazio nell'inventario per comprare qualcosa.",
	L"Non è possibile concludere il commercio perché il produttore non è stato trovato.",
	L"Non è possibile aprire uno Stand durante il commercio.",
	L"Lo Stand è già aperto.",
	L"Hai raggiunto la quota massima di ED.",
	L"Hai raggiunto la quota massima di ED che puoi acquistare.",
	L"Le informazioni degli item che vuoi acquistare sono errate.",
	L"L'item selezionato non compare nell'inventario.",
	L"Questo item non può essere scomposto.",
	L"La scomposizione dell'item è fallita. Prova di nuovo.",
	L"Puoi scomporre solamente il tuo equipaggiamento e i tuoi accessori.",
	L"Non può essere frammentato.",
	L"L'item non è stato creato.",
	L"Non c'è abbastanza spazio nell'inventario,\nper frammentare l'item.",
	L"Gli item con una scadenza non possono essere separati.",
	L"L'item che desideri migliorare non si trova nell'inventario.",
	L"Non esistono dati sugli item.",
	L"Solo armi e armature per la difesa possono essere migliorate.",
	L"L'item non può essere migliorato.",
	L"Non può più essere migliorato.",
	L"Nessuna Pietra per l'upgrade disponibile!",
	L"Impossibile eseguire l'upgrade.",
	L"Non hai abbastanza ED per l'upgrade.",
	L"Per procedere all'upgrade devi prima riporre l'item.",
	L"Nessuna Pietra fluorescente presente nell'inventario.",
	L"La Pietra fluorescente non può essere utilizzata.",
	L"Dal livello di upgrade 10 non è più possibile utilizzare la Pietra fluorescente.",
	L"Non è possibile applicare un upgrade per gli item che non puoi utilizzare.",
	L"L'upgrade è fallito.",
	L"L'item da riparare non si trova nell'inventario.",
	L"Non esistono dati sugli item.",
	L"L'item non può essere riparato.",
	L"Riparazione possibile solo per gli item che non puoi utilizzare.",
	L"Non ci sono abbastanza Pietre rigeneranti disponibili.",
	L"Non puoi riparare gli oggetti che indossi.",
	L"Item le cui particolarità sono disattivate non possono essere utilizzati.",
	L"Upgrade terminato con successo.",
	L"Nessuna modifica.",
	L"Ridotto di un grado.",
	L"Resettare il grado di upgrade.",
	L"L'item non può essere utilizzato.",
	L"L'item non è disponibile nell'inventario.",
	L"Non esistono dati sugli item.",
	L"La tassa è troppo alta.",
	L"L'arricchimento è possibile solo per armi e armature.",
	L"Nel tuo equipaggiamento non esistono informazioni sulla Pietra magica.",
	L"Nessuna Pietra magica disponibile nell'inventario.",
	L"Impossibile applicare l'arricchimento.",
	L"La Pietra magica si trova già nell'arricchimento.",
	L"La Pietra magica è stata tolta dall'arricchimento.",
	L"Non esistono opzioni d'arricchimento.",
	L"Questo nickname non esiste.",
	L"Non puoi proporre te stesso.",
	L"Non c'è nessuno che possa ricevere la ricompensa.",
	L"Il file privato che dovrebbe essere cancellato non si trova nella banca dati.",
	L"La lista degli allievi non può essere visualizzata.",
	L"Le informazioni non possono essere visualizzate. Il livello è troppo basso.",
	L"Il tuo livello non è abbastanza alto per accettare degli allievi.",
	L"Possono essere inseriti al massimo 3 allievi.",
	L"Ha già un maestro.",
	L"È già iscritto come allievo.",
	L"La merce che intendi acquistare è difettosa.",
	L"La merce non può essere acquistata.",
	L"Il pagamento è già stato effettuato.",
	L"La quantità massima di merce è stata superata.",
	L"Hai superato la quantità massima di merce che può essere acquistata.",
	L"Questa merce non può ancora essere ricomprata.",
	L"Nessun carrello disponibile.",
	L"L'utilizzo del gioco è limitato.",
	L"La quantità di merce è limitata. La merce non può essere acquistata.",
	L"Il numero delle ordinazioni è limitato.",
	L"Al momento la merce non può essere ancora riacquistata.",
	L"Non è possibile regalare la merce.",
	L"La quantità dell'ordine è limitata.",
	L"In questo momento l'altro giocatore non può accettare la merce.",
	L"Questo giocatore è bloccato.",
	L"Non è stata trovata alcuna informazione sul giocatore.",
	L"Credito insufficiente.",
	L"Verifica del sistema.",
	L"Hai raggiunto il numero massimo di Pietre rianimanti.",
	L"Non è possibile aggiungere ulteriori slot all'inventario.",
	L"Non puoi regalare qualcosa a te stesso.",
	L"I dati d'accesso sono incorretti.",
	L"Questo nickname non esiste.",
	L"Non si può regalare nulla ai giocatori con ID di prova.",
	L"La quantità di merce regalata è stata superata.",
	L"Digita la password.",
	L"Non è stato possibile verificare l'account.",
	L"Non è possibile regalare la merce.",
	L"I giocatori sotto i 14 anni non possono utilizzare questa funzione.",
	L"L'item non può essere acquistato.\nMassimo 9 Slot personaggi concessi.",
	L"Non è stato possibile ampliare lo slot del personaggio.",
	L"Questa funzione è già in uso.",
	L"Questa skill non esiste.",
	L"Non esiste l'item per il reset di una skill.",
	L"L'item per il reset di una skill non è stato eliminato dalla banca dati.",
	L"È sorto un problema nella banca dati durante il reset della skill.",
	L"La skill non può essere resettata.",
	L"La skill che si trova nello slot di scelta rapida non può essere resettata.",
	L"Questo item non può essere annotato.",
	L"Non puoi inserire altri prodotti nel carrello.",
	L"In qualità di tester non puoi usare questa funzione.",
	L"Giocatori con ID di prova non possono consigliare il gioco ad altri.",
	L"Hai raggiunto il massimo livello per giocatori con ID di prova. Se desideri proseguire accedi con un ID normale.",
	L"Giocatori con ID di prova non possono essere inseriti nella Lista di amici.",
	L"Questo utente non è stato inserito nella Lista di hacking.",
	L"La banca dati non ha ancora attualizzato i dati d'approvazione per l'hacking.",
	L"Non hai ancora confermato la segnalazione di giocatori che fanno hacking.",
	L"L'item non si trova nell'inventario.",
	L"Non è possibile migliorare queste caratteristiche.",
	L"Le caratteristiche dello slot sono già state migliorate.",
	L"Questo slot è già stato svuotato.",
	L"Non hai abbastanza ED per l'incanto degli attributi!",
	L"Non hai abbastanza Frammenti di Eldrit per un incantesimo.",
	L"Informazioni dell'item errate.",
	L"L'incanto degli attributi è possibile solo su armi e armature.",
	L"L'item selezionato non può essere smontato.",
	L"Gli Apparecchi per l'analisi disponibili non sono sufficienti!",
	L"Non c'è abbastanza spazio nell'inventario\nper scomporre questo item.",
	L"L'item che hai scelto non può essere riposto.",
	L"La creazione dell'item è fallita.",
	L"La posta in entrata non è stata aggiornata.",
	L"L'item selezionato non può essere allegato alla mail.",
	L"La quantità di ED selezionata non può essere inviata tramite Mail.",
	L"Non si è potuto inviare la mail.",
	L"La mail non esiste.",
	L"Non c'è abbastanza spazio nell'inventario per spostare l'oggetto allegato. Crea un po' di spazio e prova di nuovo.",
	L"Non si è potuto ricevere l'item annesso.",
	L"Hai provato ad aggiungere un item che non esiste.",
	L"Solo gli item riparati completamente possono essere aggiunti.",
	L"Questo nickname non esiste.",
	L"Non puoi mandare messaggi a te stesso!",
	L"Non hai abbastanza ED per inviare un messaggio.",
	L"L'altro giocatore non ha abbastanza spazio nella sua casella di posta in entrata e non può ricevere alcun messaggio.",
	L"Hai selezionato un messaggio cancellato.",
	L"Il giocatore ha rifiutato il tuo messaggio.",
	L"Gli item indossati dal tuo personaggio non possono essere spediti nei messaggi.",
	L"Non si possono inviare messaggi ai giocatori con ID di prova.",
	L"Questo nickname non esiste.",
	L"Questo nickname è già stato inserito nella Lista di blocco.",
	L"L'inserimento nella Lista di blocco è fallito.",
	L"Il nickname è stato già cancellato.",
	L"Non è stato possibile eliminare il giocatore dalla Lista di blocco.",
	L"Non sei in possesso di questo titolo.",
	L"Sei già in possesso di questo titolo.",
	L"La validità di questo titolo è scaduta.",
	L"Questo titolo non esiste.",
	L"Il titolo non è stato conquistato.",
	L"Sei già in possesso del titolo.",
	L"L'item non può essere utilizzato.",
	L"L'item non esiste.",
	L"Il tuo livello è troppo basso per questo item.",
	L"L'item non può essere utilizzato nell'inventario.",
	L"L'item non si trova nell'inventario.",
	L"Questo item non è concesso.",
	L"Questo item non è ammesso.",
	L"L'upgrade è fallito.",
	L"L'item non può essere scambiato.",
	L"L'item non si trova nell'inventario.",
	L"Non puoi vendere questo item.",
	L"Gli item per lo scambio non sono stati creati.",
	L"Abbandoni questo luogo per entrare in un'altra zona.",
	L"Abbandoni questa zona per entrare in una stanza.",
	L"Il sistema ha elaborato il tuo ritiro.",
	L"Non puoi entrare nel Villaggio.",
	L"Non hai potuto abbandonare il Villaggio.",
	L"Non è possibile visualizzare la Lista dei giocatori.",
	L"Il tuo livello è troppo basso per entrare nel Villaggio.",
	L"Non hai ancora completato il Dungeon per l'accesso al Villaggio.",
	L"Questo canale non esiste.",
	L"Il cambio di canale ha funzionato. La connessione verrà chiusa.",
	L"Non è stato possibile registrarsi al cambio del canale.",
	L"Non ti sei registrato per un cambio di canale.",
	L"Ti trovi già nel canale dove vorresti andare.",
	L"Il numero massimo di membri è stato raggiunto. Nessun cambio possibile.",
	L"Il cambio di canale è possibile solo quando ti trovi in un villaggio o nel suo circondario.",
	L"Ritenta il cambio di canale più tardi.",
	L"Non puoi utilizzare questa funzione con questo giocatore.",
	L"Non hai ancora scelto il personaggio.",
	L"Questo amico non è in linea.",
	L"Status errato.",
	L"La banca dati non ha aggiornato l'Item-drop dell'evento.",
	L"Hai già ricevuto la ricompensa dell'evento.",
	L"Questo giocatore è già un tuo amico.",
	L"Lo stato del personaggio dell'amico non è valido.",
	L"Questo giocatore non ti ha inserito come amico.",
	L"Questo giocatore non è un tuo amico.",
	L"Questo gruppo non esiste.",
	L"Il messaggio è troppo lungo.",
	L"Questo è lo stesso gruppo del quale desideri far parte.",
	L"Non possono essere creati ulteriori gruppi.",
	L"Questo gruppo esiste già.",
	L"Questo nome del gruppo è già stato assegnato.",
	L"Il tuo allievo non si connette da 7 giorni. La formazione sarà interrotta.",
	L"L'allievo è salito di livello. La formazione è conclusa.",
	L"Il personaggio è stato cancellato. La formazione verrà terminata.",
	L"La formazione è stata interrotta.",
	L"Non hai potuto terminare la formazione.",
	L"È subentrato un errore nella banca dati riguardante le funzioni d'amicizia.",
	L"Il nome del gruppo è troppo lungo.",
	L"La tua Lista di amici è piena. L'invito non è stato inviato.",
	L"Non è possibile inviare richieste d'amicizia tra i personaggi di uno stesso account.",
	L"La Lista di amici dell'altro giocatore è piena. La richiesta d'amicizia non può essere inviata.",
	L"La tua richiesta di amicizia è stata rifiutata.",
	L"Ricerca fallita.",
	L"Non puoi accedere al canale PvP.",
	L"Nel PvP il gioco comincia solo quando tutti i posti sono occupati.",
	L"L'oggetto è troppo lungo.",
	L"Il messaggio è troppo lungo.",
	L"Il giocatore invitato non può entrare nel Dungeon.",
	L"Il sigillo è già stato tolto.",
	L"Il sigillo della skill non è stato tolto.",
	L"Non hai la classe adatta per questo oggetto!",
	L"Hai già attivato questa skill!",
	L"Nell'inventario si trova già un item con le stesse funzioni. Non è stato possibile acquistare la merce.",
	L"I giocatori con l'ID di prova non possono essere invitati nello Spazio-tempo di Henir.",
	L"Il tipo di certificazione non è valido.",
	L"Gli item nella Banca non possono essere scomposti.",
	L"Non puoi arricchire gli item custoditi in Banca.",
	L"Questa funzione non può essere utilizzata in Banca.",
	L"Non si può aumentare ulteriormente il numero degli slot in Banca.",
	L"Non è possibile acquistare più di una Tessera per la Banca.",
	L"Non è possibile comprare la Tessera per la Banca.",
	L"Se sei in possesso di un Certificato di garanzia di Luriel puoi comprare una Tessera Platinum. Usa il Certificato di garanzia di Luriel.",
	L"La password non esiste.",
	L"La password non può essere rinnovata.",
	L"Il nome utente o la password non sono corretti.",
	L"C'è stato un problema di sistema durante il processo di autenticazione.",
	L"L'item non esiste.",
	L"Non sono disponibili alcune informazioni sull'item.",
	L"Questo tipo di item non può essere sigillato.",
	L"Gli item riposti non possono essere sigillati.",
	L"L'item è già sigillato.",
	L"Un item non riparato non può essere sigillato.",
	L"Gli item con una scadenza non possono essere sigillati.",
	L"Gli item distrutti non possono essere sigillati.",
	L"Gli oggetti che puoi commerciare non possono essere sigillati.",
	L"Non è possibile sigillare oltre.",
	L"Le informazioni della pergamena per sigillare non sono corrette.",
	L"Sigillatura fallita.",
	L"Non hai abbastanza pergamene per sigillare!",
	L"Non è possibile togliere il sigillo agli item riposti.",
	L"A questo item è già stato tolto il sigillo.",
	L"Rimozione del sigillo fallita.",
	L"L'update della banca dati delle informazioni sul sigillo è fallito.",
	L"Gli item sigillati non possono essere migliorati.",
	L"Errore di sistema durante la richiesta di El-Coins.",
	L"Questo account ha un margine d'attività ridotto.",
	L"Questo account non esiste.",
	L"L'account è errato.",
	L"Il numero di coupon non è valido.",
	L"Questo coupon è già stato riscosso.",
	L"Questo tipo di coupon può essere utilizzato soltanto una volta.",
	L"Il coupon è scaduto.",
	L"Durante la riscossione del coupon si è verificato un errore di sistema.",
	L"El-Coins insufficienti.",
	L"Durante l'acquisto si è verificato un errore di sistema.",
	L"L'acquisto è possibile solo dal livello 15.",
	L"Sei già iscritto ad un'altra gilda.",
	L"Questo nome della gilda viene già utilizzato.",
	L"L'item per la fondazione della gilda non si trova nell'inventario.",
	L"L'item per la fondazione della gilda non è valido.",
	L"La fondazione della gilda non ha funzionato.",
	L"La registrazione come Maestro della gilda è fallita.",
	L"Non sono state trovate informazioni sulla gilda.",
	L"Impossibile invitare alla gilda.",
	L"Questo giocatore è offline.",
	L"I giocatori con ID di prova non possono essere invitati in una gilda.",
	L"Questo giocatore è già stato invitato ad entrare nella gilda.",
	L"Un'altra gilda ha già invitato questo giocatore.",
	L"Non sei autorizzato ad invitare qualcuno nella gilda.",
	L"Non puoi aumentare il numero di membri della gilda. Per fare ciò devi procurarti un item con cui poter creare altri posti per nuovi membri.",
	L"Il giocatore invitato è già un membro della gilda.",
	L"Questo giocatore fa già parte di una gilda.",
	L"Non puoi visualizzare la lista delle gilde.",
	L"L'item che vuoi acquistare con il coupon non è valido.",
	L"Il giocatore ha rifiutato l'invito a unirsi alla gilda.",
	L"L'iscrizione alla gilda è fallito.",
	L"Non appartiene ad alcuna gilda.",
	L"Non sei autorizzato a cambiare il rango del membro della gilda.",
	L"Il rango del membro della gilda non è stato modificato.",
	L"Le modifiche al messaggio della gilda possono essere effettuate solamente dal Maestro della gilda e dall'Amministratore della gilda.",
	L"La modifica del messaggio della gilda è fallita.",
	L"Non sei autorizzato a espellere un membro dalla gilda.",
	L"Il Maestro della gilda non può abbandonare la gilda.",
	L"Abbandono della gilda non riuscito.",
	L"La lunghezza del saluto della gilda è limitato.",
	L"Non sei autorizzato a modificare il saluto della gilda.",
	L"Le modifiche al saluto della gilda non sono state effettuate.",
	L"Solo il Maestro della gilda è autorizzato a sciogliere la gilda.",
	L"La gilda non può essere sciolta. Ci sono ancora dei membri iscritti.",
	L"Non è stato possibile sciogliere la gilda.",
	L"Il rango di classe è già stato modificato.",
	L"Ci sono già degli Amministratori della gilda.\nCambia il rango dell'Amministratore della gilda,\nper nominarne uno nuovo.",
	L"Il Maestro della gilda non può eliminare il suo personaggio. Consegna il titolo di Maestro della gilda ad un altro membro.",
	L"Non puoi cambiare il tuo stesso rango di classe.",
	L"Non puoi comprare un Permesso Fondazione gilda perché sei già membro di una gilda.",
	L"Possiedi già un Permesso fondazione gilda.",
	L"Non è stato possibile aumentare il numero dei membri.",
	L"Solamente il Maestro e l'Amministratore della gilda possono utilizzare la Carta espansione.",
	L"Non si possono invitare altri giocatori a far parte della gilda.",
	L"Questa funzione non può essere utilizzata durante il commercio.",
	L"Non puoi andare in questa zona.",
	L"Questo nome della gilda non sarà disponibile per i prossimi 7 giorni.",
	L"Questo è il numero massimo di EXP disponibili.",
	L"Per poter acquistare l'item devi prima risolvere la quest correlata.",
	L"Il nome della gilda è troppo lungo.",
	L"Non hai abbastanza ED per rimuovere gli attributi.",
	L"Puoi comprare questo item solo a partire dal livello 35.",
	L"게임을 종료하고 빈펀 계정으로 업그레이드 하시기 바랍니다. 빈펀 사이트는 tw.beanfun.gamania.com 입니다.",
	L"이 계정은 이미 빈펀 계정으로 업그레이드 된 계정입니다. 빈펀 프로그램으로 접속해주세요.",
	L"Non puoi comprare altri item al momento. Il tuo inventario temporaneo è pieno.",
	L"I GSP possono essere utilizzati solamente dal Maestro della gilda.",
	L"Questa skill della gilda è stata allenata fino al suo livello più alto.",
	L"Non esistono informazioni su questa skill della gilda.",
	L"La precedente skill della gilda non è stata allenata fino al suo livello più alto.",
	L"Non hai utilizzato abbastanza Skill Point.",
	L"GSP insufficienti.",
	L"L'apprendimento di questa skill della gilda è fallito.",
	L"Le skill della gilda possono essere resettate solamente dal Maestro della gilda.",
	L"Hai bisogno del \"Flauto medievale della dimenticanza\"!",
	L"La skill della gilda non può essere resettata.",
	L"La restituzione della skill della gilda non ha funzionato.",
	L"Solo il Maestro della gilda può resettare le skill della gilda.",
	L"Il \"Flauto medievale della dimenticanza\" non si trova nell'inventario.",
	L"È impossibile resettare la skill della gilda.",
	L"Il reset della skill della gilda è fallito.",
	L"L'utilizzo è concesso solamente al Maestro della gilda.",
	L"Non hai ricevuto alcun Skill Point della gilda con scadenza.",
	L"L'item benedetto della conoscenza è già stato utilizzato.",
	L"Non è ancora possibile ricevere la ricompensa dell'evento.",
	L"Non hai abbastanza spazio nell'inventario per ricevere la ricompensa dell'evento.",
	L"Errore durante la consegna della ricompensa dell'evento.",
	L"Questa non è la modalità item.",
	L"C'è ancora un Item-drop disponibile.",
	L"L'Item-drop del PvP non è stato raccolto.",
	L"Puoi creare una classe dopo l'utilizzo della carta del personaggio.",
	L"Questo account non può partecipare all'evento.",
	L"Solamente il Maestro e l'Amministratore della gilda possono utilizzare questa funzione.",
	L"PC방 전용 아이템은 이용할 수 없는 기능입니다.",
	L"L'annuncio della gilda non esiste.",
	L"Il testo è troppo lungo.",
	L"La registrazione del periodo dell'annuncio non è valida.",
	L"Non hai abbastanza ED per registrare l'annuncio.",
	L"Un annuncio è già stato registrato.",
	L"La registrazione dell'annuncio della gilda non ha funzionato.",
	L"A causa delle troppe richieste, al momento non è possibile alcuna iscrizione.",
	L"La richiesta d'iscrizione alla gilda non ha funzionato.",
	L"Hai già inviato una richiesta di iscrizione.",
	L"Non sono state trovate informazioni sulla richiesta di iscrizione.",
	L"La accettazione dell'iscrizione alla gilda non ha funzionato.",
	L"L'eliminazione della richiesta di iscrizione alla gilda non ha funzionato.",
	L"Con un annuncio valido per un certo periodo non è possibile richiedere alcuna iscrizione.",
	L"Non sei autorizzato a consultare la lista delle richieste di iscrizione alla gilda.",
	L"Non hai aperto il lucchetto.",
	L"Questo account di gioco è stato bloccato.",
	L"Le quests per la Stanza PC possono essere accettate solamente negli Internet cafè.",
	L"Le quest per la Stanza PC possono essere terminate solamente negli Internet Cafè.",
	L"Sei stato allontanato dalla stanza perché sospettato di hacking.",
	L"Siccome l'opzione \"impedire inviti alla gilda\" è attiva non puoi inviare alcuna richiesta di iscrizione.",
	L"Non puoi richiedere l'iscrizione alla gilda perché ci sono state troppe richieste.",
	L"Questa non è la quest attualmente in corso.",
	L"Il limite d'acquisto per l'item in questione è stato raggiunto.",
	L"Gli El-Coins sono disattivati. Cambia le impostazioni sulla pagina internet sotto \"Informazioni personali\" nel menu \"Sicurezza Cash\".",
	L"Il controllo dello status attuale è già stato effettuato.",
	L"La richiesta alla banca dati per l'aumento di WebPoint non ha funzionato.",
	L"Il controllo dello status non ha funzionato.",
	L"Hai dovuto abbandonare il gruppo a causa dell'iscrizione simultanea a più gruppi.",
	L"Caricamento dello status di gruppo in corso.",
	L"Elimina lista degli item",
	L"Aggiungi lista degli item",
	L"Modifica lista degli item",
	L"La selezione della categoria è errata.",
	L"La ricerca non ha prodotto alcun risultato.",
	L"La forza di volontà del giocatore invitato non è sufficiente.",
	L"Prova a effettuare la ricerca più tardi.",
	L"In questo negozio la vendita è stata conclusa.",
	L"Il giocatore non è nello status di acquisto.",
	L"La creazione di una stanza non ha funzionato.",
	L"L'item non esiste.",
	L"Questa pagina non esiste.",
	L"Questa nota è già stata registrata.",
	L"La nota non è stata registrata.",
	L"Non possiedi alcuna Agenda della tecnica.",
	L"Non hai potuto aggiungere l'Agenda della tecnica.",
	L"Sei già in possesso di questa Agenda della tecnica.",
	L"Devi raggiungere il livello 20 per poter comprare questo item.",
	L"Non si può commerciare con giocatori di altri server.",
	L"Non si possono utilizzare Stand che si trovano su altri server.",
	L"Non puoi invitare nella gilda giocatori di altri server.",
	L"Non puoi registrare come allievi i giocatori di altri server.",
	L"Non puoi richiedere l'amicizia di giocatori che si trovano su altri server.",
	L"Non puoi giocare nella modalità sfida dello Spazio-tempo di Henir con giocatori di altri server.",
	L"Blocco dell'accesso per sospetto hacking.",
	L"[홍콩] 해당 직업으로는 전직을 할 수 없습니다.",
	L"Il numero di item che desideri gettare non è valido.",
	L"La creazione del Pet non è riuscita.",
	L"Questo nome è già in uso.",
	L"La lunghezza del nome è limitata a 12 caratteri.",
	L"Il Pet è in fase di creazione.",
	L"Non è stato possibile chiamare il Pet.",
	L"Il Pet non può essere creato in questo luogo.",
	L"Hai già chiamato un Pet.",
	L"Questo Pet è già stato chiamato.",
	L"Non è stato possibile mandare via il Pet.",
	L"Non è stato possibile eseguire il comando.",
	L"Il tuo pet è sazio. Non può mangiare nient'altro.",
	L"Non è stato possibile alimentare il Pet.",
	L"Il tuo pet sta crescendo. Ora mangia solo Frutti e Semi dell'Albero di El.",
	L"È stato già salvato.",
	L"Il prossimo livello di evoluzione non è ancora disponibile.",
	L"L'evoluzione successiva è possibile solo quando l'affiatamento è del 100%.",
	L"Il Pet non può utilizzare questo oggetto.",
	L"Il livello di cibo è troppo basso.",
	L"I dati d'accesso sono incorretti.",
	L"I dati d'accesso sono incorretti.",
	L"L'account non è stato ancora validato.",
	L"Il Pet non può mangiare questo cibo.",
	L"L'utente è occupato.",
	L"매트릭스 카드가 바인딩되어 있습니다.",
	L"토큰 패스워드 에러",
	L"키 에러",
	L"계정 정보가 수정 과정에 있습니다. 의문 사항이 있으시면 서비스 센터로 연락 바랍니다.",
	L"자이언트 패스워드 보안이 바인딩 해제 상태에 있습니다. 의문사항이 있으시면 서비스 센터로 연락 바랍니다.",
	L"GM키에란",
	L"GM리엘",
	L"[Mittente sconosciuto]",
	L"지금은 청약철회 기능을 이용 하실 수 없습니다.",
	L"청약철회 가능 개수보다 요청 갯수가 커서 청약철회를 실패하였습니다.",
	L"구매한지 7일이 초과된 상품으로 청약철회가 불가능 합니다.",
	L"패키지 중 일부 상품을 수령하여 청약철회가 불가능 합니다.",
	L"상품 가격이 0원으로 청약철회가 불가능한 상품 입니다.",
	L"중복된 RequestID입니다.",
	L"Nessuna informazione d'acquisto disponibile per questa merce.",
	L"Nessuna informazione disponibile per questa merce.",
	L"청약철회가 불가능한 상품 입니다.",
	L"선물 받은 상품이어서 청약철회가 불가능 합니다.",
	L"Gli item con un limite di tempo non possono essere gettati via.",
	L"Gli item che non possono essere venduti non possono nemmeno essere gettati via.",
	L"1 EL coins 이벤트 구매 제한을 초과 하여 더 이상 구매 할 수 없습니다. ",
	L"Il tuo livello è troppo basso per questo item.",
	L"Dal livello di upgrade 11 si possono più utilizzare le Pietre fluorescenti.",
	L"Non puoi accettare questa quest perché hai già ricevuto la ricompensa.",
	L"Non puoi accettare la quest perché non hai abbastanza spazio nell'inventario per la ricompensa.",
	L"L'utilizzo della Pietra magica non ha funzionato.",
	L"Questa funzione non è attualmente disponibile.\nCi scusiamo per il disagio.",
	L"L'accesso per questo IP è limitato.",
	L"La funzione chat è stata limitata.",
	L"La funzione di commercio è stata limitata.",
	L"Non è possibile cominciare il gioco perché l'item non esiste.",
	L"Il gioco sembra essere disturbato da un altro programma.",
	L"해당 유저가 존재하지 않습니다.",
	L"잔액이 부족합니다.",
	L"존재하지 않는 아이템 카드입니다.",
	L"해당 카드는 해당 구역에서 사용이 불가능합니다.",
	L"이미 사용한 아이템 카드입니다.",
	L"잘못된 전용 카드 ID입니다.",
	L"잘못된 전용 카드 패스워드입니다.",
	L"DB 에러",
	L"Non puoi inviar alcun messaggio perché le tue azioni sono state limitate.",
	L"Non hai aperto nessuno Stand per la vendita perché il tuo commercio ha subito delle limitazioni.",
	L"Non puoi  richiamare il tuo Stand per la vendita perché il tuo commercio ha subito delle limitazioni.",
	L"Non puoi cercare delle merci perché il tuo commercio ha subito delle limitazioni.",
	L"Non puoi accedere al Mercato perché il tuo commercio ha subito delle limitazioni.",
	L"캐시 인벤토리에 아이템이 존재합니다.(HK 이벤트에 사용)",
	L"Sono necessari più di due membri nel gruppo.",
	L"Il Dungeon è chiuso e non è possibile effettuare l'accesso.",
	L"Non puoi accedere al Dungeon Mondiale con altri giocatori di questo server.",
	L"Il log per il controllo della posta ha lo stesso prezzo.",
	L"Il log per il controllo delle vendite ha lo stesso prezzo.",
	L"Il log per il controllo della posta è fallito.",
	L"Il log per il controllo delle vendite è fallito.",
	L"Non puoi disattivare l'Agente perché ci sono ancora delle merci in fase di vendita.",
	L"L'Agente non è attiva",
	L"Non puoi interrompere il processo di acquisto.",
	L"Questa è una vendita privata: l'acquisto di item non è possibile.",
	L"Non puoi aprire lo Stand di vendita perché l'Agente non è attiva.",
	L"Hai infranto il regolamento e il tuo Stand verrà chiuso.",
	L"Non puoi disattivare l'Agente.",
	L"Unregisted User.",
	L"It is already canceled.",
	L"Invalid coupon number.",
	L"This coupon can not be canceled.",
	L"The used user information and cancel the requested user information does not match.",
	L"The issued cash by coupons  already had used . so can not be canceled.",
	L"requested price should be equal to billing items price.",
	L"The balance short.",
	L"Billing account that is unavailable.",
	L"You can not register any more today.",
	L"This coupon can not verify the information.",
	L"Coupon is already used.",
	L"Coupon use is stopped.",
	L"Coupon is expired.",
	L"Coupon is not available in the game.",
	L"Issued to certain customers who can use coupons, you do not have permission.",
	L"Buying is a restricted user.",
	L"Your use is limited to the payment service.",
	L"Your use is limited to the purchase service.",
	L"User cannot be verified.",
	L"Registration has exceeded the number of coupons available.",
	L"Unable to login due to IP restriction.",
	L"The coupon code has already been redeemed.",
	L"You cannot purchase the item at the moment. Your account have reached the daily limit for purchasing the item.",
	L"Hai inserito una password errata per due volte consecutive, per questo non puoi più effettuare il login.",
	L"Se vuoi vendere delle merci tramite l'Agente devi sottoscrivere un contratto.",
	L"I PIN che hai inserito non sono identici.",
	L"Hai inserito un PIN errato per 10 volte.\nCliccando sul pulsante \"Conferma\" la connessione verrà interrotta.\nDovrai effettuare il login al sito per resettare l'inserimento.",
	L"La creazione del PIN non è riuscita.",
	L"Il PIN è errato.",
	L"Il nome dell'item è troppo lungo.",
	L"Lo Stand di vendita dell'Agente è stato concluso.\nDopo aver ottenuto le merci potrai aprire un nuovo Stand di vendita.",
	L"L'Agente sta vendendo queste merci al momento.\nSei vuoi ottenere il denaro ricavato dalla vendita di tali merci\ndevi prima concludere lo Stand di vendita dell'Agente.",
	L"La query DB per il contratto con l'Agente di vendita è fallita.",
	L"Non è stato possibile attivare l'Agente.",
	L"Non è stato possibile inserire le merci nello Stand di vendita dell'Agente.",
	L"Può essere utilizzato solo dal committente dell'Agente.",
	L"Questi item non possono essere consegnate all'Agente.",
	L"Non puoi riprendere un item che si trova in fase di vendita.",
	L"Hai già ottenuto questo oggetto.",
	L"Hai raggiunto l'ammontare massimo di ED consentiti e non puoi prendere altre merci.",
	L"Non hai più spazio nel tuo inventario.",
	L"Non hai alcun item.",
	L"Non puoi comprare le stesse merci contemporaneamente.",
	L"Il tuo livello è troppo basso.\nNon puoi effettuare delle richieste ai gruppi.",
	L"Non puoi comprare delle merci perché l'Agente è ancora attiva.",
	L"Esistono ancora degli item che devi riprendere prima di poterne vendere degli altri.",
	L"Sono state vendute tutte le merci. Per questo motivo, l'Agente chiuderà lo Stand di vendita.",
	L"Hai già accettato questa quest e hai ottenuto la ricompensa. Non puoi accettarla di nuovo.",
	L"Non puoi accettare la quest perché non hai più spazio nell'inventario.",
	L"Non è stato possibile modificare il livello minimo del gruppo.",
	L"Non puoi aprire uno Standi di vendita perché l'Agente ha venduto tutta la merce.",
	L"(TW/HK)강화 보조 아이템 사용 불가",
	L"(TW/HK)강화 보조 아이템이 없습니다.",
	L"(TW/HK)파괴 방지 아이템 사용 불가",
	L"(TW/HK)파괴 방지 아이템이 없습니다.",
	L"Il tuo livello è troppo basso.\nScegli un altro Dungeon o rimuovi la limitazione di livello.",
	L"Il tuo livello è troppo basso.\nNon puoi imporre una limitazione di livello.",
	L"Il livello del giocatore invitato è troppo basso.",
	L"Il tuo livello è troppo basso.\nScegli un Dungeon corrispondente al tuo livello.",
	L"Il PIN non deve contenere due cifre identiche una di seguito all'altra.\n(0000, 1111, 999999, etc.)",
	L"Non utilizzare cifre progressive per il tuo PIN.\n(1234, 9876, 123456, etc.)",
	L"La cancellazione del secondo PIN-Pad è fallita.",
	L"Il secondo PIN-Pad non viene utilizzato.",
	L"Il nuovo PIN deve essere diverso da quello vecchio.",
	L"Questo item non è in vendita nello Shop.",
	L"L'abbinamento è stato interrotto a causa dell'inizio del PvP.",
	L"Un giocatore non può partecipare all'abbinamento per il PvP.",
	L"L'abbinamento è stato interrotto.",
	L"L'abbinamento è stato interrotto perché il membro del gruppo non ha partecipato al PvP.",
	L"L'abbinamento è stato portato a termine con successo. Sei stato cancellato dalla lista d'attesa.",
	L"Uno user ha interrotto l'iscrizione all'abbinamento ed è stato cancellato dalla lista d'attesa.",
	L"L'iscrizione all'abbinamento è stata interrotta perché un membro del gruppo è uscito.",
	L"L'abbinamento è già in corso.",
	L"I dati inerenti al membro del gruppo sono errati.",
	L"I dati inerenti alla modalità del PvP sono errati.",
	L"IL PvP è consentito solo a partire dal livello 10.",
	L"Puoi accedere a un gruppo per il PvP solo a partire dal livello 10.",
	L"Hai già modificato la modalità del PvP.",
	L"Non puoi passare a un gruppo per il PvP con quattro membri della gilda.",
	L"La modalità del PvP non può essere modificata.",
	L"La stanza del PvP non può essere modificata perché uno dei membri del gruppo non ha ancora raggiunto il livello 10.",
	L"Un membro del gruppo non può accedere alla stanza del PvP perché non ha ancora raggiunto il livello 10.",
	L"In un gruppo per il PvP possono essere invitati solo personaggi a partire dal livello 10.",
	L"Solo un personaggio a partire dal livello 10 può diventare fondatore di un gruppo per il PvP.",
	L"[CN]전환이 정상적으로 이루어지지 않았습니다. 다시 시도하여 주시기 바랍니다.",
	L"Non è stato possibile mettere in ordine gli item. Riprova più tardi.",
	L"Non ti sei iscritto all'abbinamento.",
	L"Ti trovi già all'interno di una stanza per il PvP.",
	L"Questa non è la stanza per il PvP.",
	L"La richiesta non è andata a buon fine.",
	L"Non puoi invitare uno user che si è iscritto alla fase di abbinamento.",
	L"Non puoi invitare uno user che si trova nell'abbinamento.",
	L"Il tuo rango è troppo basso per comprare questo item.",
	L"Durante l'abbinamento non si può fare la richiesta a un altro gruppo.",
	L"Durante l'abbinamento non puoi cambiare schieramento.",
	L"Durante l'abbinamento non puoi cambiare il canale di gioco.",
	L"Non è stato possibile autenticare l'ID.",
	L"Questo ID risulta loggato in più canali contemporaneamente.",
	L"Per oggi non puoi accettare altre quest random.",
	L"Non accetto questo contratto.",
	L"Si è verificato un errore nella visualizzazione degli SP.",
	L"Errore nell'inserimento degli SP.",
	L"Il nome desiderato è errato.",
	L"La verifica dei dati non è andata a buon fine.",
	L"죄송합니다. 캐쉬샵 점검으로 인해 이용하실 수 없습니다.",
	L"00시부터 06시까지 게임 접속이 제한됩니다.",
	L"Nessuna informazione disponibile.",
	L"Non puoi commerciare prima di essere stato registrato come avventuriero.",
	L"Non puoi mandare messaggi prima di essere stato registrato come avventuriero.",
	L"[CN]사용실패!",
	L"Hai abbandonato il campo di battaglia.",
	L"Può essere acquistato solo a partire dal livello 15.",
	L"ServerSN과 MachineID가 매칭되지 않는다.",
	L"MachineID와 ServerSN이 매칭되지 않는다.",
	L"DB에 존재 하지 않는 ServerSN이 있다.",
	L"DB에 존재 하지 않는 MachineID가 있다.",
	L"클라가 준 SN은 없는데 DB에는 MachineID에 해당하는 SN 존재.",
	L"제재된 SN입니다.",
	L"접속 제한된 ServerSN 입니다.",
	L"Con questo account non puoi accedere al test server.",
	L"Hai abbandonato automaticamente il gruppo a causa della fusione.",
	L"Non puoi comprare questo item perché hai già un Ampliamento degli slot di scelta rapida attivo a tempo indeterminato.",
	L"Questo item non può essere acquistato perché hai già un Ampliamento degli slot di scelta rapida attivo a tempo indeterminato.",
	L"[CN] 귀하의 계정이 정지되었습니다. 고객 센터에 문의하여 주십시요.",
	L"[CN] 비밀번호를 잘못 입력 하셨습니다. 다시 입력해 주십시요.",
	L"[CN] 해당 계정은 존재하지 않습니다.",
	L"[CN] 불명확인 시스템 에러",
	L"Hai già una Medaglia benedetta nell'inventario, quindi non puoi aprire il bauletto.",
	L"Il tuo livello è troppo basso per acquistare questo item.",
	L"Il tuo livello è troppo basso per ottenere questa merce.",
	L"La creazione del gruppo è fallita!",
	L"Non ci sono abbastanza membri nel gruppo.",
	L"I membri del gruppo che hai invitato stanno tardando a rispondere.",
	L"Questo articolo non è in vendita.",
	L"[JP] 한게임 빌링 오류로 구매할수 없습니다.",
	L"Gli item del sistema di condivisione Banca non possono essere inviati tramite e-mail.",
	L"Gli item del sistema di condivisione Banca non possono essere commerciati.",
	L"Questo item può essere acquistato solo a partire dal livello 20.",
	L"Solo i personaggi che appartengono a una gilda possono scambiarlo.",
	L"Può essere acquistato a partire dal livello 30.",
	L"Le richieste di accesso ai gruppi per il PvP sono possibili solo con la patch completa.",
	L"블랙리스트에 등록된 DLL 이 존재합니다.",
	L"Effettua nuovamente il login o ritenta più tardi.",
	L"Non puoi rifare il quiz oggi.",
	L"Errore sconosciuto",
	L"Durante una limitazione nel commercio non puoi acquistare alcun item.",
	L"Non può essere utilizzato durante una limitazione nel commercio.",
	L"Non puoi ampliare ulteriormente la barra degli slot di scelta rapida.",
	L"Il personaggio è stato già cancellato, oppure la cancellazione è avvenuta di recente.",
	L"La cancellazione del personaggio al momento non è possibile.",
	L"La cancellazione definitiva del personaggio al momento non è possibile.",
	L"Non è possibile cancellare definitivamente questo personaggio.",
	L"Non sarà possibile ricreare questo personaggio dopo averlo cancellato.",
	L"Il ripristino dei personaggi non è possibile in questo momento.",
	L"Sei pregato di ritentare più tardi.",
	L"Questo personaggio non esiste.",
	L"Non è stato possibile cancellare il personaggio.",
	L"Il cambio del nome del pet non è riuscito.",
	L"Il cambio del nome del pet è in corso.",
	L"Il gioco è stato interrotto.",
	L"Non sei il capo di una gilda.",
	L"I dati dell'item sono errati.",
	L"Il cambio del nome della gilda non è riuscito.",
	L"Operazione in corso...",
	L"Hai tentato di cancellare un item inesistente.",
	L"[TW] 낚시대를 장착하지 않았거나, 미끼가 없습니다.",
	L"[TW] 이미 사용중인 낚시터 입니다.",
	L"[TW] 낚시터에 문제가 있습니다. 다른 곳을 이용해 주세요.",
	L"[TW] 낚시 보상에 문제가 발생했습니다.",
	L"La cancellazione dell'item non è riuscita.",
	L"Solo il capo della gilda ha il diritto di cambiarne il nome.",
	L"펫이 있을 때만 사용이 가능합니다. 펫이 없을 경우 일주일 이내에 청약 철회를 하셔야 합니다.",
	L"Il tempo di lavorazione è scaduto e l'operazione è stata interrotta. Sei pregato di ritentare.",
	L"Il processo di cambio del nome della gilda è stato interrotto dallo user.",
	L"Non sei in grado di raggiungere tale luogo.",
	L"Ti trovi già in questo luogo.",
	L"Questo luogo è pieno, non puoi accedere.",
	L"Non puoi accedere a questo luogo perché in esso si trovano già molti gruppi.",
	L"L'accesso a questo luogo non è riuscito.",
	L"I dati relativi al luogo al quale vorresti accedere sono errati.",
	L"Durante l'accesso a questo luogo si è verificato un errore.",
	L"Nel luogo indicato non sono state trovate informazioni relative allo user.",
	L"L'inizio del gioco in un Dungeon mediante la creazione automatica di un gruppo non è riuscito.",
	L"L'inizio del gioco nel Dungeon non è riuscito.",
	L"In questo momento non puoi richiedere la creazione automatica di un gruppo.",
	L"Al momento non puoi eseguire la creazione automatica di un gruppo. Sei pregato di attendere un istante.",
	L"È già stata fatta una richiesta per la creazione automatica di un gruppo.",
	L"A causa di un'immissione errata la creazione automatica di un gruppo non è riuscita.",
	L"La richiesta come aspirante membro di un gruppo creato automaticamente non è andata a buon fine.",
	L"Non sei in grado di fare una richiesta per la creazione automatica di un gruppo.",
	L"Dato che esiste un solo membro per il gruppo, il gioco non può iniziare.",
	L"Tra i membri del gruppo non esiste alcuno user che abbia interrotto la procedura.",
	L"Dato che il tempo di risposta per l'inizio di un gioco di gruppo è scaduto, il gioco non può avere inizio.",
	L"Sei già membro di questo gruppo.",
	L"La persona che hai invitato è in attesa di una risposta da parte di un altro gruppo.",
	L"Al momento non sei membro di questo gruppo.",
	L"Le Pozioni miracolose e gli Elisir segreti non sono cumulabili e per questo non possono essere usati.",
	L"ServerSN이 중복 접속 중이다.",
	L"ServerSN 존재하지 않는데 삭제하려한다.",
	L"Questa funzione al momento non è utilizzabile.",
	L"넥슨 통합 맵버쉽 계정 인증 상향 조정 필요.",
	L"Il tuo fisico si è già spinto al limite. Non puoi usare la Pozione segreta.",
	L"Non hai i requisiti di livello minimi. Il gioco nel Dungeon non può iniziare.",
	L"[US] 추천받을 대상이 아닙니다.",
	L"[US] 추천인이 이미 3인을 추천하였습니다.",
	L"[US] 추천 가능한 유저가 아닙니다.",
	L"[US] 맞지 않는 아이템을 사용하였습니다.",
	L"Non è stato possibile ampliare lo slot del personaggio. Massimo 8 Slot personaggi concessi.",
	L"La creazione automatica del gruppo si è conclusa perché il gioco nel Dungeon è iniziato.",
	L"Uno dei partecipanti alla creazione automatica di un gruppo non ha accettato.",
	L"La creazione automatica di un gruppo è stata interrotta con successo.",
	L"Un membro del gruppo non ha accettato l'inizio del gioco dopo la creazione automatica di un gruppo. La creazione automatica di un gruppo è stata interrotta.",
	L"La creazione automatica di un gruppo è riuscita. Il tuo nome è stato cancellato dalla lista.",
	L"La richiesta per la creazione automatica di un gruppo è stata ritirata. Il nome è stato cancellato dalla lista.",
	L"A causa dell'uscita del membro di un gruppo, la creazione automatica di un gruppo è stata ritirata.",
	L"Il livello richiesto per l'item non è raggiunto. Non puoi iniziare il Dungeon.",
	L"Non è stato possibile salvare le impostazioni della tastiera.",
	L"Non è stato possibile salvare alcuna impostazione della tastiera.",
	L"Non è stato possibile leggere le impostazioni della tastiera.",
	L"Non è stato possibile leggere i dati relativi alle impostazioni della tastiera.",
	L"La risposta del gruppo per l'inizio del gioco tarda ad arrivare.",
	L"[US] 추천인 테이블에서 캐릭터 삭제를 실패하였습니다.",
	L"[US] 보안패드 리셋용 질문 및 답변을 입력하지 않았습니다.",
	L"Questo giocatore non fa parte dello stesso gruppo.",
	L"Non è stato possibile salvare i dati relativi alla scelta della chat.",
	L"Non è stato possibile leggere i dati relativi alla scelta della chat.",
	L"Non è stato possibile leggere alcuni dati relativi alla scelta della chat.",
	L"Test",
	L"셧다운제에 의하여 게임이용이 차단 됩니다.",
	L"선택적 셧다운제의 의해 게임이용이 차단됩니다.",
	L"통합 맴버십 ATL 2.0 유저가 아니므로 게임이용이 차단 됩니다.",
	L"셧다운제에 의하여 게임이용이 차단 됩니다.",
	L"선택적 셧다운제의 의해 게임이용이 차단됩니다.",
	L"통합 맴버십 ATL 2.0 유저가 아니므로 게임이용이 차단 됩니다.",
	L"Apertura impossibile.",
	L"Il tempo di apertura è passato.",
	L"ServiceID가 잘못 되었습니다.",
	L"캐시 잔액 정보를 찾을 수 없습니다.",
	L"[TW]ServiceCode 가 올바르지 않습니다.",
	L"[TW]정의되지 않은 애러 발생했습니다.",
	L"[TW]시간형식이 잘못되었습니다.",
	L"[TW]Type정보가 잘못되었습니다.",
	L"[TW]이전 상품 구매가 진행 중입니다.",
	L"Il tuo livello è troppo altro per questa quest.",
	L"파라매터 갯수 입력이 잘못되었습니다.",
	L"[JP] 합성제가 없습니다.",
	L"[JP] 없는 아바타를 합성하려고 했습니다.",
	L"[US]월 선물 가능 횟수를 초과하였습니다.",
	L"Questo Dungeon può essere affrontato esclusivamente da soli.",
	L"Il Dungeon non è ancora aperto.",
	L"Il tuo personaggio non è stato scelto correttamente.",
	L"Il tuo personaggio non può mandare un messaggio privato a se stesso.",
	L"È subentrato un errore nelle informazioni sul Pet.",
	L"Si può utilizzare solo quando il Pet è stato chiamato.",
	L"Si può utilizzare solo con Pet teen.",
	L"Si può utilizzare solo con Pet kid.",
	L"L'impostazione della quantità di tag è errata.",
	L"Il gioco inizia con almeno due membri per team.",
	L"",
	L"",
	L"",
	L"",
	L"Hai abbandonato il Dungeon.",
	L"Hai abbandonato la competizione.",
	L"Si sta per uscire in seguito a un cambio di canale.",
	L"Si sta per uscire in seguito alla visita degli stessi membri del gruppo.",
	L"Si sta per uscire in seguito all'utilizzo di item di movimento.",
	L"Si sta per uscire in seguito a interruzione irregolare.",
	L"Mentre si sta giocando un Dungeon non è possibile invitare nuovi membri nel gruppo.",
	L"Questo giocatore non può essere invitato in quanto fa già parte di un altro gruppo.",
	L"Attualmente questa persona si trova in una competizione e pertanto non può essere invitata.",
	L"Attualmente questa persona si trova in un Dungeon e pertanto non può essere invitata.",
	L"Non è stato possibile trovare il giocatore su questo server.",
	L"Non è possibile invitare altri membri nel gruppo.",
	L"Durante una competizione non è possibile invitare nuovi membri nel gruppo.",
	L"Il tuo livello è troppo basso per poter accedere a questo campo.",
	L"Non hai ancora completato i Dungeon richiesti per poter accedere a questo campo.",
	L"Si possono compiere al massimo 30 quest.",
	L"Non hai abbastanza ED.",
	L"I giocatori che utilizzano la formazione automatica del gruppo non possono essere invitati.",
	L"Quando la formazione automatica del gruppo è attiva non è possibile invitare nessuno nel proprio gruppo.",
	L"Nella stanza PvP non si può invitare nessun membro del gruppo.",
	L"Durante l'allenamento non si può invitare alcun membro del gruppo.",
	L"Durante l'abbinamento per il PvP non si può invitare alcun membro del gruppo.",
	L"Finché la formazione automatica del gruppo è attiva non è possibile effettuare inviti manuali.",
	L"Quando si è iscritti all'abbinamento per il PvP non è possibile invitare alcun membro del gruppo.",
	L"Il tuo gruppo si trova sul tuo stesso Campo.",
	L"Questa persona non può essere invitata in quanto è già candidata per un altro gruppo.",
	L"",
	L"",
	L"Questo nickname non è presente.",
	L"L'ID del gruppo sul server è sbagliato.",
	L"",
	L"Chi non dispone dell'autorizzazione a partecipare alla competizione online non può accedere al canale PvP.",
	L"Per aprire il bauletto servono item ed ED.",
	L"Non hai abbastanza ED per aprire il bauletto.",
	L"Si inizierà con l'attuale numero di partecipanti.",
	L"",
	L"",
	L"",
	L"L'evento è finito.",
	L"Non puoi andare a prendere questo item con Ara.",
	L"",
	L"Purtroppo hai raggiunto il numero massimo di scambi possibili.\nDopo la manutenzione del 17.01 saranno resi disponibili ulteriori scambi.",
	L"",
	L"Questo Pet non esiste.",
	L"Questa funzione è già attiva.",
	L"Utilizzabile solo a partire dal livello \"Kid\".",
	L"Mentre si sta aspettando di giocare non è possibile modificare gli slot delle skill.",
	L"Non è stato possibile caricare le informazioni sui mostri del campo poiché in questo momento non ti trovi nella stanza.",
	L"Non è stato possibile caricare le informazioni sui mostri del campo poiché in questo momento non ti trovi nella stanza.",
	L"Impossibile acquistare l'item per l'Ampliamento degli slot. Gli slot possono essere ampliati di massimo 30 spazi.",
	L"L'esclusione dal Dungeon è avvenuta in seguito a una votazione a favore dell'esclusione.",
	L"Il votante non è un vero giocatore.",
	L"La persona per la quale si vota non è un vero giocatore.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Non hai abbastanza ED per registrare un invito.",
	L"Non puoi presentare domanda a questa gilda, in quanto è già stato raggiunto il numero massimo di membri.",
	L"Non è stato possibile inviare la richiesta di invito.",
	L"Non è stato possibile registrare la ricerca gilda.",
	L"Esiste già un messaggio di invito gilda.",
	L"È già stata registrata una ricerca gilda.",
	L"Non è stato possibile registrare il messaggio di invito gilda.",
	L"Non hai abbastanza ED per registrare la ricerca gilda.",
	L"Non è disponibile nessun invito a unirsi alla gilda.",
	L"Non è disponibile nessuna ricerca gilda.",
	L"Questa gilda non esiste.",
	L"Non sei autorizzato a vedere la lista dei giocatori invitati.",
	L"Hai raggiunto il numero massimo di accessi al Dungeon.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Non possiedi alcuna \"Guida ai Campi\".",
	L"Non è stato possibile aggiungere questo capitolo.",
	L"Questo capitolo è già stato aggiunto.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Si è verificato un errore durante il calcolo del tempo VIP.",
	L"",
	L"",
	L"",
	L"",
	L"Il livello dell'item non è adatto a questa Pergamena dello Spazio-tempo benedetta.",
	L"Questo item è già stato identificato.",
	L"Non ci sono item nell'inventario.",
	L"Non hai ED a sufficienza per poter identificare l'item.",
	L"L'identificazione non è riuscita.",
	L"Non hai Pergamene dello Spazio-tempo a sufficienza.",
	L"Questo item non può essere identificato.",
	L"",
	L"",
	L"Questo item non può essere sostituito.",
	L"Non possiedi ED a sufficienza per coprire la tassa di sostituzione.",
	L"",
	L"",
	L"",
	L"",
	L"Non possiedi item da sostituire.",
	L"La sostituzione dell'item non è riuscita.",
	L"",
	L"",
	L"Gli item con una scadenza o i materiali non possono essere sostituiti.",
	L"Gli item con una scadenza o i materiali non possono essere sostituiti.",
	L"I requisiti non sono soddisfatti.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Non è possibile effettuare acquisti con un account bloccato.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"A causa di un errore verificatosi nel file CheckKom.xml, il programma sarà terminato.",
	L"",
	L"Informazione errata sul settore.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Manca almeno un requisito. Controlla se hai chiamato il Pet!",
	L"Manca almeno un requisito. Controlla se puoi utilizzare il Pet!",
	L"Hai utilizzato con successo la Pozione della trasformazione della Fata-zucca di Halloween!",
	L"Manca almeno un requisito. Controlla se l'affiatamento del tuo Pet ammonta al 100%!",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Hai raggiunto il numero massimo di Dungeon giocati.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"A causa di una modifica dei dati, il programma sarà terminato.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",

	L""
};
