#pragma once

//PL버전 출력
static wchar_t* szErrorStrPL[] = {
	L"Sukces",
	L"Nieznany błąd",
	L"Wystąpił błąd w statusie gracza.",
	L"Nieprawidłowa wersja. Zaloguj się ponownie.",
	L"Serwer jest pełny. Maksymalna ilość graczy została osiągnięta.",
	L"Sprawdzany będzie serwer gry. Zaloguj się po sprawdzeniu systemu.",
	L"Próbowałeś zalogować się dwa razy na tym samym serwerze.",
	L"Próbowano zalogować się równocześnie do różnych kanałów.",
	L"Sprawdzenie IP serwera nie powiodło się.",
	L"UID serwera zawiesiło się.",
	L"Użytkownik nie istnieje",
	L"Ten gracz już nie istnieje.",
	L"Dane loginu są nieprawidłowe.",
	L"Ustawienia serwera są nieprawidłowe.",
	L"Twoje dane dostępowe nie zostały zweryfikowane.",
	L"Twoje konto zostało zablokowane.\nZwróć się do naszego supportu:\nhttp://support.elsword.pl",
	L"Zapytanie jest możliwe tylko przez operatora systemu.",
	L"ID proxy niedostępne.",
	L"Niedozwolony adres IP.",
	L"Dane ID kanału nie istnieją na serwerze gry.",
	L"Nieprawidłowa długość ID.",
	L"Błąd podczas tranzakcji.",
	L"Długość ID jest niedozwolona.",
	L"Długość hasła jest nieprawidłowa.",
	L"Długość nazwy użytkownika jest nieprawidłowa.",
	L"Usunięty gracz próbował stworzyć postać.",
	L"Nazwa postaci już istnieje.",
	L"Błąd podczas tranzakcji.",
	L"Wystąpił błąd podczas ładowania danych postaci.",
	L"Nazwa postaci jest za długa.",
	L"Nie można stworzyć więcej postaci.",
	L"Nicka nie można obecnie użyć.",
	L"Baza danych nie mogła utworzyć SN postaci dla Messengera.",
	L"Tego nicka nie możesz użyć.",
	L"Na dzień można stworzyć maksymalnie cztery postacie.",
	L"Wybranej postaci nie ma na serwerze gry.",
	L"Wybrałeś nieprawidłową klasę postaci.",
	L"Nie można wyświetlić informacji dotyczących kamieni ożywienia.",
	L"Baza danych nie mogła uruchomić SN postaci Messengera.",
	L"Wystąpił błąd w bazie danych podczas wybierania postaci.",
	L"Nick musi zostać zmieniony.",
	L"Nie znaleziono kanału PvP, który pasuje do twojego poziomu.",
	L"Gracz, którego należy usunąć, nie jest na kanale.",
	L"Zmiana kanału nie powiodła się.",
	L"Za mało VP, by wejść.",
	L"Wejście na kanał placu wioski nie powiodło się.",
	L"Wejście do kanału nie powiodło się.",
	L"Nie odbędą się zawody.",
	L"Nie można otworzyć listy grupy.",
	L"W bramie planszy nie możesz sprawdzić listę grupy.",
	L"W bramie planszy nie można otworzyć listy grupy.",
	L"PvP możliwy dopiero od poziomu 3.",
	L"Na serwerze nie można stworzyć kolejnych plansz.",
	L"W okienku nie można znaleźć żadnego użytkownika.",
	L"Nie znaleziono okienka, w którym znajduje się postać.",
	L"Plansza jest pełna.",
	L"Dane loginu są nieprawidłowe.",
	L"Poprzednia plansza nie została zaliczona.",
	L"Natychmiastowe rozpoczęcie nie powiodło się. Niedostępne żadne plansze.",
	L"Tylko lider tej planszy może o to złożyć wniosek.",
	L"Status planszy nie dopuszcza chwilowo żadnych pakietów.",
	L"Gracz nie jest jeszcze gotowy.",
	L"Ilość członków grupy nie zgadza się.",
	L"Aby rozpocząć grę, więcej niż jedna postać musi być \"gotowa\".",
	L"Nie można było zmienić procesu ładowania.",
	L"Plansza została stworzona.",
	L"Informacje o planszy zostały zmienione.",
	L"Plansza została usunięta.",
	L"Na planszy nie został znaleziony żaden gracz.",
	L"Wejście nie powiodło się.",
	L"Nie mogłeś opuścić planszy.",
	L"UID zmarłego NPC jest nieprawidłowa.",
	L"NPC już nie żyje.",
	L"Niepoprawne dane potwora. Ładowanie nie powiodło się.",
	L"Gracz nie został znaleziony.",
	L"Typ czatu jest wadliwy.",
	L"Nie możesz siebie samego usunąć z planszy.",
	L"Za mało punktów woli.",
	L"Ten typ gry nie wspiera statystyki uzupełnień.",
	L"Gra zostanie zakończona. Nie możesz wejść na planszę.",
	L"Nie możesz wejść na planszę.",
	L"Plansza, na którą chcesz wejść nie zawiera żadnych informacji.",
	L"Podczas handlu nie możesz przygotować się do gry.",
	L"Nie możesz wejść na planszę, ponieważ właśnie rozpoczyna się gra. Spróbuj później ponownie.",
	L"W ekwipunku nie ma przedmiotu do rozpoczęcia gry.",
	L"Nieupoważniony gracz próbował stworzyć pomieszczenie do obserwacji.",
	L"Dane mapy PvP są nieprawidłowe.",
	L"Z kanału turnieju mogą korzystać tylko osoby posiadające upoważnienie do wzięcia udziału offline.",
	L"Potrzebujesz przedmiotu, by zaliczyć wybraną planszę. Po rozpoczęciu gry na planszy zostaniesz z niej usunięty.",
	L"Tylko na planszy PvP można użyć funkcji zaproszenia.",
	L"Zaproszony gracz nie może teraz wejść na tę planszę PvP.",
	L"Możesz zaprosić tylko graczy, którzy znajdują się w kanale lobby PvP.",
	L"Gra rozpocznie się dopiero, gdy zameldujesz się do grupy.",
	L"Nieprawidłowe ustawienia w ilości uśmierceń.",
	L"Przedmiot już nie istnieje.",
	L"Ktoś innych już otrzymał.",
	L"Losowe rozdzielenie przedmiotów nie powiodło się.",
	L"Nie ma informacji o przedmiocie.",
	L"ID przedmiotu jest nieprawidłowe.",
	L"Przedmiotu nie można było przyznać.",
	L"Przemiot nie został naprawiony.",
	L"Przedmiotu z pola szybkiego dostępu nie można było użyć",
	L"Na planszy eventu nie można używać pola szybkiego dostępu.",
	L"Przedmiot nie został nabyty",
	L"Nie można przejąć przedmiotu z magazynu.",
	L"Za mało miejsca na przedmiot z depozytu.",
	L"Wiadomość za długa.",
	L"Grupa nie została zmieniona.",
	L"Zmiany w slocie nie zostały zapisane.",
	L"Wzięcie udziału nie powiodło się.",
	L"Okienko nie zostało zamknięte.",
	L"Użytkownika nie można było usunąć.",
	L"Dane przeciwnika nie zostały zapisane.",
	L"Statusu nie został zmieniony.",
	L"Gracz sam opuścił.",
	L"Połączenie zostało zakończone.",
	L"Zostałeś usunięty.",
	L"Twój poziom jest za wysoki na ten kanał.",
	L"Stragan został zamknięty.",
	L"Odwiedzenie straganu nie powiodło się.",
	L"Czas minął. Stragan został zamknięty.",
	L"Stragan został anulowany.",
	L"Ilość prywatnych sprzedawców jest nieprawidłowa.",
	L"Podczas handlu wystąpił błąd",
	L"Masz za mało miejsca w ekwipunku lub dane przedmiotu są nieprawidłowe.",
	L"Masz za mało punktów woli.",
	L"Handel został anulowany. Nie ma przedmiotów do handlu.",
	L"Handel został anulowany.",
	L"Stragan został zamknięty, ponieważ nie wstawiłeś żadnych przedmiotów.",
	L"Handel został anulowany.",
	L"Wszystkie przedmioty zostały sprzedane. Stragan zostanie zamknięty.",
	L"Handel został anulowany, ponieważ opuściłeś planszę.",
	L"Stragan został zamknięty.",
	L"Klient zawiesił się.",
	L"Nie możesz zostać dłużej w kanale walki.",
	L"Jeśli weźmiesz udział w PvP, to opuścisz grupę.",
	L"Grupa została rozwiązana, ponieważ zaliczono planszę.",
	L"Opuściłeś grupę, ponieważ wszedłeś na rynek.",
	L"Opuściłeś grupę, ponieważ wszedłeś do obozu treningowego.",
	L"Zakończono.",
	L"Gra została zakończona z powodu podejrzenia o użycie nielegalnego oprogramowania.",
	L"Klient zawiesił się. Gra zakończona.",
	L"PD postaci nie zostały zmienione.",
	L"Postać nie mogła zostać przyporządkowana przez bazę danych.",
	L"Poziom autorytetu jest nieprawidłowy",
	L"Ten gracz nie istnieje.",
	L"Błąd podczas tranzakcji.",
	L"Nie ma gracza o takim poziomie autorytetu.",
	L"Operator zakończył połączenie.",
	L"Rozkaz może być wykonany tylko w terenie.",
	L"To polecenie nie może tutaj zostać wykonane.",
	L"Nie możesz kupić tego przedmiotu.",
	L"Nie możesz sprzedać tego przedmiotu.",
	L"Misja jest już wykonywana.",
	L"Próbowałeś usunąć misję, która jeszcze nie została zakończona.",
	L"Taka misja nie istnieje.",
	L"Misja została już zakończona.",
	L"Ta postać nie może podjąć tej misji.",
	L"Poprzednia misja nie została jeszcze zakończona.",
	L"Otrzymałeś nieprawidłową misję od NPC.",
	L"Nie ma takiego szablonu misji.",
	L"Misji nie można zakończyć, ponieważ nie spełniła ona jeszcze wszystkich warunków.",
	L"Baza danych nie przetworzyła danych misji.",
	L"Możesz przyjąć maksymalnie 10 misji równocześnie.",
	L"Twój poziom jest za niski, by przyjąć misję.",
	L"Jest za mało miejsca w ekwipunku, by zakończyć misję.",
	L"Wystąpił błąd przy rozdzieleniu nagrody za misję.",
	L"Szukana nagroda nie została znaleziona.",
	L"Zmiana klasy - misji jest w toku.",
	L"Wystąpił błąd w przetworzeniu nagrody misji w zmianie klasy .",
	L"Typ misji niepoprawny.",
	L"Wiadomość czatu została w krótkim czasie podana jako wyznaczona.",
	L"Nie możesz wysłać sam do siebie wiadomości szeptanych.",
	L"Nieprawidłowy czat.",
	L"Użykownik nie jest teraz zalogowany.",
	L"--/;/nie można użyć cudzysłowu, przecinka, spacji.",
	L"Wpis jest krótszy niż czas ładowania aktualnej listy graczy.",
	L"Wyszukiwanie danych użytkownika nie zostało zakończone.",
	L"Użykownik nie jest teraz zalogowany.",
	L"Nick nie istnieje.",
	L"Wejście na plac wioski nie powiodło się.",
	L"Opuszczenie placu wioski nie powiodło się.",
	L"Umiejętność osiągnęła najwyższy stopień.",
	L"Umiejętność nie istnieje.",
	L"Twój poziom jest za niski, by nauczyć się tej umiejętności.",
	L"Masz za mało punktów umiejętności.",
	L"Brkuje ci potrzebnego przedmiotu.",
	L"Musisz zakończyć misję, aby to nabyć.",
	L"Nie nauczyłeś jeszcze poprzedniej umiejętności.",
	L"Posiadasz już tę umiejętność.",
	L"ID okienka umiejętności jest nieprawidłowe.",
	L"Możesz dodać tylko te umiejętności, których możesz się nauczyć.",
	L"Cofnięcie umiejętności nie powiodło się.",
	L"Nie można użyć okienka umiejętności B.",
	L"Wystąpił błąd podczas powiększenia okienka umiejętności B.",
	L"Umiejętności dopiero możesz się nauczyć po zdjęciu pieczęci.",
	L"Umiejętność jest na poziomie, którego jeszcze nie osiągnąłeś.",
	L"Masz za mało punktów umiejętności, by nauczyć się tej umiejętności.",
	L"Masz za mało punktów umiejętności, by nauczyć się tej umiejętności.",
	L"Próbowałeś zmienić informacje o umiejętność, która nie istnieje.",
	L"Błędne informacje o poziomie umiejętności.",
	L"Ustawiony poziom umiejętności nie zgadza się z prawidłowym poziomem.",
	L"Zmiana dotycząca ważności punktów umiejętności w sklepie nie mogła zostać przejęta.",
	L"Rejestrowanie punktów umiejętności w sklepie nie powiodło się.",
	L"Informacje o punktach umiejętności w sklepie nie zostały zaktualizowane.",
	L"Cofnięcie informacji o punktach umiejętności w sklepie nie powiodła się.",
	L"Standartowych umiejętności nie można cofnąć.",
	L"Nie można było stworzyć grupy.",
	L"Nie mógł wystąpić z grupy.",
	L"Nieprawidłowa informacja grupy.",
	L"Użytkownik nie może zostać zaproszony.",
	L"Nie ma odpowiedniej grupy.",
	L"Jesteś już zarejetrowany w tej grupie.",
	L"W modusie PvP nie można stworzyć grupy.",
	L"W modusie PvP nie można przystąpić do grupy.",
	L"Grupa nie może przyjąć więcej członków.",
	L"Nie można przystąpić do grupy.",
	L"Grupa została usunięta.",
	L"Odrzucono przystąpienie do grupy.",
	L"Odrzucono zaproszenie do grupy.",
	L"Stąd nie można wejść na planszę.",
	L"Zmiana statusu gotowości nie powiodła się.",
	L"Wybrałeś nieprawidłową planszę.",
	L"Rozpoczęcie gry nie powiodło się.",
	L"Typ gry jest nieprawidłowy.",
	L"Nie jesteś liderem grupy.",
	L"Lider grupy nie został zmieniony.",
	L"Członkowie grupy nie zostali zmienieni.",
	L"Nie możesz rozpocząć planszy na tym obszarze.",
	L"Nie można było zmienić ustawień prywatnej sfery.",
	L"Gracz, który został wybrany na lidera, nie może zaliczyć aktualnej planszy.",
	L"Lider grupy nie może zmienić statusu \"Gotowy\".",
	L"Nie ma partnera do czatu.",
	L"Żądana lista grupy jest wadliwa.",
	L"Ustawienia dotyczące limitu poziomu nie zostały zmienione.",
	L"To jest prywatna grupa.",
	L"Kamień ożywienia niedostępny.",
	L"Zostałeś już ożywiony.",
	L"Ożywienie nie powiodło się.",
	L"Na tej planszy nie możesz użyć kamienia ożywienia.",
	L"Nie można aktualizować nieistniejącego statusu.",
	L"Nie można otworzyć opcji społeczności.",
	L"Niemożliwe dalsze wpisy na czarną listę.",
	L"Ten gracz jest już na czarnej liście.",
	L"Gracza usunięto już z czarnej listy.",
	L"Gracz nie istnieje.",
	L"Nie można było usunąć z czarnej listy.",
	L"Nie możesz dodać siebie do czarnej listy.",
	L"Nie możesz usunąć siebie z czarnej listy.",
	L"Do czarnej listy możesz dodawać tylko zalogowanych graczy.",
	L"Dodanie własnej postaci jest niemożliwe.",
	L"Minął limit czasu przeznaczony na dodanie do listy znajomych.",
	L"Postać nie została znaleziona.",
	L"Twoja postać w tym statusie nie możesz nikogo zaprosić.",
	L"Inny gracz nie może zostać teraz zaproszony.",
	L"Inny gracz nie może teraz wziąć udziału.",
	L"Nie można dodać do listy znajomych.",
	L"Nie można było otworzyć straganu.",
	L"Nie możesz opuścić prywatnego handlu.",
	L"Wyszukiwanie graczy oferujących prywatny handel nie powiodło się.",
	L"Wybrany przedmiot jest nieprawidłowy.",
	L"Wpis ED jest błędny.",
	L"Przedmiot handlu nie istnieje.",
	L"Za mało ED!",
	L"Możesz wybrać przedmioty tylko z ekwipunku.",
	L"Nie ma wystarczająco dużo miejsca w ekwipunku.",
	L"Przedmiotów połączonych z graczem nie można sprzedać.",
	L"Nie można tutaj otworzyć czat handlu.",
	L"Nie możesz handlować sam ze sobą.",
	L"Jeśli skończy się trwałość przedmiotu, nie możesz go sprzedać. Napraw przedmiot i spróbój ponownie.",
	L"Przedmiot jest już zarejestrowany.",
	L"Zostały usunięte tylko zarejestowane przedmioty.",
	L"Możesz wybrać maksymalnie 10 przedmiotów.",
	L"Podczas handlu inny gracz przekracza swoją ilość ED. Zmniejsz ilość ED dla handlu.",
	L"Zapytanie o prywatny handel zostało przyjęte.",
	L"Prowadzisz już handel z innym graczem.",
	L"Zapytanie o prywatny handel zostało odrzucone.",
	L"Nie można prowadzić handlu.",
	L"Handel niemożliwy z powodu błędu serwera.",
	L"Brakuje ci potrzebnego przedmiotu, by wziąć udział w misji planszy.",
	L"Nie jesteś jeszcze upoważniony, by wejść do obozu treningowego.",
	L"Planszy, która jest przeznaczona na obóz treningowy brakuje ID.",
	L"Wystąpił błąd podczas zapisywania nagrody.",
	L"W ekwipunku nie ma wybranego przedmiotu.",
	L"Wybrany przedmiot to nie kostka.",
	L"Ta postać nie może użyć przedmiotu.",
	L"Nie posiadasz wystarczającej ilości kluczy, by otworzyć kostkę.",
	L"Kostki nie można otworzyć.",
	L"Przedmiot nie został wyprodukowany.",
	L"Masz za mało miejsca w ekwipunku, by otworzyć kostkę.",
	L"Jest więcej niż jedno zgłoszenie.",
	L"Niepoprawny UID gracza.",
	L"ID gracza jest niepoprawne.",
	L"Nieprawidłowe UID postaci.",
	L"Nieprawidłowy nick postaci.",
	L"Nieprawidłowe UID serwera gry.",
	L"Informacje gracza jest niepoprawna.",
	L"Nieprawidłowe informacje serwera gry.",
	L"Wyszukiwanie UID nie powiodło się.",
	L"Nieprawidłowy numer messenger.",
	L"Przedmiotu nie można było wyprodukować.",
	L"Przedmiot nie jest zwojem.",
	L"Za mało ED na crafting!",
	L"Posiadasz za mało matriałów.",
	L"Musisz posiadać przynajmniej jedno miejsce wolne, by przeprowadzić Crafting.",
	L"Przedmiot nie został wyprodukowany.",
	L"Certyfikacja HackShield'a nie powiodła się.",
	L"Z powodu aktualizacji HackShield'a musisz uruchomić grę ponownie.",
	L"Weryfikacja HackShield'a nie powiodła się.",
	L"Kupon został już zrealizowany lub numer jest nieprawidłowy. Możesz użyć tylko jednego kuponu na konto.",
	L"Podaj kod składający się z 30 znaków.",
	L"Ten kupon został już zrealizowany.",
	L"Kupon jest już nieważny.",
	L"Niepoprawny numer kuponu.",
	L"Ten rodzaj kuponu można użyć tylko raz na jedno konto.",
	L"Kuponu nie można było zrealizować.",
	L"Musisz odczekać określoną ilość dniu, by móc kupić ponownie.",
	L"Nie można otworzyć listy przedmiotów.",
	L"Nieprawidłowe informacje o przedmiocie.",
	L"Masz za mało miejsca w ekwipunku.",
	L"Nie można wybrać kupionego przedmiotu.",
	L"Nie można było znaleźć reszty sumy.",
	L"Nie znaleziono informacji o członkach.",
	L"Konto zostało zablokowane.",
	L"Nie można przeciągnąć przedmiotów innych postaci do ekwipunku.",
	L"Jesteś już w posiadaniu tego przedmiotu.",
	L"Przedmiot ładuje się. Poczekaj chwilę.",
	L"Średnia wielkość obrazka (ramki) jest nieprawidłowa.",
	L"Ten gracz nie istnieje.",
	L"To nie jest obiekt, który powienien zmienić nicka.",
	L"Nick już istnieje.",
	L"Nicka nie można obecnie użyć.",
	L"Nick nie został zaktualizowany.",
	L"Nick niedozwolony.",
	L"Długość nicka niedozwolona.",
	L"Nie można było zmienić nicka.",
	L"Nie można było otworzyć straganu.",
	L"Stragan można otworzyć tylko w wiosce.",
	L"Nie można otworzyć straganu. Nie znaleziono żadnych informacji o właścicielu.",
	L"Stragan jest już obciążony. Spróbuj póżniej ponownie.",
	L"Otwarcie straganu nie powiodło się.",
	L"Wybrana ilość przedmiotów, którą chcesz sprzedać nie zgadza się z danymi.",
	L"Przedmiot został oznaczony jako sprzedany.",
	L"Nie możesz zarejestrować towarów na obcych straganach!",
	L"Więcej przedmiotów jest zarejestrowanych niż można sprzedać.",
	L"Nie masz wystarczającej ilości pieniędzy, by otworzyć stragan.",
	L"Otwarcie straganu jeszcze niezakończone.",
	L"Nie opuściłeś jeszcze sklepu.",
	L"Wybrałeś więcej przedmiotów do zakupu, niż jest oferowanych do sprzedaży.",
	L"Przedmiot, który chcesz kupić nie istnieje.",
	L"Masz za mało ED, by kupić przedmiot.",
	L"Masz za mało miejsca w ekwipunku, by coś kupić.",
	L"Handlu nie można przeprowadzić, ponieważ nie można znaleźć producenta.",
	L"Podczas handlu nie możesz otworzyć straganu.",
	L"Stragan jest już otwarty.",
	L"Przekroczyłeś maksymalną ilość ED.",
	L"Przekroczyłeś maksymalną ilość ED, którą możesz kupić.",
	L"Informacje o przedmiocie, który chcesz kupić są nieprawidłowe.",
	L"W ekwipunku nie ma wybranego przedmiotu.",
	L"Przedmiotu nie można zdemontować.",
	L"Rozkład przedmiotu nie powiódł się. Spróbuj później ponownie.",
	L"Możesz rozłożyć tylko swoje uzbrojenie oraz akcesoria.",
	L"Nie można rozłożyć.",
	L"Przedmiot nie został wyprodukowany.",
	L"Za mało miejsca w ekwipunku,\nuby rozłożyć przedmiot.",
	L"Przedmiot z okresem użycia nie można rozłożyć.",
	L"Przedmiot, który chcesz ulepszyć nie znajduje się w ekwipunku.",
	L"Dane przedmiotu nie istnieją.",
	L"W obronie można ulepszać tylko broń oraz części zbroi.",
	L"Nie można ulepszyć przedmiotu.",
	L"Nie można go więcej ulepszyć.",
	L"Nie ma dostępnych kamieni upgrade'u!",
	L"Nie można przeprowadzić upgrade'u.",
	L"Masz za mało ED na upgrade.",
	L"Aby przeprowadzić upgrade musisz najpierw przedmiot odłożyć lub zdjąć.",
	L"Kamień fluorowy jest niedostępny w ekwipunku.",
	L"Nie można użyć kamienia fluorowego.",
	L"Od upgrade'u poziomu 10 nie można już użyć kamienia fluorowego.",
	L"Nie możesz przeprowadzić upgrade'u na przedmiotach, których nie możesz użyć.",
	L"Upgrade nie powiódł się.",
	L"Przedmiot do naprawy nie znajduje się w twoim ekwipunku.",
	L"Dane przedmiotu nie istnieją.",
	L"Nie można naprawić przedmiotu.",
	L"Możliwa naprawa tylko tych przedmiotów, których nie możesz użyć.",
	L"Za mało kamieni odnowy.",
	L"Nie możesz naprawiać założonych przedmiotów.",
	L"Przedmiotów, których szczególne cechy dezaktywowane są, nie można użyć.",
	L"Upgrade zakończony.",
	L"Bez zmian.",
	L"Zmiejszono o jeden stopień.",
	L"Cofnięcie stopnia upgrade'u.",
	L"Przedmiotu nie można użyć.",
	L"Przedmiotu nie ma w ekwipunku.",
	L"Dane przedmiotu nie istnieją.",
	L"Opłata za wysoka.",
	L"Umieścić w slocie możesz tylko broń lub części zbroi.",
	L"W uzbrojeniu nie ma informacji o magicznym kamieniu.",
	L"W ekwipunku nie ma magicznego kamienia.",
	L"Nie możesz użyć slotu.",
	L"Magiczny kamień został już umieszczony w slocie.",
	L"Magiczny kamień jest już usunięty ze slotu.",
	L"Opcja slot nie istnieje.",
	L"Nick nie istnieje.",
	L"Nie możesz siebie samego zaproponować.",
	L"Nie ma nikogo, kto by przyjął nagrodę.",
	L"Prywatny plik, który chcesz usunąć, nie znajduje się w bazie danych.",
	L"Nie można otworzyć listy uczniów.",
	L"Nie można wyświetlić informacji. Poziom za niski.",
	L"Masz za niski poziom, by przyjąć ucznia.",
	L"Można zarejestrować maksymalnie 3 uczniów.",
	L"On ma już mistrza.",
	L"Jest już zarejestrowany jako uczeń.",
	L"Towary, które można kupić są wadliwe.",
	L"Towaru nie można nabyć.",
	L"Wpłaty już dokonano.",
	L"Przekroczono maksymalną ilość towarów.",
	L"Przekroczyłeś maksymalną ilość towarów, która miała zostać kupiona.",
	L"Tego towaru nie można jeszcze kupić.",
	L"Nie ma koszyka.",
	L"Użycie gry jest ograniczone.",
	L"Ilość towaru jest ograniczona. Towar niedostępny.",
	L"Ilość zamówień ograniczona.",
	L"Tego towaru teraz nie można jeszcze kupić.",
	L"Towaru nie można podarować.",
	L"Ilość zamówień ograniczona.",
	L"Inny gracz nie może teraz przyjąć towaru.",
	L"Zablokowany gracz.",
	L"Nie znaleziono informacji o graczach.",
	L"Nie wystarczające finanse.",
	L"System sprawdzany.",
	L"Osiągnąłeś maksymalną ilość kamieni ożywienia.",
	L"Nie można stworzyć dalszych okienek ekwipunku.",
	L"Nie możesz czegoś podarować sam sobie.",
	L"Dane loginu są nieprawidłowe.",
	L"Nick nie istnieje.",
	L"Graczom z próbnym ID nie można nic podarować.",
	L"Ilość podarowanych towarów została przekroczona.",
	L"Podaj hasło.",
	L"Weryfikacja konta nie powiodła się.",
	L"Towaru nie można podarować.",
	L"Gracze poniżej 14 lat nie mogą używać tej funkcji.",
	L"Nie można kupić przedmiotu.\nMaksymalnie dozwolonych 9 okienek.",
	L"Okienko postaci nie mogło zostać powiększone.",
	L"Funkcja jest już używana.",
	L"Umiejętność nie istnieje.",
	L"Nie istnieje przedmiot do cofnięcia umiejętności.",
	L"Nie można usunąć z bazy danych przedmiotu do cofnięcia umiejętności.",
	L"Podczas cofnięcia umiejętności wystąpił błąd w bazie danych.",
	L"Nie możesz cofnąć umiejętności.",
	L"Umiejętności nie można cofnąć, tak długo, dopóki znajduje się w polu szybkiego dostępu.",
	L"Tego towaru nie można dodać do listy życzeń.",
	L"Nie możesz włożyć więcej produktów do koszyka.",
	L"Tę funkcję nie możesz użyć jako tester.",
	L"Gracze z próbnym ID nie mogą polecać gry innym.",
	L"Osiągnąłeś maksymalny poziom dla gracza z próbnym ID. Jeśli chcesz kontynuować grę, zaloguj się pełnym ID.",
	L"Graczy z próbnym ID nie można zaprosić do listy znajomych.",
	L"Użytkownik nie znajduje się na liście hackerów.",
	L"Baza danych nie zaktualizowała jeszcze danych hackingu.",
	L"Nie potwierdziłeś jeszcze zgłoszenia graczy-hackerów.",
	L"Przedmiot niedostępny w ekwipunku.",
	L"Ta właściwość nie może zostać ulepszona.",
	L"Właściwości okienek zostały już ulepszone.",
	L"Okienko zostało opróżnione.",
	L"Posiadasz za mało ED na dodanie atrybutów.",
	L"Nie masz wystarczającej ilości odłamków Eldrytu na umagicznienie.",
	L"Niepoprawne informacje o przedmiocie.",
	L"Opcja dodawania atrybutów jest dostępna tylko przy broniach i zbrojach.",
	L"Wybranego przedmiotu nie można zdemontować.",
	L"Za mało urządzeń do analizy.",
	L"Za mało miejsca w ekwipunku,\nby rozłożyć przedmiot.",
	L"Wybranego przedmiotu nie można rozłożyć.",
	L"Produkcja przedmiotu nie powiodła się.",
	L"Nie można otworzyć skrzynki odbiorczej.",
	L"Wybranego przedmiotu nie może załączyć do maila.",
	L"Podaną ilość ED nie można wysłać e-mailem.",
	L"Maila nie można było wysłać.",
	L"Nie ma takiego maila.",
	L"Za mało miejsca, by przeciągnąć przedmiot. Zrób miejsce w ekwipunku i spróbuj ponownie.",
	L"Dołączony przedmiot jest niedostępny.",
	L"Próbowałeś dodać przedmiot, który nie istnieje.",
	L"Można dodać tylko całkowicie naprawione przedmioty.",
	L"Nick nie istnieje.",
	L"Nie możesz wysyłać wiadomości do siebie samego.",
	L"Za mało ED, by wysłać wiadomość.",
	L"Gracz ma za mało miejsca w swojej skrzynce odbiorczej i nie może odbierać wiadomości.",
	L"Wybrałeś skasowaną wiadomość.",
	L"Gracz odrzucił twoją wiadomość.",
	L"Przedmiotów połączonych z twoją postacią, nie możesz wysyłać załączonych do wiadomości.",
	L"Do graczy z próbnym ID nie można wysyłać wiadomości.",
	L"Nick nie istnieje.",
	L"Nick ten znajduje się już na czarnej liście.",
	L"Dodanie do czarnej listy nie powiodło się.",
	L"Nick został już skasowany.",
	L"Gracz nie mógł zostać usunięty z czarnej listy.",
	L"Nie posiadasz tego tytułu.",
	L"Posiadasz już ten tytuł.",
	L"Ważność tytułu wygasła.",
	L"Ten tytuł nie istnieje.",
	L"Nie zdobyłeś tytułu.",
	L"Posiadasz już ten tytuł.",
	L"Nie można użyć przedmiotu.",
	L"Przedmiot nie istnieje.",
	L"Masz za niski poziom na ten przedmiot.",
	L"Przedmiotu nie można użyć w ekwipunku.",
	L"Przedmiotu nie ma w ekwipunku.",
	L"Przedmiot niedozwolony.",
	L"Przedmiot niedozwolony.",
	L"Upgrade nie powiódł się.",
	L"Nie możesz wymienić przedmiotu.",
	L"Przedmiotu nie ma w ekwipunku.",
	L"Tym przedmiotem nie możesz handlować.",
	L"Przedmioty do wymiany nie zostały stworzone.",
	L"Opuszczasz to miejsce, by udać się do innego obszaru.",
	L"Opuszczasz teren, by udać się na planszę.",
	L"System uwzględnił twoją rezygnację.",
	L"Nie możesz wejść do wioski.",
	L"Nie mogłeś opuścić wioski.",
	L"Nie można wyświetlić listy graczy.",
	L"Twój poziom jest za niski, aby wejść do wioski.",
	L"Nie zaliczyłeś jeszcze planszy, która umożliwia ci wejście do wioski.",
	L"Ten kanał nie istnieje.",
	L"Zmieniłeś kanał. Połączenie zakończone.",
	L"Nie powiodła się rejestracja, by zmienić kanał.",
	L"Nie zostałeś zarejestrowany na zmianę kanału.",
	L"Znajdujesz się już w kanale, na który chcesz zmienić.",
	L"Maksymalna ilość członków została osiągnięta. Nie można już dokonywać wymian.",
	L"Funkcji zmień kanał można użyć tylko w wiosce lub w terenie.",
	L"Spróbuj zmienić kanał później.",
	L"Funkcji nie możesz użyć przy GM.",
	L"Nie wybrałeś jeszcze postaci.",
	L"Znajomy nie jest zalogowany.",
	L"Nieprawidłowy status.",
	L"Baza danych nie zaktualizowała przedmiotu upuszczonego eventu.",
	L"Otrzymałeś już nagrodę eventu.",
	L"Ten gracz jest już na twojej liście znajomych.",
	L"Status postaci znajomego jest nieprawidłowy.",
	L"Ten gracz nie dodał cię do listy znajomych.",
	L"Ten gracz nie jest na twojej liście znajomych.",
	L"Grupa nie istnieje.",
	L"Wiadomość za długa.",
	L"To ta sama grupa, którą chcesz zmienić.",
	L"Nie można zakładać kolejnych grup.",
	L"Ta grupa już istnieje.",
	L"Nazwa grupy już istnieje.",
	L"Uczeń nie zalogował się przez 7 dni. Trening zostanie przerwany.",
	L"Twój uczeń zwiększył poziom. Trening zakończony.",
	L"Postać została skasowana. Trening został zakończony.",
	L"Trening został anulowany.",
	L"Nie zakończyłeś treningu.",
	L"Błąd w bazie danych funkcji listy znajomych.",
	L"Nazwa grupy jest za długa.",
	L"Twoja lista znajomych jest już pełna. Zproszenie nie zostało wysłane.",
	L"Zaproszenia do listy znajomych między postaciami z jednego konta są niemożliwe.",
	L"Lista znajomych gracza jest już pełna. Zproszenie nie zostało wysłane.",
	L"Twoje zaproszenie zostało odrzucone.",
	L"Wyszukiwanie nie powiodło się.",
	L"Nie możesz wejść na kanał PvP.",
	L"Walka PvP rozpoczyna się, jeśli zajęte są wszystkie miejsca.",
	L"Temat za długi.",
	L"Wiadomość za długa.",
	L"Zaproszony gracz nie może wejść na tę planszę.",
	L"Pieczęć została już usunięta.",
	L"Nie można usunąć pieczęci z umiejętności.",
	L"Nieodpowiednia klasa dla przedmiotu!",
	L"Tę umiejętność już odblokowałeś!",
	L"W ekwipunku znajduje się już przedmiot o takiej samej funkcji. Towaru nie można było kupić.",
	L"Graczy z próbnym ID nie można zaprosić do czasoprzestrzeni Henira.",
	L"Nieprawidłowy rodzaj certyfikacji.",
	L"Przedmiotów znajdujących się w banku nie można zdemontować.",
	L"Przedmioty, które znajdują się w banku nie można umieścić w slocie.",
	L"Funkcji nie możesz używać w banku.",
	L"Nie można zwiększyć ilości okienek banku.",
	L"Możesz kupić tylko jedną kartę członkowską do banku.",
	L"Nie można kupić karty członkowskiej.",
	L"Jeśli posiadasz w ekwipunku Zaświadczenie od Laury, możesz kupić platynową kartę członkowską. Użyj Zaświadczenie od Laury.",
	L"Hasło nie istnieje.",
	L"Nie można zmienić hasła.",
	L"Nieprawidłowa nazwa użytkownika lub nieprawidłowe hasło.",
	L"Wystąpił błąd podczas autoryzacji.",
	L"Przedmiot nie istnieje.",
	L"Informacja o przedmiocie niedostępna.",
	L"Nie można dodać pieczęci do przedmiotów tego rodzaju.",
	L"Do założonych przedmiotów nie można dodać pieczęci.",
	L"Do przedmiotu dodano już pieczęć.",
	L"Do uszkodzonego przedmiotu nie można dodać pieczęci.",
	L"Nie możesz dodać pieczęci do przedmiotów, które posiadają okres ważności.",
	L"Do zniszczonych przedmiotów nie można dodać pieczęci.",
	L"Nie można dodać pieczęci do przedmiotów, którymi handlujesz.",
	L"Nie można dodać więcej pieczęci.",
	L"Nieprawidłowa informacja wybranego zwoju pieczęci.",
	L"Dodanie pieczęci nie powiodło się.",
	L"Za mało zwojów pieczęci!",
	L"Nie można usunąć pieczęci na założonych przedmiotach.",
	L"Z przedmiotu usunięto już pieczęć.",
	L"Usunięcie pieczęci nie powiodło się.",
	L"Aktualizacja w bazie danych informacji dotyczących dodania pieczęci nie powiodła się.",
	L"Przedmiotów z pieczęcią nie można ulepszyć.",
	L"Błąd systemu w zapytaniu o monety EL.",
	L"Konto ma ograniczony zasięg aktywności.",
	L"Konto nie istnieje.",
	L"Nieprawidłowe konto.",
	L"Niepoprawny numer kuponu.",
	L"Ten kupon został już zrealizowany.",
	L"Ten rodzaj kuponu można użyć tylko raz.",
	L"Kupon jest nieważny.",
	L"Wystąpił błąd systemu podczas realizacji kuponu.",
	L"Za mało monet EL",
	L"Wystąpił błąd systemu podczas zakupu.",
	L"Zakup możliwy dopiero od poziomu 15.",
	L"Jesteś już zarejestrowany w jednej z gildii.",
	L"Nazwa gildii już istnieje.",
	L"Przedmiotu potrzebnego do założenia gildii nie ma w ekwipunku.",
	L"Nieprawidłowy przedmiot do założenia gildii.",
	L"Założenie gildii nie powiodło się.",
	L"Rejestracja jako mistrz gildii nie powiodła się.",
	L"Nie znaleziono informacji o gildii.",
	L"Nie możesz zaprosić do gildii.",
	L"Gracz jest offline.",
	L"Graczy z próbnym ID nie można zaprosić do gildii.",
	L"Ten gracz został już zaproszony do gildii.",
	L"Inna gildia zaprosiła już tego gracza.",
	L"Nie jesteś upoważniony, by zapraszać do gildii.",
	L"Nie możesz zwiększyć ilości członków. Do tego potrzebujesz przedmiot, dzięki któremu uzyskasz więcej miejsca.",
	L"Zaproszony gracz jest już członkiem gildii.",
	L"Gracz jest już w gildii.",
	L"Nie możesz otworzyć listy członków.",
	L"Przedmiot, który został kupiony kuponem jest uszkodzony.",
	L"Gracz odrzucił zaproszenie do gildii.",
	L"Rejestracja do gildii nie powiodła się.",
	L"Nie należy do żadnej gildii.",
	L"Nie jesteś upoważniony do zmiany rangi członka gildii.",
	L"Ranga członka gildii nie została zmieniona.",
	L"Tylko mistrz oraz administrator gildii mogą zmienić wiadomości gildii.",
	L"Zmiana wiadomości gildii nie powiodła się.",
	L"Nie jesteś upoważniony usunąć członka gildii.",
	L"Mistrz gildii nie może opuścić gildii.",
	L"Opuszczenie gildii nie powiodło się.",
	L"Długość pozdrowienia gildii jest ograniczona.",
	L"Nie jesteś upoważniony do zmiany pozdrowienia gildii.",
	L"Zmiana pozdrowienia gildii nie powiodła się.",
	L"Tylko mistrz gildii jest upoważniony do rozwiązania gildii.",
	L"Gildii nie można rozwiązać. Zarejestrowani są jeszcze członkowie.",
	L"Rozwiązanie gildii nie powiodło się.",
	L"Ranga klasy została już zmieniona.",
	L"Istnieje już administrator gildii.\nZmień rang administratora gildii,\nby powołać innego.",
	L"Mistrz gildii nie może skasować swojej postaci. Przekaż tytuł mistrza gildii innemu członkowi gildii!",
	L"Nie możesz zmienić własnej rangi klasy.",
	L"Nie możesz kupić zezwolenia na założenie gildii, ponieważ należysz już do gildii.",
	L"Posiadasz już zezwolenie na założenie gildii.",
	L"Zwiększenie ilości członków nie powiodła się.",
	L"Kartę rozbudowy może używać tylko mistrz gildii oraz administrator gildii.",
	L"Nie można już przyjąć kolejnych członków do gildii.",
	L"Podczas handlu nie można użyć tej funkcji.",
	L"Nie możesz przejść na ten teren.",
	L"Nazwa tej gildii jest niedostępna przez 7 dni.",
	L"To jest maksymalna ilość punktów doświadczenia.",
	L"Aby kupić wybrany przedmiot, musisz najpierw zaliczyć odpowiednią misję.",
	L"Nazwa gildii jest za długa.",
	L"Masz za mało ED, by usunąć atrybut.",
	L"Ten przedmiot możesz kupić dopiero od poziomu 35.",
	L"게임을 종료하고 빈펀 계정으로 업그레이드 하시기 바랍니다. 빈펀 사이트는 tw.beanfun.gamania.com 입니다.",
	L"이 계정은 이미 빈펀 계정으로 업그레이드 된 계정입니다. 빈펀 프로그램으로 접속해주세요.",
	L"Nie możesz kupić więcej przedmiotów. Tymczasowy ekwipunek jest pełny.",
	L"PUG może używać tylko mistrz gildii.",
	L"Ta umiejętność gildii posiada już najwyższy poziom.",
	L"Informacje o umiejętności gildii nie istnieje.",
	L"Poprzednia umiejętność gildii nie posiada jeszcze najwyższego stopnia.",
	L"Użyłeś za mało punktów umiejętności.",
	L"Za mało PUG.",
	L"Nauka umiejętności gildii nie powiodła się.",
	L"Tylko mistrz gildii może cofnąć umiejętności gildii.",
	L"Potrzebujesz przedmiotu \"Flet Zapomnienia\"!",
	L"Umiejętności gildii nie można cofnąć.",
	L"Cofnięcie umiejętności gildii nie powiodło się.",
	L"Tylko mistrz gildii może cofnąć umiejętności gildii.",
	L"\"Fletu Zapomnienia\" nie ma w ekwipunku.",
	L"Nie można cofnąć umiejętności gildii.",
	L"Cofnięcie umiejętności gildii nie powiodło się.",
	L"Użyć może tylko mistrz gildii.",
	L"Nie uzyskano ograniczonych czasowo punktów umiejętności gildii.",
	L"Używasz już błogosławionego przedmiotu świadomości.",
	L"Nie możesz otrzymać jeszcze nagrody eventu.",
	L"Posiadasz za mało miejsca w ekwipunku, by przyjąć nagrodę eventu.",
	L"Wystąpił błąd podczas otrzymania nagrody eventu.",
	L"To nie modus przedmiotu.",
	L"Pozostał jeszcze przedmiot upuszczenia.",
	L"Brak dostępu do przedmiotu upuszczonego w PvP.",
	L"Po użyciu karty postaci, możesz stworzyć klasę.",
	L"Konto nie może wziąć udziału w event'cie.",
	L"Funkcji może użyć tylko mistrz lub administrator gildii.",
	L"PC방 전용 아이템은 이용할 수 없는 기능입니다.",
	L"Ogłoszenie gildii nie istnieje.",
	L"Tekst jest za długi.",
	L"Wygasł czas rejestracji ogłoszenia.",
	L"Za mało ED, by zarejestrować ogłoszenie.",
	L"Jedno ogłoszenie zostało już zarejestrowane.",
	L"Rejestracja ogłoszenia gildii nie powiodła się.",
	L"Za dużo wniosków, nie można przeprowadzić rejestracji.",
	L"Rejestracja gildii nie powiodła się.",
	L"Zgłosiłeś już rejestrację.",
	L"Nie istnieje informacja dotycząca wniosku o rejestrację.",
	L"Przyjęcie rejestracji gildii nie powiodło się.",
	L"Usunięcie wniosku o rejestrację gildii nie powiodło się.",
	L"Przy ogłoszeniu ograniczonym czasowo nie można złożyć wioski o rejestracjÄ.",
	L"Nie jesteś upoważniony do sprawdzenia listy zgłoszeń do rejestracji gildii.",
	L"Nie otworzyłeś zamka.",
	L"Konto zostało tymczasowo zablokowane.",
	L"",
	L"",
	L"Zostałeś usunięty z planszy z powodu podejrzenia o hacking.",
	L"Ponieważ jest aktywna opcja \"Odmów zaproszenie do gildii\", nie możesz złożyć wniosku o rejestrację.",
	L"Ponieważ istnieje dużo wniosków o rejestrację gildii, nie możesz złożyć wniosku o rejestrację.",
	L"To nie jest aktualne wykonywana misja.",
	L"Limit zakupu danego przedmiotu został osiągnięty.",
	L"Zdezaktywowane monety El. Zmień ustawienia na stronie internetowej w opcji \"Moje informacje\", w menu \"Cash -Bezpieczeństwo\".",
	L"Przeprowadzono sprawdzanie aktualnego statusu.",
	L"Przeszukanie bazy danych względem WebPoint nie powiodło się.",
	L"Sprawdzanie statusu nie funkcjonuje.",
	L"Z powodu podwójnej rejestracji do grupy, opuściłeś grupę.",
	L"Status grupy ładuje się.",
	L"Usuń listę przedmiotów",
	L"Dodaj listę przedmiotów",
	L"Edytuj listę przedmiotów",
	L"Nieprawidłowy wybór kategorii.",
	L"Wyszukiwanie nie przyniosło żadnych wyników.",
	L"Siła woli zaproszonego jest niewystarczająca.",
	L"Rozpocznij wyszukiwanie za chwilę ponownie.",
	L"W tym sklepie sprzedaż została zakończona.",
	L"Gracz nie ma statusu kupna.",
	L"Stworzenie planszy nie powiodło się.",
	L"Przedmiot nie istnieje.",
	L"Strona nie istnieje.",
	L"Notatka została już zarejestrowana.",
	L"Notatka nie została zarejestrowana.",
	L"Nie posiadasz Notatnika Techniki.",
	L"Dodanie notatki technicznej nie powiodło się.",
	L"Posiadasz już tę notatkę techniczną.",
	L"Musisz osiągnąć poziom 20, by kupić ten przedmiot.",
	L"Z graczami na innych serwerach nie można handlować.",
	L"Nie można użyć straganów znajdujących się na innych serwerach.",
	L"Nie możesz zaprosić do gildii graczy z innego serwera.",
	L"Gracze z innych serwerów nie mogą zostać zarejestrowani jako uczniowie.",
	L"Graczy z innych serwerów nie możesz dodać jako znajomych.",
	L"Nie możesz grać w Czasoprzestrzeni Henira (tryb: wyzwanie) wraz z postaciami z innych serwerów.",
	L"Blokada dostępu z powodu podejrzenia hackingu.",
	L"[홍콩] 해당 직업으로는 전직을 할 수 없습니다.",
	L"Ilość przedmiotów, które chcesz wyrzucić jest nieprawidłowa.",
	L"Stworzenie zwierzaka nie powiodło się.",
	L"Nazwa jest już używana.",
	L"Nazwa jest ograniczona do 12 znaków.",
	L"Zwierzak tworzony.",
	L"Nie można było przywołać zwierzaka.",
	L"Tutaj nie możesz stworzyć zwierzaka.",
	L"Przywołałeś już zwierzaka.",
	L"Zwierzak został już przywołany.",
	L"Nie można było odesłać zwierzaka.",
	L"Rozkaz nie został wykonany.",
	L"Twój zwierzak jest nażarty. Chwilowo więcej już nie zje.",
	L"Nie można było nakarmić zwierzaka.",
	L"Twój zwierzak jest w fazie wzrostu i je tylko owoce i nasiona z drzewa EL.",
	L"To zostało już zapisane.",
	L"Kolejny etap rozwoju jeszcze jest niedostępny.",
	L"Dalszy rozwój będzie możliwy dopiero, gdy zażyłość osiągnie poziom 100%.",
	L"Zwierzak nie może używać tego przedmiotu.",
	L"Poziom karmy jest za niski.",
	L"Dane loginu są nieprawidłowe.",
	L"Dane loginu są nieprawidłowe.",
	L"Konto nie zostało jeszcze aktywowane.",
	L"Zwierzak nie może jeść tej karmy.",
	L"Gracz zajęty.",
	L"[CN] 매트릭스 카드가 바인딩되어 있습니다.",
	L"[CN] OPT번호가 틀렸습니다. 다시 입력해 주십시요.",
	L"[CN] 보안카드 번호를 잘못 입력 하셨습니다. 다시 입력해 주십시요.",
	L"[CN] 계정 정보가 수정 과정에 있습니다. 의문 사항이 있으시면 서비스 센터로 연락 바랍니다.",
	L"[CN] 자이언트 패스워드 보안이 바인딩 해제 상태에 있습니다. 의문사항이 있으시면 서비스 센터로 연락 바랍니다.",
	L"GM키에란",
	L"GM리엘",
	L"[Nieznany nadawca]",
	L"지금은 청약철회 기능을 이용 하실 수 없습니다.",
	L"청약철회 가능 개수보다 요청 갯수가 커서 청약철회를 실패하였습니다.",
	L"구매한지 7일이 초과된 상품으로 청약철회가 불가능 합니다.",
	L"패키지 중 일부 상품을 수령하여 청약철회가 불가능 합니다.",
	L"상품 가격이 0원으로 청약철회가 불가능한 상품 입니다.",
	L"중복된 RequestID입니다.",
	L"Nie istnieją informacje o zakupie tego towaru.",
	L"Nie istnieją informacje dotyczące tego towaru.",
	L"청약철회가 불가능한 상품 입니다.",
	L"선물 받은 상품이어서 청약철회가 불가능 합니다.",
	L"Nie można wyrzucać przedmiotów ograniczonych czasowo.",
	L"Towarów, których nie można sprzedać, nie można też wyrzucić.",
	L"1 EL coins 이벤트 구매 제한을 초과 하여 더 이상 구매 할 수 없습니다. ",
	L"Twój poziom jest za niski na ten przedmiot.",
	L"Od 11 poziomu upgrade'u nie można używać kamieni fluorowych.",
	L"Nie możesz przyjąć tej misji, ponieważ otrzymałeś już nagrodę.",
	L"Nie możesz przyjąć misji, ponieważ w twoim ekwipunku nie ma miejsca na nagrodę.",
	L"Użycie magicznego kamienia nie powiodło się.",
	L"Funkcja momentalnie niedostępna.\nPrzepraszamy.",
	L"Dostęp z tego adresu IP jest ograniczony.",
	L"Funkcja czatu została ograniczona.",
	L"Funkcja handlu została ograniczona.",
	L"Gra nie może zostać uruchomiona, ponieważ przedmiot nie istnieje.",
	L"Gra jest zakłócana przez inny program.",
	L"해당 유저가 존재하지 않습니다.",
	L"잔액이 부족합니다.",
	L"존재하지 않는 아이템 카드입니다.",
	L"해당 카드는 해당 구역에서 사용이 불가능합니다.",
	L"이미 사용한 아이템 카드입니다.",
	L"잘못된 전용 카드 ID입니다.",
	L"잘못된 전용 카드 패스워드입니다.",
	L"DB 에러",
	L"Nie możesz wysłać wiadomości, ponieważ twoje działania są ograniczone.",
	L"Nie możesz otworzyć straganu, ponieważ nastąpiło ograniczenie handlu.",
	L"Nie możesz wyświetlić swojego straganu, ponieważ nastąpiło ograniczenie handlu.",
	L"Nie możesz szukać towarów, ponieważ nastąpiło ograniczenie handlu.",
	L"Nie możesz wejść na rynek, ponieważ nastąpiło ograniczenie handlu.",
	L"캐시 인벤토리에 아이템이 존재합니다.(HK 이벤트에 사용)",
	L"Potrzeba co najmniej trzech graczy w grupie.",
	L"Plansza jest zamknięta i dlatego nie można na nią wejść.",
	L"Nie możesz wejść na planszę światowej misji wraz z innymi graczami z tego serwera.",
	L"Log nadzoru poczty kosztuje tyle samo.",
	L"Log nadzoru sprzedaży kosztuje tyle samo.",
	L"Log nadzoru poczty nie powiódł się.",
	L"Log nadzoru sprzedaży nie powiódł się.",
	L"Nie możesz dezaktywować agentki, ponieważ nadal trwa sprzedaż towarów.",
	L"Agentka nie jest aktywna.",
	L"Nie możesz anulować procesu kupna.",
	L"To jest prywatna sprzedaż: Nie można kupować przedmiotów.",
	L"Nie możesz otworzyć straganu, ponieważ nadal jest aktywna agentka.",
	L"Twój stragan zostanie zamknięty, ponieważ naruszyłeś/aś regulamin.",
	L"Nie możesz dezaktywować agentki.",
	L"Unregisted User.",
	L"It is already canceled.",
	L"Invalid coupon number.",
	L"This coupon can not be canceled.",
	L"The used user information and cancel the requested user information does not match.",
	L"The issued cash by coupons  already had used . so can not be canceled.",
	L"requested price should be equal to billing items price.",
	L"The balance short.",
	L"Billing account that is unavailable.",
	L"You can not register any more today.",
	L"This coupon can not verify the information.",
	L"Coupon is already used.",
	L"Coupon use is stopped.",
	L"Coupon is expired.",
	L"Coupon is not available in the game.",
	L"Issued to certain customers who can use coupons, you do not have permission.",
	L"Buying is a restricted user.",
	L"Your use is limited to the payment service.",
	L"Your use is limited to the purchase service.",
	L"User cannot be verified.",
	L"Registration has exceeded the number of coupons available.",
	L"Unable to login due to IP restriction.",
	L"The coupon code has already been redeemed.",
	L"You cannot purchase the item at the moment. Your account have reached the daily limit for purchasing the item.",
	L"Wprowadziłeś 2 razy niepoprawne hasło i dlatego nie możesz się zalogować.",
	L"Jeśli chcesz sprzedawać towary za pomocą agentki, musisz zawrzeć umowę.",
	L"Podane PINy nie są identyczne.",
	L"Podałeś 10 razy niepoprawny PIN.\nKliknij przycisk \"Zatwierdź\", aby przerwać połączenie.\nZaloguj się potem ponownie na naszej stronie, aby cofnąć wprowadzenie danych.",
	L"Utworzenie PINu nie powiodło się.",
	L"Niepoprawny PIN",
	L"Nazwa przedmiotu jest za długa.",
	L"Stragan agentki został zamknięty.\nPo otrzymaniu swoich towarów, możesz otworzyć nowy stragan.",
	L"Towary te znajdują się w straganie agentki.\nJeśli chcesz otrzymać złoto za sprzedane towary,\nmusisz zamknąć stragan agentki.",
	L"DB-Query umowy agentki nie powiódł się.",
	L"Agentka nie mogła zostać aktywowana.",
	L"Towary nie mogły zostać wstawione do straganu agentki.",
	L"Tylko zleceniodawca agentki może tego użyć.",
	L"Przedmioty nie mogły zostać przekazane agentce.",
	L"Nie możesz przyjąć przedmiotu, który jest akurat sprzedawany.",
	L"Otrzymałeś/aś już ten przedmiot.",
	L"Posiadasz już maks. ilość ED. Nie możesz zbierać więcej ED.",
	L"Nie masz już miejsca w ekwipunku.",
	L"Nie posiadasz przedmiotów.",
	L"Nie możesz kupować tych samych towarów w tym samym czasie.",
	L"Masz za niski poziom.\nNie możesz sporządzać grupowych zapytań.",
	L"Nie możesz kupować towarów, ponieważ nadal jest aktywna agentka.",
	L"Musisz jeszcze przyjąć przedmioty, zanim zaczniesz sprzedaż następnych przedmiotów.",
	L"Wszystkie towary zostały sprzedane. Agentka zamyka stragan.",
	L"Już akceptowałeś/aś tę misję i otrzymałeś/aś nagrodę. Nie możesz jej zatem przyjąć ponownie.",
	L"Nie możesz przyjąć tej misji, ponieważ nie masz już miejsca w ekwipunku.",
	L"Zmiana minimalnego poziomu grupy nie powiodła się.",
	L"Nie możesz otworzyć straganu, ponieważ agentka sprzedała wszystkie towary.",
	L"(TW/HK)강화 보조 아이템 사용 불가",
	L"(TW/HK)강화 보조 아이템이 없습니다.",
	L"(TW/HK)파괴 방지 아이템 사용 불가",
	L"(TW/HK)파괴 방지 아이템이 없습니다.",
	L"Twój poziom jest zbyt niski.\nWybierz inną planszę lub usuń ograniczenie poziomu.",
	L"Twój poziom jest zbyt niski.\nNie możesz utworzyć ograniczenia poziomu.",
	L"Poziom zaproszonego gracza jest za niski.",
	L"Twój poziom jest zbyt niski.\nWybierz planszę, która odpowiada Twojemu poziomowi.",
	L"PIN nie może zawierać dwóch tych samych cyfr z rzędu.\n(0000, 1111, 999999, etc.)",
	L"Nie używaj następujących po sobie liczb w PINie.\n(1234, 9876, 123456, etc.)",
	L"Skasowanie drugiego PIN-Padu nie powiodło się.",
	L"2. PIN-Pad nie jest w użytku.",
	L"Nowy PIN musi się różnić od starego.",
	L"Przedmiot nie jest sprzedawany w sklepie.",
	L"Dobieranie zostało zakończone przez rozpoczęcie PvP.",
	L"Gracz nie może wziąć udziału w dobieraniu PvP.",
	L"Dobieranie zostało przerwane.",
	L"Dobieranie zostało anulowane, ponieważ dany członek grupy nie wziął udziału w PvP.",
	L"Dobieranie zostało pomyślnie zakończone. Zostanie usunięty/a z listy oczekujących.",
	L"Użytkownik anulował rejestracje do dobierania i dlatego został usunięty z listy oczekujących.",
	L"Jeden z graczy opuścił grupę, rejestracja do dobierania została zatem anulowana.",
	L"Dobieranie jest już w toku.",
	L"Dane członka grupy są błędne.",
	L"Dane trybu PvP są błędne.",
	L"Udział w trybie PvP jest możliwy dopiero od poziomu 10.",
	L"Dopiero od poziomu 10. możesz dołączyć do grupy PvP.",
	L"Już mieniłeś/aś tryb PvP.",
	L"Nie możesz przejść z czterema graczami planszy do grupy PvP.",
	L"Nie można zmienić trybu PvP.",
	L"Nie można zmienić pomieszczenia PvP, ponieważ jeden z graczy w grupie nie osiągnął jeszcze poziomu 10.",
	L"Jeden z graczy w grupie nie osiągnął jeszcze poziomu 10. i dlatego nie może wejść do pomieszczenia PvP.",
	L"Tylko postacie od poziomu 10. mogą zostać zaproszone do grupy PvP.",
	L"Tylko postać od poziomu 10. może założyć grupę.",
	L"[CN]전환이 정상적으로 이루어지지 않았습니다. 다시 시도하여 주시기 바랍니다.",
	L"Sortowanie przedmiotów nie powiodło się. Spróbuj proszę ponownie później.",
	L"Nie zgłosiłeś/aś się do dobierania.",
	L"Już jesteś w pomieszczeniu PvP.",
	L"To nie jest pomieszczenie PvP.",
	L"Zapytanie nie powiodło się.",
	L"Nie możesz zaprosić użytkownika, który zgłosił się do dobierania.",
	L"Nie możesz zaprosić użytkownika znajdującego się w trakcie dobierania.",
	L"Twoja ranga jest zbyt niska, by kupić ten przedmiot.",
	L"Podczas dobierania nie można się zgłosić do innej grupy.",
	L"Podczas dobierania nie możesz zmienić grupy.",
	L"Podczas dobierania nie możesz zmienić kanału.",
	L"ID nie zostało rozpoznane.",
	L"ID jest zalogowane równocześnie w kilku kanałach.",
	L"Dzisiaj nie możesz już przyjąć misji losowej.",
	L"Nie akceptuję umowy.",
	L"Błąd przy wyświetlaniu PU",
	L"Błąd przy wprowadzeniu PU",
	L"Błędna nazwa BD",
	L"Sprawdzanie danych nie powiodło się.",
	L"죄송합니다. 캐쉬샵 점검으로 인해 이용하실 수 없습니다.",
	L"00시부터 06시까지 게임 접속이 제한됩니다.",
	L"Nie znaleziono żadnych informacji.",
	L"Nie możesz handlować, dopóki nie zarejestrujesz się jako poszukiwacz przygód.",
	L"Nie możesz wysyłać żadnych wiadomości, dopóki nie zarejestrujesz się jako poszukiwacz przygód.",
	L"[CN]사용실패!",
	L"Opuściłeś pole walki.",
	L"Można nabyć dopiero od poziomu 15.",
	L"ServerSN과 MachineID가 매칭되지 않는다.",
	L"MachineID와 ServerSN이 매칭되지 않는다.",
	L"DB에 존재 하지 않는 ServerSN이 있다.",
	L"DB에 존재 하지 않는 MachineID가 있다.",
	L"클라가 준 SN은 없는데 DB에는 MachineID에 해당하는 SN 존재.",
	L"제재된 SN입니다.",
	L"접속 제한된 ServerSN 입니다.",
	L"Nie możesz się zalogować tym kontem na serwer testowy.",
	L"Grupa została przez ciebie automatycznie opuszczona wskutek integracji.",
	L"Nie można zakupić tego przedmiotu, ponieważ jest już aktywne nieograniczone czasowo rozszerzenie slotów umiejętności.",
	L"Nie można zakupić tego przedmiotu, ponieważ jest już aktywne nieograniczone czasowo rozszerzenie slotów umiejętności.",
	L"[CN] 귀하의 계정이 정지되었습니다. 고객 센터에 문의하여 주십시요.",
	L"[CN] 비밀번호를 잘못 입력 하셨습니다. 다시 입력해 주십시요.",
	L"[CN] 해당 계정은 존재하지 않습니다.",
	L"[CN] 불명확인 시스템 에러",
	L"Posiadasz już medal błogosławieństwa w ekwipunku, dlatego nie możesz otworzyć kostki.",
	L"Nie możesz kupić tego przedmiotu, ponieważ posiadasz zbyt niski poziom.",
	L"Twój poziom jest zbyt niski, aby nabyć ten towar.",
	L"Stworzenie grupy nie powiodło się!",
	L"Niewystarczająca ilość członków grupy",
	L"Opóźnienie odpowiedzi zaproszonych członków grupy",
	L"Towar ten nie jest na sprzedaż.",
	L"[JP] 한게임 빌링 오류로 구매할수 없습니다.",
	L"Przedmiotów z systemu bankingu nie można przesyłać mailem.",
	L"Nie można handlować przedmiotami z systemu bankingu.",
	L"Ten przedmiot można nabyć dopiero od poziomu 20.",
	L"Tej wymiany mogą dokonać jedynie postacie należące do gildii.",
	L"Można kupić dopiero od poziomu 30.",
	L"Zapytania o uczestnictwo dla grup PvP możliwe są wyłącznie z pełnym patchem.",
	L"블랙리스트에 등록된 DLL 이 존재합니다.",
	L"Zaloguj się na nowo lub spróbuj ponownie nieco później.",
	L"Dzisiaj już nie możesz wziąć udziału w quizie.",
	L"Nieznany błąd",
	L"Podczas ograniczenia handlu nie możesz kupować żadnych przedmiotów.",
	L"Nie można użyć podczas ograniczenia handlu.",
	L"Nie możesz już poszerzyć paska szybkiego dostępu.",
	L"Ta postać została już skasowana lub zostanie wkrótce skasowana.",
	L"Skasowanie postaci jest obecnie niemożliwe.",
	L"Ostateczne skasowanie postaci jest obecnie niemożliwe.",
	L"Tej postaci nie można skasować ostatecznie.",
	L"Tej postaci nie można przywrócić po skasowaniu.",
	L"Przywrócenie postaci jest obecnie niemożliwe.",
	L"Spróbuj ponownie później.",
	L"Nie ma takiej postaci.",
	L"Nie można było skasować postaci.",
	L"Zmiana nazwy zwierzaka nie powiodła się.",
	L"Zmiana nazwy zwierzaka jest już w toku.",
	L"Gra została przerwana.",
	L"Nie jesteś mistrzem gildii.",
	L"Dane dotyczące przedmiotu są błędne.",
	L"Zmiana nazwy gildii nie powiodła się.",
	L"W toku...",
	L"Próbowałeś/aś skasować nieistniejący przedmiot.",
	L"[TW] 낚시대를 장착하지 않았거나, 미끼가 없습니다.",
	L"[TW] 이미 사용중인 낚시터 입니다.",
	L"[TW] 낚시터에 문제가 있습니다. 다른 곳을 이용해 주세요.",
	L"[TW] 낚시 보상에 문제가 발생했습니다.",
	L"Skasowanie przedmiotu nie powiodło się.",
	L"Tylko mistrz gildii posiada prawa do zmiany nazwy swojej gildii.",
	L"펫이 있을 때만 사용이 가능합니다. 펫이 없을 경우 일주일 이내에 청약 철회를 하셔야 합니다.",
	L"Czas opracowania minął, proces został anulowany. Spróbuj ponownie później.",
	L"Użytkownika anulował zmianę nazwy gildii.",
	L"Nie jesteś w odpowiednim stanie, aby dotrzeć do tego miejsca.",
	L"Już jesteś w tym miejscu.",
	L"To miejsce jest już pełne, nie możesz się tam udać.",
	L"Nie możesz udać się do tego miejsca, ponieważ znajduje się tam już kilka grup.",
	L"Wejście do tego miejsca nie powiodło się.",
	L"Dane dotyczące miejsca, do którego chcesz się udać, są błędne.",
	L"Podczas wchodzenia do tego miejsca wystąpił błąd.",
	L"W danym miejscu nie można było znaleźć informacji na temat użytkownika.",
	L"Start gry na planszy poprzez automatyczne połączenie grup nie powiódł się.",
	L"Start gry na planszy nie powiódł się.",
	L"Obecnie nie skorzystać z opcji automatycznego połączenia grup.",
	L"Obecnie nie możesz przeprowadzić automatycznego połączenia grup. Zaczekaj chwilę.",
	L"Opcja automatycznego połączenia grup została już aktywowana.",
	L"Automatyczne połączenie grup nie powiodło się wskutek błędnych danych.",
	L"Rejestracja do automatycznego połączenia grup nie powiodła się.",
	L"Nie jesteś w odpowiednim stanie, aby skorzystać z opcji automatycznego połączenia grup.",
	L"Gry nie można rozpocząć, ponieważ grupa składa się tylko z 1 osoby.",
	L"Jeden z użytkowników znajdujących się grupie dokonał anulowania.",
	L"Gra nie rozpocznie się, ponieważ upłynął czas odpowiedzi na rozpoczęcie gry w grupie.",
	L"Należysz już do grupy.",
	L"Zaproszony gracz czeka na przyjęcie do innej grupy.",
	L"Obecnie nie należysz do grupy.",
	L"Cudowny środek i tajny napój nakładają się, więc nie można z nich skorzystać.",
	L"ServerSN이 중복 접속 중이다.",
	L"ServerSN 존재하지 않는데 삭제하려한다.",
	L"Obecnie nie można skorzystać z tej funkcji.",
	L"넥슨 통합 맵버쉽 계정 인증 상향 조정 필요.",
	L"Twoje ciało osiągnęło już granice wydajności. Nie możesz użyć tajnego napoju.",
	L"Nie spełniasz min. warunków poziomowych. Gra na tej planszy nie może się rozpocząć.",
	L"[US] 추천받을 대상이 아닙니다.",
	L"[US] 추천인이 이미 3인을 추천하였습니다.",
	L"[US] 추천 가능한 유저가 아닙니다.",
	L"[US] 맞지 않는 아이템을 사용하였습니다.",
	L"Okienko postaci nie mogło zostać powiększone. Maksymalnie dozwolonych 8 okienek.",
	L"Koniec automatycznego połączenia grup wskutek rozpoczęcia planszy.",
	L"Jeden z uczestników automatycznego połączenia grup nie zgodził się na rozpoczęcie gry.",
	L"Automatyczne połączenie grup powiodło się.",
	L"Któryś z członków grupy nie zgodził się na rozpoczęcie gry w automatycznym połączeniu grup. Automatyczne połączenie grup zostało przerwane.",
	L"Automatyczne połączenie grup powiodło się. Twój nick został usunięty z listy oczekujących.",
	L"Opcja automatycznego połączenia grup została dezaktywowana. Nick został usunięty z listy oczekujących.",
	L"Opcja automatycznego połączenia grup została dezaktywowana wskutek opuszczenia grupy przez jednego z graczy.",
	L"Za niski poziom przedmiotu. Nie możesz rozpocząć planszy.",
	L"Nie można zapisać konfiguracji klawiatury.",
	L"Nie można było zapisać danych konfiguracji klawiatury.",
	L"Nie można było wczytać konfiguracji klawiatury.",
	L"Nie można było wczytać danych konfiguracji klawiatury.",
	L"Odpowiedź na rozpoczęcie gry grupy na planszy opóźni się.",
	L"[US] 추천인 테이블에서 캐릭터 삭제를 실패하였습니다.",
	L"[US] 보안패드 리셋용 질문 및 답변을 입력하지 않았습니다.",
	L"Gracz ten nie należy do tej samej grupy.",
	L"Nie można było zapisać danych wyboru czatu.",
	L"Nie można było wczytać danych wyboru czatu.",
	L"Nie można było wczytać niektórych danych wyboru czatu.",
	L"Test",
	L"셧다운제에 의하여 게임이용이 차단 됩니다.",
	L"선택적 셧다운제의 의해 게임이용이 차단됩니다.",
	L"통합 맴버십 ATL 2.0 유저가 아니므로 게임이용이 차단 됩니다.",
	L"셧다운제에 의하여 게임이용이 차단 됩니다.",
	L"선택적 셧다운제의 의해 게임이용이 차단됩니다.",
	L"통합 맴버십 ATL 2.0 유저가 아니므로 게임이용이 차단 됩니다.",
	L"Otwarcie nie jest jeszcze możliwe.",
	L"Czas otwarcia minął.",
	L"ServiceID가 잘못 되었습니다.",
	L"캐시 잔액 정보를 찾을 수 없습니다.",
	L"[TW]ServiceCode 가 올바르지 않습니다.",
	L"[TW]정의되지 않은 애러 발생했습니다.",
	L"[TW]시간형식이 잘못되었습니다.",
	L"[TW]Type정보가 잘못되었습니다.",
	L"[TW]이전 상품 구매가 진행 중입니다.",
	L"Twój poziom jest zbyt wysoki do tej misji.",
	L"파라매터 갯수 입력이 잘못되었습니다.",
	L"[JP] 합성제가 없습니다.",
	L"[JP] 없는 아바타를 합성하려고 했습니다.",
	L"[US]월 선물 가능 횟수를 초과하였습니다.",
	L"Na tę planszę można się udać tylko w pojedynkę.",
	L"Plansza ta nie jest jeszcze otwarta.",
	L"Postać nie została poprawnie wybrana.",
	L"Postać nie może wysłać prywatnej wiadomości do siebie samej.",
	L"W informacji o zwierzaku wystąpił błąd.",
	L"Możesz tego użyć, tylko gdy przywołasz zwierzaka.",
	L"Do użycia jedynie przez zwierzaki w fazie młodzika.",
	L"Do użycia przez zwierzaki jedynie w fazie dzieciaka.",
	L"Ustawienie liczby TAGów jest błędne.",
	L"Rozgrywkę można rozpocząć z min. dwoma członkami drużyny.",
	L"",
	L"",
	L"",
	L"",
	L"Opuściłeś planszę.",
	L"Opuściłeś zawody.",
	L"Następuje wyjście z powodu zmiany kanału.",
	L"Następuje wyjście z powodu odwiedzin przez tych samych członków grupy.",
	L"Następuje wyjście z powodu użycia przedmiotu do poruszania się do przodu.",
	L"Wyjście z powodu nieprawidłowego zakończenia.",
	L"Podczas gdy grasz na planszy, nie możesz zapraszać nowych członków grupy.",
	L"Zaproszenie nie jest możliwe, ponieważ gracz należy już do innej grupy.",
	L"Osoba jest w trakcie zawodów, dlatego nie można jej zaprosić.",
	L"Osoba znajduje się właśnie na planszy, dlatego nie można jej zaprosić.",
	L"Nie udało się znaleźć gracza na tym serwerze.",
	L"Nie można zapraszać dalszych członków grupy.",
	L"W trakcie zawodów nie można zapraszać członków grupy.",
	L"Twój poziom jest zbyt niski, byś mógł wejść na to pole.",
	L"Nie przeszedłeś jeszcze plansz, które są warunkiem wejścia na to pole.",
	L"Można zrealizować maksymalnie 30 misji.",
	L"Masz za mało ED.",
	L"Nie można zaprosić gracza, który korzysta z automatycznego tworzenia grupy.",
	L"Jeśli opcja automatycznego tworzenia grupy jest aktywna, nie możesz zaprosić nikogo do swojej grupy.",
	L"W pokoju PvP nie możesz zapraszać żadnych członków grupy.",
	L"Podczas treningu nie możesz zapraszać członków grupy.",
	L"Podczas dobierania PvP nie możesz zapraszać członków grupy.",
	L"Dopóki korzystasz z opcji automatycznego tworzenia grupy, manualne zaproszenia do grupy są niedostępne.",
	L"Jeśli korzystasz z opcji dobierania PvP, nie możesz zapraszać członków grupy.",
	L"Ty i twoja grupa znajdujecie się na tym samym polu.",
	L"Ponieważ ta osoba jest kandydatem do innej grupy, nie można jej zaprosić.",
	L"",
	L"",
	L"Ten nick jest niedostępny.",
	L"ID grupy serwera jest nieprawidłowy.",
	L"",
	L"Gracze, którzy nie posiadają uprawnienia do udziału w zawodach online, nie mogą używać kanału PvP.",
	L"Aby otworzyć kostkę, potrzebujesz przedmiotów i ED.",
	L"Masz zbyt mało ED, aby otworzyć kostkę.",
	L"Rozgrywka rozpocznie się z aktualną liczbą uczestników.",
	L"",
	L"",
	L"",
	L"Event dobiegł końca.",
	L"Nie możesz zdobyć tego przedmiotu za pomocą Ary.",
	L"",
	L"Maksymalna liczba wymian została już niestety osiągnięta.\nPo aktualizacji w dniu 17.01 zostaną aktywowane dodatkowe wymiany.",
	L"",
	L"Ten zwierzak nie istnieje.",
	L"Ta funkcja jest już używana.",
	L"Można używać dopiero od poziomu 'Dzieciak'.",
	L"Podczas oczekiwania na grę nie możesz zmieniać swoich slotów umiejętności.",
	L"Ponieważ nie przebywasz aktualnie w pokoju, nie można było załadować informacji o potworach z terenu.",
	L"Ponieważ nie przebywasz aktualnie w pokoju, nie można było załadować informacji o potworach z terenu.",
	L"Zakup przedmiotu do rozszerzania slotów nie powiódł się. Rozszerzenie slotów jest możliwe tylko do maks. 30 sztuk.",
	L"Wykluczenie z planszy było skutkiem głosowania o wykluczeniu.",
	L"Osoba głosująca nie jest prawdziwym graczem.",
	L"Osoba, której ma dotyczyć głosowanie, nie jest prawdziwym graczem.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Masz za mało ED, aby opublikować zaproszenie.",
	L"Nie możesz zarejestrować się do gildii, ponieważ posiada ona już maks. ilość członków.",
	L"Zapytanie nie mogło zostać wysłane.",
	L"Poszukiwanie gildii nie mogło zostać opublikowane.",
	L"Istnieje już taka wiadomość.",
	L"Poszukiwanie gildii zostało już opublikowane.",
	L"Wiadomość nie mogła zostać opublikowana.",
	L"Masz za mało ED, aby opublikować poszukiwanie gildii.",
	L"Brak zaproszenia gildii",
	L"Brak podań gildii",
	L"Taka gildia nie istnieje.",
	L"Nie masz praw, by zobaczyć listę zaproszonych użytkowników.",
	L"Osiągnięto limit wejść na planszę.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Nie posiadasz \"Instrukcji na temat terenów\".",
	L"Wpisanie rozdziału nie powiodło się.",
	L"Rozdział ten jest już wpisany.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Błąd w obliczeni czasu VIP.",
	L"",
	L"",
	L"",
	L"",
	L"Poziom przedmiotu nie odpowiada temu zwojowi czasoprzestrzeni!",
	L"Przedmiot ten został już zidentyfikowany.",
	L"Brak przedmiotów w ekwipunku",
	L"Nie posiadasz wystarczającej ilości ED, by zidentyfikować ten przedmiot.",
	L"Identyfikacja nie powiodła się.",
	L"Za mało błogosławionych zwojów czasoprzestrzeni",
	L"Tego przedmiotu nie da się zidentyfikować.",
	L"",
	L"",
	L"Tego przedmiotu nie da się wymienić.",
	L"Nie posiadasz wystarczającej ilości ED, aby uiścić opłatę za wymianę.",
	L"",
	L"",
	L"",
	L"",
	L"Nie posiadasz więcej przedmiotów nadających się do wymiany.",
	L"Wymiana przedmiotów nie powiodła się.",
	L"",
	L"",
	L"Materiały oraz przedmioty z ograniczeniem czasowym nie podlegają wymianie.",
	L"Materiały oraz przedmioty z ograniczeniem czasowym nie podlegają wymianie.",
	L"Brak spełnienia wymogów",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Nie można robić zakupów, mając zablokowane konto.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Z powodu błędu w pliku CheckKom.xml program zostanie zamknięty.",
	L"",
	L"Błędna informacja etapu",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Co najmniej jeden warunek nie został spełniony. Sprawdź, czy przywołałeś zwierza.",
	L"Co najmniej jeden warunek nie został spełniony. Sprawdź, czy możesz użyć zwierza.",
	L"Zastosowanie Eliksiru Przemiany Halloweenowej Dyniowej Wróżki powiodło się!",
	L"Co najmniej jeden warunek nie został spełniony. Sprawdź, czy zażyłość ze zwierzakiem wynosi 100%.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Osiągnięto limit przejścia planszy.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Z powodu zmiany pliku program zostanie zamknięty.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",

	L""
};
