#pragma once

//EN버전 출력
static wchar_t* szErrorStrEN[] = {
	L"Success",
	L"Unknown error",
	L"An error has occurred in player status.",
	L"Version error. Log in again.",
	L"Server is full. Maximum number of players has been reached.",
	L"The game server is being verified. Log in after system verification.",
	L"You have tried to log in twice on the same server.",
	L"Simultaneous login attempts on different channels.",
	L"Server IP check failed.",
	L"UID server crashed.",
	L"User does not exist",
	L"This player no longer exists.",
	L"Log in data is incorrect.",
	L"Server settings incorrect.",
	L"Your access data cannot be verified.",
	L"Your account was locked.\nPlease contact Elsword Support: http://support.elsword.de",
	L"Query is only possible from a system operator.",
	L"No proxy ID available.",
	L"IP address not permitted.",
	L"The ID data for the channel does not exist on the game server.",
	L"ID length error.",
	L"Transaction error.",
	L"ID length is not permitted.",
	L"Password length invalid.",
	L"Length of user name invalid.",
	L"The deleted player tried to create a character.",
	L"Character name already exists.",
	L"Transaction error.",
	L"Character data loading error.",
	L"Character name length error.",
	L"No more characters can be created.",
	L"This nickname is not currently usable!",
	L"Database could not create the character SN for messenger.",
	L"This nickname cannot be used.",
	L"No more than 4 characters can be created per day.",
	L"The selected character cannot be found on the game server.",
	L"Selected character class error.",
	L"Information on the resurrection stone cannot be accessed.",
	L"The database could not access the character SN of the messenger.",
	L"An error occurred in the database during character selection.",
	L"You need to change the nickname.",
	L"No PvP channel found that matches your level.",
	L"The player to delete is not on the channel.",
	L"Channel change failed",
	L"Insufficient VP to join.",
	L"Entry to village square channel failed.",
	L"Channel entry failed.",
	L"No competition will be carried out.",
	L"Group lists cannot be accessed.",
	L"Groups list cannot be seen in the dungeon gate.",
	L"Groups lists cannot be opened in this dungeon gate.",
	L"PvP is only possible from level 3.",
	L"No more rooms can be created on the server.",
	L"No user can be found in this slot.",
	L"The slot in which the selected character is located was not found.",
	L"The room is full.",
	L"Log in data is incorrect.",
	L"Previous dungeons have not been completed.",
	L"Immediate start failed. No rooms available.",
	L"Only the room leader can apply.",
	L"Room status does not allow packets at the moment",
	L"The player is not ready yet.",
	L"Number of team members does not match.",
	L"To start the game, more than one character must be ready.",
	L"Loading could not be changed.",
	L"The room was created.",
	L"The room information was changed.",
	L"The room was deleted.",
	L"No players can be found in the room.",
	L"Entrance failed.",
	L"You could not leave the room.",
	L"Dead NPCs UID error.",
	L"The NPC is already dead.",
	L"Monster data error. Loading failed.",
	L"Player not found.",
	L"Chat type error.",
	L"You cannot eject yourself from a room.",
	L"Insufficient Will Points.",
	L"This game type does not support the additional statistics.",
	L"Game is ended. You cannot enter the room.",
	L"You cannot enter the room.",
	L"The room you wish to enter contains no information.",
	L"You cannot prepare for a game during trading.",
	L"You can no longer enter the room as the game has already started. Please try again later.",
	L"Game starter item cannot be found in the inventory.",
	L"An unauthorised player has tried to create an observation room.",
	L"The PvP map data is wrong.",
	L"Only those with offline participation rights for the tournament can use the tournament channel.",
	L"You are missing the item to play the selected dungeon. After starting the game you will be thrown out of the dungeon.",
	L"The invitation function can only be used in the PvP room.",
	L"The player to be invited cannot enter the PvP room at the moment.",
	L"You can only invite players who are in the PvP channel lobby.",
	L"Game can only be started if you are registered in the group.",
	L"Wrong setting for number of kills.",
	L"The item does not exist any more.",
	L"Someone else has already taken it.",
	L"Random item assignment failed.",
	L"No information available for the item.",
	L"Item ID error.",
	L"The item could not be assigned.",
	L"Item cannot be repaired",
	L"Item cannot be used in the quickslot",
	L"Quickslot cannot be used in the Event Dungeon",
	L"Item cannot be acquired",
	L"Item could not be taken out of storage",
	L"Not enough storage space for the item.",
	L"Message is too long.",
	L"Team could not be changed",
	L"Changes to slot could not be saved.",
	L"Participation failed.",
	L"The slot could not be closed.",
	L"The user could not be kicked out.",
	L"Opponent data could not be saved.",
	L"Status could not be changed.",
	L"Player has left.",
	L"Connection ended.",
	L"You were kicked out.",
	L"Your level is now too high for this channel.",
	L"Sales stall was closed.",
	L"Visit to sales stall failed.",
	L"Time expired. Sales stall was closed.",
	L"Sales stall aborted.",
	L"Incorrect number of private vendors.",
	L"An error occurred during trading.",
	L"Not enough space in your inventory or the item data is defective.",
	L"You do not have enough Will Points.",
	L"Trade was aborted. There are no items for trading.",
	L"Trade was aborted.",
	L"Sales stall was closed because no items were placed.",
	L"Trade was aborted.",
	L"All items sold. Sales stall is closed.",
	L"Trade was aborted because you left the room.",
	L"Sales stall was closed.",
	L"Client crashed.",
	L"You cannot stay in the fight channel any longer.",
	L"You quit the group if you take part in PvP.",
	L"The group was dissolved because the dungeon ended.",
	L"You left the group because you went to the market.",
	L"You have entered the training area. You left the group.",
	L"Ended.",
	L"The game was ended because of suspicion of hacking.",
	L"Client crashed. Game is ended.",
	L"EXP of characters cannot be changed.",
	L"Database could not allocate the character.",
	L"Authority level is defective.",
	L"This player does not exist.",
	L"Transaction error.",
	L"No player exists with this authority level.",
	L"The operator ended the connection.",
	L"This command can only be executed in the field.",
	L"This command cannot be executed in this room.",
	L"The item cannot be bought.",
	L"The item cannot be sold.",
	L"The quest is being executed.",
	L"An attempt has been made to delete an incomplete quest.",
	L"This quest does not exist.",
	L"Quest already completed.",
	L"This character cannot complete the quest.",
	L"The previous quest has not been ended.",
	L"You received the wrong quest from the NPC.",
	L"This quest template does not exist.",
	L"Quest cannot be ended because not all requirements have been fulfilled yet.",
	L"The database cannot process the quest data.",
	L"You can accept up to a maximum of 10 quests simultaneously.",
	L"Your level is too low to accept a quest.",
	L"Not enough space in your inventory to complete the quest.",
	L"An error has occurred with allocation of the quest reward.",
	L"The required reward cannot be found.",
	L"Class upgrade quest is already complete.",
	L"An error has occurred with allocation of the class upgrade quest reward.",
	L"Quest type error.",
	L"Chat message entered in a shorter time than specified.",
	L"You cannot send a private message to yourself.",
	L"Chat error.",
	L"This user is not currently logged on.",
	L"--/;/Quotation marks/commas/spaces cannot be used.",
	L"Input shorter than loading time of the actual player list.",
	L"Search for user data still running.",
	L"This user is not currently logged on.",
	L"Nickname not available.",
	L"Attempt to enter village square failed.",
	L"Leaving of village square failed.",
	L"This skill is already at the highest level.",
	L"This skill does not exist.",
	L"Your level is too low to acquire this skill.",
	L"You do not have enough skill points.",
	L"You are missing the necessary item.",
	L"You need the completed quest for this purchase.",
	L"Previous skills have not yet been learned.",
	L"You have already learned this skill.",
	L"The skillslot ID to be changed is incorrect.",
	L"You can only enter skills that you have also learnt.",
	L"Skills reset failed.",
	L"The B skill bar cannot be used.",
	L"An error occurred during expansion of the B skill bar.",
	L"You can only learn this skill once the seal is removed.",
	L"This skill is in a level you have not reached yet.",
	L"You do not have enough skill points to learn this skill.",
	L"You do not have enough skill points to learn this skill.",
	L"You tried to alter information for a skill that does not exist.",
	L"Error in level information for the skill.",
	L"The set skill level does not match the correct level.",
	L"The changes or validity of shop skill points cannot be carried over.",
	L"Registration of shop skill points failed.",
	L"The information on shop skill points was not updated.",
	L"Information reset of shop skill points failed.",
	L"Standard skills cannot be reset.",
	L"The group cannot be created.",
	L"Departure from the group is not possible.",
	L"Group information incorrect.",
	L"This user cannot be invited.",
	L"No associated group exists.",
	L"You already belong to the group.",
	L"In PvP mode, groups cannot be created.",
	L"In PvP mode, it is not possible to join a group.",
	L"The group cannot accept any more members.",
	L"It is not possible to join the group.",
	L"The group was deleted.",
	L"Entry to the group was declined.",
	L"Invitation to the group was declined.",
	L"Dungeon cannot be started here.",
	L"Change of ready status failed.",
	L"Wrong dungeon selected.",
	L"Game start failed.",
	L"Game type invalid.",
	L"You are not the group leader.",
	L"Group leader could not be changed.",
	L"Group member could not be changed.",
	L"You cannot start that dungeon in this area.",
	L"The settings for your private sphere cannot be changed.",
	L"The player named as group leader cannot complete the current dungeon.",
	L"Group leader cannot change ready-status.",
	L"No chat partner is available.",
	L"Requested group list is defective.",
	L"The settings or level boundaries cannot be changed.",
	L"That is a private group.",
	L"No resurrection stone is available.",
	L"You have already been reborn.",
	L"Rebirth failed.",
	L"The resurrection stone cannot be used in this dungeon.",
	L"Update of an unavailable status is not possible.",
	L"Community options cannot be called up.",
	L"No further entries possible in the block list.",
	L"This player is already on the block list.",
	L"This player is already deleted from the block list.",
	L"Player does not exist.",
	L"Cannot be deleted from the block list.",
	L"You cannot enter yourself on the block list.",
	L"You cannot delete yourself from the block list.",
	L"You can only enter logged-in players on the block list.",
	L"It is not possible to enter your own character.",
	L"The time limit for adding friends has expired.",
	L"Character cannot be found.",
	L"In this status, your character cannot invite anyone.",
	L"The other player cannot currently be invited.",
	L"The other player cannot currently take part.",
	L"Cannot be added as a friend.",
	L"Sales stall cannot be created.",
	L"You cannot leave the private trade",
	L"Search for players with private trading failed.",
	L"Selected item is defective.",
	L"ED entry failed.",
	L"The object to be traded does not exist.",
	L"Not enough ED!",
	L"Only items from the inventory can be selected.",
	L"Not enough space in the inventory.",
	L"Items attached to the character cannot be sold.",
	L"Trading chat cannot be opened here.",
	L"You cannot trade with yourself.",
	L"When the durability of an item has expired, it cannot be traded. Repair the item and try again.",
	L"Item is already entered.",
	L"Only entered items can be deleted.",
	L"You can choose a maximum of 10 items.",
	L"This trade would exceed the other player's ED budget. Decrease the ED for this trade.",
	L"Private trade requests accepted.",
	L"Trade with another player is already open.",
	L"Private trade request was declined.",
	L"Trading not possible.",
	L"Trading not possible because of a server error.",
	L"You are missing the necessary item to take part in this dungeon.",
	L"You do not have permission to enter the training zone.",
	L"The dungeon assigned for training camp is missing the ID.",
	L"An error occurred while saving the reward.",
	L"The selected item does not exist in the inventory.",
	L"This concerns the selected item, not the cube.",
	L"This character cannot use the item.",
	L"You do not have enough keys to open the cube.",
	L"The cube cannot be opened.",
	L"Item cannot be created.",
	L"Not enough space in the inventory to open the cube.",
	L"More than one registration detected.",
	L"Player UID error.",
	L"Player ID error.",
	L"Character UID error.",
	L"Character nickname error.",
	L"Game server UID error.",
	L"Player information error.",
	L"Game server information error.",
	L"UID search failed.",
	L"Messenger number error.",
	L"The item cannot be produced.",
	L"That's not a scroll item.",
	L"Not enough ED to craft!",
	L"You do not have enough materials.",
	L"For crafting, at least one space must be free in your inventory.",
	L"Item could not be created.",
	L"HackShield certification failed.",
	L"As a result of an update to the Hackshield, the game must be restarted.",
	L"HackShield verification failed.",
	L"The coupon has already been redeemed or the coupon number is incorrect. Only one coupon can be used per account.",
	L"Enter the 30 digit coupon code.",
	L"This coupon has already been redeemed.",
	L"The coupon is no longer valid.",
	L"The coupon number is invalid.",
	L"This coupon can only be redeemed once per account.",
	L"The coupon could not be redeemed.",
	L"You have not waited a sufficient number of days to be able to buy it again.",
	L"The item list cannot be accessed.",
	L"Item information error.",
	L"You do not have enough space in your inventory.",
	L"The acquired shop item cannot be selected.",
	L"The balance cannot be queried.",
	L"Member information could not be found.",
	L"This account has been blocked.",
	L"It is not possible to take items from other characters into your inventory.",
	L"You already have this item.",
	L"Item is being accessed. One moment please.",
	L"Standard frame size is incorrect.",
	L"This player does not exist.",
	L"This is not the object that changes the nickname.",
	L"This nickname is already in use.",
	L"Nickname is not currently usable!",
	L"The nickname could not be updated.",
	L"This nickname is not permitted.",
	L"Length of nickname not permitted.",
	L"The nickname could not be changed.",
	L"The sales stall cannot be created.",
	L"The sales stall can only be created in the village square.",
	L"The stall cannot be accessed. No information found for owner.",
	L"The stall is busy at the moment. Try again later.",
	L"Opening sales stall failed.",
	L"The selected number of items that you want to sell does not tally with the data.",
	L"The item was already entered as sold.",
	L"You cannot register goods on third party sales stalls.",
	L"More items are entered than are able to be sold.",
	L"You do not have enough money to open a sales stall.",
	L"Creation of sales stall is not complete yet.",
	L"You have not left the shop yet.",
	L"You have selected more items to buy than you have offered to sell.",
	L"The item you want to buy does not exist.",
	L"You do not have enough ED to buy the item.",
	L"You do not have enough space in the inventory to buy anything.",
	L"Trading not possible because the manufacturer could not be found.",
	L"You cannot open a sales stall during a trade.",
	L"The sales stall is already open.",
	L"You have reached your ED limit.",
	L"You have reached the maximum amount of ED you are able to buy.",
	L"The information for the items to buy is incorrect.",
	L"The selected item does not exist in the inventory.",
	L"Item cannot be taken apart.",
	L"Item cancellation error. Try again.",
	L"You can only dismantle your equipment and your accessories.",
	L"Cannot be fragmented.",
	L"Item could not be created.",
	L"Not enough space in the inventory\nto dismantle the item.",
	L"Items with a time limit cannot be separated.",
	L"The item you want to improve is not available in the inventory.",
	L"Item data does not exist.",
	L"Only weapons or armour parts for defence can be improved.",
	L"Item cannot be improved.",
	L"Cannot be improved any more.",
	L"No upgrade stone available!",
	L"Upgrade could not be carried out.",
	L"You do not have enough ED for an upgrade.",
	L"For an upgrade, the item must first be stored or removed.",
	L"Fluorite stone does not exist in the inventory.",
	L"Fluorite stone cannot be used.",
	L"From upgrade level 10, the fluorite stone can no longer be used.",
	L"It is not possible to carry out an upgrade for items you cannot use.",
	L"Upgrade failed.",
	L"The item to repair is not in your inventory.",
	L"Item data does not exist.",
	L"Item cannot be repaired.",
	L"Repair is only possible for items you cannot use.",
	L"Insufficient regeneration stones available.",
	L"Equipped items cannot be repaired.",
	L"Items that are specifically deactivated cannot be used.",
	L"Upgrade successfully completed.",
	L"No change.",
	L"Reduced by one level.",
	L"Reset of upgrade level.",
	L"Item cannot be used.",
	L"Item is not available in the inventory.",
	L"Item data does not exist.",
	L"Charge is too high.",
	L"Socket only exists for weapons or armour parts.",
	L"There is no information about the magic stone in your equipment.",
	L"Magic stone not available in the inventory.",
	L"Socket cannot be used.",
	L"The magic stone has already been inserted into the socket.",
	L"The magic stone has already been removed from the socket.",
	L"Socket option does not exist.",
	L"Nickname does not exist.",
	L"You cannot suggest yourself.",
	L"There is no one who can accept the reward.",
	L"The private file to be deleted does not exist in the database.",
	L"Apprentice lists cannot be accessed.",
	L"Information cannot be displayed. Level is too low.",
	L"Your level is not high enough to take on apprentices.",
	L"A maximum of 3 apprentices can be entered.",
	L"He already has an instructor.",
	L"Is already entered as an apprentice.",
	L"Error with goods to buy.",
	L"The goods cannot be purchased.",
	L"Payment already made.",
	L"Maximum number of goods exceeded.",
	L"You have exceeded the maximum quantity of goods that should be bought.",
	L"These goods cannot be bought again.",
	L"Shopping basket not available.",
	L"Game use is limited.",
	L"Goods quantity is limited. Goods cannot be acquired.",
	L"Number of orders is limited.",
	L"The goods cannot be acquired at the moment.",
	L"The goods cannot be given away.",
	L"Order quantity is limited.",
	L"The other player cannot currently accept the goods.",
	L"That is a blocked player.",
	L"No player information found.",
	L"Not enough credit.",
	L"System is being checked.",
	L"Maximum number of resurrection stones has been reached.",
	L"You cannot create any more inventory slots.",
	L"You cannot give yourself something.",
	L"Log in data is incorrect.",
	L"Nickname does not exist.",
	L"You cannot give things to demo ID players.",
	L"Quantity of goods given away was exceeded.",
	L"Enter password.",
	L"Account verification failed.",
	L"Goods cannot be given away.",
	L"Players under 14 cannot use this function.",
	L"The item cannot be acquired.\nMaximum of 9 character slots permitted.",
	L"Character slot could not be expanded.",
	L"This function is already in use.",
	L"Skill does not exist.",
	L"The item for skill reset does not exist.",
	L"Item for skill reset cannot be deleted from the database.",
	L"Database error occurred during skill reset.",
	L"Skill cannot be reset.",
	L"A skill cannot be reset as long as it remains in the quickslot.",
	L"This item cannot be reserved.",
	L"You cannot put any more products in your shopping basket.",
	L"You cannot use this function as a tester.",
	L"Players with a demo ID cannot recommend the game.",
	L"You have reached the maximum level for a demo ID player. If you want to continue the game, log on with a full ID.",
	L"demo ID players cannot be added to friend list.",
	L"This user is not entered in the hacking list.",
	L"The database has not yet updated hacking compliance data.",
	L"You have not yet confirmed the hacking player message.",
	L"Item does not exist in the inventory.",
	L"These characteristics cannot be improved.",
	L"The slot characteristics have already been improved.",
	L"This slot has already been removed.",
	L"Not enough ED for attribute enhancement!",
	L"Not enough Eldrit Shards for an enchantment.",
	L"Item information error.",
	L"Attribute enhancement is only possible on weapons and armour.",
	L"The selected item cannot be taken apart.",
	L"Not enough analysis equipment available.",
	L"Not enough space in the inventory\nto dismantle the item.",
	L"Selected item cannot be taken apart.",
	L"Item production error.",
	L"Mailbox cannot be accessed.",
	L"The selected item cannot be attached to the mail.",
	L"The specified ED quantity cannot be sent by mail.",
	L"Mail could not be sent.",
	L"The mail does not exist.",
	L"Not enough space in the inventory to move the attached object. Make space in the inventory and try again.",
	L"The attached object could not be collected.",
	L"You tried to add an item that does not exist.",
	L"Only completely repaired items can be added.",
	L"Nickname does not exist.",
	L"You cannot send a message to yourself!",
	L"Not enough ED to send a message.",
	L"The other player does not have enough space in his mailbox and cannot receive messages.",
	L"You have selected a deleted message.",
	L"The player declined your message.",
	L"You cannot send items attached to your character in messages.",
	L"Messages cannot be sent to demo ID players.",
	L"Nickname does not exist.",
	L"This nickname is already entered on the block list.",
	L"Block list entry failed.",
	L"Nickname was already deleted.",
	L"Player could not be deleted from the block list.",
	L"You do not have this title.",
	L"You already have this title.",
	L"The validity of this title has expired.",
	L"This title does not exist.",
	L"The title has not been attained.",
	L"You already have this title.",
	L"The item cannot be used.",
	L"The item does not exist.",
	L"Your level is too low for this item.",
	L"The item cannot be used in the inventory.",
	L"The item does not exist in the inventory.",
	L"Item is not allowed.",
	L"The item is not permitted.",
	L"Upgrade failed.",
	L"Item cannot be exchanged.",
	L"The item does not exist in the inventory.",
	L"You cannot trade this item.",
	L"Items for exchange have not been created.",
	L"Leave this place to arrive in another area.",
	L"Leave the plain to arrive in another room.",
	L"The system has processed your cancellation.",
	L"You cannot enter the village.",
	L"You could not leave the village.",
	L"The player list cannot be accessed.",
	L"Your level is too low to go into the village.",
	L"You have not yet completed the dungeon that allows you access to the village.",
	L"This channel does not exist.",
	L"Channel change was successful. Connection ended.",
	L"Registration of channel change failed.",
	L"You are not registered for a channel change.",
	L"You are already in the channel you want to change to.",
	L"Maximum number of members has been reached. Change not possible.",
	L"The channel change function can only be used in a village or area surrounding a village.",
	L"Try the channel change later.",
	L"You cannot use this function with this player.",
	L"No character selected.",
	L"This friend is not logged in.",
	L"Incorrect status.",
	L"The database has not updated the event drop item.",
	L"You have already received the event reward.",
	L"This player is already your friend.",
	L"Friend character status invalid.",
	L"This player has not added you as a friend.",
	L"This player is not friends with you.",
	L"The group does not exist.",
	L"Message is too long.",
	L"That is the same group you want to change to.",
	L"No further groups can be created.",
	L"This group already exists.",
	L"This group name is already in use.",
	L"The apprentice has not logged in for 7 days. The apprenticeship is called off.",
	L"The apprentice has gone up one level. The apprenticeship is thereby ended.",
	L"The character was deleted. The apprenticeship is thereby ended.",
	L"The apprenticeship has been cancelled.",
	L"You could not end the apprenticeship.",
	L"Database or friend functions error.",
	L"The group name is too long.",
	L"Your friend list is full. The invitation could not be sent.",
	L"Friendship requests between characters within a single account are not possible.",
	L"The other player's friend list is full. Friendship request cannot be sent.",
	L"Your friendship request was declined.",
	L"Search query failed.",
	L"The PvP channel cannot be entered.",
	L"In PvP, a game only starts when all places have been taken.",
	L"Subject is too long.",
	L"Message is too long.",
	L"The invited player cannot enter the dungeon.",
	L"Seal has already been removed.",
	L"Skill seal cannot be removed.",
	L"You have the wrong class for this object.",
	L"You have already enabled this skill!",
	L"There is already an item with the same functions in the inventory. The goods could not be bought.",
	L"Players with a demo ID cannot be invited to Henir's Time-Space Continuum.",
	L"Certification type invalid.",
	L"Items in the bank cannot be taken apart.",
	L"Items kept in the bank cannot receive socket attachments.",
	L"This function cannot be used at the bank.",
	L"The number of bank slots cannot be extended further.",
	L"It is not possible to buy more than one membership card for the bank.",
	L"Bank membership cards cannot be bought.",
	L"If you hold a guarantee from Luriel in your inventory, you can buy a platinum member card. Use the guarantee from Luriel now.",
	L"The password does not exist.",
	L"The password cannot be renewed.",
	L"Username or password incorrect.",
	L"An error occurred during the authentication phase.",
	L"The item does not exist.",
	L"Item information is not available.",
	L"This type of item cannot be sealed.",
	L"Equipped items cannot be sealed.",
	L"The item is already sealed.",
	L"An unrepaired item cannot be sealed.",
	L"Items with a time limit cannot be sealed.",
	L"Destroyed items cannot be sealed.",
	L"Items that can be traded cannot be sealed.",
	L"No further seals possible.",
	L"Selected seal scroll information error.",
	L"Seal failed.",
	L"Insufficient seal scrolls!",
	L"Seal cannot be removed from equipped items.",
	L"Seal has already been removed from this item.",
	L"Seal removal failed.",
	L"Seal information database update error.",
	L"Sealed items cannot be improved.",
	L"System error with El coins query.",
	L"This account has a limited activity radius.",
	L"This account does not exist.",
	L"The account is wrong.",
	L"The coupon number is invalid.",
	L"This coupon has already been redeemed.",
	L"This type of coupon can only be used once.",
	L"The coupon has expired.",
	L"An error occurred while redeeming the coupon.",
	L"Not enough El coins.",
	L"An error occurred during the purchase.",
	L"The purchase is only possible from level 15 upwards.",
	L"You are already registered in a Guild.",
	L"This guild name is already in use.",
	L"The guild formation item cannot be found in the inventory.",
	L"Guild formation item error.",
	L"Guild formation failed.",
	L"Guild Master registration failed.",
	L"Guild information could not be found.",
	L"Invitation to guild not possible.",
	L"This player is offline.",
	L"demo ID players cannot be invited to join a guild.",
	L"This player has already been invited into the guild.",
	L"Another guild has already invited this player.",
	L"You do not have the authority to invite someone to join the guild.",
	L"You cannot increase the number of guild members. You require an item that will enable more spaces for members.",
	L"The invited player is already a guild member.",
	L"This player is already in a guild.",
	L"You cannot see the guild list.",
	L"Error with item that should be purchased with coupon.",
	L"The player has declined the guild invitation.",
	L"Registration to the guild has failed.",
	L"Does not belong to a guild.",
	L"You do not have the authority to change the rank of guild members.",
	L"Rank of guild member could not be changed.",
	L"Change of guild message can only be carried out by the Guild Master and the Guild Administrator.",
	L"Change to guild message failed.",
	L"You are not allowed to kick a guild member.",
	L"The Guild Master cannot leave the guild.",
	L"Leaving the guild failed.",
	L"Limited length of guild greeting.",
	L"You are not allowed to change the guild greeting.",
	L"Change to guild greeting failed.",
	L"Only the Guild Master is able to disband the guild.",
	L"The guild cannot be disbanded. There are still guild members registered.",
	L"Guild disbandment failed.",
	L"The class rank has been changed.",
	L"A Guild Administrator already exists.\nChange the rank of the Guild Administrator\nto appoint a new Administrator.",
	L"The Guild Master cannot delete his character. Pass on the title of Guild Master to another guild member.",
	L"You cannot change your own class rank.",
	L"You cannot purchase any guild establishment permits as you are already member of a guild.",
	L"You already have a guild establishment permit.",
	L"Increasing the number of members failed.",
	L"The expansion card can only be used by the Guild Master or the Guild Administrator.",
	L"No further members can be accepted into the guild.",
	L"This function cannot be used during trading.",
	L"You cannot switch to this area.",
	L"This guild name is not available for 7 days.",
	L"That is the maximum number of experience points.",
	L"To be able to buy the item, the appropriate quest must be completed.",
	L"Guild name is too long.",
	L"You do not have enough ED to remove the attribute.",
	L"You can only buy this item from level 35.",
	L"",
	L"",
	L"No further items can be bought. Your temporary inventory is full.",
	L"GSP can only be used by the Guild Master.",
	L"This guild skill has already been trained to the highest level.",
	L"Guild skill information does not exist.",
	L"Previous guild skill has not yet been trained to the highest level.",
	L"Insufficient skill points deployed.",
	L"Not enough GSP.",
	L"Learning of guild skills failed.",
	L"Only the Guild Master can reset guild skills.",
	L"You need the Horn Flute of Oblivion!",
	L"Guild skill cannot be reset.",
	L"Restoration of guild skill failed.",
	L"Only the Guild Master can reset guild skills.",
	L"The Horn Flute of Oblivion is not available in the inventory.",
	L"Guild skill reset is not possible.",
	L"Guild skill reset failed.",
	L"Usage is only possible through the Guild Master.",
	L"No limited guild skill points received.",
	L"The blessed item of knowledge is already in use.",
	L"It is not yet possible to receive the event reward.",
	L"Not enough space in your inventory to accept the event reward.",
	L"Error receiving the event reward.",
	L"That is not the item mode.",
	L"There is still one drop item left.",
	L"PvP drop item could not be collected.",
	L"You can create the class after using the character card.",
	L"This account cannot participate in the event.",
	L"This function can only be used by the Guild Master or the Guild Administrator.",
	L"",
	L"The guild advertisement does not exist.",
	L"The text is too long.",
	L"Registration period for advertisement is invalid.",
	L"Not enough ED to register the advert.",
	L"An advert has already been registered.",
	L"Registration of guild advertisement unsuccessful.",
	L"The registration cannot currently be carried out because there are too many applications.",
	L"Guild registration application unsuccessful.",
	L"You have already applied for registration.",
	L"The registration application does not exist.",
	L"Guild registration acceptance unsuccessful.",
	L"Deletion of guild registration application unsuccessful.",
	L"You cannot apply for registration in the case of adverts with limited periods.",
	L"You do not have the authority to see lists of guild registration applications.",
	L"You have not opened the castle.",
	L"This game account was stopped.",
	L"",
	L"",
	L"You were removed from the room because of suspected hacking.",
	L"Because the Reject Guild Invitation option is enabled, you cannot apply for registration.",
	L"You cannot apply for registration because there are too many applications for guild registration.",
	L"That is not the quest currently being completed.",
	L"The purchase limit for the items in question has been reached.",
	L"El coins are disabled. Change the website settings under My Information in the Cash Safety menu.",
	L"Current status check was already executed.",
	L"The WebPoint enhancement DB query failed.",
	L"Status check failed.",
	L"You left the group because of a double registration.",
	L"Loading group status.",
	L"Delete item list.",
	L"Add item list.",
	L"Edit item list.",
	L"Category selection is wrong.",
	L"The search returned no hits.",
	L"The invited parties have insufficient willpower.",
	L"Restart the search after a little while.",
	L"The sale was ended in this shop.",
	L"The player does not have purchase status.",
	L"Room creation unsuccessful.",
	L"The item does not exist.",
	L"This page does not exist.",
	L"This note has already been registered.",
	L"The note could not be registered.",
	L"You do not have the Technique Notebook.",
	L"Entry of technical note failed.",
	L"You have this technical note already.",
	L"You must first reach level 20 before you may purchase this item.",
	L"You cannot trade with players on other servers.",
	L"Sales stalls on other servers cannot be used.",
	L"You cannot invite users from other servers into the Guild.",
	L"Players from other servers cannot be registered as apprentices.",
	L"You cannot add players from other servers as friends.",
	L"You cannot play the challenge mode of Henir's Time-Space Continuum with characters on other servers.",
	L"Access ban for users due to suspected hacking.",
	L"",
	L"Error in number of items you want to throw away.",
	L"Pet creation was unsuccessful.",
	L"This name is already in use.",
	L"The name is limited to 12 characters.",
	L"The pet will be created.",
	L"Was not able to summon pet.",
	L"The pet cannot be created here.",
	L"You have already summoned a pet.",
	L"This pet has already been summoned.",
	L"Was not able to dismiss pet.",
	L"Command could not be carried out.",
	L"Your pet is full. It cannot eat any more.",
	L"Pet could not be fed.",
	L"The pet is in the growth phase. It eats only fruit and seeds from El's Tree.",
	L"That was already saved.",
	L"The next evolution stage is not available yet.",
	L"Further evolution is only possible when intimacy is at 100%.",
	L"The pet cannot use this item.",
	L"The food's level is too low.",
	L"Log in data is incorrect.",
	L"Log in data is incorrect.",
	L"The account is not yet validated.",
	L"The pet cannot eat this food.",
	L"The user is busy.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"[Unknown sender]",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"No purchase information available for these goods.",
	L"No information available for these goods.",
	L"",
	L"",
	L"Time restricted items cannot be thrown away.",
	L"Goods that cannot be sold can also not be thrown away.",
	L"",
	L"Your level is too low for this item.",
	L"From upgrade level 11, fluorite stones can no longer be used.",
	L"You cannot accept this quest because the reward has already been received.",
	L"You cannot accept the quest, because there is insufficient space in your inventory for the reward.",
	L"Use of magic stone failed.",
	L"This function is not currently available.\nSorry for any inconvenience.",
	L"Access for this IP is limited.",
	L"Chat function was limited.",
	L"Trade function was limited.",
	L"The game cannot be started because the item does not exist.",
	L"The game was interrupted by another program.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"You cannot send messages because your actions have been restricted.",
	L"You cannot open a sales stand because of a trade restriction.",
	L"You cannot access your sales stand due to a trade restriction.",
	L"You cannot search for wares due to a trade restriction.",
	L"You cannot enter the market due to a trade restriction.",
	L"",
	L"More than two group members required.",
	L"The dungeon is closed and therefore cannot be entered.",
	L"You cannot enter the world mission dungeon with other players from this server.",
	L"The log for post monitoring costs the same.",
	L"The log for purchase monitoring costs the same.",
	L"Post monitoring log has failed.",
	L"Purchase monitoring log has failed.",
	L"You cannot deactivate the sales agent since goods are still being sold.",
	L"Sales agent is not active.",
	L"You cannot cancel the purchase process.",
	L"This is a private sale: Selling items is not possible.",
	L"You cannot open a sales stall since the sales agent is still active.",
	L"Your sales stand will be closed because you violated the rules.",
	L"You cannot deactivate the agent.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"You have incorrectly entered your password twice and therefore cannot log in.",
	L"You must enter a contract in order to sell items via the agent.",
	L"The PINs entered are not identical.",
	L"You have entered an incorrect PIN 10 times.\nWhen you click 'Confirm', the connection will be broken.\nYou must log into the website in order to reset the process.",
	L"PIN creation failed.",
	L"PIN is not correct.",
	L"The item name is too long.",
	L"The agent's sales stand has been closed.\nOnce you receive your wares, you can open a new sales stand.",
	L"The agent is in the process of selling these wares.\nIf you would like to receive the money for the sold items,\nyou must first close the agent's sales stand.",
	L"DB query for agent's contract failed.",
	L"Agent could not be activated.",
	L"The items could not be added to the agent's sales stand.",
	L"Only the agent's client can use this.",
	L"Items cannot be transferred to the agent.",
	L"You cannot take an item that is in the process of being sold.",
	L"You have already received this item.",
	L"You have reached the maximum amount of ED and cannot have any more.",
	L"There is no more space in your inventory.",
	L"You don't have any items.",
	L"You cannot buy the same items at the same time.",
	L"Your level is too low.\nYou cannot create a group request.",
	L"You cannot buy any items because the agent is still active.",
	L"There are still items that you must receive before you can sell additional items.",
	L"The agent is closing the sales stand because all items have been sold.",
	L"You have already accepted this quest and received the reward. You cannot accept it again.",
	L"You cannot accept the quest because you don't have any more space in your inventory.",
	L"The group's minimum level could not be changed.",
	L"You cannot open a sales stand because the agent has sold all the items.",
	L"",
	L"",
	L"",
	L"",
	L"Your level is too low.\nChoose another dungeon or remove the level restriction.",
	L"Your level is too low.\nYou cannot create a level restriction.",
	L"The invited player's level is too low.",
	L"Your level is too low.\nChoose a dungeon that suits your level.",
	L"No digit in the PIN may immediately repeat itself.\n(e.g. 0000, 1111, 999999, etc.)",
	L"Please do not use consecutive numbers in the PIN.\n(e.g. 1234, 9876, 123456, etc.)",
	L"Error in deleting the second PIN pad.",
	L"The 2nd PIN pad is not in use.",
	L"The new PIN must be different from the old PIN.",
	L"This item is not sold in the shop.",
	L"The match was ended by the start of PvP.",
	L"One player cannot take part in PvP-matching.",
	L"The matching was cancelled.",
	L"The matching was cancelled because the group member did not take part in PvP.",
	L"The match was successfully completed. You will be removed from the waiting list.",
	L"One user cancelled the match registration and has therefore been removed from the waiting list.",
	L"Match registration was cancelled because one group member left the group.",
	L"Matching is in progress.",
	L"The information on the group member is not correct.",
	L"The information on the PvP mode is not correct.",
	L"PvP is only available from level 10.",
	L"You must be at least level 10 to join a PvP group.",
	L"You just changed the PvP mode.",
	L"With four dungeon members, you cannot change into a PvP group.",
	L"The PvP mode cannot be changed.",
	L"The PvP room cannot be changed because one group member has not yet reached level 10.",
	L"One group member has not yet reached level 10 and therefore cannot enter the PvP room.",
	L"Only characters level 10 and up can be invited to a PvP group.",
	L"Only characters level 10 and up can start a PvP group.",
	L"",
	L"Items could not be sorted. Please try again later.",
	L"You have not registered for matching.",
	L"You are already in a PvP room.",
	L"This is not the PvP room.",
	L"The request has failed.",
	L"You cannot invite a user who is registered for matching.",
	L"You cannot invite a user who is in the process of matching.",
	L"Your rank is too low to buy this item.",
	L"You cannot register for another group during matching.",
	L"You cannot change your group during matching.",
	L"You cannot change channels during matching.",
	L"ID could not be recognised.",
	L"ID is logged into multiple channels at once.",
	L"You cannot take on any more random quests today.",
	L"I do not agree to the contract.",
	L"Error occurred displaying SP.",
	L"SP 입력 값에 문제가 있습니다.",
	L"목적 DB 이름이 잘못 되었습니다.",
	L"Data verification failed.",
	L"",
	L"",
	L"No information found.",
	L"You cannot trade until you have been registered as an adventurer.",
	L"You cannot send any messages until you have been registered as an adventurer.",
	L"",
	L"You have left the battlefield.",
	L"Can only be purchased if you are level 15 or higher.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"You cannot log in with this account.",
	L"You have automatically left the group due to combination.",
	L"You cannot buy this item because there is already an unlimited skill slot expansion active.",
	L"This item cannot be bought because the unlimited skill slot expansion is already active.",
	L"",
	L"",
	L"",
	L"",
	L"You already have a Medallion of Blessings in your inventory, so the cube cannot be opened.",
	L"Your level is too low to purchase the item.",
	L"Your level is too low to receive the item.",
	L"Group creation failed!",
	L"Not enough group members.",
	L"Delay in the response of the invited group members.",
	L"This item is not being sold.",
	L"",
	L"Items from the bank sharing system cannot be sent by mail.",
	L"Items from the bank sharing system cannot be traded.",
	L"Level too low for this item.",
	L"Only characters belonging to a guild can swap it.",
	L"You have to be level 30 or higher to purchase this.",
	L"Participation requests for PvP groups are only possible with a complete patch.",
	L"",
	L"Log in again or try again later!",
	L"You cannot take part in the quiz again today.",
	L"Unknown error",
	L"You cannot buy items during the trade restriction.",
	L"Cannot be used during the trade restriction.",
	L"You cannot expand the quick slot bar any more.",
	L"The character has already been deleted or is about to be deleted.",
	L"Character cannot currently be deleted.",
	L"It is not possible to permanently delete the character at the moment.",
	L"This character cannot be permanently deleted.",
	L"Once deleted this character cannot be restored.",
	L"Characters cannot currently be restored.",
	L"Please try again later.",
	L"This character does not exist.",
	L"Character unable to be deleted.",
	L"Pet name change failed.",
	L"Pet name change in progress.",
	L"The game was interrupted.",
	L"You are not a guild master.",
	L"The item information is incorrect.",
	L"Guild name change has failed.",
	L"Already in progress...",
	L"You have tried to delete an item that does not exist.",
	L"",
	L"",
	L"",
	L"",
	L"Deleting item has failed.",
	L"Only the guild master has the rights to change their guild name.",
	L"",
	L"The time for editing is over and the process has been stopped. Please try again.",
	L"Guild name change has been cancelled by user.",
	L"You do not have the status needed to reach this location.",
	L"You are already at this location.",
	L"This location is already full, you cannot enter.",
	L"You cannot enter this location since it is already occupied by several groups.",
	L"Entering location has failed.",
	L"The information on the location you want to enter is incorrect.",
	L"An error occurred while entering this location.",
	L"User information could not be found in the affected location.",
	L"Starting play in a dungeon using automatic group combination has failed.",
	L"Starting play in the dungeon has failed.",
	L"You cannot currently apply for automatic group combination.",
	L"You cannot currently start automatic group combination. Please wait a moment.",
	L"An application for automatic group combination has already been made.",
	L"Automatic group combination has failed due to incorrect information.",
	L"Candidate registration for automatic group combination has failed.",
	L"You do not have the status required to apply for automatic group combination.",
	L"The game cannot start because there is only 1 group member.",
	L"One of the group members has cancelled.",
	L"The game will not take place because the time to confirm the beginning of the group game has run out.",
	L"You are already a member of the group.",
	L"The invited person is waiting to be accepted into another group.",
	L"You are not currently a member of the group.",
	L"Wonder Drug and Secret Potion overlap and therefore cannot be used.",
	L"",
	L"",
	L"This function cannot be used at the moment.",
	L"",
	L"You have already reached your Physical Performance Limit. You cannot use the Secret Potion.",
	L"You do not meet the minimum level requirement. The game in this dungeon cannot begin.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Automatic group combination ended due to the start of a dungeon game.",
	L"One user involved with the automatic group combination did not agree to starting the game.",
	L"Automatic group combination successfully cancelled.",
	L"One group member did not agree to starting the game in the automatic group combination. The automatic group combination has been cancelled.",
	L"The automatic group combination was successful. Your name has been removed from the waiting list.",
	L"The application for automatic group combination has been withdrawn. The name has been removed from the waiting list.",
	L"The application for automatic group combination has been withdrawn because one group member opted out.",
	L"The required item level has not been met. You cannot start the dungeon.",
	L"The keyboard layout could not be saved.",
	L"No keyboard layout data could be saved.",
	L"The keyboard layout could not be read.",
	L"No keyboard layout data could be read.",
	L"There is a delay in confirming the beginning of the group's game in the dungeon.",
	L"",
	L"",
	L"That player is not in the same group.",
	L"The chat selection data could not be saved.",
	L"The chat selection data could not be read.",
	L"Some of the chat selection data could not be read.",
	L"Test",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Opening is not yet possible.",
	L"Opening hours are over.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Your level is too high for this quest.",
	L"",
	L"",
	L"",
	L"",
	L"This dungeon can only be played alone.",
	L"The dungeon is not yet open.",
	L"The character was not selected correctly.",
	L"Characters cannot send a private message to themselves.",
	L"An error has occurred in the pet information.",
	L"You can only use it when the pet has been summoned.",
	L"Can only be used by teen pets.",
	L"Can only be used by kid pets.",
	L"There is an error in the tag count settings.",
	L"The game will start only when there are at least two team members.",
	L"",
	L"",
	L"",
	L"",
	L"You have left the dungeon.",
	L"You left the competition.",
	L"Withdrawal is following due to a channel change.",
	L"Withdrawal is following due to searching for same group members.",
	L"Withdrawal will occur due to the use of a movement item.",
	L"Withdrawal due to wrongful termination.",
	L"While you are playing in a dungeon, you cannot invite any more group members.",
	L"An invitation is not possible, because the player already belongs to another group.",
	L"This person is already in a competition and can therefore not be invited.",
	L"This person is already in a dungeon and cannot be invited.",
	L"The player could not be found on this server.",
	L"No group members can be invited.",
	L"During a competition, no group members can be invited.",
	L"Your level is too low to enter this field.",
	L"You haven't played the dungeons through yet, which is a requirement for entering this field.",
	L"A maximum of 30 quests can be carried out.",
	L"You do not have enough ED.",
	L"A player that uses the automatic group formation cannot be invited.",
	L"If automatic group formation is activated, you cannot invite anyone into your group.",
	L"In the PvP room you cannot invite any group members.",
	L"During the training you cannot invite group members.",
	L"During a PvP matching you cannot invite group members.",
	L"As long as you are registered for the automatic group formation, manual group invitations won't work.",
	L"If you are registered for PvP matching, you cannot invite group members.",
	L"Your group is on the same field as you.",
	L"As this is a candidate for another group, this person cannot be invited.",
	L"",
	L"",
	L"This nickname does not exist.",
	L"The server group ID is incorrect.",
	L"",
	L"Those who are not eligible to take part in the online competition, cannot use the PvP channel.",
	L"You need items and ED to open the cube.",
	L"You do not have enough ED to open the cube.",
	L"We will start with the present number of participants.",
	L"",
	L"",
	L"",
	L"The event is over.",
	L"You cannot get this item with Ara.",
	L"",
	L"Unfortunately the maximum number of exchanges has been used up.\nAfter the maintenance on 17.01. additional exchanges will be available.",
	L"",
	L"This pet does not exist.",
	L"This function is already being used.",
	L"Can only be used from the 'Kid' level.",
	L"While you are waiting for a game, you cannot change your skill slots.",
	L"Because you're currently not in the room, the information about the field monsters could not be loaded.",
	L"Because you're currently not in the room, the information about the field monsters could not be loaded.",
	L"The item for expanding slots could not be purchased. A slot expansion is only possible up to a maximum of 30 units.",
	L"Exclusion from the dungeon was due to the exclusion vote.",
	L"The voter is not a real player.",
	L"The player who was supposed to be voted on is not a real player.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"You do not have enough ED to register an invitation.",
	L"You cannot register for this guild, as the maximum number of members has been reached.",
	L"Invitation request could not be sent.",
	L"Guild search could not be registered.",
	L"A guild invitation message already exists.",
	L"A guild search is already registered.",
	L"Guild invitation message could not be registered.",
	L"You do not have enough ED to register the guild search.",
	L"No guilds invitation available.",
	L"No guilds invitation available.",
	L"This guild does not exist.",
	L"You do not have the authorisation to view the list of invited users.",
	L"Maximum amount of dungeon entries has been reached.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"You do not have any 'instructions for the fields'.",
	L"The chapter could not be entered.",
	L"The chapter has already been entered.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Error in the calculation of the VIP time.",
	L"",
	L"",
	L"",
	L"",
	L"The item level does not match this Blessed Time-Space Scroll.",
	L"This item has already been identified.",
	L"There is no item in the inventory.",
	L"You do not have enough ED to be able to identify the item.",
	L"Identification failed.",
	L"Not enough Blessed Time-Space Scrolls available.",
	L"This item cannot be identified.",
	L"",
	L"",
	L"This item cannot be changed.",
	L"You do not have enough ED for the change fee.",
	L"",
	L"",
	L"",
	L"",
	L"You no longer have any items that you can change.",
	L"The item change failed.",
	L"",
	L"",
	L"Time-limited items or materials cannot be changed.",
	L"Time-limited items or materials cannot be changed.",
	L"The requirements are not met.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"You cannot purchase anything while your account is locked.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"An error in the file CheckKom.xml caused the program to close.",
	L"",
	L"Incorrect stage information.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"At least one requirement has not been fulfilled. Check if you have summoned the pet or not!",
	L"At least one requirement has not been fulfilled. Check if you can use the pet or not!",
	L"You have applied the Transformation Potion for the Halloween Pumpkin Fairy!",
	L"At least one requirement has not been fulfilled. Check if the intimacy level of your pet is at 100% or not!",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Maximum amount of dungeon games has been reached.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"The program will be closed due do a data change.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",

	L""
};
