#pragma once

//ES버전 출력
static wchar_t* szErrorStrES[] = {
	L"Éxito",
	L"Error desconocido",
	L"Se ha producido un error en el estatus del jugador.",
	L"Esta versión es incorrecta. Inicia de nuevo la sesión.",
	L"El servidor está lleno. Se ha alcanzado el número máximo de jugadores.",
	L"El servidor del juego está siendo analizado. Inicia sesión cuando haya finalizado el análisis.",
	L"Has intentado iniciar sesión dos veces en el mismo servidor.",
	L"Has intentado iniciar sesión en varios canales al mismo tiempo.",
	L"Fallo en la revisión de la IP del servidor.",
	L"El servidor del identificador de usuario se ha bloqueado.",
	L"El usuario no existe",
	L"Este jugador ya no existe.",
	L"Los datos de acceso son incorrectos.",
	L"La configuración del servidor es incorrecta.",
	L"No pueden verificarse tus datos de acceso.",
	L"Tu cuenta ha sido bloqueada.\nPonte en contacto con el soporte de Elsword: http://support.elsword.es",
	L"La consulta solo es posible desde un operador de sistema.",
	L"Ninguna identificación proxy disponible.",
	L"Dirección IP no permitida.",
	L"Los datos de identificación para el canal no existen en el servidor del juego.",
	L"La longitud de la identificación es incorrecta.",
	L"Error de transacción.",
	L"La longitud de la identificación no está permitida.",
	L"La longitud de la contraseña no es válida.",
	L"La longitud del nombre de usuario no es válida.",
	L"El jugador eliminado ha intentado crear un personaje.",
	L"El nombre del personaje ya existe.",
	L"Error de transacción.",
	L"Error al cargar los datos del personaje.",
	L"La longitud del nombre del personaje es incorrecta.",
	L"No se pueden crear más personajes.",
	L"¡En estos momentos no se puede utilizar este apodo!",
	L"La base de datos no pudo crear el SN del personaje para messenger.",
	L"Este apodo no se puede utilizar.",
	L"No se pueden crear más de 4 personajes por día.",
	L"El personaje seleccionado no se encuentra en el servidor del juego.",
	L"La clase del personaje seleccionada es incorrecta.",
	L"No se ha podido acceder a la información sobre la piedra de la resurrección.",
	L"La base de datos no pudo acceder al SN del personaje del messenger.",
	L"Se ha producido un error en la base de datos durante la selección de personaje.",
	L"Debes cambiar el apodo.",
	L"No se ha encontrado ningún canal JcJ que se corresponda con tu nivel.",
	L"El personaje que se va a eliminar no está en el canal.",
	L"Cambio de canal fallido.",
	L"PJcJ insuficientes para entrar.",
	L"No has podido entrar en el canal de la plaza de la villa.",
	L"No has podido entrar en el canal.",
	L"No hay ninguna competición.",
	L"No se puede acceder a la lista de grupos.",
	L"En el portal del escenario no se puede ver la lista de grupos.",
	L"No se puede abrir la lista de grupos en este portal.",
	L"JcJ solo está disponible a partir del nivel 3.",
	L"No se pueden crear más salas en el servidor.",
	L"No hay ningún usuario en este espacio.",
	L"No se encontró el espacio en el que se ubica el personaje seleccionado.",
	L"La sala está llena.",
	L"Los datos de acceso incorrectos.",
	L"No se ha completado el escenario anterior.",
	L"Inicio inmediato fallido. No hay salas disponibles.",
	L"Solo el creador de la sala puede llevar a cabo esa gestión.",
	L"El estatus de la sala no autoriza de momento ningún paquete.",
	L"Este jugador todavía no está listo.",
	L"El número de miembros del equipo no coincide.",
	L"Para poder comenzar el juego debe estar \"listo\" más de un personaje.",
	L"No se ha podido modificar el proceso de carga.",
	L"Se ha creado la sala.",
	L"Se ha modificado la información sobre la sala.",
	L"Se ha eliminado la sala.",
	L"No se ha podido encontrar a ningún jugador en la sala.",
	L"No has podido entrar.",
	L"No has podido abandonar la sala.",
	L"El identificador de usuario del PNJ muerto es incorrecto.",
	L"El PNJ ya está muerto.",
	L"Datos del monstruo incorrectos. Error en el proceso de carga.",
	L"No se puede encontrar al jugador.",
	L"Tipo de chat incorrecto.",
	L"No puedes expulsarte a ti mismo de la sala.",
	L"Puntos de voluntad insuficientes.",
	L"Este tipo de juego no apoya las estadísticas adicionales.",
	L"El juego ha terminado. No puedes entrar en la sala.",
	L"No puedes entrar en la sala.",
	L"La sala en la que deseas entrar no contiene ninguna información.",
	L"No puedes prepararte para una partida mientras comercias.",
	L"No puedes entrar en la sala porque la partida ya ha comenzado. Inténtalo más tarde.",
	L"En el inventario no se encuentra ningún objeto que inicie una partida.",
	L"Un jugador sin autorización ha intentado crear un observatorio.",
	L"Los datos del mapa de JcJ son erróneos.",
	L"Solo puede utilizar el canal de torneo aquel que posea una autorización de participación en modo desconectado para el torneo.",
	L"Te falta el objeto necesario para jugar en el escenario. Tras comenzar la partida serás expulsado del escenario.",
	L"La función de invitación solo puede utilizarse en la sala JcJ.",
	L"El jugador invitado no puede acceder, de momento, a la sala JcJ.",
	L"Solo puedes invitar a jugadores que se encuentren en el lobby del canal JcJ.",
	L"El juego solo puede comenzar si estás inscrito en el grupo.",
	L"Configuración errónea para el número de víctimas.",
	L"El objeto ya no existe.",
	L"Ya lo ha recogido alguien.",
	L"Fallo en la distribución aleatoria de los objetos.",
	L"No hay ninguna información disponible sobre el objeto.",
	L"La identificación del objeto es incorrecta.",
	L"El objeto no ha podido ser asignado.",
	L"El objeto no ha podido ser reparado.",
	L"No se ha podido utilizar el objeto de la casilla de acceso rápido.",
	L"No se pueden utilizar las casillas de acceso rápido en el escenario de evento",
	L"El objeto no ha podido ser adquirido.",
	L"El objeto no ha podido ser retirado del depósito",
	L"No hay espacio suficiente en el depósito.",
	L"El mensaje es demasiado largo.",
	L"No se ha podido cambiar de equipo",
	L"No se han podido guardar los cambios realizados en la casilla.",
	L"Participación fallida.",
	L"No se ha podido cerrar la casilla.",
	L"No se ha podido expulsar al usuario.",
	L"No se han podido guardar los datos de los adversarios.",
	L"No se ha podido modificar el estatus.",
	L"El jugador ha decidido abandonar la partida.",
	L"Se ha interrumpido la conexión.",
	L"Has sido expulsado.",
	L"Tu nivel es demasiado alto para este canal.",
	L"Se ha cerrado el puesto de venta.",
	L"No se ha podido visitar el puesto de venta.",
	L"Se acabó el tiempo. El puesto de venta se ha cerrado.",
	L"Se ha cancelado el puesto de venta.",
	L"El número de vendedores privados es incorrecto.",
	L"Se ha producido un error mientras se comerciaba.",
	L"O no tienes suficiente espacio en tu inventario o los datos sobre el objeto son erróneos.",
	L"No tienes suficientes puntos de voluntad.",
	L"Se ha cancelado el trato. No hay objetos con los que comerciar.",
	L"Se ha cancelado el trato.",
	L"Se ha cerrado el puesto de venta porque no se colocó ningún objeto.",
	L"Se ha cancelado el trato.",
	L"Se han vendido todos los objetos. Se cierra el puesto de venta.",
	L"Se ha cancelado el trato porque has abandonado la sala.",
	L"Se ha cerrado el puesto de venta.",
	L"El cliente se ha bloqueado.",
	L"No puedes permanecer en el canal de lucha durante más tiempo.",
	L"Si participas en modo JcJ, abandonas el grupo.",
	L"El grupo se disuelve porque se ha terminado el escenario.",
	L"Has abandonado el grupo porque te has ido al mercado.",
	L"Has entrado en el campo de entrenamiento. Has abandonado el grupo.",
	L"Terminado.",
	L"El juego se ha interrumpido debido a una sospecha de piratería.",
	L"El cliente se ha bloqueado. Se interrumpe el juego.",
	L"No se han podido modificar los EXP del personaje.",
	L"La base de datos no ha podido destinar al personaje.",
	L"El nivel de autoridad es incorrecto.",
	L"Este jugador no existe.",
	L"Error de transacción.",
	L"No hay ningún jugador disponible con este nivel de autoridad.",
	L"El operador ha interrumpido la conexión.",
	L"Esta orden solo puede ser llevada acabo sobre el terreno.",
	L"Esta orden no se puede llevar a cabo en esta sala.",
	L"No se puede comprar el objeto.",
	L"No se puede vender el objeto.",
	L"Se está llevando a cabo la misión.",
	L"Se ha intentado borrar una misión que no se ha completado.",
	L"Esta misión no existe.",
	L"Esta misión ya se ha completado.",
	L"Este personaje no puede completar esta misión.",
	L"No se ha completado la misión anterior.",
	L"El PNJ te ha dado la misión equivocada.",
	L"Esta plantilla de misión no existe.",
	L"La misión no puede terminar porque no se ha llevado a cabo todo lo que se pide.",
	L"La base de datos no ha podido procesar los datos de la misión.",
	L"Puedes aceptar un máximo de 10 misiones a la vez.",
	L"Tu nivel es demasiado bajo para aceptar la misión.",
	L"No puedes completar la misión con tan poco espacio en el inventario.",
	L"Se ha producido un error en la distribución de la recompensa de la misión.",
	L"No se ha podido encontrar la recompensa que se buscaba.",
	L"La misión de cambio de clase ya se ha completado.",
	L"Se ha producido un error en la atribución de la recompensa de la misión de cambio de clase.",
	L"El tipo de misión es incorrecto.",
	L"El mensaje del chat se ha introducido en menos tiempo del establecido.",
	L"No puedes susurrarte a ti mismo.",
	L"Error en el chat.",
	L"Este usuario no está conectado.",
	L"--/;/comillas/coma/espacio: no se pueden utilizar.",
	L"La entrada es más corta que el tiempo de carga de la lista actual de jugadores.",
	L"La búsqueda de los datos del usuario sigue en proceso.",
	L"Este usuario no está conectado.",
	L"Apodo no disponible.",
	L"No has podido entrar en la plaza de la villa.",
	L"No has podido abandonar la plaza de la villa.",
	L"Esta habilidad ya ha alcanzado su máximo nivel.",
	L"Esta habilidad no existe.",
	L"Tu nivel es demasiado bajo para aprender esta habilidad.",
	L"No tienes suficientes puntos de habilidad.",
	L"Te falta el objeto necesario.",
	L"Para esta adquisición necesitas la misión terminada.",
	L"Todavía no has aprendido habilidades anteriores.",
	L"Ya has aprendido esta habilidad.",
	L"La identificación de la casilla de habilidad que va a cambiarse es errónea.",
	L"Solo puedes registrar las habilidades que has aprendido.",
	L"Error al reiniciar la habilidad.",
	L"No se puede utilizar la barra de habilidades B.",
	L"Se ha producido un error durante la ampliación de la barra de habilidades B.",
	L"Podrás aprender esta habilidad cuando desaparezca el sello.",
	L"Esta habilidad se encuentra en un nivel que todavía no has alcanzado.",
	L"No tienes puntos de habilidad suficientes para aprender esta habilidad.",
	L"No tienes puntos de habilidad suficientes para aprender esta habilidad.",
	L"Has intentado modificar la información de una habilidad que no existe.",
	L"La información referente al nivel de la habilidad es incorrecta.",
	L"El nivel de habilidad seleccionado no se corresponde con el nivel correcto.",
	L"No se han podido llevar a cabo los cambios referentes a la validez de los puntos de habilidad de la tienda.",
	L"Fallo en el registro de los puntos de habilidad de la tienda.",
	L"No se ha actualizado la información referente a los puntos de habilidad de la tienda.",
	L"Fallo al reiniciar la información relativa a los puntos de habilidad de la tienda.",
	L"Las habilidades estándar no se pueden reiniciar.",
	L"No se ha podido crear el grupo.",
	L"No puedes salir del grupo.",
	L"La información sobre el grupo es incorrecta.",
	L"No se puede invitar a este usuario.",
	L"No está disponible ningún grupo relacionado.",
	L"Ya estás dentro del grupo.",
	L"No se puede crear ningún grupo en modo JcJ.",
	L"No puedes unirte a un grupo si estás en modo JcJ.",
	L"El grupo no puede aceptar a más miembros.",
	L"No puedes unirte al grupo.",
	L"Se ha borrado el grupo.",
	L"La entrada al grupo ha sido rechazada.",
	L"La entrada en el grupo ha sido rechazada.",
	L"Aquí no se puede iniciar el escenario.",
	L"Fallo en la modificación del estatus de disponibilidad.",
	L"No has seleccionado el escenario correcto.",
	L"Error al iniciar el juego.",
	L"El tipo de juego no es válido.",
	L"No eres el líder del grupo.",
	L"No se ha podido cambiar el líder del grupo.",
	L"No se han podido cambiar los miembros del grupo.",
	L"No puedes comenzar el escenario en esta región.",
	L"No se han podido modificar los ajustes de tu entorno privado.",
	L"El jugador que ha sido nombrado líder del grupo no puede completar el escenario actual.",
	L"El líder del grupo puede modificar el estatus de disponibilidad.",
	L"No está disponible ningún compañero de chat.",
	L"La lista de grupos que solicitas es incorrecta.",
	L"No se han podido modificar los ajustes referentes al límite de nivel.",
	L"Ese es un grupo privado.",
	L"No hay ninguna piedra de resurrección disponible.",
	L"Ya has resucitado.",
	L"Resurrección fallida.",
	L"No se puede utilizar la piedra de resurrección en este escenario.",
	L"No se puede actualizar un estatus que no está disponible.",
	L"No se han podido activar las opciones de la comunidad.",
	L"No puedes incluir más entradas en la lista negra.",
	L"Este jugador ya aparece en la lista negra.",
	L"Ya se ha borrado a este jugador de la lista negra.",
	L"Este jugador no existe.",
	L"No se puede borrar de la lista negra.",
	L"No te puedes incluir a ti mismo en la lista negra.",
	L"No te puedes borrar a ti mismo de la lista negra.",
	L"Solo puedes incluir en la lista negra a jugadores que estén conectados.",
	L"No puedes añadir a tu propio personaje.",
	L"Se ha acabado el tiempo límite para añadir a amigos.",
	L"No se puede encontrar a ese personaje.",
	L"Con este estatus tu personaje no puede invitar a nadie.",
	L"En este momento no puedes invitar al otro jugador.",
	L"El otro jugador no puede participar en este momento.",
	L"No puedes añadirlo como amigo.",
	L"No se ha podido crear el puesto de venta.",
	L"No puedes abandonar el comercio privado.",
	L"La búsqueda de jugadores con comercio privado no ha tenido éxito.",
	L"El objeto seleccionado está defectuoso.",
	L"La entrada de ED es incorrecta.",
	L"El objeto con el que se quiere comerciar no existe.",
	L"¡ED insuficiente!",
	L"Solo se pueden seleccionar objetos del inventario.",
	L"Espacio insuficiente en el inventario.",
	L"Los objetos que estén ligados al personaje no pueden venderse.",
	L"El chat de comercio no puede abrirse aquí.",
	L"No puedes comerciar contigo mismo.",
	L"Cuando la durabilidad de un objeto se agota, este no se puede vender. Repáralo e inténtalo de nuevo.",
	L"El objeto ya está registrado.",
	L"Solo se pueden borrar aquellos objetos que estén registrados.",
	L"Puedes seleccionar un máximo de 10 objetos diferentes.",
	L"Esta cantidad es superior al presupuesto del otro jugador. Baja el precio en ED para este trato.",
	L"La solicitud de comercio privado ha sido aceptada.",
	L"Ya está abierto un trato con otro jugador.",
	L"La solicitud de comercio privado ha sido rechazada.",
	L"No se puede comerciar.",
	L"No se puede comerciar debido a un error del servidor.",
	L"Te falta el objeto necesario para participar en este escenario.",
	L"No tienes permiso para entrar en el campo de entrenamiento.",
	L"Falta la identificación del escenario que sirve como campo de entrenamiento.",
	L"Se ha producido un error al guardar la recompensa.",
	L"El objeto seleccionado no está disponible en el inventario.",
	L"Se trata del objeto seleccionado, no del cubo.",
	L"Este personaje no puede utilizar el objeto.",
	L"No tienes llaves suficientes para abrir el cubo.",
	L"No se puede abrir el cubo.",
	L"No se ha podido crear el objeto.",
	L"Espacio insuficiente en el inventario para abrir el cubo.",
	L"Se ha detectado más de una inscripción.",
	L"El identificador de usuario del jugador es incorrecto.",
	L"El identificador del jugador es incorrecto.",
	L"El identificador de usuario del personaje es incorrecto.",
	L"El apodo del personaje es incorrecto.",
	L"El identificador de usuario del servidor del jugador es incorrecto.",
	L"La información sobre el jugador es errónea.",
	L"La información sobre el servidor del juego es errónea.",
	L"Fallo en la búsqueda de identificador de usuario.",
	L"El número de messenger es incorrecto.",
	L"No puedes fabricar este objeto.",
	L"Ese no es un objeto de pergamino.",
	L"¡ED insuficiente para fabricar!",
	L"No tienes sufientes materiales.",
	L"Para la fabricación debes tener al menos un espacio libre en el inventario.",
	L"No se ha podido crear el objeto.",
	L"Error en la certificación de HackShield.",
	L"El juego debe reiniciarse a causa de una actualización para HackShield.",
	L"Error en la verificación de HackShield.",
	L"O el cupón ya se ha canjeado o el número del cupón no es el correcto. Solo se puede utilizar un cupón por cuenta.",
	L"Introduce el código de 30 dígitos del cupón.",
	L"Este cupón ya se ha canjeado.",
	L"El cupón ya no es válido.",
	L"El número de cupón no es válido.",
	L"Este cupón solo puede ser canjeado una vez por cuenta.",
	L"No se ha podido canjear el cupón.",
	L"No has esperado el tiempo suficiente para poder comprarlo de nuevo.",
	L"No se puede acceder a la lista de objetos.",
	L"La información sobre el objeto es incorrecta.",
	L"No tienes espacio suficiente en tu inventario.",
	L"No se ha podido seleccionar el objeto de la tienda adquirido.",
	L"No se ha podido consultar el saldo.",
	L"No se ha podido encontrar información sobre los miembros.",
	L"Esta cuenta ha sido bloqueada.",
	L"No puedes pasar objetos de otros personajes a tu inventario.",
	L"Ya tienes este objeto.",
	L"Un momento, se está accediendo al objeto.",
	L"El tamaño promedio del campo de visión es incorrecto.",
	L"Este jugador no existe.",
	L"Este no es el objeto que permite cambiar el apodo.",
	L"Esta apodo ya no está disponible.",
	L"¡En estos momentos no se puede utilizar este apodo!",
	L"No se ha podido actualizar el apodo.",
	L"Este apodo no está permitido.",
	L"La longitud del apodo no es la correcta.",
	L"No se ha podido modificar el apodo.",
	L"No se ha podido crear el puesto de venta.",
	L"El puesto de venta solo se puede crear en la plaza de la villa.",
	L"No se puede acceder al puesto. No se ha encontrado información sobre el dueño.",
	L"El puesto está completo en este momento. Inténtalo de nuevo más tarde.",
	L"Apertura del puesto de venta fallida.",
	L"El número de objetos que quieres vender no concuerda con los datos.",
	L"El objeto ya se introdujo como vendido.",
	L"No puedes registrar objetos en puestos de venta ajenos.",
	L"Se han registrado más objetos de los que realmente se pueden vender.",
	L"No tienes el dinero suficiente para abrir un puesto de venta.",
	L"La creación del puesto de venta no se ha completado todavía.",
	L"Todavía no has abandonado la tienda.",
	L"El número de objetos que has seleccionado para comprar es superior al número de objetos que están en venta.",
	L"El objeto que quieres comprar no existe.",
	L"No tienes ED suficiente para comprar el objeto.",
	L"Necesitas más espacio en tu inventario para poder comprar algo.",
	L"No se puede comerciar porque no se ha podido encontrar al fabricante.",
	L"No puedes abrir un puesto de venta durante un trato.",
	L"El puesto de venta ya está abierto.",
	L"Has alcanzado la cantidad límite de ED.",
	L"Has alcanzado la máxima cantidad de ED que puedes comprar.",
	L"La información sobre los objetos que quieres comprar no es correcta.",
	L"El objeto seleccionado no está disponible en el inventario.",
	L"No se puede descomponer el objeto.",
	L"Error en la cancelación del objeto. Vuelve a intentarlo.",
	L"Solo puedes descomponer tu equipamiento y tus accesorios.",
	L"No se puede fragmentar.",
	L"No se ha podido crear el objeto.",
	L"No tienes espacio suficiente en el inventario\npara descomponer el objeto.",
	L"Los objetos con una duración limitada no se pueden dividir.",
	L"El objeto que quieres mejorar no está disponible en el inventario.",
	L"No existen datos del objeto.",
	L"Solo se pueden mejorar las armas o las partes de la armadura para la defensa.",
	L"Este objeto no se puede mejorar.",
	L"Ya no se puede mejorar.",
	L"¡Ninguna piedra de mejora disponible!",
	L"No se puede llevar a cabo la mejora.",
	L"No tienes suficiente ED para llevar a cabo una mejora.",
	L"Para una mejora, debes primero guardar o extraer el objeto.",
	L"La piedra flúor no existe en el inventario.",
	L"No se puede utilizar la piedra flúor.",
	L"La piedra flúor no se puede utilizar a partir del nivel 10 de mejora.",
	L"No se pueden mejorar objetos que no puedes utilizar.",
	L"Mejora fallida.",
	L"El objeto que va a repararse no está en tu inventario.",
	L"No existen datos del objeto.",
	L"No se puede reparar el objeto.",
	L"Solo se reparan aquellos objetos que no puedes utilizar.",
	L"No hay suficientes piedras de regeneración disponibles.",
	L"No se reparan los objetos equipados.",
	L"No se pueden utilizar aquellos objetos cuya habilidad esté desactivada.",
	L"Mejora completada correctamente.",
	L"Ningún cambio.",
	L"Ha bajado un nivel.",
	L"Reinicio del nivel de mejora.",
	L"No se puede utilizar el objeto.",
	L"Objeto no disponible en el inventario.",
	L"No existen datos del objeto.",
	L"Tasa demasiado elevada.",
	L"Solo se pueden engastar las armas y las partes de la armadura.",
	L"En tu equipamiento no hay información sobre la piedra mágica.",
	L"En el inventario no hay ninguna piedra mágica disponible.",
	L"No se puede utilizar el engaste.",
	L"Ya se ha engastado la piedra mágica.",
	L"La piedra mágica ya se ha retirado del engaste.",
	L"La opción de engaste no existe.",
	L"El apodo no existe.",
	L"No te puedes recomendar a ti mismo.",
	L"Nadie puede aceptar la recompensa.",
	L"El archivo privado que debe borrarse no está disponible en la base de datos.",
	L"No se ha podido acceder a la lista de aprendices.",
	L"No se puede mostrar esa información. El nivel es demasiado bajo.",
	L"Tu nivel no es lo suficientemente alto como para hacerte cargo de un aprendiz.",
	L"Solo se puede registrar a un máximo de 3 aprendices.",
	L"Él ya tiene un maestro.",
	L"Ya está registrado como aprendiz.",
	L"El objeto que deseas comprar es incorrecto.",
	L"No puedes comprar este objeto.",
	L"Ya se ha realizado el pago.",
	L"Has sobrepasado la cantidad máxima de objetos.",
	L"Has sobrepasado la cantidad máxima de objetos que se deben comprar.",
	L"Este objeto no se puede comprar de nuevo.",
	L"No hay ninguna cesta de la compra disponible.",
	L"El uso del juego es limitado.",
	L"La cantidad de objetos es limitada. No se puede adquirir este objeto.",
	L"La cantidad de pedidos es limitada.",
	L"Este objeto no se puede adquirir de nuevo en este momento.",
	L"Este objeto no se puede regalar.",
	L"La cantidad por cada pedido es limitada.",
	L"El otro jugador no puede aceptar el objeto en este momento.",
	L"Ese jugador está bloqueado.",
	L"No se ha encontrado información sobre los jugadores.",
	L"Saldo insuficiente.",
	L"Se está comprobando el sistema.",
	L"Se ha alcanzado la cantidad máxima de piedras de resurrección.",
	L"No se pueden crear más casillas en el inventario.",
	L"No te puedes regalar algo a ti mismo.",
	L"Los datos de acceso no son correctos.",
	L"El apodo no existe.",
	L"No les puedes regalar nada a los jugadores que tengan una ID de prueba.",
	L"Has sobrepasado la cantidad de objetos regalados.",
	L"Introduce la contraseña.",
	L"Error en la verificación de la cuenta.",
	L"Este objeto no se puede regalar.",
	L"Los jugadores menores de 14 años no pueden utilizar esta función.",
	L"No se puede adquirir este objeto.\nSolo se permite un máximo de 9 casillas de personaje.",
	L"No se ha podido ampliar la casilla de personaje.",
	L"Esta función ya está en uso.",
	L"Esta habilidad no existe.",
	L"El objeto para reiniciar una habilidad no existe.",
	L"No se ha podido borrar de la base de datos el objeto para reiniciar una habilidad.",
	L"Se ha producido un error en la base de datos al reiniciar la habilidad.",
	L"No se puede reiniciar la habilidad.",
	L"No se puede reiniciar una habilidad mientras esta se encuentre en la casilla de acceso rápido.",
	L"Este objeto no se puede marcar.",
	L"No puedes meter más productos en la cesta.",
	L"No puedes utilizar esta función como tester.",
	L"Los jugadores con una ID de prueba no pueden recomendar el juego.",
	L"Has alcanzado el máximo nivel permitido con una ID de prueba. Si deseas continuar jugando, debes acceder con una ID válida.",
	L"Los jugadores con una ID de prueba no se pueden añadir a la lista de amigos.",
	L"Este usuario no está incluido en la lista de hackeo.",
	L"La base de datos todavía no ha actualizado los datos de conformidad de hackeo.",
	L"Todavía no has confirmado el mensaje de jugadores de hackeo.",
	L"Este objeto no está en el inventario.",
	L"No se han podido mejorar estas características.",
	L"Ya se han mejorado las características de la casilla.",
	L"Ya se ha vaciado esta casilla.",
	L"¡No tienes ED suficiente para una mejora de atributo!",
	L"No tienes suficientes fragmentos de Éldrit para un hechizo.",
	L"Información sobre el objeto incorrecta.",
	L"La mejora de atributos solo se puede aplicar a las armas y a las armaduras.",
	L"El objeto seleccionado no se puede descomponer.",
	L"¡No hay suficientes herramientas de análisis disponibles!",
	L"No hay espacio suficiente en el inventario\npara descomponer el objeto.",
	L"El objeto seleccionado no se puede descomponer.",
	L"Error en la fabricación del objeto.",
	L"No se puede acceder a la bandeja de entrada.",
	L"El objeto seleccionado no se puede adjuntar en el correo electrónico.",
	L"La cantidad especificada de ED no se puede enviar por correo.",
	L"No se ha podido enviar el correo.",
	L"El correo no existe.",
	L"No hay suficiente espacio en el inventario para trasladar el objeto adjunto. Haz sitio en el inventario e inténtalo de nuevo.",
	L"No se ha podido recoger el objeto adjunto.",
	L"Has intentado añadir un objeto que no existe.",
	L"Solo se pueden añadir objetos que estén completamente reparados.",
	L"Este apodo no existe.",
	L"¡No te puedes enviar mensajes a ti mismo!",
	L"No tienes suficiente ED para enviar el mensaje.",
	L"El otro jugador no tiene suficiente espacio en la bandeja de entrada y no puede recibir más mensajes.",
	L"Has seleccionado un mensaje borrado.",
	L"El jugador ha rechazado tu mensaje.",
	L"No puedes enviar en un mensaje aquellos objetos que estén ligados a tu personaje.",
	L"No se puede enviar mensajes a jugadores con una ID de prueba.",
	L"El apodo no existe.",
	L"Este apodo ya está incluido en la lista negra.",
	L"Error en la inscripción en la lista negra.",
	L"El apodo ya se ha borrado.",
	L"No se ha podido borrar al jugador de la lista negra.",
	L"No posees este título.",
	L"Ya posees este título.",
	L"La validez de este título ha expirado.",
	L"Este título no existe.",
	L"No se ha conseguido este título.",
	L"Ya posees este título.",
	L"Este objeto no se puede utilizar.",
	L"Este objeto no existe.",
	L"Tu nivel es demasiado bajo para este objeto.",
	L"El objeto no se puede utilizar en el inventario.",
	L"Este objeto no está en el inventario.",
	L"Objeto no permitido.",
	L"El objeto no está permitido.",
	L"Mejora fallida.",
	L"Este objeto no se puede cambiar.",
	L"Este objeto no está en el inventario.",
	L"No puedes comerciar con este objeto.",
	L"No se han creado los objetos que se van a intercambiar.",
	L"Abandonas este lugar para llegar a otra zona.",
	L"Abandonas la llanura para entrar en una sala.",
	L"El sistema ha procesado tu renuncia.",
	L"No puedes entrar en la villa.",
	L"No puedes abandonar la villa.",
	L"No se puede acceder a la lista de jugadores.",
	L"Tu nivel es demasiado bajo para entrar en la villa.",
	L"Todavía no has completado el escenario que te permite el acceso a la villa.",
	L"Este canal no existe.",
	L"El cambio de canal se efectuó correctamente. Conexión terminada.",
	L"Error en el registro del cambio de canal.",
	L"No estás registrado para un cambio de canal.",
	L"Ya estás en el canal al que te quieres cambiar.",
	L"Se ha alcanzado el número máximo de miembros. El cambio no es posible.",
	L"El cambio de canal solo funciona en la villa o en las afueras de una villa.",
	L"Intenta cambiar de canal de nuevo más tarde.",
	L"No puedes utilizar esta función con este jugador.",
	L"No se ha seleccionado ningún personaje.",
	L"Este amigo no está conectado.",
	L"Estatus incorrecto.",
	L"La base de datos no ha actualizado el botín del evento.",
	L"Ya has recibido la recompensa del evento.",
	L"Este jugador ya es tu amigo.",
	L"El estatus del personaje de tu amigo no es válido.",
	L"Este jugador no te ha añadido como amigo.",
	L"Este jugador no es tu amigo.",
	L"Este grupo no existe.",
	L"El mensaje es demasiado largo.",
	L"Este es el mismo grupo al que te quieres cambiar.",
	L"No se pueden crear más grupos.",
	L"Este grupo ya existe.",
	L"Este nombre de grupo ya está en uso.",
	L"Tu aprendiz no se ha conectado en 7 días. Se ha cancelado la formación.",
	L"Tu aprendiz ha subido un nivel. La formación ha concluido.",
	L"Se ha borrado el personaje. La formación ha concluido.",
	L"La formación se ha cancelado.",
	L"No has podido concluir la formación.",
	L"Error en la base de datos referente a las funciones de amigos.",
	L"El nombre de grupo es demasiado largo.",
	L"Tu lista de amigos está llena. No se ha podido enviar la invitación.",
	L"No se pueden enviar solicitudes de amistad entre personajes de una misma cuenta.",
	L"La lista de amigos del otro jugador está llena. No se puede enviar la solicitud de amistad.",
	L"Tu solicitud de amistad ha sido rechazada.",
	L"Búsqueda fallida.",
	L"No se puede entrar en el canal JcJ.",
	L"En JcJ, el juego comienza cuando todos los puestos están ocupados.",
	L"El asunto es demasiado largo.",
	L"El mensaje es demasiado largo.",
	L"El jugador invitado no puede entrar en el escenario.",
	L"Ya se ha retirado el sello.",
	L"No se ha podido retirar el sello de la habilidad.",
	L"¡No tienes la clase correcta para este objeto!",
	L"Ya has habilitado esta habilidad.",
	L"En el inventario ya hay un objeto con las mismas funciones. No se ha podido comprar el artículo.",
	L"No se puede invitar al Espacio-tiempo de Henir a los jugadores con una ID de prueba.",
	L"El tipo de certificación no es válido.",
	L"Los objetos que están en el banco no se pueden descomponer.",
	L"Los objetos que se guardan en el banco no se pueden engastar.",
	L"Esta función no se puede utilizar en el banco.",
	L"El número de casillas del banco no puede aumentar más.",
	L"Solo se puede comprar un carné de socio para el banco.",
	L"No se puede comprar el carné de socio del banco.",
	L"Si posees una garantía de Loriel en el inventario, puedes comprar una carné de socio platino. Utiliza ahora la garantía de Loriel.",
	L"La contraseña no existe.",
	L"La contraseña no se puede renovar.",
	L"El nombre de usuario o la contraseña es incorrecto.",
	L"Se ha producido un error en el sistema durante la fase de autenticación.",
	L"El objeto no existe.",
	L"La información sobre el objeto no está disponible.",
	L"No se puede sellar este tipo de objetos.",
	L"No se pueden sellar los objetos equipados.",
	L"El objeto ya está sellado.",
	L"No se puede sellar un objeto que no está reparado.",
	L"No se pueden sellar los objetos con una duración limitada.",
	L"No se pueden sellar los objetos destruidos.",
	L"No se pueden sellar los objetos con los que puedes comerciar.",
	L"No se pueden poner más sellos.",
	L"La información sobre el pergamino de sello es incorrecta.",
	L"Sello fallido.",
	L"¡No tienes suficientes pergaminos de sello!",
	L"No se puede retirar el sello de los objetos equipados.",
	L"Ya se ha retirado el sello de este objeto.",
	L"Error al retirar el sello.",
	L"Error en la actualización de la base de datos referente a la información sobre el sello.",
	L"Los objetos sellados no se pueden mejorar.",
	L"Error del sistema en la consulta de monedas El.",
	L"Esta cuenta tiene un radio de actividad limitado.",
	L"Esta cuenta no existe.",
	L"Esta cuenta es falsa.",
	L"El número de cupón no es válido.",
	L"Este cupón ya se ha canjeado.",
	L"Este tipo de cupón solo se puede usar una vez.",
	L"El cupón ha expirado.",
	L"Se ha producido un error en el sistema al canjear el cupón.",
	L"Monedas El insuficientes.",
	L"Se ha producido un error en el sistema durante la compra.",
	L"La compra solo es posible a partir del nivel 15.",
	L"Ya estás inscrito en un gremio.",
	L"Este nombre de gremio ya está en uso.",
	L"El objeto que permite la creación del gremio no está en el inventario.",
	L"El objeto que permite la creación del gremio es incorrecto.",
	L"Error en la creación del gremio.",
	L"Error en la inscripción como maestro del gremio.",
	L"No se ha podido encontrar información sobre el gremio.",
	L"No se puede enviar la invitación al gremio.",
	L"Este jugador está desconectado.",
	L"No se puede invitar a un gremio a un jugador con una ID de prueba.",
	L"Este jugador ya ha sido invitado al gremio.",
	L"Este jugador ya ha sido invitado por otro gremio.",
	L"No tienes la autoridad para invitar a nadie al gremio.",
	L"No puedes aumentar el número de miembros del gremio. Necesitas un objeto que cree más espacio para miembros.",
	L"El jugador invitado ya es un miembro del gremio.",
	L"Este jugador ya está en un gremio.",
	L"No puedes ver la lista de gremios.",
	L"El objeto que debes comprar con el cupón es incorrecto.",
	L"El jugador ha rechazado la invitación del gremio.",
	L"Error en la inscripción en el gremio.",
	L"No es miembro de ningún gremio.",
	L"No tienes autoridad para cambiar el rango de los miembros del gremio.",
	L"No se ha podido cambiar el rango de los miembros del gremio.",
	L"Solo el maestro y el administrador del gremio pueden modificar el mensaje de gremio.",
	L"Error en la modificación del mensaje de gremio.",
	L"No tienes autorización para echar a ningún miembro del gremio.",
	L"El maestro del gremio no puede abandonar el gremio.",
	L"Error al abandonar el gremio.",
	L"El saludo del gremio tiene una longitud limitada.",
	L"No tienes autorización para cambiar el saludo del gremio.",
	L"Error al modificar el saludo del gremio.",
	L"Solo el maestro del gremio está autorizado para disolver el gremio.",
	L"No se puede disolver el gremio. Todavía hay miembros inscritos.",
	L"Error al disolver el gremio.",
	L"Se ha cambiado el rango de clase.",
	L"Ya hay un administrador del gremio.\nCambia el rango del administrador\npara nombrar a uno nuevo.",
	L"El maestro del gremio no puede borrar su personaje. Pasa el título de maestro del gremio a otro miembro.",
	L"No puedes cambiar tu propio rango de clase.",
	L"No puedes comprar ningún permiso de creación del gremio porque ya perteneces a uno.",
	L"Ya tienes un permiso de creación del gremio.",
	L"Error al aumentar el número de miembros.",
	L"Solo el maestro y el administrador del gremio pueden usar la carta de ampliación.",
	L"No se pueden aceptar más miembros en el gremio.",
	L"Esta función no se puede utilizar mientras se comercia.",
	L"No te puedes cambiar a esta zona.",
	L"Este nombre de gremio no estará disponible durante 7 días.",
	L"Esa es la cantidad máxima de puntos de experiencia.",
	L"Para poder comprar ese objeto debes completar la misión correspondiente.",
	L"El nombre de gremio es demasiado largo.",
	L"No tienes ED suficiente para retirar el atributo.",
	L"Puedes comprar este objeto a partir del nivel 35.",
	L"게임을 종료하고 빈펀 계정으로 업그레이드 하시기 바랍니다. 빈펀 사이트는 tw.beanfun.gamania.com 입니다.",
	L"이 계정은 이미 빈펀 계정으로 업그레이드 된 계정입니다. 빈펀 프로그램으로 접속해주세요.",
	L"No se pueden comprar más objetos. Tu inventario temporal está lleno.",
	L"Solo el maestro del gremio puede utilizar los PHG.",
	L"Esta habilidad de gremio ya ha sido entrenada hasta el máximo nivel.",
	L"No hay información sobre la habilidad de gremio.",
	L"La anterior habilidad de gremio todavía no se ha entrenado hasta el máximo nivel.",
	L"No se emplearon suficientes puntos de habilidad.",
	L"PHG insuficientes.",
	L"Error al aprender la habilidad de gremio.",
	L"Solo el maestro del gremio puede reiniciar las habilidades de gremio.",
	L"¡Necesitas la \"Flauta cuerno del olvido\"!",
	L"No se puede reiniciar la habilidad de gremio.",
	L"Error al restituir la habilidad de gremio.",
	L"Solo el maestro del gremio puede reiniciar las habilidades de gremio.",
	L"La \"Flauta cuerno del olvido\" no está disponible en el inventario.",
	L"No se puede reiniciar la habilidad de gremio.",
	L"Error al reiniciar la habilidad de gremio.",
	L"Solo se puede usar a través del maestro del gremio.",
	L"No has obtenido puntos de habilidad de gremio limitados.",
	L"El objeto bendito del conocimiento ya está en uso.",
	L"Todavía no puedes recibir la recompensa del evento.",
	L"No tienes suficiente espacio en el inventario para aceptar la recompensa del evento.",
	L"Error al recibir la recompensa del evento.",
	L"Ese no es el modo objeto.",
	L"Todavía falta un botín.",
	L"No se ha podido recoger el botín del JcJ.",
	L"Puedes crear la clase después de usar la carta del personaje.",
	L"Esta cuenta no puede participar en el evento.",
	L"Solo el maestro y el administrador del gremio pueden usar esta función.",
	L"PC방 전용 아이템은 이용할 수 없는 기능입니다.",
	L"El anuncio del gremio no existe.",
	L"El texto es demasiado largo.",
	L"El período de inscripción para el anuncio no es válido.",
	L"No tienes suficiente ED para registrar el anuncio.",
	L"Ya se ha registrado un anuncio.",
	L"El registro del anuncio del gremio no ha funcionado.",
	L"En este momento no se puede realizar ninguna inscripción porque hay demasiadas solicitudes.",
	L"Error en la inscripción en el gremio.",
	L"Ya has solicitado la inscripción.",
	L"No existe información sobre la solicitud de inscripción.",
	L"La inscripción en el gremio no ha sido aceptada.",
	L"La solicitud de inscripción en el gremio no se ha borrado.",
	L"No se puede solicitar una inscripción si se trata de un anuncio con un período limitado.",
	L"No tienes autorización para ver la lista de solicitudes de inscripción en el gremio.",
	L"No has abierto el castillo.",
	L"Esta cuenta se ha bloqueado.",
	L"",
	L"",
	L"Has sido expulsado de la sala por sospecha de hackeo.",
	L"No puedes solicitar ninguna inscripción porque la opción \"denegar invitación del gremio\" está activada.",
	L"No puedes solicitar más inscripciones porque hay demasiadas solicitudes de inscripción en el gremio.",
	L"Esa no es la misión que se está llevando a cabo.",
	L"Se ha alcanzado el límite de compra del objeto en cuestión.",
	L"Las monedas El están desactivadas. Puedes cambiar los ajustes en la página web si te diriges a \"Mi información\", en el menú \"Seguridad de ingresos\".",
	L"Se ha realizado la verificación de estatus.",
	L"La consulta de la base de datos sobre el aumento de los puntos de la web no ha funcionado.",
	L"Error en la verificación del estatus.",
	L"Has abandonado el grupo a causa de una doble inscripción.",
	L"El estatus de grupo se está cargando.",
	L"Borrar lista de objetos",
	L"Añadir lista de objetos",
	L"Revisar lista de objetos",
	L"La selección de categoría no es correcta.",
	L"La búsqueda no ha dado resultados.",
	L"Los invitados no tienen suficiente fuerza de voluntad.",
	L"Comienza la búsqueda de nuevo más tarde.",
	L"La venta finalizó en esta tienda.",
	L"El jugador no ha activado el estatus de compra.",
	L"Error al crear la sala.",
	L"El objeto no existe.",
	L"Esta página no existe.",
	L"Esta nota ya se ha registrado.",
	L"No se ha podido registrar la nota.",
	L"No tienes ningún cuaderno de técnicas.",
	L"Error al incluir la nota de técnica.",
	L"Ya tienes esta nota de técnica.",
	L"Para comprar este objeto debes alcanzar el nivel 20.",
	L"No se puede comerciar con jugadores de otros servidores.",
	L"No se pueden utilizar los puestos de venta de otros servidores.",
	L"No puedes invitar al gremio a jugadores de otros servidores.",
	L"No se puede registrar como aprendices a jugadores de otros servidores.",
	L"No puedes añadir como amigos a jugadores de otros servidores.",
	L"No pueden pasarte el modo desafío del Espacio-tiempo de Henir con usuarios de otros servidores.",
	L"Bloqueo de cuenta del servidor del juego por sospecha de hackeo.",
	L"[홍콩] 해당 직업으로는 전직을 할 수 없습니다.",
	L"El número de objetos que quieres desechar es incorrecto.",
	L"La mascota no se ha creado correctamente.",
	L"Este nombre ya está en uso.",
	L"El nombre debe tener un máximo de 12 caracteres.",
	L"Creación de la mascota.",
	L"No se ha podido llamar a la mascota.",
	L"La mascota no se puede crear aquí.",
	L"Ya has llamado a una mascota.",
	L"Ya se ha llamado a esta mascota.",
	L"No se ha podido echar a la mascota.",
	L"No se ha podido llevar a cabo la orden.",
	L"Tu mascota ha saciado su hambre. No puede comer más.",
	L"No se ha podido alimentar a la mascota.",
	L"La mascota está creciendo. Ahora mismo solo puede comer Frutas y Semillas del Árbol de El.",
	L"Eso ya se ha grabado.",
	L"El siguiente nivel de desarrollo todavía no está disponible.",
	L"La evolución solo es posible si el nivel de intimidad alcanza el 100%.",
	L"La mascota no puede utilizar este objeto.",
	L"El nivel de comida es demasiado bajo.",
	L"Los datos de acceso son incorrectos.",
	L"Los datos de acceso son incorrectos.",
	L"Esta cuenta todavía no está validada.",
	L"La mascota no puede comer este alimento.",
	L"El usuario está ocupado.",
	L"[CN] 매트릭스 카드가 바인딩되어 있습니다.",
	L"[CN] OPT번호가 틀렸습니다. 다시 입력해 주십시요.",
	L"[CN] 보안카드 번호를 잘못 입력 하셨습니다. 다시 입력해 주십시요.",
	L"[CN] 계정 정보가 수정 과정에 있습니다. 의문 사항이 있으시면 서비스 센터로 연락 바랍니다.",
	L"[CN] 자이언트 패스워드 보안이 바인딩 해제 상태에 있습니다. 의문사항이 있으시면 서비스 센터로 연락 바랍니다.",
	L"GM키에란",
	L"GM리엘",
	L"[Remitente desconocido]",
	L"지금은 청약철회 기능을 이용 하실 수 없습니다.",
	L"청약철회 가능 개수보다 요청 갯수가 커서 청약철회를 실패하였습니다.",
	L"구매한지 7일이 초과된 상품으로 청약철회가 불가능 합니다.",
	L"패키지 중 일부 상품을 수령하여 청약철회가 불가능 합니다.",
	L"상품 가격이 0원으로 청약철회가 불가능한 상품 입니다.",
	L"중복된 RequestID입니다.",
	L"No hay ninguna información de compra disponible sobre este artículo.",
	L"No hay ninguna información disponible sobre este artículo.",
	L"청약철회가 불가능한 상품 입니다.",
	L"선물 받은 상품이어서 청약철회가 불가능 합니다.",
	L"No es posible desechar objetos con limitación de tiempo.",
	L"Los objetos que no se pueden vender tampoco se pueden desechar.",
	L"1 EL coins 이벤트 구매 제한을 초과 하여 더 이상 구매 할 수 없습니다. ",
	L"Tu nivel es demasiado bajo para este objeto.",
	L"Las piedras flúor no se pueden utilizar a partir del nivel 11.",
	L"No puedes aceptar esta misión porque ya has recibido la recompensa.",
	L"No puedes aceptar la misión porque no tienes espacio suficiente en el inventario para la recompensa.",
	L"Error al utilizar la Piedra mágica.",
	L"Esta función no está disponible en este momento.\nSentimos las molestias.",
	L"El acceso para esta IP es limitado.",
	L"Se ha limitado la función de chat.",
	L"Se ha limitado la función de comercio.",
	L"No se puede iniciar el juego porque el objeto no existe.",
	L"El juego se ha visto interrumpido por otro programa.",
	L"해당 유저가 존재하지 않습니다.",
	L"잔액이 부족합니다.",
	L"존재하지 않는 아이템 카드입니다.",
	L"해당 카드는 해당 구역에서 사용이 불가능합니다.",
	L"이미 사용한 아이템 카드입니다.",
	L"잘못된 전용 카드 ID입니다.",
	L"잘못된 전용 카드 패스워드입니다.",
	L"DB 에러",
	L"No puedes enviar mensajes porque se han restringido tus acciones.",
	L"No puedes abrir ningún puesto de venta porque se ha restringido el comercio.",
	L"No puedes acceder a tu puesto de venta porque se ha restringido el comercio.",
	L"No puedes buscar objetos porque se ha restringido el comercio.",
	L"No puedes entrar en el mercado porque se ha restringido el comercio.",
	L"캐시 인벤토리에 아이템이 존재합니다.(HK 이벤트에 사용)",
	L"Se necesita a más de dos miembros del grupo.",
	L"No se puede entrar en el escenario porque está bloqueado.",
	L"No puedes entrar en el escenario de misión mundial con otros jugadores de este servidor.",
	L"El registro para el control de correo cuesta lo mismo.",
	L"El registro para el control de venta cuesta lo mismo.",
	L"Error en el registro para el control de correos.",
	L"Error en el registro para el control de venta.",
	L"No puedes desactivar a la agente porque todavía se está vendiendo mercancía.",
	L"La agente no está activada.",
	L"No puedes cancelar el proceso de compra.",
	L"Esta es una venta privada: no se pueden comprar objetos.",
	L"No puedes abrir ningún puesto de venta porque la agente todavía está activada.",
	L"Se cerrará tu puesto de venta por haber incumplido las normas.",
	L"No puedes desactivar a la agente.",
	L"Unregisted User.",
	L"It is already canceled.",
	L"Invalid coupon number.",
	L"This coupon can not be canceled.",
	L"The used user information and cancel the requested user information does not match.",
	L"The issued cash by coupons  already had used . so can not be canceled.",
	L"requested price should be equal to billing items price.",
	L"The balance short.",
	L"Billing account that is unavailable.",
	L"You can not register any more today.",
	L"This coupon can not verify the information.",
	L"Coupon is already used.",
	L"Coupon use is stopped.",
	L"Coupon is expired.",
	L"Coupon is not available in the game.",
	L"Issued to certain customers who can use coupons, you do not have permission.",
	L"Buying is a restricted user.",
	L"Your use is limited to the payment service.",
	L"Your use is limited to the purchase service.",
	L"User cannot be verified.",
	L"Registration has exceeded the number of coupons available.",
	L"Unable to login due to IP restriction.",
	L"The coupon code has already been redeemed.",
	L"You cannot purchase the item at the moment. Your account have reached the daily limit for purchasing the item.",
	L"Has introducido mal tu contraseña dos veces y ahora no puedes conectarte.",
	L"Si quieres vender objetos a través de la agente debes firmar un contrato.",
	L"Los PINs introducidos no son idénticos.",
	L"Has introducido mal tu PIN 10 veces.\nSi pulsas el botón \"Confirmar\" se cancelará la conexión.\nTendrás que conectarte en la página web para reiniciar el contador.",
	L"Error al fijar un PIN.",
	L"PIN incorrecto.",
	L"El nombre del objeto es demasiado largo.",
	L"Se ha cerrado el puesto de venta de la agente.\nDespués de recibir tus objetos puedes abrir un nuevo puesto de venta.",
	L"La agente está vendiendo estos objetos.\nSi quieres recibir el dinero de los artículos que se hayan vendido,\ndebes cerrar el puesto de venta de la agente.",
	L"Error en la consulta de la base de datos para el contrato de la agente.",
	L"La agente no ha podido ser activada.",
	L"No se han podido colocar los objetos en el puesto de venta de la agente.",
	L"Solo puede utilizar esto el cliente de la agente.",
	L"No se han podido entregar los objetos a la agente.",
	L"No puedes recoger ningún objeto que se esté vendiendo.",
	L"Ya has recibido este objeto.",
	L"Has alcanzado la cantidad máxima de ED y ya no puedes acumular más.",
	L"Ya no tienes espacio en tu inventario.",
	L"No tienes objetos.",
	L"No puedes comprar los mismos objetos al mismo tiempo.",
	L"Tu nivel es demasiado bajo.\nNo puedes crear ninguna solicitud de grupo.",
	L"No puedes comprar ningún objeto porque la agente todavía está activada.",
	L"Todavía hay objetos que debes aceptar antes de poder vender más artículos.",
	L"La agente cierra el puesto de venta porque se han vendido todos los objetos.",
	L"Ya has aceptado esta misión y recibido la recompensa. No puedes aceptarla de nuevo.",
	L"No puedes aceptar la misión porque no tienes espacio en el inventario.",
	L"No se ha podido cambiar el nivel mínimo del grupo.",
	L"No puedes abrir ningún puesto de venta porque la agente ha vendido todos los objetos.",
	L"(TW/HK)강화 보조 아이템 사용 불가",
	L"(TW/HK)강화 보조 아이템이 없습니다.",
	L"(TW/HK)파괴 방지 아이템 사용 불가",
	L"(TW/HK)파괴 방지 아이템이 없습니다.",
	L"Tu nivel es demasiado bajo.\nEscoge otro escenario o elimina la restricción de nivel.",
	L"Tu nivel es demasiado bajo.\nNo puedes establecer ninguna restricción de nivel.",
	L"El nivel del jugador invitado es demasiado bajo.",
	L"Tu nivel es demasiado bajo.\nEscoge un escenario que se corresponda con tu nivel.",
	L"No se pueden repetir cifras contiguas en el PIN\n(0000, 1111, 999999, etc.).",
	L"Por favor, no utilices cifras consecutivas en el PIN\n(1234, 9876, 123456, etc.).",
	L"Error al eliminar el segundo teclado PIN.",
	L"El segundo teclado PIN no está en uso.",
	L"El nuevo PIN tiene que ser diferente del anterior.",
	L"El objeto no se vende en la tienda.",
	L"El combate terminó al comenzar el JcJ.",
	L"Un jugador no puede participar en el buscador JcJ.",
	L"El buscador automático se ha interrumpido.",
	L"El buscador automático se ha interrumpido porque el miembro del grupo no ha participado en el JcJ.",
	L"El combate ha finalizado correctamente. Has sido borrado de la lista de espera.",
	L"Un usuario ha interrumpido la inscripción al combate y ha sido borrado de la lista de espera.",
	L"Se ha interrumpido la inscripción al combate porque un miembro del grupo ha salido del mismo.",
	L"Ya funciona el buscador automático.",
	L"Los datos sobre el miembro del grupo son incorrectos.",
	L"La información sobre el modo JcJ es incorrecta.",
	L"Solo puedes participar en un JcJ a partir del nivel 10.",
	L"Solo puedes unirte a un grupo JcJ a partir del nivel 10.",
	L"Ya has cambiado el modo JcJ.",
	L"No formar un grupo JcJ con cuatro miembros del escenario.",
	L"No se puede cambiar el modo JcJ.",
	L"La sala JcJ no se puede cambiar porque un miembro del grupo todavía no ha alcanzado el nivel 10.",
	L"Uno de los miembros del grupo todavía no ha alcanzado el nivel 10 y no puede entrar en la sala JcJ.",
	L"Solo pueden ser invitados a un grupo JcJ aquellos personajes que hayan alcanzado el nivel 10.",
	L"Solo puede convertirse en fundador de un grupo JcJ aquel personaje que haya alcanzado el nivel 10.",
	L"[CN]전환이 정상적으로 이루어지지 않았습니다. 다시 시도하여 주시기 바랍니다.",
	L"No es posible clasificar los objetos. Inténtalo de nuevo más adelante.",
	L"No te has inscrito en el buscador automático.",
	L"Ya estás en una sala JcJ.",
	L"Esta no es la sala JcJ.",
	L"Error al consultar.",
	L"No puedes invitar a un usuario que se ha inscrito en el buscador automático.",
	L"No puedes invitar a un usuario que aparezca en el buscador automático.",
	L"Tu rango es demasiado bajo para comprar este objeto.",
	L"Durante la búsqueda automática no puedes inscribirte en otros grupos.",
	L"Durante la búsqueda automática no puedes cambiar de grupo.",
	L"Durante la búsqueda automática no puedes cambiar de canal.",
	L"No se ha podido reconocer la identificación.",
	L"La identificación aparece conectada en varios canales al mismo tiempo.",
	L"Hoy no puedes aceptar más misiones aleatorias.",
	L"No acepto el contrato.",
	L"Error al mostrar los PH.",
	L"Error al introducir PH.",
	L"El nombre seleccionado para la base de datos es erróneo.",
	L"Error al comprobar datos.",
	L"죄송합니다. 캐쉬샵 점검으로 인해 이용하실 수 없습니다.",
	L"00시부터 06시까지 게임 접속이 제한됩니다.",
	L"No se ha encontrado información.",
	L"No puedes comerciar hasta que te registres como aventurero.",
	L"No puedes enviar mensajes hasta que te registres como aventurero.",
	L"[CN]사용실패!",
	L"Has abandonado el campo de batalla.",
	L"Puede adquirirse a partir del nivel 15.",
	L"ServerSN과 MachineID가 매칭되지 않는다.",
	L"MachineID와 ServerSN이 매칭되지 않는다.",
	L"DB에 존재 하지 않는 ServerSN이 있다.",
	L"DB에 존재 하지 않는 MachineID가 있다.",
	L"클라가 준 SN은 없는데 DB에는 MachineID에 해당하는 SN 존재.",
	L"제재된 SN입니다.",
	L"접속 제한된 ServerSN 입니다.",
	L"No puedes conectarte al servidor de prueba con esta cuenta.",
	L"Has abandonado automáticamente el grupo por reagrupación.",
	L"Este objeto no se puede comprar porque la ampliación ilimitada de casillas de habilidades ya está activa.",
	L"Este objeto no se puede comprar porque la ampliación ilimitada de casillas de habilidades ya está activa.",
	L"[CN] 귀하의 계정이 정지되었습니다. 고객 센터에 문의하여 주십시요.",
	L"[CN] 비밀번호를 잘못 입력 하셨습니다. 다시 입력해 주십시요.",
	L"[CN] 해당 계정은 존재하지 않습니다.",
	L"[CN] 불명확인 시스템 에러",
	L"Ya tienes una Medalla de la bendición en tu inventario, por eso no puedes abrir el cubo.",
	L"Tu nivel es demasiado bajo para adquirir este objeto.",
	L"Tu nivel es demasiado bajo para recibir la mercancía.",
	L"¡Error al crear grupo!",
	L"No hay suficientes miembros del grupo.",
	L"Retraso de la respuesta de los miembros del grupo invitados.",
	L"Este objeto no está en venta.",
	L"[JP] 한게임 빌링 오류로 구매할수 없습니다.",
	L"No se puede enviar por correo los objetos del sistema de banca compartida.",
	L"No se puede comerciar con los objetos del sistema de banca compartida.",
	L"Este objeto solo puede comprarse a partir del nivel 20.",
	L"Solo los personajes que pertenecen a un gremio pueden cambiarlo.",
	L"Se puede adquirir a partir del nivel 30.",
	L"Solamente es posible enviar solicitudes de participación para grupos de JcJ con el parche completo.",
	L"블랙리스트에 등록된 DLL 이 존재합니다.",
	L"¡Conéctate de nuevo o inténtalo otra vez más tarde!",
	L"No puedes volver a participar en el concurso hoy.",
	L"Error desconocido",
	L"Mientras el comercio esté restringido no puedes adquirir objetos.",
	L"No se puede utilizar mientras el comercio esté restringido.",
	L"No puedes aumentar más la barra de acceso rápido.",
	L"El personaje ya ha sido eliminado o está a punto de serlo.",
	L"En estos momentos no es posible eliminar el personaje.",
	L"En estos momentos no es posible eliminar definitivamente el personaje.",
	L"No se puede eliminar definitivamente este personaje.",
	L"Este personaje no se podrá recuperar después de ser eliminado.",
	L"En estos momentos no es posible recuperar personajes.",
	L"Por favor, inténtalo de nuevo más tarde.",
	L"Este personaje no existe.",
	L"No se ha podido eliminar el personaje.",
	L"Error al cambiar de nombre a la mascota.",
	L"El cambio de nombre de mascota ya está en marcha.",
	L"El juego se ha interrumpido.",
	L"No eres el maestro del gremio.",
	L"Los datos del objeto son incorrectos.",
	L"¡Error al cambiar el nombre del gremio!",
	L"En proceso...",
	L"Has intentado eliminar un objeto que no existe.",
	L"[TW] 낚시대를 장착하지 않았거나, 미끼가 없습니다.",
	L"[TW] 이미 사용중인 낚시터 입니다.",
	L"[TW] 낚시터에 문제가 있습니다. 다른 곳을 이용해 주세요.",
	L"[TW] 낚시 보상에 문제가 발생했습니다.",
	L"Error al eliminar el objeto.",
	L"Solamente el maestro del gremio tiene derecho a cambiar el nombre de su gremio.",
	L"펫이 있을 때만 사용이 가능합니다. 펫이 없을 경우 일주일 이내에 청약 철회를 하셔야 합니다.",
	L"Ha concluido el tiempo de procesamiento y el proceso se ha interrumpido. Por favor, inténtalo otra vez.",
	L"El usuario ha cancelado el cambio de nombre de gremio.",
	L"No tienes permiso para acceder a este lugar.",
	L"Ya te encuentras en este lugar.",
	L"Este lugar ya está lleno y no puedes acceder a él.",
	L"No puedes acceder a este lugar, ya que varios grupos ya están dentro.",
	L"Error al entrar en este lugar.",
	L"Los datos del lugar al que quieres acceder son erróneos.",
	L"Ha ocurrido un error al intentar acceder a este lugar.",
	L"No se ha podido encontrar la información del usuario en el lugar en cuestión.",
	L"Se ha abortado la entrada en un escenario mediante la agrupación automática de grupos.",
	L"Se ha abortado el inicio de la partida en el escenario.",
	L"No puedes solicitar una agrupación automática de grupos en este momento.",
	L"No puedes llevar a cabo una agrupación automática de grupos en este momento. Por favor, espera un rato.",
	L"Ya se ha solicitado una agrupación automática de grupos.",
	L"Se ha abortado la agrupación automática del grupo debido a datos erróneos.",
	L"Se ha cancelado la entrada como candidato para una agrupación automática de grupos.",
	L"No tienes permiso para solicitar una agrupación automática de grupos.",
	L"La partida no puede empezar porque solamente hay un miembro del grupo disponible.",
	L"Uno de los miembros del grupo se ha retirado.",
	L"El tiempo de espera para iniciar la partida en grupo ha finalizado y la partida no tendrá lugar.",
	L"Ya perteneces al grupo.",
	L"La persona invitada ya aguarda su admisión en otro grupo.",
	L"En estos momentos no eres miembro del grupo.",
	L"Los Medicamentos milagrosos y las Pociones secretas se solapan, por lo que no se pueden utilizar.",
	L"ServerSN이 중복 접속 중이다.",
	L"ServerSN 존재하지 않는데 삭제하려한다.",
	L"Esta función no se puede utilizar en este momento.",
	L"넥슨 통합 맵버쉽 계정 인증 상향 조정 필요.",
	L"Tu cuerpo ya ha alcanzado su límite. No puedes utilizar la poción secreta.",
	L"No cumples los requisitos de nivel. La partida no puede empezar.",
	L"[US] 추천받을 대상이 아닙니다.",
	L"[US] 추천인이 이미 3인을 추천하였습니다.",
	L"[US] 추천 가능한 유저가 아닙니다.",
	L"[US] 맞지 않는 아이템을 사용하였습니다.",
	L"No se ha podido ampliar la casilla de personaje. Solo se permite un máximo de 8 casillas de personaje.",
	L"Ha concluido la agrupación automática de grupos porque la partida ha dado comienzo.",
	L"Alguien seleccionado por la agrupación automática de grupos no ha aprobado el inicio de la partida.",
	L"Se ha interrumpido la agrupación automática de grupos.",
	L"Un miembro del grupo no ha aprobado el inicio de la partida en la agrupación automática de grupos. Se ha interrumpido la agrupación automática de grupos.",
	L"La agrupación automática de grupos ha tenido éxito. Se ha eliminado tu nombre de la lista de espera.",
	L"Se ha retirado la solicitud de agrupación automática de grupos. Tu nombre ya no figura en la lista de espera.",
	L"Se ha retirado la solicitud de agrupación automática de grupos debido a la salida de uno de los miembros.",
	L"No se ha alcanzado el nivel de objeto necesario. No puedes iniciar el escenario.",
	L"No se ha podido guardar la configuración de teclado.",
	L"No se ha podido guardar ninguna configuración de teclado.",
	L"No se ha podido leer la configuración de teclado.",
	L"No se han podido leer los datos sobre la configuración de teclado.",
	L"Tu respuesta al inicio de la partida grupal en el escenario se está demorando.",
	L"[US] 추천인 테이블에서 캐릭터 삭제를 실패하였습니다.",
	L"[US] 보안패드 리셋용 질문 및 답변을 입력하지 않았습니다.",
	L"El jugador no pertenece al mismo grupo.",
	L"No se han podido guardar los datos sobre la selección de chat.",
	L"No se han podido leer los datos sobre la selección de chat.",
	L"No se han podido leer algunos datos sobre la selección de chat.",
	L"Test",
	L"셧다운제에 의하여 게임이용이 차단 됩니다.",
	L"선택적 셧다운제의 의해 게임이용이 차단됩니다.",
	L"통합 맴버십 ATL 2.0 유저가 아니므로 게임이용이 차단 됩니다.",
	L"셧다운제에 의하여 게임이용이 차단 됩니다.",
	L"선택적 셧다운제의 의해 게임이용이 차단됩니다.",
	L"통합 맴버십 ATL 2.0 유저가 아니므로 게임이용이 차단 됩니다.",
	L"No puede tener lugar una apertura por el momento.",
	L"Ha concluido el tiempo de apertura.",
	L"ServiceID가 잘못 되었습니다.",
	L"캐시 잔액 정보를 찾을 수 없습니다.",
	L"[TW]ServiceCode 가 올바르지 않습니다.",
	L"[TW]정의되지 않은 애러 발생했습니다.",
	L"[TW]시간형식이 잘못되었습니다.",
	L"[TW]Type정보가 잘못되었습니다.",
	L"[TW]이전 상품 구매가 진행 중입니다.",
	L"Tu nivel es demasiado algo para esta misión.",
	L"파라매터 갯수 입력이 잘못되었습니다.",
	L"[JP] 합성제가 없습니다.",
	L"[JP] 없는 아바타를 합성하려고 했습니다.",
	L"[US]월 선물 가능 횟수를 초과하였습니다.",
	L"Solamente se puede jugar este escenario en solitario.",
	L"El escenario todavía no está abierto.",
	L"El personaje no se ha seleccionado correctamente.",
	L"El personaje no puede enviarse mensajes privados a sí mismo.",
	L"Se ha producido un error en la información de la mascota.",
	L"Solo puedes emplearse cuando hayas llamado a la mascota.",
	L"Es de uso exclusivo para mascotas adolescentes.",
	L"Es de uso exclusivo para mascotas niñas.",
	L"Hay un error en la configuración de la cantidad de relevos.",
	L"El juego no puede comentar hasta que haya al menos dos miembros en el equipo.",
	L"",
	L"",
	L"",
	L"",
	L"Has abandonado el escenario.",
	L"Has abandonado la competición.",
	L"Un cambio de canal ha motivado el abandono.",
	L"La salida se produce a consecuencia de la visita de los mismos miembros del grupo.",
	L"La salida se produce como consecuencia del uso de un objeto de transporte.",
	L"Salida debida a un cierre irregular.",
	L"Mientras juegas en un escenario no puedes invitar a nuevos miembros al grupo.",
	L"No es posible realizar la invitación ya que el jugador pertenece ya a otro grupo.",
	L"La persona participa en un combate y por tanto no puede ser invitada.",
	L"La persona se encuentra en un escenario y no puede ser invitada.",
	L"No ha sido posible encontrar al jugador en este servidor.",
	L"No es posible invitar a más miembros a este grupo.",
	L"Durante una competición no es posible invitar a miembros del grupo.",
	L"Tu nivel es demasiado bajo para acceder a este campo.",
	L"No has completado los escenarios necesarios para acceder a este campo.",
	L"Pueden realizarse un máximo de 30 misiones.",
	L"No tienes suficientes ED.",
	L"No es posible invitar a un jugador que use la creación automática de grupos.",
	L"Si está activada la formación automática de grupos no puedes invitar a nadie a tu grupo.",
	L"En la sala JcJ no puedes invitar a ningún miembro del grupo.",
	L"Durante el entrenamiento no puedes invitar a ningún miembro del grupo.",
	L"Mientras estás en la lista de espera de JcJ no puedes invitar a ningún miembro del grupo.",
	L"Mientras estés apuntado a la formación automática de grupos no funcionarán las invitaciones manuales al grupo.",
	L"Si te has inscrito en una lista de espera de JcJ no puedes invitar a ningún miembro del grupo.",
	L"Tu grupo se encuentra en el mismo campo que tú.",
	L"No es posible invitar a esta persona porque es candidata a entrar en otro grupo.",
	L"",
	L"",
	L"Este apodo no existe.",
	L"La identificación del grupo en el servidor es incorrecta.",
	L"",
	L"Quienes no disponen de permiso para participar en las competiciones online no pueden acceder al canal JcJ.",
	L"Para abrir el cubo necesitas objetos y ED.",
	L"Te faltan ED para poder abrir el cubo.",
	L"Se empezará con el número actual de participantes.",
	L"",
	L"",
	L"",
	L"El evento ha concluido.",
	L"No puedes traer estos objetos con Ara.",
	L"",
	L"Lamentablemente se ha alcanzado el número máximo de trueques.\nTras la actualización del 17/01 se autorizarán trueques adicionales.",
	L"",
	L"Esta mascota no existe.",
	L"Ya se ha utilizado esta función.",
	L"Puede utilizarse a partir del nivel \"Niño\".",
	L"Mientras esperas a que empiece una partida no puedes cambiar tus casillas de habilidades.",
	L"No ha sido posible cargar las informaciones sobre los monstruos del campo porque en este momento no te encuentras en la habitación.",
	L"No ha sido posible cargar las informaciones sobre los monstruos del campo porque en este momento no te encuentras en la habitación.",
	L"No ha sido posible adquirir el objeto necesario para ampliar el número de casillas. La ampliación de casillas solo es posible hasta que se alcanza la cifra de 30.",
	L"La exclusión del escenario se produce como resultado de la votación de exclusión.",
	L"El votante no es un jugador real.",
	L"La persona sobre la que se vota no es un jugador real.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"No tienes suficientes ED para registrar una invitación.",
	L"No puedes inscribirte en este gremio porque ha alcanzado el número máximo de integrantes.",
	L"No ha podido enviarse la solicitud de invitación.",
	L"No ha podido registrarse la búsqueda de gremios.",
	L"Ya existe un mensaje de invitación al gremio.",
	L"Ya se ha registrado una búsqueda de gremios.",
	L"No ha podido registrarse el mensaje de invitación al gremio.",
	L"No tienes suficientes ED para registrar la búsqueda de gremios.",
	L"No hay invitaciones de gremios.",
	L"No hay búsqueda de gremios disponible.",
	L"Este gremio no existe.",
	L"No tienes permiso para ver la lista de usuarios invitados.",
	L"Se ha alcanzado el número máximo de accesos al escenario.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"No posees las Instrucciones sobre los campos.",
	L"No se ha podido añadir el capítulo.",
	L"Ya se ha añadido este capítulo.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Error al calcular el tiempo VIP.",
	L"",
	L"",
	L"",
	L"",
	L"El nivel del objeto no se corresponde con el del Pergamino de espacio-tiempo bendito.",
	L"Este objeto ya está identificado.",
	L"No hay objetos en tu inventario.",
	L"No tienes suficientes ED para permitirte la identificación.",
	L"Ha ocurrido un error al identificar.",
	L"No hay suficientes Pergaminos de espacio-tiempo benditos.",
	L"Este objeto no se puede identificar.",
	L"",
	L"",
	L"Este objeto no se puede cambiar.",
	L"No posees suficientes ED para cubrir las tasas de cambio.",
	L"",
	L"",
	L"",
	L"",
	L"Ya no tienes más objetos que puedas cambiar.",
	L"Ha ocurrido un error al cambiar el objeto.",
	L"",
	L"",
	L"No se pueden cambiar objetos o materiales temporalmente limitados.",
	L"No se pueden cambiar objetos o materiales temporalmente limitados.",
	L"No se cumplen los requisitos.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"No se puede comprar con una cuenta bloqueada.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Se ha cerrado el programa debido a un fallo del archivo CheckKom.xml.",
	L"",
	L"Información de nivel errónea.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Por lo menos una de las condiciones no se cumple. ¡Comprueba que has invocado a tu mascota!",
	L"Por lo menos una de las condiciones no se cumple. ¡Comprueba que puedes utilizar a tu mascota!",
	L"¡Has utilizado la Poción de transformación del hada calabaza de Halloween!",
	L"Por lo menos una de las condiciones no se cumple. ¡Comprueba que la intimidad de tu mascota está al 100%!",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Se ha alcanzado el número máximo de partidas en el escenario.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Se ha cerrado el programa debido a la modificación de un archivo.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",

	L""
};
