#pragma once

//FR버전 출력
static wchar_t* szErrorStrFR[] = {
	L"Réussite",
	L"Erreur inconnue",
	L"Une erreur concernant le statut du joueur est survenue.",
	L"Cette version est incorrecte. Connecte-toi à nouveau.",
	L"Serveur complet. Le nombre maximal de joueurs est atteint.",
	L"Le serveur de jeu est est cours d'analyse. Connecte-toi après la fin de cette analyse.",
	L"Tu as essayé de te connecter 2 fois sur le même serveur.",
	L"Tu as essayé de te connecter à plusieurs canaux à la fois.",
	L"La vérification de l'IP du serveur a échoué.",
	L"Le serveur UID a planté.",
	L"L'utilisateur n'existe pas",
	L"Ce joueur n'existe plus",
	L"Données de connexion incorrectes.",
	L"Les paramètres du serveur sont incorrects.",
	L"Tes données d'identification n'ont pas pu être vérifiées.",
	L"Ton compte a été suspendu.\nContacte le support Elsword à l'adresse suivante : http://support.elsword.fr",
	L"Cette demande ne peut être faite que par un opérateur.",
	L"Aucune ID de proxy disponible.",
	L"Cette adresse IP n'est pas autorisée.",
	L"Les ID relatives au canal n'existent pas sur le serveur de jeu.",
	L"La longueur de l'identifiant est incorrecte.",
	L"Erreur lors de la transaction.",
	L"La longueur de l'identifiant est incorrecte.",
	L"Longueur du mot de passe incorrect.",
	L"Longueur du nom d'utilisateur incorrecte.",
	L"Le joueur effacé a tenté de créer un personnage.",
	L"Ce nom de personnage est déjà utilisé.",
	L"Erreur lors de la transaction.",
	L"Une erreur est survenue lors du chargement des données du personnage.",
	L"La longueur du nom de personnage est incorrecte.",
	L"Tu ne peux plus créer d'autres personnages.",
	L"Ce pseudo ne peut pas être utilisé pour l'instant !",
	L"La base de donnée n'a pas pu générer de SN de ce personnage pour la messagerie.",
	L"Ce pseudo ne peut pas être utilisé.",
	L"Tu ne peux créer que quatre personnages par jour.",
	L"Le personnage sélectionné ne se trouve pas sur le serveur de jeu.",
	L"La classe sélectionnée est incorrecte.",
	L"Les informations sur la pierre de résurrection n'ont pas pu être consultées.",
	L"La base de donnée n'a pas pu transmettre le SN du personnage à la messagerie.",
	L"Une erreur est survenue dans la base de données lors de la sélection du personnage.",
	L"Le pseudo doit être modifié.",
	L"Aucun canal JCJ correspondant à ton niveau n'a été trouvé.",
	L"Le joueur à effacer n'est pas sur le canal.",
	L"Le changement de canal a échoué.",
	L"Pas assez de PJCJ pour entrer.",
	L"Tu n'as pas pu entrer sur le canal du village.",
	L"Tu n'as pas pu entrer sur le canal.",
	L"Il n'y a pas de défi en cours.",
	L"La liste de groupe ne peut pas être consultée.",
	L"Dans la zone de seuil des donjons, il est impossible de voir la liste des groupes.",
	L"Dans cette zone de seuil des donjons, la liste des groupes ne peut pas être ouverte.",
	L"JcJ seulement disponible à partir du niveau 3.",
	L"Impossible de créer des espaces supplémentaires sur le serveur.",
	L"Il n'y a pas d'utilisateur dans cette case.",
	L"La case dans laquelle le joueur sélectionné se trouve n'a pas pu être trouvé.",
	L"Il n'y a plus de places libres dans cet espace.",
	L"Données de connexion incorrectes.",
	L"Le donjon précédent n'a pas été terminé.",
	L"Erreur lors de la tentative de démarrage immédiat. Aucun espace libre.",
	L"Seul l'administrateur de cet espace peut faire cette démarche.",
	L"Le statut de l'espace n'autorise actuellement aucun paquet.",
	L"Ce joueur n'est pas encore prêt.",
	L"Le nombre de membres de l'équipe ne correspond pas.",
	L"Pour démarrer le jeu, il faut plus d'une personne avec le statut \"prêt\".",
	L"Le processus de chargement n'a pas pu être modifié.",
	L"L'espace a été créé.",
	L"Les informations concernant cet espace ont été modifiées.",
	L"L'espace a été effacé.",
	L"Aucun joueur n'a été trouvé dans cet espace.",
	L"Erreur lors de l'entrée",
	L"Tu n'as pas pu sortir de l'espace.",
	L"L'UID du PNJ mort est erronée.",
	L"Ce PNJ est déjà mort.",
	L"Données du monstre incorrectes. Le chargement a échoué.",
	L"Le joueur n'a pas pu être trouvé.",
	L"Type de dialogue incorrect.",
	L"Tu ne peux pas t'exclure toi-même d'un espace.",
	L"Pas assez de points d'action.",
	L"Ce type de jeu ne prend pas  en compte les statistiques étendues.",
	L"Le jeu est en cours de fermeture. Tu ne peux pas entrer dans cet espace.",
	L"Tu ne peux pas entrer dans cet espace.",
	L"L'espace dans lequel tu veux entrer ne contient pas d'informations.",
	L"Tu ne peux pas te préparer alors que tu es en train de faire du commerce.",
	L"Impossible d'entrer dans cet espace, car le jeu est en train de démarrer. Recommence plus tard.",
	L"Il n'y a plus d'objet de démarrage dans l’inventaire.",
	L"Un joueur n'en possédant pas les droits à essayé de créer un espace d'observation.",
	L"Les données de la carte JcJ sont erronées.",
	L"Seuls ceux qui ont une autorisation de participation hors-ligne pour le tournoi peuvent utiliser le canal du tournoi.",
	L"Tu n'as pas l'objet requis pour jouer le donjon sélectionné. Tu en seras expulsé après le démarrage du jeu.",
	L"La fonction inviter ne peut être utilisée que dans un espace JcJ.",
	L"Le joueur invité ne peut actuellement pas entrer dans l'espace JcJ.",
	L"Tu ne peux inviter que les joueurs se trouvant dans le lobby du canal JcJ.",
	L"Le jeu ne pourra démarrer que quand tu seras inscrit dans le groupe.",
	L"Réglage erroné du nombre de points.",
	L"L'objet n'existe plus.",
	L"Quelqu'un d'autre l'a déjà reçu.",
	L"Échec de l'attribution aléatoire de l'objet.",
	L"Aucune information sur l'objet disponible.",
	L"L'ID de l'objet est erronée.",
	L"L'objet n'a pas pu être donné.",
	L"L'objet n'a pas pu être réparé",
	L"L'objet dans la case raccourci n'a pas pu être utilisé",
	L"Les cases raccourci ne peuvent pas être utilisées dans le donjon-événement",
	L"Tu n'as pas pu acquérir l'objet",
	L"L'objet placé dans l'inventaire temporaire n'a pas pu être récupéré.",
	L"Pas assez de place dans l'inventaire temporaire.",
	L"Le message est trop long.",
	L"Impossible de changer d'équipe.",
	L"Les modifications n'ont pas pu être enregistrées.",
	L"Impossible de participer.",
	L"Impossible de fermer la case.",
	L"L'utilisateur n'a pas pu être exclu.",
	L"Les données de l'adversaire n'ont pas pu être sauvegardées.",
	L"Le statut n'a pas pu être modifié.",
	L"Le joueur a décidé de quitter",
	L"La connection a été interrompue.",
	L"Tu as été exclu.",
	L"Votre niveau est trop élevé pour ce canal.",
	L"L'échoppe a été fermée.",
	L"Impossible d'accéder à l'échoppe.",
	L"Temps écoulé. L'échoppe a été fermée.",
	L"L'échoppe a été refermée.",
	L"Le nombre de vendeurs particuliers est incorrect.",
	L"Une erreur est survenue lors de la vente.",
	L"Soit tu n'as pas assez de place dans ton inventaire, soit les données de l'objet sont incorrectes.",
	L"Tu n'as plus assez de points d'action.",
	L"La vente a été interrompue. Il n'y a aucun objet à vendre.",
	L"La vente a été interrompue.",
	L"L'échoppe a été fermée car aucun objet n'a été mis en vente.",
	L"La vente a été interrompue.",
	L"Tous les objets ont été vendus. Fermeture de l'échoppe.",
	L"La vente a été interrompue car tu as quitté les lieux.",
	L"L'échoppe a été fermée.",
	L"Le logiciel client a rencontré un problème.",
	L"Tu ne peux pas rester plus longtemps sur le canal de combat.",
	L"Si tu passes en mode JcJ, tu quittes le groupe.",
	L"Le groupe a été dissout car le donjon est terminé.",
	L"Tu as quitté le groupe pour participer au marché.",
	L"Tu es entré sur l'aire d'entraînement. Tu as quitté le groupe.",
	L"Terminé.",
	L"Le jeu a été interrompu en raison d'une suspicion de triche.",
	L"Le logiciel client a rencontré un problème. Interruption du jeu.",
	L"Impossible de modifier les EXP du personnage.",
	L"La base de données n'a pas pu affecter le personnage.",
	L"Le degré d'autorité est incorrect.",
	L"Ce joueur n'existe pas.",
	L"Erreur lors de la transaction.",
	L"Il n'y a aucun joueur avec ce degré d'autorité.",
	L"L'opérateur a interrompu la connexion.",
	L"Cette commande ne peut être exécutée qu'à la campagne.",
	L"Cette action ne peut être effectuée à cet endroit.",
	L"Cet objet ne peut pas être acheté.",
	L"Cet objet ne peut pas être vendu.",
	L"Cette quête est déjà en cours.",
	L"Tu as essayé d'effacer une quête qui n'est pas en cours.",
	L"Cette quête n'existe pas.",
	L"Cette quête a déjá été accomplie.",
	L"Ce personnage ne peut pas accomplir la quête.",
	L"La quête précédente n'a pas été terminée.",
	L"Un PNJ t'a donné une mauvaise quête.",
	L"Cette référence de quête n'existe pas.",
	L"La quête ne peut pas être terminée, car toutes les conditions ne sont pas remplies.",
	L"La base de données n'a pas pu modifier les données de la quête.",
	L"Tu ne peux accepter que 10 quêtes à la fois.",
	L"Ton niveau est trop bas pour accepter cette quête.",
	L"Tu n'as pas assez de place dans ton inventaire pour terminer cette quête.",
	L"Une erreur est survenue lors de l'attribution des récompenses de quête.",
	L"La récompense cherchée n'a pas pu être trouvée.",
	L"La quête de spécialisation est déjà en cours.",
	L"Une erreur est survenue lors de l'attribution des récompenses de la quête de spécialisation.",
	L"Le type de quête est incorrect.",
	L"L'intervalle temporel entre les messages de tchat est trop court.",
	L"Tu ne peux pas te chuchoter à toi-même.",
	L"Le dialogue est incorrect.",
	L"Cet utilisateur est hors-ligne.",
	L"--/;/guilemets/virgule/espace ne peuvent pas être utilisés.",
	L"Le temps de saisie est inférieur au temps de chargement de la liste actualisée des joueurs.",
	L"La recherche des données utilisateur est en cours.",
	L"Cet utilisateur est hors-ligne.",
	L"Ce pseudo n'existe pas.",
	L"Tu n'as pas pu entrer dans le village.",
	L"Tu n'as pas pu quitter le village.",
	L"Cette compétence est déjà au niveau maximum.",
	L"Cette compétence n'existe pas.",
	L"Ton niveau est trop bas pour apprendre cette compétence.",
	L"Tu n'as pas assez de points de compétence.",
	L"Tu n'as pas l'objet nécessaire.",
	L"Tu dois d'abord finir la quête.",
	L"Tu dois d'abord apprendre la compétence précédente.",
	L"Tu as déjà appris cette compétence.",
	L"L'ID de la case raccourci de compétence est erronée.",
	L"Tu ne peux entrer que des compétences que tu as déjà apprises.",
	L"L'annulation de la compétence a échoué.",
	L"La case de compétence B ne peut pas être utilisée.",
	L"Une erreur est survenue lors de l'extension de la case de compétence B.",
	L"Pour pouvoir être apprise, cette compétence doit d'abord être débloquée.",
	L"Tu n'as pas atteint le niveau requis pour cette compétence.",
	L"Tu n'as pas assez de points pour apprendre cette compétence.",
	L"Tu n'as pas assez de points pour apprendre cette compétence.",
	L"Tu as essayé de modifier une compétence qui n'existe pas.",
	L"Les informations concernant le niveau de compétence sont incorrectes.",
	L"Le niveau de compétence sélectionné n'est pas correct.",
	L"Les modifications concernant la validité des points de compétence pour échoppe n'ont pas pu être enregistrées.",
	L"L'assignation des points de compétences pour échoppe a échoué.",
	L"Les infos concernant les points de compétence pour échoppe n'ont pas pu être actualisées",
	L"La réinitialisation des infos concernant les compétences pour échoppe a échoué.",
	L"Les compétences standard ne peuvent pas être annulées.",
	L"Le groupe n'a pas pu être créé.",
	L"Tu n'as pas pu quitter le groupe.",
	L"L'information sur le groupe est incorrecte.",
	L"Tu ne peux pas inviter cet utilisateur.",
	L"Aucun groupe disponible.",
	L"Tu es déjà dans un groupe.",
	L"Tu ne peux pas créer de groupe en mode JCJ.",
	L"Tu ne peux pas rejoindre un groupe en mode JCJ.",
	L"Le groupe est complet.",
	L"Impossible de rejoindre le groupe.",
	L"Le groupe a été dissout.",
	L"L'adhésion au groupe a été refusée.",
	L"L'invitation a été refusée.",
	L"Tu ne peux pas commencer un donjon ici.",
	L"La modification du statut \"disponible\" a échoué.",
	L"Tu as choisi le mauvais donjon.",
	L"Le démarrage du jeu a échoué.",
	L"Type de jeu non valide.",
	L"Tu n'est pas chef de groupe.",
	L"Le chef de groupe n'a pas pu être modifié.",
	L"Les membres du groupe n'ont pas pu être modifiés.",
	L"Tu ne peux pas commencer ce donjon dans cette région.",
	L"Les options de vie privée n'ont pas pu être modifiées.",
	L"Le joueur choisi comme chef de groupe ne peut pas commencer ce donjon.",
	L"Le chef de groupe ne peut pas modifier le statut \"disponible\".",
	L"Aucun partenaire de dialogue disponible.",
	L"La liste de groupe demandée est incorrecte.",
	L"Le réglage concernant la limite de niveau n'a pas pu être modifié.",
	L"C'est un groupe privé.",
	L"Pas de pierre de résurrection disponible.",
	L"Tu as été ressuscité.",
	L"Échec de la résurrection.",
	L"La pierre de résurrection ne peut pas être utilisée dans ce donjon.",
	L"Impossible d'actualiser un statut qui n'existe pas.",
	L"Les options de communauté n'ont pas pu être affichées.",
	L"Tu ne peux plus ajouter de noms à la liste noire.",
	L"Ce joueur est déjà sur la liste noire.",
	L"Ce joueur a déjà été effacé de la liste noire.",
	L"Ce joueur n'existe pas.",
	L"N'a pas pu être effacé de la liste noire.",
	L"Tu ne peux pas te mettre toi-même sur la liste noire.",
	L"Tu ne peux pas te retirer de la liste noire.",
	L"Tu ne peux ajouter un joueur à la liste noire que s'il est connecté.",
	L"Ton propre personnage ne peut être ajouté.",
	L"Le temps imparti pour ajouter des amis est écoulé.",
	L"Personnage introuvable.",
	L"Avec ce statut, ton personnage ne peut inviter personne.",
	L"L'autre joueur ne peut pas être invité pour l'instant.",
	L"L'autre joueur ne peut pas participer pour l'instant.",
	L"Ne peut pas être ajouté comme ami.",
	L"L'échope n'a pas pu être ouverte.",
	L"Tu ne peux pas quitter la vente privée.",
	L"La recherche de joueurs en vente privée a échoué.",
	L"L'objet choisi est incorrect.",
	L"Le montant de PP est incorrect.",
	L"L'objet n'existe pas.",
	L"Pas assez de pièpièces !",
	L"Tu ne peux sélectionner que des objets de l'inventaire.",
	L"Pas assez de place dans l'inventaire.",
	L"Les objets liés au personnage ne peuvent pas être vendus.",
	L"Le dialogue de vente ne peut pas être ouvert ici.",
	L"Tu ne peux pas commercer avec toi-même.",
	L"Si l'objet est usé, il ne peut pas être vendu. Repare-le et réessaye.",
	L"L'objet est déjà enregistré.",
	L"Seuls les objets enregistrés peuvent être supprimés.",
	L"Tu peux sélectionner au maximum 10 objets différents.",
	L"Le montant de la vente est supérieur au budget de l'autre joueur. Réduis le prix en PP.",
	L"La demande de vente privée a été acceptée.",
	L"Une vente privée est déjà ouverte avec un autre joueur.",
	L"La demande de vente privée a été refusée.",
	L"Pas de vente possible.",
	L"En raison d'un problème du serveur, la vente est impossible.",
	L"Tu n'as pas l'objet nécessaire pour participer à ce donjon.",
	L"Tu n'es pas encore autorisé à entrer sur l'aire d'entraînement.",
	L"Le donjon devant servir d'aire d'entraînement n'a pas d'ID.",
	L"Une erreur est survenue lors de l'enregistrement de la récompense.",
	L"L'objet sélectionné n'est pas disponible dans l'inventaire.",
	L"L'objet sélectionné n'est pas le cube.",
	L"Ce personnage ne peut pas utiliser cet objet.",
	L"Tu n'as pas assez de clés pour ouvrir le cube.",
	L"Le cube ne peut pas être ouvert.",
	L"L'objet n'a pas pu être fabriqué.",
	L"Pas assez de place dans l'inventaire pour ouvrir le cube.",
	L"Nous avons détecté plusieurs connexions simultanées.",
	L"l'identifiant de ce joueur est incorrect.",
	L"L'ID de joueur est erronée.",
	L"L'UID du personnage est erronée.",
	L"Le pseudo du personnage est incorrect.",
	L"L'UID du serveur de jeu est erronée.",
	L"Les informations sur le joueur sont incorrectes.",
	L"Les informations sur le serveur sont incorrectes.",
	L"Erreur lors de la recherche d'UID",
	L"Le numéro du messagerie est erroné.",
	L"L'objet ne peut pas être fabriqué.",
	L"Ce n'est pas un parchemin.",
	L"Pas assez de pièpièces pour la fabrication !",
	L"Tu n'as pas assez de matériaux.",
	L"Pour la fabrication, tu dois avoir au moins une place libre dans ton inventaire.",
	L"L'objet n'a pas pu être fabriqué.",
	L"La certification du HackShield a échoué.",
	L"La mise à jour du HackShield nécessite un redémarrage du jeu.",
	L"La vérification du HackShield a échoué.",
	L"Soit le coupon a déjà été utilisé, soit son numéro n'est pas correct. Tu ne peux utiliser qu'un coupon par compte.",
	L"Entre le code à 30 caractères du coupon.",
	L"Ce coupon a déjà été utilisé.",
	L"Ce coupon n'est plus valable.",
	L"Ce numéro de coupon n'est pas valable.",
	L"Ce coupon ne peut être utilisé qu'une fois par compte.",
	L"Le coupon n'a pas pu être utilisé.",
	L"Tu n'as pas attendu assez de jours pour pouvoir le racheter.",
	L"Impossible de consulter la liste d'objets.",
	L"Les informations sur l'objet sont incorrectes.",
	L"Tu n'as pas assez de place dans ton inventaire.",
	L"L'objet acheté dans l'Elromarché n'a pas pu être sélectionné.",
	L"Le reste du solde n'a pas pu être consulté.",
	L"Les informations sur les membres n'ont pas pu être trouvées.",
	L"Ce compte a été suspendu.",
	L"Tu ne peux pas ajouter des objets d'autres personnages à ton inventaire.",
	L"Tu possèdes déjà cet objet.",
	L"Veuillez patienter, l'objet est en cours de chargement.",
	L"La taille moyenne de l'image visible (Frame) est incorrecte.",
	L"Ce joueur n'existe pas.",
	L"Ceci n'est pas l'objet permettant de changer de pseudo.",
	L"Ce pseudo est déjà pris.",
	L"Ce pseudo ne peut pas être utilisé pour l'instant !",
	L"Le pseudo n'a pas pu être actualisé.",
	L"Ce pseudo n'est pas autorisé.",
	L"La longueur du pseudo est incorrecte.",
	L"Le pseudo n'a pas pu être modifié.",
	L"L'échoppe n'a pas pu être ouverte.",
	L"L'échoppe ne peut être ouverte que sur le marché.",
	L"Impossible de voir cette échoppe. Aucune information sur son propriétaire n'est disponible.",
	L"L'échoppe est actuellement surchargée. Réessaye plus tard.",
	L"L'ouverture de l'échoppe a échoué.",
	L"La quantité d'objets que tu veux vendre ne correspond pas aux données.",
	L"L'objet a déjà été signalé comme vendu.",
	L"Impossible d'inscrire des objets dans des échoppes qui ne sont pas les tiennes.",
	L"Le nombre d'objets indiqué est supérieur au nombre d'objets qui peuvent être réellement vendus.",
	L"Tu n'as pas assez d'argent pour ouvrir une échoppe.",
	L"L'ouverture de l'échoppe n'est pas terminée.",
	L"Tu n'as pas encore quitté la boutique.",
	L"La quantité d'objets que tu as sélectionnés est supérieure à celle des objets en vente.",
	L"L'objet que tu veux acheter n'existe pas.",
	L"Tu n'as pas assez de pièpièces pour acheter cet objet.",
	L"Tu n'as pas assez de place dans ton inventaire pour acheter des objets.",
	L"Vente impossible, car le fabriquant n'a pas été trouvé.",
	L"Tu ne peux pas ouvrir d'échoppe pendant une vente.",
	L"L'échoppe est déjà ouverte.",
	L"Tu as dépassé ton montant maximum de PP.",
	L"Tu as atteint le montant maximum de PP que tu peux acheter.",
	L"Les informations sur l'objet à acheter sont incorrectes.",
	L"L'objet sélectionné n'est pas disponible dans l'inventaire.",
	L"Cet objet ne peut pas être démonté.",
	L"Le démontage de l'objet a échoué. Réessaye.",
	L"Tu ne peux démonter que ton équipement et tes accessoires.",
	L"Ne peut pas être démonté.",
	L"L'objet n'a pas pu être fabriqué.",
	L"Pas assez de place dans l'inventaire\npour démonter cet objet",
	L"Les objets à durée limitée ne peuvent pas être démontés.",
	L"L'objet que tu veux améliorer n'est pas dans ton inventaire.",
	L"Les données de l'objet n'existent pas.",
	L"Seules les armes et les pièces d'armure peuvent être améliorées.",
	L"Cet objet ne peut pas être amélioré.",
	L"Ne peut pas être amélioré",
	L"Pas de pierre d'amélioration disponible !",
	L"L'amélioration n'a pas pu être effectuée.",
	L"Tu n'as pas assez de PP pour l'amélioration.",
	L"Pour améliorer un objet, tu dois d'abord l'enlever ou le poser.",
	L"Pas de pierre fluorique dans l'inventaire.",
	L"Impossible d'utiliser la pierre fluorique.",
	L"À partir du niveau 10 d'amélioration, tu ne peux plus utiliser de pierre fluorique.",
	L"Tu ne peux pas améliorer les objets que tu ne peux pas utiliser.",
	L"Échec de l'amélioration.",
	L"L'objet que tu veux réparer n'est pas dans ton inventaire.",
	L"Les données de l'objet n'existent pas.",
	L"L'objet ne peut pas être réparé.",
	L"La réparation n'est possible que pour les objets que tu ne peux pas utiliser.",
	L"Pas assez de pierres de réparation disponibles.",
	L"Tu ne peux pas réparer les objets que tu portes.",
	L"Les objets dont la particularité est désactivée ne peuvent pas être utilisés.",
	L"Amélioration réussie.",
	L"Aucun changement.",
	L"L'objet a baissé d'un niveau.",
	L"Réinitialisation du niveau d'amélioration.",
	L"L'objet ne peut pas être utilisé.",
	L"L'objet n'est pas disponible dans l'inventaire.",
	L"Les données de l'objet n'existent pas.",
	L"Le prix est trop élevé.",
	L"Seules les armes et les pièces d'armures peuvent être serties.",
	L"Tu ne disposes d'aucune information sur la pierre d'anoblissement dans ton équipement.",
	L"Aucune pierre d'anoblissement dans l'inventaire.",
	L"Sertissage impossible.",
	L"La pierre d'anoblissement est déjà sertie.",
	L"La pierre d'anoblissement a déjà été retirée.",
	L"Cette option de sertissage n'existe pas.",
	L"Ce pseudo n'existe pas.",
	L"Tu ne peux pas te proposer toi-même.",
	L"Personne ne peut encaisser la récompense.",
	L"Les données à effacer ne sont pas dans la base de données.",
	L"La liste des apprentis n'a pas pu être ouverte.",
	L"Ces informations ne sont pas disponibles. Niveau trop faible.",
	L"Ton niveau n'est pas assez élevé pour avoir des apprentis.",
	L"Tu peux avoir 3 apprentis maximum.",
	L"Il a déjà un maître.",
	L"Déjà inscrit comme apprenti.",
	L"L'objet que tu désires acheter est incorrect.",
	L"Cet objet ne peut être acheté.",
	L"Le paiement a déjà été effectué.",
	L"Nombre maximum d'objets dépassé",
	L"Tu as dépassé la quantité maximale d'objets qui peut être achetée.",
	L"Cet objet ne peut pas encore être racheté.",
	L"Pas de panier disponible.",
	L"L'utilisation du jeu est limitée",
	L"La quantité d'objet est limitée. L'objet n'a pas pu être acheté.",
	L"La quantité achetable est limitée.",
	L"Cet objet ne peut pas être acheté de nouveau pour l'instant.",
	L"Cet objet ne peut pas être offert.",
	L"La quantité achetable par commande est limitée.",
	L"L'autre joueur ne peut pas recevoir l'objet pour l'instant.",
	L"Ce joueur est bloqué.",
	L"Aucune information trouvée sur le joueur.",
	L"Avoirs insuffisants",
	L"Vérification du système.",
	L"Nombre maximal de pierres de résurrection atteint.",
	L"Tu ne peux plus avoir de cases d'inventaire supplémentaires.",
	L"Tu ne peux pas te faire de cadeaux.",
	L"Données de connexion sont incorrectes.",
	L"Le pseudo n'existe pas.",
	L"Impossible d'offrir quelque chose à un joueur ayant une ID d'essai.",
	L"La quantité maximale d'objets pouvant être offerts a été dépassée",
	L"Entre le mot de passe.",
	L"La vérification du compte a échoué.",
	L"Cet objet ne peut pas être offert.",
	L"Les joueurs de moins de 14 ans ne peuvent pas utiliser cette fonction.",
	L"L'objet ne peut pas être acheté.\nTu peux avoir au maximum 9 cases de personnage.",
	L"L'obtention de cases d'inventaire supplémentaires n'a pas fonctionné.",
	L"Cette fonction est déjà utilisée.",
	L"Cette compétence n'existe pas.",
	L"L'objet pour réinitialiser une compétence n'existe pas.",
	L"L'objet de réinitialisation des compétences n'a pas pu être effacé de la base de données.",
	L"Une erreur s'est produite dans la base de données lors de la réinitialisation de la compétence.",
	L"Cette compétence ne peut pas être réinitialisée.",
	L"Une compétence ne peut pas être réinitialisée tant qu'elle se trouve dans une case raccourci.",
	L"Cet objet ne peut pas être ajouté à la liste d'envies.",
	L"Impossible d'ajouter plus d'objets au panier.",
	L"En tant que testeur, tu ne peux pas utiliser cette fonction.",
	L"Les joueurs ayant une ID d'essai ne peuvent pas utiliser la fonction \"conseiller\".",
	L"Tu as atteint le niveau maximal pour un joueur ayant une ID de test. Pour pouvoir continuer à jouer, inscrit toi avec une ID standard.",
	L"Les joueurs ayant une ID de test ne peuvent pas être ajoutés sur la liste d'amis.",
	L"Cette utilisateur n'est pas dans la liste des tricheurs.",
	L"La base de données n'a pas encore mis à jour les données concernant les conditions d'utilisation concernant les programmes de triche.",
	L"Tu n'as pas encore accepté la clause de signalement des tricheurs.",
	L"Cet objet n'est pas dans l'inventaire.",
	L"Ces caractéristiques ne peuvent pas être améliorées.",
	L"Les caractéristiques de cette case ont déjà été améliorées.",
	L"Cette case a déjà été vidée.",
	L"Tu ne possèdes pas assez de PP pour l'enchantement !",
	L"Pas assez de fragments d'Eldrit pour un enchantement.",
	L"Informations sur l'objet incorrectes.",
	L"L'enchantement n'est possible que sur les armes et armures.",
	L"L'objet sélectionné ne peut pas être démonté.",
	L"Pas assez d'appareils d'analyse disponibles !",
	L"Pas assez de place dans l'inventaire \npour démonter l'objet.",
	L"L'objet sélectionné ne peut pas être démonté.",
	L"La fabrication de l'objet a échoué.",
	L"Impossible de consulter la boîte de réception.",
	L"L'objet sélectionné ne peut pas être joint au message.",
	L"Le montant indiqué de PP ne peut pas être envoyé par message.",
	L"Le message n'a pas pu être envoyé.",
	L"Le message n'existe pas.",
	L"Pas assez de place dans l'inventaire pour y ajouter l'objet reçu. Fais de la place et réessaye.",
	L"L'objet joint n'a pas pu être récupéré.",
	L"Tu as essayé d'ajouter un objet qui n'existe pas.",
	L"Tu ne peux ajouter un objet que s'il est réparé complétement.",
	L"Ce pseudo n'existe pas.",
	L"Tu ne peux pas t'envoyer de message !",
	L"Pas assez d'EF pour envoyer le message.",
	L"L'autre joueur n'a plus de place dans sa boîte de réception et ne peut plus recevoir de message.",
	L"Tu as sélectionné un message effacé.",
	L"Le joueur a refusé votre message.",
	L"Les objets liés à un joueur ne peuvent pas être envoyés dans un message",
	L"Impossible d'envoyer un message à un joueur ayant une ID de test.",
	L"Le pseudo n'existe pas.",
	L"Ce pseudo est déjà sur la liste noire.",
	L"Échec de l'inscription sur la liste noire.",
	L"Le pseudo a déjà été effacé.",
	L"Le joueur n'a pas pu être effacé de la liste noire.",
	L"Tu ne possèdes pas ce titre",
	L"Tu portes déjà ce titre.",
	L"Ce titre n'est plus valide.",
	L"Ce titre n'existe pas.",
	L"Ce titre n'a pas été obtenu.",
	L"Tu possèdes déjà ce titre.",
	L"Cet objet ne peut pas être utilisé.",
	L"Cet objet n'existe pas.",
	L"Ton niveau est trop bas pour cet objet.",
	L"Cet objet ne peut pas être utilisé dans l'inventaire.",
	L"Cet objet n'est pas présent dans l'inventaire.",
	L"Cet objet n'est pas autorisé.",
	L"Cet objet n'est pas autorisé.",
	L"Échec de la mise à jour.",
	L"Cet objet ne peut pas être échangé.",
	L"Cet objet n'existe pas dans l'inventaire.",
	L"Tu ne peux pas vendre cet objet.",
	L"Les objets à échanger n'ont pas été créés.",
	L"Tu quittes ce lieu pour entrer dans un autre secteur.",
	L"Tu quittes le secteur pour entrer un espace.",
	L"Le système a pris en compte ton retrait.",
	L"Tu ne peux pas aller dans le village.",
	L"Tu n'as pas pu quitter le village.",
	L"La liste de joueurs ne peut pas être consultée.",
	L"Ton niveau est trop bas pour entrer dans ce village.",
	L"Tu n'as pas encore fini le donjon permettant d'accéder à ce village.",
	L"Ce canal n'existe pas.",
	L"Changement de canal réussi. Déconnexion en cours.",
	L"L'enregistrement de votre demande de changement de canal a échoué.",
	L"Tu n'es pas inscrit pour un changement de canal.",
	L"Tu te trouves déjà dans le canal que tu veux rejoindre.",
	L"Nombre maximal de participants atteint. Changement impossible.",
	L"La fonction de changement de canal ne peut être utilisée que dans un village ou aux alentours d'un village.",
	L"Réessaye plus tard de changer de canal.",
	L"Tu ne peux pas utiliser cette fonction sur un GM.",
	L"Aucun personnage sélectionné.",
	L"Cet ami n'est pas connecté.",
	L"Statut erroné.",
	L"La base de donnée n'a pas mis à jour les objets d'événement.",
	L"Tu as déjà reçu la récompense de l'événement.",
	L"Ce joueur est déjà ton ami.",
	L"Le statut du personnage de votre ami est invalide.",
	L"Ce joueur ne t'a pas ajouté comme ami.",
	L"Ce joueur n'est pas ton ami.",
	L"Ce groupe n'existe pas.",
	L"Message trop long.",
	L"Groupe identique au groupe que tu veux rejoindre.",
	L"Aucun groupe supplémentaire ne peut être créé.",
	L"Ce groupe existe déjà.",
	L"Ce nom de groupe est déjà en utilisation.",
	L"Votre apprenti ne s'est pas connecté depuis 7 jours. L'apprentissage est annulé.",
	L"Votre apprenti a passé un niveau. La formation est donc terminée.",
	L"Le personnage a été effacé. L'apprentissage est annulé.",
	L"L'apprentissage a été annulé.",
	L"Tu n'as pas pu terminer cet apprentissage.",
	L"Erreur dans la base de donnée concernant la fonction \"amis\".",
	L"Nom de groupe trop long.",
	L"Votre liste d'amis est complète. L'invitation n'a pas pu être envoyée.",
	L"Demandes d'amitié entre personnages d'un même compte impossibles.",
	L"La liste d'amis du joueur est complète. La demande d'amitié n'a pas pu être envoyée.",
	L"Votre demande en amitié a été rejetée.",
	L"Recherche échouée.",
	L"Impossible d'entrer sur le canal JcJ.",
	L"Un jeu en JcJ ne peut démarré qu'une fois toutes les places occupées.",
	L"Le sujet est trop long.",
	L"Le message est trop long.",
	L"Le joueur invité ne peut pas pénétrer dans le donjon.",
	L"Le sceau a déjà été retiré.",
	L"Le sceau de la compétence n'a pas pu être retiré",
	L"Tu n'es pas de la bonne classe pour utiliser cet objet !",
	L"Tu as déjà déverrouillé cette compétence !",
	L"Un objet avec les même fonctions se trouve déjà dans votre inventaire. Cet objet n'a pas pu être acheté.",
	L"Les joueurs ayant une ID de test ne peuvent pas être invités dans l'espace-temps de Henir.",
	L"Le moyen de certification est invalide.",
	L"Le objets placés dans la banque ne peuvent pas être démontés.",
	L"Tu ne peux pas sertir les objets conservés dans la banque.",
	L"Cette fonction ne peut pas être utilisée à la banque.",
	L"La quantité d'emplacements à la banque ne peut plus être augmentée.",
	L"Impossible d'acheter plus d'une carte de membre pour la banque.",
	L"La carte de membre de la banque n'a pas pu être achetée.",
	L"Si tu possèdes une garantie de créance de Luriel, tu peux acheter une carte de membre platine. Utilise donc maintenant la garantie de créance de Luriel.",
	L"Mot de passe inexistant.",
	L"Le mot de passe n'a pas pu être renouvelé.",
	L"Le mot de passe ou le nom d'utilisateur n'est pas correct.",
	L"Une erreur système est apparue pendant la phase d'authentification.",
	L"Cet objet n'existe pas.",
	L"Informations sur l'objet indisponibles.",
	L"Ce type d'objet ne peut pas être scellé.",
	L"Les objets portés ne peuvent pas être scellés.",
	L"Cet objet est déjà scellé.",
	L"Tu ne peux pas sceller un objet non réparé.",
	L"Les objets à durée limitée ne peuvent pas être scellés.",
	L"Les objets détruits ne peuvent pas être scellés.",
	L"Les objets que tu peux vendre ne peuvent pas être scellés.",
	L"Aucun sceau supplémentaire possible",
	L"Les informations du parchemin de sceau sont incorrectes.",
	L"L'action de sceller a échoué.",
	L"Pas assez de parchemins de sceau pour pouvoir sceller !",
	L"Les sceaux ne peuvent pas être retirés des objets que tu portes.",
	L"Le sceau de cet objet a déjà été enlevé.",
	L"Erreur lors de la levée des sceaux.",
	L"La mise à jour des données du sceau dans la base de donnée a échoué.",
	L"Les objets scellés ne peuvent pas être améliorés.",
	L"Erreur système lors de la demande de statut des ElFlouzes.",
	L"Ce compte a une marge d'activité réduite.",
	L"Ce compte n'existe pas.",
	L"Le compte est erroné.",
	L"Ce numéro de coupon n'est pas valable.",
	L"Ce coupon a déjà été utilisé.",
	L"Ce type de coupon ne peut être utilisé qu'une seule fois.",
	L"Ce coupon n'est plus valable.",
	L"Une erreur système s'est produite pendant l'utilisation du coupon.",
	L"Pas suffisamment d'Elflouzes.",
	L"Une erreur système s'est produite pendant l'achat.",
	L"L'achat n'est possible qu'à partir du niveau 15.",
	L"Tu es déjà membre d'une autre guilde.",
	L"Ce nom de guilde est déjà utilisé.",
	L"L'objet permettant de fonder une guilde ne se trouve pas dans l'inventaire.",
	L"L'objet de fondation de guilde est incorrect.",
	L"La fondation de guilde a échoué.",
	L"L'enregistrement en tant que maître de guilde a échoué.",
	L"Les infos de guilde n'ont pas pu être trouvées.",
	L"Invitation à la guilde impossible.",
	L"Le joueur est déconnecté.",
	L"Les joueurs ayant un ID de test ne peuvent pas être invités dans une guilde.",
	L"Ce joueur a déjà été invité dans la guilde.",
	L"Ce joueur a déjà été invité par une autre guilde.",
	L"Tu n'as pas les droits pour inviter quelqu'un dans la guilde.",
	L"Tu ne peux augmenter le nombre de membres de la guilde. Pour cela il te faut un objet.",
	L"Le joueur invité est déjà membre de la guilde.",
	L"Ce joueur est déjà inscrit dans une guilde.",
	L"Tu ne peux pas voir la liste de guilde.",
	L"L'objet devant être acheté avec le coupon est incorrect.",
	L"Le joueur a refusé l'invitation dans la guilde.",
	L"L'inscription a la guilde a échoué.",
	L"N'est pas membre d'une guilde.",
	L"Tu n'as pas les droits nécessaires pour changer le rang d'un membre de guilde.",
	L"Le rang du membre de guilde n'a pas pu être modifié.",
	L"Les messages de guilde ne peuvent être modifiés que par le maître de guilde et l'intendant de guilde.",
	L"Erreur lors de la modification du message de guilde.",
	L"Tu n'es pas autorisé à exclure un joueur de la guilde.",
	L"Le maître de guilde ne pas la quitter.",
	L"Erreur lors de sortie de guilde.",
	L"La limite de signe a été dépassée pour le message d'accueil de la guilde.",
	L"Tu n'es pas autorisé à modifier le message d'accueil de la guilde.",
	L"Erreur lors de la modification du message d'accueil de la guilde.",
	L"Seul le maître de guilde peut dissoudre la guilde.",
	L"La guilde ne peut être dissoute car elle a encore des membres.",
	L"Erreur lors de la dissolution de guilde.",
	L"Le rang de classe a déjà été modifié.",
	L"Il y a déjà des intendants de guilde.\nChange le rang d'un intendant pour \npouvoir en nommer un nouveau",
	L"Le maître de guilde ne peut pas effacer son personnage avant d'avoir donné son titre de maître à un autre membre de la guilde !",
	L"Tu ne peux pas changer ton rang de classe.",
	L"Tu ne peux pas acheter d'autorisation de création de guilde car tu fais déjà partie d'une guilde.",
	L"Tu possèdes déjà une autorisation de création de guilde.",
	L"Erreur lors de l'augmentation du nombre de membres.",
	L"La carte d'extension de guilde ne peut être utilisée que par le maître de guilde ou l'intendant.",
	L"Aucun membre supplémentaire ne peut être ajouté dans la guilde.",
	L"Cette fonction ne peut pas être utilisée pendant une vente.",
	L"Tu ne peux pas aller dans ce secteur.",
	L"Ce nom de guilde sera indisponible pour 7 jours.",
	L"Maximum de points d'expérience atteint.",
	L"Pour pouvoir acheter cet objet, il faut avoir terminé la quête correspondante.",
	L"Nom de guilde trop long.",
	L"Tu n'as pas assez de PP pour retirer cet attribut magique.",
	L"Tu ne peux acheter cet objet qu'à partir du niveau 35.",
	L"게임을 종료하고 빈펀 계정으로 업그레이드 하시기 바랍니다. 빈펀 사이트는 tw.beanfun.gamania.com 입니다.",
	L"이 계정은 이미 빈펀 계정으로 업그레이드 된 계정입니다. 빈펀 프로그램으로 접속해주세요.",
	L"Impossible d'acheter plus d'objets. Ton inventaire temporaire est plein.",
	L"Les PCG ne peuvent être utilisés que par le maître de guilde.",
	L"Cette compétence de guilde a déjà été augmentée au max.",
	L"Pas d'infos sur cette compétence de guilde disponible.",
	L"La compétence de guilde précédente n'a pas encore été augmentée au niveau max.",
	L"Pas assez de points de compétence engagés.",
	L"Pas assez de PCG.",
	L"L'apprentissage de la compétence de guilde a échoué.",
	L"Seul le maître de guilde peut réinitialiser les compétences de guilde.",
	L"Tu as besoin de l'objet \"Flûte en corne de l'oubli\" !",
	L"La compétence de guilde ne peut pas être réinitialisée.",
	L"Erreur lors du remboursement des compétences de guilde.",
	L"Seul le maître de guilde peut réinitialiser les compétences de guilde.",
	L"Tu n'as pas de \"flûte en corne de l'oubli\" dans ton inventaire.",
	L"Impossible de réinitialiser les compétences de guilde.",
	L"Erreur lors de la réinitialisation des compétences de guilde.",
	L"Utilisation réservée au maître de guilde.",
	L"Tu n'as obtenu aucun point de compétence de guilde temporaire.",
	L"L'objet béni de la connaissance est déjà en utilisation.",
	L"Il n'est pas encore possible de récupérer la récompense de l'événement.",
	L"Pas assez de place dans l'inventaire pour recevoir la récompense d'événement.",
	L"Erreur lors de la réception de la récompense d'événement.",
	L"Ce n'est pas le mode objet.",
	L"Un objet de butin n'a pas encore été ramassé.",
	L"Le butin du JcJ n'a pas pu être récupéré.",
	L"Après l'utilisation de la carte de personnage, tu pourras créer la classe.",
	L"Ce compte ne peut pas participer à l'événement.",
	L"Cette fonction ne peut être utilisée que par le maître ou un intendant de la guilde.",
	L"PC방 전용 아이템은 이용할 수 없는 기능입니다.",
	L"L'annonce de guilde n'existe pas.",
	L"Le texte est trop long.",
	L"La période d'enregistrement de la pub est invalide.",
	L"Pas assez de PP pour enregistrer l'annonce.",
	L"Une pub a déjà été enregistrée.",
	L"L'enregistrement de l'annonce de guilde n'a pas fonctionné.",
	L"Comme il y a trop de demandes, aucune inscription ne peut être effectuée pour l'instant.",
	L"L'inscription de la guilde a échoué.",
	L"Tu as déjà fait une demande d'enregistrement.",
	L"Les infos concernant la demande d'enregistrement n'existent pas.",
	L"L'enregistrement de la guilde n'a pas pu être accepté.",
	L"L'effacement de la demande d'enregistrement de la guilde n'a pas fonctionné.",
	L"Il est impossible de demander un enregistrement avec une pub à durée déterminée.",
	L"Tu n'a pas les droits nécessaires pour pouvoir afficher la liste des enregistrements de guilde.",
	L"Tu n'as pas ouvert le coffre.",
	L"Ce compte a été bloqué.",
	L"Les quêtes de la salle informatique ne peuvent être acceptées que dans le cybercafé.",
	L"Les quêtes de la salle informatique ne peuvent être terminées que dans le cybercafé.",
	L"Tu as été exclu de l'espace pour suspicion d'utilisation de programme de triche.",
	L"L'option \"Invitations de guilde bloquées\" est activée, t'empêchant d'enregistrer ta demande.",
	L"Comme il y a trop de demande d'enregistrement de guilde, tu ne peux pas en envoyer une supplémentaire.",
	L"Ce n'est pas la quête en cours.",
	L"La limite d'achat de l'objet concerné a été atteinte.",
	L"Elflouzes désactivées. Modifie tes réglages sur le site, sous \"Infos personnelles\" dans le menu\"Sécurité des transactions\"",
	L"La vérification de statut a déjà été faite.",
	L"La demande à la base de données concernant l'augmentation des points de web n'a pas abouti.",
	L"La vérification de statut n'a pas fonctionné.",
	L"En raison d'une inscription à plusieurs groupes, tu as dû quitter le groupe.",
	L"Chargement du statut de groupe.",
	L"Effacer la liste d'objets",
	L"Ajouter une liste d'objets",
	L"Modifier la liste d'objets",
	L"Le choix de la catégorie est erroné.",
	L"La recherche n'a pas été fructueuse.",
	L"Le joueur invité n'a pas assez de points d'action.",
	L"Recommence ta recherche plus tard.",
	L"Fin des ventes dans cette boutique.",
	L"Le joueur n'a pas activé le statut \"acheteur\"",
	L"La création d'un espace n'a pas fonctionné.",
	L"Cet objet n'existe pas.",
	L"Cette page n'existe pas.",
	L"Cette notice a déjà été enregistrée.",
	L"Cette notice n'a pas pu être enregistrée.",
	L"Tu ne possèdes pas le bloc-notes des techniques.",
	L"L'ajout de la note de technique a échoué.",
	L"Tu possèdes déjà cette note de technique.",
	L"Pour pouvoir acheter cet objet, tu dois avoir atteint le niveau 20.",
	L"Tu ne peux pas faire de commerce avec des joueurs d'autres serveurs.",
	L"Tu ne peux pas utiliser d'échoppes d'autres serveurs.",
	L"Tu ne peux pas inviter de joueurs d'autres serveurs dans la guilde.",
	L"Les joueurs d'autres serveurs ne peuvent pas être enregistrés comme apprentis.",
	L"Tu ne peux pas ajouter de joueurs d'autres serveurs à tes amis.",
	L"Le mode de défi de l'espace-temps de Henir ne peut pas être joué avec des personnages d'autres serveurs.",
	L"Accès bloqué pour les utilisateurs soupçonnés de piratage.",
	L"[홍콩] 해당 직업으로는 전직을 할 수 없습니다.",
	L"Le nombre d'objets que tu désires jeter est incorrect.",
	L"Échec de la création de bestiole.",
	L"Ce nom est déjà pris.",
	L"12 caractères maximum.",
	L"Création de la bestiole.",
	L"La bestiole n'a pas pu être appelée.",
	L"Impossible de créer une bestiole ici.",
	L"Tu as déjà appelé une bestiole.",
	L"Cette bestiole a déjà été appelée.",
	L"La bestiole n'a pas pu être renvoyée.",
	L"L'ordre n'a pas pu être exécuté.",
	L"Ta bestiole est rassasiée. Elle ne peut plus rien avaler.",
	L"La bestiole n'a pas pu être nourrie.",
	L"La bestiole est en phase de croissance. Elle ne mange plus que des fruits et des graines de l'arbre d'El.",
	L"Déjà sauvegardé.",
	L"Le prochain stade de développement n'est pas encore disponible.",
	L"Un développement n'est possible que quand la familiarité a atteint 100%.",
	L"La bestiole ne peut pas utiliser cet objet.",
	L"Le niveau de la nourriture est trop faible.",
	L"Données de connexion incorrectes.",
	L"Données de connexion incorrectes.",
	L"Ton compte n'a pas encore été validé.",
	L"La bestiole ne peut pas manger cette nourriture.",
	L"L'utilisateur est occupé.",
	L"매트릭스 카드가 바인딩되어 있습니다.",
	L"토큰 패스워드 에러",
	L"키 에러",
	L"계정 정보가 수정 과정에 있습니다. 의문 사항이 있으시면 서비스 센터로 연락 바랍니다.",
	L"자이언트 패스워드 보안이 바인딩 해제 상태에 있습니다. 의문사항이 있으시면 서비스 센터로 연락 바랍니다.",
	L"GM키에란",
	L"GM리엘",
	L"[Expéditeur inconnu]",
	L"지금은 청약철회 기능을 이용 하실 수 없습니다.",
	L"청약철회 가능 개수보다 요청 갯수가 커서 청약철회를 실패하였습니다.",
	L"구매한지 7일이 초과된 상품으로 청약철회가 불가능 합니다.",
	L"패키지 중 일부 상품을 수령하여 청약철회가 불가능 합니다.",
	L"상품 가격이 0원으로 청약철회가 불가능한 상품 입니다.",
	L"중복된 RequestID입니다.",
	L"Pas d'informations d'achat disponibles pour cet objet.",
	L"Pas d'informations disponibles pour cet objet.",
	L"청약철회가 불가능한 상품 입니다.",
	L"선물 받은 상품이어서 청약철회가 불가능 합니다.",
	L"Les objets à durée limitée ne peuvent pas être jetés.",
	L"Les objets ne pouvant pas être vendus ne peuvent pas être jetés.",
	L"1 EL coins 이벤트 구매 제한을 초과 하여 더 이상 구매 할 수 없습니다. ",
	L"Votre niveau est trop bas pour cet objet.",
	L"À partir du 11ème niveau d'amélioration, il n'est plus possible d'utiliser des pierres fluoriques.",
	L"Tu ne peux pas accepter cette quête car tu en as déjà reçu la récompense.",
	L"Tu ne peux pas accepter cette quête car tu n'as pas assez de place dans ton inventaire pour la récompense.",
	L"L'utilisation de la pierre d'anoblissement a échoué.",
	L"Cette fonction est actuellement indisponible.\nNous nous en excusons.",
	L"L'accès est limité pour cette IP.",
	L"La fonction de tchat a été limitée.",
	L"La fonction de vente a été limitée.",
	L"Le jeu ne peut pas être démarré car l'objet n'existe pas.",
	L"Le jeu est gêné par l’exécution d'autre programme en parallèle.",
	L"해당 유저가 존재하지 않습니다.",
	L"잔액이 부족합니다.",
	L"존재하지 않는 아이템 카드입니다.",
	L"해당 카드는 해당 구역에서 사용이 불가능합니다.",
	L"이미 사용한 아이템 카드입니다.",
	L"잘못된 전용 카드 ID입니다.",
	L"잘못된 전용 카드 패스워드입니다.",
	L"DB 에러",
	L"Tu ne peux pas envoyer de messages car tes actions ont été limitées.",
	L"Tu ne peux pas ouvrir d'échoppe car le commerce a été limité.",
	L"Tu ne peux pas consulter ton échoppe car le commerce a été limité.",
	L"Tu ne peux pas rechercher de marchandises car le commerce a été limité.",
	L"Tu ne peux pas entrer dans le marché car le commerce a été limité.",
	L"캐시 인벤토리에 아이템이 존재합니다.(HK 이벤트에 사용)",
	L"Plus de deux membres de groupe requis.",
	L"Le donjon est fermé, tu ne peux pas y entrer.",
	L"Le donjon mondial ne peut pas être joué avec d'autres joueurs de ce serveur.",
	L"L'historique du courrier coûte exactement autant.",
	L"L'historique des ventes coûte exactement autant.",
	L"L'historique du courrier a échoué.",
	L"L'historique des ventes a échoué.",
	L"Tu ne peux pas désactiver l'agente car des ventes sont encore en cours.",
	L"L'agente n'est pas activée.",
	L"Tu ne peux pas interrompre la vente.",
	L"Ceci est une vente privée : impossible d'acheter des objets.",
	L"Tu ne peux pas ouvrir d'échoppe car l'agente est encore active.",
	L"Tu as commis une infraction aux règles, ton échoppe va être fermée.",
	L"Tu ne peux pas désactiver l'agente.",
	L"Unregisted User.",
	L"It is already canceled.",
	L"Invalid coupon number.",
	L"This coupon can not be canceled.",
	L"The used user information and cancel the requested user information does not match.",
	L"The issued cash by coupons  already had used . so can not be canceled.",
	L"requested price should be equal to billing items price.",
	L"The balance short.",
	L"Billing account that is unavailable.",
	L"You can not register any more today.",
	L"This coupon can not verify the information.",
	L"Coupon is already used.",
	L"Coupon use is stopped.",
	L"Coupon is expired.",
	L"Coupon is not available in the game.",
	L"Issued to certain customers who can use coupons, you do not have permission.",
	L"Buying is a restricted user.",
	L"Your use is limited to the payment service.",
	L"Your use is limited to the purchase service.",
	L"User cannot be verified.",
	L"Registration has exceeded the number of coupons available.",
	L"Unable to login due to IP restriction.",
	L"The coupon code has already been redeemed.",
	L"You cannot purchase the item at the moment. Your account have reached the daily limit for purchasing the item.",
	L"Tu as entré deux fois de suite un mot de passe erroné, c'est pourquoi tu ne peux plus te connecter.",
	L"Si tu veux que l'agente vende des marchandises pour toi, il te faut passer un contrat.",
	L"Les CODES indiqués ne sont pas identiques.",
	L"Tu as saisi 10 fois un CODE erroné.\nSi tu cliques sur \"confirmer\", la connexion sera interrompue.\nTu dois te connecter au site afin de pouvoir réinitialiser la saisie.",
	L"Échec de la création du CODE.",
	L"Le CODE est incorrect.",
	L"Le nom de l'objet est trop long.",
	L"L'échoppe de l'agente a été fermée.\nAprès avoir reçu tes marchandises, tu pourras ouvrir une nouvelle échoppe.",
	L"L'agente est en train de vendre des marchandises.\nSi tu veux récupérer l'argent des ventes,\ntu dois fermer l'échoppe de l'agente.",
	L"Échec du DB-Query pour le contrat de l'agente.",
	L"L'agente n'a pas pu être activée.",
	L"Les marchandises n'ont pas pu être transférées dans l'échoppe de l'agente.",
	L"Seul le commanditaire de l'agente peut l'utiliser.",
	L"Les objets n'ont pas pu être confiés à l'agente.",
	L"Cet objet est en train d'être vendu, tu ne peux pas le récupérer.",
	L"Tu as déjà obtenu cet objet.",
	L"Tu as atteint le maximum de PP autorisé et ne peux pas en avoir plus.",
	L"Tu n'as plus de place dans ton inventaire",
	L"Tu n'as pas d'objets.",
	L"Tu ne peux pas acheter un objet identique à celui que tu vends.",
	L"Ton niveau est trop faible.\nTu ne peux pas envoyer de demande de groupe.",
	L"Tu ne peux pas acheter de marchandises car l'agente est encore active.",
	L"Il y a encore des objets que tu dois récupérer avant de pouvoir en vendre d'autres.",
	L"Toutes les marchandises ayant été vendues, l'agente ferme l'échoppe.",
	L"Tu as déjà accepté cette quête et obtenu la récompense. Tu ne peux pas l'accepter de nouveau.",
	L"Tu ne peux pas accepter cette quête car tu n'as pas assez de place dans ton inventaire.",
	L"Le niveau minimal du groupe n'a pas pu être modifié.",
	L"Tu ne peux pas ouvrir d'échoppe, car l'agente a vendu toutes les marchandises.",
	L"(TW/HK)강화 보조 아이템 사용 불가",
	L"(TW/HK)강화 보조 아이템이 없습니다.",
	L"(TW/HK)파괴 방지 아이템 사용 불가",
	L"(TW/HK)파괴 방지 아이템이 없습니다.",
	L"Ton niveau est trop faible.\nChoisis un autre donjon ou désactive la limitation de niveau.",
	L"Ton niveau est trop faible.\nTu ne peux pas définir de limitation de niveau.",
	L"Le niveau du joueur invité est trop faible.",
	L"Ton niveau est trop faible.\nChoisis un donjon qui corresponde à ton niveau.",
	L"Aucun chiffre du code ne doit se répéter directement.\n(0000, 1111, 999999, etc.)",
	L"Merci de ne pas utiliser de chiffres consécutifs dans le CODE.\n(1234, 9876, 123456, etc.)",
	L"L'effacement du deuxième pavé numérique a échoué.",
	L"Le 2e pavé numérique n'est pas utilisé.",
	L"Le nouveau CODE doit être différent de l'ancien.",
	L"Cet objet n'est pas vendu dans l'échoppe.",
	L"La recherche a été interrompue suite au commencement du JcJ.",
	L"Un joueur ne peut pas participer à la recherche d'adversaires.",
	L"La recherche d'adversaires a été interrompue.",
	L"Le membre du groupe n'ayant pas participé au JcJ, la recherche d'adversaires a été interrompue.",
	L"La recherche est terminée. Tu as été retiré de la liste d'attente.",
	L"Un utilisateur a annulé la recherche et a été retiré de la liste d'attente.",
	L"Un membre du groupe a quitté celui-ci, c'est pourquoi l’inscription a été annulée.",
	L"La recherche est déjà en cours.",
	L"Les informations sur le membre du groupe sont erronées.",
	L"Les informations sur le mode JcJ sont erronées.",
	L"Le JcJ n'est accessible qu'à partir du niveau 10.",
	L"Tu ne peux rejoindre un groupe JcJ qu'à partir du niveau 10.",
	L"Tu as déjà modifié le mode JcJ.",
	L"Tu ne peux pas rejoindre un groupe JcJ avec 4 membres de donjon.",
	L"Le mode JcJ ne peut pas être modifié.",
	L"Tu ne peux pas changer d'espace JcJ, car un membre du groupe n'a pas atteint le niveau 10.",
	L"Un membre du groupe n'a pas atteint le niveau 10 et ne peut donc pas pénétrer l'espace JcJ.",
	L"Seuls les joueurs de niveau 10 ou plus peuvent être invités dans un groupe JcJ.",
	L"Seuls les joueurs de niveau 10 ou plus peuvent créer un groupe JcJ.",
	L"[CN]전환이 정상적으로 이루어지지 않았습니다. 다시 시도하여 주시기 바랍니다.",
	L"Impossible de classer les objets. Réessaye plus tard.",
	L"Tu ne t'es pas inscrit à la recherche d'adversaires.",
	L"Tu es déjà dans un espace JcJ.",
	L"Ce n'est pas l'espace JcJ.",
	L"Échec de la demande.",
	L"Tu ne peux pas inviter un utilisateur déjà inscrit à la recherche d'adversaires.",
	L"Tu ne peux pas inviter un utilisateur en train de chercher un adversaire.",
	L"Ton rang n'est pas assez élevé pour acheter cet objet.",
	L"Tu ne peux pas rejoindre un autre groupe pendant la recherche d'adversaires.",
	L"Tu ne peut pas changer de groupe pendant la recherche d'adversaires.",
	L"Tu ne peux pas changer de canal pendant la recherche d'adversaires.",
	L"ID inconnu.",
	L"Cet ID est connecté sur plusieurs canaux simultanément.",
	L"Tu ne peux plus accepter de quêtes aléatoires aujourd'hui.",
	L"Je n'accepte pas les termes du contrat.",
	L"Erreur lors de l'affichage de PC.",
	L"Erreur lors de l'attribution des PC.",
	L"Le nom souhaité est invalide.",
	L"La vérification des données a échoué.",
	L"죄송합니다. 캐쉬샵 점검으로 인해 이용하실 수 없습니다.",
	L"00시부터 06시까지 게임 접속이 제한됩니다.",
	L"Aucune information disponible.",
	L"Tu ne peux pas commercer avant d'être enregistré comme aventurier.",
	L"Tu ne peux envoyer aucun message avant d'être enregistré comme aventurier.",
	L"[CN]사용실패!",
	L"Tu as quitté le champ de bataille.",
	L"N'est disponible qu'à partir du niveau 15.",
	L"ServerSN과 MachineID가 매칭되지 않는다.",
	L"MachineID와 ServerSN이 매칭되지 않는다.",
	L"DB에 존재 하지 않는 ServerSN이 있다.",
	L"DB에 존재 하지 않는 MachineID가 있다.",
	L"클라가 준 SN은 없는데 DB에는 MachineID에 해당하는 SN 존재.",
	L"제재된 SN입니다.",
	L"접속 제한된 ServerSN 입니다.",
	L"Tu ne peux pas te connecter au serveur test avec ce compte.",
	L"Tu as quitté le groupe automatiquement.",
	L"Tu ne peux pas acheter cet objet, car une extension permanente de cases de compétence est déjà active.",
	L"Tu ne peux pas acheter cet objet, car une extension permanente de cases de compétence est déjà active.",
	L"[CN] 귀하의 계정이 정지되었습니다. 고객 센터에 문의하여 주십시요.",
	L"[CN] 비밀번호를 잘못 입력 하셨습니다. 다시 입력해 주십시요.",
	L"[CN] 해당 계정은 존재하지 않습니다.",
	L"[CN] 불명확인 시스템 에러",
	L"Tu as déjà une médaille de bénédiction dans ton inventaire, c'est pourquoi tu ne peux pas ouvrir le cube.",
	L"Ton niveau est trop faible pour acquérir cet objet.",
	L"Ton niveau est trop faible pour obtenir cette marchandise.",
	L"La création de groupe a échoué !",
	L"Pas suffisamment de membres de groupe.",
	L"Retard de réponse des membres du groupe invités.",
	L"Cette marchandise n'est pas à vendre.",
	L"[JP] 한게임 빌링 오류로 구매할수 없습니다.",
	L"Les objets du système de compte commun ne peuvent pas être envoyés par message.",
	L"Les objets du système de compte commun ne peuvent pas être vendus.",
	L"Cet objet n'est disponible qu'à partir du niveau 20.",
	L"Seuls les personnages qui sont membres d'une guilde peuvent l'échanger.",
	L"Ne peut être acquis qu'à partir du niveau 30.",
	L"Les demandes de participation aux groupes JcJ ne peuvent être effectuées qu'avec le patch complet.",
	L"블랙리스트에 등록된 DLL 이 존재합니다.",
	L"Connecte-toi à nouveau ou réessaye plus tard.",
	L"Tu ne peux plus participer au quiz aujourd'hui.",
	L"Erreur inconnue",
	L"Tu ne peux pas acquérir d'objets pendant la limitation du commerce.",
	L"Ne peut être utilisé pendant la limitation du commerce.",
	L"Tu ne peux plus agrandir ta barre de cases raccourci.",
	L"Le personnage a déjà été effacé ou est sur le point de l'être.",
	L"Impossible d'effacer le personnage pour le moment.",
	L"Effacement définitif du personnage impossible pour le moment.",
	L"Ce personnage ne peut pas être effacé définitivement.",
	L"Après avoir été effacé, ce personnage ne pourra pas être rétabli.",
	L"Le rétablissement de personnages est impossible pour l'instant.",
	L"Réessaye plus tard.",
	L"Ce personnage n'existe pas.",
	L"Le personnage n'a pas pu être effacé.",
	L"La modification du nom de la bestiole a échoué.",
	L"La modification est déjà en cours.",
	L"Le jeu a été interrompu.",
	L"Tu n'es pas maître de guilde.",
	L"Les renseignements sur l'objet sont erronés.",
	L"La modification du nom de guilde a échoué !",
	L"Déjà en cours...",
	L"Tu as essayé d'effacer un objet n'existant pas.",
	L"[TW] 낚시대를 장착하지 않았거나, 미끼가 없습니다.",
	L"[TW] 이미 사용중인 낚시터 입니다.",
	L"[TW] 낚시터에 문제가 있습니다. 다른 곳을 이용해 주세요.",
	L"[TW] 낚시 보상에 문제가 발생했습니다.",
	L"L'effacement de l'objet a échoué.",
	L"Seul le maître de guilde a les droits pour modifier le nom de la guilde.",
	L"펫이 있을 때만 사용이 가능합니다. 펫이 없을 경우 일주일 이내에 청약 철회를 하셔야 합니다.",
	L"Le temps de traitement est écoulé, la procédure a été interrompue. Réessaye.",
	L"La modification du nom de guilde a été annulée par l'utilisateur.",
	L"Tu ne peux pas accéder à cet endroit.",
	L"Tu es déjà à cet endroit.",
	L"Cet endroit est déjà plein, tu ne peux pas y entrer.",
	L"Tu ne peux pas accéder à ce lieu, car plusieurs groupes s'y trouvent déjà.",
	L"L'entrée a échoué.",
	L"Les données concernant le lieu où tu veux aller sont erronées.",
	L"Une erreur est survenue pendant que tu pénétrais le lieu.",
	L"Aucune information trouvée sur l'utilisateur dans ce lieu.",
	L"Le lancement du jeu dans un donjon, utilisant la fonction automatique de formation de groupe a échoué.",
	L"Le lancement du jeu dans le donjon a échoué.",
	L"Tu ne peux pas créer de groupe automatiquement pour l'instant.",
	L"Tu ne peux pas créer de groupe automatiquement pour l'instant. Attends un instant.",
	L"Tu as déjà fait une demande de création de groupe automatique.",
	L"La création automatique de groupe a échoué car les données étaient erronées.",
	L"La demande de création de groupe automatique a échoué.",
	L"Tu n'as pas le statut nécessaire pour pouvoir faire une demande de création de groupe automatique.",
	L"1 seul membre est disponible, c'est pourquoi le jeu ne peut pas commencer.",
	L"Un des membres du groupe a annulé.",
	L"Le jeu est annulé car le temps de réponse est écoulé.",
	L"Tu es déjà membre d'un groupe.",
	L"La personne invitée attend déjà d'être acceptée dans un autre groupe.",
	L"Tu n'es membre d'aucun groupe pour l'instant.",
	L"L'élixir secret et le remède miracle se recoupent et ne peuvent donc pas être utilisés.",
	L"ServerSN이 중복 접속 중이다.",
	L"ServerSN 존재하지 않는데 삭제하려한다.",
	L"Cette fonction ne peut pas être utilisée pour le moment.",
	L"넥슨 통합 맵버쉽 계정 인증 상향 조정 필요.",
	L"Ton corps sa atteint ses limites. Tu ne peux pas utiliser la potion secrète.",
	L"Tu n'as pas le niveau requis. Le jeu dans ce donjon ne peut pas commencer.",
	L"[US] 추천받을 대상이 아닙니다.",
	L"[US] 추천인이 이미 3인을 추천하였습니다.",
	L"[US] 추천 가능한 유저가 아닙니다.",
	L"[US] 맞지 않는 아이템을 사용하였습니다.",
	L"L'obtention de cases d'inventaire supplémentaires n'a pas fonctionné. Tu peux avoir au maximum 8 cases de personnage.",
	L"Fin de la création de groupe automatique en raison du démarrage du donjon.",
	L"Un des membres n'a pas accepté le début du jeu.",
	L"La création de groupe automatique a été annulée.",
	L"Un des membres n'a pas accepté le lancement du jeu. La création de groupe automatique a été annulée.",
	L"La création de groupe automatique a fonctionné. Ton nom a été retiré de la liste d'attente.",
	L"Le demande de création de groupe automatique a été retirée. Ton nom a été effacé de la liste.",
	L"La demande de création de groupe automatique a été annulée en raison du départ d'un des membres.",
	L"L'objet n'a pas le niveau requis. Vous ne pouvez pas commencer le donjon.",
	L"La disposition des touches n'a pas pu être sauvegardée.",
	L"Les données concernant la disposition des touches n'ont pas pu être sauvegardées.",
	L"La disposition des touches n'a pas pu être lue.",
	L"La disposition des touches ne peut pas être lue.",
	L"La réponse au commencement du jeu dans le donjon est retardée.",
	L"[US] 추천인 테이블에서 캐릭터 삭제를 실패하였습니다.",
	L"[US] 보안패드 리셋용 질문 및 답변을 입력하지 않았습니다.",
	L"Le joueur n'appartient pas au même groupe.",
	L"Les données de sélection de dialogue n'ont pas pu être sauvegardées.",
	L"Les données de sélection de dialogue n'ont pas pu être lues.",
	L"Certaines données de sélection de dialogue n'ont pas pu être lues.",
	L"Test",
	L"셧다운제에 의하여 게임이용이 차단 됩니다.",
	L"선택적 셧다운제의 의해 게임이용이 차단됩니다.",
	L"통합 맴버십 ATL 2.0 유저가 아니므로 게임이용이 차단 됩니다.",
	L"셧다운제에 의하여 게임이용이 차단 됩니다.",
	L"선택적 셧다운제의 의해 게임이용이 차단됩니다.",
	L"통합 맴버십 ATL 2.0 유저가 아니므로 게임이용이 차단 됩니다.",
	L"Impossible d'ouvrir.",
	L"Le temps d'ouverture est écoulé.",
	L"ServiceID가 잘못 되었습니다.",
	L"캐시 잔액 정보를 찾을 수 없습니다.",
	L"[TW]ServiceCode 가 올바르지 않습니다.",
	L"[TW]정의되지 않은 애러 발생했습니다.",
	L"[TW]시간형식이 잘못되었습니다.",
	L"[TW]Type정보가 잘못되었습니다.",
	L"[TW]이전 상품 구매가 진행 중입니다.",
	L"Ton niveau est trop élevé pour cette quête.",
	L"파라매터 갯수 입력이 잘못되었습니다.",
	L"[JP] 합성제가 없습니다.",
	L"[JP] 없는 아바타를 합성하려고 했습니다.",
	L"[US]월 선물 가능 횟수를 초과하였습니다.",
	L"Ce donjon ne peut être joué que seul.",
	L"Ce donjon n'est pas encore ouvert.",
	L"Le personnage n'a pas été sélectionné correctement.",
	L"Ton personnage ne peut pas s'envoyer de messages.",
	L"Une erreur est survenue sur l'écran d'information de la bestiole.",
	L"Tu ne peux l'utiliser que lorsque tu as appelé la bestiole.",
	L"Ne peux être utilisé que par les jeunes bestioles.",
	L"Ne peut être utilisé que par les petites bestioles.",
	L"Mauvais réglage du nombre de tags",
	L"Il faut au minimum deux membres dans l'équipe pour commencer la partie.",
	L"",
	L"",
	L"",
	L"",
	L"Tu as quitté le donjon.",
	L"Tu as quitté la compétition.",
	L"Tu va être expulsé en raison d'un changement de canal.",
	L"Tu va être expulsé car les mêmes membres du groupe sont présents.",
	L"Tu va être expulsé en raison de l'utilisation d'un objet de déplacement.",
	L"Tu va être expulsé en raison d'une interruption anormale.",
	L"Tu ne peux pas inviter de membres pendant que tu joues un donjon.",
	L"Ce joueur fait déjà partie d'un groupe. Impossible de l'inviter.",
	L"Le joueur est en compétition et ne peut pas être invité.",
	L"Le joueur est dans un donjon et ne peut pas être invité.",
	L"Le joueur n'a pas été trouvé sur ce serveur.",
	L"Tu ne peux plus inviter d'autres membres de groupe.",
	L"Impossible d'inviter des membres pendant une compétition.",
	L"Tu n'as pas le niveau requis pour entrer.",
	L"Tu n'as pas joué les donjons requis pour entrer sur ce champ.",
	L"Tu peux jouer au maximum 30 quêtes simultanément.",
	L"Tu n'as pas assez de PP.",
	L"Un joueur qui utilise la recherche de groupe automatique ne peut pas être invité.",
	L"Tant que la recherche de groupe automatique est active, tu ne peux inviter personne dans ton groupe.",
	L"Tu ne peux pas inviter de joueurs dans l'espace JcJ.",
	L"Tu ne peux pas inviter de joueurs pendant l'entraînement.",
	L"Tu ne peux pas inviter de joueurs pendant la recherche d'adversaires JcJ.",
	L"Tant que tu es inscrit à la recherche de groupe automatique, tu ne peux pas inviter de joueurs manuellement.",
	L"Tant que tu es inscrit à la recherche de groupe automatique, tu ne peux pas inviter de membre de groupe.",
	L"Ton groupe se trouve dans le même champ que toi.",
	L"Ce joueur est candidat pour un autre groupe. Il ne peut pas être invité.",
	L"",
	L"",
	L"Ce pseudo n'existe pas.",
	L"L'ID de groupe du serveur est incorrecte",
	L"",
	L"Impossible d'utiliser le canal de JcJ sans autorisation de participation à la compétition en ligne.",
	L"Pour ouvrir le cube, il te faut des objet set des PP.",
	L"Tu n'as pas assez de PP pour ouvrir le cube.",
	L"Vous allez commencer avec le nombre de membres actuel.",
	L"",
	L"",
	L"",
	L"L'événement est terminé.",
	L"Tu ne peut pas obtenir cet objet avec Ara.",
	L"",
	L"Tu as utilisé le nombre maximal d'échanges.\nAprès la maintenance du 17/01, de nouveaux échanges seront disponibles.",
	L"",
	L"Cet bestiole n'existe pas.",
	L"Cette fonction est déjà active.",
	L"Ne peut être utilisé qu'à partir du stade \"petit\".",
	L"Tu ne peux pas modifier tes cases de compétence pendant que tu attends de commencer un jeu.",
	L"Tu ne te trouves pas au bon endroit. Les informations sur les monstres du champ ne peuvent pas être chargées.",
	L"Tu ne te trouves pas au bon endroit. Les informations sur les monstres du champ ne peuvent pas être chargées.",
	L"L'objet d'extension de cases n'a pas pu être acheté. Tu peux avoir au maximum 30 cases supplémentaires.",
	L"Tu as été exclu du donjon suite à un vote.",
	L"La personne votante n'est pas un joueur réel.",
	L"La personne concernée par le vote n'est pas un joueur réel.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Tu n'as pas assez de PP pour enregistrer une invitation.",
	L"Tu ne peux pas rejoindre cette guilde car elle a atteint son nombre maximal de membres.",
	L"L'invitation n'a pas pu être envoyée.",
	L"La recherche de guilde n'a pas pu être enregistrée.",
	L"Un message d'invitation de guilde existe déjà.",
	L"Une recherche est déjà enregistrée.",
	L"L'invitation n'a pas pu être enregistrée.",
	L"Tu n'as pas assez de PP pour enregistrer une recherche de guilde.",
	L"Aucune invitation de guilde.",
	L"Aucune recherche de guilde.",
	L"Cette guilde n'existe pas.",
	L"Tu n'es pas autorisé à consulter la liste des joueurs invités.",
	L"Nombre d'entrée maximum dans le donjon atteint.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Tu ne possèdes aucune « instruction sur les champs ».",
	L"Ce chapitre n'a pas pu être ajouté.",
	L"Ce chapitre est déjà enregistré.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Erreur lors du calcul du temps VIP.",
	L"",
	L"",
	L"",
	L"",
	L"Le niveau de l'objet ne correspond pas à ce parchemin béni de l'espace-temps.",
	L"Cet objet a déjà été identifié.",
	L"Aucun objet dans l'inventaire.",
	L"Tu n'as pas assez de PP pour identifier cet objet.",
	L"L'identification a échoué.",
	L"Pas assez de parchemins bénis de l'espace-temps.",
	L"Cet objet ne peut pas être identifié.",
	L"",
	L"",
	L"Cet objet ne peut pas être échangé.",
	L"Tu ne disposes pas d'assez de PP pour régler les frais d'échange.",
	L"",
	L"",
	L"",
	L"",
	L"Tu n'as plus d'objets échangeables.",
	L"L'échange a échoué.",
	L"",
	L"",
	L"Les objets ou matériaux à durée limitée ne peuvent pas être échangés.",
	L"Les objets ou matériaux à durée limitée ne peuvent pas être échangés.",
	L"Les conditions ne sont pas remplies.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Achat impossible tant que le compte est bloqué.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Fermeture du programme suite à une erreur dans le fichier CheckKom.xml",
	L"",
	L"Information de scène erronée.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Au moins une des conditions n'est pas remplie. Vérifie si tu as bien appelé une bestiole !",
	L"Au moins une des conditions n'est pas remplie. Vérifie si tu peux utiliser la bestiole !",
	L"Tu as utilisé la potion de transformation de la fée-citrouille d'Halloween !",
	L"Au moins une des conditions n'est pas remplie. Vérifie si le taux de familiarité de la bestiole est bien à 100% !",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Nombre maximum de fois que le donjon a été joué atteint.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"Fermeture du programme en raison d'une modification de données.",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",
	L"",

	L""
};
