-- lua header. UTF-8 인코딩 인식을 위해 이 줄은 지우지 마세요.


-- 기본적으로 튜토리얼, 훈련소, 헤니르시공은 출현하지 않도록 되어 있습니다.


-- 이벤트 몬스터 드롭 테스트
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 1,
	m_iMonsterDropCount = 1,
	m_bIsAdventInBossStage = True,
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_VELDER_MISSION"],
			ADVENT_RATE = 50,
		},
		
		{
			NPC_ID		= NPC_UNIT_ID["NUI_RUBEN_MISSION"],
			ADVENT_RATE = 50,
		},
	},
	
	ADVENT_DUNGEON_TABLE =
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
	},
	
	NO_ADVENT_STAGE_TABLE =
	{
		0,
	},
}



-- 조크 뽀루 이벤트
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 2,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_JOKE_PPORU"],
			ADVENT_RATE = 100,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 페어리 가디언 이벤트
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 3,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_FAIRY_GUARDIAN_RED"],
			ADVENT_RATE = 100,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 산타 클로에 이벤트 
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 4,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_SANTA_CHLOE"],
			ADVENT_RATE = 100,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}


-- 머맨, 워커 이벤트
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 5,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_MERMAN_EVENT"],
			ADVENT_RATE = 50,
		},
		{
			NPC_ID		= NPC_UNIT_ID["NUI_SHADOW_WALKER_EVENT"],
			ADVENT_RATE = 50,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 등교거부몽
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 6,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_REJECTION_MONKEY"],
			ADVENT_RATE = 100,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 김소드(엘소드)
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 7,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_EVENT_CHALLENGER"],
			ADVENT_RATE = 100,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 엘을 훔친 도적
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 8,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_EVENT_EL_THIEF"],
			ADVENT_RATE = 100,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 뱀파이어 링커
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 9,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_VAMPIRE_LINKER"],
			ADVENT_RATE = 70,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_EXPERT"],
	},
	
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}



--다오
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 10,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_EVENT_GOLDEN_DAO"],
			ADVENT_RATE = 50,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_EXPERT"],
	},
	
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}


--배찌

GameEvent:AddEventMonsterInfo
{
	m_iEventID = 11,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_EVENT_BAZZI"],
			ADVENT_RATE = 70,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_EXPERT"],
	},
	
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}


--로우

GameEvent:AddEventMonsterInfo
{
	m_iEventID = 12,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_PVP_HERO_LOW_EVENT"],
			ADVENT_RATE = 30,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_EXPERT"],
	},
	
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

----산타 뽀루---


GameEvent:AddEventMonsterInfo
{
	m_iEventID = 13,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_PPORU_WILLIAM_SANTA"],
			ADVENT_RATE = 30,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_EXPERT"],
	},
	
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}


----불량뽀---


GameEvent:AddEventMonsterInfo
{
	m_iEventID = 14,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_DEFIANCE_PPORU"],
			ADVENT_RATE = 30,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_EXPERT"],
	},
	
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

----타락한 엘 크리스탈----


GameEvent:AddEventMonsterInfo
{
	m_iEventID = 15,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_CORRUPTION_CRYSTAL"],
			ADVENT_RATE = 100,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_EXPERT"],
	},
	
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}


----타락한 손나은 대천사 npc----


GameEvent:AddEventMonsterInfo
{
	m_iEventID = 16,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_EVENT_APINK_LOCKUP"],
			ADVENT_RATE = 20,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_EXPERT"],
	},
	
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

----공존의 축제 - 다크 엘----
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 17,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 

	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_DARK_CRYSTAL"],
			ADVENT_RATE = 100,
		},
	},
	
	---필드-------
	ADVENT_FIELD_TABLE =					-- 몬스터 출현 필드 
	{
		VILLAGE_MAP_ID["VMI_INVALID"],		-- 설정 안하면 모든 필드에 출현
	},
	   
	NO_ADVENT_FIELD_TABLE =					-- 지정된 필드에서는 출현하지 않습니다.(설정 안하면 모든 필드에 출현)
	{
	
	},
	
	---던전---------
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_EXPERT"],
	},
	
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

----공존의 축제 불안정한 엘 ----
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 18,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	m_bAllyNpc = True,				--아군 몬스터 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_CORRUPTION_CRYSTAL"],
			ADVENT_RATE = 100,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_EXPERT"],
	},
	
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

----방황하는 마족의 영혼 ----
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 19,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_WANDERING_SOUL_OF_DEMON"],
			ADVENT_RATE = 30,
		},
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_EXPERT"],
	},
	
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

----폭염 뽀루----
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 21,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_WILLIAM_PPORU_FIRE_EVENT"],	-- 폭염 뽀루
			ADVENT_RATE = 50,
			IS_ACTIVE = FALSE,
		},
		
		{
			NPC_ID		= NPC_UNIT_ID["NUI_WILLIAM_PPORU_FIRE_EVENT2"],	-- 진격의 폭염 뽀루
			ADVENT_RATE = 50,
			IS_ACTIVE = FALSE,
		},
	},
	
	---필드-------
	ADVENT_FIELD_TABLE =               -- 몬스터 출현 필드 
	{
	},
	   
	NO_ADVENT_FIELD_TABLE =      -- 지정된 필드에서는 출현하지 않습니다.(설정 안하면 모든 필드에 출현)
	{
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_RUBEN_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ELDER_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ELDER_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_03"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_03"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_PEITA_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_PEITA_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_PEITA_FIELD_03"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_03"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_04"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_03"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_04"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_SHIP_STAGE"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_SHIP_STAGE"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_03"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_04"],
	},
	
	---던전---------
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_EXPERT"],
	},
	
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 130912/이경철/어둠의 문 시즌 3 개편 이벤트
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 22,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_GHOST_PPORU"],	-- 다크엘프 스나이퍼
			ADVENT_RATE = 10,
			IS_ACTIVE = FALSE,
		},
		
		{
			NPC_ID		= NPC_UNIT_ID["NUI_FLAME_RED_EVENT"],	-- 글리터 정예 돌격병
			ADVENT_RATE = 10,
			IS_ACTIVE = FALSE,
		},
		
		{
			NPC_ID		= NPC_UNIT_ID["NUI_FLAME_BLUE_EVENT"],	-- 정예 코카트리글
			ADVENT_RATE = 10,
			IS_ACTIVE = FALSE,
		},
		
		{
			NPC_ID		= NPC_UNIT_ID["NUI_JOKE_PPORU"],	-- 포트 쉐도우 스팅어
			ADVENT_RATE = 10,
			IS_ACTIVE = FALSE,
		},
	},
	
	---필드-------
	ADVENT_FIELD_TABLE =               -- 몬스터 출현 필드 
	{
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ELDER_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ELDER_FIELD_02"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_03"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_03"],
	},
	   
	NO_ADVENT_FIELD_TABLE =      -- 지정된 필드에서는 출현하지 않습니다.(설정 안하면 모든 필드에 출현)
	{
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_RUBEN_FIELD_01"],
	},
	
	---던전---------
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
			DUNGEON_ID["DI_END"],
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{

	},
	
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 130926/이경철/결혼 이벤트
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 23,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_JOKE_PPORU2"],	-- 턱시도 뽀루
			ADVENT_RATE = 30,
			IS_ACTIVE = FALSE,
		},
		{
			NPC_ID		= NPC_UNIT_ID["NUI_JOKE_PPORU"],	-- 드레스 뽀루
			ADVENT_RATE = 30,
			IS_ACTIVE = FALSE,
		},
	},
	
	---필드-------
	ADVENT_FIELD_TABLE =               -- 몬스터 출현 필드 
	{
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ELDER_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ELDER_FIELD_02"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_03"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_03"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_PEITA_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_PEITA_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_PEITA_FIELD_03"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_03"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_04"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_03"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_04"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_SHIP_STAGE"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_SHIP_STAGE"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_03"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_04"],
	},
	   
	NO_ADVENT_FIELD_TABLE =      -- 지정된 필드에서는 출현하지 않습니다.(설정 안하면 모든 필드에 출현)
	{
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_RUBEN_FIELD_01"],
	},
	
	---던전---------
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
			DUNGEON_ID["DI_END"],
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{

	},
	
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 131023/이경철/마법의 스프
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 24,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	--m_bAllyNpc = True,				--아군 몬스터 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_JOKE_PPORU"],
			ADVENT_RATE = 50,
		},
	},
	
	m_iAddLevel 	= 0,      		   -- 몬스터 레벨
	m_bDrop			= True,            -- 드롭 여부 / true = 드롭 함
	--m_bAggressive	= True,  		   -- 선/비 선공 / true = 선공
	--m_fAddPosY 		= 0.0,         -- 몬스터 높이값 설치 
	
	
	---필드-------
	ADVENT_FIELD_TABLE =					-- 몬스터 출현 필드 
	{
		VILLAGE_MAP_ID["VMI_INVALID"],		-- 설정 안하면 모든 필드에 출현
	},
	   
	NO_ADVENT_FIELD_TABLE =					-- 지정된 필드에서는 출현하지 않습니다.(설정 안하면 모든 필드에 출현)
	{
	
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_EXPERT"],	

		DUNGEON_ID["DI_ELDER_SECRET_COMMON"],
		DUNGEON_ID["DI_ELDER_SECRET_HELL"],
		DUNGEON_ID["DI_BESMA_SECRET_COMMON"],
		DUNGEON_ID["DI_BESMA_SECRET_HELL"],
		DUNGEON_ID["DI_ALTERA_SECRET_COMMON"],
		DUNGEON_ID["DI_ALTERA_SECRET_HELL"],
		DUNGEON_ID["DI_VELDER_SECRET_COMMON"],
		DUNGEON_ID["DI_VELDER_SECRET_HELL"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 131212/임홍락/란 짜응
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 25,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	--m_bAllyNpc = True,				--아군 몬스터 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_FLAME_RED_EVENT"],
			ADVENT_RATE = 50,
			IS_ACTIVE = FALSE,
		},
	},
	
	m_iAddLevel 	= 0,      		   -- 몬스터 레벨
	m_bDrop			= True,            -- 드롭 여부 / true = 드롭 함
	--m_bAggressive	= True,  		   -- 선/비 선공 / true = 선공
	--m_fAddPosY 		= 0.0,         -- 몬스터 높이값 설치 
	
	
	---필드-------
	ADVENT_FIELD_TABLE =					-- 몬스터 출현 필드 
	{
		VILLAGE_MAP_ID["VMI_INVALID"],		-- 설정 안하면 모든 필드에 출현
	},
	   
	NO_ADVENT_FIELD_TABLE =					-- 지정된 필드에서는 출현하지 않습니다.(설정 안하면 모든 필드에 출현)
	{
	
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_EXPERT"],	

		DUNGEON_ID["DI_ELDER_SECRET_COMMON"],
		DUNGEON_ID["DI_ELDER_SECRET_HELL"],
		DUNGEON_ID["DI_BESMA_SECRET_COMMON"],
		DUNGEON_ID["DI_BESMA_SECRET_HELL"],
		DUNGEON_ID["DI_ALTERA_SECRET_COMMON"],
		DUNGEON_ID["DI_ALTERA_SECRET_HELL"],
		DUNGEON_ID["DI_VELDER_SECRET_COMMON"],
		DUNGEON_ID["DI_VELDER_SECRET_HELL"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 131212/임홍락/란 짜응
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 26,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_FLAME_BLUE_EVENT"],	-- 턱시도 뽀루
			ADVENT_RATE = 30,
			IS_ACTIVE = FALSE,
		},
	},
	
	---필드-------
	ADVENT_FIELD_TABLE =               -- 몬스터 출현 필드 
	{
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ELDER_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ELDER_FIELD_02"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_03"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_03"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_PEITA_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_PEITA_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_PEITA_FIELD_03"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_03"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_04"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_03"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_04"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_SHIP_STAGE"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_SHIP_STAGE"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_03"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_04"],
	},
	   
	NO_ADVENT_FIELD_TABLE =      -- 지정된 필드에서는 출현하지 않습니다.(설정 안하면 모든 필드에 출현)
	{
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_RUBEN_FIELD_01"],
	},
	
	---던전---------
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
			DUNGEON_ID["DI_END"],
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{

	},
	
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 131212/임홍락/란 짜응/2차 전직 World War 이벤트 테스트용
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 27,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	--m_bAllyNpc = True,				--아군 몬스터 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_JOKE_PPORU"],
			ADVENT_RATE = 100,
			IS_ACTIVE = FALSE,
		},
	},
	
	m_iAddLevel 	= 0,      		   -- 몬스터 레벨
	m_bDrop			= True,            -- 드롭 여부 / true = 드롭 함
	--m_bAggressive	= True,  		   -- 선/비 선공 / true = 선공
	--m_fAddPosY 		= 0.0,         -- 몬스터 높이값 설치 
	
	
	---필드-------
	ADVENT_FIELD_TABLE =					-- 몬스터 출현 필드 
	{
		VILLAGE_MAP_ID["VMI_INVALID"],		-- 설정 안하면 모든 필드에 출현
	},
	   
	NO_ADVENT_FIELD_TABLE =					-- 지정된 필드에서는 출현하지 않습니다.(설정 안하면 모든 필드에 출현)
	{
	
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_EXPERT"],	

		DUNGEON_ID["DI_ELDER_SECRET_COMMON"],
		DUNGEON_ID["DI_ELDER_SECRET_HELL"],
		DUNGEON_ID["DI_BESMA_SECRET_COMMON"],
		DUNGEON_ID["DI_BESMA_SECRET_HELL"],
		DUNGEON_ID["DI_ALTERA_SECRET_COMMON"],
		DUNGEON_ID["DI_ALTERA_SECRET_HELL"],
		DUNGEON_ID["DI_VELDER_SECRET_COMMON"],
		DUNGEON_ID["DI_VELDER_SECRET_HELL"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 140115/이경철/춘절 이벤트
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 28,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_EVENT_DUMPLING_THIEF_PHORU"],
			ADVENT_RATE = 100,
		},
	},
	
	m_iAddLevel 	= 0,      		   -- 몬스터 레벨
	m_bDrop			= True,            -- 드롭 여부 / true = 드롭 함
	
	---필드-------
	ADVENT_FIELD_TABLE =					-- 몬스터 출현 필드 
	{
			VILLAGE_MAP_ID["VMI_INVALID"],		-- 설정 안하면 모든 필드에 출현
	},
	   
	NO_ADVENT_FIELD_TABLE =					-- 지정된 필드에서는 출현하지 않습니다.(설정 안하면 모든 필드에 출현)
	{

	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
	
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_EXPERT"],	
		
		DUNGEON_ID["DI_ELDER_SECRET_COMMON"],
		DUNGEON_ID["DI_ELDER_SECRET_HELL"],
		DUNGEON_ID["DI_BESMA_SECRET_COMMON"],
		DUNGEON_ID["DI_BESMA_SECRET_HELL"],
		DUNGEON_ID["DI_ALTERA_SECRET_COMMON"],
		DUNGEON_ID["DI_ALTERA_SECRET_HELL"],
		DUNGEON_ID["DI_VELDER_SECRET_COMMON"],
		DUNGEON_ID["DI_VELDER_SECRET_HELL"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 140212/원소절 이벤트 (던전)
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 29,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	--m_bAllyNpc = True,				--아군 몬스터 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_EVENT_INT_MOON"],
			ADVENT_RATE = 100,
			IS_ACTIVE = FALSE,
		},
	},
	
	m_iAddLevel 	= 0,      		   -- 몬스터 레벨
	m_bDrop			= True,            -- 드롭 여부 / true = 드롭 함
	--m_bAggressive	= True,  		   -- 선/비 선공 / true = 선공
	--m_fAddPosY 		= 0.0,         -- 몬스터 높이값 설치 
	
	
	---필드-------
	ADVENT_FIELD_TABLE =					-- 몬스터 출현 필드 
	{
		VILLAGE_MAP_ID["VMI_INVALID"],		-- 설정 안하면 모든 필드에 출현
	},
	   
	NO_ADVENT_FIELD_TABLE =					-- 지정된 필드에서는 출현하지 않습니다.(설정 안하면 모든 필드에 출현)
	{
	
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_BESMA_HENIR_SPACE"],
		DUNGEON_ID["DI_ALTERA_HENIR_SPACE"],
		DUNGEON_ID["DI_FEITA_HENIR_SPACE"],
		DUNGEON_ID["DI_VELDER_HENIR_SPACE"],
		DUNGEON_ID["DI_HAMEL_HENIR_SPACE"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_BESMA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ALTERA_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_PEITA_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_VELDER_EXPERT"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_HAMEL_EXPERT"],	

		DUNGEON_ID["DI_ELDER_SECRET_COMMON"],
		DUNGEON_ID["DI_ELDER_SECRET_HELL"],
		DUNGEON_ID["DI_BESMA_SECRET_COMMON"],
		DUNGEON_ID["DI_BESMA_SECRET_HELL"],
		DUNGEON_ID["DI_ALTERA_SECRET_COMMON"],
		DUNGEON_ID["DI_ALTERA_SECRET_HELL"],
		DUNGEON_ID["DI_VELDER_SECRET_COMMON"],
		DUNGEON_ID["DI_VELDER_SECRET_HELL"],
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}
-- 140212/원소절 이벤트 (필드)
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 30,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	--m_bAllyNpc = True,				--아군 몬스터 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_EVENT_INT_MOON"],
			ADVENT_RATE = 30,
			IS_ACTIVE = FALSE,
		},
	},
	
	m_iAddLevel 	= 0,      		   -- 몬스터 레벨
	m_bDrop			= True,            -- 드롭 여부 / true = 드롭 함
	--m_bAggressive	= True,  		   -- 선/비 선공 / true = 선공
	--m_fAddPosY 		= 0.0,         -- 몬스터 높이값 설치 
	
	
	---필드-------
	ADVENT_FIELD_TABLE =               -- 몬스터 출현 필드 
	{
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ELDER_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ELDER_FIELD_02"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_BESMA_FIELD_03"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_ALTERA_FIELD_03"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_PEITA_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_PEITA_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_PEITA_FIELD_03"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_03"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_FIELD_04"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_03"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_FIELD_04"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_VELDER_SHIP_STAGE"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_HAMEL_SHIP_STAGE"],
		
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_01"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_02"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_03"],
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_SANDER_FIELD_04"],
	},
	   
	NO_ADVENT_FIELD_TABLE =      -- 지정된 필드에서는 출현하지 않습니다.(설정 안하면 모든 필드에 출현)
	{
		VILLAGE_MAP_ID["VMI_BATTLE_FIELD_RUBEN_FIELD_01"],
	},
	
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
			DUNGEON_ID["DI_END"],
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
	},
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}

-- 140219/박필홍/샌더5,6  이벤트(던전 출현)
GameEvent:AddEventMonsterInfo
{
	m_iEventID = 31,
	m_iMonsterDropCount = 1,		--던전에 출현하는 마리수 
	m_bIsAdventInBossStage = False,  --보스 스테이지에서 출현 시킬껀지 
	
	ADVENT_NPC_TABLE =
	{
		{
			NPC_ID		= NPC_UNIT_ID["NUI_EVENT_SANDER_SAND"],	-- 모래 더미
			ADVENT_RATE = 100,
			IS_ACTIVE = FALSE,
		},
		
	},
	
	---필드-------
	ADVENT_FIELD_TABLE =               -- 몬스터 출현 필드 
	{
		VILLAGE_MAP_ID["VMI_INVALID"],		-- 설정 안하면 모든 필드에 출현
	},
	   
	NO_ADVENT_FIELD_TABLE =      -- 지정된 필드에서는 출현하지 않습니다.(설정 안하면 모든 필드에 출현)
	{

	},
	
	---던전---------
	ADVENT_DUNGEON_TABLE = --나오는 던전
	{
	
	},
	
	NO_ADVENT_DUNGEON_TABLE =  --안나오는 던전
	{
		DUNGEON_ID["DI_RUBEN_EL_TREE_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_NORMAL"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_HARD"],
		DUNGEON_ID["DI_RUBEN_RUIN_OF_ELF_EXPERT"],
		DUNGEON_ID["DI_RUBEN_SWAMP_NORMAL"],
		DUNGEON_ID["DI_RUBEN_SWAMP_HARD"],
		DUNGEON_ID["DI_RUBEN_SWAMP_EXPERT"],
		
		DUNGEON_ID["DI_ELDER_HENIR_SPACE"],
				
		DUNGEON_ID["DI_SANDER_DRY_SANDER_NORMAL"],
		DUNGEON_ID["DI_SANDER_DRY_SANDER_HARD"],
		DUNGEON_ID["DI_SANDER_DRY_SANDER_EXPERT"],
		DUNGEON_ID["DI_SANDER_GARPAI_ROCK_NORMAL"],
		DUNGEON_ID["DI_SANDER_GARPAI_ROCK_HARD"],
		DUNGEON_ID["DI_SANDER_GARPAI_ROCK_EXPERT"],
		DUNGEON_ID["DI_SANDER_DEN_OF_TROCK_NORMAL"],
		DUNGEON_ID["DI_SANDER_DEN_OF_TROCK_HARD"],
		DUNGEON_ID["DI_SANDER_DEN_OF_TROCK_EXPERT"],
		DUNGEON_ID["DI_SANDER_KARUSO_VILLAGE_NORMAL"],
		DUNGEON_ID["DI_SANDER_KARUSO_VILLAGE_HARD"],
		DUNGEON_ID["DI_SANDER_KARUSO_VILLAGE_EXPERT"],
		DUNGEON_ID["DI_SANDER_SANTILUS_SHIP_NORMAL"],
		DUNGEON_ID["DI_SANDER_SANTILUS_SHIP_HARD"],
		DUNGEON_ID["DI_SANDER_SANTILUS_SHIP_EXPERT"],
		DUNGEON_ID["DI_SANDER_BEHIMOSS_HEART_NORMAL"],
		DUNGEON_ID["DI_SANDER_BEHIMOSS_HEART_HARD"],
		DUNGEON_ID["DI_SANDER_BEHIMOSS_HEART_EXPERT"],
		
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_NORMAL"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_HARD"],
		DUNGEON_ID["DI_DEFENCE_DUNGEON_ELDER_EXPERT"],
				
	},
	
	
	NO_ADVENT_STAGE_TABLE = --안나오는 스테이지 
	{
		0,
	},
}